using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using BaseFixture=AreaBattle.EditorTools.OutgameAudioPlaybackValidation.Fixture;
namespace AreaBattle.EditorTools
{
    public static class OutgameAudioFadeValidation
    {
        public sealed class Timer
        {
            public int Id,Duration;public Action<int> Complete;public Action<int,int> Every;
        }
        public sealed class Fixture:IDisposable
        {
            public readonly BaseFixture Base;public readonly List<Timer> Timers=new List<Timer>();public readonly List<int> Removed=new List<int>();public Action<int> Removing;public Action Scheduling;
            public Fixture(bool native=false){Base=new BaseFixture(native);Base.Services.SetCountDownByMillisecond=(duration,finish,every)=>{Scheduling?.Invoke();var t=new Timer{Id=Timers.Count+1,Duration=duration,Complete=finish,Every=every};Timers.Add(t);Base.Calls.Add("timer:"+t.Id);return t.Id;};Base.Services.RemoveTime=id=>{Removing?.Invoke(id);Removed.Add(id);Base.Calls.Add("remove-time:"+id);};}
            public OutgameAudioFadeBase Create(bool loop=false)=>loop?new OutgameAudioLoopFadeAction(Base.Root,Base.Data.id,g=>Base.Started++,g=>{Base.Ended++;Base.Calls.Add("end");},Base.Services):new OutgameAudioFadeAction(Base.Root,Base.Data.id,g=>Base.Started++,g=>{Base.Ended++;Base.Calls.Add("end");},Base.Services);
            public Timer Last=>Timers[Timers.Count-1];public void Complete()=>Last.Complete(Last.Id);public void Every(int remaining)=>Last.Every(Last.Id,remaining);
            public void Dispose(){OutgameAudioActionFactory.Override=null;Base.Dispose();}
        }
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static bool Near(float a,float b)=>Mathf.Abs(a-b)<.00001f;static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-audio-fade-play-native-source-and-countdown",()=>{using(var f=new Fixture()){var a=f.Create();a.Play();Require(a.AudioSource&&!a.AudioSource.loop&&a.AudioSource.volume==0&&a.AudioSource.name=="fade_"+a.Guid&&Near(a.FadeVolume,.5f)&&a.ClipLength==f.Base.Clip.length&&a.FadeMilliseconds==1000&&f.Last.Duration==1000&&a.TimerId==1&&f.Base.Started==1,"source setup -> Play -> length -> timer -> base start");a.Dispose();}});
            check("source-audio-fade-countdown-remaining-and-live-volume",()=>{using(var f=new Fixture()){var a=f.Create(true);a.Play();f.Every(750);Require(Near(a.AudioSource.volume,.125f),"remaining750 =>25% of captured target");f.Base.Settings.SetMusicGameVolume(OutgameVoiceType.Music,.4f);Require(Near(a.FadeVolume,.2f)&&Near(a.AudioSource.volume,.2f),"volume event writes target and immediate native volume");f.Every(500);Require(Near(a.AudioSource.volume,.1f),"next callback uses live target");f.Complete();Require(Near(a.AudioSource.volume,.2f)&&a.TimerId==1&&f.Removed.Count==1&&f.Base.Ended==0&&a.AudioSource.loop&&a.AudioSource.name=="loopFade_"+a.Guid,"fade-in completion removes passed id, retains field, sets live target, no end");a.Dispose();}});
            check("source-audio-fade-stop-double-setting-and-complete-order",()=>{using(var f=new Fixture()){f.Base.NewResources=true;f.Base.Settings.MusicGameVolume=.4f;var a=f.Create();a.Play();f.Complete();a.Stop();Require(a.Stopping&&Near(a.FadeVolume,.08f)&&a.TimerId==2,"Stop re-multiplies native .2 volume by .4 setting");f.Every(500);Require(Near(a.AudioSource.volume,.04f),"fade-out uses remaining fraction");f.Base.Calls.Clear();f.Complete();Require(string.Join(",",f.Base.Calls)=="remove-time:2,end,release,remove,remove-time:2,destroy,unload:"+f.Base.Data.ResPath&&!a.Stopping&&a.TimerId==2&&a.ResourceHandle!=null&&!a.AudioSource,"completion remove -> end -> release -> Dispose repeated remove -> destroy/unload -> stopping false");}});
            check("source-audio-fade-second-stop-disposes-without-end",()=>{using(var f=new Fixture()){f.Base.NewResources=true;var a=f.Create();a.Play();f.Complete();a.Stop();a.Stop();Require(f.Base.Ended==0&&a.Stopping&&!a.AudioSource&&a.Data==null&&f.Base.Provider.Releases==1,"repeat Stop takes direct release/Dispose branch with no end and no flag reset");}});
            check("source-audio-fade-stop-before-play-retains-first-call",()=>{using(var f=new Fixture()){var a=f.Create();a.Stop();Require(a.Stopping&&a.UpdateId!=0&&f.Timers.Count==0&&f.Base.Ended==0,"null source fade helper does nothing after stopping flag");a.Stop();Require(a.UpdateId==0&&a.Stopping&&f.Base.Ended==0,"second call disposes without callback");}});
            check("source-audio-fade-volume-event-during-await-updates-target",()=>{using(var f=new Fixture()){var pending=new TaskCompletionSource<AudioClip>();f.Base.Services.LoadAudioClip=p=>pending.Task;var a=f.Create();a.Play();f.Base.Settings.SetMusicGameVolume(OutgameVoiceType.Music,.2f);pending.SetResult(f.Base.Clip);f.Base.Context.Pump();f.Every(500);Require(Near(a.FadeVolume,.1f)&&Near(a.AudioSource.volume,.05f),"fade target stored before await and remains live for event updates, unlike captured loop volume");a.Dispose();}});
            check("source-audio-fade-paused-source-does-not-pause-countdown",()=>{using(var f=new Fixture()){var a=f.Create();a.Play();a.Pause(true);f.Every(250);Require(Near(a.AudioSource.volume,.375f),"empty pause hook does not suppress fade callbacks");a.Dispose();}});
            check("source-audio-fade-destroyed-source-still-completes-out-callback",()=>{using(var f=new Fixture()){var a=f.Create();a.Play();f.Complete();a.Stop();UnityEngine.Object.DestroyImmediate(a.AudioSource.gameObject);f.Every(500);f.Complete();Require(f.Base.Ended==1&&!a.Stopping&&a.Data==null&&a.UpdateId==0,"destroyed captured source skips volume, still invokes fade-out completion and disposal");}});
            check("source-audio-fade-completion-remove-failure-stops-callback",()=>{using(var f=new Fixture()){var a=f.Create();a.Play();f.Every(500);f.Removing=id=>throw new InvalidOperationException();Throws<InvalidOperationException>(f.Complete);Require(Near(a.AudioSource.volume,.25f)&&f.Base.Ended==0&&a.UpdateId!=0,"remove failure precedes target volume and completion");f.Removing=null;a.Dispose();}});
            check("source-audio-fade-scheduling-failure-retains-created-child",()=>{using(var f=new Fixture()){f.Scheduling=()=>throw new InvalidOperationException();var a=f.Create();a.Play();f.Base.Context.Pump();Require(f.Base.Context.Errors.Count==1&&!a.AudioSource&&f.Base.Root.GetComponentsInChildren<AudioSource>().Length==1&&f.Base.Started==0&&a.TimerId==0&&a.Data!=null,"source played before timer registration failure; base await never receives child");a.Dispose();}});
            check("source-audio-fade-release-failure-retains-stopping-flag",()=>{using(var f=new Fixture()){f.Base.NewResources=true;var a=f.Create();a.Play();f.Complete();a.Stop();f.Base.Provider.Releasing=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(f.Complete);Require(f.Base.Ended==1&&a.Stopping&&a.UpdateId!=0&&a.Data!=null,"end commits, release failure skips Dispose and flag reset");f.Base.Provider.Releasing=null;a.Stop();Require(f.Base.Ended==1&&a.Stopping&&a.UpdateId==0,"retry Stop disposes without a second end");}});
            check("source-audio-fade-explicit-end-repeated-update-disposes",()=>{using(var f=new Fixture()){f.Base.Data.EndTime=1;var a=f.Create();a.Play();f.Base.Tick();Require(a.Stopping&&f.Timers.Count==2,"time0 reaches End1 minus fade1 even without isPlaying gate");f.Base.Tick();Require(!a.AudioSource&&a.Stopping&&f.Base.Ended==0&&a.UpdateId==0,"explicit EndTime branch has no stopping gate; next update executes second-stop disposal");}});
            check("source-audio-loopfade-explicit-end-reschedules-every-update",()=>{using(var f=new Fixture()){f.Base.Data.EndTime=1;var a=f.Create(true);a.Play();f.Base.Tick();f.Base.Tick();Require(a.Stopping&&a.TimerId==3&&f.Timers.Count==3&&f.Removed.Contains(2),"positive EndTime cancels/replaces fade-out on each update");f.Complete();Require(!a.Stopping&&a.TimerId==4&&f.Base.Ended==0&&a.AudioSource&&a.AudioSource.time<.1f,"loop fade-out completion starts fade-in, no stop/end or cursor seek");a.Dispose();}});
            check("source-audio-fade-null-clip-and-repeated-dispose",()=>{using(var f=new Fixture()){f.Base.Clip=null;var a=f.Create();a.Play();Require(!a.AudioSource&&f.Timers.Count==0&&a.Data!=null&&f.Base.Ended==0,"null clip returns without countdown, log or disposal");a.Dispose();a.Dispose();Require(a.UpdateId==0&&f.Base.Calls.FindAll(c=>c=="destroy").Count==2,"base repeated Dispose still invokes source cleanup");}});
            check("source-audio-fade-dispose-removal-failure-keeps-source",()=>{using(var f=new Fixture()){var a=f.Create();a.Play();f.Removing=id=>throw new InvalidOperationException();Throws<InvalidOperationException>(a.Dispose);Require(a.UpdateId==0&&a.AudioSource&&a.Data!=null&&a.TimerId==1,"update/listener removal precedes timer failure; source and data not cleared");f.Removing=null;a.Dispose();}});
            check("source-audio-factory-four-types-default-and-invalid",()=>{using(var f=new Fixture()){var factory=new OutgameAudioActionFactory(f.Base.Services);Type[] types={typeof(OutgameAudioOnceAction),typeof(OutgameAudioLoopAction),typeof(OutgameAudioFadeAction),typeof(OutgameAudioLoopFadeAction)};for(int i=1;i<=4;i++){var a=(OutgameAudioAction)factory.Create(f.Base.Root,i,1002,null,null);Require(a.GetType()==types[i-1],"allocated source type"+i);a.Dispose();}Require(factory.Create(f.Base.Root,0,1002,null,null)==null&&factory.Create(f.Base.Root,5,1002,null,null)==null,"invalid type null");f.Base.Data.Ptype=4;Require(factory.GetAudioType(1002)==4,"Ptype copied");f.Base.Data=null;Require(factory.GetAudioType(999)==1,"missing config defaults Once");}});
            check("source-audio-factory-override-before-switch-and-throw",()=>{using(var f=new Fixture()){var factory=new OutgameAudioActionFactory(f.Base.Services);var custom=f.Base.Once();int calls=0;Action<int> start=g=>{},end=g=>{};OutgameAudioActionFactory.Override=(root,type,id,s,e)=>{calls++;Require(root==f.Base.Root&&(int)type==999&&id==42&&s==start&&e==end,"override receives original values");return custom;};Require(ReferenceEquals(factory.Create(f.Base.Root,999,42,start,end),custom)&&calls==1,"nonnull override bypasses even invalid constructor type");OutgameAudioActionFactory.Override=(root,type,id,s,e)=>null;var fallback=(OutgameAudioAction)factory.Create(f.Base.Root,2,1002,null,null);Require(fallback is OutgameAudioLoopAction,"null override falls back");fallback.Dispose();OutgameAudioActionFactory.Override=(root,type,id,s,e)=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>factory.Create(f.Base.Root,1,1002,null,null));custom.Dispose();}});
            check("source-audio-parallel-concrete-factory-fade-end-removes-guid",()=>{using(var f=new Fixture()){var factory=new OutgameAudioActionFactory(f.Base.Services);f.Base.Data.Ptype=4;var node=new OutgameAudioParallel(f.Base.Root,17,"concrete-fade-node",factory.GetAudioType,factory.Create,()=>f.Base.Messages,UnityEngine.Object.DestroyImmediate);int ends=0;f.Base.Messages.AddListener("AudioPlayEnd",args=>ends++);var ids=node.Play(new[]{1002});Require(ids.Length==1&&node.Actions[ids[0]] is OutgameAudioLoopFadeAction&&node.Actions[ids[0]].AudioSource,"real node -> source type -> actual loaded native source -> start registration");f.Complete();node.StopByGuid(ids[0]);f.Complete();Require(ends==1&&node.Actions.Count==0&&f.Base.Updates.Count==0,"timer complete -> action end -> parallel remove -> global end -> Dispose");node.Destroy();}});
            return r;
        }
    }
}
