using System;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameTimeModuleValidation
    {
        sealed class Fixture:IDisposable
        {
            readonly DateTime start=OutgameTimeClock.StartTime,now=OutgameTimeClock.Now;readonly bool focus=OutgameTimeClock.IsFocus;
            public readonly OutgameMessageDispatcher Messages=new OutgameMessageDispatcher();public readonly List<string> Logs=new List<string>(),Warnings=new List<string>();public readonly OutgameTimeModule Time;
            public Fixture(){OutgameTimeClock.IsFocus=true;Time=new OutgameTimeModule(()=>Messages,a=>Logs.Add((string)a[0]),a=>Warnings.Add((string)a[0]),()=>OutgameTimeClock.DefaultTime);Time.Initialize();}
            public void Dispose(){OutgameTimeClock.StartTime=start;OutgameTimeClock.Now=now;OutgameTimeClock.IsFocus=focus;}
        }
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-time-module-initialize-callback-committed-and-shared-id",()=>{using(var f=new Fixture()){var t=f.Time;int calls=0;t.Initialized=()=>{Require(t.IsInitialized&&t.UnityTimers.Count==0&&t.TimeId==0,"callback sees initialized maps");calls++;throw new InvalidOperationException();};Throws<InvalidOperationException>(t.Initialize);Require(calls==1&&t.IsInitialized&&t.Priority==60,"callback failure retains initialized flag");Require(t.SetCountDownByMillisecond(1,i=>{},null)==1&&t.AddLoopTimer(1,false,true,false,i=>{})==2&&t.AddUnityTimer(1,true,null,null,null)==3&&t.AddUnityEverySecondTimer(true,null)==4,"all three source timer families share id");}});
            check("source-loop-false-autoplay-still-starts-and-log-excludes-queued",()=>{using(var f=new Fixture()){int calls=0;int id=f.Time.AddLoopTimer(1,false,true,false,i=>calls++);Require(f.Time.LoopTimers.Count==0&&f.Logs[0].EndsWith("0"),"queued not counted");f.Time.CheckLoopTimer(1,1);Require(calls==1&&!f.Time.LoopTimers[id].Paused,"source default pause=false despite AutoPlay false");}});
            check("source-loop-remove-before-first-add-warns-but-still-activates",()=>{using(var f=new Fixture()){int calls=0;int id=f.Time.AddLoopTimer(1,false,true,true,i=>calls++);f.Time.RemoveLoopTimer(id,null);f.Time.CheckLoopTimer(1,1);Require(calls==1&&f.Warnings.Count==1&&f.Time.LoopTimers.ContainsKey(id),"removals process before pending additions");}});
            check("source-loop-two-passes-all-timers-advance-before-first-callback",()=>{using(var f=new Fixture()){float observed=0;int second=0;f.Time.AddLoopTimer(1,false,true,true,i=>observed=f.Time.LoopTimers[second].Elapsed);second=f.Time.AddLoopTimer(5,false,true,true,i=>{});f.Time.CheckLoopTimer(1,1);Require(observed==1,"distinct AddTimes and Check passes");}});
            check("source-loop-callback-add-remove-deferred-until-next-check",()=>{using(var f=new Fixture()){int child=0,calls=0;int id=0;id=f.Time.AddLoopTimer(1,false,true,true,i=>{child=f.Time.AddLoopTimer(1,false,true,true,j=>calls++);f.Time.RemoveLoopTimer(id,null);});f.Time.CheckLoopTimer(1,1);var original=f.Time.LoopTimers[id];Require(calls==0&&f.Time.LoopTimers.ContainsKey(id)&&!f.Time.LoopTimers.ContainsKey(child),"queued during callback");f.Time.CheckLoopTimer(1,1);Require(calls==1&&!f.Time.LoopTimers.ContainsKey(id)&&original.IntCallback==null,"next pass destroys removed callbacks then activates child");}});
            check("source-loop-scaled-spike-and-unscaled-spike-asymmetry",()=>{using(var f=new Fixture()){int a=0,b=0;int first=f.Time.AddLoopTimer(1,false,true,true,i=>a++),second=f.Time.AddLoopTimer(1,false,false,true,i=>b++);f.Time.CheckLoopTimer(3,3);Require(a==1&&b==0&&f.Time.LoopTimers[first].TotalTime==3&&f.Time.LoopTimers[first].Elapsed==0&&f.Time.LoopTimers[second].TotalTime==0,"scaled spike accepted once and remainder dropped; unscaled spike ignored");f.Time.CheckLoopTimer(-.5f,-.5f);Require(f.Time.LoopTimers[second].Elapsed==-.5f,"negative delta not clamped");}});
            check("source-loop-check-not-gated-by-pause-or-focus",()=>{using(var f=new Fixture()){int calls=0,id=f.Time.AddLoopTimer(0,false,true,true,i=>calls++);f.Time.CheckLoopTimer(0,0);f.Time.PauseLoopTimer(id,null);OutgameTimeClock.IsFocus=false;f.Time.CheckLoopTimer(1,1);Require(calls==2&&f.Time.LoopTimers[id].TotalTime==0,"AddTimes gated, Check still invokes step zero");}});
            check("source-loop-pause-reset-and-total-value-semantics",()=>{using(var f=new Fixture()){var t=f.Time;int got=-1,id=t.AddLoopTimer(2,false,true,true,i=>{});t.CheckLoopTimer(3.75f,0);Require(t.GetLoopTimerValue(id)==3&&t.LoopTimers[id].Elapsed==0,"value returns truncated total, not current elapsed");t.CheckLoopTimer(.75f,0);t.PauseLoopTimer(id,i=>got=i);Require(got==0&&t.LoopTimers[id].Elapsed==.75f&&t.LoopTimers[id].Paused,"pause callback truncates elapsed without reset");t.PlayLoopTimer(id);t.ResetLoopTimer(id,false);Require(t.LoopTimers[id].TotalTime==4.5f&&!t.LoopTimers[id].Paused,"reset false keeps total");t.ResetLoopTimer(id,true);Require(t.GetLoopTimerValue(id)==0,"reset true clears total");}});
            check("source-loop-gamepause-flush-order-reentry-and-failure",()=>{using(var f=new Fixture()){var t=f.Time;float got=-1;int id=t.AddLoopTimer(8f,true,true,true,v=>{got=v;t.LoopTimers[1].Elapsed=99;});t.CheckLoopTimer(.75f,0);t.GamePause(new object[]{true});Require(got==.75f&&t.LoopTimers[id].Elapsed==0&&t.LoopTimers[id].TotalTime==.75f&&!t.LoopTimers[id].Paused,"flush reports float then overwrites callback elapsed mutation");t.LoopTimers[id].Elapsed=2;t.LoopTimers[id].FloatCallback=v=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>t.GamePause(new object[]{true}));Require(t.LoopTimers[id].Elapsed==2,"error prevents post-callback reset");}});
            check("source-loop-periodic-error-resets-before-callback",()=>{using(var f=new Fixture()){int id=f.Time.AddLoopTimer(1,false,true,true,i=>throw new InvalidOperationException());Throws<InvalidOperationException>(()=>f.Time.CheckLoopTimer(2,0));Require(f.Time.LoopTimers[id].Elapsed==0&&f.Time.LoopTimers[id].TotalTime==2,"elapsed cleared before failure");}});
            check("source-loop-duplicate-add-leaves-partial-dictionary-and-queue",()=>{using(var f=new Fixture()){f.Time.AddLoopTimer(1,false,true,true,i=>{});f.Time.TimeId=0;f.Time.AddLoopTimer(2,false,true,true,i=>{});Throws<ArgumentException>(()=>f.Time.CheckLoopTimer(1,0));Require(f.Time.LoopTimers.Count==1&&f.Time.AddLoopTimerData.Count==2&&f.Time.LoopTimers[1].TotalTime==0,"partial insertion before duplicate, no advancement or queue clear");Throws<ArgumentException>(()=>f.Time.CheckLoopTimer(1,0));}});
            check("source-loop-missing-operations-and-removal-error-queue",()=>{using(var f=new Fixture()){f.Time.PlayLoopTimer(9);f.Time.PauseLoopTimer(9,i=>throw new Exception());f.Time.ResetLoopTimer(9,true);Require(f.Time.GetLoopTimerValue(9)==0&&f.Warnings.Count==4,"missing calls warn only");int id=f.Time.AddLoopTimer(4,false,true,true,i=>{});f.Time.CheckLoopTimer(.5f,0);Throws<InvalidOperationException>(()=>f.Time.RemoveLoopTimer(id,i=>throw new InvalidOperationException()));Require(f.Time.LoopTimerRemoveIds.Count==1&&f.Time.LoopTimers.Count==1,"remove id queues before callback exception");}});
            check("source-unity-second-main-minute-order-and-complete-deferred",()=>{using(var f=new Fixture()){var events=new List<string>();int id=f.Time.AddUnityTimer(1,true,()=>events.Add("complete"),v=>events.Add("every"),()=>events.Add("second"));f.Time.NewEveryMinute.Add(new OutgameUnityTimer(id,1,true,true,()=>events.Add("minute"),null));f.Time.CheckUnityTimer(1,1);Require(string.Join(",",events)=="second,every,complete,minute"&&f.Time.UnityTimers[id].IsComplete,"second before main before minute; completed timer remains this frame");f.Time.CheckUnityTimer(1,1);Require(events.Count==4&&f.Time.UnityTimers.Count==0&&f.Time.EverySecondTimers.Count==0&&f.Time.EveryMinuteTimers.Count==0,"next check removes all families by same id before advancement");}});
            check("source-unity-removal-during-second-still-runs-main",()=>{using(var f=new Fixture()){int id=0,calls=0;id=f.Time.AddUnityTimer(10,true,null,v=>calls++,()=>f.Time.RemoveUnityTimer(id));f.Time.CheckUnityTimer(1,1);Require(calls==1&&f.Time.CashCompleteUnityTimers.Count==1,"second queues removal; main still runs");f.Time.CheckUnityTimer(1,1);Require(calls==1&&f.Time.UnityTimers.Count==0,"next frame applies removal");}});
            check("source-unity-remove-before-add-and-callback-add-delay",()=>{using(var f=new Fixture()){int child=0,calls=0;int id=f.Time.AddUnityTimer(0,true,()=>child=f.Time.AddUnityTimer(0,true,()=>calls++,null,null),null,null);f.Time.RemoveUnityTimer(id);f.Time.RemoveUnityTimer(id);f.Time.CheckUnityTimer(0,0);Require(f.Time.UnityTimers.ContainsKey(id)&&child>id&&calls==0&&f.Time.NewUnityTimers.Count==1,"cached removals dedupe and run before activation; callback child stays pending");f.Time.CheckUnityTimer(0,0);Require(calls==1&&!f.Time.UnityTimers.ContainsKey(id),"next pass removes parent then activates child");}});
            check("source-unity-loop-retains-overshoot-and-fires-only-once",()=>{using(var f=new Fixture()){int calls=0,id=f.Time.AddUnityEverySecondTimer(true,()=>calls++);f.Time.CheckUnityTimer(3.5f,0);Require(calls==1&&f.Time.EverySecondTimers[id].Elapsed==2.5f,"one callback then subtract duration");f.Time.CheckUnityTimer(0,0);Require(calls==2&&f.Time.EverySecondTimers[id].Elapsed==1.5f,"remaining overshoot triggers on later check");}});
            check("source-unity-every-live-mutation-precedes-complete",()=>{using(var f=new Fixture()){int calls=0;var timer=new OutgameUnityTimer(1,1,true,false,()=>calls++,null);timer.Every=v=>timer.Elapsed=0;timer.AddTimer(2,2);Require(calls==0&&timer.Elapsed==0,"completion reads mutated elapsed");timer.Every=null;timer.Complete=()=>{timer.Loop=true;timer.Duration=.5f;};timer.AddTimer(2,2);Require(!timer.IsComplete&&timer.Elapsed==1.5f,"post complete uses live loop/duration");}});
            check("source-unity-exceptions-retain-elapsed-and-skip-complete-cleanup",()=>{using(var f=new Fixture()){int id=f.Time.AddUnityTimer(1,true,()=>throw new InvalidOperationException(),null,null);Throws<InvalidOperationException>(()=>f.Time.CheckUnityTimer(1,1));Require(f.Time.UnityTimers[id].Elapsed==1&&!f.Time.UnityTimers[id].IsComplete&&f.Time.CompleteUnityTimers.Count==0,"completion throws before flag and deferred removal");f.Time.UnityTimers[id].Complete=null;f.Time.UnityTimers[id].Every=v=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Time.CheckUnityTimer(1,1));Require(f.Time.UnityTimers[id].Elapsed==2&&!f.Time.UnityTimers[id].IsComplete,"every failure prevents completion");}});
            check("source-unity-focus-and-unscaled-spike-gates-entire-helper",()=>{using(var f=new Fixture()){int calls=0;var t=new OutgameUnityTimer(1,0,false,false,()=>calls++,v=>calls++);t.AddTimer(2,2);Require(calls==0&&t.Elapsed==0,"unscaled spike skips all callbacks");OutgameTimeClock.IsFocus=false;t.AddTimer(1,1);Require(calls==0,"focus gates even zero-duration completion");OutgameTimeClock.IsFocus=true;t.AddTimer(0,0);Require(calls==2&&t.IsComplete,"zero duration completes when focused");t.AddTimer(1,1);Require(calls==2,"complete flag gates subsequent helper calls");}});
            check("source-unity-duplicate-activation-retains-partial-and-pending",()=>{using(var f=new Fixture()){f.Time.AddUnityTimer(1,true,null,null,null);f.Time.TimeId=0;f.Time.AddUnityTimer(2,true,null,null,null);Throws<ArgumentException>(()=>f.Time.CheckUnityTimer(1,1));Require(f.Time.NewUnityTimers.Count==2&&f.Time.UnityTimers.Count==1&&f.Time.UnityTimers[1].Elapsed==0,"duplicate failure preserves queue and first insertion");}});
            check("source-time-clear-retains-pending-and-completed-queues",()=>{using(var f=new Fixture()){var t=f.Time;int id=t.AddLoopTimer(1,false,true,true,i=>{});t.AddUnityTimer(1,true,null,null,()=>{});t.CompleteUnityTimers.Add(7);t.CashCompleteUnityTimers.Add(8);t.LoopTimerRemoveIds.Add(9);t.LastMillisecond=42;t.UnityRealTime=9;t.ClearTimer();Require(t.AddLoopTimerData.Count==1&&t.NewUnityTimers.Count==1&&t.NewEverySecond.Count==1&&t.CompleteUnityTimers.Count==1&&t.CashCompleteUnityTimers.Count==1&&t.LoopTimerRemoveIds.Count==0&&t.LastMillisecond==42&&t.UnityRealTime==9&&t.TimeId==0,"ClearTimer retains ctor queues except loop remove, resets only selected fields");t.CheckLoopTimer(0,0);t.CheckUnityTimer(0,0);Require(t.LoopTimers.ContainsKey(id)&&t.UnityTimers.Count==1,"queued work survives clear");}});
            check("source-time-initialize-retains-pending-with-id-reuse-collision",()=>{using(var f=new Fixture()){f.Time.AddUnityTimer(1,true,null,null,null);f.Time.Initialize();f.Time.AddUnityTimer(1,true,null,null,null);Throws<ArgumentException>(()=>f.Time.CheckUnityTimer(0,0));Require(f.Time.IsInitialized&&f.Time.TimeId==1&&f.Time.NewUnityTimers.Count==2,"reinitialize leaves pending ids while resetting sequence");}});
            check("source-time-start-duplicates-and-shutdown-removes-one-listener",()=>{using(var f=new Fixture()){var t=f.Time;int calls=0;t.AddLoopTimer(10,true,true,true,i=>calls++);t.CheckLoopTimer(1,1);t.Start();t.Start();f.Messages.SendMessage("GF_NewGamePause",new object[]{true});Require(calls==2,"duplicate Start registers twice and second flush reports zero");t.Shutdown();Require(!t.IsInitialized&&t.LoopTimers.Count==0,"shutdown clears timers and initialized flag");f.Messages.SendMessage("GF_GameFocus",new object[]{false});Require(!OutgameTimeClock.IsFocus,"one duplicate listener remains");t.Shutdown();OutgameTimeClock.IsFocus=true;f.Messages.SendMessage("GF_GameFocus",new object[]{false});Require(OutgameTimeClock.IsFocus,"second shutdown removes remaining listener");}});
            check("source-time-pause-focus-invalid-payload-and-no-blanket-update-gate",()=>{using(var f=new Fixture()){Throws<NullReferenceException>(()=>f.Time.GamePause(null));Throws<IndexOutOfRangeException>(()=>f.Time.GameFocus(new object[0]));Throws<InvalidCastException>(()=>f.Time.GameFocus(new object[]{1}));int calls=0;f.Time.SetCountDownByMillisecond(0,i=>calls++,null);f.Time.IsInitialized=false;OutgameTimeClock.IsFocus=false;f.Time.Update();Require(calls==1,"Update still checks DateTime countdown when initialization/focus flags false");}});
            check("source-time-clear-does-not-destroy-loop-callbacks",()=>{using(var f=new Fixture()){int id=f.Time.AddLoopTimer(1,false,true,true,i=>{});f.Time.CheckLoopTimer(0,0);var timer=f.Time.LoopTimers[id];f.Time.ClearTimer();Require(timer.IntCallback!=null,"ClearTimer clears dictionary without Destroy iteration");}});
            return r;
        }
    }
}
