using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameMatchValidation
    {
        public sealed class Transmitter:IOutgameMatchRankTransmitter
        {
            public Action SendResponseCallback {get;set;}
            public readonly List<(string uid,string nick,string url,int wins,int losses,int rank,int weight)> Requests=new List<(string,string,string,int,int,int,int)>();
            public Action Sending;
            public void SendRankDataRequest(string uid,string nick,string url,int wins,int losses,int rankType,int weight)
            {Requests.Add((uid,nick,url,wins,losses,rankType,weight));Sending?.Invoke();}
        }
        sealed class Host:IOutgameDataStorageHost
        {
            public int Progress=10;public bool Server;public int Uploads;
            public int SourceLoginProgress=>Progress;public bool LoginProcedureFlag8=>false;public bool LoginStaticFlag4=>false;
            public bool IsUseServer=>Server;public string MineGameName=>"Proj_hdzd";public bool HasToast=>false;
            public void Log(string s){}public void Error(string s){}public void Toast(string s){}
            public string Compress(string k,string s)=>throw new Exception("unexpected compression");
            public string Decompress(string k,string s)=>throw new Exception("unexpected decompression");
            public void QueueUpload(string k,string s){Uploads++;}
        }
        sealed class Fixture
        {
            public readonly Host Host=new Host();public readonly OutgameSdkStringStorage Strings;
            public readonly OutgameDataManagerPool Pool;public readonly OutgameMessageDispatcher Messages=new OutgameMessageDispatcher();
            public readonly OutgameDataVersionState Versions=new OutgameDataVersionState(()=>{},()=>{},()=>{},s=>{},s=>{});
            public readonly OutgameMatchManager Manager;public readonly OutgameMatchControl Control;public readonly Transmitter Transmitter=new Transmitter();
            public readonly List<string> Trace=new List<string>();public readonly string PathName;
            public int Level=8,Downloads;public Func<int> ReadLevel;public Func<string> ReadOpenId,ReadName;public Action InitAvatar;
            public Fixture(string path=null,bool initialize=true)
            {
                PathName=path??Path.Combine(Path.GetTempPath(),"AreaBattleMatch-"+Guid.NewGuid().ToString("N"));
                Strings=new OutgameSdkStringStorage(new OutgameFileStorageBackend(PathName,a=>a()),s=>{throw new Exception(s);});
                Pool=new OutgameDataManagerPool(()=>{},Trace.Add,Trace.Add,Trace.Add);Pool.OnInit(false,"Proj_hdzd",Array.Empty<OutgameManagerRegistration>());
                Manager=new OutgameMatchManager(new OutgameDataManagerStorage(()=>"MatchManager",Host,Strings,Versions),Host,s=>Downloads++,()=>ReadOpenId!=null?ReadOpenId():"uid",()=>ReadLevel!=null?ReadLevel():Level,()=>ReadName!=null?ReadName():"昵称");
                Pool.Managers[4130]=Manager;
                Control=new OutgameMatchControl(()=>Pool,()=>Messages,()=>ReadLevel!=null?ReadLevel():Level,()=>ReadOpenId!=null?ReadOpenId():"uid",()=>{Trace.Add("avatar");InitAvatar?.Invoke();}){Transmitter=Transmitter};
                if(initialize)Manager.OnInit();
            }
            public string Stored=>Strings.GetString("Proj_hdzdMatchManager","");
        }
        sealed class LastRandom:System.Random {public override int Next(int maxValue)=>maxValue-1;}
        static void Require(bool b,string why){if(!b)throw new Exception(why);}
        static T Throws<T>(Action a)where T:Exception{try{a();}catch(T e){return e;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion,limitations="Original MatchManager/MatchControl field schema, persistence and rank request/callback ordering. Pinned LitJSON primitive schema verified against original ReadValue/ToJson; original library commit unknown. Transmitter/OpenID/avatar initialization are explicit fixture endpoints, not server/platform success. Full rank UI/Main/Player pending."};
            Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id="match-"+id,result="pass"});}catch(Exception e){r.passed=false;r.checks.Add(new BattleBuild.Check{id="match-"+id,result="fail",detail=e.ToString()});}};
            check("fresh-schema-and-original-clamp",()=>{var f=new Fixture();var d=f.Manager.Data.rankData;Require(d.uid=="uid"&&d.nick=="昵称"&&d.url==""&&d.VN_t==5&&d.DN_t==0&&d.playNum==0&&!d.isGetWechatInfo,"fresh fields");f.Level=1;f.Manager.UpdateDataCallBack("");Require(f.Manager.Data.rankData.VN_t==0,"below3 clamp");int reads=0;f.ReadLevel=()=>++reads==1?7:1;f.Manager.UpdateDataCallBack("");Require(reads==2&&f.Manager.Data.rankData.VN_t==-2,"two reads, negative maximum retained");});
            check("constructor-missing-vs-explicit-null-and-no-default-repair",()=>{var f=new Fixture();f.Manager.UpdateDataCallBack("{}");Require(f.Manager.Data.rankData!=null&&f.Manager.Data.rankData.uid==null&&f.Manager.Data.rankData.nick==null&&f.Manager.Data.rankData.VN_t==0,"LitJSON constructor applies for missing field; manager skips defaults");f.Manager.UpdateDataCallBack("{\"rankData\":null}");Require(f.Manager.Data.rankData==null,"explicit null retained");f.Manager.UpdateDataCallBack("{\"rankData\":{\"nick\":\"\",\"unknown\":[1,{}]}}");Require(f.Manager.Data.rankData.nick==""&&f.Manager.Data.rankData.url==null,"unknown fields skipped; existing empty fields retained");});
            check("typed-json-corruption-does-not-replace-live-data",()=>{var f=new Fixture();var old=f.Manager.Data;Throws<LitJson.JsonException>(()=>f.Manager.UpdateDataCallBack("null"));Require(f.Manager.Data==old,"original root grammar excludes literal null");Throws<LitJson.JsonException>(()=>f.Manager.UpdateDataCallBack("{\"rankData\":{\"VN_t\":\"7\"}}"));Require(f.Manager.Data==old,"typed parse fails before assignment");Throws<ArgumentNullException>(()=>f.Manager.UpdateDataCallBack(null));Require(f.Manager.Data==old,"null input follows reader failure");Throws<LitJson.JsonException>(()=>f.Manager.UpdateDataCallBack("{invalid}"));Require(f.Manager.Data==old,"invalid token retains live data");});
            check("fresh-default-failure-retains-published-prefix",()=>{var f=new Fixture();var old=f.Manager.Data;f.ReadOpenId=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Manager.UpdateDataCallBack(""));Require(f.Manager.Data!=old&&f.Manager.Data.rankData.uid==null,"new data published before OpenID failure");f.ReadOpenId=()=>"next";f.ReadName=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Manager.UpdateDataCallBack(""));Require(f.Manager.Data.rankData.uid=="next"&&f.Manager.Data.rankData.VN_t==5&&f.Manager.Data.rankData.url==null,"name failure leaves ID/count prefix before URL assignment");});
            check("fresh-provider-reentry-captures-target-and-rereads-data",()=>{var f=new Fixture();OutgameMatchPlayerData captured=null;var replacement=new OutgameMatchData();f.ReadOpenId=()=>{captured=f.Manager.Data.rankData;f.Manager.Data=replacement;return "captured";};f.ReadName=()=>{var newer=new OutgameMatchData();f.Manager.Data=newer;return "old-target";};f.Manager.UpdateDataCallBack("");Require(captured.uid=="captured"&&replacement.rankData.VN_t==5&&replacement.rankData.nick=="old-target"&&replacement.rankData.url==null&&f.Manager.Data.rankData.url=="","evaluation targets retained while subsequent fields re-resolve");});
            check("real-file-roundtrip-schema-and-release-retention",()=>{var f=new Fixture();var d=f.Manager.Data.rankData;d.nick="恢复测试\n\"";d.url="https://example.invalid/a";d.VN_d=int.MaxValue;d.DN_t=-2;d.playNum=12;d.isGetWechatInfo=true;f.Pool.SaveData();Require(!f.Stored.Contains("Nickname")&&!f.Stored.Contains("HasWechatInfo")&&f.Stored.Contains("rankData"),"interface aliases excluded from LitJSON schema");var g=new Fixture(f.PathName);Require(g.Manager.Data.rankData.nick==d.nick&&g.Manager.Data.rankData.url==d.url&&g.Manager.Data.rankData.VN_d==int.MaxValue&&g.Manager.Data.rankData.DN_t==-2&&g.Manager.Data.rankData.playNum==12&&g.Manager.Data.rankData.isGetWechatInfo,"fresh independent backend read");var held=g.Manager.Data;g.Manager.OnRelease();Require(g.Manager.Data==held,"empty release retains data");});
            check("server-init-remains-pending-and-local-override",()=>{var f=new Fixture(initialize:false);f.Host.Server=true;f.Manager.OnInit();Require(f.Downloads==1&&f.Manager.Data==null,"server download without synthetic completion");f.Manager.UpdateData(false);Require(f.Manager.Data.rankData.VN_t==5&&f.Downloads==1,"explicit local update");f.Manager.ParticipatesInSync=false;f.Manager.OnInit();Require(f.Downloads==1,"sync disabled uses local");});
            check("login-gate-digest-and-disabled-pool",()=>{var f=new Fixture();f.Host.Progress=9;f.Manager.OnSave();Require(f.Stored=="","login gate");f.Host.Progress=10;f.Manager.OnSave();Require(f.Stored=="","source digest already committed, unchanged save skipped");f.Manager.Data.rankData.playNum++;f.Pool.SetSaveDisabled(true);f.Pool.SaveData();Require(f.Stored=="","global disabled");f.Pool.SetSaveDisabled(false);f.Pool.SaveData();Require(f.Stored!="","changed record saves after gates");});
            check("events-init-failure-argument-types-level-gate-dispose",()=>{var f=new Fixture();f.InitAvatar=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(f.Control.OnInit);f.Messages.SendMessage("GamePlayState",new object[]{8});Require(f.Transmitter.Requests.Count==0,"avatar init failure precedes listener");f.InitAvatar=null;f.Control.OnInit();f.Control.OnGamePlayerState(null);f.Control.OnGamePlayerState(Array.Empty<object>());Throws<InvalidCastException>(()=>f.Control.OnGamePlayerState(new object[]{8L}));f.Level=2;f.Messages.SendMessage("GamePlayState",new object[]{8});Require(f.Manager.Data.rankData.playNum==0,"early level ignored");f.Level=3;f.Messages.SendMessage("GamePlayState",new object[]{8});Require(f.Manager.Data.rankData.playNum==1&&f.Transmitter.Requests.Count==3,"eligible win");f.Control.ActiveUpdate=true;f.Control.OnDispose();f.Messages.SendMessage("GamePlayState",new object[]{9});Require(f.Manager.Data.rankData.playNum==1&&f.Control.ActiveUpdate&&f.Control.Transmitter==f.Transmitter,"dispose only removes listener");});
            check("three-ranks-pre-response-counts-and-no-auto-save",()=>{var f=new Fixture();f.Control.OnGamePlayerState(new object[]{8});var req=f.Transmitter.Requests;Require(req.Count==3&&string.Join(",",req.Select(x=>x.rank))=="2,3,1"&&req[0].wins==1&&req[1].wins==1&&req[2].wins==6&&req.All(x=>x.losses==0&&x.weight==100)&&f.Manager.Data.rankData.VN_t==5&&f.Manager.Data.rankData.playNum==1,"day/week/total before callback");f.Transmitter.SendResponseCallback();Require(f.Transmitter.SendResponseCallback==null&&f.Manager.Data.rankData.VN_t==6&&f.Manager.Data.rankData.VN_d==1&&f.Manager.Data.rankData.VN_w==1&&f.Stored=="","response increments without save");});
            check("request-failure-retains-play-prefix-and-prior-callback",()=>{var f=new Fixture();Action old=()=>{};f.Transmitter.SendResponseCallback=old;f.Transmitter.Sending=()=>{if(f.Transmitter.Requests.Count==2)throw new InvalidOperationException();};Throws<InvalidOperationException>(()=>f.Control.OnGamePlayerState(new object[]{9}));Require(f.Transmitter.Requests.Count==2&&f.Transmitter.SendResponseCallback==old&&f.Manager.Data.rankData.playNum==1&&f.Manager.Data.rankData.DN_t==0,"second request failure skips third and new callback");});
            check("request-reentry-resolves-transmitter-and-id-each-time",()=>{var f=new Fixture();var second=new Transmitter();int ids=0;f.ReadOpenId=()=>{ids++;if(ids==1){f.Control.Transmitter=second;f.Manager.Data.rankData.nick="changed";f.Manager.Data.rankData.VN_t=99;}return "u"+ids;};f.Control.SendRank(true);Require(f.Transmitter.Requests.Count==1&&second.Requests.Count==2&&f.Transmitter.Requests[0].uid=="u1"&&f.Transmitter.Requests[0].nick=="changed"&&second.Requests[1].uid=="u3"&&second.Requests[1].wins==100&&second.Requests.All(x=>x.weight==100)&&f.Transmitter.SendResponseCallback==null&&second.SendResponseCallback!=null,"target captured before OpenID; next target and fields reread; weight captured once");});
            check("response-installed-after-all-synchronous-requests",()=>{var f=new Fixture();int oldCalls=0;f.Transmitter.SendResponseCallback=()=>oldCalls++;f.Transmitter.Sending=()=>f.Transmitter.SendResponseCallback?.Invoke();f.Control.SendRank(false);Require(oldCalls==3&&f.Manager.Data.rankData.DN_t==0,"synchronous responses see only old callback");f.Transmitter.SendResponseCallback();Require(f.Manager.Data.rankData.DN_d==1&&f.Manager.Data.rankData.DN_w==1&&f.Manager.Data.rankData.DN_t==1,"new callback available after all requests");});
            check("win-current-record-loss-captured-record-and-current-transmitter-clear",()=>{var f=new Fixture();var old=f.Manager.Data.rankData;f.Control.SendRank(true);var win=f.Transmitter.SendResponseCallback;f.Manager.Data=new OutgameMatchData();var next=new Transmitter{SendResponseCallback=()=>{}};f.Control.Transmitter=next;win();Require(next.SendResponseCallback==null&&f.Transmitter.SendResponseCallback==win&&old.VN_t==5&&f.Manager.Data.rankData.VN_t==1,"win uses current data/current transmitter");f.Control.SendRank(false);var lose=next.SendResponseCallback;var captured=f.Manager.Data.rankData;f.Manager.Data=new OutgameMatchData();lose();Require(captured.DN_t==1&&f.Manager.Data.rankData.DN_t==0,"loss uses captured data");lose();Require(captured.DN_t==2,"retained callback has no invented idempotence");});
            check("null-transmitter-preserves-play-and-openid-order",()=>{var f=new Fixture();int ids=0;f.ReadOpenId=()=>{ids++;return "id";};f.Control.Transmitter=null;Throws<NullReferenceException>(()=>f.Control.OnGamePlayerState(new object[]{8}));Require(ids==1&&f.Manager.Data.rankData.playNum==1,"no implicit transmitter, argument evaluated before null invocation");});
            check("lazy-manager-cache-and-unchecked-counters",()=>{var f=new Fixture();Require(f.Control.Manager==f.Manager,"lazy lookup");f.Pool.Managers.Remove(4130);f.Manager.Data.rankData.VN_t=int.MaxValue;f.Manager.Data.rankData.playNum=int.MaxValue;f.Control.OnGamePlayerState(new object[]{8});Require(f.Control.Manager==f.Manager&&f.Manager.Data.rankData.playNum==int.MinValue&&f.Transmitter.Requests[2].wins==int.MinValue&&f.Transmitter.Requests[2].weight==unchecked(int.MaxValue*20),"retained manager and wrapping request arithmetic");f.Transmitter.SendResponseCallback();Require(f.Manager.Data.rankData.VN_t==int.MinValue,"callback wraps");});
            check("random-string-final-element-and-empty-source-failure",()=>{var rng=new GameRandomSource(new LastRandom());Require(rng.Element(new List<string>{"a","b"})=="b","generic source Random.Next(count) includes final name");Throws<ArgumentOutOfRangeException>(()=>rng.Element(new List<string>()));});
            check("top-info-auth-persists-real-match-with-separate-profile",()=>{string path;using(var f=new OutgameTopInfoPageValidation.Fixture()){var runtime=AttachTopInfo(f);f.Start();string name=f.User.Name;f.Messages.SendMessage("Avatar_Refresh_OnAuth",new object[]{"event","url"});var d=runtime.Manager.Data.rankData;Require(d.isGetWechatInfo&&d.nick=="platform-nickname"&&d.url=="platform-avatar"&&f.Page.MatchNameText.text==d.nick&&f.User.Name==name,"real match authorizes separately from profile");var stored=LitJson.JsonMapper.ToObject<OutgameMatchData>(f.Account.Stored("MatchManager"));Require(stored.rankData.nick==d.nick&&stored.rankData.isGetWechatInfo,"TopInfo pool save includes actual MatchManager");path=f.Account.PathName;}using(var f=new OutgameTopInfoPageValidation.Fixture(path:path)){var runtime=AttachTopInfo(f);Require(runtime.Manager.Data.rankData.isGetWechatInfo&&runtime.Manager.Data.rankData.nick=="platform-nickname","independent account backend restores authorization");}});
            return r;
        }
        public static OutgameMatchControl AttachTopInfo(OutgameTopInfoPageValidation.Fixture f)
        {
            OutgameConfigDerivedIndexes.AppendChineseNames(f.Config.dicAIName,f.Config.ChineseNames);
            var runtime=new OutgameMatchRuntime(()=>f.Account.Statistics.Pool,()=>f.Config,f.Account.Host,f.Account.Services.Storage,f.Account.Services.Versions,f.Account.Host.Downloads.Add,()=>"fixture-openid",()=>8,()=>f.Messages,()=>f.Trace.Add("explicit-avatar-init"));
            var reg=runtime.Registration;var manager=reg.Create();manager.ParticipatesInSync=reg.AutoSyn;manager.CompressData=reg.CompressData;manager.OnInit();f.Account.Statistics.Pool.Managers[reg.SourceTypeIndex]=manager;
            runtime.BindController(f.Account.Page.Data.Registry);var control=(OutgameMatchControl)f.Account.Page.Data.Registry.Resolve(4129);control.OnInit();OutgameMatchRuntime.BindTopInfo(f.Services,()=>control);return control;
        }
    }
}
