using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;
using ListArrayInt=AreaBattle.OriginalConfig.ListArrayInt;
namespace AreaBattle.EditorTools
{
    public static class OutgameBuffToolControlValidation
    {
        sealed class Buff:OutgameBuffBase{public override object TargetId{get;set;}public int Clears;public override void Clear(){Clears++;}}
        sealed class Hash{readonly int value;public Hash(int value){this.value=value;}public override int GetHashCode()=>value;}
        sealed class Platform:IOutgameControllerPlatform{public int GetAppChannelId()=>0;public void SetAppChannelId(int n){}public bool IsInstallVersion=>true;public long GetServerTimeByServerTimeZone()=>0;public int GetNetworkingState()=>0;public DateTime LocalNow=>DateTime.Now;public bool IsReleaseVersion=>false;}
        sealed class Effects:IOutgameToolEffects
        {
            public readonly List<string> Trace=new List<string>();public Action Saving;
            public void RefreshTopInfo()=>Trace.Add("top");public void GoldSpent(int id,long amount)=>Trace.Add("spent:"+amount);public void ToolChanged(int id)=>Trace.Add("changed:"+id);
            public void UnlockScene(int id)=>Trace.Add("scene:"+id);public void UnlockSoldier(int id)=>Trace.Add("soldier:"+id);public bool ApplyItemEntity(int id,long delta)=>throw new InvalidOperationException("Unbound item entity in isolated test");public void MissingItemEntity(int id)=>throw new Exception();
            public void ReportGet(int id,int category,int amount,int balance,string reason)=>Trace.Add("get:"+id+":"+amount+":"+balance+":"+reason);public void ReportCost(int id,int category,int amount,int balance)=>Trace.Add("cost:"+id+":"+amount+":"+balance);public void Save(){Trace.Add("save");Saving?.Invoke();}
        }
        sealed class Fixture
        {
            public readonly OutgameControllerRegistry Registry=new OutgameControllerRegistry();public readonly Effects Effects=new Effects();public readonly OutgameLocalInventoryState State=new OutgameLocalInventoryState();public OutgameLocalInventory Inventory;public OutgameToolDispatcher Dispatcher;public OutgameToolControl Control;public long ModuleCount;public int ModuleReads,LocalReads;public string Reason="PurchaseCost";
            public Fixture(){Inventory=new OutgameLocalInventory(State,BattleView.ReadText("Data/AllSkillConfig"));Dispatcher=new OutgameToolDispatcher(Inventory,Effects,BattleView.ReadText("Data/Outgame/GameItemConfig"),BattleView.ReadText("Data/Outgame/SceneSkinConfig"),BattleView.ReadText("Data/Outgame/SkinConfig"));OutgameCoreControllerBindings.BindTools(Registry,()=>Dispatcher,()=>{LocalReads++;return Inventory;},id=>{ModuleReads++;return ModuleCount;},()=>Reason);Control=(OutgameToolControl)Registry.Resolve(4256);}
        }
        static int Listeners(OutgameMessageDispatcher m){var d=(Dictionary<string,Action<object[]>>)typeof(OutgameMessageDispatcher).GetField("listeners",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(m);return d.TryGetValue("GamePlayState",out var action)?action.GetInvocationList().Length:0;}
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        static ListArrayInt Row(int id,int amount)=>new ListArrayInt{datas=new[]{id,amount}};
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-buff-control-core-binding-and-repeated-subscriptions",()=>{var registry=new OutgameControllerRegistry();var m=new OutgameMessageDispatcher();OutgameCoreControllerBindings.Bind(registry,null,null,new Platform(),()=>m,null,(c,s)=>{},s=>{},s=>{});var c=(OutgameBuffControl)registry.Resolve(4025);c.OnInit();c.OnInit();Require(Listeners(m)==2&&c.Buffs.Count==0,"source duplicate init subscribes twice");m.SendMessage("GamePlayState",null);m.SendMessage("GamePlayState",new object[]{"invalid"});c.Updata(float.NaN,float.NegativeInfinity);c.OnDispose();Require(Listeners(m)==1&&!registry.HasInstance(4025),"dispose removes one delegate then clears slot");});
            check("source-buff-control-dispose-clears-dictionary-not-buffs",()=>{var r0=new OutgameControllerRegistry();var m=new OutgameMessageDispatcher();r0.Bind(4025,()=>new OutgameBuffControl(r0,()=>m));var c=(OutgameBuffControl)r0.Resolve(4025);var b=new Buff();c.Buffs.Add(4,b);var held=c.Buffs;c.OnInit();c.OnDispose();Require(ReferenceEquals(held,c.Buffs)&&held.Count==0&&b.Clears==0&&Listeners(m)==0,"clear existing dictionary only, no per-buff Clear");Require(!ReferenceEquals(c,r0.Resolve(4025)),"source slot creates fresh instance");});
            check("source-buff-dispose-failure-keeps-later-state",()=>{var registry=new OutgameControllerRegistry();bool fail=false;var m=new OutgameMessageDispatcher();registry.Bind(4025,()=>new OutgameBuffControl(registry,()=>fail?throw new InvalidOperationException():m));var c=(OutgameBuffControl)registry.Resolve(4025);c.OnInit();c.Buffs[1]=new Buff();fail=true;Throws<InvalidOperationException>(c.OnDispose);Require(c.Buffs.Count==1&&registry.HasInstance(4025)&&Listeners(m)==1,"lookup failure prevents dictionary clear and singleton reset");fail=false;c.Buffs=null;Throws<NullReferenceException>(c.OnDispose);Require(Listeners(m)==0&&registry.HasInstance(4025),"dictionary failure happens after unsubscribe before singleton clear");});
            check("source-buff-dispose-resolves-current-dispatcher-and-old-instance",()=>{var registry=new OutgameControllerRegistry();var old=new OutgameMessageDispatcher();var current=old;registry.Bind(4025,()=>new OutgameBuffControl(registry,()=>current));var c=(OutgameBuffControl)registry.Resolve(4025);c.OnInit();current=new OutgameMessageDispatcher();c.OnDispose();Require(Listeners(old)==1,"source disposal uses current dispatcher");var replacement=registry.Resolve(4025);c.OnDispose();Require(!registry.HasInstance(4025)&&replacement!=null,"old instance unconditionally clears new slot");});
            check("source-buff-equals-target-hash-and-null-order",()=>{var b=new Buff{TargetId=new Hash(7)};Require(b.Equals(new Hash(7))&&!b.Equals(new Hash(8)),"compares hashes with arbitrary object");Throws<NullReferenceException>(()=>b.Equals(null));b.TargetId=null;Throws<NullReferenceException>(()=>b.Equals(new Hash(7)));int hash=b.GetHashCode();Require(b.GetHashCode()==hash,"identity hash stable despite null target");});
            check("source-tool-lifecycle-retains-singleton-through-logic-shutdown",()=>{var f=new Fixture();var module=new OutgameLogicModule(b=>{},()=>{},()=>{},s=>{},s=>{});module.Initialize();module.RegisterLogicCtr(f.Control,false);module.InitCtrl(true);module.Update(1,2);module.Shutdown();Require(f.Registry.HasInstance(4256)&&ReferenceEquals(f.Control,f.Registry.Resolve(4256))&&f.Effects.Trace.Count==0,"verified empty source lifecycle does not reset singleton or save");});
            check("source-tool-rewards-use-live-list-and-live-reason",()=>{var f=new Fixture();var list=new List<ListArrayInt>{Row(1001,3)};int saves=0;f.Effects.Saving=()=>{if(++saves==1){f.Reason="changed";list.Add(Row(1002,4));}};f.Control.GetReward(list,false);Require(f.State.goldNum==3&&f.State.diamondsNum==4&&saves==2&&f.Effects.Trace.Contains("get:1001:3:3:PurchaseCost")&&f.Effects.Trace.Contains("get:1002:4:4:changed")&&!f.Effects.Trace.Contains("top"),"indexed live count and reason read once per row");});
            check("source-tool-reward-debit-failure-continues-next-row",()=>{var f=new Fixture();f.Control.GetReward(new List<ListArrayInt>{Row(1001,-1),Row(1002,4)},true);Require(f.State.goldNum==0&&f.State.diamondsNum==4&&f.Effects.Trace.FindAll(s=>s=="save").Count==2&&f.Effects.Trace.FindAll(s=>s=="top").Count==2,"bool result ignored, next row applies and each saves");});
            check("source-tool-reward-malformed-row-keeps-previous-save",()=>{var f=new Fixture();Throws<IndexOutOfRangeException>(()=>f.Control.GetReward(new List<ListArrayInt>{Row(1001,2),new ListArrayInt{datas=new[]{1002}},Row(1001,99)},false));Require(f.State.goldNum==2&&f.Effects.Trace.FindAll(s=>s=="save").Count==1,"earlier row remains committed; no atomic batch or repair");Throws<NullReferenceException>(()=>f.Control.GetReward(null,false));});
            check("source-tool-multireward-int32-wrap-and-zero-still-dispatch",()=>{var f=new Fixture();f.State.goldNum=5;f.Control.GetMultiReward(new List<ListArrayInt>{Row(1001,int.MaxValue)},2,false);Require(f.State.goldNum==3&&f.Effects.Trace.Contains("cost:1001:2:3"),"multiplication wraps to-2");f.Effects.Trace.Clear();f.Control.GetMultiReward(new List<ListArrayInt>{Row(1001,7)},0,false);Require(f.State.goldNum==3&&string.Join("|",f.Effects.Trace)=="changed:1001|save","zero reward still notifies and saves");});
            check("source-tool-query-8001-boundary-and-narrowing",()=>{var f=new Fixture();f.ModuleCount=0x100000005L;Require(f.Control.GetItemNum(8000)==0&&f.LocalReads==1&&f.ModuleReads==0,"8000 local");Require(f.Control.GetItemNum(8001)==5&&f.ModuleReads==1,"8001 Int64 wraps to Int32");f.ModuleCount=uint.MaxValue;Require(f.Control.GetItemNum(9999)==-1&&!f.Control.IsEnough(9999,0)&&f.Control.IsEnough(9999,-1),"signed compare after narrowing");});
            check("source-tool-countbyid-always-local-and-local-replacement",()=>{var f=new Fixture();f.ModuleCount=100;Require(f.Control.GetItemCountById(8001)==0&&f.ModuleReads==0,"count by id never routes global");f.Inventory=new OutgameLocalInventory(new OutgameLocalInventoryState{goldNum=9},"{\"Datas\":[]}");Require(f.Control.GetItemNum(1001)==9&&f.Control.IsEnough(1001,9),"resolve current inventory on every read");});
            check("source-tool-change-overload-and-explicit-report-suppression",()=>{var f=new Fixture();Require(f.Control.ToolChange(1001,2,false,"reward"),"default notify overload");Require(f.Effects.Trace.Contains("get:1001:2:2:reward"),"wrapper enables report");f.Effects.Trace.Clear();f.Control.ToolChange(1001,1,false,"unused",false);Require(string.Join("|",f.Effects.Trace)=="save"&&f.State.goldNum==3,"explicit false preserved");});
            check("source-tool-batch-save-failure-stops-after-mutated-row",()=>{var f=new Fixture();f.Effects.Saving=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Control.GetReward(new List<ListArrayInt>{Row(1001,2),Row(1002,4)},false));Require(f.State.goldNum==2&&f.State.diamondsNum==0,"source preserves mutation before failed save and stops next row");});
            return r;
        }
    }
}
