using System;
using System.Linq;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameObjectPoolManagerValidation
    {
        sealed class Probe:IOutgameManagedObjectPool
        {public Action<float,float> OnUpdate;public Action OnShutdown;public void Update(float a,float b)=>OnUpdate?.Invoke(a,b);public void Shutdown()=>OnShutdown?.Invoke();}
        static void Require(bool b,string why){if(!b)throw new Exception(why);}
        static T Throws<T>(Action a)where T:Exception{try{a();}catch(T e){return e;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion,limitations="Original ObjectPoolManager lifecycle/generic factory/name/destroy plus actual Frame/Logic/NormalPool binding. Alternative object types use explicit factories; general resource acquisition/platform/Main/Player remain incomplete."};
            Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id="pool-manager-"+id,result="pass"});}catch(Exception e){r.passed=false;r.checks.Add(new BattleBuild.Check{id="pool-manager-"+id,result="fail",detail=e.ToString()});}};
            check("initialize-priority-retained-registry-callback-and-shutdown-flag",()=>{var m=new OutgameObjectPoolManager();var p=m.CreateSingleSpawnObjectPool("preinit");int n=0;m.Initialized=()=>{Require(m.IsInitialized&&m.Pools.Count==1,"flag before callback and constructor registry retained");n++;};m.Initialize();m.Initialize(new object[]{1});Require(n==2&&m.Priority==70&&ReferenceEquals(p,m.Pools.Values.Single()),"repeat initialize no clear");m.Shutdown();Require(!m.IsInitialized&&m.Pools.Count==0&&m.Initialized!=null,"successful shutdown retains delegate");});
            check("original-full-type-key-null-empty-name-and-distinct-type",()=>{var m=new OutgameObjectPoolManager();m.CreateSingleSpawnObjectPool(null);Require(m.HasObjectPool("")&&m.Pools.ContainsKey("g\u0093t\u0090\u00b6O"),"original obfuscated prefab name");Throws<OutgameFrameworkException>(()=>m.CreateSingleSpawnObjectPool(""));var p=m.CreateSingleSpawnObjectPool("Another.Type",null,(n,b,c,e,o)=>new Probe());Require(m.Pools.Count==2&&ReferenceEquals(p,m.Pools["Another.Type"]),"different original type independent");m.Shutdown();});
            check("single-spawn-default-constructor-arguments-and-duplicate-before-factory",()=>{var m=new OutgameObjectPoolManager();int calls=0;var p=m.CreateSingleSpawnObjectPool("Type","named",(n,b,c,e,o)=>{calls++;Require(n=="named"&&!b&&c==int.MaxValue&&e==float.MaxValue&&o==0,"source default arguments");return new Probe();});var error=Throws<OutgameFrameworkException>(()=>m.CreateSingleSpawnObjectPool("Type","named",(n,b,c,e,o)=>{calls++;return new Probe();}));Require(calls==1&&error.Message=="Already exist object pool 'Type.named'.","original error and no duplicate allocation");m.Shutdown();});
            check("original-key-format-keeps-dot-collision-and-factory-failure-unregistered",()=>{var m=new OutgameObjectPoolManager();m.CreateSingleSpawnObjectPool("A","B.C",(n,b,c,e,o)=>new Probe());Require(m.HasObjectPool("A.B","C"),"source format collision retained");Throws<InvalidOperationException>(()=>m.InternalCreateObjectPool<Probe>("fail","n",false,1,2,3,(n,b,c,e,o)=>throw new InvalidOperationException()));Require(!m.HasObjectPool("fail","n"),"failed constructor never added");m.Shutdown();});
            check("factory-reentry-add-failure-retains-first-registered-owner",()=>{var m=new OutgameObjectPoolManager();var first=new Probe();Throws<ArgumentException>(()=>m.CreateSingleSpawnObjectPool("T","n",(n,b,c,e,o)=>{m.Pools.Add("T.n",first);return new Probe();}));Require(ReferenceEquals(m.Pools["T.n"],first),"source Add after construction does not replace reentrant owner");m.Shutdown();});
            check("live-update-arguments-mutation-and-first-failure-order",()=>{var m=new OutgameObjectPoolManager();int second=0;var a=new Probe{OnUpdate=(x,y)=>{Require(x==.25f&&y==2,"both frame deltas unchanged");m.Pools.Add("new",new Probe());}};m.Pools.Add("a",a);m.Pools.Add("b",new Probe{OnUpdate=(x,y)=>second++});Throws<InvalidOperationException>(()=>m.Update(.25f,2));Require(second==0&&m.Pools.Count==3,"live dictionary enumerator, no snapshot/catch");m.Shutdown();});
            check("destroy-releases-before-removal-failure-retains-registration",()=>{var m=new OutgameObjectPoolManager();var p=new Probe{OnShutdown=()=>{Require(m.HasObjectPool("T","n"),"visible during shutdown");throw new InvalidOperationException();}};m.Pools.Add("T.n",p);Throws<InvalidOperationException>(()=>m.DestroyObjectPool("T","n"));Require(m.Pools.Count==1,"failure keeps pool");p.OnShutdown=()=>{};Require(m.DestroyObjectPool("T","n")&&!m.DestroyObjectPool("T","n"),"success true then miss false");});
            check("destroy-return-reflects-callback-removal-and-null-entry-failure",()=>{var m=new OutgameObjectPoolManager();m.Pools.Add("T.n",new Probe{OnShutdown=()=>m.Pools.Remove("T.n")});Require(!m.DestroyObjectPool("T","n"),"return Remove result after callback");m.Pools.Add("T.null",null);Throws<NullReferenceException>(()=>m.DestroyObjectPool("T","null"));Require(m.HasObjectPool("T","null"),"single destroy does not null-skip");m.Shutdown();});
            check("shutdown-failure-retains-initialized-and-all-registrations",()=>{var m=new OutgameObjectPoolManager();m.Initialize();int a=0,b=0;m.Pools.Add("a",new Probe{OnShutdown=()=>a++});var failed=new Probe{OnShutdown=()=>throw new InvalidOperationException()};m.Pools.Add("b",failed);m.Pools.Add("c",new Probe{OnShutdown=()=>b++});Throws<InvalidOperationException>(m.Shutdown);Require(a==1&&b==0&&m.Pools.Count==3&&m.IsInitialized,"no per-entry removal or final clear/flag on failure");failed.OnShutdown=()=>{};m.Shutdown();Require(a==2&&b==1&&!m.IsInitialized,"retry repeats earlier release");});
            check("frame-priority-and-real-effect-pool-shutdown-order",()=>{using(var f=new OutgameEffectControlValidation.Fixture(frameManager:true)){Require(f.Frame.Modules.First.Value==f.Manager&&f.Frame.Modules.Last.Value==f.Logic&&f.Manager.Pools.Count==1&&f.Host.Pools.Count==0,"real manager70 precedes logic12, local host no registry");GameObject go=null;f.Control.Spawn("model/entity/golditem",x=>go=x);Require(f.Manager.HasObjectPool("moneyPool")&&go,"actual registered prefab pool");f.Frame.Shutdown();Require(!go&&f.Manager.Pools.Count==0&&!f.Manager.IsInitialized&&!f.Registry.HasInstance(4058)&&f.Host.Unloads==1&&f.Frame.Started,"reverse shutdown: logic destroys pool before manager shutdown; Started retained");}});
            check("normal-lifetime-uses-getmodule-even-after-frame-cleared",()=>{using(var f=new OutgameEffectControlValidation.Fixture(frameManager:true)){f.Frame.Shutdown();Require(f.Frame.Modules.Count==0,"cleared frame");f.Control.DestoryPool();var fresh=f.Frame.HaveModule<OutgameObjectPoolManager>();Require(fresh!=null&&!fresh.IsInitialized&&!ReferenceEquals(fresh,f.Manager)&&f.Host.Unloads==2,"source generic GetModule creates new manager before no-op destroy");}});
            return r;
        }
    }
}
