using System;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameVirtualItemsValidation
    {
        sealed class Backend:IOutgameStorageBackend {public string Get(string k)=>null;public void Set(string k,string v,Action<string> f,Action c)=>c();public void Remove(string k,Action<string> f,Action c)=>c();public void Clear(Action<string> f,Action c)=>c();}
        sealed class StorageHost:IOutgameDataStorageHost {public int SourceLoginProgress=>0;public bool LoginProcedureFlag8=>false;public bool LoginStaticFlag4=>false;public bool IsUseServer=>false;public string MineGameName=>"virtual-item-fixture";public bool HasToast=>false;public void Log(string s){}public void Error(string s){}public void Toast(string s){}public string Compress(string k,string s)=>s;public string Decompress(string k,string s)=>s;public void QueueUpload(string k,string s){}}
        sealed class CommanderUI:IOutgameCommanderItemRefresh {public Action<int> Refresh;public void RefreshCommanderItem(int id)=>Refresh(id);}
        sealed class Fixture
        {
            public readonly OutgameGlobalItemRewardsValidation.Fixture Core=new OutgameGlobalItemRewardsValidation.Fixture();public OutgameCommanderManager Commander;public List<int> HeadBoxes=new List<int>();public readonly List<int> Refreshed=new List<int>();public readonly OutgameHeadBoxInventory Heads;public readonly OutgameDicePoints Points;public readonly CommanderUI UI=new CommanderUI();
            public Fixture(){Core.Config.Instance.Items.Clear();Core.Config.Instance.InitLegacyUnityJson(new OutgameLegacyConfigRead(n=>Resources.Load<TextAsset>("Recovered/FirstPack/Config/"+n),s=>{}));var host=new StorageHost();Commander=new OutgameCommanderManager(new OutgameProfile(),BattleView.ReadText("Data/Outgame/CommanderConfig"),new OutgameDataManagerStorage(()=>"CommanderManager",host,new OutgameSdkStringStorage(new Backend(),s=>{}),new OutgameDataVersionState(()=>{},()=>{},()=>{},i=>{},s=>{})),host,s=>{});Commander.OnInit();UI.Refresh=Refreshed.Add;Heads=new OutgameHeadBoxInventory(()=>HeadBoxes,()=>Core.Messages);Points=new OutgameDicePoints(()=>Core.Global,()=>Core.Messages);Core.Services.Virtual=new OutgameVirtualItemServices{Commander=()=>Commander,CommanderUI=()=>UI,HeadBoxes=()=>Heads,DicePoints=()=>Points};}
            public OutgameItemBase Item(int id)=>(OutgameItemBase)Core.Engine.GetItem(Core.Config.Instance.Items[id]);
        }
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-virtual-original-config-creates-seven-types",()=>{var f=new Fixture();Require(f.Item(1001) is OutgameGoldItem&&f.Item(1002) is OutgameDiamondItem&&f.Item(1004) is OutgameStrengthItem&&f.Item(3001) is OutgameCommanderItem&&f.Item(8001) is OutgameHeroPieceItem&&f.Item(10004) is OutgameHeadBoxItem&&f.Item(11001) is OutgameGamePointsItem,"original JSON subtype mapping with actual constructors");Require(f.Item(1005)==null&&f.Item(4001)==null&&f.Item(5001)==null,"unsupported source subtypes retained as null");});
            check("source-virtual-commander-count-ignored-level-reset-no-inventory",()=>{var f=new Fixture();var state=f.Commander.GetCommanderData(1);state.level=8;f.Item(3001).AddItem(0);Require(state.level==1&&f.Refreshed[0]==1&&f.Core.Global.Indexes.Items.Count==0&&f.Core.Reports.Changes.Count==0&&f.Core.Reports.Uses.Count==0&&f.Core.Host.Adds==0,"zero unlock resets existing high level, no base Add/Use");state.level=9;f.Item(3001).AddItemOnlyModel(-99);Require(state.level==1&&f.Refreshed.Count==2,"model path also directly invokes Use, ignores negative count");});
            check("source-virtual-commander-refresh-failure-retains-unlock",()=>{var f=new Fixture();f.Commander.GetCommanderData(1).level=0;f.UI.Refresh=id=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Item(3001).Use(1));Require(f.Commander.GetCommanderData(1).level==1,"unlock precedes UI failure without rollback");Require(f.Commander.GetCommanderData(999)==null,"source TryGet miss null");f.Core.Config.Instance.Items[3001].paramInt=999;Throws<NullReferenceException>(()=>f.Item(3001).AddItem(5));});
            check("source-virtual-commander-rereads-config-after-ui-resolution",()=>{var f=new Fixture();var item=f.Item(3001);f.Core.Services.Virtual.CommanderUI=()=>{item.ItemConfig.paramInt=2;return f.UI;};item.Use(7);Require(f.Commander.GetCommanderData(1).level==1&&f.Refreshed[0]==2,"paramInt read independently before manager and UI calls");});
            check("source-virtual-commander-headbox-add-virtual-use-dispatch",()=>{var f=new Fixture();var a=new CommanderOverride(f.Core.Services);var b=new HeadOverride(f.Core.Services);a.AddItem(long.MinValue);a.AddItemOnlyModel(4);b.AddItem(0);b.AddItemOnlyModel(long.MaxValue);Require(a.Values.Count==2&&a.Values[0]==long.MinValue&&a.Values[1]==4&&b.Values[0]==0&&b.Values[1]==long.MaxValue,"source slot7 Use receives unchanged Int64");});
            check("source-virtual-headbox-unlock-idempotence-and-live-record",()=>{var f=new Fixture();int events=0;f.Core.Messages.AddListener("UserInfo_HeadBoxUnlock",a=>{events++;Require((int)a[0]==4&&f.HeadBoxes.Contains(4),"append before message");});f.Item(10004).AddItem(-4);f.Item(10004).AddItemOnlyModel(0);Require(events==1&&f.HeadBoxes.Count==1&&f.Core.Global.Indexes.Items.Count==0&&f.Core.Reports.Uses.Count==0,"ignore count, skip already owned, no shared inventory/report");f.HeadBoxes=new List<int>();f.Item(10004).Use(1);Require(events==2&&f.HeadBoxes.Count==1,"host resolves current record list");});
            check("source-virtual-headbox-event-failure-keeps-appended-id",()=>{var f=new Fixture();f.Core.Messages.AddListener("UserInfo_HeadBoxUnlock",a=>throw new InvalidOperationException());Throws<InvalidOperationException>(()=>f.Item(10004).AddItem(1));Require(f.HeadBoxes.Count==1&&f.HeadBoxes[0]==4,"append retained after listener fails");f.Item(10004).AddItem(1);Throws<InvalidOperationException>(()=>f.Heads.AddHeadBox(4));Require(f.HeadBoxes.Count==2,"manager AddHeadBox itself permits duplicates; control owns guard");});
            check("source-virtual-strength-normal-model-use-event-differences",()=>{var f=new Fixture();var item=f.Item(1004);int sp=0;f.Core.Messages.AddListener("SP_CHANGE",a=>{Require(a==null,"source empty overload has null args");sp++;});item.AddItem(3);Require(sp==1&&f.Core.Host.Adds==1&&f.Core.Global.GetItemCount(1004)==3,"base Add first then SP");item.AddItemOnlyModel(2);Require(sp==1&&f.Core.Host.Adds==1&&f.Core.Global.GetItemCount(1004)==5,"inherited model path has no SP");item.Use(9);Require(sp==2&&f.Core.Global.GetItemCount(1004)==5&&f.Core.Reports.Uses.Count==1,"base Use report before SP, no debit");});
            check("source-virtual-strength-base-failure-skips-sp-and-current-dispatcher",()=>{var f=new Fixture();int sp=0;f.Core.Messages.AddListener("SP_CHANGE",a=>sp++);f.Core.Host.Added=r0=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Item(1004).AddItem(2));Require(sp==0&&f.Core.Global.GetItemCount(1004)==2,"host fail leaves base inventory and skips SP");f.Core.Host.Added=r0=>{f.Core.Messages=new OutgameMessageDispatcher();f.Core.Messages.AddListener("SP_CHANGE",a=>sp+=10);};f.Item(1004).AddItem(1);Require(sp==10,"SP resolves current message service after base call");});
            check("source-virtual-heropiece-real-base-model-and-use",()=>{var f=new Fixture();var item=f.Item(8001);item.AddItem(4);item.AddItemOnlyModel(-1);item.Use(100);Require(f.Core.Global.GetItemCount(8001)==3&&f.Core.Host.Adds==1&&f.Core.Reports.Changes.Count==2&&f.Core.Reports.Uses.Count==1,"hero piece follows base methods, no invented crafting/consume");});
            check("source-virtual-gamepoints-no-double-credit-and-model-notification",()=>{var f=new Fixture();var events=new List<int>();f.Core.Messages.AddListener("Mxtz_DataChange",a=>{Require((int)a[0]==1&&f.Core.Reports.Changes.Count==events.Count+1,"notification after base report");events.Add((int)a[1]);});f.Item(11001).AddItem(5);f.Item(11001).AddItemOnlyModel(3);Require(f.Core.Global.GetItemCount(11001)==8&&events[0]==5&&events[1]==8&&f.Core.Host.Adds==1,"point callback reads final shared count without adding again");});
            check("source-virtual-dice-points-wrap-and-clamp-message-only",()=>{var f=new Fixture();f.Core.Global.Indexes.Items[11001]=new OutgameItemUserData{itemId=11001,itemCount=uint.MaxValue};int value=-9;f.Core.Messages.AddListener("Mxtz_DataChange",a=>value=(int)a[1]);Require(f.Points.GetPoint()==-1&&f.Points.ChangePoint(99)==0&&value==0&&f.Core.Global.GetItemCount(11001)==uint.MaxValue,"low32 then clamp return only, ignored delta");f.Core.Global.Indexes.Items[11001].itemCount=0x100000005L;f.Points.AddPoint(-9);Require(value==5&&f.Core.Global.GetItemCount(11001)==0x100000005L,"AddPoint ignores its input and preserves Int64 stock");});
            check("source-virtual-gamepoints-base-and-message-failure-prefix",()=>{var f=new Fixture();int events=0;f.Core.Messages.AddListener("Mxtz_DataChange",a=>{events++;throw new InvalidOperationException();});Throws<InvalidOperationException>(()=>f.Item(11001).AddItem(3));Require(f.Core.Global.GetItemCount(11001)==3&&f.Core.Host.Adds==1&&events==1,"point event failure after host/base effects");f.Core.Host.Added=rs=>throw new ApplicationException();Throws<ApplicationException>(()=>f.Item(11001).AddItem(2));Require(f.Core.Global.GetItemCount(11001)==5&&events==1,"host failure skips point notification");});
            return r;
        }
        sealed class CommanderOverride:OutgameCommanderItem {public readonly List<long> Values=new List<long>();public CommanderOverride(OutgameItemEntityServices s):base(3001,s){}public override void Use(long n)=>Values.Add(n);}
        sealed class HeadOverride:OutgameHeadBoxItem {public readonly List<long> Values=new List<long>();public HeadOverride(OutgameItemEntityServices s):base(10004,s){}public override void Use(long n)=>Values.Add(n);}
    }
}
