using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameAudioControlValidation
    {
        sealed class Node:IOutgameAudioNode
        {
            public readonly List<string> Calls;public readonly int Mode;public Action<OutgameVoiceType> Stopping;public Action Playing;public int[] LastIds,Handles;
            public Node(int mode,List<string> calls){Mode=mode;Calls=calls;Handles=new[]{100+mode};}
            public int[] Play(int[] ids){LastIds=ids;Calls.Add("play:"+Mode+":"+(ids==null?"null":string.Join(",",ids)));Playing?.Invoke();return Handles;}
            public void Stop(OutgameVoiceType voice){Calls.Add("stop:"+Mode+":"+(int)voice);Stopping?.Invoke(voice);}
            public void Pause(bool paused)=>Calls.Add("pause:"+Mode+":"+paused);public void StopByGuid(int guid)=>Calls.Add("guid:"+Mode+":"+guid);
        }
        sealed class Fixture
        {
            public readonly List<string> Calls=new List<string>();public readonly List<object[]> Events=new List<object[]>();public readonly Dictionary<int,Node> Nodes=new Dictionary<int,Node>();
            public readonly OutgameControllerRegistry Registry=new OutgameControllerRegistry();public readonly OutgameMessageDispatcher Messages=new OutgameMessageDispatcher();public OutgameUserPreferences Prefs;public readonly OutgameAudioSettings Settings;public readonly OutgameUiAudioManagerSlot Slot;public readonly OutgameAudioControl Control;public int Reads,Creations;public string Saved;public Func<int,IOutgameAudioNode> Create;public Action<object[]> Logging;
            public Fixture(){Prefs=Preferences(()=>Saved,s=>Saved=s);Prefs.OnInit(false);Messages.AddListener("GlobalVolumeChange",a=>Events.Add(a));Settings=new OutgameAudioSettings(()=>Prefs,()=>Messages);Slot=new OutgameUiAudioManagerSlot((mode,parent)=>{Require(parent==null,"source UI node parent null");Creations++;Calls.Add("create:"+mode);if(Create!=null)return Create(mode);return Nodes[mode]=new Node(mode,Calls);},a=>{Calls.Add("log:"+a[0]);Logging?.Invoke(a);});OutgameCoreControllerBindings.BindAudio(Registry,()=>Settings,()=>{Reads++;return Slot.Instance;});Control=(OutgameAudioControl)Registry.Resolve(3904);}
        }
        static OutgameUserPreferences Preferences(Func<string> read,Action<string> write)=>new OutgameUserPreferences(p=>read(),(p,s)=>write(s),()=>false,s=>{},s=>{},(c,s)=>{},s=>{});
        static void Require(bool b,string text){if(!b)throw new Exception(text);}static void Throws(Action a){try{a();}catch(InvalidOperationException){return;}throw new Exception("Missing exception");}
        static void Sequence(List<string> calls,string text)=>Require(string.Join("|",calls)==text,"Expected "+text+", got "+string.Join("|",calls));
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-audio-controller-lifecycle-empty-and-registry-release",()=>{var f=new Fixture();f.Control.OnInit();f.Control.Updata(100,200);Require(f.Reads==0&&f.Calls.Count==0,"source init/update do not create audio services");f.Control.OnDispose();var replacement=f.Registry.Resolve(3904);Require(!ReferenceEquals(replacement,f.Control),"fresh controller after static-slot release");f.Control.OnDispose();Require(!f.Registry.HasInstance(3904),"old controller also clears newer slot");});
            check("source-audio-state-routing-full-switch-defaults",()=>{var f=new Fixture();for(int i=-1;i<=12;i++){f.Control.OnGamePlayState(i);}Sequence(f.Calls,"create:1|play:1:1001|stop:1:0|create:1|play:1:1002|pause:1:False|pause:1:True|log:StopParallelNode==StopParallelNode[Music]|stop:1:1|log:StopParallelNode==StopParallelNode[Music]|stop:1:1|log:StopParallelNode==StopParallelNode[0]|stop:1:0");Require(f.Reads==8,"only source explicit cases resolve UI owner");});
            check("source-audio-pause-before-play-does-not-create-node",()=>{var f=new Fixture();f.Control.OnGamePlayState(6);f.Control.OnGamePlayState(7);f.Slot.Instance.StopParallelAudioByGUID(17);Require(f.Reads==2&&f.Creations==0&&!f.Slot.Instance.Initialized,"pause/stop do not initialize routing or nodes");});
            check("source-audio-sound-setting-silent-music-setting-notifies",()=>{var f=new Fixture();Require(f.Control.IsSoundEffect&&f.Control.IsMusicEffect,"original defaults1");f.Control.IsSoundEffect=false;Require(f.Settings.SoundGameVolume==0&&f.Events.Count==0,"sound setter does not send GlobalVolumeChange");f.Control.IsMusicEffect=false;Require(f.Settings.MusicGameVolume==0&&f.Events.Count==1&&f.Events[0][0] is OutgameVoiceType&&(OutgameVoiceType)f.Events[0][0]==OutgameVoiceType.Music&&(float)f.Events[0][1]==0,"music persists before source typed event");});
            check("source-audio-settings-strict-threshold-and-live-preferences",()=>{var f=new Fixture();f.Settings.SoundGameVolume=.99f;f.Settings.MusicGameVolume=float.NaN;Require(!f.Control.IsSoundEffect&&!f.Control.IsMusicEffect,"strict .99 and NaN");f.Settings.SoundGameVolume=.9901f;Require(f.Control.IsSoundEffect,"above threshold");f.Prefs=Preferences(()=>null,s=>{});f.Prefs.OnInit(false);Require(f.Control.IsMusicEffect&&f.Control.IsSoundEffect,"every getter resolves current preferences");});
            check("source-audio-volume-event-failure-retains-preference-write",()=>{var f=new Fixture();f.Messages.AddListener("GlobalVolumeChange",a=>throw new InvalidOperationException());Throws(()=>f.Control.IsMusicEffect=false);Require(f.Settings.MusicGameVolume==0&&f.Events.Count==1,"store precedes callback and exception propagates");});
            check("source-audio-volume-invalid-type-still-notifies-unclamped",()=>{var f=new Fixture();f.Settings.SetMusicGameVolume((OutgameVoiceType)99,-3);Require(f.Settings.MusicGameVolume==1&&f.Settings.SoundGameVolume==1&&f.Events.Count==1&&(float)f.Events[0][1]==-3,"invalid type no preference mutation, still event");f.Settings.SetMusicGameVolume(OutgameVoiceType.Sound,2.5f);Require(f.Settings.SoundGameVolume==2.5f,"no invented clamping");});
            check("source-audio-settings-save-and-reopen-isolated-disk",()=>{var path=Path.Combine(BattleBuild.Workspace,"analysis/audio-settings-restart/UserData.txt");Directory.CreateDirectory(Path.GetDirectoryName(path));var f=new Fixture();f.Prefs=Preferences(()=>null,s=>File.WriteAllText(path,s));f.Prefs.OnInit(false);f.Control.IsSoundEffect=false;f.Control.IsMusicEffect=true;f.Prefs.SetString("unrelated-probe","preserve");f.Prefs.OnSave();var reloaded=Preferences(()=>File.ReadAllText(path),s=>{});reloaded.OnInit(false);f.Prefs=reloaded;Require(!f.Control.IsSoundEffect&&f.Control.IsMusicEffect&&reloaded.GetString("unrelated-probe")=="preserve","actual source UserDataPrefs schema disk roundtrip, unrelated key retained");});
            check("source-ui-audio-three-lazy-nodes-and-array-identity",()=>{var f=new Fixture();var ui=f.Slot.Instance;var ids=new[]{2012,2013};var handles=ui.Play(3,ids);ui.Play(3,ids);ui.Play(2,2001);ui.Play(1,1001);Require(f.Creations==3&&ReferenceEquals(f.Nodes[3].LastIds,ids)&&ReferenceEquals(f.Nodes[3].Handles,handles)&&ui.Initialized,"source mode slots cache independent nodes and pass arrays without copying");});
            check("source-ui-audio-invalid-mode-initializes-without-factory",()=>{var f=new Fixture();Require(f.Slot.Instance.Play(0,1001)==null&&f.Slot.Instance.Initialized&&f.Creations==0,"unknown mode null after route initialization");});
            check("source-ui-audio-null-factory-retries-and-play-failure-keeps-node",()=>{var f=new Fixture();f.Create=mode=>null;Require(f.Slot.Instance.Play(1,1001)==null&&f.Creations==1,"source factory null yields null");f.Create=mode=>{var node=new Node(mode,f.Calls);node.Playing=()=>throw new InvalidOperationException();return node;};Throws(()=>f.Slot.Instance.Play(1,1001));Throws(()=>f.Slot.Instance.Play(1,1001));Require(f.Creations==2&&f.Slot.Instance.ParallelNode!=null,"assignment precedes Play and survives failure");});
            check("source-ui-audio-stopall-partial-failure-order",()=>{var f=new Fixture();var ui=f.Slot.Instance;ui.Play(1,1001);ui.Play(2,1002);ui.Play(3,2001);f.Nodes[2].Stopping=v=>throw new InvalidOperationException();f.Calls.Clear();Throws(ui.StopAll);Sequence(f.Calls,"stop:1:0|stop:2:0");Require(ui.ParallelNode==null&&ReferenceEquals(ui.SequenceNode,f.Nodes[2])&&ui.SingleNode!=null,"clear each slot only after its Stop returns");});
            check("source-ui-audio-stopall-callback-can-replace-later-node",()=>{var f=new Fixture();var ui=f.Slot.Instance;ui.Play(1,1001);ui.Play(2,1002);var newSequence=new Node(22,f.Calls);f.Nodes[1].Stopping=v=>ui.SequenceNode=newSequence;f.Calls.Clear();ui.StopAll();Sequence(f.Calls,"stop:1:0|stop:22:0");Require(ui.ParallelNode==null&&ui.SequenceNode==null,"later slot read live after previous callback");});
            check("source-ui-audio-parallel-log-before-stop-and-null-node",()=>{var f=new Fixture();f.Slot.Instance.StopParallelNode(OutgameVoiceType.Music);Require(f.Creations==0&&f.Calls.Count==1,"logs even before any node exists");f.Slot.Instance.Play(1,1001);f.Logging=a=>throw new InvalidOperationException();int count=f.Calls.Count;Throws(()=>f.Slot.Instance.StopParallelNode());Require(f.Calls.Count==count+1,"failed log prevents Stop");});
            check("source-ui-audio-guid-and-pause-target-only-parallel",()=>{var f=new Fixture();var ui=f.Slot.Instance;ui.Play(1,1001);ui.Play(2,1002);ui.Play(3,2001);f.Calls.Clear();ui.StopParallelAudioByGUID(42);ui.PauseParallerNode(true);ui.StopParallelNode(OutgameVoiceType.Sound);Sequence(f.Calls,"guid:1:42|pause:1:True|log:StopParallelNode==StopParallelNode[Sound]|stop:1:2");Require(ui.ParallelNode!=null&&ui.SequenceNode!=null&&ui.SingleNode!=null,"selective stop preserves all node references");});
            check("source-ui-audio-destroy-releases-owner-without-stop",()=>{var f=new Fixture();var old=f.Slot.Instance;old.Play(1,1001);f.Calls.Clear();old.Destroy();var current=f.Slot.Instance;Require(!ReferenceEquals(old,current)&&old.ParallelNode!=null&&current.ParallelNode==null&&f.Calls.Count==0,"destroy only clears singleton, retained node not stopped");old.Destroy();Require(!ReferenceEquals(current,f.Slot.Instance),"old owner clears new shared slot too");});
            return r;
        }
    }
}
