using System;
using System.Collections.Generic;
using UnityEngine;
using Random=System.Random;
using AreaBattle.SharedItemConfig;
namespace AreaBattle.EditorTools
{
    public static class OutgamePackageItemsValidation
    {
        sealed class MinimumRandom:Random
        {public int Calls;public Action<int,int> Called;public override int Next(int min,int max){Calls++;Called?.Invoke(min,max);if(min>max)throw new ArgumentOutOfRangeException();return min;}}
        sealed class FixedRandom:Random {readonly int value;public FixedRandom(int value){this.value=value;}public override int Next(int min,int max)=>value;}
        sealed class Fixture
        {
            public readonly OutgameGlobalItemRewardsValidation.Fixture Core=new OutgameGlobalItemRewardsValidation.Fixture();public readonly OutgameItemManager Manager=new OutgameItemManager(null,null,null,null,null,null,null,null);public readonly MinimumRandom Shared=new MinimumRandom();public int ChanceCreations;public Func<Random> Chance=()=>new MinimumRandom();public readonly OutgamePackageServices Packages;
            public Fixture(){Core.Config.Instance.Items.Clear();Core.Config.Instance.InitLegacyUnityJson(new OutgameLegacyConfigRead(n=>Resources.Load<TextAsset>("Recovered/FirstPack/Config/"+n),s=>{}));Packages=new OutgamePackageServices{Manager=()=>Manager,NewChanceRandom=()=>{ChanceCreations++;return Chance();},Random=new GameRandomSource(Shared),Error=Core.Errors.Add};Core.Services.Packages=Packages;Core.Services.Virtual=new OutgameVirtualItemServices{DicePoints=()=>new OutgameDicePoints(()=>Core.Global,()=>Core.Messages)};}
            public OutgameItemBase Item(int id)=>(OutgameItemBase)Core.Engine.GetItem(Core.Config.Instance.Items[id]);
            public OutgameItemBase Manual(){Core.Config.Instance.Items[40000]=new GameItemConfig{id=40000,type1=9,type2=2,paramInt=20000};return Item(40000);}
        }
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-package-original-table-two-draws-without-replacement-per-package",()=>{var f=new Fixture();var rows=f.Item(20000).ItemToReward(2);Require(rows.Count==4&&rows[0].itemId==1001&&rows[0].itemCount==10&&rows[1].itemId==1002&&rows[1].itemCount==5&&rows[2].itemId==1001&&rows[3].itemId==1002&&rows[1].rewardOrder==2,"original group101 deterministic minima; fresh candidate list each package");Require(f.ChanceCreations==2&&f.Shared.Calls==8&&f.Core.Config.Instance.GetRewardItemRanges(101).Count==4&&f.Core.Global.Indexes.Items.Count==0,"one fresh chance generator/group; selection and quantity share global RNG; config cache intact");});
            check("source-package-chance-strict-threshold-and-nonpositive-count",()=>{var f=new Fixture();f.Core.Config.Instance.PackageRewards[20000][200001].rewardRandom=5000;f.Chance=()=>new FixedRandom(5000);Require(f.Item(20000).ItemToReward(1).Count==0&&f.Shared.Calls==0,"equal threshold excluded");f.Chance=()=>new FixedRandom(4999);Require(f.Item(20000).ItemToReward(1).Count==2,"strict less accepts");int calls=f.ChanceCreations;Require(f.Item(20000).ItemToReward(0).Count==0&&f.Item(20000).ItemToReward(-1).Count==0&&f.ChanceCreations==calls,"zero/negative do not draw");});
            check("source-package-weight-boundaries-zero-empty-null-and-overflow",()=>{var f=new Fixture();var a=new OutgameRewardRangeData{Weight=2};var b=new OutgameRewardRangeData{Weight=3};var rows=new List<OutgameRewardRangeData>{a,b};f.Packages.Random=new GameRandomSource(new FixedRandom(2));Require(ReferenceEquals(f.Packages.Select(rows),b),"roll at cumulative boundary selects next");a.Weight=b.Weight=0;f.Packages.Random=new GameRandomSource(f.Shared);Require(ReferenceEquals(f.Packages.Select(rows),a),"zero sum falls back to first");Throws<ArgumentOutOfRangeException>(()=>f.Packages.Select(new List<OutgameRewardRangeData>()));Require(f.Packages.Select(null)==null&&f.Core.Errors[0]=="权重随机集合不能为空","only null logs; empty reaches index0");a.Weight=int.MaxValue;b.Weight=1;Throws<ArgumentOutOfRangeException>(()=>f.Packages.Select(rows));});
            check("source-package-exhausted-candidates-fail-not-truncate",()=>{var f=new Fixture();f.Core.Config.Instance.PackageRewards[20000][200001].rewardItemCount=5;var manual=f.Manual();Throws<ArgumentOutOfRangeException>(()=>manual.ItemToReward(1));Require(f.Core.Config.Instance.GetRewardItemRanges(101).Count==4&&f.Core.Global.Indexes.Items.Count==0,"five requests over four candidates fail, original cache preserved");});
            check("source-package-inclusive-quantity-upper-bound-and-overflow",()=>{var f=new Fixture();var bounds=new List<string>();f.Shared.Called=(lo,hi)=>bounds.Add(lo+":"+hi);f.Item(20000).ItemToReward(1);Require(string.Join(",",bounds)=="0:400,10:21,0:300,5:11","weight exclusive, quantity max+1");f.Core.Config.Instance.RewardItems[101][10101].itemCountMax=int.MaxValue;Throws<ArgumentOutOfRangeException>(()=>f.Item(20000).ItemToReward(1));});
            check("source-package-auto-nested-awards-during-conversion",()=>{var f=new Fixture();var rows=f.Item(20001).ItemToReward(1);Require(rows.Count==1&&rows[0].itemId==11001&&rows[0].itemCount==10&&f.Core.Global.GetItemCount(11001)==0,"outer row returned but not yet awarded");Require(f.Core.Global.GetItemCount(8101)==1&&f.Manager.PackageOpenRewardsTemp.Count==1&&f.Manager.PackageOpenRewardsTemp.First.Value.itemId==8101&&f.Core.Reports.Uses.Count==1&&f.Core.Host.Adds==1,"nested8000 AddItem immediately opens and awards original hero-piece group");});
            check("source-package-use-nested-queue-order-and-shared-row-references",()=>{var f=new Fixture();f.Item(20001).AddItem(1);var queued=f.Manager.GetPackageOpenReward();Require(queued.Count==2&&queued[0].itemId==8101&&queued[1].itemId==11001&&ReferenceEquals(queued[1],f.Core.Host.Last[0]),"nested rewards enqueued before outer rows; references preserved");Require(f.Core.Global.GetItemCount(8101)==1&&f.Core.Global.GetItemCount(11001)==10&&f.Core.Reports.Uses.Count==2&&f.Core.Host.Adds==2,"all actual nested entities and global engine applied");Require(f.Core.Global.GetItemCount(20001)==0&&f.Core.Global.GetItemCount(8000)==0,"no implicit package balance addition/debit");});
            check("source-package-manual-add-versus-use-source-virtual-conversion",()=>{var f=new Fixture();var manual=f.Manual();manual.AddItem(1);Require(f.Core.Global.GetItemCount(1001)==10&&f.Core.Global.GetItemCount(1002)==5&&f.Manager.PackageOpenRewardsTemp.Count==0&&f.Core.Reports.Uses.Count==0&&f.Core.Host.Adds==1,"base Add uses virtual conversion, no Use queue/report");manual.Use(1);Require(f.Core.Global.GetItemCount(1001)==20&&f.Manager.PackageOpenRewardsTemp.Count==2&&f.Core.Reports.Uses.Count==1&&f.Core.Host.Adds==2,"explicit Use first reports then queues/awards");});
            check("source-package-auto-model-add-invokes-full-use",()=>{var f=new Fixture();f.Item(20000).AddItemOnlyModel(1);Require(f.Core.Host.Adds==1&&f.Manager.PackageOpenRewardsTemp.Count==2&&f.Core.Reports.Uses.Count==1,"auto model path calls Use and host, does not suppress it");var overrideItem=new AutoOverride(f.Core.Services);overrideItem.AddItem(long.MinValue);overrideItem.AddItemOnlyModel(long.MaxValue);Require(overrideItem.Values[0]==long.MinValue&&overrideItem.Values[1]==long.MaxValue,"unchanged long argument via virtual Use");});
            check("source-package-use-failure-prefix-report-then-queue-then-award",()=>{var f=new Fixture();f.Core.Reports.Sending=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Item(20000).Use(1));Require(f.ChanceCreations==0&&f.Manager.PackageOpenRewardsTemp.Count==0,"base report failure stops draw");f.Core.Reports.Sending=null;f.Core.Engine.AddRewardsByItemSelfDel=rows=>throw new ApplicationException();Throws<ApplicationException>(()=>f.Item(20000).Use(1));Require(f.Manager.PackageOpenRewardsTemp.Count==2&&f.Core.Global.Indexes.Items.Count==0,"complete queue retained before failed award");});
            check("source-package-current-manager-resolved-per-enqueue-row",()=>{var f=new Fixture();var second=new OutgameItemManager(null,null,null,null,null,null,null,null);int calls=0;f.Packages.Manager=()=>++calls==1?f.Manager:second;f.Item(20000).Use(1);Require(f.Manager.PackageOpenRewardsTemp.Count==1&&second.PackageOpenRewardsTemp.Count==1&&calls==2,"each AddLast rereads manager singleton");});
            check("source-package-auto-missing-config-differs-from-base",()=>{var f=new Fixture();f.Core.Config.Instance.Items.Remove(1001);Throws<KeyNotFoundException>(()=>f.Item(20000).ItemToReward(1));Require(f.Shared.Calls==1,"auto validates selected item before quantity roll");var rows=f.Manual().ItemToReward(1);Require(rows.Count==2&&rows[0].itemId==1001,"base conversion does not look up reward item config");});
            check("source-package-live-outer-group-and-negative-pick-count",()=>{var f=new Fixture();f.Core.Config.Instance.PackageRewards[20000][200001].rewardItemCount=-1;Require(f.Item(20000).ItemToReward(1).Count==0&&f.ChanceCreations==1&&f.Shared.Calls==0,"chance and range lookup still run but no picks");f.Core.Config.Instance.PackageRewards[20000][200001].rewardItemCount=2;f.Shared.Called=(lo,hi)=>{if(lo==10)f.Core.Config.Instance.PackageRewards[20000].Add(1,new GamePackageConfig());};Throws<InvalidOperationException>(()=>f.Item(20000).ItemToReward(1));});
            return r;
        }
        sealed class AutoOverride:OutgameAutoPackageItem {public readonly List<long> Values=new List<long>();public AutoOverride(OutgameItemEntityServices s):base(20000,s){}public override void Use(long n)=>Values.Add(n);}
    }
}
