using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameWxAvatarValidation
    {
        public sealed class Request:IOutgameAvatarRequest
        {
            public bool Success=true;public string Error=>"fixture download failed";public bool Succeeded=>Success;
            public Texture2D Texture;public Func<Texture2D> Content;public int Sent,Reads;
            public object Token=new object();public object Send(){Sent++;return Token;}
            public Texture2D GetContent(){Reads++;return Content!=null?Content():Texture;}
        }
        sealed class Fixture:IDisposable
        {
            public readonly OutgameMessageDispatcher Messages=new OutgameMessageDispatcher();public readonly List<string> Trace=new List<string>();
            public readonly Queue<IEnumerator> Pending=new Queue<IEnumerator>();public readonly Request Request=new Request();
            public readonly OutgameWxAvatarServices Services;public readonly OutgameWxAvatar Avatar;public readonly Texture2D Texture=new Texture2D(8,6);
            public int Refreshed;
            public Fixture(){Request.Texture=Texture;Services=new OutgameWxAvatarServices{Messages=()=>Messages,StartCoroutine=Pending.Enqueue,Request=url=>Request,Log=Trace.Add};Avatar=new OutgameWxAvatar(Services);Messages.AddListener("Avatar_Refresh",a=>{Require(a==null,"null source payload");Refreshed++;Trace.Add("refresh");});}
            public IEnumerator Begin(){var e=Pending.Dequeue();Require(e.MoveNext()&&e.Current==Request.Token&&Request.Sent==1,"real iterator first yield");return e;}
            public void Dispose(){foreach(var p in Avatar.Sprites)if(p.Key!="default"&&p.Value)UnityEngine.Object.DestroyImmediate(p.Value);UnityEngine.Object.DestroyImmediate(Texture);}
        }
        static void Require(bool b,string why){if(!b)throw new Exception(why);}
        static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion,limitations="WXAvatar original default asset/cache/iterator/callback semantics with deterministic request fixtures; native UnityWebRequest and TopInfo/UserDataPrefs/shared-account file restart tested separately. Platform auth event remains explicit test stimulus; production Main/SDK not claimed."};
            Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id="wx-avatar-"+id,result="pass"});}catch(Exception e){r.passed=false;r.checks.Add(new BattleBuild.Check{id="wx-avatar-"+id,result="fail",detail=e.ToString()});}};
            check("original-default-resource-geometry-and-initialization",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();var s=f.Avatar.Sprites["default"];Require(f.Avatar.Initialized&&s.name=="defaultIcon"&&s.pixelsPerUnit==80&&s.vertices.Length==7&&s.triangles.Length==15&&s.rect==new Rect(0,0,128,128)&&s.texture==f.Avatar.Textures["default"],"original resource identity/geometry");var source=LitJson.JsonMapper.ToObject(System.IO.File.ReadAllText(System.IO.Path.Combine(BattleBuild.Target,"generated/unity-assets/Sprite/defaultIcon__resources_assets__78.json")));string hex=(string)source["m_RD"]["m_VertexData"]["m_DataSize"]["bytesHex"];var bytes=new byte[hex.Length/2];for(int i=0;i<bytes.Length;i++)bytes[i]=Convert.ToByte(hex.Substring(i*2,2),16);var vertices=s.vertices;for(int i=0;i<7;i++)Require(vertices[i].x==BitConverter.ToSingle(bytes,12*i)&&vertices[i].y==BitConverter.ToSingle(bytes,12*i+4),"original source vertex "+i);var indices=s.triangles;for(int i=0;i<indices.Length;i++)Require(indices[i]==((int)source["m_RD"]["m_IndexBuffer"][2*i]|((int)source["m_RD"]["m_IndexBuffer"][2*i+1]<<8)),"original source index "+i);var physics=new List<Vector2>();s.GetPhysicsShape(0,physics);Require(physics.Count==25,"original physics count");for(int i=0;i<physics.Count;i++)Require(Mathf.Abs(physics[i].x-(float)(double)source["m_PhysicsShape"][0][i]["x"])<.000001f&&Mathf.Abs(physics[i].y-(float)(double)source["m_PhysicsShape"][0][i]["y"])<.000001f,"original physics point "+i);f.Services.LoadSprite=p=>throw new Exception("must not reload");f.Avatar.InitAtStartGame();}});
            check("initialization-prefix-failure-and-retry-collision",()=>{using(var f=new Fixture()){f.Avatar.Sprites.Add("default",null);Throws<ArgumentException>(f.Avatar.InitAtStartGame);Require(!f.Avatar.Initialized&&f.Avatar.Textures.ContainsKey("default"),"texture published before duplicate sprite failure");f.Avatar.Sprites.Clear();Throws<ArgumentException>(f.Avatar.InitAtStartGame);Require(!f.Avatar.Initialized&&!f.Avatar.Sprites.ContainsKey("default"),"retry collides with retained texture prefix");}});
            check("cached-default-synchronous-null-callback-and-null-key",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();Sprite got=null;f.Avatar.GetAvatar("default",s=>got=s);f.Avatar.GetAvatar("default",null);Require(got==f.Avatar.Sprites["default"]&&f.Pending.Count==0&&f.Avatar.Downloading.Count==0,"cached source immediately resolves");Throws<ArgumentNullException>(()=>f.Avatar.GetAvatar(null,null));}});
            check("merged-callbacks-one-download-and-notification-order",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();f.Avatar.GetAvatar("url",s=>f.Trace.Add("sprite1"));f.Avatar.GetAvatar("url",s=>f.Trace.Add("sprite2"));f.Avatar.GetAvatar("url",null);f.Avatar.TextureCallbacks.Add("url",t=>{Require(t==f.Texture&&f.Avatar.SpriteCallbacks.ContainsKey("url"),"texture first");f.Trace.Add("texture");});Require(f.Pending.Count==1&&f.Avatar.Downloading.Count==1,"deduplicated");var e=f.Begin();Require(!e.MoveNext()&&f.Refreshed==1&&!f.Avatar.TextureCallbacks.ContainsKey("url")&&!f.Avatar.SpriteCallbacks.ContainsKey("url"),"callback lists removed only after invocation");Require(f.Trace.IndexOf("texture")<f.Trace.IndexOf("sprite1")&&f.Trace.IndexOf("sprite1")<f.Trace.IndexOf("sprite2")&&f.Trace.IndexOf("sprite2")<f.Trace.IndexOf("refresh"),"source callback order");Require(f.Avatar.Sprites["url"].rect==new Rect(0,0,8,6)&&f.Avatar.Sprites["url"].pixelsPerUnit==100&&f.Avatar.Downloading.Contains("url"),"downloaded sprite default PPU and retained URL");}});
            check("failed-request-keeps-waiters-and-blocks-later-retry",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();f.Request.Success=false;int calls=0;f.Avatar.GetAvatar("bad",s=>calls++);var e=f.Begin();Require(!e.MoveNext()&&calls==0&&f.Request.Reads==0&&f.Refreshed==0&&!f.Avatar.Sprites.ContainsKey("bad")&&f.Avatar.SpriteCallbacks.ContainsKey("bad"),"failed request no content/fallback/callback/event");f.Avatar.GetAvatar("bad",s=>calls++);Require(f.Pending.Count==0&&f.Avatar.Downloading.Count==1&&f.Avatar.SpriteCallbacks["bad"].GetInvocationList().Length==2,"failed URL is permanently deduplicated in this instance");}});
            check("success-null-and-content-exception-use-default-texture",()=>{foreach(bool throws in new[]{false,true})using(var f=new Fixture()){f.Avatar.InitAtStartGame();f.Request.Content=()=>throws?throw new InvalidOperationException():null;Sprite got=null;f.Avatar.GetAvatar("empty",s=>got=s);var e=f.Begin();Require(!e.MoveNext()&&got.texture==f.Avatar.Textures["default"]&&got!=f.Avatar.Sprites["default"]&&got.pixelsPerUnit==100&&got.rect.width==128&&f.Refreshed==1,"source creates new sprite from default texture");}});
            check("missing-default-fallback-propagates-retaining-queue",()=>{using(var f=new Fixture()){f.Request.Content=()=>throw new InvalidOperationException();f.Avatar.GetAvatar("missing-default",null);var e=f.Begin();Throws<KeyNotFoundException>(()=>e.MoveNext());Require(f.Avatar.SpriteCallbacks.ContainsKey("missing-default")&&f.Refreshed==0&&!f.Avatar.Sprites.ContainsKey("missing-default"),"fallback outside catch is not swallowed/repaired");}});
            check("texture-callback-failure-retains-cache-and-both-waiters",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();int sprites=0;f.Avatar.GetAvatar("url",s=>sprites++);f.Avatar.TextureCallbacks.Add("url",t=>throw new InvalidOperationException());var e=f.Begin();Throws<InvalidOperationException>(()=>e.MoveNext());Require(f.Avatar.Sprites.ContainsKey("url")&&f.Avatar.TextureCallbacks.ContainsKey("url")&&f.Avatar.SpriteCallbacks.ContainsKey("url")&&sprites==0&&f.Refreshed==0,"callbacks outside fallback catch");f.Avatar.GetAvatar("url",s=>sprites++);Require(sprites==1&&f.Pending.Count==0,"later cached lookup synchronous despite retained failed waiters");}});
            check("sprite-callback-failure-retains-delegate-and-skips-refresh",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();f.Avatar.GetAvatar("url",s=>throw new InvalidOperationException());f.Avatar.TextureCallbacks.Add("url",null);var e=f.Begin();Throws<InvalidOperationException>(()=>e.MoveNext());Require(!f.Avatar.TextureCallbacks.ContainsKey("url")&&f.Avatar.SpriteCallbacks.ContainsKey("url")&&f.Refreshed==0,"texture null delegate removed before sprite exception");}});
            check("callback-reentry-uses-current-cache-before-removal",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();int n=0;f.Avatar.GetAvatar("url",s=>{f.Avatar.GetAvatar("url",next=>{Require(next==s,"same cached sprite");n++;});Require(f.Avatar.SpriteCallbacks.ContainsKey("url"),"removal after callback");});var e=f.Begin();Require(!e.MoveNext()&&n==1&&f.Pending.Count==0&&f.Refreshed==1,"reentrant cache callback does not start second download");}});
            check("start-host-failure-retains-download-marker",()=>{using(var f=new Fixture()){f.Services.StartCoroutine=e=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Avatar.GetAvatar("url",null));Require(f.Avatar.Downloading.Contains("url")&&f.Avatar.SpriteCallbacks.ContainsKey("url")&&f.Request.Sent==0,"marker/waiter precede host call");f.Services.StartCoroutine=f.Pending.Enqueue;f.Avatar.GetAvatar("url",null);Require(f.Pending.Count==0,"subsequent request blocked by original marker");}});
            check("iterator-dispose-does-not-cancel-or-clear",()=>{using(var f=new Fixture()){f.Avatar.InitAtStartGame();f.Avatar.GetAvatar("url",null);var e=f.Begin();((IDisposable)e).Dispose();Require(f.Avatar.Downloading.Contains("url")&&f.Avatar.SpriteCallbacks.ContainsKey("url")&&!e.MoveNext()&&f.Refreshed==1,"empty source Dispose leaves iterator continuation possible");}});
            check("preference-cache-write-failure-types-and-no-read-caching",()=>{int reads=0;var p=new OutgamePlatformStringPreferences((k,d)=>{reads++;return d;},(k,v)=>throw new InvalidOperationException());Require(p.GetString("k","one")=="one"&&p.GetString("k","two")=="two"&&reads==2,"backend reads not cached");p.Cache["k"]=7;Require(p.GetString("k","typed")=="typed","nonstring falls back");Throws<InvalidOperationException>(()=>p.SetString("k","held"));Require(p.GetString("k","fallback")=="held","cache written before backend failure");p.ClearCache();Require(p.GetString("k","fresh")=="fresh","explicit clear");});
            check("nickname-url-defaults-and-single-instance",()=>{using(var f=new Fixture()){var seen=new List<string>();var runtime=new OutgameWxAvatarRuntime(f.Services,(k,d)=>{seen.Add(k);return d;});Require(runtime.GetMyNickname()=="����ǳ�"&&runtime.GetMyAvatarUrl()=="default"&&string.Join(",",seen)=="myNickName,myAvatarUrl","original keys and corrupted default literal retained");Require(runtime.Instance==runtime.Instance&&!runtime.Instance.Initialized,"lazy constructor does not initialize default resource");}});
            check("real-userdata-disabled-save-still-allows-source-pool-call",()=>{using(var f=new OutgameTopInfoPageValidation.Fixture()){var match=OutgameMatchValidation.AttachTopInfo(f);var file=new OutgameWebGlFileStorage(f.Account.Statistics.Strings,()=>false,x=>{});int warnings=0;var prefs=file.CreatePreferences(()=>true,x=>{},x=>warnings++,(c,x)=>{},x=>{});prefs.OnInit(false);prefs.SetInt("pending",3);var runtime=new OutgameWxAvatarRuntime(new OutgameWxAvatarServices{Messages=()=>f.Messages,StartCoroutine=e=>{throw new Exception("default must be cached");},Log=x=>{}},(k,d)=>k=="myNickName"?"actual-name":"default");runtime.InitAtStartGame();runtime.BindTopInfo(f.Services,()=>prefs);f.Start();f.Page.AvatarAuthorized(new object[]{"a","b"});Require(warnings==1&&f.Account.Statistics.Strings.GetString("UserData.txt","")==""&&LitJson.JsonMapper.ToObject<OutgameMatchData>(f.Account.Stored("MatchManager")).rankData.nick=="actual-name"&&f.Page.WechatHead.sprite==runtime.Instance.Sprites["default"],"UserData save returns when disabled; original caller proceeds to enabled pool save");}});
            check("real-userdata-write-failure-stops-match-pool-save",()=>{using(var f=new OutgameTopInfoPageValidation.Fixture()){var match=OutgameMatchValidation.AttachTopInfo(f);var prefs=new OutgameUserPreferences(k=>"{}",(k,t)=>throw new System.IO.IOException("write failed"),()=>false,x=>{},x=>{},(c,x)=>{},x=>{});prefs.OnInit(false);prefs.SetInt("pending",3);var runtime=new OutgameWxAvatarRuntime(new OutgameWxAvatarServices{Messages=()=>f.Messages,StartCoroutine=e=>{throw new Exception("default must be cached");},Log=x=>{}},(k,d)=>k=="myNickName"?"before-failure":"default");runtime.InitAtStartGame();runtime.BindTopInfo(f.Services,()=>prefs);f.Start();Throws<System.IO.IOException>(()=>f.Page.AvatarAuthorized(new object[]{"a","b"}));Require(match.Manager.Data.rankData.isGetWechatInfo&&f.Page.MatchNameText.text=="before-failure"&&f.Page.WechatHead.sprite==runtime.Instance.Sprites["default"]&&f.Account.Stored("MatchManager")=="","actual UserData file error propagates after avatar/name updates and before pool persistence");}});
            return r;
        }
    }
}
