using System;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameAudioManagerValidation
    {
        sealed class Fixture:IDisposable
        {
            public readonly OutgameAudioPlaybackValidation.Fixture Audio=new OutgameAudioPlaybackValidation.Fixture();
            public readonly GameObject CameraRoot=new GameObject("AudioManagerCamera");public readonly OutgameAudioManagerServices Services;public readonly OutgameAudioManager M;public readonly List<string> Events=new List<string>();public List<OutgameAudioData> Rows=new List<OutgameAudioData>();public bool HasConfig=true,NewResources;int id;
            readonly List<UnityEngine.Object> roots=new List<UnityEngine.Object>();
            public Fixture(){var camera=CameraRoot.AddComponent<Camera>();Services=new OutgameAudioManagerServices{Actions=Audio.Services,HasConfigResource=()=>HasConfig,UseNewResources=()=>NewResources,ReadAudioConfig=()=>Rows,ReadOnceConfig=d=>Events.Add("once"),UiCamera=()=>camera,RandomRange=(a,b)=>++id,Log=a=>Events.Add("log:"+a[0]),Error=a=>Events.Add("error:"+a[0]),Warning=a=>Events.Add("warning:"+a[0]),Persist=o=>{roots.Add(o);Events.Add("persist");},Destroy=o=>{Events.Add("destroy:"+o.name);UnityEngine.Object.DestroyImmediate(o);}};M=new OutgameAudioManager(Services);}
            public void Dispose(){if(M.Listener)UnityEngine.Object.DestroyImmediate(M.Listener.gameObject);foreach(var o in roots)if(o)UnityEngine.Object.DestroyImmediate(o);UnityEngine.Object.DestroyImmediate(CameraRoot);Audio.Dispose();}
        }
        sealed class Node:OutgameAudioNode
        {public Action StopAction;public int Stops,Destroys;public Node(GameObject p,int id):base(p,id,"probe",null,null,null,UnityEngine.Object.DestroyImmediate){}public override int[] Play(int[] ids)=>null;public override void Pause(bool b){}public override void Stop(OutgameVoiceType voice){if(voice!=0)throw new Exception("voice");Stops++;StopAction?.Invoke();}public override void Destroy(){Destroys++;}}
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-audio-manager-original55rows-and53once-durations",()=>{using(var f=new Fixture()){var reader=new OutgameAudioConfigReader(n=>Resources.Load<TextAsset>("Recovered/FirstPack/Config/"+n),()=>true,()=>false,f.Services.Error);f.Services.ReadAudioConfig=reader.ReadAudio;f.Services.ReadOnceConfig=reader.ReadOnce;f.M.InitAudioManager();Require(f.M.AudioData.Count==55&&f.M.OnceDurations.Count==53&&f.M.UseOnceAudio&&f.M.Initialized,"original tables loaded");Require(f.M.GetAudioData(1001).Ptype==4&&f.M.GetAudioData(1002).Ptype==2&&f.M.GetAudioData(2001).Ptype==1&&f.M.GetAudioData(1001).Vol==.4f,"original factory types and volumes");Require(f.M.GetOnceAudioDuration("Audio/Once/ui/button_normal.mp3")==.12f,"original case-sensitive once name/duration");}});
            check("source-audio-manager-missing-config-keeps-old-map",()=>{using(var f=new Fixture()){f.M.AudioData=new Dictionary<int,OutgameAudioData>{{7,new OutgameAudioData{id=7}}};f.HasConfig=false;f.M.InitAudioManager();Require(!f.M.Initialized&&f.M.AudioData.ContainsKey(7)&&!f.M.Root&&f.Events.Count==1,"source missing bundle logs before replacing map or creating roots");f.NewResources=true;f.M.InitAudioManager();Require(f.M.Initialized&&f.M.AudioData.Count==0&&f.M.Root,"new-resource mode bypasses legacy bundle requirement");}});
            check("source-audio-manager-null-list-initializes-and-repeat-guard",()=>{using(var f=new Fixture()){f.Rows=null;f.M.InitAudioManager();var map=f.M.AudioData;var root=f.M.Root;f.Services.ReadAudioConfig=()=>throw new Exception();f.M.InitAudioManager();Require(f.M.Initialized&&map.Count==0&&ReferenceEquals(map,f.M.AudioData)&&root==f.M.Root,"null rows still initialize, repeat no work");}});
            check("source-audio-manager-duplicates-keep-first-but-scan-path",()=>{using(var f=new Fixture()){var first=new OutgameAudioData{id=1,ResPath="Audio/loop/a.wav"};f.Rows.Add(first);f.Rows.Add(new OutgameAudioData{id=1,ResPath="AUDIO/ONCE/b.wav"});f.M.InitAudioManager();Require(ReferenceEquals(f.M.GetAudioData(1),first)&&f.M.UseOnceAudio&&f.Events.Contains("once")&&f.Events.Contains("error:表[音效表]中有相同键(1)"),"duplicate skipped in dict but still scanned for once path");}});
            check("source-audio-manager-row-error-retains-prefix-and-allows-retry",()=>{using(var f=new Fixture()){f.Rows.Add(new OutgameAudioData{id=1,ResPath=null});Throws<NullReferenceException>(f.M.InitAudioManager);Require(f.M.AudioData.ContainsKey(1)&&!f.M.Initialized&&f.M.OnceDurations==null,"dictionary insertion precedes path failure");f.Rows[0].ResPath="a.wav";f.M.InitAudioManager();Require(f.M.Initialized&&f.M.AudioData.Count==1,"retry replaces map");}});
            check("source-audio-manager-once-error-precedes-flag-and-root",()=>{using(var f=new Fixture()){f.Rows.Add(new OutgameAudioData{id=1,ResPath="audio/once/x"});f.Services.ReadOnceConfig=d=>{d.Add("x",1);throw new InvalidOperationException();};Throws<InvalidOperationException>(f.M.InitAudioManager);Require(f.M.UseOnceAudio&&!f.M.Initialized&&f.M.OnceDurations["x"]==1&&!f.M.Root,"once loader failure retains partial duration map");}});
            check("source-audio-manager-root-failure-after-initialized-prevents-retry",()=>{using(var f=new Fixture()){f.Services.UiCamera=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(f.M.InitAudioManager);Require(f.M.Initialized&&f.M.Root&&!f.M.Listener,"flag/root committed before camera lookup");f.Services.ReadAudioConfig=()=>throw new Exception();f.M.InitAudioManager();Require(!f.M.Listener,"repeat guard prevents repairing listener automatically");}});
            check("source-audio-manager-root-listener-lazy-and-parent-world-position",()=>{using(var f=new Fixture()){f.CameraRoot.transform.position=new Vector3(3,4,5);f.M.InitAudioManager();Require(f.M.Root.name=="AudioRoot"&&f.M.Listener.name=="AudioListener"&&f.M.Listener.transform.parent==f.CameraRoot.transform&&f.M.Listener.transform.position==Vector3.zero,"listener uses world-position-stays parenting");f.M.MoveAudioListen(0);Require(f.M.Listener.transform.parent==f.CameraRoot.transform,"non1 does not detach existing listener");Require(f.M.Root.transform.parent==null,"audio root independent of UI camera");}});
            check("source-audio-manager-move-queries-camera-before-listener",()=>{using(var f=new Fixture()){f.Services.UiCamera=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.M.MoveAudioListen(0));Require(!f.M.Listener,"even non1 queries module camera before creating listener");}});
            check("source-audio-manager-node-types-parent-names-and-invalid-type",()=>{using(var f=new Fixture()){var a=f.M.CreateNode(1);var b=f.M.CreateNode(2);var c=f.M.CreateNode(3);Require(a is OutgameAudioParallel&&b is OutgameAudioSequence&&c is OutgameAudioSingle&&a.Root.name=="parallel_1"&&b.Root.name=="sequence_2"&&c.Root.name=="single_3","source factories and random ids");Require(a.Root.transform.parent==f.M.Root.transform&&f.M.Nodes.Count==3&&!f.M.Initialized,"CreateNode creates roots but not config");Require(f.M.CreateNode(77)==null&&f.M.Nodes.Count==3,"invalid type still draws id but does not register");var custom=f.M.CreateNode(1,f.CameraRoot);Require(custom.Root.transform.parent==f.CameraRoot.transform,"supplied native parent retained");}});
            check("source-audio-manager-collision-recurses-but-returns-original-id",()=>{using(var f=new Fixture()){var numbers=new Queue<int>(new[]{7,7,8});f.Services.RandomRange=(a,b)=>numbers.Dequeue();var first=f.M.CreateNode(1);var second=f.M.CreateNode(2);Require(first.NodeId==7&&second.NodeId==7&&f.M.Nodes.Count==1&&ReferenceEquals(f.M.Nodes[7],second)&&first.Root,"recursive retry result discarded, set_Item overwrites tracked node without destroying old root");}});
            check("source-audio-manager-clear-stops-not-destroys-and-preserves-caches",()=>{using(var f=new Fixture()){f.M.InitAudioManager();var node=new Node(f.M.Root,1);f.M.Nodes.Add(1,node);f.M.UseOnceAudio=true;f.M.OnceDurations["x"]=1;f.M.AndroidIds[2]="sdk";node.StopAction=()=>Require(f.M.AudioData!=null&&f.M.Initialized&&f.M.Nodes.Count==1,"stop precedes clear/reset");f.M.ClearNode();Require(node.Stops==1&&node.Destroys==0&&f.M.Nodes.Count==0&&f.M.AudioData.Count==0&&!f.M.Initialized&&f.M.Root&&f.M.Listener&&f.M.UseOnceAudio&&f.M.OnceDurations.Count==1&&f.M.AndroidIds.Count==1,"clear retained root/listener/once/android state");}});
            check("source-audio-manager-stop-failure-prevents-clear-and-destroy",()=>{using(var f=new Fixture()){f.M.InitAudioManager();var node=new Node(f.M.Root,1){StopAction=()=>throw new InvalidOperationException()};f.M.Nodes.Add(1,node);Throws<InvalidOperationException>(f.M.Destroy);Require(f.M.Initialized&&f.M.Nodes.Count==1&&f.M.Root&&f.M.Listener,"failure aborts later destruction");}});
            check("source-audio-manager-live-node-enumerator-modification-fails",()=>{using(var f=new Fixture()){f.M.InitAudioManager();var node=new Node(f.M.Root,1){StopAction=()=>f.M.Nodes.Add(2,new Node(f.M.Root,2))};f.M.Nodes.Add(1,node);Throws<InvalidOperationException>(f.M.ClearNode);Require(f.M.Initialized&&f.M.Nodes.Count==2,"live foreach mutation failure retained");}});
            check("source-audio-manager-destroy-clears-ui-slot-not-manager-slot",()=>{using(var f=new Fixture()){var slot=new OutgameAudioManagerSlot(()=>f.Services);var m=slot.Instance;m.InitAudioManager();var ui=m.UiSlot.Instance;m.Destroy();Require(ReferenceEquals(m,slot.Instance)&&!ReferenceEquals(ui,m.UiSlot.Instance)&&!m.Root&&!m.Listener&&!m.Initialized,"source manager singleton retained; UI singleton recreated");Require(f.Events.FindIndex(x=>x=="destroy:AudioRoot")<f.Events.FindIndex(x=>x=="destroy:AudioListener"),"root destroyed before listener");}});
            check("source-audio-manager-retained-once-flag-forces-next-reload",()=>{using(var f=new Fixture()){f.Rows.Add(new OutgameAudioData{id=1,ResPath="audio/once/x"});f.M.InitAudioManager();f.M.ClearNode();f.Rows.Clear();f.Events.Clear();f.M.InitAudioManager();Require(f.M.UseOnceAudio&&f.Events.Contains("once"),"Clear does not reset once flag even next table has no once paths");}});
            check("source-audio-manager-once-query-gates-and-case-sensitive-names",()=>{using(var f=new Fixture()){Require(f.M.GetOnceAudioDuration(null)==0&&f.Events[0].StartsWith("error:"),"disabled once query logs and returns zero before dictionary");f.M.UseOnceAudio=true;Throws<NullReferenceException>(()=>f.M.GetOnceAudioDuration("x"));f.M.OnceDurations=new Dictionary<string,float>{{"X",2}};Require(f.M.GetOnceAudioDuration("x")==0&&f.M.GetOnceAudioDuration("X")==2&&f.M.GetAndroidAudioID(1)=="","case-sensitive lookup and absent Android id");}});
            check("source-audio-config-once-duplicate-and-invalid-float-prefix",()=>{var assets=new List<TextAsset>();try{var text=new TextAsset("{\"AudioInfos\":[{\"Name\":\"x\",\"Length\":\"1.25\"},{\"Name\":\"x\",\"Length\":\"2\"}]}");assets.Add(text);var reader=new OutgameAudioConfigReader(n=>text,()=>true,()=>false,a=>{});var d=new Dictionary<string,float>();Throws<ArgumentException>(()=>reader.ReadOnce(d));Require(d["x"]==1.25f,"direct Add keeps first then duplicate throws");text=new TextAsset("{\"AudioInfos\":[{\"Name\":\"y\",\"Length\":\"bad\"}]}");assets.Add(text);Throws<FormatException>(()=>reader.ReadOnce(d));Require(d.Count==1,"float.Parse failure propagates");}finally{foreach(var a in assets)UnityEngine.Object.DestroyImmediate(a);}});
            check("source-audio-config-missing-assets-log-and-return",()=>{var e=new List<string>();var reader=new OutgameAudioConfigReader(n=>null,()=>false,()=>false,a=>e.Add((string)a[0]));Require(reader.ReadAudio()==null,"missing AudioConfig returns null");reader.ReadOnce(new Dictionary<string,float>());Require(e.Count==3&&e[1]=="ResourcesInfo为NULL"&&e[2].StartsWith("OnceAudioConfig不存在"),"once logs no config then attempts actual load and logs missing asset");});
            return r;
        }
    }
}
