using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameAudioResourceValidation
    {
        sealed class Request:IOutgameLegacyAssetRequest{public bool Done;public UnityEngine.Object Value;public bool IsDone=>Done;public float Progress=>.25f;public UnityEngine.Object Asset=>Value;}
        sealed class Fixture:IDisposable
        {
            public bool Modern;public AudioClip Clip=AudioClip.Create("AudioProbe",16,1,8000,false);public readonly List<string> Calls=new List<string>();public IDictionary<string,AssetBundle> Packs=new Dictionary<string,AssetBundle>();public OutgameAssetProvider Provider;public OutgameAudioResources Helper;public Func<string,Task<OutgameAssetHandle>> New;public Func<string,string,Task<AudioClip>> Old;
            public Fixture(){Provider=new OutgameAssetProvider(()=>false,Calls.Add){Status=4,AssetObject=Clip};New=p=>{Calls.Add("new:"+p);return Task.FromResult(Provider.CreateHandle(p,()=>false));};Old=(b,a)=>{Calls.Add("old:"+b+":"+a);return Task.FromResult(Clip);};Helper=new OutgameAudioResources(()=>{Calls.Add("switch");return Modern;},()=>{Calls.Add("packs");return Packs;},p=>New(p),(b,a)=>Old(b,a),p=>Calls.Add("unload:"+p),s=>Calls.Add("debug:"+s),a=>Calls.Add("log:"+a[0]));}
            public void Dispose(){UnityEngine.Object.DestroyImmediate(Clip);}
        }
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-audio-resource-old-path-basename-and-log-order",()=>{using(var f=new Fixture()){Require(f.Helper.LoadAudioClip("Audio/Loop/Mix.Part.WAV").Result==f.Clip,"result");Require(string.Join("|",f.Calls)=="switch|debug:加载音频：audio/loop/mix.part.wav|debug:加载音频：Mix|packs|old:audio/loop/mix.part.wav.unity3d:Mix","case, first dot, logs and route order");}});
            check("source-audio-resource-basename-only-splits-forward-slash",()=>{using(var f=new Fixture()){f.Helper.LoadAudioClip("Audio\\UI\\A.wav").GetAwaiter().GetResult();Require(f.Calls.Contains("old:audio\\ui\\a.wav.unity3d:Audio\\UI\\A"),"backslashes preserved");}});
            check("source-audio-resource-null-path-fault-before-switch",()=>{using(var f=new Fixture()){var task=f.Helper.LoadAudioClip(null);Require(task.IsFaulted&&f.Calls.Count==0,"faulted task before mode lookup");Throws<NullReferenceException>(()=>task.GetAwaiter().GetResult());Throws<NullReferenceException>(()=>f.Helper.LoadAudioClipForNewResource(null).GetAwaiter().GetResult());}});
            check("source-audio-resource-new-handle-retained-by-both-wrappers",()=>{using(var f=new Fixture()){f.Modern=true;Require(f.Helper.LoadAudioClip("A/B.wav").Result==f.Clip&&f.Provider.RefCount==1,"clip wrapper retains handle");var h=f.Helper.LoadAudioClipForNewResource("A/C.wav").Result;Require(h.MainObject==f.Clip&&f.Provider.RefCount==2&&!f.Calls.Contains("packs"),"handle wrapper returns ownership");h.Release();Require(f.Provider.RefCount==1,"only returned handle released");}});
            check("source-audio-resource-new-wrapper-has-no-own-mode-guard",()=>{using(var f=new Fixture()){f.Helper.LoadAudioClipForNewResource("A.wav").GetAwaiter().GetResult();Require(string.Join("|",f.Calls)=="new:a.wav","source delegates guard to NewResLoadHelper");}});
            check("source-audio-resource-modern-null-and-wrong-object",()=>{using(var f=new Fixture()){f.Modern=true;f.New=p=>Task.FromResult<OutgameAssetHandle>(null);Throws<NullReferenceException>(()=>f.Helper.LoadAudioClip("a").GetAwaiter().GetResult());Require(f.Helper.LoadAudioClipForNewResource("a").Result==null,"handle wrapper permits null");var asset=new TextAsset("x");try{f.Provider.AssetObject=asset;f.New=p=>Task.FromResult(f.Provider.CreateHandle(p,()=>false));Require(f.Helper.LoadAudioClip("a").Result==null&&f.Provider.RefCount==1,"wrong type casts null without releasing");}finally{UnityEngine.Object.DestroyImmediate(asset);}}});
            check("source-audio-resource-pending-and-fault-not-fallback",()=>{using(var f=new Fixture()){var pending=new TaskCompletionSource<AudioClip>();f.Old=(b,a)=>pending.Task;var result=f.Helper.LoadAudioClip("a");Require(!result.IsCompleted,"await suspends");pending.SetException(new InvalidOperationException("transport"));Throws<InvalidOperationException>(()=>result.GetAwaiter().GetResult());Require(!f.Calls.Exists(s=>s.StartsWith("new:")),"no modern retry");}});
            check("source-audio-resource-firstpack-null-entry-no-fallback",()=>{using(var f=new Fixture()){f.Packs.Add("a.wav.unity3d",null);Throws<NullReferenceException>(()=>f.Helper.LoadAudioClip("A.wav").GetAwaiter().GetResult());Require(f.Calls.Contains("log:触发firstpackLoad:+a.wav.unity3d")&&!f.Calls.Exists(s=>s.StartsWith("old:")),"presence decides route even null bundle");}});
            check("source-audio-resource-current-culture-lowercase",()=>{using(var f=new Fixture()){var previous=CultureInfo.CurrentCulture;try{CultureInfo.CurrentCulture=new CultureInfo("tr-TR");f.Helper.LoadAudioClip("UI/I.wav").GetAwaiter().GetResult();Require(f.Calls.Contains("old:uı/ı.wav.unity3d:I"),"culture-sensitive source ToLower");}finally{CultureInfo.CurrentCulture=previous;}}});
            check("source-audio-resource-unload-order-and-live-mode",()=>{using(var f=new Fixture()){Throws<NullReferenceException>(()=>f.Helper.UnloadAudioClip(null));Require(f.Calls.Count==0,"normalize before switch even modern");f.Helper.UnloadAudioClip("Audio/A.wav");f.Modern=true;f.Helper.UnloadAudioClip("Audio/A.wav");Require(string.Join("|",f.Calls)=="switch|unload:audio/a.wav.unity3d|switch","modern suppresses legacy unload");var services=new OutgameAudioActionServices();f.Helper.Bind(services);Require(services.UseNewResourceLoader()&&services.LoadAudioClip!=null&&services.UnloadClip!=null,"action services bound");}});
            check("source-modern-resource-helper-guard-and-typed-forward",()=>{bool enabled=false;var calls=new List<string>();var h=new OutgameNewResourceAsyncHelper(()=>enabled,(p,t)=>{calls.Add(p+":"+t.Name);return Task.FromResult<OutgameAssetHandle>(null);},a=>calls.Add((string)a[0]));Require(h.LoadAssetAsync<AudioClip>(null).Result==null&&calls.Count==1&&calls[0]=="当前不是新资源加载，请确认是否添加UseNewRes宏开启","guard returns null before module");enabled=true;h.LoadAssetAsync<AudioClip>("Unchanged/WAV").GetAwaiter().GetResult();Require(calls[1]=="Unchanged/WAV:AudioClip","helper generic does not normalize");});
            check("source-legacy-asset-operation-native-request-detaches-early",()=>{var req=new Request();int loads=0;var op=new OutgameLegacyAssetOperation("b","a",typeof(AudioClip),(string n,out string e,out int m)=>{e=null;m=0;return new OutgameLegacyBundleResult();},s=>{},(b,a,t)=>{loads++;return req;});Require(!op.Update()&&!op.IsDone()&&op.Progress()==.25f,"manager stops tracking as soon as request exists");Require(!op.Update()&&loads==1&&op.MoveNext()&&op.GetAsset<AudioClip>()==null,"await independently continues");req.Done=true;Require(op.IsDone()&&!op.MoveNext(),"request done ends coroutine");});
            check("source-legacy-asset-operation-error-still-manager-pending",()=>{var logs=new List<string>();var op=new OutgameLegacyAssetOperation("b","a",typeof(AudioClip),(string n,out string e,out int m)=>{e="0";m=0;return null;},logs.Add);Require(op.Update()&&op.IsDone()&&op.Update()&&op.IsDone()&&logs.Count==2,"asset op treats any nonnull error incl0 as done but remains in manager operations");});
            check("source-assetbundle-async-null-operation-and-ignored-guard",()=>{int guards=0,loads=0,waits=0,errors=0;var h=new OutgameAssetbundleAsyncLoader(()=>{guards++;return false;},(b,a,t)=>{loads++;return null;},a=>errors++,op=>{waits++;return Task.CompletedTask;});Require(h.LoadAsset<AudioClip>("b","a").Result==null&&guards==1&&loads==1&&waits==0&&errors==0,"false guard ignored/null operation silent return");});
            check("source-assetbundle-async-null-asset-logs-after-await",()=>{var logs=new List<string>();var req=new Request();var operation=new OutgameLegacyAssetOperation("b","a",typeof(AudioClip),(string n,out string e,out int m)=>{e=null;m=0;return new OutgameLegacyBundleResult();},logs.Add,(b,a,t)=>req);operation.Update();var pending=new TaskCompletionSource<object>();var h=new OutgameAssetbundleAsyncLoader(()=>true,(b,a,t)=>operation,a=>logs.Add((string)a[0]),o=>pending.Task);var task=h.LoadAsset<AudioClip>("b","a");Require(!task.IsCompleted&&logs.Count==0,"no premature failure");req.Done=true;pending.SetResult(null);Require(task.GetAwaiter().GetResult()==null&&logs[0]=="加载资源失败:b AssName:a","failure diagnostic after completion");});
            check("source-assetbundle-async-await-fault-propagates",()=>{int errors=0;var operation=new OutgameLegacyAssetOperation("b","a",typeof(AudioClip),null,s=>{});var h=new OutgameAssetbundleAsyncLoader(()=>true,(b,a,t)=>operation,a=>errors++,o=>Task.FromException(new InvalidOperationException()));Throws<InvalidOperationException>(()=>h.LoadAsset<AudioClip>("b","a").GetAwaiter().GetResult());Require(errors==0,"await exception bypasses missing asset diagnostic");});
            return r;
        }
    }
}
