using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
namespace AreaBattle.EditorTools
{
    public static class OutgameTopInfoPageValidation
    {
        public sealed class Player:IOutgameMatchPlayerInfo {public string Nickname {get;set;}public string AvatarUrl {get;set;}public bool HasWechatInfo {get;set;}}
        public sealed class Avatar:IOutgameAvatarSource {public Action<string,Action<Sprite>> Load;public void GetAvatar(string url,Action<Sprite> done)=>Load(url,done);}
        public sealed class ReadyWait {public WaitUntil Instruction;public readonly TaskCompletionSource<bool> Done=new TaskCompletionSource<bool>();public void Complete(){Require(!Instruction.keepWaiting,"original ready predicate");Done.SetResult(true);}}
        public sealed class Fixture:IDisposable
        {
            public readonly OutgameAccountRewardsValidation.Fixture Account;
            public readonly OutgameTopInfoAssetsValidation.Fixture Effects;
            public readonly OutgameLegacyConfigManager Config;
            public readonly OutgameUserInfoRuntime UserRuntime;
            public readonly OutgameUserInfoControl User;
            public readonly OutgameUiPageServices Ui;
            public readonly OutgameTopInfoServices Services;
            public readonly OutgameAssetProvider Provider;
            public readonly OutgameUiAnimation Runner;
            public readonly OutgameUiOpenRegistry<OutgameUiPage> OpenRegistry;
            public readonly OutgameUiCloseRegistry<OutgameUiPage> CloseRegistry;
            public readonly Dictionary<string,OutgameUiPage> Pages=new Dictionary<string,OutgameUiPage>();
            public readonly Queue<IEnumerator> Loads=new Queue<IEnumerator>();public readonly List<ReadyWait> Waits=new List<ReadyWait>();
            public readonly List<string> Trace=new List<string>();public readonly List<(Image image,string name,string atlas,int mode)> Sprites=new List<(Image,string,string,int)>();
            public Player CurrentPlayer=new Player();public readonly Avatar AvatarSource=new Avatar();
            public OutgameTopInfoPage Page;public int UserOpens,UserSaves,ReadyEvents;public Action Save,SpriteRead;
            public Action<Sprite> AvatarCallback;public string AvatarRequested;
            public readonly bool Native;public Transform Layer;public OutgameMessageDispatcher Messages=>Account.Statistics.Messages;
            public Fixture(bool native=false,string path=null)
            {
                Native=native;Account=new OutgameAccountRewardsValidation.Fixture(native,path);Account.Page.Root.SetActive(false);
                Effects=new OutgameTopInfoAssetsValidation.Fixture(native);Effects.Top.SetActive(false);
                Runner=Effects.Root.AddComponent<OutgameUiAnimation>();Layer=new GameObject("UIPopup",typeof(RectTransform)).transform;Layer.SetParent(Effects.Root.transform,false);
                Config=new OutgameLegacyConfigManager(new OutgameLegacyConfigReadState(s=>{}),new OutgameConfigGlobalValues(),s=>null,()=>9,()=>200,()=>null,(s,a,o)=>{});
                var reader=new OutgameLegacyConfigRead(n=>Resources.Load<TextAsset>("Recovered/FirstPack/Config/"+n),s=>{throw new Exception(s);});reader.ReadTable(Config.dicAIName);reader.ReadTable(Config.dicCountryConfig);reader.ReadTable(Config.dicHeadport);reader.ReadTable(Config.dicHeadBox);reader.ReadTable(Config.dicLargeNum);
                UserRuntime=new OutgameUserInfoRuntime(()=>Account.Statistics.Pool,()=>Config,Account.Host,Account.Services.Storage,Account.Services.Versions,s=>{throw new Exception("Unexpected server request");},()=>456,()=>false,()=>Messages,s=>Trace.Add("role:"+s),a=>{throw new Exception("name config");});
                UserRuntime.BindController(Account.Page.Data.Registry,Account.Services.VirtualItems);
                var reg=UserRuntime.Registration;var manager=reg.Create();manager.ParticipatesInSync=reg.AutoSyn;manager.CompressData=reg.CompressData;manager.OnInit();Account.Statistics.Pool.Managers[reg.SourceTypeIndex]=manager;
                User=(OutgameUserInfoControl)Account.Page.Data.Registry.Resolve(4228);User.OnInit();
                var symbols=new OutgameBigNumberSymbols();symbols.Set(OutgameBigNumberSymbols.FromConfig(Config.dicLargeNum));
                Provider=new OutgameAssetProvider(()=>false,Trace.Add){Status=4,AssetObject=Resources.Load<GameObject>("Recovered/TopInfo/TopInfoUI")};
                var loader=new OutgameUiModernLoader((p,cb)=>{Require(p=="UI/MainMenu/TopInfoUI","source page path");var h=Provider.CreateHandle(p,()=>false);cb(h);return h;},name=>{Require(name=="UIPopup","source layer2");return Layer;},r=>{if(native)Runner.StartCoroutine(r);else Loads.Enqueue(r);},(p,l,cb)=>throw new Exception("legacy page host"));
                CloseRegistry=new OutgameUiCloseRegistry<OutgameUiPage>(Pages,p=>((IOutgameOwnedUiPage)p).CloseInModule());
                Ui=new OutgameUiPageServices{Loader=()=>loader,UsesNewResources=()=>true,Animation=Runner,CloseRegistry=()=>CloseRegistry,Messages=()=>Messages,MaximumWindowIndex=()=>throw new Exception("popup has no window index"),WideWindowSorting=()=>false,Loading=()=>Effects.Root,UnloadUnusedAssets=()=>Trace.Add("unload"),UnloadUnusedBundle=s=>Trace.Add(s),Log=Trace.Add,DestroyObject=native?(Action<GameObject>)UnityEngine.Object.Destroy:UnityEngine.Object.DestroyImmediate};
                Services=new OutgameTopInfoServices{DataPool=()=>Account.Statistics.Pool,UserInfo=()=>User,RankScore=()=>123,NumberSymbols=symbols,Warning=a=>Trace.Add("warning"),Language=key=>{Require(key=="You","source nickname key");return "You";},
                    SetSprite=(im,name,atlas,mode)=>{Sprites.Add((im,name,atlas,mode));SpriteRead?.Invoke();},Effects=()=>Effects.Module,ShowUserInfo=args=>{Require(args.Length==0,"empty original UserInfoUI arguments");UserOpens++;},
                    MatchPlayer=()=>CurrentPlayer,MyNickname=()=>"platform-nickname",MyAvatarUrl=()=>"platform-avatar",Avatars=()=>AvatarSource,SaveUserData=()=>{UserSaves++;Save?.Invoke();}};
                AvatarSource.Load=(url,cb)=>{AvatarRequested=url;AvatarCallback=cb;};
                if(!native)Services.WaitUntil=instruction=>{var w=new ReadyWait{Instruction=instruction};Waits.Add(w);return w.Done.Task;};
                var outlets=new OutgameImportedUiOutlets(File.ReadAllText(Path.Combine(BattleBuild.Target,"generated/outgame/top-info-ui-import.json")),"TopInfoUI");
                OpenRegistry=new OutgameUiOpenRegistry<OutgameUiPage>(Pages,name=>{Require(name==OutgameTopInfoPage.SourceNamespace+"."+OutgameTopInfoPage.SourceName,"source UI type");return new OutgameUiType<OutgameUiPage>(OutgameTopInfoPage.SourceName,()=>Page=new OutgameTopInfoPage(Ui,outlets,Services){Cached=!native});},(page,args)=>((IOutgameOwnedUiPage)page).Open(args),s=>{throw new Exception(s);});
                Messages.AddListener("GF_LoadUIOver",args=>{if(ReferenceEquals(args[0],Page)){ReadyEvents++;Trace.Add("ready");}});Messages.AddListener("OpenUI",args=>{if(ReferenceEquals(args[0],Page))Trace.Add("open");});Messages.AddListener("CloseUI",args=>{if(ReferenceEquals(args[0],Page))Trace.Add("close");});
                Account.Services.Tools.RefreshTopInfo=()=>Page.RefreshInfo();
            }
            public OutgameTopInfoPage Open(params object[] args)=>(OutgameTopInfoPage)OpenRegistry.Open(OutgameTopInfoPage.SourceNamespace,OutgameTopInfoPage.SourceName,args);
            public void CompleteLoad(){var e=Loads.Dequeue();Require(e.MoveNext()&&e.MoveNext()&&!e.MoveNext(),"actual two-yield load");}
            public void Start(){Open();CompleteLoad();Page.OpenParts();Waits[0].Complete();}
            public void Dispose(){if(Page!=null&&!Page.Lifetime.IsDisposed)Page.CloseUINow();Effects.Dispose();Account.Dispose();}
        }
        static void Require(bool b,string why){if(!b)throw new Exception(why);}
        static T Throws<T>(Action a)where T:Exception{try{a();}catch(T e){return e;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion,limitations="Original TopInfo owned load/outlets/Awake/profile/account/events/icons/disposal and BaseUI Await, sharing actual account/UserInfo/data-pool/effect runtime. Rank score, Match record, avatar platform/download, UserInfoUI open destination and sprite loader remain required fixture endpoints. Native open/close/storage/resource verification separate; complete production Main/platform/Player not claimed."};
            Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id="top-info-page-"+id,result="pass"});}catch(Exception e){r.passed=false;r.checks.Add(new BattleBuild.Check{id="top-info-page-"+id,result="fail",detail=e.ToString()});}};
            check("deferred-page-original25-outlets-awake-and-separate-icon-wait",()=>{using(var f=new Fixture()){var args=new object[]{7};var p=f.Open(args);Require(p.GameObject==null&&p.Lifetime.Arguments==args&&f.Provider.RefCount==1&&p.GoldEffectId==-1&&p.DiamondEffectId==-1,"original deferred ownership/ctor fields");f.CompleteLoad();Require(p.OutletCount==25&&p.UserRoot.activeSelf&&!p.MatchUserRoot.activeSelf&&!p.StaminaRoot.activeSelf&&p.NameRed!=null,"source Awake visibility/red binding");Require(p.GoldText.text=="0"&&p.DiamondsText.text=="0"&&p.NameText.text==f.User.Name&&p.ScoreText.text=="1.23","actual local/user records and recovered score formatting");Require(!p.IconInitialization.IsCompleted&&f.Effects.Module.Effects.Count==0&&f.ReadyEvents==0,"native readiness is a separate wait");f.Waits[0].Complete();Require(p.IconInitialization.IsCompleted&&f.Effects.Module.Get(p.GoldEffectId).Config.id==1007&&f.Effects.Module.Get(p.DiamondEffectId).Config.id==1019&&f.ReadyEvents==1,"ready before original two ordered effects");}});
            check("real-tool-economy-refresh-and-server-record-replacement",()=>{using(var f=new Fixture()){f.Start();f.Account.Account.Tool.ToolChange(1001,17,true,"",true);Require(f.Page.GoldText.text=="17"&&f.Account.Account.Local.GoldNum==17,"actual tool callback reaches real top Text");f.Account.Account.Local.UpdateDataCallBack("{\"goldNum\":123,\"diamondsNum\":9}");f.Page.RefreshInfo();Require(f.Page.GoldText.text=="123"&&f.Page.DiamondsText.text=="9","captured manager reads current replacement record");f.Account.Statistics.Pool.Managers.Remove(4119);f.Page.RefreshInfo();Require(f.Page.GoldText.text=="123"&&ReferenceEquals(f.Page.LocalData,f.Account.Account.Local),"manager captured in Awake; later pool removal does not re-resolve");}});
            check("loadstarting-refresh-nickname-red-score-and-distinct-sprite-fields",()=>{using(var f=new Fixture()){f.Start();f.User.Manager.Name="You";f.Services.RankScore=()=>150;f.Sprites.Clear();f.Messages.SendMessage("LoadStartingUI",new object[]{"ignored"});Require(f.Page.NameText.text=="You"&&f.Page.NameRed.activeSelf&&f.Page.ScoreText.text=="1","source nickname equality and last-zero score rule");Require(f.Sprites.Count==2&&f.Sprites[0].image==f.Page.HeadIcon&&f.Sprites[0].name==f.User.GetHeadportConfig().icon&&f.Sprites[0].atlas==f.User.GetHeadportConfig().atlas&&f.Sprites[1].image==f.Page.HeadBoxIcon&&f.Sprites[1].atlas==f.User.GetHeadBoxConfig().atlas&&f.Sprites.All(s=>s.mode==0),"original head/frame config field mapping");f.User.Manager.Name="renamed";f.Messages.SendMessage("LoadStartingUI");Require(!f.Page.NameRed.activeSelf&&f.Page.NameText.text=="renamed","later live profile refresh");}});
            check("profile-reentry-captures-name-but-rereads-current-config",()=>{using(var f=new Fixture()){f.Start();f.User.Manager.Name="before";f.Services.Language=key=>{f.User.Manager.Name="after";f.User.Manager.Data.headportId=2;return "before";};f.Sprites.Clear();f.Page.RefreshProfile();Require(f.Page.NameText.text=="before"&&f.Page.NameRed.activeSelf&&f.Sprites[0].name==f.Config.dicHeadport[2].icon&&f.User.Name=="after","nickname evaluated before language; later config follows mutated account");}});
            check("sprite-failure-preserves-earlier-profile-updates-and-skips-frame",()=>{using(var f=new Fixture()){f.Start();f.User.Manager.Name="new";f.Services.RankScore=()=>999;f.Sprites.Clear();f.SpriteRead=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(f.Page.RefreshProfile);Require(f.Page.NameText.text=="new"&&f.Page.ScoreText.text=="9.99"&&f.Sprites.Count==1,"failure after labels and head request, before frame request");}});
            check("both-user-pointers-request-empty-args-without-button-message",()=>{using(var f=new Fixture()){f.Start();int n=0;f.Messages.AddListener("GF_UIButtonClick",a=>n++);OutgameUiPointerClick.Get(f.Page.UserRoot).OnPointerClick(null);OutgameUiPointerClick.Get(f.Page.MatchUserRoot).OnPointerClick(null);Require(f.UserOpens==2&&n==0,"both GameObject source click overloads");}});
            check("auth-null-empty-single-null-element-and-gate-order",()=>{using(var f=new Fixture()){f.Start();f.Page.AvatarAuthorized(null);f.Page.AvatarAuthorized(Array.Empty<object>());Throws<IndexOutOfRangeException>(()=>f.Page.AvatarAuthorized(new object[]{"a"}));Throws<NullReferenceException>(()=>f.Page.AvatarAuthorized(new object[]{null,"b"}));Throws<NullReferenceException>(()=>f.Page.AvatarAuthorized(new object[]{"",null}));f.Page.AvatarAuthorized(new object[]{"","b"});Require(!f.CurrentPlayer.HasWechatInfo&&f.UserSaves==0,"both ToString calls occur before empty gate; source length1 failure retained");}});
            check("auth-uses-platform-values-and-orders-download-name-save",()=>{using(var f=new Fixture()){f.Start();var originalName=f.User.Name;f.Save=()=>{Require(f.CurrentPlayer.HasWechatInfo&&f.Page.MatchNameText.text=="platform-nickname"&&f.AvatarRequested=="platform-avatar","record/download/name before save");};f.Messages.SendMessage("Avatar_Refresh_OnAuth",new object[]{"event-name","event-url"});Require(f.CurrentPlayer.Nickname=="platform-nickname"&&f.CurrentPlayer.AvatarUrl=="platform-avatar"&&f.User.Name==originalName&&f.UserSaves==1,"platform projection updates Match, separate UserInfo unchanged");var sprite=f.Page.HeadIcon.sprite;f.AvatarCallback(sprite);Require(f.Page.WechatHead.sprite==sprite,"actual callback target");}});
            check("auth-captures-target-before-getter-and-reresolves-current-player",()=>{using(var f=new Fixture()){f.Start();var old=f.CurrentPlayer;var next=new Player{Nickname="replacement"};f.Services.MyNickname=()=>{f.CurrentPlayer=next;return "returned";};f.Services.MyAvatarUrl=()=>"";f.Page.AvatarAuthorized(new object[]{"a","b"});Require(old.HasWechatInfo&&old.Nickname=="returned"&&!next.HasWechatInfo&&next.AvatarUrl==""&&f.Page.MatchNameText.text=="replacement"&&f.AvatarRequested==null,"nickname captured target; later fields/rereads use replacement; empty URL skips source");}});
            check("auth-failure-keeps-prefix-and-suppresses-later-save",()=>{using(var f=new Fixture()){f.Start();f.Services.MyNickname=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Page.AvatarAuthorized(new object[]{"a","b"}));Require(f.CurrentPlayer.HasWechatInfo&&f.CurrentPlayer.Nickname==null&&f.UserSaves==0,"auth flag before platform nickname failure");f.Services.MyNickname=()=>"updated";f.AvatarSource.Load=(url,cb)=>throw new InvalidOperationException();string prior=f.Page.MatchNameText.text;Throws<InvalidOperationException>(()=>f.Page.AvatarAuthorized(new object[]{"a","b"}));Require(f.CurrentPlayer.Nickname=="updated"&&f.CurrentPlayer.AvatarUrl=="platform-avatar"&&f.Page.MatchNameText.text==prior&&f.UserSaves==0,"download failure after fields and before name/save");}});
            check("dispose-removes-listeners-closes-effects-retains-base-fields-and-clicks",()=>{using(var f=new Fixture()){f.Start();var p=f.Page;var root=p.GameObject;var args=p.Lifetime.Arguments;int a=p.GoldEffectId,b=p.DiamondEffectId;p.Dispose();Require(!p.Lifetime.IsDisposed&&p.GameObject==root&&p.Lifetime.Arguments==args&&p.OutletCount==25&&p.GoldEffectId==a&&p.DiamondEffectId==b&&f.Effects.Module.Effects.Count==0,"direct source Dispose does not call base or reset IDs");f.User.Manager.Name="ignored";f.Messages.SendMessage("LoadStartingUI");f.Messages.SendMessage("Avatar_Refresh_OnAuth",new object[]{"a","b"});Require(p.NameText.text!="ignored"&&f.UserSaves==0,"both listeners removed");OutgameUiPointerClick.Get(p.UserRoot).OnPointerClick(null);Require(f.UserOpens==1,"pointer delegate retained");}});
            check("disposal-first-effect-failure-stops-second-resolution",()=>{using(var f=new Fixture()){f.Start();int calls=0;var p=f.Page;f.Services.Effects=()=>{calls++;throw new InvalidOperationException();};Throws<InvalidOperationException>(p.Dispose);Require(calls==1&&f.Effects.Module.Effects.Count==2,"failure leaves both effects and stops second module resolution");f.Messages.SendMessage("Avatar_Refresh_OnAuth",new object[]{"a","b"});Require(f.UserSaves==0,"listeners already removed before close failure");f.Services.Effects=()=>f.Effects.Module;}});
            check("late-icon-continuation-after-direct-dispose-is-not-cancelled",()=>{using(var f=new Fixture()){f.Open();f.CompleteLoad();f.Page.Dispose();Require(f.Effects.Module.Effects.Count==0,"initial -1 closes no effect");f.Waits[0].Complete();Require(f.Effects.Module.Effects.Count==2&&!f.Page.Lifetime.IsDisposed,"source pending continuation can create after direct Dispose");}});
            check("second-icon-failure-retains-first-id-and-earlier-effects",()=>{using(var f=new Fixture()){f.Start();int oldGold=f.Page.GoldEffectId,oldDiamond=f.Page.DiamondEffectId,calls=0;f.Services.Effects=()=>{if(++calls==2)throw new InvalidOperationException();return f.Effects.Module;};var task=f.Page.InitializeIconsAsync();f.Waits.Last().Complete();Throws<InvalidOperationException>(()=>task.GetAwaiter().GetResult());Require(f.Page.GoldEffectId!=oldGold&&f.Page.DiamondEffectId==oldDiamond&&f.Effects.Module.Get(oldGold)!=null&&f.Effects.Module.Effects.Count==3,"first Show published before second failure; no rollback or older-id close");f.Services.Effects=()=>f.Effects.Module;}});
            check("auth-userdata-save-failure-prevents-pool-save-after-name",()=>{using(var f=new Fixture()){f.Start();string before=f.Account.Stored("LocalDataManager");f.Account.Services.Profile.inventory.goldNum=91;f.Save=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Page.AvatarAuthorized(new object[]{"a","b"}));Require(f.Page.MatchNameText.text=="platform-nickname"&&f.UserSaves==1&&f.Account.Stored("LocalDataManager")==before,"user prefs failure stops pool persistence after Match/text changes");}});
            check("real-uicontrol-currency-cache-follows-owned-deferred-page",()=>{using(var f=new Fixture()){var registry=f.Account.Page.Data.Registry;var control=new OutgameUiControl(null,registry,()=>f.Messages,new OutgameUiControlGlobals(),null,()=>f.Open(),null,null,null);control.ShowTopInfoUI();Require(control.TopInfo==f.Page&&control.GoldText==null&&f.Loads.Count==1,"actual UIControl holds page before async outlet init");f.CompleteLoad();f.Page.OpenParts();f.Waits[0].Complete();Require(control.GoldText==f.Page.GoldText&&control.DiamondsText==f.Page.DiamondsText,"lazy actual cache retries after outlets load");f.Page.SetVisible(false);control.ShowTopInfoUI();Require(f.Page.Visible&&f.Page.GoldRoot.activeSelf&&f.Page.DiamondRoot.activeSelf&&f.Loads.Count==0,"source UIControl reuse/show/renderer route uses same owned page");}});
            check("ready-predicate-null-disposed-live-and-callback-destruction",()=>{var bus=new OutgameMessageDispatcher();var life=new OutgameUiLifetime(null,()=>{},UnityEngine.Object.DestroyImmediate);var owner=new object();var ready=new OutgameUiReadyAwait(life,owner,()=>bus);int notices=0;Require(!ready.IsReady(),"null live waits");life.MarkDisposed();Require(ready.IsReady(),"null disposed completes without message");var go=new GameObject("ready");life.Attach(go,null);bus.AddListener("GF_LoadUIOver",a=>{Require(ReferenceEquals(a[0],owner),"original page identity");notices++;UnityEngine.Object.DestroyImmediate(go);});Require(ready.IsReady()&&notices==1&&!life.Transform,"live transform even disposed emits and returns true after callback destroys it");Require(ready.IsReady()&&notices==1,"Unity null disposed branch emits no second notice");});
            check("empty-refresh-and-missing-local-manager-retain-prefab-currency",()=>{using(var f=new Fixture()){f.Account.Statistics.Pool.Managers.Remove(4119);f.Open();f.CompleteLoad();string before=f.Page.GoldText.text;Require(f.Page.LocalData==null&&before=="19960","source missing local manager returns null and keeps original prefab text");f.Page.Refresh();Require(f.Page.GoldText.text==before,"original virtual Refresh empty");f.Waits[0].Complete();}});
            return r;
        }
    }
}
