using System;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameUpdateManagerValidation
    {
        sealed class Fixture:IDisposable
        {public readonly GameObject Root=new GameObject("UpdateManagerGolden");public readonly OutgameUpdateManager M;public Fixture(){M=Root.AddComponent<OutgameUpdateManager>();}public void Dispose(){UnityEngine.Object.DestroyImmediate(Root);}}
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-update-default-state-and-all-families-share-id",()=>{using(var f=new Fixture()){var m=f.M;Require(!m.IsPause&&m.TimePreFrame==16&&m.NextIndex==0&&m.UpdateData.Count==0,"source constructor defaults");Require(m.Register(()=>{})==1&&m.RegisterFixed(()=>{})==2&&m.RegisterForce(()=>{})==3&&m.IndexDict.Count==3,"one id dictionary for all update families");m.HandleList=null;Require(m.HandleList.Count==0,"null property gets lazily recreated");}});
            check("source-update-id-collision-scan-and-threshold-reset",()=>{using(var f=new Fixture()){var m=f.M;m.IndexDict[1]=()=>{};Require(m.Register(()=>{})==2,"skip used id");m.NextIndex=2147483645;Require(m.Register(()=>{})==2147483646&&m.NextIndex==0,"threshold resets stored sequence after returning high id");Require(m.Register(()=>{})==3,"reset sequence skips occupied ids");m.NextIndex=int.MaxValue;Require(m.Register(()=>{})==int.MinValue&&m.NextIndex==int.MinValue,"unchecked overflow retained");}});
            check("source-update-force-before-normal-fixed-independent",()=>{using(var f=new Fixture()){var events=new List<string>();f.M.Register(()=>events.Add("normal"));f.M.RegisterForce(()=>events.Add("force"));f.M.RegisterFixed(()=>events.Add("fixed"));f.M.Update();f.M.FixedUpdate();Require(string.Join(",",events)=="force,normal,fixed","native update order");}});
            check("source-update-add-same-pass-defers-but-force-to-normal-runs",()=>{using(var f=new Fixture()){var e=new List<string>();bool first=true;f.M.RegisterForce(()=>{e.Add("force");if(first){first=false;f.M.RegisterForce(()=>e.Add("new-force"));f.M.Register(()=>e.Add("new-normal"));}});f.M.Register(()=>{e.Add("normal");f.M.Register(()=>e.Add("late-normal"));});f.M.Update();Require(string.Join(",",e)=="force,normal,new-normal","each pass captures count at its start");e.Clear();f.M.Update();Require(string.Join(",",e)=="force,new-force,normal,new-normal,late-normal","same-pass additions run on later update");}});
            check("source-update-queued-removal-still-runs-current-frame",()=>{using(var f=new Fixture()){int calls=0;int second=0;f.M.Register(()=>f.M.QueueRemove(second));second=f.M.Register(()=>calls++);f.M.Update();Require(calls==1&&f.M.IndexDict.ContainsKey(second),"queued remove does not interrupt current pass");f.M.Update();Require(calls==1&&!f.M.IndexDict.ContainsKey(second),"next frame removes before dispatch");}});
            check("source-update-paused-retains-removal-and-gates-force-fixed",()=>{using(var f=new Fixture()){int calls=0,id=f.M.Register(()=>calls++);f.M.RegisterForce(()=>calls++);f.M.RegisterFixed(()=>calls++);f.M.QueueRemove(id);f.M.IsPause=true;f.M.Update();f.M.FixedUpdate();Require(calls==0&&f.M.RemoveIds.Count==1&&f.M.IndexDict.ContainsKey(id),"pause gates whole update including queue processing, and fixed");f.M.IsPause=false;f.M.Update();Require(calls==1&&!f.M.IndexDict.ContainsKey(id),"resume drains queue then invokes remaining force");}});
            check("source-update-fixed-does-not-drain-removal-queue",()=>{using(var f=new Fixture()){int calls=0,id=f.M.RegisterFixed(()=>calls++);f.M.QueueRemove(id);f.M.FixedUpdate();f.M.FixedUpdate();Require(calls==2&&f.M.RemoveIds.Count==1,"fixed keeps invoking until Update drains");f.M.Update();f.M.FixedUpdate();Require(calls==2&&f.M.IndexDict.Count==0,"Update removes fixed family");}});
            check("source-update-removal-queues-dedupe-and-replace-only-nonempty",()=>{using(var f=new Fixture()){Action callback=()=>{};f.M.QueueRemove(7);f.M.QueueRemove(7);f.M.QueueRemove(callback);f.M.QueueRemove(callback);var ids=f.M.RemoveIds;var handles=f.M.RemoveHandles;Require(ids.Count==1&&handles.Count==1,"IndexOf prevents duplicate removal requests");f.M.ProcessRemovals();Require(!ReferenceEquals(ids,f.M.RemoveIds)&&!ReferenceEquals(handles,f.M.RemoveHandles)&&ids.Count==1&&handles.Count==1,"replace queue objects rather than Clear");ids=f.M.RemoveIds;handles=f.M.RemoveHandles;f.M.ProcessRemovals();Require(ReferenceEquals(ids,f.M.RemoveIds)&&ReferenceEquals(handles,f.M.RemoveHandles),"empty queue references retained");}});
            check("source-update-remove-delegate-prefers-normal-over-force-plus-fixed",()=>{using(var f=new Fixture()){Action callback=()=>{};int normal=f.M.Register(callback),force=f.M.RegisterForce(callback),fixedId=f.M.RegisterFixed(callback);f.M.RemoveNow(callback);Require(f.M.HandleList.Count==0&&f.M.ForceHandleList.Count==1&&f.M.FixedUpdateHandle.Count==0,"normal OR force, plus fixed removal");Require(!f.M.IndexDict.ContainsKey(normal)&&f.M.IndexDict.ContainsKey(force)&&f.M.IndexDict.ContainsKey(fixedId),"only first dictionary matching key removed even across families");}});
            check("source-update-id-removal-can-delete-earlier-equal-delegate-index",()=>{using(var f=new Fixture()){Action callback=()=>{};int first=f.M.Register(callback),second=f.M.Register(callback);f.M.RegisterData(first,"first","one",a=>{});f.M.RegisterData(second,"second","two",a=>{});f.M.RemoveNow(second);Require(!f.M.IndexDict.ContainsKey(first)&&f.M.IndexDict.ContainsKey(second)&&f.M.HandleList.Count==1,"requested second id resolves delegate, removes first equal id");Require(f.M.UpdateData.ContainsKey(first)&&!f.M.UpdateData.ContainsKey(second),"debug data removal still uses requested id");}});
            check("source-update-delegate-removal-keeps-debug-data",()=>{using(var f=new Fixture()){Action callback=()=>{};int id=f.M.Register(callback);f.M.RegisterData(id,"name","handle",a=>{});f.M.QueueRemove(callback);f.M.Update();Require(f.M.UpdateData.ContainsKey(id)&&f.M.IndexDict.Count==0,"delegate removal never touches debug records");f.M.QueueRemove(id);f.M.Update();Require(f.M.UpdateData.ContainsKey(id),"missing id short-circuits debug cleanup");}});
            check("source-update-id-removals-before-delegate-removals",()=>{using(var f=new Fixture()){Action callback=()=>{};int a=f.M.Register(callback),b=f.M.Register(callback);f.M.RegisterData(a,"a","a",x=>{});f.M.RegisterData(b,"b","b",x=>{});f.M.QueueRemove(callback);f.M.QueueRemove(b);f.M.ProcessRemovals();Require(f.M.IndexDict.Count==0&&f.M.HandleList.Count==0&&f.M.UpdateData.ContainsKey(a)&&!f.M.UpdateData.ContainsKey(b),"id pass executes before delegate pass regardless of queued chronology");}});
            check("source-update-negative-id-removes-callback-but-leaves-index",()=>{using(var f=new Fixture()){f.M.NextIndex=int.MaxValue;int id=f.M.Register(()=>{});f.M.RegisterData(id,"negative","x",a=>{});f.M.QueueRemove(id);f.M.Update();Require(id==int.MinValue&&f.M.HandleList.Count==0&&f.M.IndexDict.ContainsKey(id)&&!f.M.UpdateData.ContainsKey(id),"RemoveNow only removes found key when >=0");}});
            check("source-update-null-normal-throws-fixed-null-skips",()=>{using(var f=new Fixture()){f.M.RegisterFixed(null);int calls=0;f.M.RegisterFixed(()=>calls++);f.M.FixedUpdate();Require(calls==1,"fixed skips null");f.M.Register(null);f.M.Register(()=>calls++);Throws<NullReferenceException>(f.M.Update);Require(calls==1,"normal directly invokes null and aborts later callbacks");}});
            check("source-update-callback-error-aborts-later-passes",()=>{using(var f=new Fixture()){int calls=0;int id=f.M.RegisterForce(()=>throw new InvalidOperationException());f.M.Register(()=>calls++);Throws<InvalidOperationException>(f.M.Update);Require(calls==0&&f.M.IndexDict.ContainsKey(id),"force failure prevents normal and retains callback");f.M.QueueRemove(id);f.M.Update();Require(calls==1,"next successful drain permits normal pass");}});
            check("source-update-live-list-replacement-is-observed-with-captured-count",()=>{using(var f=new Fixture()){var e=new List<string>();f.M.Register(()=>{e.Add("first");f.M.HandleList=new List<Action>{()=>e.Add("unused"),()=>e.Add("replacement")};});f.M.Register(()=>e.Add("old-second"));f.M.Update();Require(string.Join(",",e)=="first,replacement","getter read on each iteration with count from original list");}});
            check("source-update-immediate-list-shrink-retains-source-index-failure",()=>{using(var f=new Fixture()){Action first=null;first=()=>f.M.RemoveNow(first);f.M.Register(first);f.M.Register(()=>{});Throws<ArgumentOutOfRangeException>(f.M.Update);Require(f.M.HandleList.Count==1&&f.M.IndexDict.Count==1,"immediate shrink during captured-count loop skips shifted entry then fails");}});
            check("source-update-data-duplicate-logs-and-preserves-record",()=>{using(var f=new Fixture()){var errors=new List<string>();f.M.RegisterData(7,"first","one",a=>errors.Add((string)a[0]));f.M.RegisterData(7,"second","two",a=>errors.Add((string)a[0]));Require(errors.Count==1&&errors[0]=="重复添加：7"&&f.M.UpdateData[7].ActionName=="first"&&f.M.UpdateData[7].Handle=="one","duplicate logs and retains original data even without registered handle");}});
            check("source-update-fixed-captured-count-defers-new-callback",()=>{using(var f=new Fixture()){int calls=0;f.M.RegisterFixed(()=>f.M.RegisterFixed(()=>calls++));f.M.FixedUpdate();Require(calls==0,"fixed captured count");f.M.FixedUpdate();Require(calls==1,"new fixed callback next pass");}});
            check("source-update-pause-set-during-force-does-not-stop-current-pass",()=>{using(var f=new Fixture()){int calls=0;f.M.RegisterForce(()=>f.M.IsPause=true);f.M.Register(()=>calls++);f.M.Update();Require(calls==1&&f.M.IsPause,"pause read only at Update entry");f.M.Update();Require(calls==1,"later Update observes pause");}});
            check("source-update-real-audio-action-register-dispose-deferred",()=>{using(var f=new Fixture())using(var audio=new OutgameAudioPlaybackValidation.Fixture()){audio.Services.AddUpdate=f.M.Register;audio.Services.RemoveUpdate=f.M.QueueRemove;var action=new OutgameAudioLoopAction(audio.Root,1002,null,null,audio.Services);action.Play();int id=action.UpdateId;Require(f.M.IndexDict.ContainsKey(id)&&f.M.HandleList.Count==1,"production audio constructor registers actual source update handle");action.Stop();Require(action.UpdateId==0&&f.M.IndexDict.ContainsKey(id)&&f.M.RemoveIds.Count==1,"audio Dispose queues removal before resetting its id");f.M.Update();Require(f.M.IndexDict.Count==0&&f.M.HandleList.Count==0,"actual Update drains disposed action callback");}});
            return r;
        }
    }
}
