using System;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameInputManagerValidation
    {
        internal sealed class Source:IOutgameInputSource
        {
            public RuntimePlatform platform=RuntimePlatform.WindowsPlayer;public bool down,up,held;public Vector3 position;public float scroll;
            public OutgameTouch[] touches=Array.Empty<OutgameTouch>();public Event current;public int scrollReads,platformReads,mouseReads,touchReads;
            public Func<Vector3> ReadPosition;public Action ReadTouches;
            public RuntimePlatform Platform{get{platformReads++;return platform;}}public bool MouseDown=>down;public bool MouseUp=>up;public bool MouseHeld=>held;
            public Vector3 MousePosition{get{mouseReads++;return ReadPosition!=null?ReadPosition():position;}}public float Scroll{get{scrollReads++;return scroll;}}
            public int TouchCount{get{touchReads++;ReadTouches?.Invoke();return touches.Length;}}public OutgameTouch FirstTouch=>touches[0];public OutgameTouch GetTouch(int i)=>touches[i];public Event CurrentEvent=>current;
            public void Touch(TouchPhase phase,float x=0,float y=0){touches=new[]{new OutgameTouch(new Vector2(x,y),phase)};}
            public void Key(EventType type,KeyCode key){current=new Event{type=type,keyCode=key};}
        }
        sealed class Fixture:IDisposable
        {
            public readonly GameObject go=new GameObject("input-golden");public readonly OutgameInputManager manager;public readonly Source source=new Source();public readonly List<string> events=new List<string>();
            public Fixture(){manager=go.AddComponent<OutgameInputManager>();manager.Source=source;manager.TouchBegin+=(x,y)=>events.Add("begin");manager.TouchHold+=(x,y)=>events.Add("hold");manager.TouchMove+=(x,y)=>events.Add("move");manager.TouchEnd+=(x,y)=>events.Add("end");manager.Click+=(x,y)=>events.Add("click");manager.Scale+=s=>events.Add("scale");manager.MulTouchBegin+=(n,l)=>events.Add("multi-begin");manager.MulTouchHold+=(n,l)=>events.Add("multi-hold");manager.MulTouchMove+=(n,l)=>events.Add("multi-move");manager.MulTouchEnd+=()=>events.Add("multi-end");}
            public void Dispose(){UnityEngine.Object.DestroyImmediate(go);OutgameInputManager.MoveStep=50;}
        }
        static OutgameTouch T(float x,TouchPhase phase)=>new OutgameTouch(new Vector2(x,0),phase);
        static void Require(bool b,string text){if(!b)throw new Exception(text);}static void Throws(Action a){try{a();}catch(InvalidOperationException){return;}throw new Exception("Missing callback exception");}
        static void Sequence(List<string> actual,string expected)=>Require(string.Join(",",actual)==expected,"Expected "+expected+", got "+string.Join(",",actual));
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-input-platform-short-circuit-and-webgl-touch-only",()=>{foreach(var entry in new[]{(RuntimePlatform.Android,1),(RuntimePlatform.IPhonePlayer,2),(RuntimePlatform.WebGLPlayer,3),(RuntimePlatform.WindowsPlayer,3)})using(var f=new Fixture()){f.source.platform=entry.Item1;f.source.down=true;f.source.Touch(TouchPhase.Began);f.manager.CheckTouch();Require(f.source.platformReads==entry.Item2&&f.source.touchReads==(entry.Item1==RuntimePlatform.WindowsPlayer?0:1)&&f.source.mouseReads==(entry.Item1==RuntimePlatform.WindowsPlayer?3:0),"platform reads and exclusive source branch");Sequence(f.events,"begin");}});
            check("source-input-mouse-priority-independent-position-reads",()=>{using(var f=new Fixture()){f.source.down=f.source.up=f.source.held=true;int read=0;f.source.ReadPosition=()=>new Vector3(++read,10*read,100);f.source.scroll=.5f;f.manager.GetMouseInput();Require(f.manager.MouseX==1&&f.manager.MouseY==20&&f.manager.PressPoint==new Vector3(3,30,100)&&f.manager.PreviousX==1&&f.manager.PreviousY==20,"independent XY/press reads");Sequence(f.events,"begin,scale");}});
            check("source-input-mouse-move-exact-float-and-hold",()=>{using(var f=new Fixture()){f.source.held=true;f.manager.GetMouseInput();f.source.position.x=.001f;f.manager.GetMouseInput();Sequence(f.events,"hold,move");Require(f.manager.PreviousX==0,"no MoveStep movement debounce");}});
            check("source-input-mouse-click-before-end-and-strict-distance",()=>{using(var f=new Fixture()){f.source.up=true;f.source.position.x=50;f.manager.GetMouseInput();f.source.position.x=49.99f;f.manager.GetMouseInput();Sequence(f.events,"end,click,end");}});
            check("source-input-mouse-click-failure-prevents-end-and-scroll",()=>{using(var f=new Fixture()){f.source.up=true;f.manager.PreviousX=91;f.manager.Click+=(x,y)=>throw new InvalidOperationException();Throws(f.manager.GetMouseInput);Sequence(f.events,"click");Require(f.manager.PreviousX==91&&f.source.scrollReads==0,"failure retains old previous position and skips later input reads");}});
            check("source-input-scroll-retains-last-nonzero-and-accepts-nan",()=>{using(var f=new Fixture()){f.source.scroll=-2;f.manager.GetMouseInput();f.source.scroll=0;f.manager.GetMouseInput();Require(f.manager.LastScroll==-2,"zero does not clear history");f.source.scroll=float.NaN;f.manager.GetMouseInput();Require(float.IsNaN(f.manager.LastScroll),"source IEEE comparison");Sequence(f.events,"scale,scale");}});
            check("source-input-touch-end-before-click-including-cancel",()=>{using(var f=new Fixture()){f.source.Touch(TouchPhase.Began,10,20);f.manager.GetTouchInput();f.source.Touch(TouchPhase.Canceled,10,20);f.manager.GetTouchInput();Require(f.manager.MulTouchLen==1,"ended single remains1");f.source.touches=Array.Empty<OutgameTouch>();f.manager.GetTouchInput();f.manager.GetTouchInput();Sequence(f.events,"begin,end,click,multi-end");}});
            check("source-input-touch-end-reentrancy-live-press-and-coordinates",()=>{using(var f=new Fixture()){bool entered=false;f.manager.TouchEnd+=(x,y)=>{if(entered)return;entered=true;f.source.Touch(TouchPhase.Began,200,300);f.manager.GetTouchInput();};f.source.Touch(TouchPhase.Ended,0,0);f.manager.GetTouchInput();Sequence(f.events,"end,begin");Require(f.manager.MouseX==200&&f.manager.PressPoint.x==200,"End callback modifies click gate with live press point");}});
            check("source-input-touch-end-failure-stops-click",()=>{using(var f=new Fixture()){f.source.Touch(TouchPhase.Ended);f.manager.TouchEnd+=(x,y)=>throw new InvalidOperationException();Throws(f.manager.GetTouchInput);Sequence(f.events,"end");Require(f.manager.MulTouchLen==1,"touch state committed first");}});
            check("source-input-touch-phase-dispatch-no-position-debounce",()=>{using(var f=new Fixture()){f.source.Touch(TouchPhase.Moved);f.manager.GetTouchInput();f.source.Touch(TouchPhase.Stationary,99);f.manager.GetTouchInput();Sequence(f.events,"move,hold");}});
            check("source-input-multi-began-is-hold-and-scale-uses-previous-list",()=>{using(var f=new Fixture()){f.source.touches=new[]{T(0,TouchPhase.Began),T(100,TouchPhase.Began)};f.manager.GetTouchInput();var previous=f.manager.MultiTouches;f.source.touches=new[]{T(0,TouchPhase.Stationary),T(150,TouchPhase.Moved)};f.manager.GetTouchInput();Sequence(f.events,"multi-hold,multi-move,scale");Require(f.manager.LastScroll==1&&!ReferenceEquals(previous,f.manager.MultiTouches)&&previous[1].x==100,"distance delta divided by fixed50");}});
            check("source-input-multi-filters-ended-retains-array-index-and-no-early-end",()=>{using(var f=new Fixture()){f.source.touches=new[]{T(0,TouchPhase.Ended),T(20,TouchPhase.Began),T(60,TouchPhase.Moved)};f.manager.GetTouchInput();Require(f.manager.MulTouchLen==2&&f.manager.MultiTouches[0].id==1&&f.manager.MultiTouches[1].id==2,"source ids are input-array indices");f.source.touches=new[]{T(0,TouchPhase.Canceled),T(20,TouchPhase.Stationary)};f.manager.GetTouchInput();Require(f.manager.MulTouchLen==1,"active count retained");Sequence(f.events,"multi-move");f.source.touches=Array.Empty<OutgameTouch>();f.manager.GetTouchInput();Sequence(f.events,"multi-move,multi-end");}});
            check("source-input-multi-move-callback-live-list-controls-scale",()=>{using(var f=new Fixture()){f.source.touches=new[]{T(0,TouchPhase.Began),T(100,TouchPhase.Began)};f.manager.GetTouchInput();f.manager.MulTouchMove+=(n,l)=>l[1].x=200;f.source.touches=new[]{T(0,TouchPhase.Moved),T(150,TouchPhase.Moved)};f.manager.GetTouchInput();Require(f.manager.LastScroll==2,"scale reads current mutable list after move callback");}});
            check("source-input-key-repeat-hold-live-list-and-keyup-order",()=>{using(var f=new Fixture()){f.manager.KeyDown+=k=>f.events.Add("down");f.manager.KeyHold+=l=>{Require(ReferenceEquals(l,f.manager.HeldKeys),"no held-key copy");f.events.Add("key-hold");};f.manager.KeyUp+=k=>{Require(f.manager.HeldKeys.Contains(k),"KeyUp before removal");f.events.Add("up");};f.source.Key(EventType.KeyDown,KeyCode.A);f.manager.CheckKeys();f.manager.CheckKeys();f.source.Key(EventType.KeyUp,KeyCode.A);f.manager.CheckKeys();Sequence(f.events,"down,key-hold,key-hold,up");Require(f.manager.HeldKeys.Count==0,"removed after callback");}});
            check("source-input-key-gui-gates-and-zero-key-hold",()=>{using(var f=new Fixture()){f.manager.CheckKeys();Require(f.manager.HeldKeys!=null,"list initializes even without Event.current");f.manager.HeldKeys.Add(KeyCode.B);f.manager.HeldKey=KeyCode.B;f.manager.KeyHold+=l=>f.events.Add("key-hold");f.source.current=new Event{type=EventType.Repaint};f.manager.CheckKeys();f.source.Key(EventType.KeyDown,KeyCode.None);f.manager.CheckKeys();Sequence(f.events,"key-hold");Require(f.manager.HeldKey==KeyCode.B,"zero code preserves held key");}});
            check("source-input-keyup-failure-preserves-key-and-stops-hold",()=>{using(var f=new Fixture()){f.manager.HeldKeys=new List<KeyCode>{KeyCode.A};f.source.Key(EventType.KeyUp,KeyCode.A);f.manager.KeyUp+=k=>throw new InvalidOperationException();f.manager.KeyHold+=l=>f.events.Add("key-hold");Throws(f.manager.CheckKeys);Require(f.manager.HeldKeys.Count==1&&f.events.Count==0,"callback failure stops removal and hold");}});
            check("source-input-keyup-live-held-key-mutation",()=>{using(var f=new Fixture()){f.manager.HeldKeys=new List<KeyCode>{KeyCode.A,KeyCode.B};f.source.Key(EventType.KeyUp,KeyCode.A);f.manager.KeyUp+=k=>f.manager.HeldKey=KeyCode.B;f.manager.CheckKeys();Require(f.manager.HeldKeys.Count==1&&f.manager.HeldKeys[0]==KeyCode.A,"removal reads HeldKey after callback");}});
            check("source-input-shutdown-clears-listeners-retains-input-history",()=>{using(var f=new Fixture()){f.source.Touch(TouchPhase.Began,5,8);f.manager.GetTouchInput();f.manager.HeldKeys=new List<KeyCode>{KeyCode.C};f.manager.LastScroll=4;f.manager.Shutdown();f.source.Touch(TouchPhase.Ended,5,8);f.manager.GetTouchInput();Sequence(f.events,"begin");Require(f.manager.HeldKeys.Count==1&&f.manager.PressPoint.x==5&&f.manager.MulTouchLen==1&&f.manager.LastScroll==4,"shutdown clears delegates only");}});
            check("source-input-begin-registration-log-failure-precedes-subscription",()=>{using(var f=new Fixture()){int called=0;Action<float,float> listener=(x,y)=>called++;f.manager.RegistrationLog=a=>{Require(a.Length==1&&(string)a[0]=="add touch begin handle:","source diagnostic payload");throw new InvalidOperationException();};Throws(()=>f.manager.TouchBegin+=listener);f.source.down=true;f.manager.GetMouseInput();Require(called==0,"log failure leaves delegate unchanged");f.manager.RegistrationLog=a=>{};f.manager.TouchBegin+=listener;f.manager.GetMouseInput();Require(called==1,"subsequent successful registration works");}});
            return r;
        }
    }
}
