using System;
using System.Collections.Generic;
using UnityEngine;
using AreaBattle.SharedItemConfig;
namespace AreaBattle.EditorTools
{
    public static class OutgameItemConfigValidation
    {
        static void Require(bool b,string s){if(!b)throw new Exception(s);}
        static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        static OutgameItemConfigSlot Slot()=>new OutgameItemConfigSlot(a=>{});
        static OutgameLegacyConfigRead Reader(List<string> trace,List<string> errors)=>new OutgameLegacyConfigRead(name=>{trace.Add(name);return Resources.Load<TextAsset>("Recovered/FirstPack/Config/"+name);},errors.Add);
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-shared-item-slot-does-not-initialize-tables",()=>{var s=Slot();Require(!s.HasInstance,"lazy");var m=s.Instance;Require(s.HasInstance&&ReferenceEquals(m,s.Instance)&&m.Items.Count==0&&m.PackageRewards==null&&m.RewardItems==null,"constructor initializes six dictionaries only");Throws<NullReferenceException>(()=>m.GetPackageRewards(1));});
            check("source-shared-item-original-four-tables-and-distinct-schema",()=>{var m=Slot().Instance;var trace=new List<string>();var errors=new List<string>();var reader=Reader(trace,errors);m.InitLegacyUnityJson(reader);Require(string.Join(",",trace)=="GameItemConfig,GamePackageConfig,GameRewardConfig,GameProductConfig"&&reader.ReadCount==4&&errors.Count==0,"source read order");Require(m.Items.Count==79&&m.Packages.Count==4&&m.Products.Count==16&&m.Rewards.Count==10,"original row counts");Require(m.Items[1001].name.key=="item_name_1001"&&m.Items[1001].quality==1,"shared metadata fields read");Require(m.Products[100101].itemId==0&&m.Products[100101].groupID==0&&m.GroupProducts[0].Count==16,"project-only JSON fields do not invent shared fields");Require(m.PackageRewards[20001].Count==2&&m.RewardItems[101].Count==4,"source groups");});
            check("source-shared-item-reinit-preserves-rows-and-appends-products",()=>{var m=Slot().Instance;var errors=new List<string>();var reader=Reader(new List<string>(),errors);m.InitLegacyUnityJson(reader);var old=m.PackageRewards;var item=m.Items[1001];var products=m.GroupProducts[0];m.InitLegacyUnityJson(reader);Require(errors.Count==109&&reader.ReadCount==8&&ReferenceEquals(item,m.Items[1001]),"duplicates retained by ConfigRead");Require(!ReferenceEquals(old,m.PackageRewards)&&ReferenceEquals(products,m.GroupProducts[0])&&products.Count==32,"groups replaced except products appended");});
            check("source-shared-item-group-values-overwrite-same-row-id",()=>{var m=Slot().Instance;var first=new GamePackageConfig{packageRewardId=3,packageId=2};var last=new GamePackageConfig{packageRewardId=3,packageId=2};m.Packages[10]=first;m.Packages[11]=last;m.Rewards[10]=new GameRewardConfig{rewardItemId=8,rewardId=7};var reward=new GameRewardConfig{rewardItemId=8,rewardId=7};m.Rewards[11]=reward;m.BuildGroups();Require(ReferenceEquals(m.PackageRewards[2][3],last)&&ReferenceEquals(m.RewardItems[7][8],reward),"group by row fields and indexer overwrite, not Add");});
            check("source-shared-item-missing-groups-fresh-and-existing-groups-live",()=>{var m=Slot().Instance;m.Packages[1]=new GamePackageConfig{packageRewardId=1,packageId=2};m.BuildGroups();Require(!ReferenceEquals(m.GetPackageRewards(99),m.GetPackageRewards(99))&&!ReferenceEquals(m.GetRewardItems(99),m.GetRewardItems(99)),"miss returns fresh dictionaries");m.GetPackageRewards(2).Clear();Require(m.PackageRewards[2].Count==0&&!m.PackageRewards.ContainsKey(99),"hit returns live group; miss not cached");});
            check("source-shared-item-range-copies-list-shares-elements-snapshots-weight",()=>{var m=Slot().Instance;var reward=new GameRewardConfig{rewardItemId=1,rewardId=2,weight=-3};m.Rewards[1]=reward;m.BuildGroups();var a=m.GetRewardItemRanges(2);var b=m.GetRewardItemRanges(2);Require(!ReferenceEquals(a,b)&&ReferenceEquals(a[0],b[0])&&ReferenceEquals(a[0].Config,reward)&&a[0].Weight==-3,"shallow copy and signed weight");a.Clear();reward.weight=9;Require(m.GetRewardItemRanges(2)[0].Weight==-3,"weight captured only cache creation");b[0].Weight=7;Require(m.GetRewardItemRanges(2)[0].Weight==7,"element modifications shared");});
            check("source-shared-item-range-cache-survives-group-rebuild",()=>{var m=Slot().Instance;m.BuildGroups();Require(m.GetRewardItemRanges(5).Count==0,"cache missing group");m.Rewards[1]=new GameRewardConfig{rewardItemId=1,rewardId=5,weight=2};m.BuildGroups();Require(m.GetRewardItems(5).Count==1&&m.GetRewardItemRanges(5).Count==0,"group rebuild does not invalidate range cache");m.RewardRanges.Clear();Require(m.GetRewardItemRanges(5).Count==1,"explicit cache clear allows refill");});
            check("source-shared-item-package-failure-keeps-later-groups",()=>{var m=Slot().Instance;m.BuildGroups();var old=m.RewardItems;m.Packages[1]=new GamePackageConfig{packageRewardId=1,packageId=2};m.Packages[2]=null;m.Products[1]=new GameProductConfig{groupID=1};Throws<NullReferenceException>(m.BuildGroups);Require(m.PackageRewards[2].Count==1&&ReferenceEquals(old,m.RewardItems)&&m.GroupProducts.Count==0,"package prefix retained; later stages untouched");});
            check("source-shared-item-reward-failure-does-not-publish-range-cache",()=>{var m=Slot().Instance;m.BuildGroups();m.RewardItems[1]=new Dictionary<int,GameRewardConfig>{{1,new GameRewardConfig{weight=3}},{2,null}};Throws<NullReferenceException>(()=>m.GetRewardItemRanges(1));Require(!m.RewardRanges.ContainsKey(1),"list cached only after successful enumeration");});
            check("source-shared-item-getters-current-product-and-original-item",()=>{var errors=new List<object[]>();var s=new OutgameItemConfigSlot(errors.Add);var old=s.Instance;old.Items[1]=new GameItemConfig{id=1};old.Products[1]=new GameProductConfig{id=1};old.Dispose();var fresh=s.Instance;var p=new GameProductConfig{id=1};fresh.Products[1]=p;Require(ReferenceEquals(old.GetGameProductConfig(1),p)&&old.GetGameItemConfig(1).id==1,"product uses current slot; item uses receiver");old.Items[2]=null;Require(old.GetGameItemConfig(2)==null&&errors.Count==0,"existing null does not log");Require(old.GetGameItemConfig(3)==null&&old.GetGameProductConfig(3)==null&&errors.Count==2&&Equals(errors[0][0],"道具表配置中不包含id")&&Equals(errors[1][0],"商品表配置中不包含id")&&Equals(errors[1][1],3),"source diagnostic args");});
            check("source-shared-item-dispose-retains-tables-and-clears-current-slot",()=>{var s=Slot();var old=s.Instance;old.Packages[1]=new GamePackageConfig{packageRewardId=1,packageId=2};old.Products[1]=new GameProductConfig();old.BuildGroups();old.GetRewardItemRanges(2);var groups=old.PackageRewards;old.Dispose();Require(!s.HasInstance&&old.Packages.Count==1&&old.Products.Count==1&&ReferenceEquals(groups,old.PackageRewards)&&old.RewardRanges.Count==0&&old.GroupProducts.Count==0,"clear only caches and singleton");var fresh=s.Instance;old.Dispose();Require(!s.HasInstance&&!ReferenceEquals(fresh,s.Instance),"stale receiver clears replacement slot");});
            check("source-shared-item-dispose-and-read-failure-prefix",()=>{var s=Slot();var m=s.Instance;m.RewardRanges[1]=new List<OutgameRewardRangeData>();m.GroupProducts=null;Throws<NullReferenceException>(m.Dispose);Require(m.RewardRanges.Count==0&&s.HasInstance,"second clear failure prevents singleton reset");int reads=0;var reader=new OutgameLegacyConfigRead(name=>{reads++;if(reads==2)throw new InvalidOperationException();return Resources.Load<TextAsset>("Recovered/FirstPack/Config/"+name);},a=>{});Throws<InvalidOperationException>(()=>m.InitLegacyUnityJson(reader));Require(m.Items.Count==79&&m.Packages.Count==0&&reader.ReadCount==1&&m.PackageRewards==null,"read failure keeps first table and skips indexes");});
            return r;
        }
    }
}
