using System;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameAudioNodeValidation
    {
        internal sealed class ActionProbe:IOutgameAudioAction
        {
            public int Id,Type,Handle;public OutgameVoiceType Voice=OutgameVoiceType.Sound;public AudioSource Source;public Action<int> Begin,End;public Action OnPlay,OnStop,OnPause;public int Plays,Stops,Pauses;
            public int Guid=>Handle;public OutgameVoiceType VoiceType=>Voice;public AudioSource AudioSource=>Source;
            public void Play(){Plays++;OnPlay?.Invoke();}public void Stop(){Stops++;OnStop?.Invoke();}public void Pause(bool paused){Pauses++;OnPause?.Invoke();}
            public void Started()=>Begin(Handle);public void Ended()=>End(Handle);
        }
        sealed class Fixture:IDisposable
        {
            public readonly GameObject Parent=new GameObject("audio-node-parent");public readonly OutgameMessageDispatcher Messages=new OutgameMessageDispatcher();public readonly List<string> Events=new List<string>();public readonly List<ActionProbe> Actions=new List<ActionProbe>();public readonly List<OutgameAudioNode> Nodes=new List<OutgameAudioNode>();public readonly List<int> RequestedIds=new List<int>();
            public Func<int,int> GetType=id=>1;public Action<ActionProbe> Configure;public bool NullAction;
            public Fixture(){Parent.layer=8;Parent.transform.position=new Vector3(1,2,3);Parent.transform.localScale=Vector3.one*2;Messages.AddListener("AudioPlayStart",a=>Events.Add("start:"+a[0]));Messages.AddListener("AudioPlayEnd",a=>Events.Add("end:"+a[0]));}
            IOutgameAudioAction Create(GameObject root,int type,int id,Action<int> begin,Action<int> end){RequestedIds.Add(id);if(NullAction)return null;var a=new ActionProbe{Id=id,Type=type,Handle=100+Actions.Count,Begin=begin,End=end};Actions.Add(a);Configure?.Invoke(a);return a;}
            public AudioSource NativeSource(){var go=new GameObject("source-probe",typeof(AudioSource));go.transform.SetParent(Parent.transform,false);return go.GetComponent<AudioSource>();}
            public OutgameAudioParallel Parallel(){var n=new OutgameAudioParallel(Parent,1,"parallel_1",id=>GetType(id),Create,()=>Messages,UnityEngine.Object.DestroyImmediate);Nodes.Add(n);return n;}
            public OutgameAudioSequence Sequence(){var n=new OutgameAudioSequence(Parent,2,"sequence_2",id=>GetType(id),Create,()=>Messages,UnityEngine.Object.DestroyImmediate);Nodes.Add(n);return n;}
            public OutgameAudioSingle Single(){var n=new OutgameAudioSingle(Parent,3,"single_3",id=>GetType(id),Create,()=>Messages,UnityEngine.Object.DestroyImmediate);Nodes.Add(n);return n;}
            public void Dispose(){UnityEngine.Object.DestroyImmediate(Parent);}
        }
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        static void Events(Fixture f,string value)=>Require(string.Join(",",f.Events)==value,"Expected "+value+", got "+string.Join(",",f.Events));
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-audio-node-native-root-parent-reset-and-layer",()=>{using(var f=new Fixture()){var n=f.Parallel();Require(n.Root.name=="parallel_1"&&n.NodeId==1&&n.Root.layer==8&&n.Root.transform.parent==f.Parent.transform&&n.Root.transform.localPosition==Vector3.zero&&n.Root.transform.localRotation==Quaternion.identity&&n.Root.transform.localScale==Vector3.one,"source native node root helper");}});
            check("source-audio-parallel-pending-load-not-registered-before-start",()=>{using(var f=new Fixture()){var n=f.Parallel();var handles=n.Play(new[]{11,12});Require(handles[0]==100&&handles[1]==101&&n.Actions.Count==0&&f.Actions[0].Plays==1,"parallel returns GUIDs immediately but tracks only started actions");n.Stop(0);n.StopByGuid(100);Require(f.Actions[0].Stops==0,"stop cannot reach source unstarted load");f.Actions[0].Started();Require(ReferenceEquals(n.Actions[100],f.Actions[0]),"start callback stores captured action");Events(f,"start:100");}});
            check("source-audio-parallel-start-end-event-mutation-order",()=>{using(var f=new Fixture()){var n=f.Parallel();n.Play(new[]{11});f.Messages.AddListener("AudioPlayStart",a=>{Require(n.Actions.ContainsKey(100),"insert before start event");throw new InvalidOperationException();});Throws<InvalidOperationException>(f.Actions[0].Started);Require(n.Actions.ContainsKey(100),"entry retained after start event failure");f.Messages.AddListener("AudioPlayEnd",a=>{Require(!n.Actions.ContainsKey(100),"remove before end event");throw new InvalidOperationException();});Throws<InvalidOperationException>(f.Actions[0].Ended);}});
            check("source-audio-parallel-factory-callback-before-captured-assignment",()=>{using(var f=new Fixture()){f.Configure=a=>a.Started();var n=f.Parallel();n.Play(new[]{11});Require(n.Actions.Count==0&&f.Actions[0].Plays==1,"creation-time start has null captured action but still publishes");Events(f,"start:100");}});
            check("source-audio-parallel-stop-source-loop-index-removal",()=>{using(var f=new Fixture()){var n=f.Parallel();n.Play(new[]{11,12});f.Actions[0].Handle=42;f.Actions[1].Handle=0;f.Actions[0].Started();f.Actions[1].Started();n.Stop(0);Require(f.Actions[0].Stops==1&&f.Actions[1].Stops==0&&n.Actions.ContainsKey(42)&&!n.Actions.ContainsKey(0),"source Remove(i) removes key0 after stopping GUID42; next captured key0 is absent");}});
            check("source-audio-parallel-stop-voice-filter-snapshot-and-end-removal",()=>{using(var f=new Fixture()){var n=f.Parallel();n.Play(new[]{11,12});f.Actions[0].Voice=OutgameVoiceType.Music;f.Actions[0].OnStop=()=>{f.Actions[0].Ended();n.Actions[300]=new ActionProbe{Handle=300,Voice=OutgameVoiceType.Music};};foreach(var a in f.Actions)a.Started();n.Stop(OutgameVoiceType.Music);Require(f.Actions[0].Stops==1&&f.Actions[1].Stops==0&&n.Actions[300].Guid==300&&n.Actions.Count==2,"filter source voice, snapshot keys excludes callback-added action");}});
            check("source-audio-parallel-guid-stop-retains-entry-until-completion",()=>{using(var f=new Fixture()){var n=f.Parallel();n.Play(new[]{11});f.Actions[0].Started();n.StopByGuid(999);n.StopByGuid(100);Require(f.Actions[0].Stops==1&&n.Actions.ContainsKey(100),"GUID stop delegates action callback cleanup");}});
            check("source-audio-parallel-pause-native-null-and-live-enumerator",()=>{using(var f=new Fixture()){var n=f.Parallel();n.Play(new[]{11,12});foreach(var a in f.Actions)a.Started();f.Actions[0].Source=f.NativeSource();n.Pause(true);Require(f.Actions[0].Pauses==1&&f.Actions[1].Pauses==0,"skip unloaded source");f.Actions[0].OnPause=()=>n.Actions.Add(999,new ActionProbe());Throws<InvalidOperationException>(()=>n.Pause(true));}});
            check("source-audio-parallel-destroy-retains-late-callback-events",()=>{using(var f=new Fixture()){var n=f.Parallel();n.Play(new[]{11});n.Destroy();Require(n.Actions==null&&!n.Root&&f.Actions[0].Stops==0,"destroy root/collection without stopping untracked action");f.Actions[0].Started();f.Actions[0].Ended();Events(f,"start:100,end:100");}});
            check("source-audio-sequence-type2-coercion-and-queued-start",()=>{using(var f=new Fixture()){f.GetType=id=>id==1?2:4;var n=f.Sequence();Require(n.Play(new[]{1,2})==null&&n.Actions.Count==2&&f.Actions[0].Type==1&&f.Actions[1].Type==4&&f.Actions[0].Plays==1&&f.Actions[1].Plays==0,"only loop2 coerced to once1; sequence returns null");f.Actions[0].Ended();Require(n.Actions.Count==1&&f.Actions[1].Plays==1,"end dequeues then starts next");Events(f,"end:100");}});
            check("source-audio-sequence-sync-completion-precedes-first-enqueue",()=>{using(var f=new Fixture()){f.Configure=a=>a.OnPlay=a.Ended;var n=f.Sequence();n.Play(new[]{1,2});Require(n.Actions.Count==2&&ReferenceEquals(n.Actions.Peek(),f.Actions[0])&&f.Actions[1].Plays==0,"source synchronous first completion leaves ended first action queued");Events(f,"end:100");}});
            check("source-audio-sequence-end-event-failure-leaves-next-unstarted",()=>{using(var f=new Fixture()){var n=f.Sequence();n.Play(new[]{1,2});f.Messages.AddListener("AudioPlayEnd",a=>throw new InvalidOperationException());Throws<InvalidOperationException>(f.Actions[0].Ended);Require(n.Actions.Count==1&&f.Actions[1].Plays==0,"dequeue commits before event failure prevents next Play");}});
            check("source-audio-sequence-stop-skips-unloaded-and-ignores-voice",()=>{using(var f=new Fixture()){var n=f.Sequence();n.Play(new[]{1,2});f.Actions[0].Source=f.NativeSource();f.Actions[0].OnStop=f.Actions[0].Ended;n.Stop(OutgameVoiceType.Music);Require(f.Actions[0].Stops==1&&f.Actions[1].Stops==0&&f.Actions[1].Plays==0&&n.Actions==null&&!n.Stopping&&!n.Root,"Stopping suppresses completion dequeue/advance; unloaded dequeued without Stop; Destroy resets flag");}});
            check("source-audio-sequence-stop-failure-retains-partial-dequeue",()=>{using(var f=new Fixture()){var n=f.Sequence();n.Play(new[]{1,2});f.Actions[0].Source=f.NativeSource();f.Actions[0].OnStop=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>n.Stop(0));Require(n.Actions.Count==1&&n.Stopping&&n.Root,"failed first Stop leaves second queued and flag set, root retained");}});
            check("source-audio-sequence-pause-every-loaded-queued-action",()=>{using(var f=new Fixture()){var n=f.Sequence();n.Play(new[]{1,2});foreach(var a in f.Actions)a.Source=f.NativeSource();n.Pause(true);Require(f.Actions[0].Pauses==1&&f.Actions[1].Pauses==1&&f.Actions[1].Plays==0,"source pauses all loaded queue entries, not just head");}});
            check("source-audio-single-first-id-only-and-empty-requests-id0",()=>{using(var f=new Fixture()){var n=f.Single();Require(n.Play(new[]{11,12})==null&&f.RequestedIds.Count==1&&f.RequestedIds[0]==11,"single takes first only and returns null");n.Play(null);Require(f.RequestedIds[1]==0&&n.Pending==f.Actions[1]&&f.Actions[0].Stops==1,"null list creates audio0 pending then stops current");}});
            check("source-audio-single-replacement-completion-order",()=>{using(var f=new Fixture()){var n=f.Single();n.Play(new[]{11});f.Actions[0].OnStop=f.Actions[0].Ended;f.Messages.AddListener("AudioPlayEnd",a=>Require(n.Current==null&&ReferenceEquals(n.Pending,f.Actions[1]),"clear current before event with pending retained"));n.Play(new[]{12});Require(n.Current==f.Actions[1]&&n.Pending==null&&f.Actions[1].Plays==1,"pending promoted/play before pending clear");}});
            check("source-audio-single-end-event-failure-retains-pending",()=>{using(var f=new Fixture()){var n=f.Single();n.Play(new[]{11});n.Play(new[]{12});f.Messages.AddListener("AudioPlayEnd",a=>throw new InvalidOperationException());Throws<InvalidOperationException>(f.Actions[0].Ended);Require(n.Current==null&&n.Pending==f.Actions[1]&&f.Actions[1].Plays==0,"no catch/finally pending cleanup");}});
            check("source-audio-single-stop-starts-pending-before-root-destroy",()=>{using(var f=new Fixture()){var n=f.Single();n.Play(new[]{11});n.Play(new[]{12});f.Actions[0].OnStop=f.Actions[0].Ended;n.Stop(OutgameVoiceType.Music);Require(f.Actions[1].Plays==1&&n.Current==null&&n.Pending==null&&!n.Root,"source stop callback can start pending before Destroy clears current/root, ignores voice");}});
            check("source-audio-single-destroy-retains-pending-and-late-end",()=>{using(var f=new Fixture()){var n=f.Single();n.Play(new[]{11});n.Play(new[]{12});n.Destroy();Require(n.Pending==f.Actions[1]&&!n.Root,"Pending not cleared");f.Actions[0].Ended();Require(n.Current==f.Actions[1]&&f.Actions[1].Plays==1&&n.Pending==null,"late end promotes pending even after native root destruction");}});
            return r;
        }
    }
}
