using System;
using System.Collections.Generic;
using UnityEngine;
using AreaBattle.SharedItemConfig;
namespace AreaBattle.EditorTools
{
    public static class OutgameGlobalItemRewardsValidation
    {
        public sealed class Reports:IOutgameItemReports
        {public readonly List<OutgameItemChangeReport> Changes=new List<OutgameItemChangeReport>();public readonly List<bool> Gains=new List<bool>();public readonly List<OutgameItemUseReport> Uses=new List<OutgameItemUseReport>();public Action Creating,Sending;public OutgameItemChangeReport CreateChange(bool gain){Creating?.Invoke();return new OutgameItemChangeReport();}public void SendChange(bool gain,OutgameItemChangeReport r){Sending?.Invoke();Changes.Add(r);Gains.Add(gain);}public OutgameItemUseReport CreateUse(){Creating?.Invoke();return new OutgameItemUseReport();}public void SendUse(OutgameItemUseReport r){Sending?.Invoke();Uses.Add(r);}}
        sealed class LifecycleHost:IOutgameGlobalItemLifecycleHost {public int AddUpdate(Action a)=>1;public void RemoveUpdate(int i){}public void DisposeItemConfiguration(){}public void ClearGlobalInstance(){}public void SendStatisticsRegistration(string s,int i,Func<object[],long> f){}}
        internal sealed class RewardHost:IOutgameGlobalItemRewardHost
        {public int Adds,Costs;public List<OutgameItemReward> Last;public Action<List<OutgameItemReward>> Added;public Func<GameItemConfig,IOutgameItemEntity> Factory;public IOutgameItemEntity GetItem(GameItemConfig c)=>Factory(c);public void AddRewards(List<OutgameItemReward> r){Adds++;Last=r;Added?.Invoke(r);}public void ExpendReward(List<OutgameItemReward> r){Costs++;Last=r;}public DateTime GetNowDateTime()=>new DateTime(2026,9,30);}
        internal sealed class Fixture
        {
            public readonly OutgameGlobalItemLifecycle Global=new OutgameGlobalItemLifecycle(new LifecycleHost(),()=>{},i=>true,i=>true,()=>new DateTime(2026,9,30));public readonly OutgameItemConfigSlot Config=new OutgameItemConfigSlot(a=>{});public OutgameMessageDispatcher Messages=new OutgameMessageDispatcher();public readonly Reports Reports=new Reports();public readonly RewardHost Host=new RewardHost();public readonly List<string> Trace=new List<string>(),Errors=new List<string>();public readonly OutgameGlobalItemRewards Engine;public readonly OutgameItemEntityServices Services;
            public Fixture(){Global.InitializeWithHost("",Host);Config.Instance.Items[1001]=new GameItemConfig{id=1001,type1=1,type2=1,item_game="g"};Config.Instance.Items[1002]=new GameItemConfig{id=1002,type1=1,type2=2,item_game="g"};Engine=new OutgameGlobalItemRewards(Global,()=>Config.Instance,()=>Messages,()=>Reports,Errors.Add);Services=new OutgameItemEntityServices{Config=()=>Config.Instance,Rewards=()=>Engine,Messages=()=>Messages,Reports=()=>Reports};Host.Factory=c=>new OutgameItemFactory(c.id,()=>Config.Instance,Errors.Add,Services.Construct).Produce();Messages.AddListener("CommonGameModule_StatisticsEventSet",a=>Trace.Add("statistics:"+a[2]+":"+a[1]));Messages.AddListener("ItemUI_RefreshUserItem",a=>Trace.Add("ui:"+a[0]));Messages.AddListener("Item_ItemChange",a=>Trace.Add("change:"+a[0]+":"+a[1]));}
        }
        static List<OutgameItemReward> Rows(int id,long count)=>new List<OutgameItemReward>{new OutgameItemReward{itemId=id,itemCount=count}};
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-global-reward-new-versus-existing-statistics-order",()=>{var f=new Fixture();bool exists=false;f.Messages.AddListener("CommonGameModule_StatisticsEventSet",a=>{Require(f.Global.Indexes.Items.ContainsKey(1001)==exists,"new row not published before statistics");if(exists)Require(f.Global.GetItemCount(1001)==7,"existing row already changed");});f.Engine.AddRewards(Rows(1001,5));exists=true;f.Engine.AddRewards(Rows(1001,2));Require(f.Host.Adds==2&&f.Reports.Changes.Count==2&&f.Global.GetItemCount(1001)==7&&f.Global.Indexes.Items[1001].holdTime==0,"actual inventory and host delegation");Require(string.Join(",",f.Trace)=="statistics:1001:5,ui:1001,change:1001:5,statistics:1001:7,ui:1001,change:1001:2","source event order");});
            check("source-global-reward-statistics-exception-new-and-existing-prefix",()=>{var f=new Fixture();f.Messages.AddListener("CommonGameModule_StatisticsEventSet",a=>throw new InvalidOperationException());Throws<InvalidOperationException>(()=>f.Engine.AddRewards(Rows(1001,4)));Require(!f.Global.Indexes.Items.ContainsKey(1001)&&f.Host.Adds==0,"new row lost before insertion");f.Global.Indexes.Items[1001]=new OutgameItemUserData{itemId=1001,itemCount=8};Throws<InvalidOperationException>(()=>f.Engine.AddRewards(Rows(1001,4)));Require(f.Global.GetItemCount(1001)==12&&f.Host.Adds==0,"existing mutation retained");});
            check("source-global-reward-reentrant-statistics-insertion-throws",()=>{var f=new Fixture();f.Messages.AddListener("CommonGameModule_StatisticsEventSet",a=>f.Global.Indexes.Items.Add(1001,new OutgameItemUserData{itemId=1001,itemCount=99}));Throws<ArgumentException>(()=>f.Engine.AddRewards(Rows(1001,4)));Require(f.Global.GetItemCount(1001)==99&&f.Trace.Count==1,"source Add after callback cannot overwrite reentrant row");});
            check("source-global-reward-updates-item-snapshot-before-ui-callback",()=>{var f=new Fixture();f.Global.Indexes.Products[1001]=new OutgameProductUserData{m_uniqueId=1001,buyCount=4};f.Global.Indexes.IsDirty=false;f.Messages.AddListener("ItemUI_RefreshUserItem",a=>Require(f.Global.Indexes.ItemSnapshot[1001].itemCount==3,"snapshot before UI"));f.Engine.AddRewardsModel(Rows(1001,3));Require(f.Global.Indexes.ProductSnapshot.Count==0&&f.Global.Indexes.ItemSnapshot[1001].itemCount==3&&!ReferenceEquals(f.Global.Indexes.Items[1001],f.Global.Indexes.ItemSnapshot[1001])&&f.Global.Indexes.IsDirty&&f.Host.Adds==0,"source34596 fields36/44; model path still reports");});
            check("source-global-reward-delegates-replace-entire-default-path",()=>{var f=new Fixture();var rows=Rows(1001,5);int calls=0;f.Engine.AddRewardsDel=(r0,n)=>{Require(ReferenceEquals(r0,rows)&&n==0,"delegate zero source arg");calls++;};f.Engine.AddRewardsModelDel=f.Engine.AddRewardsDel;f.Engine.ExpendRewardsDel=r0=>calls++;f.Engine.AddRewardsByItemSelfDel=f.Engine.ExpendRewardsDel;f.Engine.AddRewards(rows);f.Engine.AddRewardsModel(rows);f.Engine.ExpendReward(rows);f.Engine.AddRewardsByItemSelf(rows);Require(calls==4&&f.Global.Indexes.Items.Count==0&&f.Trace.Count==0&&f.Host.Adds==0&&f.Host.Costs==0,"overrides skip all builtin effects and host");});
            check("source-global-reward-live-list-and-report-override-after-message",()=>{var f=new Fixture();var rows=Rows(1001,5);f.Engine.ReportDel=(id,n,reason)=>{Require(f.Trace[f.Trace.Count-1]=="change:"+id+":"+n&&reason==0,"change message first");if(rows.Count==1)rows.Add(new OutgameItemReward{itemId=1002,itemCount=6});};f.Engine.AddRewards(rows);Require(f.Global.GetItemCount(1002)==6&&f.Host.Adds==1&&ReferenceEquals(f.Host.Last,rows)&&f.Reports.Changes.Count==0,"live loop and custom report replaces default");});
            check("source-global-reward-report-zero-overflow-and-intmin-magnitude",()=>{foreach(long delta in new[]{0L,(long)int.MaxValue+1,int.MinValue,(long)int.MinValue-1,long.MinValue}){var f=new Fixture();f.Engine.AddRewardsModel(Rows(1001,delta));var p=f.Reports.Changes[0];int expected=delta==int.MinValue?int.MinValue:0;Require(p.Amount==expected&&p.Balance==(delta>=int.MinValue&&delta<=int.MaxValue?(int)delta:0)&&f.Reports.Gains[0]==(delta>=1),"source conversion: out of range zero and abs(intMin) wraps");Require(p.Id==1001&&p.Game=="g"&&p.Type1==1&&p.Type2==1,"source-owned report fields");}});
            check("source-global-reward-expend-negates-long-without-insufficient-check",()=>{var f=new Fixture();var rows=Rows(1001,4);f.Engine.ExpendReward(rows);Require(f.Global.GetItemCount(1001)==-4&&f.Host.Costs==1&&ReferenceEquals(f.Host.Last,rows)&&f.Reports.Changes[0].Amount==4,"negative stock permitted and original positive list passed host");f.Engine.ExpendReward(Rows(1002,long.MinValue));Require(f.Global.GetItemCount(1002)==long.MinValue,"unchecked negation wraps");});
            check("source-global-reward-report-missing-null-and-failure-prefix",()=>{var f=new Fixture();Throws<KeyNotFoundException>(()=>f.Engine.AddRewards(Rows(88,2)));Require(f.Global.GetItemCount(88)==2&&f.Trace.Count==3&&f.Host.Adds==0&&f.Errors.Count==0,"missing dictionary key throws after mutation/messages");f.Config.Instance.Items[88]=null;f.Engine.AddRewards(Rows(88,0));Require(f.Errors.Count==1&&f.Errors[0]=="道具上报错误, 未找到道具id 88 , 请检查配置"&&f.Host.Adds==1,"existing null logs then returns to host");});
            check("source-global-reward-report-create-rereads-live-balance",()=>{var f=new Fixture();f.Reports.Creating=()=>f.Global.Indexes.Items[1001].itemCount=77;f.Engine.AddRewards(Rows(1001,4));Require(f.Reports.Changes[0].Amount==4&&f.Reports.Changes[0].Balance==77,"report factory precedes current balance lookup");f.Reports.Sending=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Engine.AddRewards(Rows(1001,1)));Require(f.Host.Adds==1&&f.Global.GetItemCount(1001)==77,"report failure skips host but keeps mutation/callback effects");});
            check("source-global-item-common-item-fallback-and-null-config",()=>{var f=new Fixture();int common=0;f.Engine.GetCommonItem=c=>{common++;return null;};Require(f.Engine.GetItem(null)==null&&common==0,"null config never calls provider");Require(f.Engine.GetItem(f.Config.Instance.Items[1001]) is OutgameGoldItem&&common==1,"null common falls through manager");var diamond=new OutgameDiamondItem(1002,f.Services);f.Engine.GetCommonItem=c=>diamond;Require(ReferenceEquals(f.Engine.GetItem(f.Config.Instance.Items[1001]),diamond),"nonnull common takes precedence");});
            check("source-global-reward-by-self-model-only-then-one-host-call",()=>{var f=new Fixture();var rows=Rows(1001,4);rows.Add(new OutgameItemReward{itemId=1002,itemCount=6});f.Engine.AddRewardsByItemSelf(rows);Require(f.Global.GetItemCount(1001)==4&&f.Global.GetItemCount(1002)==6&&f.Reports.Changes.Count==2&&f.Host.Adds==1,"real Gold/Diamond entities use model path then one host call");f.Host.Factory=c=>null;f.Engine.AddRewardsByItemSelf(Rows(1001,2));Require(f.Global.GetItemCount(1001)==4&&f.Host.Adds==2,"null entity skipped, host still receives list");});
            check("source-item-base-null-config-and-use-does-not-debit",()=>{var f=new Fixture();f.Config.Instance.Items[3]=null;var empty=new OutgameItemBase(3,f.Services);Require(empty.ItemToReward(5).Count==0,"null row gives fresh empty reward list");empty.AddItem(5);Require(f.Host.Adds==1&&f.Global.Indexes.Items.Count==0,"empty list still host callback");var gold=new OutgameGoldItem(1001,f.Services);f.Global.Indexes.Items[1001]=new OutgameItemUserData{itemId=1001,itemCount=9};long amount=0;f.Messages.AddListener("Item_Use",a=>{amount=(long)a[1];Require(f.Reports.Uses.Count==0,"event before report");});gold.Use(4);Require(amount==4&&f.Global.GetItemCount(1001)==9&&f.Reports.Uses[0].Id==1001,"source Use sends event/report only; caller owns debit");});
            check("source-item-base-reward-virtual-dispatch-and-captured-global",()=>{var f=new Fixture();var list=new OutgameGoldItem(1001,f.Services).ItemToReward(long.MaxValue);Require(list.Count==1&&list[0].itemCount==long.MaxValue&&list[0].rewardOrder==0,"Int64 reward and source order0");var item=new OverrideItem(f.Services){During=()=>f.Services.Rewards=()=>throw new Exception("must already have captured engine")};item.AddItem(2);Require(f.Global.GetItemCount(1002)==2&&f.Host.Adds==1,"global resolved before virtual ItemToReward");});
            check("source-global-reward-host-null-initialization-retains-local-time-fallback",()=>{var f=new Fixture();f.Global.InitializeWithHost("",null);Require(f.Global.RewardHost==null&&f.Global.Data.saveTimestamp==OutgameItemTimestamp.FromDateTime(new DateTime(2026,9,30)),"null source host accepted; local clock fallback");f.Engine.AddRewardsModel(Rows(1001,3));Require(f.Global.GetItemCount(1001)==3,"model path needs no host");Throws<NullReferenceException>(()=>f.Engine.AddRewards(Rows(1001,2)));Require(f.Global.GetItemCount(1001)==5,"regular path fails at host after mutation/report");});
            return r;
        }
        sealed class OverrideItem:OutgameItemBase {public Action During;public OverrideItem(OutgameItemEntityServices s):base(1001,s){}public override List<OutgameItemReward> ItemToReward(long n){During();return Rows(1002,n);}}
    }
}
