using System;
using System.Collections.Generic;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameTimeCountdownValidation
    {
        sealed class Fixture:IDisposable
        {
            readonly DateTime savedNow=OutgameTimeClock.Now,savedStart=OutgameTimeClock.StartTime,savedDefault=OutgameTimeClock.DefaultTime;
            readonly bool savedInit=OutgameTimeClock.IsInit,savedFocus=OutgameTimeClock.IsFocus;readonly double savedDifference=OutgameTimeClock.TimeDifference;
            public DateTime Now;public readonly OutgameTimeCountdowns Time;public bool ThrowClock;
            public Fixture(){OutgameTimeClock.DefaultTime=new DateTime(1970,1,1,8,0,0);OutgameTimeClock.TimeDifference=0;Now=OutgameTimeClock.DefaultTime;Time=new OutgameTimeCountdowns(()=>{if(ThrowClock)throw new InvalidOperationException("clock");return Now;});Time.Initialize();}
            public void At(double milliseconds){Now=OutgameTimeClock.StartTime.AddTicks((long)(milliseconds*10000));Time.CheckTime(Now,3.25f);}
            public void Dispose(){OutgameTimeClock.Now=savedNow;OutgameTimeClock.StartTime=savedStart;OutgameTimeClock.DefaultTime=savedDefault;OutgameTimeClock.TimeDifference=savedDifference;OutgameTimeClock.IsInit=savedInit;OutgameTimeClock.IsFocus=savedFocus;}
        }
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-time-local-eight-hour-epoch-and-millisecond-offset",()=>{using(var f=new Fixture()){OutgameTimeClock.TimeDifference=500;f.Now=new DateTime(1970,1,1,8,0,1).AddTicks(2500);Require(Math.Abs(f.Time.GetNowTime()-1500.25)<.00001&&OutgameTimeClock.Now==f.Now&&f.Time.GetNowTimeInt()==1&&f.Time.GetNowTimeLong()==1,"millisecond getters add static offset; seconds getters ignore it and truncate");Require(f.Time.GetTime(new DateTime(1970,1,1))==-28800000+500,"no UTC/local epoch normalization");}});
            check("source-time-int-seconds-overflow-min-and-long",()=>{using(var f=new Fixture()){f.Now=OutgameTimeClock.StartTime.AddSeconds(2147483648d);Require(f.Time.GetNowTimeInt()==int.MinValue&&f.Time.GetNowTimeLong()==2147483648L,"WASM signed conversion out of range returns min");f.Now=OutgameTimeClock.StartTime.AddSeconds(-.75);Require(f.Time.GetNowTimeInt()==0,"negative fractional seconds truncate toward zero");}});
            check("source-time-initialize-replaces-maps-retains-millisecond-clock",()=>{using(var f=new Fixture()){var old=f.Time.CompleteHandles;f.Time.LastTime=12;f.Time.LastMinute=34;f.Time.LastMillisecond=56;f.Time.UnityRealTime=78;f.Time.TimeId=9;f.Time.Initialize();Require(old!=f.Time.CompleteHandles&&f.Time.LastTime==0&&f.Time.LastMinute==0&&f.Time.TimeId==0&&f.Time.LastMillisecond==56&&f.Time.UnityRealTime==78,"source Initialize resets selected fields only");}});
            check("source-time-null-completion-short-circuits-uninitialized",()=>{var t=new OutgameTimeCountdowns(()=>throw new Exception());Require(t.SetCountDownByMillisecond(100,null,(i,n)=>{})==-1&&t.TimeId==0&&t.CompleteHandles==null,"null completion returns -1 before clock/dictionaries/id");});
            check("source-time-registration-clock-failure-partial-state",()=>{using(var f=new Fixture()){f.ThrowClock=true;Throws<InvalidOperationException>(()=>f.Time.SetCountDownByMillisecond(10,i=>{},null));Require(f.Time.TimeId==1&&f.Time.CompleteHandles.ContainsKey(1)&&!f.Time.CompleteTimes.ContainsKey(1),"id/complete insertion commits before time lookup");}});
            check("source-time-id-wrap-and-duplicate-registration",()=>{using(var f=new Fixture()){f.Time.TimeId=int.MaxValue;Require(f.Time.SetCountDownByMillisecond(1,i=>{},null)==int.MinValue,"source unchecked integer id wrap");f.Time.TimeId=int.MaxValue;Throws<ArgumentException>(()=>f.Time.SetCountDownByMillisecond(1,i=>{},null));Require(f.Time.TimeId==int.MinValue&&f.Time.CompleteHandles.Count==1,"duplicate insertion failure retains incremented id");}});
            check("source-time-millisecond-remaining-and-complete-before-every",()=>{using(var f=new Fixture()){var events=new List<string>();int id=f.Time.SetCountDownByMillisecond(100,i=>events.Add("end"),(i,left)=>events.Add("every:"+left));f.At(25.75);f.At(100);Require(id==1&&string.Join(",",events)=="every:74,end"&&f.Time.CompleteHandles.Count==0&&f.Time.EveryMillisecondHandles.Count==0,"remaining truncates before callback; exact deadline completes first and removes every");Require(f.Time.UnityRealTime==3.25&&f.Time.RemoveList.Count==1,"CheckTime writes realtime and completion removal list retained");}});
            check("source-time-complete-snapshots-callbacks-but-live-deadlines",()=>{using(var f=new Fixture()){var events=new List<string>();int second=0;f.Time.SetCountDownByMillisecond(0,i=>{events.Add("first");f.Time.CompleteHandles[second]=j=>events.Add("replacement");},null);second=f.Time.SetCountDownByMillisecond(0,i=>events.Add("captured"),null);f.At(0);Require(string.Join(",",events)=="first,captured","snapshot callback survives replacement");f.Time.Initialize();int a=f.Time.SetCountDownByMillisecond(0,i=>f.Time.RemoveTime(i+1),null);f.Time.SetCountDownByMillisecond(0,i=>events.Add("removed"),null);f.At(0);Require(!events.Contains("removed")&&f.Time.CompleteHandles.Count==0,"removed future deadline prevents snapshotted complete call");}});
            check("source-time-completion-add-defers-new-complete-but-enables-every",()=>{using(var f=new Fixture()){var events=new List<string>();f.Time.SetCountDownByMillisecond(1,i=>{events.Add("parent");f.Time.SetCountDownByMillisecond(0,j=>events.Add("child-end"),(j,left)=>events.Add("child-every:"+left));},null);f.At(1);Require(string.Join(",",events)=="parent,child-every:0","new completion absent from first snapshot, new every present in later pass");f.At(2);Require(events[events.Count-1]=="child-end","new child completes next check");}});
            check("source-time-completion-throw-skips-deferred-cleanup",()=>{using(var f=new Fixture()){int calls=0;int first=f.Time.SetCountDownByMillisecond(0,i=>calls++,null);int second=f.Time.SetCountDownByMillisecond(0,i=>throw new InvalidOperationException(),null);Throws<InvalidOperationException>(()=>f.At(0));Require(calls==1&&f.Time.RemoveList.Count==1&&f.Time.CompleteHandles.Count==2,"earlier completed timer remains when later callback throws before cleanup");f.Time.RemoveTime(second);f.At(0);Require(calls==2&&f.Time.CompleteHandles.Count==0,"earlier callback runs again on retry");}});
            check("source-time-null-completion-entry-is-not-auto-removed",()=>{using(var f=new Fixture()){int id=f.Time.SetCountDownByMillisecond(0,i=>{},null);f.Time.CompleteHandles[id]=null;f.At(1);Require(f.Time.CompleteHandles.ContainsKey(id)&&f.Time.CompleteTimes.ContainsKey(id),"null entry skips callback and remove-list insertion");}});
            check("source-time-every-snapshot-calls-removed-entry-with-zero",()=>{using(var f=new Fixture()){var events=new List<string>();int second=0;f.Time.SetCountDownByMillisecond(100,i=>{},(i,left)=>{events.Add("first");f.Time.RemoveTime(second);});second=f.Time.SetCountDownByMillisecond(100,i=>{},(i,left)=>events.Add("removed:"+left));f.At(25);Require(string.Join(",",events)=="first,removed:0"&&!f.Time.EveryMillisecondHandles.ContainsKey(second),"every snapshots object, missing live deadline means remaining0 instead of skip");}});
            check("source-time-every-uses-live-last-timestamp-per-callback",()=>{using(var f=new Fixture()){int secondCalls=0;f.Time.SetCountDownByMillisecond(100,i=>{},(i,left)=>f.Time.LastMillisecond=9.5);int second=f.Time.SetCountDownByMillisecond(100,i=>{},(i,left)=>secondCalls++);f.At(10);Require(secondCalls==0&&f.Time.EveryMillisecondHandles[second].Accumulated==.5f&&f.Time.LastMillisecond==10,"earlier callback changes subsequent elapsed calculation; outer successful pass writes now last");}});
            check("source-time-every-error-retains-accumulator-and-last",()=>{using(var f=new Fixture()){int id=f.Time.SetCountDownByMillisecond(100,i=>{},(i,left)=>throw new InvalidOperationException());Throws<InvalidOperationException>(()=>f.At(10));Require(f.Time.EveryMillisecondHandles[id].Accumulated==10&&f.Time.LastMillisecond==0,"callback throws before accumulation reset and timestamp assignment");f.Time.EveryMillisecondHandles[id].Callback=(i,left)=>{};f.At(10);Require(f.Time.EveryMillisecondHandles[id].Accumulated==0&&f.Time.LastMillisecond==10,"successful retry resets accumulated remainder entirely");}});
            check("source-time-every-large-gap-fires-once-and-discards-remainder",()=>{int calls=0;var e=new OutgameTimeEvery((i,left)=>calls++,3);e.Call(1,10,2);e.Call(1,8,8);Require(calls==1&&e.Accumulated==0,"10 elapsed with interval3 invokes once, resets0; no catchup loop");});
            check("source-time-cadence-empty-map-asymmetry-and-no-focus-gate",()=>{using(var f=new Fixture()){OutgameTimeClock.IsFocus=false;f.At(60000);Require(f.Time.LastTime==60000&&f.Time.LastMillisecond==60000&&f.Time.LastMinute==0,"empty second/ms advance last; minute requires nonempty map");int calls=0;f.Time.EveryMinuteHandles.Add(8,new OutgameTimeEvery((i,left)=>calls++,1));f.At(60000);Require(calls==1&&f.Time.LastMinute==60000,"no focus gate; orphan minute callback invoked with zero remaining");}});
            check("source-time-second-minute-int-conversion-before-division",()=>{using(var f=new Fixture()){int second=0,minute=0;f.Time.CompleteTimes[1]=3000000000d;f.Time.EverySecondHandles[1]=new OutgameTimeEvery((i,left)=>second=left,1);f.Time.EveryMinuteHandles[1]=new OutgameTimeEvery((i,left)=>minute=left,1);f.At(60000);Require(second==int.MinValue/1000&&minute==int.MinValue/60000,"remaining milliseconds overflow to min before integer unit division");}});
            check("source-time-clock-rewind-suppresses-every-until-forward",()=>{using(var f=new Fixture()){int calls=0;f.Time.SetCountDownByMillisecond(1000,i=>{},(i,left)=>calls++);f.At(100);f.At(90);f.At(100);Require(calls==1&&f.Time.LastMillisecond==100,"strict ms>last suppresses rewind/equality");f.At(101);Require(calls==2,"forward wall clock resumes callbacks");}});
            check("source-time-clear-countdowns-retains-last-ms-and-realtime",()=>{using(var f=new Fixture()){f.Time.SetCountDownByMillisecond(100,i=>{},(i,left)=>{});f.At(10);var map=f.Time.CompleteHandles;f.Time.ClearCountdowns();Require(ReferenceEquals(map,f.Time.CompleteHandles)&&map.Count==0&&f.Time.CompleteTimes.Count==0&&f.Time.EveryMillisecondHandles.Count==0&&f.Time.LastMillisecond==10&&f.Time.UnityRealTime==3.25&&f.Time.TimeId==0,"source clear mutates existing maps and leaves selected timestamps");}});
            check("source-time-binds-actual-audio-fade-countdown",()=>{using(var f=new Fixture())using(var audio=new OutgameAudioPlaybackValidation.Fixture()){f.Time.BindAudio(audio.Services);var a=new OutgameAudioFadeAction(audio.Root,1002,null,null,audio.Services);a.Play();f.At(250);Require(Mathf.Abs(a.AudioSource.volume-.125f)<.0001,"actual source countdown drives fade curve");f.At(1000);Require(a.AudioSource.volume==.5f&&f.Time.CompleteHandles.Count==0,"source complete removes its own timer safely during completion iteration");a.Stop();f.At(1500);Require(Mathf.Abs(a.AudioSource.volume-.25f)<.0001,"stop schedules another real source timer");f.At(2000);Require(!a.AudioSource&&a.UpdateId==0&&f.Time.CompleteHandles.Count==0,"audio completion/removal/Dispose repeated RemoveTime integrates safely");}});
            return r;
        }
    }
}
