using System;
using System.Collections.Generic;
using UnityEngine;
using Random=System.Random;
using AreaBattle.SharedItemConfig;
namespace AreaBattle.EditorTools
{
    public static class OutgameItemModuleValidation
    {
        sealed class Backend:IOutgameStorageBackend
        {public readonly Dictionary<string,string> Data=new Dictionary<string,string>();public int Writes;public string Get(string k)=>Data.TryGetValue(k,out var v)?v:null;public void Set(string k,string v,Action<string> f,Action c){Data[k]=v;Writes++;c();}public void Remove(string k,Action<string> f,Action c){Data.Remove(k);c();}public void Clear(Action<string> f,Action c){Data.Clear();c();}}
        sealed class StorageHost:IOutgameDataStorageHost
        {public int Progress;public bool Server;public int SourceLoginProgress=>Progress;public bool LoginProcedureFlag8=>false;public bool LoginStaticFlag4=>false;public bool IsUseServer=>Server;public string MineGameName=>"item-fixture";public bool HasToast=>false;public void Log(string s){}public void Error(string s){}public void Toast(string s){}public string Compress(string k,string s)=>s;public string Decompress(string k,string s)=>s;public void QueueUpload(string k,string s){}}
        sealed class GlobalHost:IOutgameGlobalItemLifecycleHost
        {public readonly List<string> Trace=new List<string>();public int AddUpdate(Action a){Trace.Add("update+");return 8;}public void RemoveUpdate(int id)=>Trace.Add("update-:"+id);public void DisposeItemConfiguration()=>Trace.Add("config-dispose");public void ClearGlobalInstance()=>Trace.Add("global-clear");public void SendStatisticsRegistration(string m,int id,Func<object[],long> f)=>Trace.Add("statistics");}
        sealed class Effects:IOutgameToolEffects
        {public Action Saving;public readonly List<string> Trace=new List<string>();public void RefreshTopInfo()=>Trace.Add("top");public void GoldSpent(int id,long n)=>Trace.Add("spent");public void ToolChanged(int id)=>Trace.Add("change");public void UnlockScene(int id)=>Trace.Add("scene");public void UnlockSoldier(int id)=>Trace.Add("soldier");public bool ApplyItemEntity(int id,long n)=>throw new Exception("Type6 must be skipped");public void MissingItemEntity(int id)=>throw new Exception();public void ReportGet(int id,int c,int n,int b,string r)=>Trace.Add("report");public void ReportCost(int id,int c,int n,int b)=>Trace.Add("report");public void Save(){Trace.Add("save");Saving?.Invoke();}}
        // Explicit entity boundary: records invocation only, never substitutes original entity effects.
        sealed class Entity:IOutgameItemEntity {public Action<long> Apply;public void AddItem(long n)=>Apply(n);public void AddItemOnlyModel(long n)=>Apply(n);}
        sealed class Fixture
        {
            public readonly Backend Backend;public readonly StorageHost Host=new StorageHost();public readonly GlobalHost GlobalHost=new GlobalHost();public readonly OutgameControllerRegistry Registry=new OutgameControllerRegistry();public readonly OutgameItemConfigSlot ConfigSlot=new OutgameItemConfigSlot(a=>{});public OutgameDataManagerPool Pool;public OutgameGlobalItemLifecycle Global;public OutgameItemManager Manager;public OutgameMessageDispatcher Messages=new OutgameMessageDispatcher();public readonly Effects Effects=new Effects();public readonly OutgameLocalInventoryState Local=new OutgameLocalInventoryState();public readonly List<string> Trace=new List<string>(),Warnings=new List<string>();public Func<int,int,IOutgameItemEntity> Construct;public DateTime Now=new DateTime(2026,9,30,11,0,0);public int Downloads;
            public Fixture(Backend backend=null){Backend=backend??new Backend();Construct=(t,id)=>new Entity{Apply=n=>Trace.Add("entity:"+id+":"+n)};Pool=new OutgameDataManagerPool(()=>{},Warnings.Add,s=>{},s=>Trace.Add("pool-error"));Pool.OnInit(false,"item-fixture",new OutgameManagerRegistration[0]);ConfigSlot.Instance.Items[8001]=new GameItemConfig{id=8001,type1=1,type2=1};Global=new OutgameGlobalItemLifecycle(GlobalHost,()=>{},id=>true,id=>true,()=>Now);var inventory=new OutgameLocalInventory(Local,"{\"Datas\":[]}");var dispatcher=new OutgameToolDispatcher(inventory,Effects,"{\"Datas\":[{\"id\":8001}]}","{\"Datas\":[]}","{\"Datas\":[]}");var tool=new OutgameToolControl(()=>dispatcher,()=>inventory,id=>Global.GetItemCount(id),()=>"PurchaseCost");var storage=new OutgameDataManagerStorage(()=>"ItemManager",Host,new OutgameSdkStringStorage(Backend,s=>{}),new OutgameDataVersionState(()=>{},()=>{},()=>{},n=>{},s=>{}));Manager=new OutgameItemManager(storage,Host,s=>Downloads++,()=>Global,id=>new OutgameItemFactory(id,()=>ConfigSlot.Instance,Warnings.Add,(t,n)=>Construct(t,n)),()=>tool,dispatcher.GoodsType,()=>Now);Pool.Managers[4500]=Manager;Manager.OnInit();Messages.AddListener("Item_Change",args=>Trace.Add("message:"+args[0]));OutgameCoreControllerBindings.BindItems(Registry,()=>Pool,()=>ConfigSlot.Instance,()=>Messages,Warnings.Add);}
            public OutgameItemModuleControl Control=>(OutgameItemModuleControl)Registry.Resolve(3875);
        }
        sealed class LowestRandom:Random {public override int Next(int min,int max)=>min;}
        static void Require(bool b,string s){if(!b)throw new Exception(s);}static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var r=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion};Action<string,Action> check=(id,a)=>{try{a();r.checks.Add(new BattleBuild.Check{id=id,result="pass"});}catch(Exception ex){r.passed=false;r.checks.Add(new BattleBuild.Check{id=id,result="fail",detail=ex.ToString()});}};
            check("source-item-manager-original-record-local-restart-and-login-gate",()=>{var f=new Fixture();f.Global.Indexes.Items[8001]=new OutgameItemUserData{itemId=8001,itemCount=0x100000003L};f.Manager.OnSave();Require(f.Backend.Writes==0,"real login gate not bypassed");f.Host.Progress=10;f.Global.Indexes.Items[8001].itemCount++;f.Manager.OnSave();Require(f.Backend.Writes==1,"changed state writes after explicitly configured test login");var restarted=new Fixture(f.Backend);Require(restarted.Manager.GetItemNum(8001)==0x100000004L&&restarted.Global.Data.saveTimestamp==OutgameItemTimestamp.FromDateTime(restarted.Now),"Int64 record restores through actual storage and global lifecycle");});
            check("source-item-manager-server-download-gate-and-current-global",()=>{var f=new Fixture();var old=f.Global;f.Host.Server=true;f.Manager.UpdateData(true);Require(f.Downloads==1&&ReferenceEquals(old,f.Global),"download request, no implicit callback");f.Manager.ParticipatesInSync=false;f.Manager.UpdateData(true);Require(f.Downloads==1,"autosyn false reads local");var replacement=new OutgameGlobalItemLifecycle(f.GlobalHost,()=>{},id=>true,id=>true,()=>f.Now);f.Global=replacement;f.Manager.UpdateDataCallBack("{\"itemUserDatas\":[{\"itemId\":8001,\"itemCount\":9}],\"productUserDatas\":[]}");Require(f.Manager.GetItemNum(8001)==9&&ReferenceEquals(replacement,f.Global),"every callback/count resolves current global");});
            check("source-item-manager-slots-retry-null-then-cache-through-release",()=>{var f=new Fixture();f.Pool.Managers.Remove(4500);var slot=new OutgameItemManagerSlot(()=>f.Pool);Require(slot.Instance==null&&f.Control.ItemMgr==null&&f.Warnings.Count==2,"missing pool lookup retries");f.Pool.Managers[4500]=f.Manager;Require(ReferenceEquals(slot.Instance,f.Manager)&&ReferenceEquals(f.Control.ItemMgr,f.Manager),"both caches populate");f.Pool.Managers.Remove(4500);f.Manager.OnRelease();Require(ReferenceEquals(slot.Instance,f.Manager)&&ReferenceEquals(f.Control.ItemMgr,f.Manager)&&string.Join(",",f.GlobalHost.Trace).EndsWith("update-:8,config-dispose,global-clear"),"release affects global but not manager slots");});
            check("source-item-manager-reward-filter-truncation-and-live-list",()=>{var f=new Fixture();var rewards=new List<OutgameItemReward>{new OutgameItemReward{itemId=8001,itemCount=3},new OutgameItemReward{itemId=1001,itemCount=0x100000002L}};f.Effects.Saving=()=>{if(rewards.Count==2)rewards.Add(new OutgameItemReward{itemId=1002,itemCount=4});};f.Manager.AddRewards(rewards);Require(f.Local.goldNum==2&&f.Local.diamondsNum==4&&string.Join(",",f.Effects.Trace)=="save,save"&&f.Trace.Count==0,"type6 skip, signed low32, live loop, refresh/report false");f.Manager.ExpendReward(null);f.Manager.Update();});
            check("source-item-manager-reward-save-failure-keeps-prefix",()=>{var f=new Fixture();f.Effects.Saving=()=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Manager.AddRewards(new List<OutgameItemReward>{new OutgameItemReward{itemId=1001,itemCount=3},new OutgameItemReward{itemId=1002,itemCount=4}}));Require(f.Local.goldNum==3&&f.Local.diamondsNum==0,"no atomic rollback or continuation");});
            check("source-item-manager-package-rewards-drain-shares-rows",()=>{var f=new Fixture();var row=new OutgameItemReward{itemId=3,itemCount=9};var held=f.Manager.PackageOpenRewardsTemp;held.AddLast(row);held.AddLast(row);var rewards=f.Manager.GetPackageOpenReward();Require(rewards.Count==2&&ReferenceEquals(rewards[0],row)&&ReferenceEquals(held,f.Manager.PackageOpenRewardsTemp)&&held.Count==0&&f.Manager.GetPackageOpenReward().Count==0,"copy list, shared row references, clear same linked list");});
            check("source-item-factory-all-source-subtype-mappings",()=>{var f=new Fixture();var cases=new[]{new[]{1,1,4496},new[]{1,2,4494},new[]{1,4,4499},new[]{1,5,4493},new[]{1,8,4498},new[]{1,10,4497},new[]{1,11,4495},new[]{9,1,4490},new[]{9,2,4491}};int seen=0;foreach(var c in cases){f.ConfigSlot.Instance.Items[8001]=new GameItemConfig{id=8001,type1=c[0],type2=c[1]};f.Construct=(t,id)=>{Require(t==c[2]&&id==8001,"exact original source type");seen++;return new Entity();};Require(f.Manager.GetItem(new GameItemConfig{id=8001,type1=99})!=null,"input config supplies id only; factory rereads current table");}Require(seen==9,"all supported types");foreach(var c in new[]{new[]{4,1},new[]{1,3},new[]{1,6},new[]{1,7},new[]{1,9},new[]{9,3}}){f.ConfigSlot.Instance.Items[8001]=new GameItemConfig{id=8001,type1=c[0],type2=c[1]};Require(f.Manager.GetItem(f.ConfigSlot.Instance.Items[8001])==null,"source unsupported subtype returns null");}});
            check("source-item-factory-missing-and-current-table-reread",()=>{var s=new OutgameItemConfigSlot(a=>{});var errors=new List<string>();var factory=new OutgameItemFactory(7,()=>s.Instance,errors.Add,(t,id)=>new Entity());Require(errors.Count==1&&errors[0]=="无法创建当前道具 id :7","constructor logs missing");Throws<NullReferenceException>(()=>factory.Produce());s.Instance.Items[7]=new GameItemConfig{id=7,type1=1,type2=1};factory=new OutgameItemFactory(7,()=>s.Instance,errors.Add,(t,id)=>{Require(t==4494,"subfactory uses current row");return new Entity();});s.Instance.Items[7]=new GameItemConfig{id=7,type1=1,type2=2};Require(factory.Produce()!=null,"subfactory constructor rereads table");});
            check("source-item-module-init-categories-and-repeated-init-prefix",()=>{var f=new Fixture();var c=f.ConfigSlot.Instance;c.Items.Clear();c.Items[1]=new GameItemConfig{id=1,type1=6};c.Items[2]=new GameItemConfig{id=2,type1=4};c.Items[3]=new GameItemConfig{id=3,type1=5};f.Control.OnInit();Require(f.Control.Props.Count==1&&f.Control.Skills.Count==1&&f.Control.Heroes.Count==1&&ReferenceEquals(c.Items,f.Control.Items),"three categories and shared table");var newHero=new GameItemConfig{id=1,type1=6};c.Items[1]=newHero;Throws<ArgumentException>(f.Control.OnInit);Require(ReferenceEquals(f.Control.Heroes[1],newHero)&&f.Control.Props.Count==1,"hero overwrites before duplicate prop throws, no clears");});
            check("source-item-module-init-rereads-current-config-and-dispose-retains-data",()=>{var f=new Fixture();var old=f.ConfigSlot.Instance;var replacement=new OutgameItemConfigSlot(a=>{}).Instance;replacement.Items[3]=new GameItemConfig{id=3,type1=6};int reads=0;var registry=new OutgameControllerRegistry();OutgameCoreControllerBindings.BindItems(registry,()=>f.Pool,()=>++reads==1?old:replacement,()=>f.Messages,f.Warnings.Add);var c=(OutgameItemModuleControl)registry.Resolve(3875);c.OnInit();Require(ReferenceEquals(c.Items,old.Items)&&c.Heroes.ContainsKey(3),"two current config reads intentionally distinct");c.Updata(1,1);c.OnDispose();Require(c.Heroes.Count==1&&!registry.HasInstance(3875),"dispose clears slot only");var fresh=registry.Resolve(3875);c.OnDispose();Require(!registry.HasInstance(3875)&&fresh!=null,"stale instance clears replacement");});
            check("source-item-module-rejects-negative-and-overflow-before-factory",()=>{var f=new Fixture();Require(!f.Control.ChangeItemNum(8001,-1)&&f.Trace.Count==0&&f.Warnings[0]=="道具 8001 数量不足!!!","insufficient balance no effects");f.Global.Indexes.Items[8001]=new OutgameItemUserData{itemId=8001,itemCount=long.MaxValue};Require(!f.Control.ChangeItemNum(8001,1)&&f.Trace.Count==0,"unchecked Int64 overflow rejected as negative");});
            check("source-item-module-add-message-save-order-zero-and-no-balance-recheck",()=>{var f=new Fixture();f.Host.Progress=10;f.Global.Indexes.Items[8001]=new OutgameItemUserData{itemId=8001,itemCount=5};f.Construct=(t,id)=>new Entity{Apply=n=>{f.Trace.Add("entity:"+n);f.Global.Indexes.Items[id].itemCount=99;}};f.Messages.AddListener("Item_Change",args=>{Require(f.Backend.Writes==0&&f.Global.GetItemCount(8001)==99,"message after entity before save");});Require(f.Control.ChangeItemNum(8001,0)&&string.Join(",",f.Trace)=="entity:0,message:8001"&&f.Backend.Writes==1,"zero still invokes all stages; entity decides mutation");});
            check("source-item-module-entity-and-message-failures-skip-save",()=>{var f=new Fixture();f.Host.Progress=10;f.Construct=(t,id)=>new Entity{Apply=n=>throw new InvalidOperationException()};Throws<InvalidOperationException>(()=>f.Control.ChangeItemNum(8001,1));Require(f.Trace.Count==0&&f.Backend.Writes==0,"entity throw skips message/save");f.Construct=(t,id)=>new Entity{Apply=n=>f.Trace.Add("entity")};f.Messages.AddListener("Item_Change",args=>throw new InvalidOperationException());Throws<InvalidOperationException>(()=>f.Control.ChangeItemNum(8001,1));Require(string.Join(",",f.Trace)=="entity,message:8001"&&f.Backend.Writes==0,"message failure leaves entity prefix");});
            check("source-item-module-unsupported-factory-and-current-query-config",()=>{var f=new Fixture();f.ConfigSlot.Instance.Items[8001].type1=4;Throws<NullReferenceException>(()=>f.Control.ChangeItemNum(8001,1));Require(f.Trace.Count==0,"source null entity fails, no fallback");f.Control.OnInit();var held=f.Control.Items;f.ConfigSlot.Instance.Dispose();var row=new GameItemConfig{id=8001,type1=9};f.ConfigSlot.Instance.Items[8001]=row;Require(ReferenceEquals(f.Control.GetItemConfig(8001),row)&&!ReferenceEquals(held,f.ConfigSlot.Instance.Items),"GetItemConfig resolves current singleton not initialization snapshot");});
            check("source-item-module-real-gold-entity-global-local-and-storage-chain",()=>{var f=new Fixture();f.Host.Progress=10;f.ConfigSlot.Instance.Items[1001]=new GameItemConfig{id=1001,type1=1,type2=1};var reports=new OutgameGlobalItemRewardsValidation.Reports();var engine=new OutgameGlobalItemRewards(f.Global,()=>f.ConfigSlot.Instance,()=>f.Messages,()=>reports,f.Warnings.Add);var services=new OutgameItemEntityServices{Config=()=>f.ConfigSlot.Instance,Rewards=()=>engine,Messages=()=>f.Messages,Reports=()=>reports};f.Construct=services.Construct;Require(f.Control.ChangeItemNum(1001,7)&&f.Global.GetItemCount(1001)==7&&f.Local.goldNum==7&&f.Backend.Writes==1&&reports.Changes.Count==1,"real module -> manager -> factory -> Gold -> global -> manager -> Tool/local -> pool/storage");Require(f.Control.ChangeItemNum(1001,-3)&&f.Global.GetItemCount(1001)==4&&f.Local.goldNum==4&&f.Backend.Writes==2&&!reports.Gains[1],"real debit and report flow");var restored=new Fixture(f.Backend);Require(restored.Global.GetItemCount(1001)==4,"shared record reload includes real entity mutations");});
            check("source-item-module-real-package-through-tools-and-persistence",()=>{var f=new Fixture();f.Host.Progress=10;f.ConfigSlot.Instance.Items.Clear();f.ConfigSlot.Instance.InitLegacyUnityJson(new OutgameLegacyConfigRead(n=>Resources.Load<TextAsset>("Recovered/FirstPack/Config/"+n),s=>{}));var reports=new OutgameGlobalItemRewardsValidation.Reports();var engine=new OutgameGlobalItemRewards(f.Global,()=>f.ConfigSlot.Instance,()=>f.Messages,()=>reports,f.Warnings.Add);var services=new OutgameItemEntityServices{Config=()=>f.ConfigSlot.Instance,Rewards=()=>engine,Messages=()=>f.Messages,Reports=()=>reports,Packages=new OutgamePackageServices{Manager=()=>f.Manager,NewChanceRandom=()=>new LowestRandom(),Random=new GameRandomSource(new LowestRandom()),Error=f.Warnings.Add}};f.Construct=services.Construct;Require(f.Control.ChangeItemNum(20000,1)&&f.Local.goldNum==10&&f.Local.diamondsNum==5&&f.Global.GetItemCount(1001)==10&&f.Global.GetItemCount(1002)==5&&f.Manager.PackageOpenRewardsTemp.Count==2&&f.Backend.Writes==1,"real module, package, global model, manager, local tools and storage");var restarted=new Fixture(f.Backend);Require(restarted.Global.GetItemCount(1001)==10&&restarted.Global.GetItemCount(1002)==5&&restarted.Global.GetItemCount(20000)==0,"source reward stock persisted; no invented consumed package row");});
            return r;
        }
    }
}
