using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
namespace AreaBattle.EditorTools
{
    public static class OutgameRankTransmitterValidation
    {
        public sealed class Request
        {public string Url,Json;public object Data,UserData;public Action<int,object> Callback;}
        public sealed class Fixture
        {
            public readonly OutgameMessageDispatcher Bus=new OutgameMessageDispatcher();
            public readonly List<string> Trace=new List<string>();public readonly List<Request> Requests=new List<Request>();
            public readonly List<OutgameHttpErrorRecord> Errors=new List<OutgameHttpErrorRecord>();public readonly List<int> CryptoErrors=new List<int>();
            public readonly OutgameHttpTransmitterServices Services;public readonly OutgameRanklistTransmitter Transmitter;
            public Action<Request> Sending;public int Rate=20;public bool Encrypt;
            public Fixture()
            {
                Services=new OutgameHttpTransmitterServices{EncryptionEnabled=()=>Encrypt,Key=()=>"abc",LogEnabled=()=>false,
                    NetLog=a=>Trace.Add("net"),Warning=a=>Trace.Add("warning"),Log=a=>Trace.Add("log:"+a[0]),Messages=()=>Bus,
                    NewErrorReport=()=>{Trace.Add("new-report");return new OutgameHttpErrorRecord();},ReportError=e=>{Errors.Add(e);Trace.Add("report");},
                    ReportCryptoError=(code,msg)=>CryptoErrors.Add(code),CryptoError=e=>Trace.Add("crypto-error")};
                Services.AddWebRequest=(url,data,callback,userData)=>{
                    var request=new Request{Url=url,Data=data,Json=LitJson.JsonMapper.ToJson(data),Callback=callback,UserData=userData};Requests.Add(request);Sending?.Invoke(request);return Requests.Count;
                };
                foreach(string name in new[]{"GF_HttpServerSuccess","GF_HttpServerErrorCode","GF_HttpWebRequestError"}){string key=name;Bus.AddListener(key,a=>Trace.Add(key));}
                Transmitter=new OutgameRanklistTransmitter(Services,()=>Rate){RanklistName="fixture-rank",Uid="fallback"};Transmitter.SetUrl("https://fixture.invalid");Transmitter.InitProtocol();
            }
            public void Success(int index,string json)=>Requests[index].Callback(1,new OutgameHttpSuccess{SerialId=index+1,UserData=Requests[index].UserData,Bytes=Encoding.UTF8.GetBytes(json)});
            public void Failure(int index)=>Requests[index].Callback(2,new OutgameHttpFailure{SerialId=index+1,UserData=Requests[index].UserData,Uri=Requests[index].Url,Error="explicit transport failure"});
        }
        static void Need(bool b,string why){if(!b)throw new Exception(why);}
        static void Throws<T>(Action a)where T:Exception{try{a();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
        public static BattleBuild.Report Run()
        {
            var report=new BattleBuild.Report{passed=true,unityVersion=Application.unityVersion,limitations="Source BaseHttpNetTransmitter and RanklistTransmitter requests/callbacks plus original AES wrapper. WebRequestManager queue/agent HTTP IO, HttpManager/NetTool platform/domain/key installation and report upload remain explicit ports. Responses are test events, no remote server success claimed."};
            Action<string,Action> check=(id,a)=>{try{a();report.checks.Add(new BattleBuild.Check{id="rank-transmitter-"+id,result="pass"});}catch(Exception e){report.passed=false;report.checks.Add(new BattleBuild.Check{id="rank-transmitter-"+id,result="fail",detail=e.ToString()});}};
            check("protocol-paths-duplicate-init-and-url-capture",()=>{var f=new Fixture();var t=f.Transmitter;Need(t.Urls[8101]=="https://fixture.invalid/mini-toplist/knock"&&t.Urls[8102].EndsWith("/query")&&t.Urls[8103].EndsWith("/delete"),"original8101..8103 paths");t.SetUrl("changed");t.InitProtocol();Need(t.Urls[8101].StartsWith("https://fixture.invalid")&&f.Trace.Count==3,"duplicate init logs without changing captured URLs");});
            check("match-upload-original-fields-and-independent-ext-uid",()=>{var f=new Fixture();f.Transmitter.SendRankDataRequest("","昵称","avatar",3,4,2,99);var d=LitJson.JsonMapper.ToObject<OutgameSendRankRequest>(f.Requests[0].Json);Need(d.uid=="fallback"&&d.name=="fixture-rank"&&d.category==2&&d.score==60&&d.forceUpdate&&!d.incr&&d.ext.uid==null&&d.ext.nick=="昵称"&&d.ext.victoryNum==3&&d.ext.defeatNum==4&&d.ext.totalScore==99,"request score=Rate*wins, weight in extension only");});
            check("player-query-cache-stale-category-name-offset",()=>{var f=new Fixture();var t=f.Transmitter;t.GetPlayerRankDataRequest(2,7);var original=f.Requests[0].Data;t.RanklistName="changed";t.Uid="next";t.GetPlayerRankDataRequest(3,9);Need(f.Requests[1].Data==original,"player query keeps cached request");t.GetRankDataRequest(1,4,10);var d=LitJson.JsonMapper.ToObject<OutgameGetRankRequest>(f.Requests[2].Json);Need(d.category==2&&d.name=="fixture-rank"&&d.uid=="next"&&d.offset=="9"&&d.page==4&&d.count==10,"list call reuses previous category/name/offset while replacing uid/page/count");t.GetRankDataRequest(1,0,20);d=LitJson.JsonMapper.ToObject<OutgameGetRankRequest>(f.Requests[3].Json);Need(d.category==1&&d.name=="changed"&&d.offset==null&&f.Requests[3].Data!=original,"list call clears cache only after Send returns");});
            check("upload-send-failure-retains-prior-cache",()=>{var f=new Fixture();f.Sending=r=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>f.Transmitter.SendRankDataRequest("first","a","b",2,3,2,40));var held=f.Requests[0].Data;f.Sending=null;f.Rate=99;f.Transmitter.SendRankDataRequest("second","x","y",9,9,3,100);var d=LitJson.JsonMapper.ToObject<OutgameSendRankRequest>(f.Requests[1].Json);Need(f.Requests[1].Data==held&&d.uid=="first"&&d.score==40&&d.category==2,"failed send retains all initial arguments");});
            check("level-upload-increment-and-shared-cache",()=>{var f=new Fixture();var t=f.Transmitter;t.SendLevelRankDataRequest(null,"n","a",1,50);var a=LitJson.JsonMapper.ToObject<OutgameSendRankRequest>(f.Requests[0].Json);t.SendLevelRankDataRequest("u","n","a",3,60);var b=LitJson.JsonMapper.ToObject<OutgameSendRankRequest>(f.Requests[1].Json);Need(!a.incr&&!a.forceUpdate&&a.ext.totalScore==50&&a.ext.victoryNum==0&&b.incr&&b.score==60,"level request flags");f.Sending=r=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>t.SendLevelRankDataRequest("old","n","a",2,70));f.Sending=null;t.SendRankDataRequest("new","x","y",8,9,1,999);a=LitJson.JsonMapper.ToObject<OutgameSendRankRequest>(f.Requests[3].Json);Need(a.uid=="old"&&a.category==2&&a.score==70&&!a.incr&&!a.forceUpdate,"match send shares level cache but clears incr");});
            check("query-response-routes-by-count-not-rank",()=>{var f=new Fixture();var t=f.Transmitter;int mine=0,list=0;t.MineRankResponse=r=>{mine++;Need(r.data.no==7,"parsed data rank");};t.GetRankResponse=r=>list++;t.GetRankDataRequest(1,1,2);f.Success(0,"{\"code\":0,\"data\":{\"count\":0,\"no\":7}}");f.Success(0,"{\"code\":0,\"data\":{\"count\":2,\"no\":0}}");f.Success(0,"{\"code\":9,\"msg\":\"bad\",\"data\":{\"count\":2}}");Need(mine==1&&list==1&&f.Errors.Single().Code==9,"data.count selects mine/list; nonzero code rejected by rank parser");});
            check("business-error-still-invokes-upload-after-report",()=>{var f=new Fixture();f.Transmitter.SendResponseCallback=()=>f.Trace.Add("upload");f.Transmitter.SendRankDataRequest("u","n","a",1,1,1,1);f.Trace.Clear();f.Success(0,"{\"code\":42,\"msg\":\"denied\"}");Need(f.Trace.SequenceEqual(new[]{"net","GF_HttpServerErrorCode","warning","new-report","report","upload"})&&f.Errors[0].Message=="8101","source business error reports then dispatches upload callback");});
            check("transport-failure-reports-without-protocol-callback",()=>{var f=new Fixture();int calls=0;f.Transmitter.SendResponseCallback=()=>calls++;f.Transmitter.SendRankDataRequest("u","n","a",1,1,1,1);f.Trace.Clear();f.Failure(0);Need(calls==0&&f.Errors[0].Code==-9999&&f.Trace.SequenceEqual(new[]{"GF_HttpWebRequestError","new-report","report","warning"}),"failure message then report then warning, no upload response");});
            check("late-callback-current-delegate-and-message-reentry",()=>{var f=new Fixture();int old=0,next=0;f.Transmitter.SendResponseCallback=()=>old++;f.Transmitter.SendRankDataRequest("u","n","a",1,1,1,1);f.Transmitter.SendResponseCallback=()=>next++;f.Success(0,"{\"code\":0}");Need(old==0&&next==1,"response uses current delegate");f.Bus.AddListener("GF_HttpServerSuccess",a=>f.Transmitter.Dispose());Throws<KeyNotFoundException>(()=>f.Success(0,"{\"code\":0}"));Need(next==1,"success event can clear actions before lookup");});
            check("disposal-suppresses-inflight-response-and-send",()=>{var f=new Fixture();f.Transmitter.SendRankDataRequest("u","n","a",1,1,1,1);int calls=0;f.Transmitter.SendResponseCallback=()=>calls++;f.Transmitter.Dispose();f.Success(0,"invalid");Need(f.Transmitter.Send(8101,null)==-1&&calls==0&&f.Transmitter.Urls.Count==0&&f.Transmitter.SendResponseCallback!=null,"disposed flag gates parse/send but retains derived callbacks");});
            check("invalid-raw-json-and-unknown-protocol-fail-after-prefix",()=>{var f=new Fixture();Need(f.Transmitter.Send(999,null)==-1&&f.Requests.Count==0,"unregistered send rejected");f.Transmitter.GetRankDataRequest(1,0,1);Throws<LitJson.JsonException>(()=>f.Success(0,"invalid"));Need(!f.Trace.Contains("GF_HttpServerSuccess"),"parse fails before success message");Throws<KeyNotFoundException>(()=>f.Transmitter.RequestCallBack(1,new OutgameHttpSuccess{UserData=999,Bytes=Encoding.UTF8.GetBytes("{\"code\":0}")}));Need(f.Trace.Last()=="GF_HttpServerSuccess","callback dictionary failure follows success event");});
            check("cipher-independent-openssl-vector-and-key-normalization",()=>{var f=new Fixture();var cipher=new OutgameHttpCipher(f.Services);const string text="{\"msg\":\"原版\",\"code\":0}";const string expected="x4DKo+xbPobmUvTENmnGYmhYydkmxvrRXbBfi/jnA9Y=";Need(cipher.Encrypt(text,"abc")==expected&&cipher.Decrypt(expected,"abc")==text,"independent OpenSSL AES128CBC vector includes original UTF8 stream BOM");Need(OutgameHttpCipher.NormalizeKey("abc")=="abc0000000000000"&&OutgameHttpCipher.NormalizeKey("12345678901234567")=="1234567890123456","source16 UTF16char normalization");});
            check("cipher-errors-report-return-null-and-callback-exceptions",()=>{var f=new Fixture();var cipher=new OutgameHttpCipher(f.Services);Need(cipher.Encrypt("x",null)==null&&cipher.Decrypt("bad","abc")==null&&f.CryptoErrors.SequenceEqual(new[]{1008,1007}),"source errors swallowed after reporting and logging");Need(cipher.Encrypt("x","中文中文中文中文中文中文中文中文")==null,"16chars may exceed AES key/IV byte size; no UTF8 truncation repair");f.Services.ReportCryptoError=(c,m)=>throw new InvalidOperationException();Throws<InvalidOperationException>(()=>cipher.Decrypt("bad","abc"));});
            check("encrypted-envelope-shared-and-server-time-bypass",()=>{var f=new Fixture();f.Encrypt=true;f.Transmitter.SetUrl("unused");f.Transmitter.SendRankDataRequest("u","n","a",2,3,1,9);var envelope=LitJson.JsonMapper.ToObject<OutgameHttpEncryptedData>(f.Requests[0].Json);var cipher=new OutgameHttpCipher(f.Services);var data=LitJson.JsonMapper.ToObject<OutgameSendRankRequest>(cipher.Decrypt(envelope.encrypt,"abc"));Need(data.score==40&&f.Requests[0].Data==f.Transmitter.EncryptedRequest,"actual encryption envelope");f.Transmitter.AddHttpProtocol(2,"server-time",null);var raw=new OutgameGetRankRequest();f.Transmitter.Send(2,raw);Need(f.Requests[1].Data==raw,"protocol2 bypasses encryption");f.Transmitter.EncryptData(null);Need(f.Transmitter.EncryptedRequest.encrypt=="","null data encodes empty string without cipher");});
            check("encrypted-response-and-plain-fallback",()=>{var f=new Fixture();f.Encrypt=true;f.Transmitter.SetUrl("unused");int calls=0;f.Transmitter.SendResponseCallback=()=>calls++;f.Transmitter.SendRankDataRequest("u","n","a",1,1,1,1);var cipher=new OutgameHttpCipher(f.Services);f.Success(0,LitJson.JsonMapper.ToJson(new OutgameHttpEncryptedData{encrypt=cipher.Encrypt("{\"code\":0}","abc")}));Need(calls==1,"real cipher response parsed before callback");f.Success(0,"{\"code\":0}");Need(calls==2&&f.CryptoErrors.Contains(1007),"null encrypted field falls back to unchanged plaintext");});
            check("real-match-first-response-and-independent-account-restart",()=>{string path;using(var top=new OutgameTopInfoPageValidation.Fixture()){var match=OutgameMatchValidation.AttachTopInfo(top);var f=new Fixture();match.Transmitter=f.Transmitter;match.OnGamePlayerState(new object[]{8});Need(f.Requests.Select(x=>LitJson.JsonMapper.ToObject<OutgameSendRankRequest>(x.Json).category).SequenceEqual(new[]{2,3,1})&&match.Manager.Data.rankData.VN_t==5,"actual Match emits three structured requests before response");f.Success(1,"{\"code\":7,\"msg\":\"business-error\"}");Need(match.Manager.Data.rankData.VN_t==6&&f.Transmitter.SendResponseCallback==null,"source business error response still runs current Match win callback");f.Success(0,"{\"code\":0}");Need(match.Manager.Data.rankData.VN_t==6&&top.Account.Stored("MatchManager")=="","later reply sees cleared callback; no implicit save");match.Manager.OnSave();path=top.Account.PathName;}using(var top=new OutgameTopInfoPageValidation.Fixture(path:path)){var reopened=OutgameMatchValidation.AttachTopInfo(top);Need(reopened.Manager.Data.rankData.VN_t==6,"actual independent account restart");}});
            return report;
        }
    }
}
