// Generated by analysis/generate_original_config_schemas.py from original metadata.
using System;
using System.Collections.Generic;
namespace AreaBattle.OriginalConfig
{
    // Original type 3452
    [Serializable] public sealed class ListArrayInt
    {
        public int[] @datas;
    }
    // Original type 3490
    [Serializable] public sealed class Lang
    {
        public string @key;
    }
    // Original type 3909
    [Serializable] public sealed class AgentGradeConfig : IOutgameConfigRow
    {
        public int @id;
        public string @AgentPath;
        public string @AgentName;
        public int @SkillUseId;
        public double @ActionRate;
        public object UniqueID => @id;
    }
    // Original type 3910
    [Serializable] public sealed class AgentSkillUseConfig : IOutgameConfigRow
    {
        public int @id;
        public int @total;
        public double @DelayTime;
        public int @rate_skill1;
        public double @space_skill1;
        public int @rate_skill2;
        public double @space_skill2;
        public int @rate_skill3;
        public double @space_skill3;
        public object UniqueID => @id;
    }
    // Original type 3911
    [Serializable] public sealed class AIConfig : IOutgameConfigRow
    {
        public int @id;
        public int @AIType;
        public int @DelayTime;
        public int[] @ActionTime;
        public int @ActionNum;
        public int[] @Protect;
        public int[] @Defend;
        public int[] @Reinforce;
        public int[] @Occupy;
        public object UniqueID => @id;
    }
    // Original type 3912
    [Serializable] public sealed class AILevelFactorConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3913
    [Serializable] public sealed class AINameConfig : IOutgameConfigRow
    {
        public int @id;
        public string @zh_cn;
        public object UniqueID => @id;
    }
    // Original type 3914
    [Serializable] public sealed class AIReplayFactorConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3915
    [Serializable] public sealed class AllSkillBConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3916
    [Serializable] public sealed class AllSkillConfig : IOutgameConfigRow
    {
        public int @id;
        public int @gameItem;
        public int @unLockLevel;
        public int @castType;
        public int @price;
        public int @diamondPrice;
        public int @useType;
        public int @targetType;
        public int[] @dataType;
        public int[] @describeData;
        public object UniqueID => @id;
    }
    // Original type 3917
    [Serializable] public sealed class ArenaConfig
    {
        public int @unlockLevel;
        public int @seasonDurationDay;
        public int @refreshTime;
        public int[] @aiCupRange;
        public List<ListArrayInt> @combatReward;
        public int @playinitCup;
        public int @aiBaseNum;
        public int @initialCupLowerLimit;
        public int[] @motivatVideoReward;
        public int @freeChallengeCount;
        public int @challengeCD;
        public int[] @skipChallengerCD;
        public int @AdAddChallengeCount;
        public List<ListArrayInt> @buyChallengeCast;
    }
    // Original type 3918
    [Serializable] public sealed class ArenaCupRangeConfig : IOutgameConfigRow
    {
        public int @id;
        public int[] @rankRange;
        public int[] @growCup;
        public int[] @reduceCup;
        public int[] @mapId;
        public object UniqueID => @id;
    }
    // Original type 3919
    [Serializable] public sealed class ArenaDailyRewardConfig : IOutgameConfigRow
    {
        public int @id;
        public int[] @rankRange;
        public int[] @itemId;
        public int[] @itemCount;
        public object UniqueID => @id;
    }
    // Original type 3920
    [Serializable] public sealed class ArenaInheritanceConfig : IOutgameConfigRow
    {
        public int @id;
        public int @basecup;
        public int @inheritancup;
        public string @sym;
        public object UniqueID => @id;
    }
    // Original type 3921
    [Serializable] public sealed class ArenaInitAiSocreConfig : IOutgameConfigRow
    {
        public int @id;
        public int[] @rankRnage;
        public int @maxCup;
        public int @minCup;
        public object UniqueID => @id;
    }
    // Original type 3922
    [Serializable] public sealed class ArenaSeasonRewardConfig : IOutgameConfigRow
    {
        public int @id;
        public int[] @rankRange;
        public int[] @itemId;
        public int[] @itemCount;
        public object UniqueID => @id;
    }
    // Original type 3923
    [Serializable] public sealed class BossConfig : IOutgameConfigRow
    {
        public int @id;
        public int @DelayTime;
        public int[] @ActionTime;
        public int[] @Skill1;
        public int[] @Skill2;
        public int @skill1_Hit;
        public double @skill1_duration;
        public double @skill1_first;
        public double @skill1_second;
        public int @skill2_Hit;
        public double @skill2_duration;
        public double @skill2_first;
        public double @skill2_second;
        public object UniqueID => @id;
    }
    // Original type 3924
    [Serializable] public sealed class CampConfig : IOutgameConfigRow
    {
        public int @id;
        public int @bossModelId;
        public int @bossSoldierId;
        public string @LineColor;
        public string @BasitionMaterial;
        public string @soldierColor0;
        public string @soldierColor1;
        public string @soldierColor2;
        public object UniqueID => @id;
    }
    // Original type 3925
    [Serializable] public sealed class ChannelConfig : IOutgameConfigRow
    {
        public int @id;
        public int @noAB;
        public int @channelA;
        public int @channelB;
        public int @channelC;
        public int @channelD;
        public int @channelE;
        public object UniqueID => @id;
    }
    // Original type 3926
    [Serializable] public sealed class ChannelProcedureConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3927
    [Serializable] public sealed class CommanderBConfig : IOutgameConfigRow
    {
        public int @id;
        public int @maxLevel;
        public List<ListArrayInt> @unlockPrice;
        public object UniqueID => @id;
    }
    // Original type 3928
    [Serializable] public sealed class CommanderConfig : IOutgameConfigRow
    {
        public int @id;
        public string @name;
        public int @maxLevel;
        public int @unlockType;
        public string @describe;
        public int @unlockLevel;
        public List<ListArrayInt> @unlockPrice;
        public int[] @skills;
        public int @EntityId;
        public string @IconName;
        public int @usePercent;
        public string @headport;
        public object UniqueID => @id;
    }
    // Original type 3929
    [Serializable] public sealed class CommanderUpgradeBConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3930
    [Serializable] public sealed class CommanderUpgradeConfig : IOutgameConfigRow
    {
        public int @id;
        public int @upgradeCost;
        public object UniqueID => @id;
    }
    // Original type 3931
    [Serializable] public sealed class CountryConfigConfig : IOutgameConfigRow
    {
        public int @id;
        public int @LangKey;
        public string @countryFlagName;
        public string[] @countryCode;
        public object UniqueID => @id;
    }
    // Original type 3932
    [Serializable] public sealed class DailyChallengeConfig : IOutgameConfigRow
    {
        public int @id;
        public int[] @awardId;
        public int[] @awardCount;
        public object UniqueID => @id;
    }
    // Original type 3933
    [Serializable] public sealed class DiceGameConfig : IOutgameConfigRow
    {
        public int @id;
        public string @pos;
        public int @siblingIndex;
        public int @type;
        public List<ListArrayInt> @rewards;
        public object UniqueID => @id;
    }
    // Original type 3934
    [Serializable] public sealed class DicePointConfig : IOutgameConfigRow
    {
        public int @id;
        public int @weight;
        public object UniqueID => @id;
    }
    // Original type 3935
    [Serializable] public sealed class DiceShopConfig : IOutgameConfigRow
    {
        public int @id;
        public int @storeType;
        public string @price;
        public int @buyLimit;
        public int @buyLimitParam;
        public int @weight;
        public object UniqueID => @id;
    }
    // Original type 3936
    [Serializable] public sealed class DiceShopTypeConfig : IOutgameConfigRow
    {
        public int @shopId;
        public int @refreshPeriod;
        public int[] @refreshParams;
        public int @capacity;
        public object UniqueID => @shopId;
    }
    // Original type 3937
    [Serializable] public sealed class DispatchConfig : IOutgameConfigRow
    {
        public int @id;
        public int @scoreLimit;
        public int @maxLine;
        public int @addSpace;
        public int @swanpSpaceOne;
        public int @swanpSpaceTwo;
        public int @swanpSpaceThree;
        public object UniqueID => @id;
    }
    // Original type 3938
    [Serializable] public sealed class DrawConfig : IOutgameConfigRow
    {
        public int @id;
        public int @item;
        public int @num;
        public int @weight;
        public string @prob;
        public object UniqueID => @id;
    }
    // Original type 3939
    [Serializable] public sealed class EntityModelConfig : IOutgameConfigRow
    {
        public int @id;
        public string @AssetName;
        public int @PathEnum;
        public object UniqueID => @id;
    }
    // Original type 3940
    [Serializable] public sealed class FirstChargeConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3941
    [Serializable] public sealed class FuncSettingConfig
    {
        public int @BossLevel;
        public bool @HeroSetting;
        public int @HeroPreUnlockLevel;
        public bool @useNewUIMask;
        public int @ValentineSetting;
        public int @SummerSetting;
        public int @dontShowInsertAfterSeeToolVideo;
        public int @dontShowInsertIfSeeOverVideo;
        public int @ShowInsertADPerXLevel;
    }
    // Original type 3942
    [Serializable] public sealed class GameItemConfig : IOutgameConfigRow
    {
        public int @id;
        public int @type1;
        public int @type2;
        public string @icon;
        public string @atlasName;
        public string @ItemIcon;
        public Lang @name;
        public Lang @detail;
        public int @paramInt;
        public object UniqueID => @id;
    }
    // Original type 3943
    [Serializable] public sealed class GameProductConfig : IOutgameConfigRow
    {
        public int @id;
        public int @isActive;
        public int @storeType;
        public int @NoAds;
        public string @icon;
        public List<ListArrayInt> @itemConfig;
        public int @getType;
        public string @price;
        public Lang @priceText;
        public object UniqueID => @id;
    }
    // Original type 3944
    [Serializable] public sealed class GlobalValueConfig : IOutgameConfigRow
    {
        public int @id;
        public string @Content1;
        public object UniqueID => @id;
    }
    // Original type 3945
    [Serializable] public sealed class GuideBConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3946
    [Serializable] public sealed class GuidebookConfig : IOutgameConfigRow
    {
        public int @id;
        public Lang @name;
        public int @guideId;
        public int[] @reward;
        public object UniqueID => @id;
    }
    // Original type 3947
    [Serializable] public sealed class GuideConfig : IOutgameConfigRow
    {
        public int @id;
        public int @guildLv;
        public int @guildsmallLv;
        public int @nextGuildStage;
        public string @title;
        public string @explain;
        public string @button;
        public string @picture;
        public string @param;
        public object UniqueID => @id;
    }
    // Original type 3948
    [Serializable] public sealed class GuideDConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3949
    [Serializable] public sealed class GuideTipsConfig : IOutgameConfigRow
    {
        public int @id;
        public Lang @name;
        public Lang @des;
        public int @unlockLevel;
        public int[] @reward;
        public object UniqueID => @id;
    }
    // Original type 3950
    [Serializable] public sealed class HeadBoxConfig : IOutgameConfigRow
    {
        public int @id;
        public string @icon;
        public string @lockIcon;
        public string @atlas;
        public Lang @des;
        public int @weight;
        public object UniqueID => @id;
    }
    // Original type 3951
    [Serializable] public sealed class HeadportConfig : IOutgameConfigRow
    {
        public int @id;
        public string @icon;
        public string @atlas;
        public Lang @des;
        public object UniqueID => @id;
    }
    // Original type 3952
    [Serializable] public sealed class LargeNumConfig : IOutgameConfigRow
    {
        public int @mag;
        public string @magName;
        public object UniqueID => @mag;
    }
    // Original type 3953
    [Serializable] public sealed class LevelBConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3954
    [Serializable] public sealed class LevelConfig : IOutgameConfigRow
    {
        public int @id;
        public int[] @LevelType;
        public int @SceneId;
        public object UniqueID => @id;
    }
    // Original type 3955
    [Serializable] public sealed class LimitedProductConfig : IOutgameConfigRow
    {
        public int @id;
        public int @productId;
        public bool @isActive;
        public int @limitedTime;
        public int @levelId;
        public object UniqueID => @id;
    }
    // Original type 3956
    [Serializable] public sealed class MatchLevelConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3957
    [Serializable] public sealed class MenuTabConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3958
    [Serializable] public sealed class NewRankSettingConfig
    {
        public int @intPlayerRank;
        public int @HM_RankShowNum;
        public int @HM_UpPlayerNum;
        public int @HM_LowPlayerNum;
        public int[] @HM_RankGapRag;
        public int[] @GM_RankGapRe;
        public int @playerItemScaleT;
        public int @playerItemscaleV;
        public int @playerItemLargeScaleT;
        public int @playerItemSmallScaleT;
        public int @playerItemLargeScaleN;
    }
    // Original type 3959
    [Serializable] public sealed class RaceConfig
    {
        public int[] @raceActReward;
        public int[] @raceActAiSpeed;
        public int[] @raceActTargetLVRange;
    }
    // Original type 3960
    [Serializable] public sealed class RankRewardConfig : IOutgameConfigRow
    {
        public int @ID;
        public int @type;
        public int @rank;
        public List<ListArrayInt> @reward;
        public object UniqueID => @ID;
    }
    // Original type 3961
    [Serializable] public sealed class RankSubConfig : IOutgameConfigRow
    {
        public int @id;
        public int @areaValue;
        public int[] @randValue;
        public object UniqueID => @id;
    }
    // Original type 3962
    [Serializable] public sealed class SceneEffectConfig : IOutgameConfigRow
    {
        public int @sceneId;
        public string @idleEffect;
        public string @gameEffect;
        public object UniqueID => @sceneId;
    }
    // Original type 3963
    [Serializable] public sealed class SceneSkinConfig : IOutgameConfigRow
    {
        public int @id;
        public int @skinType;
        public string @iconName;
        public string @idleIconName;
        public string @gameIconName;
        public int @castType;
        public int @price;
        public int @DiamondPrice;
        public int @lockState;
        public int @sortNo;
        public int @actNo;
        public int @special;
        public string @tag;
        public string @describe;
        public object UniqueID => @id;
    }
    // Original type 3964
    [Serializable] public sealed class SettingConfig
    {
        public int @showInterst_finishLevel;
        public int @showInterst_nofinishLevel;
        public int @levelNo_showEvaluate;
        public int @levelNo_showInterst;
        public int @levelNo_showReplayInterst;
        public int @levelNo_showBanner;
        public float[] @arrowTowerAttackRate;
        public float[] @arrowTowerAttackRegion;
        public float @arrowTowerRegionBaseScale;
        public int @storeAdDiamondCount;
        public int @storeAdGoldCount;
        public int[] @storeAdSendDiamond;
        public int @accelerationDiamondCount;
        public int @towerUnlock;
        public int @diceunlock;
        public int @buyDiceTimes_mainlevel;
        public int @buyDiceTimes_AD;
        public int @buyDiceTimes_gole;
        public List<ListArrayInt> @buyDiceCost;
    }
    // Original type 3965
    [Serializable] public sealed class SkillConfig : IOutgameConfigRow
    {
        public int @id;
        public double @duration;
        public double @data1;
        public double @data2;
        public double @data3;
        public object UniqueID => @id;
    }
    // Original type 3966
    [Serializable] public sealed class SkinConfig : IOutgameConfigRow
    {
        public int @id;
        public int @skinType;
        public string @iconName;
        public int @prefabId;
        public int @castType;
        public int @price;
        public int @DiamondPrice;
        public int @lockState;
        public int @sortNo;
        public int @actNo;
        public int @special;
        public string @tag;
        public string @describe;
        public object UniqueID => @id;
    }
    // Original type 3967
    [Serializable] public sealed class SoldierConfig : IOutgameConfigRow
    {
        public int @id;
        public int @EntityID;
        public int @shipType;
        public int @hp;
        public int @attack;
        public int @occupy;
        public int @reinforce;
        public int @voyage;
        public object UniqueID => @id;
    }
    // Original type 3968
    [Serializable] public sealed class SpecialLevelConfig : IOutgameConfigRow
    {
        public int @id;
        public int @SceneId;
        public object UniqueID => @id;
    }
    // Original type 3969
    [Serializable] public sealed class StatisticEventConfig
    {
        public int @BuySkin;
        public int @BuyScene;
        public int @DailyCommUpgrade;
        public int @DailyRaceGetLv;
        public int @DailyCompleteLv;
        public int @DailyWatchAds;
        public int @DailyUseProp;
        public int @DailyArenaWin;
        public int @ArenaCombatCount;
        public int @SelectCard;
        public int @RaceGetLv;
        public int @UseProp;
        public int @HaveSkinNum;
        public int @HaveSceneNum;
        public int @HczzqUnlocakSoldier1;
        public int @HczzqUnlocakSoldier2;
        public int @CommanderUpgrade;
        public int @ArenaWin;
        public int @ArenaRank;
        public int @CommanderUpgradeTotal;
        public int @UseCoinTotal;
    }
    // Original type 3970
    [Serializable] public sealed class SummerRewardConfig : IOutgameConfigRow
    {
        public int @id;
        public int[] @itemId;
        public int[] @itemCount;
        public int[] @giftWay;
        public object UniqueID => @id;
    }
    // Original type 3971
    [Serializable] public sealed class UIMonitorConfigConfig : IOutgameConfigRow
    {
        public int @id;
        public object UniqueID => @id;
    }
    // Original type 3972
    [Serializable] public sealed class WXAMSConfig : IOutgameConfigRow
    {
        public int @Id;
        public int @PlacementId;
        public string @ReportLable;
        public object UniqueID => @Id;
    }
}
