// Generated from CONFIG_INITIALIZATION_ROSTER.json and source ConfigMgr30413.
using System.Collections.Generic;
using AreaBattle.OriginalConfig;
namespace AreaBattle
{
    public sealed partial class OutgameLegacyConfigManager
    {
        public readonly Dictionary<object,OriginalConfig.ChannelConfig> dicChannel=new Dictionary<object,OriginalConfig.ChannelConfig>();
        public readonly Dictionary<object,OriginalConfig.ChannelProcedureConfig> dicChannelProcedure=new Dictionary<object,OriginalConfig.ChannelProcedureConfig>();
        public readonly Dictionary<object,OriginalConfig.AINameConfig> dicAIName=new Dictionary<object,OriginalConfig.AINameConfig>();
        public readonly Dictionary<object,OriginalConfig.AIConfig> dicAI=new Dictionary<object,OriginalConfig.AIConfig>();
        public readonly Dictionary<object,OriginalConfig.DispatchConfig> dicDispatch=new Dictionary<object,OriginalConfig.DispatchConfig>();
        public readonly Dictionary<object,OriginalConfig.AIReplayFactorConfig> dicAIReplayFactor=new Dictionary<object,OriginalConfig.AIReplayFactorConfig>();
        public readonly Dictionary<object,OriginalConfig.AILevelFactorConfig> dicAILevelFactor=new Dictionary<object,OriginalConfig.AILevelFactorConfig>();
        public readonly Dictionary<object,OriginalConfig.AgentSkillUseConfig> dicAgentSkillUse=new Dictionary<object,OriginalConfig.AgentSkillUseConfig>();
        public readonly Dictionary<object,OriginalConfig.AgentGradeConfig> dicAgentGrade=new Dictionary<object,OriginalConfig.AgentGradeConfig>();
        public readonly Dictionary<object,OriginalConfig.BossConfig> dicBoss=new Dictionary<object,OriginalConfig.BossConfig>();
        public readonly Dictionary<object,OriginalConfig.SummerRewardConfig> dicSummerReward=new Dictionary<object,OriginalConfig.SummerRewardConfig>();
        public readonly Dictionary<object,OriginalConfig.DailyChallengeConfig> dicDailyChallenge=new Dictionary<object,OriginalConfig.DailyChallengeConfig>();
        public readonly Dictionary<object,OriginalConfig.FirstChargeConfig> dicFirstCharge=new Dictionary<object,OriginalConfig.FirstChargeConfig>();
        public readonly Dictionary<object,OriginalConfig.ArenaDailyRewardConfig> dicArenaDailyReward=new Dictionary<object,OriginalConfig.ArenaDailyRewardConfig>();
        public readonly Dictionary<object,OriginalConfig.ArenaSeasonRewardConfig> dicArenaSeasonReward=new Dictionary<object,OriginalConfig.ArenaSeasonRewardConfig>();
        public readonly Dictionary<object,OriginalConfig.ArenaInitAiSocreConfig> dicArenaInitAiSocre=new Dictionary<object,OriginalConfig.ArenaInitAiSocreConfig>();
        public readonly Dictionary<object,OriginalConfig.ArenaCupRangeConfig> dicArenaCupRange=new Dictionary<object,OriginalConfig.ArenaCupRangeConfig>();
        public readonly Dictionary<object,OriginalConfig.ArenaInheritanceConfig> dicArenaInheritance=new Dictionary<object,OriginalConfig.ArenaInheritanceConfig>();
        public readonly Dictionary<object,OriginalConfig.GameItemConfig> dicGameItem=new Dictionary<object,OriginalConfig.GameItemConfig>();
        public readonly Dictionary<object,OriginalConfig.GameProductConfig> dicGameProduct=new Dictionary<object,OriginalConfig.GameProductConfig>();
        public readonly Dictionary<object,OriginalConfig.LimitedProductConfig> dicLimitedProduct=new Dictionary<object,OriginalConfig.LimitedProductConfig>();
        public readonly Dictionary<object,OriginalConfig.MatchLevelConfig> dicMatchLevel=new Dictionary<object,OriginalConfig.MatchLevelConfig>();
        public readonly Dictionary<object,OriginalConfig.HeadportConfig> dicHeadport=new Dictionary<object,OriginalConfig.HeadportConfig>();
        public readonly Dictionary<object,OriginalConfig.HeadBoxConfig> dicHeadBox=new Dictionary<object,OriginalConfig.HeadBoxConfig>();
        public readonly Dictionary<object,OriginalConfig.WXAMSConfig> dicWXAMS=new Dictionary<object,OriginalConfig.WXAMSConfig>();
        public readonly Dictionary<object,OriginalConfig.MenuTabConfig> dicMenuTab=new Dictionary<object,OriginalConfig.MenuTabConfig>();
        public readonly Dictionary<object,OriginalConfig.GlobalValueConfig> dicGlobalValue=new Dictionary<object,OriginalConfig.GlobalValueConfig>();
        public readonly Dictionary<object,OriginalConfig.LevelConfig> dicLevel=new Dictionary<object,OriginalConfig.LevelConfig>();
        public readonly Dictionary<object,OriginalConfig.LevelBConfig> dicLevelB=new Dictionary<object,OriginalConfig.LevelBConfig>();
        public readonly Dictionary<object,OriginalConfig.SpecialLevelConfig> dicSpecialLevel=new Dictionary<object,OriginalConfig.SpecialLevelConfig>();
        public readonly Dictionary<object,OriginalConfig.DiceGameConfig> dicDiceGame=new Dictionary<object,OriginalConfig.DiceGameConfig>();
        public readonly Dictionary<object,OriginalConfig.DicePointConfig> dicDicePoint=new Dictionary<object,OriginalConfig.DicePointConfig>();
        public readonly Dictionary<object,OriginalConfig.DiceShopConfig> dicDiceShop=new Dictionary<object,OriginalConfig.DiceShopConfig>();
        public readonly Dictionary<object,OriginalConfig.DiceShopTypeConfig> dicDiceShopType=new Dictionary<object,OriginalConfig.DiceShopTypeConfig>();
        public readonly Dictionary<object,OriginalConfig.CountryConfigConfig> dicCountryConfig=new Dictionary<object,OriginalConfig.CountryConfigConfig>();
        public readonly Dictionary<object,OriginalConfig.SoldierConfig> dicSoldier=new Dictionary<object,OriginalConfig.SoldierConfig>();
        public readonly Dictionary<object,OriginalConfig.GuideConfig> dicGuide=new Dictionary<object,OriginalConfig.GuideConfig>();
        public readonly Dictionary<object,OriginalConfig.GuideBConfig> dicGuideB=new Dictionary<object,OriginalConfig.GuideBConfig>();
        public readonly Dictionary<object,OriginalConfig.GuideDConfig> dicGuideD=new Dictionary<object,OriginalConfig.GuideDConfig>();
        public readonly Dictionary<object,OriginalConfig.GuidebookConfig> dicGuidebook=new Dictionary<object,OriginalConfig.GuidebookConfig>();
        public readonly Dictionary<object,OriginalConfig.GuideTipsConfig> dicGuideTips=new Dictionary<object,OriginalConfig.GuideTipsConfig>();
        public readonly Dictionary<object,OriginalConfig.EntityModelConfig> dicEntityModel=new Dictionary<object,OriginalConfig.EntityModelConfig>();
        public readonly Dictionary<object,OriginalConfig.DrawConfig> dicDraw=new Dictionary<object,OriginalConfig.DrawConfig>();
        public readonly Dictionary<object,OriginalConfig.AllSkillConfig> dicAllSkill=new Dictionary<object,OriginalConfig.AllSkillConfig>();
        public readonly Dictionary<object,OriginalConfig.AllSkillBConfig> dicAllSkillB=new Dictionary<object,OriginalConfig.AllSkillBConfig>();
        public readonly Dictionary<object,OriginalConfig.SkillConfig> dicSkill=new Dictionary<object,OriginalConfig.SkillConfig>();
        public readonly Dictionary<object,OriginalConfig.CommanderConfig> dicCommander=new Dictionary<object,OriginalConfig.CommanderConfig>();
        public readonly Dictionary<object,OriginalConfig.CommanderBConfig> dicCommanderB=new Dictionary<object,OriginalConfig.CommanderBConfig>();
        public readonly Dictionary<object,OriginalConfig.CommanderUpgradeConfig> dicCommanderUpgrade=new Dictionary<object,OriginalConfig.CommanderUpgradeConfig>();
        public readonly Dictionary<object,OriginalConfig.CommanderUpgradeBConfig> dicCommanderUpgradeB=new Dictionary<object,OriginalConfig.CommanderUpgradeBConfig>();
        public readonly Dictionary<object,OriginalConfig.RankSubConfig> dicRankSub=new Dictionary<object,OriginalConfig.RankSubConfig>();
        public readonly Dictionary<object,OriginalConfig.RankRewardConfig> dicRankReward=new Dictionary<object,OriginalConfig.RankRewardConfig>();
        public readonly Dictionary<object,OriginalConfig.UIMonitorConfigConfig> dicUIMonitorConfig=new Dictionary<object,OriginalConfig.UIMonitorConfigConfig>();
        public readonly Dictionary<object,OriginalConfig.LargeNumConfig> dicLargeNum=new Dictionary<object,OriginalConfig.LargeNumConfig>();
        public readonly Dictionary<object,OriginalConfig.SceneEffectConfig> dicSceneEffect=new Dictionary<object,OriginalConfig.SceneEffectConfig>();
        public readonly Dictionary<object,OriginalConfig.SceneSkinConfig> dicSceneSkin=new Dictionary<object,OriginalConfig.SceneSkinConfig>();
        public readonly Dictionary<object,OriginalConfig.SkinConfig> dicSkin=new Dictionary<object,OriginalConfig.SkinConfig>();
        public readonly Dictionary<object,OriginalConfig.CampConfig> dicCamp=new Dictionary<object,OriginalConfig.CampConfig>();
        public OriginalConfig.RaceConfig raceConfig;
        public OriginalConfig.ArenaConfig arenaConfig;
        public OriginalConfig.FuncSettingConfig funcSettingConfig;
        public OriginalConfig.SettingConfig settingConfig;
        public OriginalConfig.StatisticEventConfig statisticEventConfig;
        public OriginalConfig.NewRankSettingConfig newRankSettingConfig;
        void ReadOriginalConfigs()
        {
            reader.ReadTable(dicChannel);
            reader.ReadTable(dicChannelProcedure);
            reader.ReadTable(dicAIName);
            reader.ReadTable(dicAI);
            reader.ReadTable(dicDispatch);
            reader.ReadTable(dicAIReplayFactor);
            reader.ReadTable(dicAILevelFactor);
            reader.ReadTable(dicAgentSkillUse);
            reader.ReadTable(dicAgentGrade);
            reader.ReadTable(dicBoss);
            reader.ReadTable(dicSummerReward);
            reader.ReadTable(dicDailyChallenge);
            reader.ReadTable(dicFirstCharge);
            reader.ReadTable(dicArenaDailyReward);
            reader.ReadTable(dicArenaSeasonReward);
            reader.ReadTable(dicArenaInitAiSocre);
            reader.ReadTable(dicArenaCupRange);
            reader.ReadTable(dicArenaInheritance);
            reader.ReadTable(dicGameItem);
            reader.ReadTable(dicGameProduct);
            reader.ReadTable(dicLimitedProduct);
            reader.ReadTable(dicMatchLevel);
            reader.ReadTable(dicHeadport);
            reader.ReadTable(dicHeadBox);
            reader.ReadTable(dicWXAMS);
            reader.ReadTable(dicMenuTab);
            reader.ReadTable(dicGlobalValue);
            reader.ReadTable(dicLevel);
            reader.ReadTable(dicLevelB);
            reader.ReadTable(dicSpecialLevel);
            reader.ReadTable(dicDiceGame);
            reader.ReadTable(dicDicePoint);
            reader.ReadTable(dicDiceShop);
            reader.ReadTable(dicDiceShopType);
            reader.ReadTable(dicCountryConfig);
            reader.ReadTable(dicSoldier);
            reader.ReadTable(dicGuide);
            reader.ReadTable(dicGuideB);
            reader.ReadTable(dicGuideD);
            reader.ReadTable(dicGuidebook);
            reader.ReadTable(dicGuideTips);
            reader.ReadTable(dicEntityModel);
            reader.ReadTable(dicDraw);
            reader.ReadTable(dicAllSkill);
            reader.ReadTable(dicAllSkillB);
            reader.ReadTable(dicSkill);
            reader.ReadTable(dicCommander);
            reader.ReadTable(dicCommanderB);
            reader.ReadTable(dicCommanderUpgrade);
            reader.ReadTable(dicCommanderUpgradeB);
            reader.ReadTable(dicRankSub);
            reader.ReadTable(dicRankReward);
            reader.ReadTable(dicUIMonitorConfig);
            reader.ReadTable(dicLargeNum);
            reader.ReadTable(dicSceneEffect);
            reader.ReadTable(dicSceneSkin);
            reader.ReadTable(dicSkin);
            reader.ReadTable(dicCamp);
            raceConfig=reader.ReadValue<OriginalConfig.RaceConfig>();
            arenaConfig=reader.ReadValue<OriginalConfig.ArenaConfig>();
            funcSettingConfig=reader.ReadValue<OriginalConfig.FuncSettingConfig>();
            settingConfig=reader.ReadValue<OriginalConfig.SettingConfig>();
            statisticEventConfig=reader.ReadValue<OriginalConfig.StatisticEventConfig>();
            newRankSettingConfig=reader.ReadValue<OriginalConfig.NewRankSettingConfig>();
        }
    }
}
