"""Freeze local skill visual import evidence; does not grant an orchestration acceptance tier."""
import json,hashlib
from pathlib import Path
W=Path(__file__).resolve().parent.parent;R=W/'analysis/targets/wxcf1394487200e48f/43';S=R/'generated/resource-snapshots/skill-effects-20260928'
read=lambda p:json.loads(p.read_text(encoding='utf8'))
files=[W/'analysis/unity-skill-effect-import-report.json',W/'analysis/unity-embedded-effect-import-report.json',S/'particle-roundtrip-validation.json',S/'embedded-particle-roundtrip-validation.json',S/'embedded-particle-migration-evidence.json',W/'analysis/skill-effect-render-probe.json']
main,embedded,ps,embedded_ps,migration,probe=map(read,files)
assert main['passed'] and embedded['passed'] and ps['passed'] and migration['activeParticleValuesEqual']
material_samples=[m for s in probe['snapshots'] for d in s['draws'] for m in d['materials']]
assert all(m['supported'] and not m['error'] and m['shader']!='Hidden/InternalErrorShader' for m in material_samples)
out={'target':{'appId':'wxcf1394487200e48f','version':'43'},'prefabs':main['prefabCount']+embedded['prefabCount'],'mainParticleRoundtrip':{'count':ps['particleSystems'],'numericValues':ps['numericScalars'],'differences':0},'embeddedParticleRoundtrip':{'count':embedded_ps['particleSystems'],'numericValues':embedded_ps['numericScalars'],'strictEqual':False,'inactiveCurveNormalizations':migration['normalizedInactiveCurveArrays'],'evidence':'embedded-particle-migration-evidence.json'},'editablePackedAnimation':{'controllers':3,'clips':4,'curves':embedded['packedCurves'],'nativeSamplesCompared':embedded['curveSamples']},'renderProbe':{'skills':[2,9,10,18],'times':[.2,1.2],'materialSamples':len(material_samples),'unsupportedOrShaderError':0,'screenshots':[str((W/f'analysis/captures/probe-skill{skill}-{stage}.png').relative_to(W)).replace('\\','/') for skill in (2,9,10,18) for stage in (0,1)]},'sourceBindingCorrection':{'claim':'SkillBase.GetSkillParent returns a SkillItem UIObject Transform. UIObject.initGameObject writes GameObject.get_transform to offset16. SkillItem ancestor local scales are1 and source Canvas height1920/UICamera ortho6.4 produces lossyScale~0.006666667. The runtime now parents exact source skills2/9/10/18 to this UI Transform, retains world positions and original layer0. Original scales are unchanged.','source':['generated/combat-disassembly/SkillBase-100665079.txt','generated/ui-lifecycle-evidence.json','generated/presentation-prepared/hud-import.json'],'correctionEffect':'Native poison bottle scale150 becomes worldScale1; root-parent omission previously inflated it150x. Replayed skill18 giant triangles and skill10 black fan geometry disappeared after parent fix.'},'limitations':['No original-game dynamic capture for pixel comparison; internal render replay does not prove source visual equivalence.','Unity6 generates requested texture mipmaps from retained source base-level PNG; original GPU compressed mip bytes remain in source bundles.','Six original constant-mode startDelay fields have dormant empty min/max curves initialized by Unity6 to two keys; strict structural report retains these12 differences.','The original ice disappearance clip clears six PS.looping values and the original reactivation only SetActive/SetInteger(0) does not reset them; production preserves this native behavior.'],'artifacts':[{'path':p.relative_to(W).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files]}
clock=W/'analysis/embedded-effect-clock-probe.json'
assert read(clock)['passed']
out['embeddedProductionClock']={'passed':True,'evidence':clock.relative_to(W).as_posix(),'cases':'inactive attach, activate/grow .5s, melt2s, pause0, deactivate/reactivate; automatic Animator disabled and explicit Update drives all three controllers'}
out['artifacts'].append({'path':clock.relative_to(W).as_posix(),'sha256':hashlib.sha256(clock.read_bytes()).hexdigest()})
(S/'presentation-validation-summary.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf8');print('Saved summary: 24 source prefabs, 116 particle systems; no visual-baseline acceptance claimed.')
