"""Join confirmed static rules with implementation/test evidence; preserve unresolved gaps."""
import json,hashlib
from pathlib import Path
WORK=Path(__file__).resolve().parent.parent
ROOT=WORK/'analysis/targets/wxcf1394487200e48f/43'
OUT=ROOT/'generated'
coverage=json.loads((OUT/'combat-skill-coverage.json').read_text(encoding='utf8'))
testfile=WORK/'analysis/unity-skill-validation.json'
validation=json.loads(testfile.read_text(encoding='utf8')) if testfile.exists() else None
gaps=[
 {'id':'skill-ui-origin','status':'implemented-static-confirmed','skills':[2,7],'impact':'Original item1/item0 launch origin is UI WorldToScreenPoint then z=5 then BattleCamera.ScreenToWorldPoint. Root View supplies recovered three-slot positions and resolution matching; original visual comparison remains pending.','next':'Compare original HUD and launch frames after recovered artwork binding.'},
 {'id':'bullet-control-point','status':'implemented-static-confirmed','skills':[2,7,9],'impact':'Original clamped quadratic Bezier, up-offset arc, zero-arc random side control point and skill2 endpoint/duration distinction are implemented. Skill9 uses independent Unity Random.value. Two production tests passed in unified116 validation.','next':'Compare recovered Bullet model orientation and frame timing against original runtime.'},
 {'id':'skill-async-frame-order','status':'unknown','skills':[2,7,9,10,12,14,15,17,18],'impact':'Scaled coroutine/projectile APIs are separate, but frame ordering relative to SkillBase expiration and special callbacks has not been compared against original runtime. Skill12/18 mechanical startup is now proven immediate on Execute; only their visual resource/continuation timing remains unverified.','next':'Match source registration/update order and capture boundary frames at skill expiration, pause/resume and result.'},
 {'id':'boss-rain-tower-order','status':'implemented-static-confirmed','skills':[],'impact':'Boss rain now updates in its original list_tower position after that tower base update. Regen and rain combine into one ChangeScore call. Boundary and combined-score cases passed.','next':'No further code change absent new evidence; original frame comparison remains part of runtime acceptance.'},
 {'id':'async-restart','status':'partially-implemented-static-confirmed','skills':[2,7,9,10,14,15,17,18],'impact':'Skill15 waits now survive Restart with remaining delay/count and original Tower reference; they stop on observed inactive/different-camp Tower and continue on active same-camp reuse. Other skill waits/projectiles retain the existing clear-on-Restart behavior pending their own lifecycle evidence.','next':'Observe original resource-loading/reuse timing during replay; do not infer other skills share skill15 cancellation behavior. See combat-evidence rules serial-wait-runner-owner and skill15-restart-conditional-survival.'},
 {'id':'towerbuff-source','status':'no-active-producer-found','skills':[],'impact':'Ordinary fresh Tower starts with empty buff dictionary, InitBuff and BuffControl callbacks/update are nop. Whole-module verified opcode xrefs found no parameter constructor/table/getter calls and no TowerBuff TypeInfo usage. No active producer is evidenced; reflection/inlined creation remains a bounded unknown.','next':'Treat fresh ordinary no-skill baseline as eligible with empty buffs; reopen if actual save/runtime shows a buff producer.'},
 {'id':'commander-pvp-auto-skill','status':'unknown','skills':list(range(1,19)),'impact':'CastSkill is a mechanics API. Original loadout selection, commander unlock/save state and enemy/PVP automatic cast scheduling are not supplied by this file.','next':'Flow agent traces current commander, CommanderConfig weighting, PVP configuration and runtime skill trigger consumers.'},
 {'id':'boss-config-reachability','status':'unknown','skills':[],'impact':'Boss998/999 are active Star config references. The23 CampInfo-only config references are not assumed enabled; special-mode mutation is still being audited.','next':'Complete SpecialLevel/PVP loading transforms without inventing dead configuration mechanics.'},
 {'id':'original-runtime-oracle','status':'unknown','skills':list(range(1,19)),'impact':'Unity cases are static-derived golden cases; they are not captured executions of these original skill functions.','next':'Observe representative original skill/boss actions and compare numerical and frame-level results.'}
]
files=[WORK/'UnityProject/Assets/AreaBattle/Scripts/BattleSkills.cs',WORK/'UnityProject/Assets/AreaBattle/Editor/SkillValidation.cs']
report={'target':coverage['target'],'implementationFiles':[str(p) for p in files],'sourceHashes':{str(p.relative_to(WORK)):hashlib.sha256(p.read_bytes()).hexdigest() for p in files},'skillBranches':[{'skillId':s['skillId'],'ruleId':s['ruleId'],'staticKernelStatus':'confirmed','implemented':True,'fullFidelityComplete':False,'representativeConfig':s['representativeConfig'],'remainingGapIds':[g['id'] for g in gaps if s['skillId'] in g['skills'] and g['status'] != 'implemented-static-confirmed']} for s in coverage['skills']],'boss':{'configIds':[998,999],'implementedActions':[1,2,5,6],'noNewActionAfterCancellation':[0,3,4,7,8,9,10],'scoreCapturePrevention':True,'resultPrecedence':'no player tower => Defeat; else all owned => Victory; else lastBoss trunc(score)<=0 => Victory','fullFidelityComplete':False},'clockContract':{'BeforeBattleTick':'Running only, after Level/towers and before WayLines; raw Unity scaled dt for player SkillBase.','TickEnemySkillTimers':'After PVP agent casts, before AI/Level; raw Unity scaled dt for enemy SkillBase.','TickBosses':'AI phase before Level; raw Unity scaled dt for BossActionEntity.','AfterBattleTick':'Running only; recruit movement uses dt*GameTimeScale*ShipTimeScale*0.5.','TickSkillCoroutines':'Call once per Unity frame with Time.deltaTime; WaitForSeconds model; timeScale0 on Pause freezes positive waits; Result does not automatically cancel.','TickSkillProjectiles':'Call once per Unity frame with Time.deltaTime; Bullet.Update / default scaled arrow tween. Skill7 and9 callbacks require Running; skill2/10/Boss volley callbacks do not.','TickBossTower':'Runs in original active tower list order after base regen/rain score delta, using dt*GameTimeScale.','unscaledSkillClock':'No blanket unscaled skill clock implemented; no SetUpdate(true) evidence established.','ordering':'Controller order is static-confirmed; relative async/projectile MonoBehaviour frame order remains unverified. Do not double-tick async APIs from both View and core.'},'tests':{'path':str(testfile),'passed':validation.get('passed') if validation else None,'caseCount':len(validation.get('checks',[])) if validation else 0,'kind':'static-derived production-logic tests, not original runtime oracle'},'gaps':gaps,'acceptance':'mechanics extension validated; complete in-level/visual acceptance remains open'}
report['representativeBaseline']={'layout':'generated/all-levels/level_5.json','scenario':'fresh ordinary layout5, default loadout0, no active skill casts, no PVP, no carried async work','mechanicsGate':'eligible; these two audited gaps do not block this bounded baseline','towerBuff':'empty dictionary with no active producer in audited ordinary initialization','skill15Restart':'unreachable without skill15 cast and pending serial wait; Commander default has no skill15','conditions':['Do not reuse a simulation/session with prior active skill15 jobs when claiming this baseline.','This eligibility does not prove visual equivalence or original runtime numeric acceptance.'],'newEvidence':['towerbuff-no-active-producer-found','serial-wait-runner-owner','skill15-restart-conditional-survival']}
(OUT/'skill-implementation-coverage.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8')
print(json.dumps({'implementedSkills':18,'skillTests':report['tests'],'gaps':len(gaps)}))
