"""Evidence-led combat rules: parse metadata and index static disassembly, never run target code."""
import json, struct, hashlib, sys
from pathlib import Path
from datetime import datetime, timezone
ROOT=Path(__file__).parent/'targets/wxcf1394487200e48f/43'
OUT=ROOT/'generated'
metadata=ROOT/'work/webdata/Il2CppData/Metadata/global-metadata.dat'
b=metadata.read_bytes()
pairs=[struct.unpack_from('<II',b,8+8*i) for i in range(21)]
def string(i):
 start=pairs[2][0]+i
 return b[start:b.index(0,start)].decode('utf8')
types=[struct.unpack_from('<16i8H2I',b,pairs[19][0]+i*88) for i in range(pairs[19][1]//88)]
defaults={x[0]:x for off in range(pairs[7][0],sum(pairs[7]),12) for x in [struct.unpack_from('<3i',b,off)]}
enums={}
for ti in [3908,4226,4232,4269]:
 t=types[ti];rows=[]
 for fi in range(t[8],t[8]+t[18]):
  f=struct.unpack_from('<3i',b,pairs[11][0]+fi*12)
  if fi not in defaults:continue
  dataoff=pairs[8][0]+defaults[fi][2];c=b[dataoff]
  # IL2CPP v31 compressed signed integer: all selected positive enum values fit one byte.
  assert c<128 and c%2==0
  rows.append({'name':string(f[0]),'value':c>>1,'fieldToken':f[2],'metadataOffset':dataoff,'bytes':bytes([c]).hex()})
 enums[string(t[0])]=rows
methods=json.loads((OUT/'gameplay-method-map.json').read_text(encoding='utf8'))['methods']+json.loads((OUT/'combat-extra-map.json').read_text(encoding='utf8'))['methods']
bytoken={x['token']:x for x in methods}
def ref(token, start=None, end=None):
 m=bytoken[token];path=OUT/f'combat-disassembly/{m["class"]}-{token}.txt'
 if not path.exists():path=OUT/f'disassembly/{m["class"]}-{m["method"]}.txt'
 lines=path.read_text(encoding='utf8').split('\n');first=3;last=len(lines)
 if start:
  first=next(i for i,x in enumerate(lines,1) if x.startswith(start))
 if end:
  last=next(i for i,x in enumerate(lines,1) if x.startswith(end))
 body=m['body'];return {'method':m['class']+'.'+m['method'],'token':token,'disassembly':path.relative_to(ROOT).as_posix(),'lines':[first,last],'wasm':f'generated/wasm/{m["module"]}.wasm','function':m['function'],'bodyOffset':body['offset'],'bodySize':body['size'],'instructionOffsetsHex':[start,end] if start else None}
rules=[]
def add(id,rule,evidence,status='confirmed',scope='ordinary towers and unmodified soldiers'):
 rules.append({'id':id,'status':status,'scope':scope,'rule':rule,'evidence':evidence})
add('soldier-stats','Soldier.Init(configID,campID,originTowerID): HP=config.hp, Attack=config.attack, Occupy=config.occupy, Reinforce=config.reinforce, Voyage=config.voyage; Speed=1.0f; soldier type=config.shipType. Runtime offsets are Camp24, HP28, Attack32, Occupy36, Reinforce40, Voyage44, Speed48, origin12.',[ref(100665360,'00295700','0029577c'),'generated/tables/SoldierConfig.json'])
add('tower-basic-fields','Tower: camp20, grade24, index28, spawnTime32, regenInterval36, IsAutoAddScore40(byte), maxScore44, score48(float), outgoingLineCount52, maxLines56, soldierType60, position68/72/76, collisionRadius80, forwarding-history list84, state88.',[ref(100665408),ref(100665432),ref(100665416)])
add('tower-capacity-grade','Ordinary Tower.Init reads maximum score from DispatchConfig ID3 (65), grade thresholds from ID1/ID2 (9/29). Grade=0 when trunc(score)<=9, 1 when 9<trunc(score)<=29, 2 when trunc(score)>29. This also demotes on loss. Max outgoing lines=1/2/3 by grade. Initialization sets collisionRadius=0.1f even though layout CollisionRadius is 0.',[ref(100665408,'00725c71','00725d05'),ref(100665420,'00725eaa','00725f08'),ref(100665432),'generated/tables/DispatchConfig.json'])
add('tower-damage','On soldier arrival to an enemy camp, call ChangeScore(soldier.CampID, -float(soldier.Occupy), false), then Soldier.Clear(true). Attack is used against soldiers, NOT for tower score damage.',[ref(100665389,'00725743','0072578e')])
add('tower-reinforce','On arrival to a same-camp non-full tower, ChangeScore(soldier.CampID,+float(soldier.Reinforce),false), then Clear(true). Full test uses trunc(score)>=maxScore. Positive results are clamped to maxScore.',[ref(100665389,'0072542b','00725483'),ref(100665389,'00725743','0072578e'),ref(100665425,'00499ed2','00499ef4')])
memory=(OUT/'wasm/wasmcode.static-memory.bin').read_bytes();encoded=struct.unpack_from('<I',memory,3928972)[0];typeindex=(encoded&0x1fffffff)>>1
boss=next((i,string(t[0])) for i,t in enumerate(types) if t[2]==typeindex)
assert boss==(4216,'Boss')
add('tower-capture','If delta!=0, score=f32(score+delta). If score<=0 and preventCapture==false and tower is not Boss: score=-score; ChangeCamp(sourceCamp), including exact-zero capture. Otherwise score<=0 is clamped to0 without capture. Positive branch clamps to[0,maxScore]. Capture branch retains overflow magnitude without a second cap.',[ref(100665425,'00499d58','00499d60'),ref(100665425,'00499e63','00499ef4'),{'staticMemoryAddress':3928972,'encodedMetadataUsage':hex(encoded),'decodedByvalTypeIndex':typeindex,'metadataTypeIndex':4216,'typeName':'Boss','metadataTypeOffset':pairs[19][0]+4216*88}])
add('camp-change','ChangeCamp first removes outgoing directions from this tower (incoming directions remain; bidirectional lines lose only this side), sets new camp, refreshes camp-specific visuals; after a real camp change clears state to Normal and refreshes global camp info. Capture/loss voice IDs2005/2006 are player-related and time-gated; Tree clear voice2018.',[ref(100665375),ref(100665555),ref(100665529),ref(100665524)])
add('full-friendly-forward','A full same-camp tower leaves score unchanged, decrements Voyage by1. If originTowerID==tower.IndexID OR Voyage<=0, clear soldier. Else obtain all outgoing lines, choose first line not in tower forwarding-history, add it to history and call line.AddSoldier(tower,soldier). If every outgoing line is visited, clear history and repeat enumeration. If no outgoing line, clear history and soldier. Thus round-robin follows list order; history is tower-owned, not soldier-owned.',[ref(100665389,'00725485','00725740'),ref(100665577,'0027123c','0027126a'),{'tableIndex':9521,'resolvedMethod':'WayLine.AddSoldier','resolvedModule':'wasmcode','resolvedFunction':14739}])
add('regeneration','When camp!=0, outgoingLineCount==0, IsAutoAddScore and state!=Tree: accumulator+=dt; if accumulator>=regenInterval, delta=1*product(buff.regenMultiplier), accumulator-=regenInterval once. Calls ChangeScore(ownCamp,delta,true). No loop to catch up multiple intervals in one update. Baseline regenInterval=2 seconds. Neutral towers do not regen. Accumulator pauses rather than resets when condition is false.',[ref(100665404,'00289fb6','0028a043'),ref(100665404,'0028a092','0028a24f'),ref(100665404,'0028a2d3','0028a2fe'),'generated/dispatch-model.json'])
add('rain-state','Rain state value3: a separate accumulator adds dt and at >=1s subtracts trunc(GameSceneControl field40) from delta, retaining 1s remainder. This shares ChangeScore(...,preventCapture=true); rain cannot transfer ownership.',[ref(100665404,'0028a254','0028a2fe')],scope='Rain state; config binding confirmed by boss-skill-parameters')
add('spawn-clock','For each enabled direction (state1 small->large; state2 large->small; state3 both), if source.state!=Tree, compute multiplier, add dt to direction timer; spawn only when timer>source.SpawnTime/multiplier; set timer=0 (discard overshoot). Timer does not run while its direction is disabled or source is Tree. At most one batch per direction per update. Source score is not consumed in base GetSoldierEntity/AddSoldier/spawn state machine.',[ref(100665496),ref(100665382),ref(100665513),ref(100665536)],scope='ordinary Tower virtual slot7 GetSoldierEntity and unmodified base dispatch')
add('spawn-multiplier','Base spawn-speed multiplier1. Rain replaces base with GameSceneControl float field36. Applies camp-specific virtual modifier, then multiplies all buff f64 field8 values converted to f32. The camp modifier is CommanderBase.GetSpawnRate (vtable slot8; base identity), with Commander2Skill and Commander4Skill overrides; buff fields are TowerBuff.spawnRate.',[ref(100665532)],status='confirmed',scope='formula structure confirmed; buff and camp modifier values unresolved')
add('spawn-batches','Scan source buffs for max(trunc(buff field24)) and max(trunc(buff field28)), initially0. Test Random.Next(0,100)<maxField28: if true batch3; else test Random.Next(0,100)<maxField24: if true batch2; else batch1. Async spawn loops batch times: obtain source.GetSoldierEntity via virtual slot7, AddSoldier, await configured0.2s wait. Undead5 gives generated soldier HP100000 and effect418; Comm04_2=6 attaches another EffectID. Base spawn has no score debit.',[ref(100665500),ref(4876),ref(100665515),ref(100665536,'00485e23','00485fb0'),ref(100665497,'00456e52','00456e6d'),ref(1545)],scope='batch mechanics; randomness source and modified soldier effect details not fully mapped')
add('line-init-and-directions','WayLine holds sorted small/large tower endpoints and separate opposing soldier lists. Init computes normalized straight-line direction with magnitude epsilon1e-5 and stores distance. AddSoldier checks soldier active and source is a currently enabled line direction; otherwise clears soldier. It resets soldier start/end positions and records the destination directional list.',[ref(100665495),ref(100665513)])
add('update-order','Active WayLine.Updata performs spawn timers, then moves all listed soldiers, then tower arrivals, then pair collisions between opposite lists. Arrival processing precedes opposite-unit combat in the same update.',[ref(100665534),ref(100665501)])
add('movement-frame','Only PlayState Running(value6) updates lines. WayLineControl computes scaledDelta=dt*ConfigMgr.gameTimeScale, movementLength=scaledDelta*ConfigMgr.shipTimeScale, movement vector=(0,0,1)*movementLength. Soldier movement along line uses magnitude of this vector times normalized direction and a camp-specific virtual modifier of Soldier.Speed (base1). ConfigMgr defaults resolve to gameTimeScale=1 and shipTimeScale=0.8 from GlobalValueConfig Content1 IDs101/102. Base CommanderBase.GetSoldierSpeed returns input unchanged. Skill overrides may change it.',[ref(100665573,'006e2534','006e2654'),ref(100663651),ref(100663652),ref(100665526),ref(100665351)],scope='base speed0.8 units/second; commander-dependent overrides')
add('arrival-boundary','Soldier arrives if distance(current,target)<=target.CollisionRadius OR distance(current,legStart)>=distance(legStart,legEnd). Ordinary tower radius0.1f. The latter prevents missing arrival after overshoot. Forwarding resets leg start/end and distance.',[ref(100665348),ref(100665337,'002959a6','00295a25'),ref(100665501,'00456506','004565a4'),ref(100665408,'00725cc1','00725ccc')])
add('movement-no-position-jitter','WayLine movement gate function6771 is only whether either directional soldier list is nonempty. Soldier.InitPosInfo directly copies passed start/end vectors into fields60..68/72..80, calls position setter10313 with the start vector, and computes leg distance. AddSoldier passes tower positions; this path adds no random lateral offset. InitPosInfo subsequent transform changes are model scale/orientation, not logical position jitter.',[ref(100665516),ref(100665337),ref(100665342),ref(100665513)],scope='normal WayLine.AddSoldier positioning')
add('soldier-combat','Compare opposite-direction soldiers on same WayLine with distinct camps. If distance<=ShipCollideDis, simultaneously subtract enemy Attack from each HP. Each HP<=0 is cleared; surviving HP persists. ShipCollideDis=max(movementLength,0.1f), so collision threshold adapts to frame movement. No separate attack cooldown appears in this path. One opposing pair is handled per first-list soldier per update (inner loop breaks after a hit). Same-camp soldiers pass through.',[ref(100665501,'0045697a','00456bd1'),ref(100665573,'006e263a','006e2654')])
add('effects','Grade increases play effectID105 and voice2014; decreases still switch grade model but do not play upgrade effect. Grade representation enables only the matching model list index. Enemy score-change hit effectID104 is rate limited to elapsed>0.5 seconds. Player-related tower arrival sound2012; lethal soldier contact sound2013.',[ref(100665420),ref(100665391),ref(100665425,'00499d62','00499e62'),ref(100665501)])
add('absolute-base-speed','ConfigMgr initializer token100663684 reads dictionary field116 (dicGlobalValue), ID101.Content1 parsed float to static fields8(gameTimeScale) and4(base scale); ID102.Content1 parsed float to static12(shipTimeScale). Cached values are1 and0.8, respectively. CommanderBase virtual slots8(GetSpawnRate) and9(GetSoldierSpeed) return input unchanged. Hence unmodified baseline unit speed0.8 world units/s; collision threshold=max(dt*1*0.8,0.1).',[ref(100663684,'005ded32','005dee53'),ref(100663651),ref(100663652),ref(100665065),ref(100665066),'generated/tables/GlobalValueConfig.json'])
add('tower-buff-fields','TowerBuff constructor assigns spawnRate=f64 offset8, riseRate=f64 offset16, spawnX2=f32 offset24 from integer argument, spawnX3=f32 offset28 from integer argument. Spawn-rate and rise-rate stack multiplicatively; X2/X3 chance thresholds take maximum across buffs, and X3 is tested before X2.',[ref(100664234),ref(100665500),ref(100665532),ref(100665404)])
add('arrow-basic','ArrowTower denies outgoing lines (get_IsCanAddLine always false). Update runs Tower.Update and then arrow targeting timer. Timer resets0 when elapsed>attackRate[grade], even if no target. SettingConfig defines attackRate=[1.8,1.3,0.8], attackRegion=[0.7,1,1.4], visual regionBaseScale0.44. Target search first requests one enemy soldier, then one enemy tower only when no soldier found, using grade range and minimum distance0.2.',[ref(100665255),ref(100665260),ref(100665259),ref(100665252),'generated/tables/SettingConfig.json'],scope='ArrowTower behavior; ShipID4 routing must be cross-checked in LevelControl factory')
add('arrow-hit','Projectile helper receives duration0.2f and an on-completion callback. Soldier hit callback directly calls ClearInSkill (kills regardless of HP), then hides and returns projectile to pool. Tower callback calls target.ChangeScore(source.currentCamp,-1,true): cannot capture a normal tower, only reduce to0. Source camp is read at callback time.',[ref(100665263,'0069fc44','0069fc80'),ref(100665265),ref(100665267,'0072afe8','0072b024'),ref(100665269)],scope='callbacks and duration arguments confirmed; helper3531/1459 exact engine method names not resolved')
add('skill-config-binding','CommanderBase.Upgrade reads CommanderConfig.skills in order; per-skill level from CommanderData.skills[i].level. SkillConfig key=skillID*100+level. Sets skill.cdTime32=float(duration), skillCamp12=commander.camp16, no8=i, args36=float[3]{data1,data2,data3}, targetType24=AllSkillConfig.targetType. SkillBase.Execute starts timer0 and inSkill16=true only if not already active. Updata calls SkillInUpdate1 always; active skills increment timer, invoke SkillInUpdate2(dt), then when timer>=duration reset timer/inSkill, invoke completion callback, and SkillEnd. Duration is active lifetime, not an inferred separate cooldown.',[ref(100665055),ref(100665074),ref(100665075),ref(100665078),'generated/tables/CommanderConfig.json','generated/tables/SkillConfig.json','generated/tables/AllSkillConfig.json'],scope='all commander skills')
add('commander2-speed','Commander2.GetSpawnRate: for queried camp==commander.camp use skills[0] (skill4), otherwise skills[1] (skill5). If selected skill.inSkill, multiply input by args[0]; otherwise identity. Thus skill4 modifies own camp dispatch, skill5 modifies every other camp. Both Execute methods use base active timer semantics.',[ref(100665126),ref(100665127),ref(100665128),ref(100665132)],scope='Commander2 skills4/5')
add('commander2-reinforce','Skill6 Execute reads selected target from SkillControl.TargetTower for player skillCamp1; when target exists calls its virtual ChangeScore(LevelControl.PlayerCampID,+trunc(args[0]),true), clears target reference, plays voice4501. This adds score and respects target maxScore; it cannot capture. Target eligibility is delegated to SkillControl.',[ref(100665134),ref(100665135)],scope='Commander2 skill6')
add('commander4-speed','Commander4.GetSpawnRate and GetSoldierSpeed apply only for queried camp==commander.camp and skills[1] (skill11) active. Spawn rate multiplies args[1]; soldier speed multiplies args[0]. When inactive/othercamp both are identity. Skill11.Execute sets all current player-camp towers to state6 (Comm04_2); SkillEnd resets all current player-camp tower states to0 unconditionally. Execute attaches effect420 to selected existing soldier effect holders using helper9548; -9999 is an effect duration/argument, NOT damage. Helper resolves wasmcode7935 and invokes GameModule.get_Effect, never ChangeScore/HP mutation.',[ref(100665158),ref(100665159),ref(100665161),ref(100665184),ref(100665185),ref(7935),ref(100664494)],scope='Commander4 skill11')
add('commander4-dot','Skill12 active SkillInUpdate2 adds dt to its own damage timer; at >=1 second subtracts1 once and invokes selectedTarget.ChangeScore(skillCamp,-trunc(args[0]),true). No catch-up loop. SkillEnd nulls target and zeroes damage timer. Execute coroutine binds selected target and starts the base skill timer; targeting/visual travel details remain partial.',[ref(100665189),ref(100665191),ref(100665194)],scope='Commander4 skill12 damage kernel')
add('commander1-freeze','Skill1 Execute iterates active non-neutral towers of a different camp, invokes tower virtual effect slot26 with6/cdTime and sets state1(Tree); removes all enemy soldiers via WayLineControl.RemoveAllEnemySoldier. Tree pauses generation and regen. SkillEnd clears state toNormal only on currently active different-camp towers whose current state isTree. Current ownership/state are checked at end, not a stored affected list.',[ref(100665106),ref(100665107),ref(100665404),ref(100665496)],scope='Commander1 skill1')
add('commander1-direct-damage','Skill3 selected-target strike calls ChangeScore(LevelControl.PlayerCampID,-trunc(args[0]),true), plays effect413 and voice4401. Damage cannot capture. The selected target field is44.',[ref(100665124,'006e756d','006e765d')],scope='Commander1 skill3 damage kernel; target selection elsewhere')
add('boss-init-and-soldier','Boss.Init reads CampConfig[camp].bossModelId to field256 and bossSoldierId to field184. Camp5..9 map model801..805 and soldier11..15. Boss maxScore44=trunc(initial StarInfo.Score), radius80=0.15f, autoRegen40=false; it retains ordinary grade thresholds and resets timers/state. Boss.GetSoldierEntity initializes a pooled Soldier using field184,camp,index. ChangeScore calls base with preventCapture=false but base explicitly recognizes Boss and clamps score<=0 to0 without ownership change; then publishes score notification.',[ref(100665274,'014ad7c0','014ad9fc'),ref(100665278),ref(100665286),ref(100665277),ref(100665425),'generated/tables/CampConfig.json'],scope='Boss runtime; layout factory selection not inferred from isBoss alone')
add('boss-skill-parameters','Boss.InitSkillData(actionID) reads BossConfig[actionID]: fields260/264/268/272=skill1_Hit/duration/first/second; fields276/280/284/288=skill2_Hit/duration/first/second. For initial camp6 only, writes GameSceneControl.rainSpawnMultiplier36=skill1_first and rainDamage40=skill1_Hit. Rain values therefore come from the active boss action config, not global guessed constants.',[ref(100665280),'generated/tables/BossConfig.json'],scope='Boss config binding')
add('boss-rain-area','While Boss field224 rainActive, Boss.Update adds dt to scanTimer248; when scanTimer>0.5 subtracts0.5 once and enumerates active towers. Only current player-camp or neutral towers qualify. If distance(tower transform position, rainCenter fields228..236)<skill1_second(field272), sets state3 Rain. Separately durationTimer220+=dt; when durationTimer>skill1_duration264, ends visual/audio rain, resets timers/active flag and sets EVERY current player-camp or neutral tower stateNormal. Out-of-radius towers are not cleared on each scan; cleanup occurs at the rain end.',[ref(100665287,'014ace6c','014ad36e')],scope='Boss rain update kernel; center and scheduling documented separately')
add('boss-action-dispatch','BossUseSkill(action): first stops any stored running coroutine. action1 starts Type4212 strike, action2 starts Type4214 projectile volley, action5 calls Boss3UseSkill1 (rain), action6 starts Type4215 strike. Values3/4 and values outside1..6 have no branch after stopping the prior coroutine.',[ref(100665284),ref(100665279),ref(100665273),ref(100665285)],scope='BossUseSkill API; higher-level schedule is separate')
add('boss-single-strikes','Action1 and6 play cast animation then yield UnityEngine.WaitForSeconds(1). On resume rebuild a list of active current player-camp towers, select one via RandomHelper-backed generic helper2673/10954, and apply ChangeScore(target.currentCamp,-hit,true). Action1 uses skill1_Hit260 and effect311 (position+up*0.3); action6 uses skill2_Hit276 and effect303. Both damage without capture. Selection has no explicit empty-list guard in these functions.',[ref(100665291),ref(100665305),ref(2673),ref(10954),{'staticMemoryAddress':3941920,'encodedMetadataUsage':'0x2000bbb7','metadataTypeIndex':6854,'typeName':'UnityEngine.WaitForSeconds'},{'staticMemoryAddress':3937580,'encodedMetadataUsage':'0x20009fb1','metadataTypeIndex':3391,'typeName':'GameFramework.RandomHelper'}],scope='Boss actions1/6')
add('boss-rain-center','Action5 Boss3UseSkill1 resets scan/duration timers to0, chooses one tower from LevelControl.GetCampAllTower(PlayerCampID) through helper2673/10954, copies its transform position into rainCenter228..236, sets rainActive224=true and enables rain visual. Plays voice3310. The affected region is later evaluated by boss-rain-area.',[ref(100665275),ref(2673),ref(10954)],scope='Boss action5')
add('boss-projectile-volley','Action2: cast animation, WaitForSeconds(1), then for integer i=0 while float(i)<skill2_first284: rebuild candidate list of all active non-Boss towers (all camps); select random target; launch pooled projectile from boss fields208..216 to target. Movement helper receives arc-height0.5 and duration=distance/2. Yield WaitForSeconds(skill2_duration280/skill2_first284) between launches. Callback rechecks target current camp: if camp==5, ChangeScore(5,+skill2_Hit276,true), effect404; otherwise ChangeScore(target.currentCamp,-skill2_Hit276,true), effect408. This can heal camp5 towers and harm any other camp, always without capture.',[ref(100665299),ref(100665296),ref(2673),ref(10954)],scope='Boss action2; motion helper exact engine name unresolved')
add('buff-lifecycle-stubs','Tower.InitBuff and BuffControl.Updata bodies are nop; they do not initialize or tick a buff in this build. Existing nonempty buff containers still affect the confirmed generation/regen formulas. No caller for the non-default TowerBuff constructor was identified by direct-call/table-index scan; this alone does not prove all buff containers remain empty, because inlined or generic creation may exist.',[ref(100665388),ref(100664232),ref(100664234)],scope='negative static evidence only; does not assert buffs absent at runtime')
add('boss-schedule-creation','AICampController.InitInfo first creates ordinary AICamp entries from non-neutral non-player CampInfoCfgs; then separately iterates StarInfoCfgs. Only Star.isBoss(byte56) creates/activates BossActionEntity using Star.CampID44 and Star.bossSkillId60, and calls current Boss.InitSkillData(bossSkillId). CampInfoCfgs.BossActionId is not read by this path. AICampController.Updata ticks the stored BossActionEntity only when ActiveUpdate and PlayState.Running6.',[ref(100664055),ref(100664046)],scope='serialized layout initialization; pre-init layout mutation must be considered separately')
add('boss-schedule-clock','BossActionEntity.Init stores camp16,configID12,active8=true, delay20=BossConfig.DelayTime/1000, countdown24=0. Each Update: if delay>0 subtract dt and RETURN (overshoot is discarded); otherwise countdown-=dt. Only when countdown<0 (strict) add one GetBossActionTime interval and invoke AICampController.BossUseSkill(camp,configID). Thus first action occurs the frame after delay reaches/crosses0; each update emits at most one action and interval overshoot is retained. GetBossActionTime selects ActionTime[index]/1000; missing config/list returns float.MaxValue. Existing config rows have one-element ActionTime arrays.',[ref(100664061),ref(100664063),ref(100663653),ref(100663680),'generated/tables/BossConfig.json'],scope='BossActionEntity exact timer semantics')
add('boss-weighted-action','ConfigMgr.GetBossAction(configID,trunc(boss.score),boss.maxScore) evaluates each pair Skill1/Skill2=[minimumHpPercent,weight]. Include pair if currentHp>=minimumHpPercent*(maxHp/100f), add weight to cumulative list, then sample RandomHelper.Random(0,totalWeight) and choose first cumulative>sample. Return skill slot1/2, or0 if none. Weight0 contributes no selectable interval. AICampController maps slots to actions: camp5→1/2, camp7→3/4, camp6→5/6, camp8→7/8,camp9→9/10. It acts on the current active Boss reference LevelControl+60; absent/inactive boss returns.',[ref(100663641),ref(100663648),ref(100664056)],scope='Boss weighted action decision')
add('commander1-fireball','Skill2 coroutine launches ceil(args[0]) balls (integer i while i<args0) at cdTime/args0 intervals while active. Every ball rebuilds a list of all active towers (all camps), picks one via RandomHelper, then Bullet.Init with arc1.5, end=target position+up*0.2, and duration=distance(origin,UNOFFSET target position)/10+0.3. On hit, compare target CURRENT camp to skillCamp: friendly adds trunc(args[2]), otherwise subtracts trunc(args[1]); ChangeScore uses target.currentCamp and preventCapture=true. It cannot capture. First-level config201 duration5,args[10,2,2].',[ref(100665118),ref(100665113),ref(100665115),'generated/tables/SkillConfig.json'],scope='Commander1 skill2')
add('commander3-undead','Skill8 Execute sets existing same-camp soldiers HP=10000 and effect418; sets current player-camp towers state5 Undead, causing newly generated soldiers HP=100000 via spawn state machine. These are large finite HP values, not an invulnerability flag. SkillEnd sets affected same-camp soldiers HP back to SoldierConfig.hp (full baseline HP), removes effect418, and resets current player-camp tower states toNormal.',[ref(100665149),ref(100665150),ref(100665536)],scope='Commander3 skill8')
add('commander5-inspiration','Skill13 Execute subscribes Event.SoldierInit (Event static offset60) and activates duration; SkillEnd unsubscribes. Callback only modifies newly initialized same-camp soldiers: effect511; Occupy*=trunc(1+args[0]/100f); Attack+=99. It does not iterate pre-existing soldiers in Execute. Thus localized description claiming all friendly soldiers is broader than this path.',[ref(100665199),ref(100665200),ref(100665201)],scope='Commander5 skill13')
add('commander6-fatigue','Skill16 Execute subscribes Event.SoldierInit and activates duration; SkillEnd unsubscribes. Callback only modifies newly initialized DIFFERENT-camp soldiers: effect611,Attack=0,Reinforce=0. Occupy and HP remain unchanged. It does not retroactively iterate all existing soldiers in Execute.',[ref(100665224),ref(100665225),ref(100665227)],scope='Commander6 skill16')
add('commander3-unlinkable','Skill7 Execute targets all active non-neutral different-camp towers. Each bat arrives through callback100665147: while Running, if target.state is not4 set Unlinkable4 and remove outgoing directions only. If already4 and now same skill camp, return bat to pool and setNormal; if already4 and still enemy, leave unchanged. SkillEnd returns tracked bat objects and clears ALL active towers currently state4, irrespective of camp.',[ref(100665140),ref(100665142),ref(100665147),ref(100665141)],scope='Commander3 skill7; incoming lines survive')
add('commander3-drain','Skill9 picks the player selected friendly target (field48), or random active same-camp tower for AI. For every active non-neutral different-camp source tower, source visual helper subtracts trunc(args0) with preventCapture=true before launching the absorption bullet. Travel duration argument is0.7. On arrival only while Running and selected target still belongs to skill camp, add trunc(args0) to that target (preventCapture=false); otherwise no heal. SkillEnd nulls selected target. The amount healed does not depend on source actual score loss after clamp.',[ref(100665152),ref(100665151),ref(100665153),ref(100665155)],scope='Commander3 skill9')
add('commander4-arrow-rain','Skill10 runs independent arrow visuals/collision and tower damage coroutines. Tower coroutine waits0.3s, then for integer i starting0 while i<=cdTime and active, applies -trunc(args1) with preventCapture=true to GetOtherTower(skillCamp), then waits1s. Visual coroutine emits two arrows per inner iteration, i<args0*0.5, waiting2/args0 between iterations. Each landed arrow queries different-camp soldiers in radius0.15 (minimum0), and clears only the FIRST returned soldier with ClearInSkill; it does not subtract HP. Visual random landing x=Random(-20,20)/20 and z=Random(-40,40)/15+3; launch height10, fall duration1.',[ref(100665163),ref(100665180),ref(100665174),ref(100665169),ref(100665171),ref(100665335)],scope='Commander4 skill10; inclusive integer endpoints confirmed by random-point-distribution')
add('commander5-recruit','Skill14 coroutine emits trunc(args0) special DeadSoldier objects at cdTime/trunc(args0) intervals, first emission immediate. Each chooses a random GetEnemyTower(skillCamp); if none, random neutral tower; no candidates skips that emission. Starts at UnityMathfTool.randomPoint(target.x,target.z,0.3,0.5). Init receives damage1,skillCamp,callbacknull. Each active unit moves normalized fixed direction by WayLineControl.movementLength*0.5 per update; hit when distanceSquared<0.01. On hit applies +1 if current target camp equals skillCamp, otherwise -1, with preventCapture=false, so it CAN capture ordinary towers. These are separate from ordinary WayLine soldier lists.',[ref(100665209),ref(100665220),ref(100665219),ref(100665221),ref(100665205)],scope='Commander5 skill14; discrete ring sampling confirmed by random-point-distribution')
add('commander5-serial-score','Skill15 selects one tower; if target camp equals skill camp, calls ChangeScoreInSerial(skillCamp,+trunc(args0),cdTime/args0,null); otherwise negative amount. Tower serial coroutine stores initial target camp, applies one +1/-1 immediately and then after each WaitForSeconds(gap), integer counter while counter<abs(amount). Every unit change uses preventCapture=true. If target becomes inactive it stops; if target camp changes and callback is null it stops. Skill15 has null callback, clears selected reference after starting sequence, and can never capture by its own damage. Friendly/enemy effect IDs532/531.',[ref(100665216),ref(100665413),ref(100665434)],scope='Commander5 skill15 scoring; selected target validation remains in controls')
add('commander6-recovery','Skill17 coroutine snapshots active same-camp towers once and attaches effect612. Starting immediately, each integer second i with i<cdTime iterates that stored list: if still same camp, ChangeScore(ownCamp,+args0,false), preserving float amount; if camp changed, remove corresponding effect. WaitForSeconds1 follows each pass. Newly captured friendly towers are not added to the snapshot. SkillEnd cleans remaining effects.',[ref(100665228),ref(100665234),ref(100665231)],scope='Commander6 skill17')
add('commander6-poison','Skill18 constructor radius56 is f32 bits1060320051 =0.7. While active, damageTimer44,killTimer48,elapsed52 each add dt. damageTimer>=1 subtracts1 once and applies -trunc(args0),preventCapture=true to GetTowerInRange(skillCamp,false,center88..96,radius0.7,min0). Separately only elapsed>1 and killTimer>0.2 resets killTimer0 and clears ALL different-camp soldiers in radius0.7 through ClearInSkill, regardless of HP. No catch-up loops. Drag-end accepts only |x|<2.5 and0.5<z<5 before launching bottle; center is selected ground position. SkillEnd resets timers and stops poison effect/audio.',[ref(100665238),ref(100665244),ref(100665239),ref(100665240),ref(100665335)],scope='Commander6 skill18; precise projectile-to-duration start relation still needs runtime verification')
add('tower-buff-read-only','Tower.GetBuff generic table9527 resolves through wasmcode1 f44848 to f20732. That specialization loads tower dictionary offset136, retrieves the requested key via generic dictionary helper, then performs generic cast/type handling. There is no allocation or insertion in this function. Combined with InitBuff nop, this removes GetBuff itself as a buff creation source, while leaving external/inlined creation unresolved.',[ref(21405),ref(1044848),ref(1020732),ref(100665388)],scope='generic GetBuff specialization; negative source evidence')
add('skill-update-clock','SkillControl.Updata only dispatches its current Commander when LevelControl.PlayState==Running6. CommanderControl.Updata is nop. CommanderBase.Updata loops its skills and passes the first dt argument twice to SkillBase.Updata; it does not apply ConfigMgr.gameTimeScale.',[ref(100665084),ref(100664247),ref(100665057)],scope='SkillBase duration and damage timers')
add('bullet-scaled-update','Bullet.Update f20382 increments elapsed12 by f1246, whose resolved internal-call name at static-memory1911954 is UnityEngine.Time::get_deltaTime(). Bullet is a MonoBehaviour-driven quadratic Bezier projectile, not a DOTween timer. Bullet.Init duration argument4 goes to60; bool argument8 is stored at84 and controls whether its component is disabled after arrival callbacks. Skill7 passes false so its landed bat callback repeats each Update until pooled/disabled. Skill2 also passes false, but its hit callback returns the object to its pool; skill9 passes true. Arrival tests squared-distance to end<1e-10 after evaluating the curve.',[ref(100664285),ref(100664289),ref(1246),ref(100665142),{'staticMemoryAddress':1911954,'decodedString':'UnityEngine.Time::get_deltaTime()'}],scope='skills2/7/9 and other Bullet-based effects; scaled Unity time')
add('bullet-control-point','Bullet.Init stores start at20..28, control at32..40, end at44..52, duration60 and arc76. Nonzero arc sets control=(start+end)/2+Vector3.up*arc. Zero arc computes normalized Cross(start-end,ProjectOnPlane(start-end,Vector3.up))*0.5 and adds/subtracts it from midpoint by inclusive RandomHelper.Random(1,100) parity. Static Vector3 usage3941368 resolves to metadata type6789; static field24 is upVector, not forwardVector. GetBezierPoint f4700 clamps t to[0,1] and evaluates the quadratic Bezier. Skill9 arc calls f5798 UnityEngine.Random::get_value, distinct from RandomHelper. Skill2 end is tower.position+up*0.2, but duration is Distance(origin,tower.position)/10+0.3 before applying that offset.',[ref(100664289,'00172a5c','00172cf6'),ref(4700),ref(5798),ref(100665151),ref(100665113),{'staticMemoryAddress':3941368,'metadataTypeIndex':6789,'staticFieldOffset':24,'field':'UnityEngine.Vector3.upVector'},{'staticMemoryAddress':1902483,'decodedString':'UnityEngine.Random::get_value()'}],scope='original Bullet geometry for skills2/7/9 and Boss volleys')
add('random-point-distribution','UnityMathfTool.randomPoint(x,z,minimumRadius,maximumRadius) samples angle=RandomHelper.Random(0,100)*0.01*pi*2 and radius=RandomHelper.Random(0,100)*0.01*(maximum-minimum)+minimum; returns x+radius*cos(angle),z+radius*sin(angle). Raw1621 implements RandomHelper.Random(min,max) by calling underlying Random.Next(min,max+1), so integer upper endpoint is inclusive. The two samples are discrete and radial distance is uniform, not uniform area.',[ref(9709),ref(1621),ref(1108),ref(1114)],scope='skill14 recruitment ring and helper-driven integer sampling')
add('commander-passive-stat-boundary','CommanderBase.Init stores CommanderData at12 and camp16, allocates a3-skill list, invokes subclass skill construction and Upgrade. Upgrade binds each skill config from saved skill levels; no separate hero-level HP/Attack/Occupy/regen passive multiplier is applied in these paths. Base GetSpawnRate/GetSoldierSpeed return the input unchanged. Confirmed active multipliers are Commander2 skills4/5 and Commander4 skill11; SoldierInit callbacks13/16 are separate stat mutations.',[ref(100665054),ref(100665055),ref(100665065),ref(100665066),ref(100665126),ref(100665158),ref(100665159)],scope='bounded absence of a passive stat multiplier in confirmed battle paths')
add('skills12-18-start-before-visual','Skill12 async MoveNext initial state sets inSkill=true and base timer0 before selecting target44; it spawns effect417 at target.position+up*0.7, then awaits0.8 before effect419/audio2032/2033. SkillInUpdate2 reads target44 and accumulates damage from the active start with no visual-ready gate. Skill18.Execute likewise sets active/timer immediately at006dd280..296, copies selected point76..84 to damage center88..96 at006dd297..2c3 (AI then replaces center with player tower position plus discrete jitter), before launching the bottle. Skill18.SkillInUpdate2 accumulates all three damage/kill timers unconditionally and queries that center; it has no bottle-landed gate. Therefore duration and damage start on Execute, not at visual completion.',[ref(100665194,'00512795','005127af'),ref(100665194,'00512c80','00512e43'),ref(100665189),ref(100665242,'006dd280','006dd372'),ref(100665244,'006dc428','006dc4d2')],scope='mechanical startup timing confirmed; visual asset load/callback frame timing still unverified')
add('commander-active-guard','CommanderBase function3652 finds a skill by SkillBase.type20 and returns its inSkill16 flag, orfalse if absent. This is active-duration status, not a separate cooldown countdown. Execute8120 finds the same type, stores completion callback40 and invokes virtual Execute. GetSkill6203 indexes list[type-1]. Effective5153 returns true fornull target; otherwise dispatches matching skill virtual target predicate.',[ref(100665061),ref(100665060),ref(100665062),ref(100665064)],scope='CommanderBase API consumed by SkillControl')
add('commander-multiplier-consumer','WayLine spawn multiplier f6775 loads SkillControl singleton usage3953560.currentCommander116 and invokes only that Commander virtual GetSpawnRate with tower camp. Soldier.MoveTo f15868 likewise invokes only the same Commander.GetSoldierSpeed. Neither consumer enumerates enemy Commanders. PVPController independently owns enemyCommander16 and does not assign SkillControl116 (special_pvp_all audit). Therefore AI skills4/5/11 may activate but their Commander multiplier overrides are not consumed by these movement/dispatch paths; direct Skill11 player-tower state6 side effects remain.',[ref(100665532,'002703ca','00270404'),ref(100665351,'007473ac','007473ea')],scope='player Commander consumers including PVP; enemy passive multiplier absence bounded to audited paths')
add('controller-update-registration-order','MineGameLogicModule registration occurs PVPController at005516d1, AIControl at005516ee, LevelControl at0055179c, SkillControl at005517f3 and WayLineControl at0055184a. PVP agents use scaled game dt followed by enemyCommander raw dt; player SkillControl raw-dt skill expiration occurs after the tower pass and before line spawn/movement. A player freeze expiring this frame therefore still blocks that frame tower regeneration, then allows line movement/spawn after cleanup.',['generated/pvp-evidence.json','generated/flow-evidence.json',ref(100665084),ref(100665057)],scope='controller order from flow-agent static registration audit; Unity async/projectile relative ordering remains unverified')
add('towerbuff-no-active-producer-found','Tower constructor creates an empty buff dictionary136; Tower.Clear helper removes buffs and clears that dictionary. Tower.InitBuff is nop. BuffControl constructor creates another empty dictionary; its event handler and Updata are nop. A two-module opcode-validated xref scan finds no direct call to TowerBuff parameter constructor f44849, no constant table14444 call site, no constant table15528 BuffEntity getter call site, and no TowerBuff TypeInfo encoded usage in aligned static memory. This supports an unenabled residual feature in the audited ordinary path, not a proof against every possible reflection/inlined producer. Do not invent buff values or block a fresh ordinary no-skill baseline on the mere existence of these fields.',[ref(100665380,'001de291','001de2af'),ref(100665384,'00289df9','00289e0e'),ref(100665388),ref(100664230),ref(100664232),ref(100664231),'generated/combat-lifecycle-xrefs.json'],scope='ordinary first-load buff emptiness; global dynamic reachability remains bounded')
add('serial-wait-runner-owner','Skill15 Tower.ChangeScoreInSerial awaits a UnityEngine.WaitForSeconds object through table2540->GetAwaiter5995->11853. This allocates SimpleCoroutineAwaiter, dispatches an Action to Unity synchronization context via5015, then closure14594 calls AsyncCoroutineRunner.Instance8244.StartCoroutine(ReturnVoid(...)). ReturnVoid state machine15141 yields the supplied wait, then completes the awaiter. Runner getter creates a GameObject named AsyncCoroutineRunner; Awake20638 sets hideFlags61 and calls Object.DontDestroyOnLoad1111. The wait is owned by that runner, not the Tower or Skill object. Opcode scan finds the only explicit StopAllCoroutines call in ResourcesModule.RemoveAll on its field20 ResourcesMono, a separate GameObject created in Initialize17743.',[ref(100665434),ref(5995),ref(11853),ref(5015),ref(14594),ref(15141),ref(8244),ref(20638),ref(1023540),ref(17743),'generated/combat-lifecycle-xrefs.json',{'staticMemoryAddress':3941920,'type':'UnityEngine.WaitForSeconds'},{'staticMemoryAddress':4045044,'literal':'AsyncCoroutineRunner'},{'staticMemoryAddress':4067944,'literal':'ResourcesMono'}],scope='skill15 and same GFRunning await helper; scaled wait owner/lifetime')
add('skill15-restart-conditional-survival','CommanderBase.Reset calls each Skill.Reset then SkillEnd; Skill15 has no Reset override. Tower.Clear calls helper6992 which sets Active8=false and clears visuals/buffs but has no cancellation-token or serial-task handle. Serial MoveNext holds the Tower object, initial camp and remaining loop count: after each wait it stops if inactive; if active and same initial camp it applies the next signed1; if camp differs and callbacknull (Skill15), it stops. Thus a restarted/reused Tower observed active with the same initial camp at continuation time can receive remaining old serial ticks. If the continuation observes the inactive interval or a different camp, it terminates. No explicit serial cancellation on Reset is evidenced. Reconstruction now preserves only the independently proven Skill15 waits, retaining delay/count and the original Tower reference across Restart. It checks Active/current camp at continuation time; actual original replay resource-loading timing still requires observation.',[ref(100665058),ref(100665216),ref(100665402),ref(100665384,'00289e11','00289e2a'),ref(100665434,'0054d373','0054d440')],scope='conditional source behavior; exact replay/reuse timing not measured')
add('soldier-skin-stat-separation','Soldier.Init obtains combat fields only from SoldierConfig and then emits SoldierInit event. GetSoldierObj for shipType<=9 chooses player equipped or enemy random skin through PlayerControl, loads the prefab, invokes InitGameObject and recolors it. shipType>9 uses SoldierConfig.EntityID. InitGameObject/config helper sets scale, animation component, shadow and active state; it does not overwrite HP/Attack/Occupy/Reinforce/Voyage. SkinConfig IDs104/204/304 map to visual prefab1004/2004/3004; their04 labels do not establish an extra combat type. SoldierConfig has only IDs1,2,3,11..15, while EntityModelConfig soldier_400..427 have no matching SkinConfig type4 or SoldierConfig4.',[ref(100665360),ref(100665336),ref(100665349),ref(100665355),'generated/tables/SoldierConfig.json','generated/tables/SkinConfig.json','generated/tables/EntityModelConfig.json'],scope='configured soldier variants and visual-only skin selection')
unknowns=[
 {'id':'runtime-oracle','status':'unknown','question':'原游戏运行时数值与时序验证','next':'在原游戏代表关卡记录连线、三次命中占领、升级/降级、对冲和满塔转发；与静态派生测试逐项比对。'},
 {'id':'remaining-skills','status':'unknown','question':'技能12/18表现资源加载与异步回调实际帧时序','next':'数值核已确认在Execute立即起算，不能等待表现落地再计时；资源延迟与画面表现需原游戏代表配置对照。'},
 {'id':'buffs','status':'unknown','question':'TowerBuff是否存在未发现的反射或内联创建来源','next':'普通初始化/控制器更新均无producer，2模块xref未找到构造调用或TypeInfousage；当前空buff普通基线可验收。仅在真实save/runtime出现buff时重开调查。'},
 {'id':'special-tower','status':'unknown','question':'Boss空候选目标行为、特殊模式加载是否改写Star.isBoss/bossSkillId；Bastion是否独立机制','next':'BossActionEntity和调度已闭环；普通加载未发现字段patch。需审计特殊模式入口。仅2份布局有isBoss=true，不可把CampInfo.BossActionId配置均当已启用；CampConfig.BasitionMaterial仅证明材质字段。'},
 {'id':'async-time','status':'unknown','question':'异步跨Restart复用原塔的实际恢复帧时序','next':'table2540/2542已闭合为Unity WaitForSeconds、常驻AsyncCoroutineRunner；skill15条件存活已证实，需观察旧continuation是否在inactive窗口触发。'},
 {'id':'rendering','status':'unknown','question':'grade模型、动画时长、命中特效资产完整绑定及UI精确位置','next':'接合资源分析产物与运行截图；本子任务只交付机制与效果调用证据。'}]
cases=[
 {'id':'L0-neutral-capture','status':'derived-not-runtime-verified','level':'generated/levels/level_0.json','pre':{'tower':0,'camp':0,'score':3,'shipConfigID':1,'incomingCamp':1,'incomingCount':3},'expected':{'afterEachScore':[2,1,0],'afterEachCamp':[0,0,1]},'rules':['tower-damage','tower-capture']},
 {'id':'L0-source-grade','status':'derived-not-runtime-verified','pre':{'level':0,'tower':3,'score':10},'expected':{'grade':1,'maxOutgoingLines':2,'oneLineBaseSpawnTime':1.032,'twoLineBaseSpawnTime':1.185},'rules':['tower-capacity-grade','spawn-clock']},
 {'id':'capture-overflow','status':'derived-not-runtime-verified','pre':{'camp':0,'score':1,'incomingCamp':1,'incomingShip':3,'occupy':2},'expected':{'camp':1,'score':1},'rules':['tower-capture']},
 {'id':'friendly-cap','status':'derived-not-runtime-verified','pre':{'camp':1,'score':64,'incomingCamp':1,'incomingShip':2,'reinforce':2},'expected':{'score':65,'soldierConsumed':True},'rules':['tower-reinforce']},
 {'id':'equal-hp-contact','status':'derived-not-runtime-verified','pre':{'A':{'hp':1,'attack':1,'camp':1},'B':{'hp':1,'attack':1,'camp':2},'withinThreshold':True},'expected':{'hpA':0,'hpB':0,'bothClear':True},'rules':['soldier-combat']},
 {'id':'tank-contact','status':'derived-not-runtime-verified','pre':{'A':{'hp':2,'attack':2,'camp':1},'B':{'hp':1,'attack':1,'camp':2},'withinThreshold':True},'expected':{'hpA':1,'hpB':-1,'clearB':True},'rules':['soldier-combat']},
 {'id':'grade-edges','status':'derived-not-runtime-verified','pre':{'scores':[9,9.9,10,29,29.9,30,65]},'expected':{'grades':[0,0,1,1,1,2,2]},'rules':['tower-capacity-grade']},
 {'id':'base-regen','status':'derived-not-runtime-verified','pre':{'camp':1,'score':9,'outgoing':0,'regenAccumulator':0,'deltaTime':2,'buffs':[],'state':0},'expected':{'score':10,'grade':1,'regenAccumulator':0},'rules':['regeneration','tower-capacity-grade']},
 {'id':'spawn-no-catchup','status':'derived-not-runtime-verified','pre':{'baseInterval':1.032,'timer':1.02,'deltaTime':0.03,'multiplier':1},'expected':{'batchCount':1,'timer':0,'sourceScoreDebit':0},'rules':['spawn-clock']},
 {'id':'forward-budget','status':'derived-not-runtime-verified','pre':{'fullFriendly':True,'voyage':1,'originIsCurrent':False},'expected':{'voyage':0,'cleared':True,'forwarded':False},'rules':['full-friendly-forward']}]
cases += [
 {'id':'boss-zero-no-capture','status':'derived-not-runtime-verified','pre':{'isBossRuntime':True,'initialScore':150,'score':1,'camp':6,'incomingCamp':1,'delta':-2},'expected':{'score':0,'camp':6,'maxScore':150,'autoRegen':False,'radius':0.15},'rules':['boss-init-and-soldier','tower-capture']},
 {'id':'skill4-level1','status':'derived-not-runtime-verified','pre':{'skillConfigID':401,'sameCamp':True,'active':True,'inputSpawnRate':1},'expected':{'spawnRate':1.8,'duration':10},'rules':['skill-config-binding','commander2-speed']},
 {'id':'skill5-level1','status':'derived-not-runtime-verified','pre':{'skillConfigID':501,'sameCamp':False,'active':True,'inputSpawnRate':1},'expected':{'spawnRate':0.7,'duration':10},'rules':['skill-config-binding','commander2-speed']},
 {'id':'skill11-level1','status':'derived-not-runtime-verified','pre':{'skillConfigID':1101,'sameCamp':True,'active':True,'baseWorldSpeed':0.8},'expected':{'spawnRateMultiplier':1.8,'soldierSpeedMultiplier':1.8,'worldSpeedApprox':1.44,'duration':10},'rules':['skill-config-binding','commander4-speed']},
 {'id':'skill3-cannot-capture','status':'derived-not-runtime-verified','pre':{'skillConfigID':301,'targetCamp':2,'score':10,'playerCamp':1},'expected':{'score':0,'camp':2,'damage':20},'rules':['skill-config-binding','commander1-direct-damage']},
 {'id':'skill12-no-catchup','status':'derived-not-runtime-verified','pre':{'skillConfigID':1201,'damageTimer':0,'dt':2.5,'score':20,'camp':2},'expected':{'score':15,'damageTimer':1.5,'camp':2},'rules':['skill-config-binding','commander4-dot']}]
cases += [
 {'id':'skill9-clamp-not-conservation','status':'derived-not-runtime-verified','pre':{'skillConfigID':901,'enemySourceScore':2,'friendlyTargetScore':10,'targetStillFriendlyOnArrival':True},'expected':{'enemySourceScore':0,'enemyCampUnchanged':True,'friendlyTargetScore':15},'rules':['commander3-drain']},
 {'id':'skill13-new-only','status':'derived-not-runtime-verified','pre':{'skillConfigID':1301,'newSoldier':{'occupy':1,'attack':1},'existingSoldier':{'occupy':1,'attack':1}},'expected':{'newSoldier':{'occupy':2,'attack':100},'existingSoldier':{'occupy':1,'attack':1}},'rules':['commander5-inspiration']},
 {'id':'skill14-recruit-capture','status':'derived-not-runtime-verified','pre':{'skillConfigID':1401,'emittedRecruitDamage':1,'targetCamp':2,'targetScore':1,'skillCamp':1,'hitDistanceSquared':0.005},'expected':{'targetScore':0,'targetCamp':1,'spawnCount':25,'spawnInterval':0.2},'rules':['commander5-recruit','tower-capture']},
 {'id':'skill15-does-not-capture','status':'derived-not-runtime-verified','pre':{'skillConfigID':1501,'targetCamp':2,'targetScore':2,'skillCamp':1,'ticks':3},'expected':{'scores':[1,0,0],'camp':2,'totalUnitTicks':30,'gapApprox':0.0566666667},'rules':['commander5-serial-score']},
 {'id':'skill16-occupy-not-attack','status':'derived-not-runtime-verified','pre':{'skillConfigID':1601,'newEnemy':{'attack':2,'reinforce':2,'occupy':1,'hp':2}},'expected':{'attack':0,'reinforce':0,'occupy':1,'hp':2},'rules':['commander6-fatigue']},
 {'id':'skill17-snapshot','status':'derived-not-runtime-verified','pre':{'skillConfigID':1701,'initialFriendlyTowerIds':[1],'newlyCapturedTowerId':2,'score1':10,'score2':10,'healingPasses':1},'expected':{'score1':13,'score2':10},'rules':['commander6-recovery']},
 {'id':'skill18-damage-no-catchup','status':'derived-not-runtime-verified','pre':{'skillConfigID':1801,'damageTimer':0,'elapsed':0,'killTimer':0,'dt':2.5,'inRangeEnemyScore':10,'inRangeEnemySoldierHp':100000},'expected':{'enemyScore':8,'damageTimer':1.5,'killTimer':0,'soldierCleared':True},'rules':['commander6-poison']},
 {'id':'boss-delay-overshoot','status':'derived-not-runtime-verified','pre':{'delay':0.1,'countdown':0,'frameDeltas':[0.2,0.01],'interval':17},'expected':{'actionsPerFrame':[0,1],'finalCountdownApprox':16.99},'rules':['boss-schedule-clock']}
]
corrections=[{'id':'projectile-vector-and-disable','previousClaim':'Vector3 static field24 was treated as forward; Skill2 autoDisable was reported true.','correctedClaim':'Static field24 is upVector; Skill2 passes autoDisable=false but its hit callback pools the object. Bullet curve and duration now use exact source geometry.','evidence':[ref(100664289),ref(100665113),ref(100665115)]},{'id':'outgoing-only-capture-cleanup','previousClaim':'ChangeCamp removes all touching lines','correctedClaim':'ChangeCamp removes outgoing directions only; incoming directions survive and bidirectional lines become incoming-only.','evidence':[ref(100665555),ref(100665529),ref(100665524)]}]
report={'target':{'appid':'wxcf1394487200e48f','version':'43'},'generatedAt':datetime.now(timezone.utc).isoformat(),'analysisMode':'static-only; target code was never executed by this subtask','implementationGate':'static handoff: ordinary combat and all18 skill kernels plus Boss scheduling supported; listed timing/reachability unknowns and runtime verification remain','commands':[{'command':'python analysis/combat_disassemble.py','exitCode':0},{'command':'python analysis/combat_extra_map.py','exitCode':0},{'command':'python analysis/combat_evidence.py','exitCode':0}],'pythonVersion':sys.version,'sourceHashes':{str(x.relative_to(ROOT)):hashlib.sha256(x.read_bytes()).hexdigest() for x in [metadata,OUT/'wasm/wasmcode.wasm',OUT/'wasm/wasmcode1.wasm']},'corrections':corrections,'enumValues':enums,'rules':rules,'derivedCases':cases,'unknowns':unknowns,'meaningfulFailures':['Initial PowerShell inline string escaping failed before writing; replaced by Python heredoc.','Initial console output GBK could not represent obfuscated names; PYTHONIOENCODING=utf-8 fixed display.','Original gameplay-symbols excludes namespace-empty nested async types: independent parser recovered type4233 spawn state machine.']}
(OUT/'combat-evidence.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8')
lines=['# COMBAT_EVIDENCE','',f'Target: wxcf1394487200e48f / 43. Generated: {report["generatedAt"]}.','静态分析；未运行目标代码。这里的派生案例不是原游戏黄金验证，不能宣称完整关内已还原。','', '## 可实施的普通关内机制','']
for rule in rules:
 lines+=['### '+rule['id'],'','[已确认] '+rule['rule'],'','Scope: '+rule['scope'],'']
 for e in rule['evidence']:
  if isinstance(e,dict) and 'disassembly' in e:lines+=['- '+e['disassembly']+':'+str(e['lines'][0])+' (through line '+str(e['lines'][1])+'); '+e['wasm']+' function '+str(e['function'])+'; body ['+hex(e['bodyOffset'])+','+hex(e['bodyOffset']+e['bodySize'])+').']
  else:lines+=['- '+(e if isinstance(e,str) else json.dumps(e,ensure_ascii=False))]
 lines+=['']
lines+=['## 修正记录','','ChangeCamp先前“移除全部关联线”的表述不准确：只撤去本塔出兵方向，入线保留，双向线降为单向入线。证据见 camp-change 条目及 JSON corrections。Vector3静态field24也已由forward修正为up；技能2的autoDisable为false，但命中回调会回池。','','## 枚举实际值','',json.dumps({k:{x['name']:x['value'] for x in v} for k,v in enums.items()},ensure_ascii=False,indent=2),'','## 派生案例（尚未原游戏验证）','']
for c in cases:lines+=['- '+c['id']+': '+json.dumps({'pre':c['pre'],'expected':c['expected']},ensure_ascii=False)]
lines+=['','## 待确认项','']
for u in unknowns:lines+=['- [待确认] '+u['question']+'。最小下一步：'+u['next']]
lines+=['','## 重现','', '```powershell','python analysis/combat_disassemble.py','python analysis/combat_extra_map.py','python analysis/combat_evidence.py','```','','所有函数与元数据读取均为本地静态解析。原始包不变。共享 manifest、总报告、总状态未修改。']
(ROOT/'COMBAT_EVIDENCE.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
print(json.dumps({'rules':len(rules),'derivedCases':len(cases),'unknowns':len(unknowns),'output':'generated/combat-evidence.json'},ensure_ascii=False))
