"""Record evidence-backed player control and adjacency rules without target execution."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).parent/'targets/wxcf1394487200e48f/43'
DIS=ROOT/'generated/controls-disassembly'
def src(name,start=None,end=None):
    p=DIS/name;t=p.read_text(encoding='utf8')
    if start:assert start in t,(name,start)
    if end:assert end in t,(name,end)
    return {'path':p.relative_to(ROOT).as_posix(),'wasmByteStart':start,'wasmByteEnd':end,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
rules=[]
def rule(id,statement,evidence,**data):rules.append(dict(id=id,status='confirmed',statement=statement,evidence=evidence,**data))
rule('adjacency-cache','GetStarAllLine(towerIndex) lazily creates one list in the dictionary at WayLineControl+136; it is a candidate adjacency list, not the active outgoing-line count.',[src('WayLineControl-GetStarAllLine-100665552.txt','00154469','001544c3')])
rule('adjacency-generation','InitStarLine async MoveNext waits for level readiness and one EndOfFrame, then iterates active tower pairs i<j and calls GetWayLineEntity. It next builds each tower adjacency by collecting every pooled WayLine.IsContainTower(tower), then sorts by ascending LineLength.',[src('__zX_lp-MoveNext-100665604.txt','00486cc2','00486ce0'),src('__zX_lp-MoveNext-100665604.txt','00487425','00487579'),src('__zX_lp-MoveNext-100665604.txt','00486e1c','004871ef'),src('__c-TnyuYV_-100665602.txt','0070f0fb','0070f111'),src('CoreProbe-function2297-2297.txt','000ab9c2','000ab9f1')],asyncTypeDefinitionIndex=4238,asyncMoveNextFunction=9892,sort='lineA.LineLength.CompareTo(lineB.LineLength)',tieRule='No secondary key in comparator; do not claim a stable tie order.')
rule('capsule-blocking','Potential lines use tower world positions and Physics overlap-capsule radius 0.029999999329447746 in the GamePlayer1 layer. Any collider whose GameObject differs from both endpoint GameObjects blocks creation. Existing pair lookup happens before this new-line test.',[src('WayLineControl-GetWayLineEntity-100665560.txt','00270e25','00270ed5'),src('WayLineControl-GetOverlapCapsuleGameObj-100665583.txt','0018a3f7','0018a407'),src('WayLineControl-_oWgo__-100665571.txt','001d699e','001d6a16'),src('Layers-.cctor-100668000.txt') if (DIS/'Layers-.cctor-100668000.txt').exists() else src(next(DIS.glob('Layers-.cctor-*.txt')).name,'00821183','0082118b')],radius=0.029999999329447746,layer='GamePlayer1')
rule('line-direction-states','WayLine canonical endpoints are small/large tower index. State 0 none, 1 small→large, 2 large→small, 3 both. SetLineState rejects already-both and already-same-direction. Adding the reverse direction between same-camp towers replaces direction; different camps become bidirectional.',[src('WayLine-SetLineState-100665522.txt','0027025e','002702a4'),src('WayLine-IsFromThisTower-100665529.txt','00122c56','00122ca4')],states={'0':'none','1':'small-to-large','2':'large-to-small','3':'bidirectional'})
rule('remove-outgoing-only','RemoveStarAllLine(tower) iterates WayLines but removes only IsFromThisTower=true. In a bidirectional line RemoveLine(tower) leaves the opposite direction. Inbound-only lines remain. This corrects any earlier interpretation that camp-change deletes every touching line.',[src('WayLineControl-RemoveStarAllLine-100665555.txt','00270b18','00270b38'),src('WayLine-RemoveLine-100665524.txt','00270675','002706a8')],transitionCases=[{'before':3,'remove':'small','after':2},{'before':3,'remove':'large','after':1},{'before':1,'remove':'small','after':0},{'before':1,'remove':'large','after':1},{'before':2,'remove':'small','after':2},{'before':2,'remove':'large','after':0}])
rule('line-count-outgoing','GetTowerAllLine filters IsFromThisTower; SetTowerLineNum writes that list count through virtual slot 9. Incoming lines therefore do not consume the tower outgoing count.',[src('WayLineControl-GetTowerAllLine-100665577.txt','0027123c','00271246'),src('WayLineControl-SetTowerLineNum-100665597.txt','002709b3','002709ed')])
rule('ai-connect-validation','AITryConnectLine rejects ArrowTower, source state 4 (Unlinkable per combat evidence), self target, and failed virtual get_IsCanAddLine. It obtains the pair and calls SetLineState only if a non-null line exists.',[src('WayLineControl-AITryConnectLine-100665563.txt','006e334c','006e33aa')])
rule('press-player-source','Touch-down handler f14747 is gated by CanDraw and an overlay/input-block flag, raycasts tower/obstacle layer GamePlayer1, resolves the GameObject to a tower, requires source camp == LevelControl.playerCamp, and requires virtual get_IsCanAddLine. Rejected selection clears source fields. It preserves original tutorial-specific level-2 gate instead of inventing generic behavior.',[src('WayLineControl-M____rR-100665576.txt','006e2988','006e2a81')],handlerFunction=14747,sourceObjectField=116,sourceTowerField=124,pendingTargetObjectField=120,dragActiveField=64)
rule('drag-preview-release-commit','Touch-move f9378 projects pointer to Scenes10 ground, updates preview and potential target; it does not call SetLineState. Touch-up f14746 calls f9379 only when source and target objects exist, then resets selection, active flag, cutting marker and preview. f9379 requires distinct valid towers, stored selected source identity, and source capacity, then GetWayLineEntity and SetLineState.',[src('WayLineControl-_uZly_h-100665574.txt','004579dc','00457b4f'),src('WayLineControl-O_PYk_S-100665554.txt','006e28e6','006e2928'),src('WayLineControl-_xt_lM_-100665584.txt','00458628','004586e8'),src('WayLineControl-n__fO_a-100665570.txt','0018a1f7','0018a247')])
rule('nearest-drag-collider','Preview helper f9377 excludes the source GameObject and chooses the nearest collider by world-space Euclidean transform-position distance, starting at 1000. It replaces on <=, so equal-distance candidates choose the last collider in the engine-provided result order.',[src('WayLineControl-q_VST__-100665580.txt','00457859','00457955')],maxInitialDistance=1000,replaceOnEqual=True)
rule('cut-player-direction','When dragging from empty ground, f9378 checks the segment between previous/current world points against GameNPC1, obtains the WayLine from the hit object, and calls RemoveLine(LevelControl.playerCamp). That overload removes direction(s) whose source endpoint camp matches the player; enemy outbound direction survives a bidirectional cut.',[src('WayLineControl-_uZly_h-100665574.txt','00458525','004585dd'),src('WayLine-RemoveLine-100665494.txt','00457451','00457483')],layer='GameNPC1')
rule('interaction-feedback','Press tower plays audio ID 2015; successful pair obtained on release plays 2007; a cut hit plays 2008. Connection/cut paths request a 50 ms vibration (type 2).', [src('WayLineControl-M____rR-100665576.txt','006e2a02','006e2a0e'),src('WayLineControl-_xt_lM_-100665584.txt','004586ba','004586dd'),src('WayLineControl-_uZly_h-100665574.txt','0045859e','004585c1')],audio={'press':2015,'connect':2007,'cut':2008},vibrateMs=50)
data={'schemaVersion':1,'target':{'appId':'wxcf1394487200e48f','version':'43'},'validationLevel':'Static bytecode control-flow and literal evidence; original-game live interaction not observed','rules':rules,'crossReferences':[{'path':'generated/combat-evidence.json','rules':['tower-capacity-grade','arrow-basic'],'claim':'Ordinary tower maximum outgoing slots 1/2/3 at trunc(score)<=9 / <=29 / >29; ArrowTower refuses outgoing connection. Combat agent verified source functions.'}],'unknowns':[{'id':'preview-segment-style','status':'unknown','description':'Exact WayLineCircle.DrawParaLine preview shape/color choices across every blocked/nearest-target branch are not yet normalized into a standalone behavioral model.','verificationPlan':'Read WayLineCircle implementation and compare a captured drag path with source overlay.'},{'id':'input-live-baseline','status':'unknown','description':'No live original-game touch trace or visual baseline was obtained by this subtask.','verificationPlan':'Replay own-tower drag, blocker drag, enemy reverse line and empty-ground cut in original game and restored build.'},{'id':'tutorial-special-branches','status':'unknown','description':'Level-2 tutorial-specific press restrictions remain in bytecode evidence; full tutorial phase integration belongs to level-flow recovery.','verificationPlan':'Cross-reference LevelControl.CurLevel and GuideControl phase predicates before enabling original tutorial gates.'}]}
(ROOT/'generated/controls-evidence.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf8')
lines=['# Controls and adjacency evidence','','Target `wxcf1394487200e48f/43`. Static local WASM evidence; no game code executed.','']
for r in rules:
    lines.extend(['## '+r['id'],'','[已确认] '+r['statement'],''])
    lines.extend('- `'+s['path']+'`'+(' @ `0x'+s['wasmByteStart']+'`–`0x'+s['wasmByteEnd']+'`' if s['wasmByteStart'] else '') for s in r['evidence'])
    lines.append('')
lines.extend(['## Limits','','[待确认] Preview line geometry and all tutorial-specific branches require the next bounded checks listed in controls-evidence.json. Static findings do not certify a live visual match.','','Reproduce: bundled Python `-B analysis/controls_disassemble.py`, then `-B analysis/controls_evidence.py`. Both exit 0. Every cited offset is checked against the generated disassembly.'])
(ROOT/'generated/CONTROLS_EVIDENCE.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
print(json.dumps({'rules':len(rules),'evidenceOffsetsVerified':sum(len(r['evidence']) for r in rules),'unknowns':len(data['unknowns'])}))
