"""Record independently checked static flow evidence; never execute target code."""
import json,sys,subprocess,hashlib,struct
from pathlib import Path
ROOT=Path(__file__).parent/'targets/wxcf1394487200e48f/43'
selected=[('Global','.cctor'),('LevelControl','OnInit'),('UnityMathfTool','GetVector3ByVector3Int'),('StarInfoCfg','SetTransform'),('LevelControl','RefreshCampInfo'),('@7629',),('LevelControl','OnGamePlayState'),('LevelControl','Updata'),('@11599',),('@11596',),('@15186',),('Tower','Init'),('AICamp','Init'),('AICamp','Updata'),('AICampController','InitInfo'),('AICampController','GetStarAIAction'),('ConfigMgr','GetAIAction'),('@5139',),('ConfigMgr','GetAIDelayTime'),('ConfigMgr','GetAIActionTime'),('ConfigMgr','GetAIActionNum'),('ConfigMgr','GetLevelConfig'),('ConfigMgr','GetLevelRealID'),('GameControl','SetCameraSize')]
selected += [('AICampController','AIGoToAction'),('LevelControl','GetCampAllTowerNonArrow'),('@9710',),('@5918',),('@11593',),('@11594',),('@11595',),('Path','.cctor'),('@15519',),('StarInfoCfg','.ctor'),('ObstacleInfoCfg','.ctor'),('LevelControl','InitGameData'),('LevelControl','SetLevelSpeed'),('AICampController','Updata'),('WayLineControl','Updata'),('GameControl','.cctor'),('@11337',),('@1622',),('@18543',),('@5043',),('@12170',)]
dis=[]
for args in selected:
 p=subprocess.run([sys.executable,str(Path(__file__).parent/'flow_disassemble.py'),*args],capture_output=True,encoding='utf-8',check=True)
 dis.append({'command':'python analysis/flow_disassemble.py '+' '.join(args),'exitCode':p.returncode,'text':p.stdout})
def fact(id,status,value,refs):return dict(id=id,status=status,value=value,evidence=refs)
def w(a,b):return 'generated/wasm/wasmcode.wasm:0x'+a+'-0x'+b
facts=[
 fact('player-camp','confirmed',1,[w('846bfb','846c0b'),w('81fb98','81fbb6')]),
 fact('coordinate-decimal-places','confirmed',2,[w('846bdb','846beb')]),
 fact('tower-world-position','confirmed',{'formula':'position = (pos.x, pos.y, pos.z) / 100.0','coordinateSpace':'Unity world position','axes':'unchanged x/y/z','scaleStatus':'StarInfoCfg.SetTransform consumes pos and caller-provided euler angles; serialized scale not consumed here'},[w('29238a','29241f'),w('18c9dc','18ca37'),'python analysis/flow_api_names.py: wasmcode function1348 = UnityEngine.Transform.set_position']),
 fact('normal-level-tower-init','confirmed',{'count':'StarInfoCfgs.Length','towerIds':'array index + 1','camp':'StarInfoCfg.CampID','score':'float(StarInfoCfg.StartScore)','ship':'StarInfoCfg.ShipID','legacyDispathchID':'not a field in current StarInfoCfg metadata; Tower.Init consumes ShipID, not legacy DispathchID'},[w('56ac0c','56acef'),w('725bc8','725bea'),w('725c66','725c71'),w('725ccc','725cd9'),'gameplay-symbols.json: StarInfoCfg fields']),
 fact('ship4-arrow-tower','confirmed',{'rule':'ShipID==4 creates or reuses ArrowTower; other non-boss ShipIDs create/reuse Tower','legacyDispathchID99':'No current typed field consumes it; ShipID controls tower subclass'},[w('56ac50','56ac59'),w('56a9f1','56aa0c'),w('56aa4e','56aa62')]),
 fact('battle-state-enum','confirmed',{'None':0,'First':1,'StartUI':2,'Enter':3,'BeforePlay':4,'StartPlay':5,'Running':6,'Pause':7,'Victory':8,'Defeat':9,'Again':10,'Exit':11,'Jump':12,'EnterSmallLevel1':13,'EnterSmallLevel2':14,'Relive':15},['global-metadata.dat: field indices18349..18364; compressed default bytes00,02,...1e',w('37a144','37a15e')]),
 fact('state-transitions','confirmed',{'initial':'First -> StartUI','enter':'Enter opens loading then callback requests current-level configuration','ready':'load callback creates towers/obstacles, RefreshCampInfo, BeforePlay unless callback flag disables transition','beforePlay':'BeforePlay -> StartPlay after pre-game UI checks','start':'StartPlay -> Running for non-guide; guide advances guide stage','again':'Again invokes InitGameData, resets SmallLevelIndex to0, enters Enter','runningUpdate':'Tower updates only if current state==6'},[w('37a15f','37a1c4'),w('708548','7085fa'),w('37a2cc','37a33d'),w('37a510','37a555'),w('81f516','81f51e')]),
 fact('victory-defeat','confirmed',{'evaluation':'RefreshCampInfo; skips StartUI and special-controller active guard; requires player camp record','defeat':'player camp active tower count == 0 -> Defeat(9)','victory':'total initial StarInfoCfg count <= player camp active tower count -> Victory(8)','bossVictory':'if curBoss exists and trunc(curBoss.score/HP) <= 0 -> Victory(8)','refresh':'score-sum dirty flag and countdown<=0 cause RefreshCampInfo in Running; countdown +=1 second'},[w('163a78','163abc'),w('163b10','163b6b'),w('379ee5','379ef1'),w('81f6fb','81f736')]),
 fact('AI-active-camps','confirmed','AI controller initializes only CampID !=0 and CampID !=PlayerCampID; AIGrade passed to AICamp.Init',[w('631540','631575')]),
 fact('AI-timer','confirmed',{'initialDelay':'AIConfig.DelayTime / 1000.0; absent config => float.MaxValue','initialTimer':0,'update':'if delay>0: delay-=delta; return. Otherwise timer-=delta; if timer<0: timer+=actionTime; AIGoToAction(campId, AI_id). At most one action per Update.','actionInterval':'pick one element of AIConfig.ActionTime, convert /1000; no config or empty array => float.MaxValue','actionCount':'RandomHelper.Random(1,AIConfig.ActionNum); absent config=>0','RandomHelper':'function1621 forwards lower and upper+1 into a virtual random method; inclusive upper is inferred from standard System.Random.Next contract'},[w('631256','631287'),w('90d6d3','90d748'),w('5e0bea','5e0c1a'),w('5e0db7','5e0ea3'),w('82a72','82a99')]),
 fact('AI-action-choice','confirmed',{'type0or1':'ConfigMgr.GetAIAction(AI_id,trunc(score),maxScore)','type2or3':'q = int(maxScore/5); score<q =>1; score<2q=>2; score<3q=>4; else=>3','otherType':'0','weightedConfigActionIds':{'Protect':1,'Defend':2,'Reinforce':4,'Occupy':3},'weightedEligibility':'score >= pair[0] * (maxScore/100.0); cumulative weight += pair[1]','weightedSelection':'RandomHelper.Random(0,last cumulative), first cumulative > sample; exact terminal equality does not match any entry'},[w('90da27','90db45'),w('5e0ca2','5e0d02'),w('1add55','1addda'),w('5e0d42','5e0db3')]),
 fact('level-table-access','confirmed',{'method':'GetLevelConfig(level) normalizes GetLevelRealID then queries ConfigMgr instance+120 (dicLevel). It does not query instance+124 (dicLevelB).','limitWrap':'if level>maxLevelNum: n=maxLevelNum-36; r=(level-maxLevelNum)%n; replace zero r with n; h=(n+1)/2 integer; if r<=h return 2*r+35 else return 2*(r-h)+36'},[w('21cd63','21cda9'),w('5e032e','5e03a6')]),
 fact('camera-adaptation','confirmed',{'aspect':'Screen.width/Screen.height','orthographicSize':'2.1 * (0.5625 / aspect)','defaultAspect':0.5625,'sceneScale':'ratio based correction applied to GameSceneMono field+32 Transform.localScale; wider-than-default uses 2*aspect*orthographicSize/2.5875'},[w('3913e2','391411'),w('391440','3914d1'),'python analysis/flow_api_names.py']),
]
facts += [
 fact('AI-source-and-target-order','confirmed',{'sources':'GetCampAllTowerNonArrow(camp): active camp-owned towers excluding ArrowTower','shuffle':'for i=0..Count-1: j=UnityEngine.Random.Range(0,Count); swap source[i],source[j] if unequal; whole list range each iteration','budget':'GetAIActionNum; if budget<=0 at next-source boundary, return','targetOrder':'No target distance or score sorting in AIGoToAction. Enumerates current incoming tower list for Protect/Defend; current GetStarAllLine physical-line list for Reinforce/Occupy. WayLineControl initializes the physical list sorted by LineLength ascending (independent asset_pipeline static proof); therefore Reinforce/Occupy prefer shortest eligible physical edges.','lineContains':'Outgoing exclusion uses List.Contains semantics: helper1209->5918 invokes index-search and compares !=-1.'},[w('631713','6318b5'),w('46f9e8','46faae'),w('1ff354','1ff3c7'),'controls-disassembly/__c-TnyuYV_-100665602.txt: comparer LineLength field+52; CoreProbe-function2297-2297.txt less=-1 greater=1']),
 fact('AI-protect','confirmed',{'action':1,'steps':['RemoveStarAllLine(source) removes source outgoing directions only; incoming connections survive.','GetAllTowerPointThis(source); if incoming.Count==0 return whole AIGoToAction.','For each incoming target: break if source.IsCanAddLine is false; skip same camp; otherwise AITryConnectLine(source,target). Its return is ignored.','After loop budget-- once; continue next source.'],'playerExclusion':'No AIType player-exclusion filter in this action.'},[w('6318d1','631bda'),'WayLineControl.RemoveStarAllLine function6780@0x270b18 -> WayLine.IsFromThisTower; asset_pipeline independent decode']),
 fact('AI-defend','confirmed',{'action':2,'preconditions':'source.IsCanAddLine and GetStarAllLine(source).Count>0; otherwise next source','steps':['Enumerate GetAllTowerPointThis(source) in list order.','Skip same camp, skip player-camp targets for AIType0 or2, skip targets already in outgoing list.','AITryConnectLine(source,target); ignore boolean result; budget-- for each attempt.','No inner budget/capacity recheck; budget can become negative before next-source boundary. Continue next source.']},[w('631be0','631f73')]),
 fact('AI-reinforce-and-occupy','confirmed',{'preconditions':'source.IsCanAddLine and at least one physical WayLine','commonFilter':'For every line get its opposite endpoint; skip absent endpoint and endpoint already in source outgoing list.','enemyFilter':'different camp; additionally AIType0/2 exclude player-camp targets','reinforce4':'Primary targets same camp. First AddActiveLine success decrements budget then RETURNS WHOLE AI CALL. If no success, only AIType2/3 fallback to enemyFilter; first fallback success decrements budget and continues next source.','occupy3':'Primary targets enemyFilter. First AddActiveLine success decrements budget then RETURNS WHOLE AI CALL. If no success, only AIType2/3 fallback to same-camp; first fallback success decrements budget and continues next source.','failedAttempts':'AddActiveLine failure does not consume budget; continue enumeration.','noEligibleTarget':'continue next source; no budget consumed.','loopEvidence':'flow_ai_trace.py annotates branch destinations; distinguishes whole-call return0x632d15 from next-source0x6317a5.'},[w('631f75','6326ff'),w('632701','632d15'),w('632278','6323e9'),w('632497','6326f3'),w('6329fd','632d15')]),
 fact('normal-level-file-mapping','confirmed',{'normal':'GetLevelConfig(requestedLevel) yields typed LevelConfig row: SceneId(+16) is file ID; id(+8) is level identity. Load Path.GetPath(Level_ + SceneId,4).','special':'If LevelControl.SpecialLevel(+24)!=0, uses supplied level directly as file ID.','maxLevelNum':'dicLevel.Count-1 (dictionary count minus free count minus1); 561 rows0..560 imply560','legacySceneIdColumns':'Current LevelConfig typed fields are id,LevelType,SceneId only; SceneId2..10 table columns are not represented.','sublevel':'callback payload contains path,rowId,SmallLevelIndex; no claim that old SceneId2..10 are used.'},[w('56a2d0','56a31a'),w('56a31c','56a748'),w('7c584f','7c5862'),'gameplay-symbols.json: LevelConfig fields']),
 fact('tower-transform-defaults','confirmed',{'rotation':'Tower function15519 initializes zero vector and calls StarInfoCfg.SetTransform with it, so tower root world Euler=(0,0,0); serialized angle ignored by this caller.','scale':'StarInfoCfg.SetTransform never reads scale; therefore absent serialized scale does not imply zero tower scale. Prefab/model initialization controls actual scale.','constructors':'StarInfoCfg and ObstacleInfoCfg constructors are no-op bodies (3 bytes); no explicit unit-scale default or nonzero angle default is installed by constructors.'},[w('725af9','725b1d'),w('29238a','29241f'),'StarInfoCfg..ctor and ObstacleInfoCfg..ctor in captured disassemblies']),
 fact('pause-and-update-gates','confirmed',{'gate':'LevelControl tower updates, WayLineControl simulation updates and AICampController updates each require state==Running(6).','pause':'OnGamePlayState common preamble calls GlobalData.PauseGame(state==7), forwarding changeTimeScale=true to GameFrameEntry.PauseGame; Time.timeScale=0 on Pause and1 for any non-Pause transition. Case7 also pauses audio.','running':'Running calls SetLevelSpeed(saved speed); SetLevelSpeed stores speed and calls UnityEngine.Time.set_timeScale.','towerDt':'LevelControl passes dt*ConfigMgr static+8 to active Tower virtual update slot18, second time argument unchanged.','lineDt':'WayLineControl dt multiplied by same ConfigMgr static+8, and movement further uses static+12.','order':'AICampController -> LevelControl (active towers and victory refresh) -> WayLineControl. MineGameMain registers them in this order and MineGameLogicModule.Update traverses the insertion list.'},[w('81f516','81f51e'),w('81f638','81f660'),w('6e2534','6e25ac'),w('90d816','90d826'),w('37a393','37a404'),w('1a33de','1a33ec'),w('37a032','37a039'),w('1a754b','1a7551'),w('5a1118','5a1127'),w('5516ee','5516fd'),w('55179c','5517ab'),w('55184a','551859'),w('82b54','82b63'),w('7f77f4','7f78d3'),'flow_pause_api.py resolves2762=UnityEngine.Time.set_timeScale,1821=UIAudioManager.get_Instance']),
 fact('retry-initial-score','confirmed',{'again':'Again(10): InitGameData clears active tower/soldier state, resets SmallLevelIndex0, enters Enter(3).','reinitialize':'Load callback creates/reuses towers and invokes Tower.Init; Tower.Init writes float(StarInfoCfg.StartScore) unconditionally. Retry thus restores serialized starting score, not surviving battle score.','clear':'InitGameData resets curBoss; clears camp active/counts; calls active tower virtual slot17; invokes Soldier.Clear(true) then soldier effect destruction.'},[w('37a510','37a555'),w('fc1f3','fc1f7'),w('fc49a','fc4d6'),w('fc674','fc68d'),w('fc836','fc876'),w('725c66','725c71')]),
 fact('camera-base-scale','confirmed',{'vector':[0.25,0,0.4000000059604645],'destination':'GameSceneMono field+32 Transform.localScale','ratio':'aspect<0.5625 uses0.5625/aspect; aspect==0.5625 uses1; aspect>0.5625 uses2*aspect*orthoSize/2.5875','qualification':'This is the specific scene object adjusted by SetCameraSize, not every tower root.'},[w('86533e','865361'),w('391429','3914d1')]),
]
facts += [fact('ordinary-wave-scope','inferred',{'observation':'Recovered ordinary level path creates the serialized tower set once. Recovered LevelControl.Updata only updates active towers and periodically refreshes camp totals; it contains no independent wave-spawn timer. AI acts through tower connections.','limit':'This supports no additional scheduled enemy waves for the selected ordinary slice. It is not a global absence proof across boss, commander, skill, or special mode code.'},[w('56ac0c','56acef'),w('81f516','81f736'),w('631633','632d15')])]
unknowns=[{'id':'levelB-channel-use','status':'unknown','plan':'Trace dicLevelB references across callers if alternate channel is required; observed GetLevelConfig directly uses dicLevel.'},{'id':'original-runtime-golden','status':'unknown','plan':'Compare original running level tower positions and one victory/defeat replay; all current findings are static verified, not live parity.'}]
levels=[]
for p in sorted((ROOT/'generated/levels').glob('*.json')):
 d=json.loads(p.read_text(encoding='utf-8-sig'))
 if 'StarInfoCfgs' in d:levels.append({'source':str(p.relative_to(ROOT)),'towers':[{'id':i+1,'worldPosition':{k:v/100 for k,v in t['pos'].items()},'campId':t['CampID'],'score':t['StartScore'],'shipId':t['ShipID']} for i,t in enumerate(d['StarInfoCfgs'])]})
out={'target':{'appid':'wxcf1394487200e48f','version':'43'},'method':'static metadata + WASM decode; no network or target-code execution','facts':facts,'unknowns':unknowns,'representativeLayouts':levels,'disassemblies':dis,'sourceHashes':{name:hashlib.sha256((ROOT/'generated/wasm'/name).read_bytes()).hexdigest() for name in ('wasmcode.wasm','wasmcode1.wasm')}}
(ROOT/'generated/flow-evidence.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# Flow / level evidence','', 'Target wxcf1394487200e48f / 43. Static evidence only.','', 'Reproduce: `python analysis/flow_evidence.py`. Decoder source: `analysis/flow_disassemble.py`. Every body is stored in generated/flow-evidence.json with exact byte offsets.','']
for f in facts:lines += ['## '+f['id']+' ['+f['status']+']','',json.dumps(f['value'],ensure_ascii=False,indent=2),'','Evidence: '+'; '.join(f['evidence']),'']
lines+=['## Remaining unknowns','',json.dumps(unknowns,ensure_ascii=False,indent=2),'','The first stdout attempt hit GBK UnicodeEncodeError on obfuscated symbols; decoder now explicitly writes UTF-8. PowerShell numeric @ selectors require single quotes. No source artifacts were modified.']
(ROOT/'FLOW_EVIDENCE.md').write_text('\n'.join(lines),encoding='utf-8')
print('wrote flow-evidence.json and FLOW_EVIDENCE.md',len(facts),'facts',len(dis),'bodies')
