from pathlib import Path
p=Path('analysis/flow_evidence.py')
s=p.read_text(encoding='utf-8')
s=s.replace("dis=[]", "selected += [('AICampController','AIGoToAction'),('LevelControl','GetCampAllTowerNonArrow'),('@9710',),('@5918',),('@11593',),('@11594',),('@11595',),('Path','.cctor'),('@15519',),('StarInfoCfg','.ctor'),('ObstacleInfoCfg','.ctor'),('LevelControl','InitGameData'),('LevelControl','SetLevelSpeed'),('AICampController','Updata'),('WayLineControl','Updata'),('GameControl','.cctor')]\ndis=[]")
s=s.replace("unknowns=[{'id':'ai-target-ranking','status':'unknown','plan':'Decode AICampController.AIGoToAction 0x631633,5965 bytes and its comparator closure methods; action categories/timing are recovered but target choice is not complete.'},", "unknowns=[")
s=s.replace("{'id':'camera-default-scene-scale','status':'unknown','plan':'Extract GameSceneMono field+32 original transform scale / GameControl static default vector from assets or cctor; do not assume unit scale.'},", "")
anchor="unknowns=["
extra='''facts += [
 fact('AI-source-and-target-order','confirmed',{'sources':'GetCampAllTowerNonArrow(camp): active camp-owned towers excluding ArrowTower','shuffle':'for i=0..Count-1: j=UnityEngine.Random.Range(0,Count); swap source[i],source[j] if unequal; whole list range each iteration','budget':'GetAIActionNum; if budget<=0 at next-source boundary, return','targetOrder':'No target distance or score sorting in AIGoToAction. Enumerates current incoming tower list for Protect/Defend; current GetStarAllLine physical-line list for Reinforce/Occupy. Ordering of physical list is a separate WayLineControl dependency.','lineContains':'Outgoing exclusion uses List.Contains semantics: helper1209->5918 invokes index-search and compares !=-1.'},[w('631713','6318b5'),w('46f9e8','46faae'),w('1ff354','1ff3c7')]),
 fact('AI-protect','confirmed',{'action':1,'steps':['RemoveStarAllLine(source) removes source outgoing directions only; incoming connections survive.','GetAllTowerPointThis(source); if incoming.Count==0 return whole AIGoToAction.','For each incoming target: break if source.IsCanAddLine is false; skip same camp; otherwise AITryConnectLine(source,target). Its return is ignored.','After loop budget-- once; continue next source.'],'playerExclusion':'No AIType player-exclusion filter in this action.'},[w('6318d1','631bda'),'WayLineControl.RemoveStarAllLine function6780@0x270b18 -> WayLine.IsFromThisTower; asset_pipeline independent decode']),
 fact('AI-defend','confirmed',{'action':2,'preconditions':'source.IsCanAddLine and GetStarAllLine(source).Count>0; otherwise next source','steps':['Enumerate GetAllTowerPointThis(source) in list order.','Skip same camp, skip player-camp targets for AIType0 or2, skip targets already in outgoing list.','AITryConnectLine(source,target); ignore boolean result; budget-- for each attempt.','No inner budget/capacity recheck; budget can become negative before next-source boundary. Continue next source.']},[w('631be0','631f73')]),
 fact('AI-reinforce-and-occupy','confirmed',{'preconditions':'source.IsCanAddLine and at least one physical WayLine','commonFilter':'For every line get its opposite endpoint; skip absent endpoint and endpoint already in source outgoing list.','enemyFilter':'different camp; additionally AIType0/2 exclude player-camp targets','reinforce4':'Primary targets same camp. First AddActiveLine success decrements budget then RETURNS WHOLE AI CALL. If no success, only AIType2/3 fallback to enemyFilter; first fallback success decrements budget and continues next source.','occupy3':'Primary targets enemyFilter. First AddActiveLine success decrements budget then RETURNS WHOLE AI CALL. If no success, only AIType2/3 fallback to same-camp; first fallback success decrements budget and continues next source.','failedAttempts':'AddActiveLine failure does not consume budget; continue enumeration.','noEligibleTarget':'continue next source; no budget consumed.','loopEvidence':'flow_ai_trace.py annotates branch destinations; distinguishes whole-call return0x632d15 from next-source0x6317a5.'},[w('631f75','6326ff'),w('632701','632d15'),w('632278','6323e9'),w('632497','6326f3'),w('6329fd','632d15')]),
 fact('normal-level-file-mapping','confirmed',{'normal':'GetLevelConfig(requestedLevel) yields typed LevelConfig row: SceneId(+16) is file ID; id(+8) is level identity. Load Path.GetPath(Level_ + SceneId,4).','special':'If LevelControl.SpecialLevel(+24)!=0, uses supplied level directly as file ID.','maxLevelNum':'dicLevel.Count-1 (dictionary count minus free count minus1); 561 rows0..560 imply560','legacySceneIdColumns':'Current LevelConfig typed fields are id,LevelType,SceneId only; SceneId2..10 table columns are not represented.','sublevel':'callback payload contains path,rowId,SmallLevelIndex; no claim that old SceneId2..10 are used.'},[w('56a2d0','56a31a'),w('56a31c','56a748'),w('7c584f','7c5862'),'gameplay-symbols.json: LevelConfig fields']),
 fact('tower-transform-defaults','confirmed',{'rotation':'Tower function15519 initializes zero vector and calls StarInfoCfg.SetTransform with it, so tower root world Euler=(0,0,0); serialized angle ignored by this caller.','scale':'StarInfoCfg.SetTransform never reads scale; therefore absent serialized scale does not imply zero tower scale. Prefab/model initialization controls actual scale.','constructors':'StarInfoCfg and ObstacleInfoCfg constructors are no-op bodies (3 bytes); no explicit unit-scale default or nonzero angle default is installed by constructors.'},[w('725af9','725b1d'),w('29238a','29241f'),'StarInfoCfg..ctor and ObstacleInfoCfg..ctor in captured disassemblies']),
 fact('pause-and-update-gates','confirmed',{'gate':'LevelControl tower updates, WayLineControl simulation updates and AICampController updates each require state==Running(6).','pause':'OnGamePlayState Pause(7) calls audio virtual pause(true). This branch does not set Time.timeScale=0.','running':'Running calls SetLevelSpeed(saved speed); SetLevelSpeed stores speed and calls UnityEngine.Time.set_timeScale.','towerDt':'LevelControl passes dt*ConfigMgr static+8 to active Tower virtual update slot18, second time argument unchanged.','lineDt':'WayLineControl dt multiplied by same ConfigMgr static+8, and movement further uses static+12.','order':'Relative controller scheduling order not yet resolved.'},[w('81f516','81f51e'),w('81f638','81f660'),w('6e2534','6e25ac'),w('90d816','90d826'),w('37a393','37a404'),w('1a33de','1a33ec'),'flow_pause_api.py resolves2762=UnityEngine.Time.set_timeScale,1821=UIAudioManager.get_Instance']),
 fact('retry-initial-score','confirmed',{'again':'Again(10): InitGameData clears active tower/soldier state, resets SmallLevelIndex0, enters Enter(3).','reinitialize':'Load callback creates/reuses towers and invokes Tower.Init; Tower.Init writes float(StarInfoCfg.StartScore) unconditionally. Retry thus restores serialized starting score, not surviving battle score.','clear':'InitGameData resets curBoss; clears camp active/counts; calls active tower virtual slot17; invokes Soldier.Clear(true) then soldier effect destruction.'},[w('37a510','37a555'),w('fc1f3','fc1f7'),w('fc49a','fc4d6'),w('fc674','fc68d'),w('fc836','fc876'),w('725c66','725c71')]),
 fact('camera-base-scale','confirmed',{'vector':[0.25,0,0.4000000059604645],'destination':'GameSceneMono field+32 Transform.localScale','ratio':'aspect<0.5625 uses0.5625/aspect; aspect==0.5625 uses1; aspect>0.5625 uses2*aspect*orthoSize/2.5875','qualification':'This is the specific scene object adjusted by SetCameraSize, not every tower root.'},[w('86533e','865361'),w('391429','3914d1')]),
]
'''
s=s.replace(anchor,extra+anchor)
p.write_text(s,encoding='utf-8')
