"""Emit typed serializable fields from original IL2CPP metadata, never from guessed JSON types."""
from pathlib import Path
import json,struct,re
p=Path('analysis/recover_outgame_manager_registry.py');n={'__file__':str(p.resolve())};exec(p.read_text(encoding='utf8').split('rows=[]')[0],n)
u,mem,b,pairs,ts,ms=[n[k] for k in ['u','mem','b','pairs','ts','ms']]
out=n['p']/'generated/outgame';roster=json.loads((out/'CONFIG_INITIALIZATION_ROSTER.json').read_text(encoding='utf8'));pending={r['sourceTypeIndex'] for r in roster['rows']};done={};tabletypes={r['sourceTypeIndex']:r for r in roster['rows'] if r['kind']=='table'}
def type_name(ptr):
 data,bits=struct.unpack_from('<II',mem,ptr);code=bits>>16&255
 primitives={2:'bool',8:'int',12:'float',13:'double',14:'string'}
 if code in primitives:return primitives[code]
 if code==29:return type_name(data)+'[]'
 if code==18:pending.add(data);return ms(ts[data][0])
 if code==21:
  definition,inst=struct.unpack_from('<II',mem,data);assert ms(ts[u(definition)][0])=='List`1'
  count,args=struct.unpack_from('<II',mem,inst);assert count==1
  return 'List<'+type_name(u(args))+'>'
 raise ValueError((code,data))
while pending:
 tid=pending.pop()
 if tid in done:continue
 name=ms(ts[tid][0]);assert name.isidentifier();fields=[]
 for j in range(ts[tid][18]):
  index=ts[tid][8]+j;fname,ftype,token=struct.unpack_from('<3i',b,pairs[11][0]+12*index);ptr=u(200288+4*ftype);attrs=u(ptr+4)&65535;assert attrs&7==6 and not attrs&16,(name,ms(fname),attrs)
  fields.append(dict(name=ms(fname),type=type_name(ptr),offset=u(u(3823136+4*tid)+4*j)))
 key=None
 if tid in tabletypes:
  getter=(out/tabletypes[tid]['uniqueIdMethods'][0]['path']).read_text(encoding='utf8');offsets=re.findall(r'local.get \[0\]\n\w+\s+i32.load \[2, (\d+)\]',getter);assert offsets==['8'] and 'call [910]' in getter
  key=next(f['name'] for f in fields if f['offset']==8);assert next(f['type'] for f in fields if f['name']==key)=='int'
 done[tid]=dict(name=name,fields=fields,key=key)
lines=['// Generated by analysis/generate_original_config_schemas.py from original metadata.', 'using System;','using System.Collections.Generic;','namespace AreaBattle.OriginalConfig','{']
for tid,row in sorted(done.items()):
 lines+=['    // Original type '+str(tid),'    [Serializable] public sealed class '+row['name']+(' : IOutgameConfigRow' if row['key'] else ''),'    {']
 lines+=['        public '+f['type']+' @'+f['name']+';' for f in row['fields']]
 if row['key']:lines+=['        public object UniqueID => @'+row['key']+';']
 lines+=['    }']
lines+=['}'];Path('UnityProject/Assets/AreaBattle/Scripts/OutgameOriginalConfigSchemas.cs').write_text('\n'.join(lines)+'\n',encoding='utf8')
(out/'CONFIG_SCHEMA_GENERATION.json').write_text(json.dumps(dict(types=done,source='original metadata v31 and 58 UniqueID getter bodies',qualification='Public declared fields preserved; unrelated JSON fields are not invented as runtime fields'),ensure_ascii=False,indent=2)+'\n',encoding='utf8');print('Generated',len(done),'types')
