"""Emit bounded source-backed GuideUI presentation evidence without altering baseline."""
from pathlib import Path
import hashlib,json,struct
G=Path(__file__).parent/'targets/wxcf1394487200e48f/43/generated'
S=G/'resource-snapshots/hud-soldier300-20260928/guide-spine'
read=lambda p:json.loads(p.read_text(encoding='utf8'))
hashfile=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
source=read(G/'guide-evidence.json')
settings=G/'unity-assets/MonoBehaviour/DOTweenSettings__resources.bin'
b=settings.read_bytes()
assert struct.unpack_from('<i',b,0x6c)[0]==6 and struct.unpack_from('<i',b,0x7c)[0]==0
spine=read(S/'YD.txt');manifest=read(S/'native/native-import.json')
assert spine['skeleton']['spine']=='4.1.16'
functions=[{'function':f['function'],'method':f['method'],'module':f['module'],'offset':hex(f['body']['offset']),'size':f['body']['size']} for f in source['functions'] if f['function'] in (6006,7740,11888,19274,19276,19287,19288,19289)]
d={
 'target':'wxcf1394487200e48f/43','status':'source-confirmed; runtime checks separate',
 'spine':{'sourceComponent':'CAB-71a96badbcffab7b7451a783f271bc4b:-6083250585791921037','version':'4.1.16','animation':'YD','loop':True,'duration':1.5333,'bones':len(spine['bones']),'slots':len(spine['slots']),'attachmentCount':47,'localPosition':[-1.07000005,-37.7199936,0],'localScale':[100,100,1],'layer':5,'sourceHashes':{x['name']:x['sha256'] for x in read(S/'spine-sources.json')},'resourceCount':len(manifest['resources']),'preparedManifest':str(S/'native/native-import.json')},
 'lifecycle':{'Awake':'f19289 disables YD_0 then calls ShowUI. ShowUI f7740 stage1 activates YD_0 and disables guideIcon Image. No general else/deactivate branch; preserve activation on subsequent popups of same UI instance.','popup':'ShowUI mainbg/imageBg true and guideHand false; OnOK f11888 sets these popup roots false. GuideUI root remains during gameplay guide, so hand must not be parented under mainbg.','clock':'SkeletonAnimation source updateTiming1/unscaledTimefalse/timeScale1; explicit scaled clock invokes official runtime Update/LateUpdate with automatic component disabled. Original animation/atlas/material data preserved.','dispose':'f19288 kills existing tween, removes listeners/timers and clears guide state.'},
 'hand':{'componentBinding':'GuideUI.InitializeComponent f19287 offset148 -> guideHand Image; offset160 -> YD_0 GameObject','connect':{'start':'source TowerUI canvas world position - Vector3.up','end':'target TowerUI canvas world position - Vector3.up','duration':2,'loops':2147483647},'cut':{'points':'rotate connect endpoints -90 degrees about their midpoint around Vector3.forward','duration':2,'loops':2147483647},'skillPulse':{'stages':[9,10],'start':'SkillItem slot0/1 world position','property':'Transform.localScale','target':[1.2,1.2,1.2],'duration':1,'loops':15,'completion':'deactivate hand'},'skillDrag':{'stage':11,'start':'SkillItem slot2 world position','end':'GetEndPosInSkill -> TowerUI canvas world position - Vector3.up','duration':2,'loops':15,'completion':'deactivate hand','noTarget':'deactivate when original target point is zero'},'tweenDefaults':{'ease':'OutQuad','loopType':'Restart','scaled':True,'binary':str(settings),'sha256':hashfile(settings),'offsets':{'defaultUpdateType':'0x64 = 0 Normal','defaultTimeScaleIndependent':'0x68 = false','defaultEaseType':'0x6c = 6 OutQuad','defaultLoopType':'0x7c = 0 Restart'},'mapping':'IL2CPP DOTweenSettings type14796 field order43027..43055 matches original serialized field sequence; official public DOTweenSettings defines enum fields. f5573→f9972 SetLoops(int) only sets count, not loopType.','primaryReferences':['https://raw.githubusercontent.com/Demigiant/dotween/develop/_DOTween.Assembly/DOTween/Core/DOTweenSettings.cs','https://raw.githubusercontent.com/Demigiant/dotween/develop/_DOTween.Assembly/DOTween/DOTween.cs']},'sourceHelpers':str(G/'guide-presentation-tween-helpers.json')},
 'popupText':{'correction':'The earlier name PersistentTip described the local adapter, not original visibility. Original textTipAdd belongs to mainbg and appears during the prompt only. No reparenting is performed.','source':'TextGuideLogic.Start f15651 subscribes GuideMessage+0 to show f15649 and +4 to clear/hide f15652. GuideUI.ShowUI f7740 fires +0 at0x38b369; OnOK f11888 fires +4 at0x58bd25.','alignment':'Text.set_alignment token0x06000474 resolves to wasmcode f3259. TextGuideLogic virtual default returns4=MiddleCenter; Guide_TowerAttack/Defense override returns3=MiddleLeft.','stages':[6,7,8,9,10,11,12],'Pitch':'f7740@0x38b192-0x38b28c enables guideContent.child0 only stage7/8, splits GuideConfig.param on semicolon, assigns child[i].child2 Text, and clears guideContent Text. Stage7 param2;2;1;2, stage8 param2;2;2;1. OnOK hides the Pitch child.'},
 'functions':functions,
 'implementation':{'runtime':'UnityProject/Assets/AreaBattle/Scripts/RecoveredGuidePresentation.cs','importer':'UnityProject/Assets/AreaBattle/Editor/RecoveredGuideSpineImporter.cs','probe':'UnityProject/Assets/AreaBattle/Editor/GuidePresentationProbe.cs','probeResult':'analysis/guide-presentation-probe.json','scope':'Official Spine runtime only; original custom game executable behaviours excluded. Guide decisions remain production BattleGuide.'},
 'unknowns':['Matched original-game screenshots and rendered-frame timing alignment remain unaccepted.','Precise relative ordering of original DOTween, guide events and rendering inside one frame remains unestablished.']
}
(G/'guide-presentation-evidence.json').write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')
print('guide presentation evidence written')
