"""Publish verified first-three-level guide rules without executing game code."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).parent/'targets/wxcf1394487200e48f/43'
path=ROOT/'generated/guide-evidence.json'
r=json.loads(path.read_text(encoding='utf8'))
funcs={f['function']:f for f in r['functions']}
def ev(fn,*offsets):
    f=funcs[fn]
    for off in offsets:assert any(x.startswith(off+' ') for x in f['disassembly']),(fn,off)
    return {'module':f['module'],'function':fn,'token':f['token'],'method':f['class']+'.'+f['method'],'body':f['body'],'instructionOffsets':list(offsets)}
def rule(id,text,evidence,**extra):return dict(id=id,status='confirmed-static',rule=text,evidence=evidence,**extra)
tables=ROOT/'generated/tables'
cfg=json.loads((tables/'GuideConfig.json').read_text(encoding='utf8'))['Datas']
rows=[x for x in cfg if x['id'] in range(1,7)]
langs={x['id']:x for x in json.loads((tables/'LanguageConfig.json').read_text(encoding='utf8'))['Datas']}
keys={x[k] for x in rows for k in ('title','explain','button') if x[k]}|{'GuideUI.tipAdd.max'}
r.update(analysisMode='static-only; no target code execution',scope='First three zero-based levels: 0,1,2; their first small-level branch',implementationGate='first-three guide mechanics statically supported; live input/timing/visual acceptance not performed',configRows=rows,localization={k:langs[k]['zh_cn'] for k in sorted(keys)},helperIdentities=[
 {'assembly':'UnityEngine.CoreModule.dll','function':949,'tableIndex':2416,'method':'GameObject.SetActive','nativeLiteral':'UnityEngine.GameObject::SetActive(System.Boolean)'},
 {'assembly':'GFRunning.dll','function':10103,'method':'TimeModule.AddLoopTimer','parameters':['LoopSteepTime','LoopTimeCompleteCallBack','AutoPaly','UseTimeScale']},
 {'assembly':'GFRunning.dll','function':7029,'method':'TimeHelper.Delay'},
 {'assembly':'DOTween.dll','function':3531,'method':'ShortcutExtensions.DOMove'}])
r['rules']=[
 rule('guide-entry','ConfigMgr.IsGuideLv reads LevelConfig.LevelType[min(SmallLevelIndex,Length-1)] == 1. Levels 0,1,2 have [1,0,0]. GetGuideId finds GuideConfig guildLv==CurLevel AND guildsmallLv==SmallLevelIndex; initial stages are 1,4,5 respectively. EnterNextStage advances by nextGuildStage, maps -1/missing to13, and closes GuideUI/restores playState6 if no config or stage13. It does not check whether user has previously acknowledged these first-three prompts.',[ev(8085,'003a957a'),ev(12792,'005e08eb','005e0999'),ev(4406,'001647b7','00164850','001648b8')]),
 rule('guide-popup','ShowUI pauses running battle by playState6->7, shows original title/explain/picture/button from config, sets one-second OK countdown and disables the button. Completion restores original button label and interaction. OnOK hides popup, sets playState6, emits GuideMessage+4 then dispatches stage action. For existing GuideUI, empty title auto-invokes OnOK; stage2 therefore skips the visible prompt. No extra invented skip button or persisted unlock condition.',[ev(7740,'0038b28d','0038b2ef','0038b34d'),ev(19280,'0083f962'),ev(11888,'0058bd25','0058bd5d'),ev(4406,'001649b1')]),
 rule('stage1-select','On stage1 OK, take first tower from LevelControl.GetCampAllTower(playerCamp). Retrieve its complete potential adjacency, collect opposite endpoints in adjacency order, choose endpoint with greatest GameObject transform world Z (initial threshold -100; replace only strict greater). For every collected neighbor set its tower GameObject and tower-UI GameObject active iff that neighbor is selected endpoint. This does not mutate Tower.IsActive or remove candidates from the simulation. Other non-neighbor towers are untouched.',[ev(11897,'0058d42d','0058d455','0058d63c','0058d6cf','0058d80e','0058d853')],selection={'source':'playerCampTowers[0]','target':'argmaxStrict(worldZ) over source potential neighbors','tie':'first in adjacency order'}),
 rule('stage1-input-and-progress','LineAdd event hides hand and sets WayLineControl.CanDraw=false only during stage1 or stage5. Stage1 does NOT advance on connection. GuideUI listens to Event.StarOccupy (static offset28); when current stage1 it schedules GuideCanDrawLine. That delay is float32 0.699999988079071; callback first enables CanDraw then calls EnterNextStage. Callback does not check captured tower identity or current stage again.',[ev(19754,'00870388','008703de'),ev(7739,'0038ab15','0038ab87'),ev(19274,'0083f73c','0083f74f','0083f774'),ev(19282,'0083f9ba'),ev(6007),ev(19294,'0083ff84','0083ff8c')],delaySeconds=0.699999988079071),
 rule('stage2-cut','Stage2 uses the previous source/target guide positions, rotates both around their midpoint by -90 degrees about Vector3.forward (0,0,1) to display a cross-line swipe. A LineCut event while stage2 immediately sets CanDraw=false and sends SetGuideActive(false), reactivates all stored neighbor tower GameObjects and tower-UI GameObjects, then schedules the same0.7s unlock+next-stage transition. No endpoint identity test exists inside OnLineCutEvent.',[ev(11887,'0058b45f'),ev(19754,'008703b3'),ev(19273,'0083f700'),ev(11895,'0058c508','0058c51a','0058c560','0058c648','0058c683','0058c722')]),
 rule('stage3-and4-exit','Stage3 victory-objective popup and stage4 camp popup OK both invoke inherited UI close virtual slot15. Dispose kills hand tween, removes timers/listeners, and ClearState sets config/source/target=null, stage0, clears stored neighbor and candidate-line lists, and zeroes stored positions. They do not require another connection or victory to dismiss their prompt.',[ev(11887),ev(19288,'0083fd0f','0083fd36','0083fd46'),ev(11899,'0058e0bc','0058e0c8','0058e100','0058e127')]),
 rule('stage5-disable-growth','On stage5 OK, SetTowerUpgradeStage writes Tower.IsAutoAddScore(+40)=false for every active tower. Growth remains disabled after target reaches max: OnStarMaxScore only restores GameObjects and schedules the next stage; ClearState also never writes this flag. Do not automatically re-enable regeneration at stage6.',[ev(11893),ev(11894),ev(11899)],relatedEvidence='combat-evidence.json: tower-basic-fields/regeneration'),
 rule('stage5-select','GetStartAndEndInUpgrade starts with first player tower then replaces source for every other player tower whose trunc(score) >= trunc(currentSource.score), so maximum with ties choosing last. It appends opposite endpoints of source adjacency to endGuideList, chooses endGuideList[0] as target (nearest from confirmed adjacency length sort), then appends opposite endpoints of target adjacency to same list. For each entry, tower and UI GameObjects remain active iff entry is source or target; all others in this list are deactivated. No camp filter or dedup is applied to that collected list.',[ev(11896,'0058c88f','0058ca1e','0058ca25','0058ccee','0058ce96','0058d078','0058d0cd')],selection={'source':'max trunc(score) in playerCampTowers, last wins ties','target':'first opposite endpoint of source sorted adjacency','visibility':'collected source-neighbors + target-neighbors: only chosen source/target active'}),
 rule('stage5-input-and-completion','Existing controls touch-down special gate: if CurLevel==2 AND guideStage==5 AND trunc(source.score)<source.maxScore, clear selected source. Ordinary capacity/camp/physics checks still apply. Successful LineAdd disables input/hides hand as in stage1. AddLoopTime registers TimeModule.AddLoopTimer(1,OnStarMaxScore,true,false); poll checks trunc(tower_end.score)>=tower_end.maxScore, independent of event payload/currentStage. On success restore all collected GameObjects, schedule0.7s unlock+EnterNextStage and remove that loop timer. There is no forced score assignment in guide code.',[ev(19274),ev(19278,'0083f8cd','0083f8d7'),ev(19286,'0083fb36'),ev(11894,'0058c258','0058c340','0058c37b','0058c41a','0058c427'),ev(10103),ev(7025)],inputEvidence='controls-evidence.json; WayLineControl token100665576/function14747',poll={'LoopSteepTime':1,'AutoPaly':True,'UseTimeScale':False,'comparison':'>=','resetAccumulatorToZero':True}),
 rule('stage6-free-battle','At stage6 enter, GuideLogicControl creates Guide_TowerMax, configured text key GuideUI.tipAdd.max=全军出击. Stage6 OK hides popup, restores playState6 and emits GuideMessage+4 so TextGuideLogic shows this tip; stage action switch maps stage6 to its no-op exit. It does NOT immediately close GuideUI, clear stage or require another connection. Input was unlocked by delayed callback before the stage6 popup; normal modal pause applies until OK. Keep guideStage6 until normal GuideUI lifecycle disposal.',[ev(11891,'0058beb7','0058bf20'),ev(11880,'0058b16c'),ev(15651,'0072fb10','0072fb38'),ev(15649,'0072f95f'),ev(11888,'0058bd25'),ev(11887,'0058b37f')]),
 rule('guide-hand-only','GuideUI hand tween places Transform at first guide point and calls DOMove(second,2.0,false), repeating2147483647 times. Guide functions contain no WayLine.SetLineState/AddActiveLine call for these stages. The hand is a visual instruction, not automated player input. Potential adjacency construction is not an active line.',[ev(6006,'002042f1','00204348','00204351','00204354')],automaticLineCreation='not present in inspected guide functions; do not synthesize one'),
 rule('guide-timer-kernel','Resolved AddLoopTimer overload stores LoopSteepTime int1 at timer+12, UseTimeScale=false at+22, enables AutoPlay. Timer AddTimes accumulates deltaTime or unscaledDeltaTime according to+22; unscaled delta>1 is ignored. Check fires once at accumulator>=float(LoopSteepTime), clears accumulator to0 (does not carry remainder) then calls callback with step int. The guide poll therefore uses unscaled1.0 timer units and no catch-up loop.',[ev(10103),ev(7025,'0028cdfd','0028ce12'),ev(14988,'006f5117','006f5128','006f5136'),ev(14987,'006f50aa','006f50b3','006f50cb')])
]
r['rules'].append(rule('guide-delay-scaled-and-adjacency-alias', 'TimeHelper.Delay async MoveNext f9901 allocates UnityEngine.WaitForSeconds(duration), proving scaled time. GuideControl stores GetStarAllLine result directly at+28 without copying; ClearState calls List.Clear on that same object. Thus stage3 disposal clears source adjacency; stage6 disposal clears target adjacency, while WayLine entities remain in the global list.',[ev(9901,'0048928b','004892c4'),ev(11897,'0058d457','0058d45a'),ev(11896,'0058cd08','0058cd0b'),ev(11899,'0058e127')]))
r['stateMachines']=[
 {'level':0,'startStage':1,'steps':[{'stage':1,'onOK':'select source/target and show hand','onLineAdd':'CanDraw=false; hide hand','onStarOccupy':'delay0.7 -> CanDraw=true -> stage2'},{'stage':2,'onEnter':'empty-title autoOK; show cut hand','onLineCut':'CanDraw=false; hide hand; restore neighbors; delay0.7 -> stage3'},{'stage':3,'onOK':'playState6; CloseGuideUI; Dispose clears stage0'}]},
 {'level':1,'startStage':4,'steps':[{'stage':4,'onOK':'playState6; CloseGuideUI; Dispose clears stage0'}]},
 {'level':2,'startStage':5,'steps':[{'stage':5,'onOK':'stop active towers natural regeneration; select donor/nearest target; hide other collected neighbors; show hand; start unscaled1 loop','onLineAdd':'CanDraw=false; hide hand','onTargetMax':'restore neighbor GameObjects; stop loop; delay0.7 -> CanDraw=true -> stage6'},{'stage':6,'onOK':'playState6; show original 全军出击 tip; no immediate Close/clear'}]}
]
r['unknowns']=[
 {'id':'live-tutorial-capture','blocking':'visual-and-runtime-acceptance','unknown':'No live first-three tutorial recording/input trace. Static constraints and native Unity collider interaction still need end-to-end tests.'},
 {'id':'external-automatic-links','blocking':False,'unknown':'No automatic active-line creation exists in inspected GuideControl/GuideUI; root/flow analysis likewise found none in loader. This is bounded static absence, not a live behavior claim.'},
 {'id':'guide-world-points','blocking':'exact-presentation','unknown':'Hand points use TowerUI GameObject world position minus Vector3 static offset24 (Vector3.up, 0,1,0); original camera/UI world conversion and prefab hand size need live presentation comparison.'}
]
r['sourceHashes']={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [ROOT/'generated/wasm/wasmcode.wasm',ROOT/'work/webdata/Il2CppData/Metadata/global-metadata.dat',tables/'GuideConfig.json',tables/'LanguageConfig.json',tables/'LevelConfig.json']}
r['validation']={'instructionReferencesChecked':sum(len(e['instructionOffsets']) for q in r['rules'] for e in q['evidence']),'functionsDecoded':len(r['functions']),'status':'static-references-pass','targetRuntimeExecuted':False}
path.write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf8')
lines=['# First-three tutorial evidence','',r['scope'],'','All conclusions are static. Original functions and offsets are embedded in guide-evidence.json.','']
for q in r['rules']:lines += ['## '+q['id'],'',q['rule'],'','Evidence: '+', '.join(f"f{e['function']} {e['method']}" for e in q['evidence']), '']
lines += ['## Original text','']+[f'- `{k}`: {r["localization"][k]}' for k in sorted(keys)]
lines += ['','## Limits','']+[f'- {x["id"]}: {x["unknown"]}' for x in r['unknowns']]
(ROOT/'generated/GUIDE_EVIDENCE.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
print(json.dumps(r['validation']))
