from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==545 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type10741-'+str(i)+'.txt' for i in range(74403,74432)]+['disassembly/Type10740-74434.txt','video-button-generics.json','video-button-virtual-slots.json','ui-import.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='native-video-button';s['validation'].update(integratedChecksPassed=545,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['native-video-button']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameVideoButton.cs','OutgameVideoClick.cs','OutgameVideoButtonCompletion.cs'],'scope':'Native Unity Button subclass restores source data lookup/lock, state, readiness, audio, reports, click and completion. Requires binding while inactive before activation. Original shop prefab IDs verified but page import/composition and real SDK/report host remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='UIVideoBtn native configuration and reporting source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Native video Button callbacks, configuration/state/report ordering and explicit SDK fixture','checksPassed':545,'outgameChecksPassed':278,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'freshPlayModeRun':False,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'native_button_verified_shop_composition_and_sdk_pending','source':sources,'verified':['Original data/report override lock preserves existing data even when videoID changes','Native Button.OnPointerClick runs between video click event and play report; interactability only suppresses base callback','SDK completion fixture reaches success report, per-flag event names and original UnityEvent listeners','Success transport uses override parameters; event label uses original data','Manual showType0 readiness path uses SDK15 refresh=true; delayed path refresh=false','TrackVideo succeeds before report-state mutation','SetButtonState2 does not activate object; base SetGay and CustomizeReport are empty','Source ShopUI IDs: btn_addGold1001, btn_addDiamond1006; AutoCallBtnShowtrue'],'remaining':['Bind native components into original page import and account composition','VideoBtnManager configuration and concrete SDK/report host','Actual Start/OnEnable scaled coroutine PlayMode evidence for new class','Full persistence/build/E2E'],'checks':545,'priorPlaymodeChecks':8,'dynamicScope':'Native Unity Button editor checks with SDK result fixture; prior8 fly PlayMode checks not rerun'}
write(o/'NATIVE_VIDEO_BUTTON_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Native OutgameVideoButton implements original configuration/state/report/click flow against explicit SDK host. Native callbacks validated; original ShopUI videoIDs1001/1006 identified. Page composition and real SDK integration remain pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## 原生视频Button组件（545项）\n新增OutgameVideoButton继承Unity Button，恢复配置读取/锁定、重设ID、显示状态、音效、上报、回调及原生点击事件顺序。显式宿主提供SDK和上报接口，需在页面激活前绑定。验证普通Button不可交互仅抑制其自身onClick，原视频逻辑仍请求广告；成功上报使用覆盖参数，而分类事件仍使用原配置ReportLable；TrackVideo失败不推进报告状态。解析成功事件switch表，确认ShopUI金币videoID1001/钻石1006及AutoCallBtnShow。545项集成通过（关外278项），Unity退出0；此前8项飞币PlayMode未重跑。新组件OnEnable/Start动态流程、原页面组件接入、VideoBtnManager、真实SDK及完整账号菜单构建仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameNativeVideoButton','--result','pass','--evidence','545 integrated checks; prior8 PlayMode checks not rerun. Native shop composition, ad platform and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded545; full goal active.')
