from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==522
play=read(w/'analysis/outgame-fly-playmode-validation.json');assert play['passed'] and len(play['checks'])==8
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-runtime-playmode';s['validation'].update(integratedChecksPassed=522,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-runtime-playmode']={'implementationReady':True,'productionConnected':False,'source':['FLY_RUNTIME_AUDIT.json'],'implementation':['OutgameFlyRuntime.cs','OutgameFlyTweenRunner.cs','OutgameFlyToolAnimation.cs'],'validation':'analysis/outgame-fly-playmode-validation.json','scope':'Actual Play Mode with native prefab pool fixture and isolated inventory: simultaneous gold/diamond grants, unscaled movement/collection/cleanup at timeScale0. Original pool and page/account integration still pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Actual isolated fly runtime Play Mode') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Actual isolated fly runtime Play Mode','checksPassed':522,'outgameChecksPassed':255,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Actual Unity Play Mode successfully ran simultaneous gold/diamond effects at timeScale0. Ten original prefabs spawned/returned, native labels reached150/27, callbacks2, saves2 only, active effects and pending cleanup0. Explicit pool fixture, not original NormalPool.','validation':'analysis/outgame-fly-playmode-validation.json'});write(p,audit)
p=o/'FLY_RUNTIME_PLAYMODE_AUDIT.json';write(p,{'status':'isolated_real_playmode_passed_original_pool_page_pending','integratedChecks':522,'playmodeChecks':8,'report':'analysis/outgame-fly-playmode-validation.json','runtimeFrames':play['frames'],'editorPolls':play['polls'],'elapsedRealtime':play['elapsed'],'scaledElapsed':play['scaledElapsed'],'verified':play['checks'],'harnessRecovery':'First delayed startup callback was interrupted by editor shortcut preference access exception. Replaced delayCall startup with direct EnteredPlayMode callback; successful runs exited0. Unrelated shortcut preference warning still logged. No editor preferences modified.','limits':['Pool is an explicit instantiate/deactivate fixture, not recovered NormalPool','Audio is a fixture; no platform/ad/account access','This is actual dynamic execution, not matched screenshot/recording visual validation','Full lobby/build/end-to-end objective remains incomplete']})
p=w/'analysis/VALIDATION_MANIFEST.json';manifest=read(p);manifest['latestValidation']['playModeReport']='analysis/outgame-fly-playmode-validation.json';manifest['latestValidation']['playModeChecksPassed']=8;write(p,manifest)
note='\n\n## 飞行动效真实Play Mode验证（522项机械检查 + 独立8项动态检查）\n新增隔离批处理OutgameFlyPlayModeValidation，直接进入Unity Play Mode，真实协程/Update/Tween与恢复Prefab在timeScale=0下运行金币+钻石两路奖励。10个图标全部回收，真实Text到150/27，两次完成回调，库存只启动时保存2次；结束时活动动效和待清理均0。动态报告passed、Unity退出0，原522项机械检查计数不冒充增加为530。首轮因编辑器快捷键偏好权限异常打断delayCall，已改直接EnteredPlayMode启动并成功重跑；没有改用户偏好。池仍是明确的实例化/停用夹具，音频也是夹具，不代表原NormalPool、平台、账号或整页已恢复；未做匹配截图或新Player构建。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyRuntimePlayMode','--result','pass','--evidence','522 integrated checks; 522 integrated checks plus8 separate actual Play Mode checks; unscaled dual effects and cleanup verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded522; full goal remains active.')
