from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==447
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-notifications';s['validation'].update(integratedChecksPassed=447,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-notifications']={'implementationReady':True,'productionConnected':False,'source':['ad-notify-listener-slots.json','disassembly/Type7488-54683.txt','disassembly/Type7488-54684.txt','disassembly/Type7488-54686.txt','disassembly/Type7488-54688.txt','disassembly/Type7488-54690.txt'],'implementation':['OutgameAdNotifications.cs'],'scope':'Stateful request success/fail, shown, close and rewarded notifications restored with original listener/timer/report ordering and reentrancy. Click/show-error notification and concrete native/listener wiring pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original adapter notification state transitions and listener ordering') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original adapter notification state transitions and listener ordering','checksPassed':447,'outgameChecksPassed':180,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'DAUAdsAdapter notify success/fail/show/close/reward restored sharing adapter state; interface7534 slots0/1/2/5/6 resolved. Source function4475 is stopLoadTimeout for metadata54676 despite duplicate-name annotation. Success state2 then stop-load/report/listener, rereads cache/busy and may clear then state3/fail or start show. Shown only state2, close suppresses only state5, reward no dedup.447 checks pass; native/listener production connection incomplete.','source':['ad-notify-listener-slots.json','disassembly/Type7488-54684.txt'],'implementation':'OutgameAdNotifications.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 适配器状态通知与监听器顺序（447项）\n新增OutgameAdNotifyingAdapter，和现有适配器共享SourceState，恢复请求成功/失败、展示、关闭、奖励通知。解析IADListener槽0/1/2/5/6；明确共享函数4475在此为stopLoadTimeout。保持监听回调后的条件重读、忙碌时先清理后state3、展示仅state2、关闭state5去重、奖励无新增去重规则。447项（战斗267+关外180）通过，Unity退出0。点击/展示错误通知、完整原生适配器及监听器实际接线仍待完成，整体目标继续有效。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdNotifications','--result','pass','--evidence','447 integrated checks; source state notifications, listener mutation and timer/report ordering verified; production wiring and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded447; full goal remains active.')
