from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();report=W/'analysis/unity-integrated-validation.json';r=read(report);assert r['passed'] and len(r['checks'])==1077
assert 'AREABATTLE_INTEGRATED_PASS cases=1077' in (W/'analysis/package-items-integrated-final.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');ids=set(range(34300,34310))|{26192,34590};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids];generics=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in read(O/'package-random-generics.json')['methods']]
findings=[
'PackageItemBase34300 and Auto34305 outer counter is unchecked Int32 compared after sign extension to Int64 requested count. Nonpositive count returns empty; no clamp or long counter substituted. Per iteration reads current config.GetPackageRewards(ItemConfig.paramInt), enumerates dictionary pairs.',
'Every package group creates fresh System.Random and calls virtual Next(0,10000), accepts roll<rewardRandom. Then gets current reward range list, skips if initially empty. For j<live rewardItemCount: GetRandomWeight, List.Remove(selected), generate quantity using shared RandomHelper.Random(min,max)=Next(min,unchecked(max+1)), set original rewardOrder. Removal affects returned list only, cached elements/config remain. No check for exhaustion inside pick loop; excess requested picks fail on empty selector.',
'Generic GetRandomWeight26203 body f10956 and lambda26209 f15316 resolved via original registration. Null list logs source text and returns null. Aggregate unchecked sum of weights; shared Random.Next(0,total); live indexed cumulative unchecked sum with strict roll<cumulative; fallback first row. Empty list reaches index0, zero weight sum falls back first, negative/overflow total passed to Random unchanged. No normalization or weight repair.',
'Base conversion creates reward rows without item-config lookup or nested expansion. Auto conversion looks up current Items[selected.Config.itemId], if type1==9 obtains current global.GetItem before quantity RNG, then calls nonnull entity virtual AddItem(count) immediately; no row appended for that nested item. Null nested entity still consumes quantity RNG. This is effectful conversion and nested effects can survive later failures. Virtual slot4 verified table2088->wasm14832 invoked by helper2866.',
'Package.Use34302 calls base ItemBase.Use first (message/report), then virtual ItemToReward, appends each returned row reference to current ItemManager.PackageOpenRewardsTemp via LinkedList.AddLast per iteration, then current global.AddRewardsByItemSelf(list). No implicit debit/save beyond downstream methods. Base Add/OnlyModel delegate base ItemBase and thus virtual reward conversion; Manual only inherits. Auto Add/OnlyModel use virtual Use(count), including model path host callbacks.',
'All nine original factory entity types now have concrete constructors. Removed AdditionalConstructors placeholder; unsupported source type2 values still return null in original factory selection. Default chance RNG creates System.Random per group; shared GameRandomSource remains one shared generator for weight and inclusive quantity. Golden tests inject deterministic RNG, not original time-seed reconstruction.',
'Next ownership evidence: GlobalItemManager.get_Instance34590 constructs and publishes singleton before invoking current ItemConfigMgr.InitMgr. This missing production ownership path is the next task; class constructor and failure/reentrancy semantics need source-backed composition. ItemConfigMgr.get_Instance alone does not initialize tables.'
]
limits=['Full source GlobalItemManager singleton/owner composition not yet integrated into Main; standalone service tests explicitly initialize config/record.','Reporting/platform, full UserInfo/Dice/CommanderUI owners and24 controller lifecycles still incomplete.','No fresh native PlayMode or full outgame Player build. RNG default time seeding/platform sequence not claimed bit-identical; original source call structure and deterministic boundary cases validated.']
write(O/'PACKAGE_ITEMS_SOURCE_EVIDENCE.json',dict(atUtc=now,methods=methods,genericMethods=generics,criticalEvidence=findings,limits=limits))
v=dict(atUtc=now,scope='Both package entities, weighted selection/nested effects, all nine factory constructors and real package->module/tool/storage flow',checksPassed=1077,newIntegratedChecks=14,nativePlayModeChecks=0,freshPlayModeRun=False,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly'],notClaimed='Full owner/Main composition, original time-seeded RNG replay, SDK delivery or full outgame Player')
remaining='Restore GlobalItemManager.get_Instance34590 owner: construct/publish global before current ItemConfigMgr.InitMgr, preserving failure/reentrancy and release/reset; compose config/record/rewards/factory/entity services into source-default legacy data manager startup. Then full UserInfo/CommanderUI/Dice/report owners and24 remaining controller lifecycles, full Main/account/menu/business flows and runnable outgame Player.'
a=dict(atUtc=now,status='all-nine-item-entities-package-random-and-real-chain-owner-composition-pending',sourceEvidence='PACKAGE_ITEMS_SOURCE_EVIDENCE.json',verification=v,implementedLifecycleControllers=14,remainingLifecycleControllers=24,findings=findings,remaining=[remaining]+limits,disassembledMethodMapCount=len(mm),artifacts=dict(integratedLog='analysis/package-items-integrated-final.log'));write(O/'PACKAGE_ITEMS_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='package-item-entities',packageItemsAudit='generated/outgame/PACKAGE_ITEMS_AUDIT.json',nextPriority=remaining);d['validation']['integratedChecksPassed']=1077;d['validation']['packageItems']=v;d['milestones'].append(dict(id='package-item-entities',atUtc=now,status=a['status'],integratedChecks=1077,remainingLifecycleControllers=24));write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=1077,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=report.stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 礼包实体和权重随机增量\n- 1077集成通过（新增14），最终log analysis/package-items-integrated-final.log；Unity72384已退出。初68908编译因Random歧义失败，Editor加System.Random alias修复。无新native/Player；14/38 lifecycle不变，method-map5170（generic另存3不入map）。\n- 新OutgamePackageItems.cs：PackageItemBase4489/Auto4490/Manual4491及OutgamePackageServices。工厂现在9实体全具体创建，移除AdditionalConstructors；未知原type2仍源null。Packages.Manager须currentItemManager provider；NewChanceRandom默认每group newSystem.Random；weight/quantity共用GameRandomSource.Shared。\n- Base34300和Auto34305：Int32 outerindex unchecked增量，signextend与longcount比，非正空，不擅改long循环/上限（>intMax可能源wrap，不测试不可终止情况）。每次currentConfig.GetPackageRewards(paramInt) KVP枚举，每row freshRandom.Next(0,10000)<rewardRandom才获currentGetRewardRanges；初始空跳过。j按live rewardItemCount，weightedselect→remove→quantity Inclusive(min,max)→order；不每轮检查候选空，overdraw会空selector[index0]异常，不补位/截断。\n- GenericRandom26203 f10956+lambda26209 f15316从registration提取至O/disassembly/PackageRandomGeneric-{26203,26206,26209}.txt及package-random-generics.json；26206为另一个sortlambda仅证据不使用。weightednull日志权重随机集合不能为空并null，empty不日志但Next(0,0)后index0异常；sum unchecked，roll shared.Next(0,total)，live cumulative严格roll<sum，fallback0；不修负/溢出权重。analysis/extract_package_random_generic.py可重抽。\n- Auto与Base差异：选中后Auto先currentconfig.Items[itemId]再type1==9则currentglobal.GetItem→Inclusive数量→非null virtual AddItem，立即副作用，不appendnestedrow；nullentity也消耗数量RNG。Base不查itemconfig、不展开。slot4由helper2866调table2088→wasm14832明确VirtualActionInvoker，概率Next helpertable6324→f1901槽6。\n- Use34302先baseUse（Item_Use/report）→virtualToReward→逐row currentManager.PackageOpenRewardsTemp.AddLast（共享row）→currentGlobal.AddRewardsByItemSelf。Base Add/OnlyModel调用baseItemBase，因此也virtualToReward，但不Use队列/报告。Manual仅ctor继承。Auto Add/OnlyModel virtualUse，模型路径也会hostAdd。无补造礼包扣库或保存。\n- 13Packagechecks+1Module真实链：原20000每份2无放回（min RNG gold10 diamond5）、共享cache不删、概率边界、null/empty/zero/overflowweight、overdraw、inclusive max+1和intMax overflow、原20001嵌套8000立刻奖8101而外11001稍后、队列nested先/引用、manualAdd/Use差异、autoOnlyModel fullUse、失败prefix、每row currentManager、auto缺配置 vsbase、live枚举异常；真实module20000→实际pkg/global/manager/Tool/local/存档重读gold10/diamond5，未插入礼包库存。\n- 关键下一步：rg发现ItemConfigMgr.InitMgr唯一已抽caller为GlobalItemManager.get_Instance34590/f2040：ifglobalnull newctor→先publishglobal→currentItemConfigMgr.InitMgr，再returnstaticcurrentglobal。不能由ItemConfigSlot getter自动init；现需把此owner的failure/reentrant语义、Release/reset和config/reward/entity实际服务组成起来，接source-default legacyDataManager启动。查Type4542-34570 ctor及34590 getter/34577Release。\n- O/PACKAGE_ITEMS_SOURCE_EVIDENCE.json/AUDIT.json、state/manifest/交接同步，完整目标仍active，后续仍需UserInfo/CommanderUI/Dice/report owners、24control及完整Main/关外Player。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('1063 项 checks','1077 项 checks').replace('caseCount=1063；latestValidation 为 seven virtual item entities','caseCount=1077；latestValidation 为 package entities and weighted random').replace('最新集成日志 analysis/virtual-items-integrated.log。1063集成通过','最新集成日志 analysis/package-items-integrated-final.log。1077集成通过').replace('in_progress / virtual-item-entities','in_progress / package-item-entities');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgamePackageItemEntities','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/PACKAGE_ITEMS_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
assert all(hashlib.sha256((W/f['path']).read_bytes()).hexdigest()==f['sha256'] for f in d['sourceFingerprints'])
print(json.dumps(dict(checks=1077,controllers=14,remaining=24,fingerprints=len(files),sourceMethods=len(methods),genericMethods=len(generics),methodMap=len(mm))))
