from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==421
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='video-placement-mapping';s['validation'].update(integratedChecksPassed=421,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['video-placement-mapping']={'implementationReady': True, 'productionConnected': False, 'source': ['disassembly/Type4452-34154.txt', 'disassembly/Type7574-55421.txt', 'disassembly/Type9254-64899.txt', 'disassembly/Type9254-64900.txt', 'startup-prefab-resolution.json', 'user-prefs-fields.json'], 'implementation': ['OutgameVideoMapping.cs', 'Resources/Data/Outgame/WXAMSConfig.json'], 'scope': 'Original startup label->placement dictionary from 59 source configuration records, Dictionary.Add duplicate behavior, bridge dictionary reference retention and video placement resolution errors/fallback68 implemented. Only placement resolution from OnNewEvent is covered; full analytics event filter/JSON conversion and ad callbacks/rewards not yet connected.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original video placement table and bridge mapping resolution') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original video placement table and bridge mapping resolution','checksPassed':421,'outgameChecksPassed':154,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact': 'ProcedureStarGame.OnEnter builds Dictionary<string,int> with WXAMSConfig.ReportLable(offset16) -> PlacementId(offset12), using Add before WXAMS.SetVideoMapping. WXAMS dispatches Bridge slot115; Bridge_WX_XYXFunction.SetVideoMapping simply stores dictionary reference at offset32. OnNewEvent video placement section uses mapping lookup: positive ID preserved, nonpositive/missing log distinct exact errors then set68. Dictionary absent/null label exceptions are not hidden. Imported all59 original rows and verified representative economy/skin/tool labels, shared reference mutation, duplicate failure and fallback errors. Complete OnNewEvent filtering/JSON/event reporting and actual ad reward callbacks remain incomplete.', 'source': ['disassembly/Type4452-34154.txt', 'disassembly/Type7574-55421.txt', 'disassembly/Type9254-64899.txt', 'disassembly/Type9254-64900.txt', 'startup-prefab-resolution.json', 'user-prefs-fields.json'], 'implementation': 'OutgameVideoMapping.cs', 'validation': 'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 原始广告位置表与桥接映射（421项）\n导入WXAMSConfig全部59条原配置，新增OutgameVideoMapping按启动逻辑用ReportLable→PlacementId和Dictionary.Add构造映射；桥接保存原字典引用。恢复OnNewEvent中位置解析部分：正数直用，缺失/非正数分别记录原错误并回退68；未初始化字典及错误回调异常不吞掉。原表代表性商店/皮肤/道具位置、引用更新、重复标签及回退验证通过；421项（原267+关外154），Unity退出0，源方法1428。完整事件过滤/JSON上报与实际广告播放奖励、OnEnter连接仍待补齐。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameVideoPlacementMapping','--result','pass','--evidence','421 integrated checks; source original 59-row video placement mapping and bridge fallback behavior verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded421; full goal remains active.')
