from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-skin-item-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==341
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='scene-skin-actions';s['validation'].update(integratedChecksPassed=341,skinItemActionChecksPassed=8)
s['nextActions']=['Resolve scene prefab binding mismatch (btn_grandUnlock vs inherited btn_actLimit) before native scene view binding.','Recover source ordering and full ShopUI assembly/listeners; bind real sprite/activity/video providers.','Complete account startup and remaining outgame systems; build and validate full playable flows.']
for sub in s['subsystems']:
 if sub['id']=='skins-cosmetics':sub.update(implementation='SceneSkinItem buy/select source differences implemented; native scene binding and full ShopUI/providers pending',validation='7 manager and8 item/native-card/scene checks pass; subsystem incomplete')
write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['scene-skin-actions']={'implementationReady':True,'scope':'SceneSkinItem purchase/select overrides, not full native scene view or GameControl visual implementation','rules':['Buy debit first; failure retains equipment and shows missing-currency toast after dispatcher save. Success voice2017, BuyScene config runtime offset12 +1, equipment type4 assignment, ChangeSceneStyle(id,false), ToolChange skin+1, clear-new/red-dot, virtual Refresh(slot13 verified metadata). No explicit ReportToolUse or ChooseSkin event in purchase.','Select compares only current used type4 id. If different: voice2001, equip4, ChangeSceneStyle(id,false), clear-new/red-dot, ReportToolUse(id,3). No ownership/item-state gate, onClick callback, ChooseSkin event or save.','Refresh shares base SkinItem state rendering with used type4. Awake/Dispose/ctor delegate to base.'],'source':['disassembly/Type4359-33311.txt','disassembly/Type4359-33312.txt','disassembly/Type4359-33316.txt'],'implementation':['OutgameSceneSkinActions.cs'],'validation':'Real dispatch/skin/isolated disk proves equipped state saved before clear-new; exact action effects sequence and no-op same selection verified.','limitations':['Recovered sceneSkinItem prefab binds btn_grandUnlock and lacks btn_actLimit; do not silently alias without source evidence.','Scene visual provider and full page binding pending']};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['sourceMethodsIndexed']=756;write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='SceneSkinItem source overrides') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'SceneSkinItem source override effects and save boundaries','checksPassed':341,'outgameChecksPassed':74,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Shop acquisition/payment/UI, complete account startup or playable lobby'};write(p,s)
note='\n\n## 场景皮肤独立操作（341项）\n新增 OutgameSceneSkinActions，保留独立BuyScene统计与装备/场景切换先于解锁保存的顺序；选择只判当前装备ID，不沿用兵种curItemState检查，也不发送ChooseSkin事件。验证购买扣款失败、完整成功顺序、隔离重启保存边界、相同选择无动作和原处理器无ownership检查。2新检查通过，Unity退出0，341集成检查（原267+关外74），原方法索引756。场景原预制体存在btn_grandUnlock而缺继承方法所查btn_actLimit，已记录待核对，未猜测别名。场景实际视觉与原页面全流程、启动及构建仍未完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
for name in ['unityCompile','outgameCommanderCore','outgameInventoryCore','outgameToolDispatchCore','outgameProfileStore','outgameMenuNavigation','outgameCommanderActions','outgameUiImport','outgameMenuView','outgameCommanderView','outgameLevelProgression','outgameOriginalLocalData','outgameOriginalCommanders','outgameSkinRecords','outgameSkinActions','outgameSkinItemActions','outgameSkinItemView','outgameSceneSkinActions']:
 subprocess.run(b+['set-check']+a+['--name',name,'--result','pass','--evidence','341 integrated checks passed including skin item callbacks and isolated restart; full outgame incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded 341 checks; full goal remains incomplete.')
