from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==520
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-effect-ids-easing';s['validation'].update(integratedChecksPassed=520,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-effect-ids-easing']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4054-31228.txt','disassembly/Type4054-31229.txt','disassembly/Type4054-31230.txt','disassembly/Type4054-31231.txt','disassembly/Type4054-31232.txt','disassembly/Type9974-68862.txt'],'implementation':['OutgameFlyEffectIds.cs','OutgameFlyEasing.cs'],'scope':'Source shared effect/sub-id registry and exact circular easing float expression order. Runtime tween host pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Source fly effect id registry and circular easing') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Source fly effect id registry and circular easing','checksPassed':520,'outgameChecksPassed':253,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Original effect registry starts id1, uses monitor around postincrement/add, allocates fly_{id}_{oldSubCount}, returns-1 for missing count, removes without recycling. EaseManager circular20/21 branches use float division and sqrt; restored expression order verified at endpoints/midpoints.','source':['disassembly/Type4054-31230.txt','disassembly/Type4054-31229.txt','disassembly/Type9974-68862.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'FLY_IDS_EASING_AUDIT.json';write(p,{'status':'id_registry_and_easing_verified_execution_pending','checks':520,'source':['disassembly/Type4054-31228.txt','disassembly/Type4054-31229.txt','disassembly/Type4054-31230.txt','disassembly/Type4054-31231.txt','disassembly/Type4054-31232.txt','disassembly/Type9974-68862.txt'],'verified':['IDs start1, monitor-protected postincrement/add; unchecked increment','Per-effect subids consume old count and format fly_{id}_{sub}; missing count-1, unknown allocation throws','Removal does not recycle global ids','Ease20 InCirc = -(sqrt(1-t*t)-1); ease21 OutCirc = sqrt(1-(t-1)^2), float expression order, no evaluator clamp'],'pending':['Concrete Unity tween advancement/target pulse semantics','Original random scatter and sin/cos binding','Production animation/pool host and visual test']})
note='\n\n## 动效编号与圆形缓动（520项）\n恢复OutgameFlyEffectIds：全局共享实例、ID从1开始、加锁后自增注册、分阶段fly_id_sub子编号、缺失计数-1及移除不复用。新增OutgameFlyEasing，按原EaseManager68862的浮点运算顺序恢复20/InCirc和21/OutCirc，保留原始求值器不夹紧越界输入。520项（战斗267+关外253）通过，Unity退出0。尚待具体逐帧Tween执行器、目标跳动、随机散点及生产页面组合，未做动态画面验收或Player构建。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyEffectIdsEasing','--result','pass','--evidence','520 integrated checks; source id registry and circular easing verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded520; full goal remains active.')
