from pathlib import Path
import json,hashlib,datetime,subprocess,difflib,re
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/audio-fade-native-validation.json');assert r['passed'] and len(r['checks'])==893;assert n['passed'] and len(n['checks'])==13
mm=read(O/'method-map.json');ids=set(range(26286,26301))|set(range(26310,26327))|{26381,26382};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
def normalized(stem):
 lines=[]
 for s in (O/'disassembly'/f'{stem}.txt').read_text(encoding='utf8').splitlines()[3:]:
  s=re.sub(r'^\w+\s+','',s);s=re.sub(r'AudioLoopFadeAction|AudioFadeAction','FadeAction',s);s=re.sub(r'(i32.const|call) \[\d{4,}\]',r'\1 [LINK]',s);lines.append(s)
 return lines
comparison={}
for x,y in [('Type3406-26296','Type3411-26322'),('Type3408-26292','Type3413-26316'),('Type3408-26286','Type3413-26315'),('Type3408-26294','Type3413-26314')]:comparison[x+' vs '+y]=list(difflib.unified_diff(normalized(x),normalized(y),n=2))
source=dict(atUtc=now,methods=methods,normalizedBodyComparison=comparison,factoryMetadata={'3928512':'AudioFadeAction type3408','3928516':'AudioLoopAction type3410','3928520':'AudioLoopFadeAction type3413','3928532':'AudioOnceAction type3415','3425 static field typeReference6088':'Func<GameObject,AudioActionType,int,Action<int>,Action<int>,AudioActionBase>; normal values, not mutation-by-ref. Generic invoker uses stack argument addresses.'},criticalEvidence=[
 'Fade OnPlay26296 and LoopFade26322 share normalized opcodes except source name fade_/loopFade_ and loop false/true. Capture path/start/end/type/volume/setting/name; write End68 then Start64 then targetVolume48 before await. Await new/legacy clip. Native clip-null returns null, initial data-null calls Stop. Create/play source volume0, record clip.length56, invoke Fade(source,true,null) before returning source to base Play.',
 'Fade helper26289/26320 captures source, callback, direction, owner; only native-nonnull source schedules. Remove prior timer72 if nonzero, then assign SetCountDownByMillisecond(1000,complete,every). Each callback observes live targetVolume48 and fadeMilliseconds52. Every(id,remaining): in target*((float)duration-remaining)/duration, out target*(float)remaining/duration.',
 'Complete26299/26325 first RemoveTime(callback id). Destroyed captured source invokes optional callback and returns. Live fade-in sets target and returns without invoking optional callback. Fade-out sets0 then optional callback. Timer field is never reset, so completion plus Dispose can remove same id twice.',
 'OnStop26292/26316 first sets stopping60 true; for live source stores targetVolume=source.volume*GetSettingVolume again, then Fade(false,CompleteStop). Null source leaves stopping true and no timer/cleanup. Repeated Stop releases handle and Dispose directly without EndCall or flag reset.',
 'CompleteStop26290/26310 source.Stop -> EndCall -> handle.Release -> Dispose -> stopping=false. Exception ordering retained. OnDispose26286/26315 removes nonzero timer without clearing field, destroys source GameObject, clears source. Refresh26294/26314 writes live target on matching voice even without a source, then base writes native volume.',
 'Fade OnUpdate26293 and LoopFade26312 native source gate: if End<=0 evaluate isPlaying/time/length-fadeSeconds and require playing/time>=threshold/!stopping; else time>=End-fadeSeconds without stopping or playing gates. Fade calls OnStop. LoopFade marks stopping and fades out; callback26321 clears stopping and fades in, without seek or restart. Positive end repeats/resets countdown on each loop-fade update; Fade second update can direct-dispose without end.',
 'AudioCompositeBase26381 checks optional static override first then exact types1Once/2Loop/3Fade/4LoopFade/default null. Opcode ctor annotation for type3 aliases shared ctor6273; allocated usage3928512 resolves actual3408Fade. GetAudioType26382 missing config=>1 otherwise Ptype. Override return type verified from generic metadata reference6088.'
 ],limits=['Original TimeModule3534 SetCountDownByMillisecond27283/AddCoundDown227275/RemoveTime27284 APIs identified, but full scheduler/clock and update ownership remain to restore. Production actions require these delegates; validation drivers are explicit.', 'No full AudioManager config/root/listener/node registry, original clip resource composition, acoustic recording or Player acceptance claim.'])
write(O/'AUDIO_FADE_SOURCE_EVIDENCE.json',source)
v=dict(atUtc=now,scope='Concrete Fade/LoopFade and all-four-type action factory; native controller/UI/Parallel/factory/action playback with explicit countdown driver',checksPassed=893,newIntegratedChecks=18,nativePlayModeChecks=13,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameAudioFadePlayModeValidation.Run'],notClaimed='Original TimeModule/resource/update/AudioManager ownership, complete Main/controller graph, device recording or full outgame Player')
a=dict(atUtc=now,status='partial-subsystem',sourceEvidence='AUDIO_FADE_SOURCE_EVIDENCE.json',verification=v,findings=[
 'OutgameAudioFadeActions.cs implements source Fade and LoopFade via evidence-shared bodies: native playback from volume0, live target volume, millisecond countdown interpolation and callback/disposal ordering. Both required new/legacy resource operations use source handles.',
 'Preserves stop-volume setting multiplication, repeat-stop disposal without end, null-source first-stop retention, retained timer ids and duplicate removal, countdown continuation during native pause, errors before later cleanup, and live volume events during pending load.',
 'LoopFade source loop transition only fades out then in without native seek/restart or end. Explicit EndTime lacks stopping gate: repeated updates replace loop countdown, whereas Fade re-enters OnStop and direct-disposes. Source quirks are covered as source behavior, not silently fixed.',
 'OutgameAudioActionFactory now supplies real constructors for types1..4; optional static typed override runs first even for invalid action types, null override falls back, invalid default returns null. Missing config GetAudioType returns1. Nodes can use actual GetAudioType/Create delegates.',
 '893 integrated pass,18 new.13 native PlayMode checks prove controller state2/7/6/8 -> UI parallel -> original Ptype4 LoopFade1001, actual cursor/pause/resume/volume/fade-out/end/release/destruction, plus original2001 Ptype3 automatic one-shot fade through same node. Countdown pulses and update/resource host in test remain explicit driver boundaries.',
 'Method map4979; real controller lifecycle methods11/38 with27 remaining. Goal still incomplete. No fresh Player build or full Main entry.'
 ],remaining=['Restore source TimeModule millisecond countdown and clock/paused behavior plus original shared UpdateManager; wire actual audio resources and AudioManager config/root/listener/node registry to the concrete action factory.','Continue remaining27 control lifecycles and full Main/account/module/menu graph, all objective subsystems, restart/failure/return flows and runnable Player acceptance.'],artifacts=dict(integratedLog='analysis/audio-fade-integrated.log',nativeLog='analysis/audio-fade-native.log',nativeReport='analysis/audio-fade-native-validation.json'),disassembledMethodMapCount=len(mm))
write(O/'AUDIO_FADE_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='audio-fade-actions-factory-native',audioFadeAudit='generated/outgame/AUDIO_FADE_AUDIT.json',nextPriority=' '.join(a['remaining']));d['validation']['integratedChecksPassed']=893;d['validation']['audioFadeFactoryNative']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='audio-fade-actions-factory-native'];d['milestones'].append(dict(id='audio-fade-actions-factory-native',atUtc=now,status='partial-subsystem',integratedChecks=893,nativeChecks=13,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,audioFadeAudit='AUDIO_FADE_AUDIT.json');d['remaining'][0]=' '.join(a['remaining']);d['findings'].append('Concrete Fade/LoopFade and four-way factory restored:893 integrated and13 fresh native chain checks, countdown driver explicitly fixture. Original TimeModule/resource/update/AudioManager pending; count11/38 unchanged.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=893,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 淡入淡出与完整动作工厂增量\n- OutgameAudioFadeActions.cs：真实Fade/LoopFade动作，公共body经原始opcode对比仅name/loop值差异；volume0播放、clipLength、调度Fade后base才写source/Start。required SetCountDownByMillisecond(int,Action<int>,Action<int,int>) / RemoveTime，尚未伪装成已恢复TimeModule。\n- Fade targetVolume在await前写入并可由等待中的音量消息更新；每帧in=target*(duration-remaining)/duration，out=target*remaining/duration；Complete先RemoveTime(id)，source销毁也调用end callback；fadein只写target，fadeout写0后调用callback。TimerId从不归0，Dispose重复Remove保留。\n- Stop先置Stopping，target=当前native.volume*setting（二次乘设置）；再fadeout。第一次Stop时source空只留下flag；第二次Stop直接release/Dispose，无EndCall、不resetflag。正常CompleteStop按Stop/End/release/Dispose/flag=false；所有失败保留已完成步骤。\n- End<=0要求isPlaying且time>=length-1且!Stopping。显式End>0只比较time>=End-1，无stopping/playing gate：Fade第二次Update走重复Stop直接销毁不End；LoopFade每次Update重置渐弱计时。LoopFade渐弱结束只flag=false+渐强，无seek/Play或结束消息。Pause hook空，native暂停不影响外部计时。\n- OutgameAudioActionFactory：真实1Once/2Loop/3Fade/4LoopFade，invalid=>null；GetType查Data缺失=>1否则Ptype；static Override typed Func<GameObject,OutgameAudioActionType,int,Action<int>,Action<int>,OutgameAudioAction>先执行，返回null才fallback。元数据typeRef6088证实普通值参数，WASM generic invoker的栈地址不是可变ref规则。type3 ctor注释误标LoopFade但usage3928512明确3408Fade。\n- 893集成通过（新18），13新原生PlayMode通过：实际AudioControl state2/7/6/8→UI→Parallel→factory→原始1001 LoopFade及2001 Fade，游标、暂停恢复、声音开关/分数音量、渐弱、end/句柄释放/帧后对象销毁。原生验证的倒计时由明确实时driver提供、update/resource仍fixture，不能声称完整TimeModule/AudioManager/Main已接。\n- analysis/audio-fade-integrated.log、audio-fade-native.log、audio-fade-native-validation.json；O/AUDIO_FADE_SOURCE_EVIDENCE.json和AUDIO_FADE_AUDIT.json。状态audio-fade-actions-factory-native；893/4979/11/27，无本任务待续进程。无新Player build。\n- 下一步TimeModule3534：已抽取46方法（methodmap此前已有）。SetCountDownByMillisecond27283转AddCoundDown227275；RemoveTime27284转Remove27276。Add要求complete非空否则-1；++field40计时id，先dict56.Add(id,complete)，GetNowTime+duration后dict60.Add(id,end)，有Every则dict68.Add(id,new everyinfo{callback8,type12=1,last16=0})。GetNowTime27271和CheckMillisecond27280/CheckComplete27278/Remove27276、clock/pause需继续核对，不能替换成普通Unitydelta timer。随后shared UpdateManager和AudioManager root/listener/config/node registry/资源load/unload完整接线。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('875 项 checks','893 项 checks').replace('caseCount=875；latestValidation 为 audio once/loop native','caseCount=893；latestValidation 为 audio fade/factory native').replace('in_progress / audio-once-loop-native','in_progress / audio-fade-actions-factory-native').replace('最新集成日志 analysis/audio-playback-integrated.log。875集成、13原生音频通过（loader/update为fixture）；','最新集成日志 analysis/audio-fade-integrated.log。893集成、13原生音频链通过（timer/loader/update为fixture）；');p.write_text(s+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameAudioFadeFactoryNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/AUDIO_FADE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=893,nativeChecks=13,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
