from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==513
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='project-shop-item';s['validation'].update(integratedChecksPassed=513,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['project-shop-item']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4362-33336.txt','disassembly/Type4362-33333.txt','disassembly/Type4362-33337.txt','disassembly/Type4362-33334.txt'],'implementation':['OutgameProjectShopItem.cs'],'scope':'Original Proj_hdzd ShopItem SetData and click: first itemConfig, integer price, diamond debit, reward, voice, extra report and refresh, using actual ToolDispatcher/LocalInventory and original table. Full page card selection/instantiation and account binding pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original project ShopItem purchase flow') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original project ShopItem purchase flow','checksPassed':513,'outgameChecksPassed':246,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'ShopItem4362.SetData reads Proj_hdzd product.itemConfig[0] first id/count, price string display then Int32.Parse. Click calls ToolChange(1002,-price,true,empty,true), on success reward ToolChange, voice(1,2017), extra ReportToolGet category1 with Global.CoinCost and current balance, then virtual Refresh. Real dispatcher and original16-row table tests pass.513 checks pass; complete store UI/account not connected.','source':['disassembly/Type4362-33336.txt','disassembly/Type4362-33333.txt','disassembly/Type4362-33337.txt'],'implementation':['OutgameProjectShopItem.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'PROJECT_SHOP_ITEM_AUDIT.json';write(p,{'status':'controller_implemented_page_binding_pending','sourceType':4362,'configType':3943,'configNamespace':'Proj_hdzd','checks':513,'implementation':'OutgameProjectShopItem.cs','source':['disassembly/Type4362-33336.txt','disassembly/Type4362-33333.txt','disassembly/Type4362-33337.txt'],'verified':'Original16-row table and actual local inventory/tool dispatcher; debit-success gating, first reward only, ordered audio/report/refresh and uncaught parse partial state','pending':['Trace StorePurchaseUI category/card selection before assigning product rows to prefab types','Connect original native card view and account manager dependencies','Implement other sales/coin/jewel/free-diamond callbacks and complete store lifecycle']})

note='\n\n## 项目ShopItem原表与购买（513项）\n新增OutgameProjectShopItem及Proj_hdzd原表DTO，读取原16条商品数据；SetData仅第一itemConfig，先显示price再Int32.Parse，保留失败中间态。点击先真实ToolDispatcher扣1002，成功才发第一奖励、Voice(1,2017)、额外ReportToolGet(category1,Global.CoinCost,当前库存)和Refresh。已验证余额不足仍保留分发器原通知/保存但不发奖，第二奖励不处理。513项（战斗267+关外246）通过，Unity退出0。控制器测试不代表完整页面可用，StorePurchaseUI卡片分类、原Prefab/账号绑定和其他礼包回调待继续。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameProjectShopItem','--result','pass','--evidence','513 integrated checks; original project ShopItem table, actual currency/reward dispatcher and failure sequencing verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded513; full goal remains active.')
