from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-ads-playmode-validation.json')
assert r['passed'] and len(r['checks'])==553 and v['passed'] and play['passed'] and len(play['checks'])==7
sources=['disassembly/Type2883-'+str(i)+'.txt' for i in [22358,22359,22360]]+['disassembly/Type2875-'+str(i)+'.txt' for i in range(22366,22371)]+['disassembly/Type2878-22384.txt','disassembly/Type2881-22391.txt','disassembly/Type3373-26053.txt','disassembly/Type3373-26072.txt','disassembly/Type3374-26078.txt']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ads-unity-await';s['validation'].update(integratedChecksPassed=553,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ads-unity-await']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameUnityAwait.cs','OutgameUnityAwaitRunner.cs','OutgameAdsVideoFlow.cs'],'scope':'Single-yield Unity await runner and completion/context dispatch restored. Actual original ShopUI/config/native Button verified in PlayMode with real0.2second wait while paused and scaled1second report after resume. SDK and report transport remain explicit fixtures.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Unity coroutine await source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Unity await runner and actual paused/resumed advertisement timing','checksPassed':553,'outgameChecksPassed':286,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-ads-playmode-validation.json','playModeChecksPassed':7,'freshPlayModeRun':True,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'actual_unity_ads_timing_verified_platform_pending','source':sources,'verified':['Unity synchronization-context dispatch runs inline on matching context or posts from other context','SimpleCoroutineAwaiter source completion/registration assertions and ExceptionDispatchInfo rethrow restored','Shared singleton runner creates hidden61 DontDestroyOnLoad gameObject; ReturnVoid yields original instruction then completes','Actual original ShopUI/config/Start/native pointer verified in Unity PlayMode','0.2048666second real wait advances at timeScale0, with show message before SDK fixture and successful raw callback','Scaled report coroutine remains suspended at timeScale0 and executes after resume'],'remaining':['Concrete DBTSDKManager platform adapter and readiness','Worker-thread context dispatch dynamic coverage and other original await overloads','Production account/menu/report owner and full persistence/build/E2E'],'checks':553,'freshAdsPlaymodeChecks':7,'priorFlyPlaymodeChecks':8,'dynamicScope':'Fresh actual Unity PlayMode; SDK/report transport remain fixtures; historical fly PlayMode not rerun'}
write(o/'ADS_UNITY_AWAIT_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Unity await runner restored;7 actual PlayMode checks verify original ShopUI native startup, real-time advertisement wait while paused, raw callback and scaled delayed reports after resume. Concrete SDK and production account remain pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-ads-playmode-validation.json']});write(p,s)
note='\n\n## Unity广告等待运行器与实际PlayMode（553+独立7项）\n恢复原单yield ReturnVoid、SimpleCoroutineAwaiter断言/异常传播和Unity同步上下文派发，运行器hiddenFlags61并DontDestroyOnLoad。新增真实PlayMode验证使用原ShopUI和原视频表：Start绑定就绪、原生点击后经真实0.2秒等待发送show事件、原始JSON完成回调；timeScale0期间实测请求等待0.2048666秒，scaled1秒上报保持暂停，恢复时间后正常执行。7项动态检查通过，Unity退出0。集成回归仍553项通过，未把独立动态检查累加为集成计数。此前8项飞币PlayMode未重跑。索引2389；具体SDK/就绪/上报平台、生产账号菜单和完整构建仍未完成，动态SDK返回明确为fixture。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdsUnityAwait','--result','pass','--evidence','553 integrated checks and7 fresh actual Ads PlayMode checks; prior8 fly PlayMode not rerun. Concrete SDK/account composition pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded553; full goal active.')
