from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==429
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-entry-controller-chain';s['validation'].update(integratedChecksPassed=429,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-entry-controller-chain']={'implementationReady': True, 'productionConnected': False, 'source': ['disassembly/Type9240-64771.txt', 'disassembly/Type9240-64773.txt', 'disassembly/Type9240-64776.txt', 'disassembly/Type9202-64478.txt', 'disassembly/Type7544-55102.txt', 'disassembly/Type9202-64492.txt'], 'implementation': ['OutgameAdModuleEntry.cs', 'OutgameRewardVideoControllerHost.cs', 'OutgameRewardVideo.cs', 'OutgameAdRequestRouter.cs'], 'scope': 'Original WXFunctionManager cached module lookup/activation gate now wired via controller host to recovered ADModule and NewAdsManager routing. Integrated entry->module->router->controller callbacks verified. Environment/controller provider still required; native WeChat controller creation and concrete business reward handlers not completed.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original entry-to-ad-controller integrated lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original entry-to-ad-controller integrated lifecycle','checksPassed':429,'outgameChecksPassed':162,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact': 'WXFunctionManger caches module at offset20, CheckFunctionActive reads offset8, warns and rereads flag when disabled. Inactive ShowVideo returns without reward callback; inactive AdsIsReady adds second warning; missing module throws. OutgameAdModuleEntry implements this gate and OutgameRewardVideoControllerHost connects existing ADModule state to NewAdsManager router: native readiness delegates router, clears sourceFlag64, forwards show optionfalse. Integration demonstrates shown(true) does not reward, close(false/true) forwards exact result; absent controller shown(false) cancels timeout but retains pending callback, then outer VideoAdShow still emitted. No fabricated failure completion added. Concrete native controllers and gameplay reward consumers still pending.', 'source': ['disassembly/Type9240-64771.txt', 'disassembly/Type9240-64773.txt', 'disassembly/Type9240-64776.txt', 'disassembly/Type9202-64478.txt', 'disassembly/Type7544-55102.txt', 'disassembly/Type9202-64492.txt'], 'implementation': 'OutgameAdModuleEntry.cs + OutgameRewardVideoControllerHost.cs', 'validation': 'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 广告入口至控制器调用链（429项）\n新增OutgameAdModuleEntry还原WXFunctionManger缓存查找和启用门控，禁用时只警告不回调，Ready额外警告，警告后重读启用字段。新增OutgameRewardVideoControllerHost连接原ADModule与NewAdsManager：查底层Ready、清field64、Show选项false。集成覆盖入口→模块→路由→控制器→展示/关闭回调，展示成功不领奖、提前关闭失败、结束成功；缺控制器保留原待处理回调并取消超时，不发明完成事件。429项（原267+关外162）通过，Unity退出0。实际微信控制器创建/原生调用与具体业务领奖入口仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdEntryControllerChain','--result','pass','--evidence','429 integrated checks; source integrated module entry/controller lifecycle and reward result separation verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded429; full goal remains active.')
