from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==437
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-request-queue';s['validation'].update(integratedChecksPassed=437,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-request-queue']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7511-54851.txt','disassembly/Type7488-54716.txt','ad-price-fields-and-request-slot.json'],'implementation':['OutgameAdRequestQueue.cs','OutgameAdReadiness.cs'],'scope':'Two-pass real request queue: non-cache high priority then non-high priority, dedup, fresh list each pass, interstitial report, handle before removal with queue reread. Base high-priority default false. Full controller/native lifecycle still pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original two-pass real request queue and callback ordering') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original two-pass real request queue and callback ordering','checksPassed':437,'outgameChecksPassed':170,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'BaseController.showAd clears realRequestList on non-continuation, calls getPlatList separately for high/non-high passes, excludes cache candidates, deduplicates via Contains, checks isHighPriority virtual slot9 (base false). Nonempty rebuilt queue reports only if zkey Contains INTERSTITAL. Then first.Handle runs before rereading queue and Remove(first). Continuation bypasses rebuild/report. 437 integrated checks pass. Additional source branch inspected: weixin platform fallback requires isGuarantee && state2 && canShow; no fallback and empty continuation reports failure, with INTERSTITAL4 close(true) before report. Complete showAd composition pending.','source':['disassembly/Type7511-54851.txt','disassembly/Type7488-54716.txt','ad-price-fields-and-request-slot.json'],'implementation':['OutgameAdRequestQueue.cs','OutgameAdReadiness.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 广告真实请求队列（437项）\n新增OutgameAdRequestQueue，按原始双遍getPlatList顺序收集非缓存高优先级/普通候选，Contains去重；非续请求先清队列，非空且zkey含INTERSTITAL才报告轮转请求。Handle先于移除，回调后重读队列并Remove原对象，失败保留待请求项。补齐适配器isHighPriority默认false。437项（战斗267+关外170）通过，Unity退出0。已确认微信回退候选还要求isGuarantee、state2、canShow；下一步组合完整showAd控制流与视频回调。完整目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdRequestQueue','--result','pass','--evidence','437 integrated checks; original two-pass request priority, deduplication, continuation and callback mutation verified; full controller and goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded437; full goal remains active.')
