from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==416
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='user-preferences-new-day';s['validation'].update(integratedChecksPassed=416,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['user-preferences-new-day']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type3486-26871.txt','disassembly/Type3486-26863.txt','disassembly/Type3486-26851.txt','disassembly/Type3486-26882.txt','disassembly/Type3566-27472.txt','disassembly/Type3566-27474.txt','disassembly/Type3566-27464.txt','disassembly/Type3566-27467.txt','disassembly/Type3566-27473.txt','user-prefs-resolution.json','user-prefs-fields.json'],'implementation':['OutgameUserPreferences.cs'],'scope':'Managed UserDataPrefs original three typed columns, initialization/overwrite/save digest and reports plus GlobalData.CheckNewDay order implemented. Actual isolated UserData.txt save/restart validated. Required platform preference ownership, source file routing and SDK days/event providers remain explicit. DataContract JSON handles verified source record schema; full original Json parser and MD5 failure parity not proven. Complete startup and daily consumers remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original managed preference records and SDK-day transition') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original managed preference records and SDK-day transition','checksPassed':416,'outgameChecksPassed':149,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'GlobalData.CheckNewDay compares UserDataPrefs Day default0 to SDK GetDaysByFirstLaunch, then rereads old Day and SDK days, updates Day, emits GameEnterNewDay(new,old) without save. Backward day changes trigger; listener failure retains Day. SDKToolManager forwards platform virtual slot203 or returns0 with absent platform. Managed UserDataPrefs keeps UserDataList records Key/StrVar/IntVar/FloatVar, initializes once, platform-owned branch defers; invalid entries skipped and duplicate keys overwrite. Setters preserve other typed columns; null strings ignored. Save uses MD5 before FileManager UserData.txt write, suppresses unchanged retries even after failed write, reports current login user. Original JSON field schema and real isolated persistence tested; complete parser edge compatibility, file/SDK production providers and full startup pending.','source':['user-prefs-resolution.json','user-prefs-fields.json','disassembly/Type3486-26871.txt','disassembly/Type3566-27464.txt','disassembly/Type3566-27474.txt'],'implementation':'OutgameUserPreferences.cs','validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 原格式偏好存档与跨日检查（416项）\n新增OutgameUserPreferences实现原UserDataList/Key/StrVar/IntVar/FloatVar结构，保留托管初始化一次、平台接管时延后、重复键覆盖、类型列共存、null字符串忽略与保存MD5提前更新。新增OutgameNewDay按SDK首次启动天数比较并重读，先写Day再发送GameEnterNewDay(new,old)，回退天数也触发，异常不回滚或重发。真实隔离UserData.txt保存/重启与失败后去重通过；416项（原267+关外149），Unity退出0，源方法1296。DataContract用于已验证JSON格式，完整原解析器边界/平台天数/文件路径及完整启动仍未接通，整体目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameUserPreferencesNewDay','--result','pass','--evidence','416 integrated checks; source preferences actual isolated persistence and SDK-day transitions verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded416; full goal remains active.')
