from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==511
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-product-random';s['validation'].update(integratedChecksPassed=511,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-product-random']={'implementationReady':True,'productionConnected':False,'source':['disassembly/GenericPriceRandom-7643.txt','../combat-disassembly/Raw-10954.txt','disassembly/Type3391-26192.txt','disassembly/Type3391-26197.txt'],'implementation':['GameRandomSource.cs','OutgameProductPrices.cs','BattleView.cs'],'scope':'Original shared parameterless System.Random, inclusive integer range with unchecked upper increment, Next(count) list indexing. Battle default source and price constructor share the instance; explicit battle override retained. Original seed/timing not claimed identical.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original shared product and battle random source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original shared product and battle random source','checksPassed':511,'outgameChecksPassed':244,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Generic price random table7643 maps to wasmcode2673 forwarding10954; list selection calls shared Random.Next(count) then list index. Source cctor creates one parameterless System.Random. Shared source extracted from BattleView and reused by prices; existing battle overrides retained.511 checks pass including all267 battle checks. Original runtime seed/timing parity remains unclaimed.','source':['disassembly/GenericPriceRandom-7643.txt','../combat-disassembly/Raw-10954.txt','disassembly/Type3391-26192.txt','disassembly/Type3391-26197.txt'],'implementation':['GameRandomSource.cs','OutgameProductPrices.cs','BattleView.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='price_random_shared_provider_implemented_power_and_account_pending';audit['randomImplementation']={'files':['GameRandomSource.cs','OutgameProductPrices.cs','BattleView.cs'],'checks':511,'detail':'Shared managed source; inclusive range and list overload dispatch; empty list and upper overflow preserve source failure. Seeded interleaving verified; original seed/timing not claimed.'};audit['pending']=['Verify native wasm power versus Unity rounding boundaries and connect source config','Implement reward side effects and statistics bus production host','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 原共享随机源（511项）\n价格泛型table7643映射wasmcode2673再调用10954，确认Next(count)后列表索引。RandomHelper静态构造创建唯一无参System.Random。提取GameRandomSource，BattleView默认及价格构造入口共用Managed，战斗显式RandomSourceOverride保持。验证包含上界、max+1 Int32溢出、空列表先Next(0)再索引异常与战斗/价格序列交错。511项（战斗267+关外244）通过，Unity退出0；不宣称原会话种子/时序一致，幂运算精度、真实配置及账号Provider尚待完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameProductRandom','--result','pass','--evidence','511 integrated checks; source random range/list semantics and shared battle-price interleaving verified; native power precision and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded511; full goal remains active.')
