from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==517
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-currency-assets';s['validation'].update(integratedChecksPassed=517,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-currency-assets']={'implementationReady':True,'productionConnected':False,'source':['fly-ui-evidence.json','fly-ui-import.json','../resource-snapshots/fly-currency-20260929/acquisition-manifest.json'],'implementation':['OutgameFlyCurrencyAssets.cs','Recovered/FlyCurrency'],'scope':'Three original fly currency prefabs, original geometry and pixel bindings imported; animation host and visual comparison still pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original fly currency prefab assets') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original fly currency prefab assets','checksPassed':517,'outgameChecksPassed':250,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Recovered original goldItem,diamondItem,strengthItem prefabs. Missing two bundles acquired from original catalog URL, exact MD5/size verified. Original sprite render identity and geometry used for exported pixel reuse; all matching copies have same hash. Actual Unity prefab geometry and sprite binding tests pass.','source':['fly-ui-evidence.json','fly-ui-import.json'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'FLY_CURRENCY_ASSETS_AUDIT.json';write(p,{'status':'original_prefabs_imported_animation_pending','checks':517,'acquisition':'../resource-snapshots/fly-currency-20260929/acquisition-manifest.json','evidence':'fly-ui-evidence.json','import':'fly-ui-import.json','unityReport':'analysis/unity-fly-currency-import-report.json','verified':['Three bundle sizes and MD5 match original catalog','Original single-node goldItem70x70,diamondItem64x64,strengthItem70x70, pivot0.5 and unit scale','Actual Unity Image sprite and texture bindings','Diamond/strength sprite reuse requires exact renderDataKey,rect,pivot,ppu,border and all matching pixel hashes identical'],'pending':['Actual fly animation pool/Tween host','Source cleanup scheduler and global Target_Tween semantics','Matched runtime visual capture']})
note='\n\n## 原版飞行货币资源（517项）\n补齐钻石/体力原始资源包（11470字节），并连同已缓存金币包按原目录大小/MD5校验。恢复goldItem、diamondItem、strengthItem三个单节点Prefab与Image。钻石/体力图片以原renderDataKey、rect、pivot、ppu、border逐项一致且匹配副本像素哈希一致为依据复用导出像素，证据保留在fly-ui-import.json。新增OutgameFlyCurrencyAssets，将原加载路径映射到真实恢复Prefab。517项（战斗267+关外250）通过，Unity退出0；验证原尺寸、中心pivot、单位缩放和实际Sprite绑定。动画宿主、清理调度和完整关外连接仍待继续，本次没有新Player构建/动态视觉验收。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyCurrencyAssets','--result','pass','--evidence','517 integrated checks; three original fly currency prefabs, source geometry and real sprite bindings verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded517; full goal remains active.')
