from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==529 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type3667-28679.txt','normal-pool-destroy-generics.json','disassembly/Type3664-28674.txt','disassembly/Type3595-27679.txt']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='normal-pool-destruction';s['validation'].update(integratedChecksPassed=529,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['normal-pool-destruction']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameNormalPool.cs'],'scope':'NormalPool destruction ordering implemented with explicit manager/resource lifetime provider. New-resource order, repeated calls and failure propagation verified. Native provider and old-resource branch still require integration validation.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Object<T> shared source wrapper') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original pooled object count/lifecycle wrapper','checksPassed':529,'outgameChecksPassed':262,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'destruction_contract_implemented_provider_integration_pending','source':sources,'verified':['Request registered pool destruction if manager exists before root destruction','Unity-live root destroyed before loader-flag branch','New loader: iterate handle dictionary values, Release each, then UnloadUnusedAssets','Only old ResourcesInfo dictionary cleared at successful method end; new handles retained','Repeated destruction repeats retained-handle release; release exceptions stop before unused cleanup'],'staticOnly':['Old branch calls ResourcesModule.UnloadUnusedBundle for each cached info','Pooled ReleaseUIForm delegates GlobalUnityEngineAPI.Destroy; helper checks Unity inequality before Object.Destroy'],'remaining':['Concrete pool manager lookup/removal and original provider integration','Native handle lifetime and unused asset operation','Legacy backend dynamic validation','Production page/account composition and full build/E2E'],'checks':529,'playmodeChecks':8,'dynamicScope':'New destruction order uses instrumented dependencies;8 Play Mode checks rerun existing coin flow, not destruction'}
write(o/'NORMAL_POOL_DESTRUCTION_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'NormalPool destruction order restored from28679; generic resolution confirms new handle Values and old info Values/Clear. ReleaseUIForm and GlobalUnityEngineAPI.Destroy bodies extracted. Provider integration and production flow pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## NormalPool销毁与缓存释放（529项 + 独立8项动态检查）\n解析28679及泛型绑定，新增DestroyObjectPool显式生命周期依赖：先请求管理器销毁，再销毁Unity存活根节点，新加载器逐个Release缓存句柄然后UnloadUnusedAssets，旧加载器逐个UnloadUnusedBundle；成功末尾只Clear旧ResourcesInfo字典。保留原版新句柄缓存以及重复调用、异常中断行为。529项集成检查通过，8项既有飞币Play Mode回归通过（动态8项不代表销毁验证，销毁顺序由集成探针验证）。额外提取ReleaseUIForm28674与GlobalUnityEngineAPI.Destroy27679，确认其最终是Unity空检查后Object.Destroy。原始方法索引2046。管理器/句柄原生提供者、旧分支动态覆盖、生产页面账号及完整构建仍待完成。\n' 
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameNormalPoolDestruction','--result','pass','--evidence','529 integrated checks and8 independent actual Play Mode checks; complete pool and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded529; full goal active.')
