from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/loading-page-native-validation.json');assert r['passed'] and len(r['checks'])==741;assert n['passed'] and len(n['checks'])==23
methods=read(O/'method-map.json');ids={31471,31489,31491,31505,31509,31522,31529,31530,31533,31535,34200,34203,30397,30416,30438,30443,32694,32697,32703,30193}
ids.update(x['metadata'] for x in methods if x['cls']=='TransformTools' and x['method']=='FindNearCanvas')
ids.update({33551,33560,33566,33549,33557,33552,33553,33570,33564,33558,33556,33567,33547,33548})
selected=[dict(x,sha256=hashlib.sha256((O/x['path']).read_bytes()).hexdigest()) for x in methods if x['metadata'] in ids]
write(O/'LEVEL_LOADING_SOURCE_EVIDENCE.json',{'atUtc':now,'methods':selected,'qualification':'Source IDs include explicit incomplete post-prepare LevelControl31535 boundary. No claim that LevelControl/PlayerControl lifecycle is fully implemented.','genericResolution':{'methodSpecTable':483008,'genericInstPointerTable':72592,'independentParentContexts':{'557':'Level4107','564':'Player4462','574':'UI4296'},'levelTupleUsages':{'3986656':'Item1','3986660':'Item2','3986652':'ctor','3986664':'Item3','4013044':'ScriptableObject.CreateInstance<LevelInfoCfg>'}},'sourceTypes':{'LevelInfoCfg':4099,'Proj_xqzdLoadingUI':4387,'AutoCanvasLayer':3876},'disassembledMethodMapCount':len(methods)})
v={'atUtc':now,'scope':'Level config/resource and Player skin entity source helpers; concrete preload services; original loading-page import/runtime/UIControl methods','checksPassed':741,'newIntegratedChecks':12,'nativePlayModeChecks':23,'freshPlayModeRun':True,'freshPlayerBuild':False,'freshPlayerSmoke':False,'commands':['OutgameLevelResourceBundles.Build','RecoveredHudImporter.ImportLoadingBatch','BattleBuild.ValidateMechanicsOnly','OutgameLoadingPlayModeValidation.Run'],'notClaimed':'Full Level/Player lifecycles, actual complete preload entity asset set, complete Main/account/lobby, original matched rendering or remote service/device verification'}
a={'atUtc':now,'status':'partial-subsystem','sourceEvidence':'LEVEL_LOADING_SOURCE_EVIDENCE.json','verification':v,'findings':[
 'ConfigMgr level real-ID loop, stored CurrentLevelConfig, missing-key-only diagnostic, guide raw-id/upper-only index clamp and base-speed reset restored. Original table has561 entries and max560. No invented negative-level clamp.',
 'Player equipped/random skin-to-entity lookup uses actual SkinCatalog/config; camp clamped2..4 with independent enemy category arrays, fallbacktype*1000 and optional animation+3000. Enemy random calls9 in index/category order over original81/3 rows.',
 'LevelInfoCfg restored as ScriptableObject with Camp/Star/Obstacle arrays and shared IOutgameLevelLayout; existing battle LevelLayout implements interface without changing its fields/rules.',
 'LoadHomeLevel/LoadLevel deliberately always dispatch: source Item1!=id OR Item1==id predicate is exhaustive. Mutable resource arguments determine tuple IDs; home callback captures filename while game callback reads argument0. New tuple assigned before FromJsonOverwrite, previous SO not destroyed.',
 'Concrete OutgamePrefabPreloadServices uses live resource tuple, player skin resolver and actual loading page. Prepare completion remains explicit Action boundary for source31535 towers/obstacles/playUI/camera/coroutine, which are not all composed yet.',
 'Original Resources loading GameObject273 has10 nodes. Three serialized outlets decoded from raw68-byte MonoBehaviour1605 by metadata offsets32/44/56. Partial UGUI schemas decoded via exact-consumption same-class full schemas from authorized bundles; raw hashes and schema provenance recorded separately.',
 'Recovered11sprites and1font, SpriteRenderer source552 sortinglayerTop/order99, Animator52/Pulbic_man001 and sourceclip49/lodingSoldier. Six streamed PPtr frames at12fps loop0.5sec; negative initial sentinel normalized to0. Native PPtr keys hold for one sample, so no extra seventh hold key.',
 'AutoCanvasLayer Start walks parents excluding self, copies parent layer, enables override and adds original offset25. Native test validates source parentCanvas42 => nested67.',
 'Loading page preserves initial0.6..0.8 random range/1second defaultOutQuad, anchor825, N0 percent, earlyClose then final1-current duration, strict timeout>, SetSpine5 withoutreset, retry destroy thenstate10false and cancel transitioncallback then destroy/state11false.',
 'Singleton cleanup is unconditional even when an older page closes after a newer page opens. Unity destruction is deferred. UIControl Close/Reset use CLR reference checks, allowing managed timer writes on a destroyed native owner, verified natively.',
 'UIControl original Resources path explicitly maps to recovered prefab, creates on everyOpen and parents under actual UiNodes UIStory with worldPositionStays=false. Bind must occur before page Start; full Main/UI host composition remains open.',
 '12 new integrated cases load rebuilt native bundles from recovered original level1/2 data. Prefab template cache is explicitly synthetic warm test data to isolate config/callback behavior; this does not prove full entity preload asset availability. No fake account/platform callbacks used.',
 'Failed first import was Unity fake-null GetComponent combined with CLR ??; changed importer to Unity truth checks. Failed first integrated run was test fixture null loadEditorConfig dependency, fixed. First native animation check found extra PPtr hold key, corrected. Failure logs preserved.'
 ],'remaining':['Complete Level4107 lifecycle/update/state/tower/obstacle/post-prepare graph and Player4462 lifecycle, then bind their actual services into full Main. Lifecycle coverage stays8/38, remaining30.','Supply real loading host common-tip/transition/level-state providers in complete UI graph; current native host verifies callback ordering only.','Restore all actual fixed preload entity templates and source resource addresses; warm synthetic templates are test-only.','Finish all objective subsystems and full persistent restart/failure/Player build acceptance; production scene remains Battle.unity.'], 'artifacts':{'import':'analysis/unity-loading-import-report.json','decoded':'generated/outgame/LOADING_UI_DECODED_COMPONENTS.json','manifest':'generated/outgame/loading-ui-import.json','integratedLog':'analysis/level-resource-integrated-fixed.log','nativeLog':'analysis/loading-page-native-fixed.log','nativeReport':'analysis/loading-page-native-validation.json'}}
write(O/'LEVEL_LOADING_AUDIT.json',a)
p=O/'LOADING_UI_SOURCE_AUDIT.json';d=read(p);d.update(qualification='Original binary/schema-backed hierarchy, outlets and animation recovered. Runtime behavior and23 native checks recorded in LEVEL_LOADING_AUDIT.json; original matched rendering remains unverified.',runtimeAudit='LEVEL_LOADING_AUDIT.json');write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,levelLoadingAudit='LEVEL_LOADING_AUDIT.json',verification=v);d['remaining'][0]=a['remaining'][0];write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='level-config-player-skins-loading-page',levelLoadingAudit='generated/outgame/LEVEL_LOADING_AUDIT.json',nextPriority='Complete LevelControl4107 lifecycle/update/post-prepare towers/obstacles/playUI/camera graph and PlayerControl4462 lifecycle using new source resource/skin helpers. Bind real loading host into Main/UI; actual preload entity assets remain incomplete. Remaining30 controllers, all objective subsystem and full persistence/Player acceptance requirements preserved.');d['validation']['integratedChecksPassed']=741;d['validation']['levelLoading']=v;d['validation']['loadingPageNative']=n;d['milestones']=[m for m in d['milestones'] if m['id']!='level-config-player-skins-loading-page'];d['milestones'].append({'id':'level-config-player-skins-loading-page','atUtc':now,'status':'partial-subsystem','integratedChecks':741,'nativeChecks':23,'remainingControllers':30});write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=741,latestValidation=v);d['validationHistory'].append(v)
for path in ['analysis/loading-page-native-validation.json','analysis/unity-loading-import-report.json']:
 if path not in d['reports']:d['reports'].append(path)
files=[p for p in (W/'UnityProject/Assets/AreaBattle').rglob('*') if p.is_file() and (p.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in p.as_posix() or '/Recovered/Loading/' in p.as_posix())]
d['sourceFingerprints']=[{'path':p.relative_to(W).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files)];d['levelLoadingBundles']=[{'path':f'analysis/level-resource-native-bundles/level-{i}','sha256':hashlib.sha256((W/f'analysis/level-resource-native-bundles/level-{i}').read_bytes()).hexdigest()} for i in (1,2)];write(p,d)
text='''\n\n## 2026-09-30 关卡配置、皮肤实体与原始加载页增量\n- 新增源配置/资源片段 OutgameLevelConfigAccess、OutgameLevelResourceState、OutgameLevelConfigAsset(ScriptableObject)、OutgamePlayerSkinEntities；真实 tuple/皮肤/加载页由 OutgamePrefabPreloadServices 连接。完整 Level4107/Player4462 生命周期仍未完成，8/38不变。\n- 恢复原 Resources 加载页10节点/3引用/11sprites/1font；原六帧12fps/.5秒循环动画、AutoCanvasLayer偏移25、进度/超时/重试/返回。UIControl Open/Close/Reset与原资源路径→恢复prefab映射已实现。全Main/UI host仍待接。\n- 741集成（新增12）+23加载页原生检查通过。原生验证Animator/UGUI/默认OutQuad/825位移/严格超时>/state10、11时序/延迟销毁/旧页清新Singleton/CLR已销毁对象字段写。\n- 集成关卡测试用原始关卡1/2重建原生bundle；模板缓存显式测试fixture，不能当成所有实体预加载已可用。没有新Player构建。首次导入fake-null、测试fixture缺依赖、动画额外尾键失败日志保留，修复后通过。\n- 审计O/LEVEL_LOADING_AUDIT.json、LEVEL_LOADING_SOURCE_EVIDENCE.json；method-map4612。日志analysis/level-resource-integrated-fixed.log和loading-page-native-fixed.log。\n- 下一步完整Level生命周期/update/Prepare后初始化与Player生命周期、真实loading host/Main/所有缺失实体资源，继续全部关外与持久化/构建验收。无本任务待续进程。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('729 项 checks','741 项 checks').replace('caseCount=729；latestValidation 为 LoadPrefabControl entity/preload + native pool','caseCount=741；latestValidation 为 level config/player skins/loading page').replace('最新method-map4565','最新method-map4612').replace('in_progress / entity-preload-source-and-native-pool','in_progress / level-config-player-skins-loading-page').replace('最新集成日志 analysis/entity-preload-integrated.log；实体池原生日志 analysis/entity-pool-native.log。729集成+13实体池原生通过；历史资源链/Game/UI/基础控制器原生分别8/7/6/10项通过。无本任务待续进程。','最新集成日志 analysis/level-resource-integrated-fixed.log；加载页原生日志 analysis/loading-page-native-fixed.log。741集成+23加载页原生通过；历史实体池/资源链/Game/UI/基础控制器原生分别13/8/7/6/10项通过。无本任务待续进程。');s+=text;p.write_text(s,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameLevelLoadingNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/LEVEL_LOADING_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps({'checks':741,'native':23,'fingerprints':len(files),'sourceMethods':len(selected),'remainingControllers':30}))
