from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-player-models-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==352
sources=['disassembly/Type4462-34205.txt','disassembly/Type4462-34197.txt','disassembly/Type4462-34194.txt','disassembly/Type4458-34213.txt','disassembly/Type4459-34215.txt','disassembly/Type4462-34210.txt','player-cache-generic-resolution.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='player-model-load-lifecycle';s['validation'].update(integratedChecksPassed=352,playerModelChecksPassed=3);s['nextActions']=['Recover equipped model color/animation helper, virtual methods and completion callback; connect real model assets and source roots.','Connect concrete shop effects and original account lifecycle.','Complete remaining outgame systems and fresh playable lobby build/end-to-end validation.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['player-model-load-lifecycle']={'implementationReady':True,'productionConnected':False,'scope':'Required-provider two-stage model loader and category cache/display; animation callback deliberately required, actual source adapter pending.','source':sources,'implementation':['OutgamePlayerModels.cs'],'validation':'Three isolated Unity cases: transform/layer/cache timing; asynchronous late callback and attack resource mapping; duplicate pending requests and replacement.'};write(p,s)
p=o/'PLAYER_DISPLAY_AUDIT.json';s=read(p);s['confirmed'][1]['fact']='LoadModel uses SkinConfig prefabId; category3 adds1000 and selects9034, other categories9033. Entity callback sets active, parent(false), source local position, zero Euler angles, source uniform scale and recursive parent layer. Auxiliary callback parents attachment(false), sets localPosition zero, then assigns cache[config.skinType][config.id] and invokes completion.';s['confirmed'][1]['source']=sources[2:5];s['confirmed'].append({'fact':'Display activates only requested cache key, then calls equipped animation helper. Cache setter replaces existing entry; in-flight loads are not deduplicated and late completion displays its own requested key. Auxiliary transform scale/rotation are not rewritten.','source':sources});s['confirmed'].append({'fact':'Animation helper reads currently equipped ID, applies Soldier.SetSoldierColor before activeSelf guard, caches animator, invokes unresolved virtual reset, plays relax nonlooping and assigns completion. Completion rereads equipped ID and plays idle looping on its cached animator or captured fallback.','source':['disassembly/Type4462-34211.txt','disassembly/Type4461-34219.txt']});s['pending']=['Resolve animation virtual reset, concrete color/animation adapter and pooled lifecycle','Source model roots/camera, scale/position defaults and actual prefab import coverage','Swipe/rotation continuous input behavior'];write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='PlayerControl two-stage model-load lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'PlayerControl two-stage model-load lifecycle','checksPassed':352,'outgameChecksPassed':85,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Production model/animation wiring or complete playable lobby'};write(p,s)
note='\n\n## 商店模型加载生命周期（352项）\n新增 OutgamePlayerModels：原实体/附属资源两阶段加载、父节点与局部变换、递归层级、分类模型缓存和显示切换。泛型元数据确认缓存使用 set_Item；保留加载中重复请求、晚回调覆盖显示与缺配置无加载回调。3项新增异步顺序测试通过，Unity退出0，集成352项（原267+关外85）。动画适配器、真实模型资源与展示根节点尚未接入，完整目标仍未完成。下一步恢复动画虚方法与具体资源/根节点。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgamePlayerModelLifecycle','--result','pass','--evidence','352 integrated checks; isolated model lifecycle verified, real visual/animation wiring incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded352; complete outgame goal remains active.')
