from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==488
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='store-data-manager';s['validation'].update(integratedChecksPassed=488,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['store-data-manager']={'implementationReady':True,'productionConnected':False,'source':['STORE_MANAGER_AUDIT.json','store-serialization-fields.json','store-default-array.json','disassembly/Type4092-31398.txt','disassembly/Type4092-31401.txt','data-manager-registration-roster.json'],'implementation':['OutgameStoreDataManager.cs'],'scope':'Source store record/constructor/reset/wire and manager lifecycle, download deferral, empty create-decode-create and file restart. Source manager4092 has NO automatic registration attribute; not injected into production roster. Manual registration/reachability and UI consumers pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original store data model, manager lifecycle and isolated persistence') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original store data model, manager lifecycle and isolated persistence','checksPassed':488,'outgameChecksPassed':221,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Store model/manager implemented with source constructor/reset/private field serialization and create-decode-create ordering. Unity tests confirm runtime fields excluded, source ctor defaults restored, local isolated file restart preserves counts/time and server route defers. StoreDataManager4092 has no source registration attribute; earlier plan to connect automatic provider was corrected.488 checks pass, actual registration/page reachability unresolved.','source':['STORE_MANAGER_AUDIT.json','data-manager-registration-roster.json','store-serialization-fields.json','store-default-array.json'],'implementation':'OutgameStoreDataManager.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'STORE_MANAGER_AUDIT.json';audit=read(p);audit['status']='runtime_implemented_reachability_pending';audit['implementation']='OutgameStoreDataManager.cs';audit['checks']=488;audit['automaticRegistration']=False;audit['productionConnected']=False;audit['pending']=['Trace manual registration and actual game/page reachability before activating manager4092','Trace free-reward/purchase consumers and daily reset triggers','Verify missing nested/null JSON behavior and cross-account lifecycle'];write(p,audit)
note='\n\n## 商店数据模型与隔离存档实现（488项）\n新增OutgameStoreDataManager及原结构StoreRecord/Coin/Diamond，保留全局配置读取、构造默认数组、Reset顺序、private/NonSerialized字段、empty create/decode/create、下载延后和实例发布/清空。Unity验证源配置5/3/[20,20,20]、保留领取次数/Int64时间、运行字段不入JSON、真实隔离文件重启。发现并纠正先前接注册计划：原StoreDataManager4092的registration=null，不自动注入账户管理器池；独立实现未证明当前游戏可达。488项（战斗267+关外221）通过，Unity退出0。后续需查手动注册/消费者及每日触发；注册池实际已实现管理器仍为原3个，不算新增激活。目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameStoreDataManager','--result','pass','--evidence','488 integrated checks; original store wire, constructor/reset, deferred download and isolated file restart verified; manager lacks automatic registration and production reachability pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded488; full goal remains active.')
