from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();report=W/'analysis/unity-integrated-validation.json';r=read(report)
assert r['passed'] and len(r['checks'])==1020
assert 'AREABATTLE_INTEGRATED_PASS cases=1020' in (W/'analysis/shared-item-config-integrated.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['cls'] in ['ItemConfigMgr','GameItemConfig','GamePackageConfig','GameRewardConfig','GameProductConfig','RewardRangeData']]
findings=[
'Original ItemConfigMgr4534 constructor34551 creates fields8/12/16/20/32/36 only. Package/reward group dictionaries remain null. get_Instance34554 creates/publishes instance without InitMgr. Restored explicit owner slot preserves this separation.',
'InitMgr34550 selected Unity JSON route reads item/package/reward/product tables in order then calls34558. No clear. Source MemoryPack/alternate parser branches explicitly outside this implementation; InitLegacyUnityJson method names its supported route.',
'Shared GameItemConfig4527/GamePackageConfig4529/GameProductConfig4531/GameRewardConfig4533 and helper Lang3490/ListArrayInt3452 generated from metadata offsets/types in separate SharedItemConfig namespace; project GameItemConfig3942 remains distinct. Four UniqueID bodies34514/34523/34532/34541 confirmed boxing field8. Actual firstpack JSON reads79/4/16/10 records. Shared product groupID/itemId defaults0 because project-specific JSON lacks them; no guessed remapping.',
'BuildGroups34558 replaces package dictionary then enumerates rows, groups by packageId, keyed by packageRewardId. Outer/inner writes use Dictionary.set_Item (generic usages3954552/3955676). Then replaces reward dictionary grouped by rewardId, keyed by rewardItemId (3954568/3955688 set_Item). Duplicate row IDs overwrite, source row IDs need not equal table dictionary keys. Prefix failures retain partial replacement and skip later phases.',
'Product helper34552 enumerates Products.Values, row offset84 groupID, creates list using dictionary Add (3954820), then appends each row. Does not clear existing product groups; repeated initialization appends duplicate references.',
'GetPackageRewards34553/GetRewardItems34555 return existing live group; missing returns fresh empty dictionary without adding it. Calls before index creation fail on null as source.',
'GetRewardItemRanges34560 builds cache on miss from reward dictionary, stores original row reference at offset12 and snapshots row.weight(offset28) into inherited RandomObject3392 int offset8. Publishes cache using set_Item3954972 only after successful enumeration. Returns new list populated by live indexed loop, shares cached elements. Cache survives group rebuild, including missing-group empty caches.',
'GetGameItemConfig34557 uses receiver Items.TryGetValue. GetGameProductConfig34559 uses current singleton Products.TryGetValue. Existing null row returns null without log. Miss emits source object-array prefix and boxed id.',
'Dispose34556 clears range cache, then product groups, then current singleton slot. Four tables and package/reward groups survive. No try/finally; second-clear failure prevents slot reset. Stale object disposal clears replacement slot.'
]
limits=['No full ItemManager4500/factory or ItemModuleControl3875 binding yet; controller lifecycle remains13/38.','Only selected source-default legacy Unity JSON route implemented here; MemoryPack and alternate parser routes not claimed.','No new native PlayMode, Player build, real platform/account or full menu flow validation in this milestone.']
write(O/'SHARED_ITEM_CONFIG_SOURCE_EVIDENCE.json',dict(atUtc=now,methods=methods,metadataScript='analysis/generate_shared_item_schemas.py',criticalEvidence=findings,limits=limits))
v=dict(atUtc=now,scope='Shared item config4534 metadata schemas, source-default legacy Unity JSON, groups/cache/queries/owner slot',checksPassed=1020,newIntegratedChecks=12,nativePlayModeChecks=0,freshPlayModeRun=False,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly'],notClaimed='Full ItemManager/factory/ItemModule controller; full Main and outgame Player')
remaining='Continue ItemManager4500 and original FactoryBase4486/VirtualItem/PackageItem production behavior, then bind ItemModuleControl3875 using distinct shared config manager. Complete remaining25 controller lifecycles, full source-default legacy Main/account/menu/business graph and persistence/restart/failure/return flows, then runnable outgame Player acceptance. Modern alternate acquisition remains explicit unimplemented branch, not default startup prerequisite.'
a=dict(atUtc=now,status='shared-item-config-implemented-owner-composition-incomplete',sourceEvidence='SHARED_ITEM_CONFIG_SOURCE_EVIDENCE.json',verification=v,implementedLifecycleControllers=13,remainingLifecycleControllers=25,findings=findings,remaining=[remaining]+limits,disassembledMethodMapCount=len(mm),artifacts=dict(integratedLog='analysis/shared-item-config-integrated.log'));write(O/'SHARED_ITEM_CONFIG_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='shared-item-config',sharedItemConfigAudit='generated/outgame/SHARED_ITEM_CONFIG_AUDIT.json',nextPriority=remaining);d['validation']['integratedChecksPassed']=1020;d['validation']['sharedItemConfig']=v;d['milestones'].append(dict(id='shared-item-config',atUtc=now,status=a['status'],integratedChecks=1020,remainingLifecycleControllers=25));write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=1020,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=report.stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 共享道具配置增量\n- 1020集成全通过（新增12），log analysis/shared-item-config-integrated.log；本轮Unity69928已退出，无新native/Player。method-map5147；controller仍13/38、25余。本轮没有声称ItemModule生命周期完成。\n- 新OutgameSharedItemSchemas.cs由analysis/generate_shared_item_schemas.py按原metadata生成6类（共享4527/4529/4531/4533、Lang3490、ListArrayInt3452），独立AreaBattle.SharedItemConfig命名空间，防止与项目玩法类型3942混用。同名原始firstpack JSON真实读取79/4/16/10条。共享product字段groupID/itemId原JSON不存在则保持0，16条全入group0，不编造字段映射。\n- 新OutgameItemConfigManager.cs：构造六个dictionary（package/reward index初始null）、slot lazy创建不自动Init；InitLegacyUnityJson显式选择原始Unity JSON支路，四表顺序item/package/reward/product读后BuildGroups，不清表。MemoryPack/alternate parser尚未绑定且未伪装支持。\n- BuildGroups先替换package index→foreach按packageId/packageRewardId indexer覆盖，再替换reward index→按rewardId/rewardItemId覆盖，再Products.Values按groupID追加既有List（不clear）。泛型usage3954552/3955676/3954568/3955688均set_Item，3954820商品外层Add。失败保留已执行前缀，后续阶段不运行。\n- Package/Reward查询miss新建空dictionary不cache，hit返回原引用。GetRewardItemRanges34560缓存原GameRewardConfig引用与weight snapshot（RandomObject3392 int offset8）；cache成功构建才publish，返回浅拷贝List/复用元素；group rebuild不clear cache。GetGameItemConfig使用receiver，GetGameProductConfig使用当前slot。Dispose只clear两个cache后clear当前singleton，保留原四表和两组；旧receiver仍会清掉新slot，异常保留前缀。\n- 新OutgameItemConfigValidation12checks覆盖以上原表解析/重复初始化109重复日志和商品32项、分组重复id覆盖、浅拷贝和权重快照、空cache不失效、失败前缀、getter旧对象/当前singleton差异、dispose顺序。通过真实Unity JsonUtility+Resources加载恢复JSON，但无native资源传输新验证。\n- O/SHARED_ITEM_CONFIG_SOURCE_EVIDENCE.json/AUDIT.json、SHARED_ITEM_CONFIG_SCHEMAS.json记录源方法hash、元数据和范围；analysis/inspect_shared_item_metadata.py可重查字段/泛型。新抽取GamePackageConfig/GameRewardConfig/RewardRangeData至methodmap5147。\n- 下一步ItemManager4500 wrapper和FactoryBase4486→VirtualItem_Factory4488/PackageItem_Factory4487→实际item entities，再ItemModuleControl3875接线。工厂和manager源已在O/disassembly，尚未实现，不用GlobalItemLifecycle直接冒充。全目标继续active。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('1008 项 checks','1020 项 checks').replace('caseCount=1008；latestValidation 为 Buff/Tool controller registration','caseCount=1020；latestValidation 为 shared item config').replace('最新集成日志 analysis/buff-tool-controller-integrated.log。1008集成通过','最新集成日志 analysis/shared-item-config-integrated.log。1020集成通过').replace('in_progress / buff-tool-controller-registration','in_progress / shared-item-config').replace('最新method-map5089；13控制器','最新method-map5147；13控制器');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameSharedItemConfig','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/SHARED_ITEM_CONFIG_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
assert all(hashlib.sha256((W/f['path']).read_bytes()).hexdigest()==f['sha256'] for f in d['sourceFingerprints'])
print(json.dumps(dict(checks=1020,controllers=13,remaining=25,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
