from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==383
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='data-version-state';s['validation'].update(integratedChecksPassed=383,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Resolve and implement GameDataVersionMgr reload/upload/download branches and inherited login failure handling.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['data-version-state']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs'],'scope':'Original per-key version increment, dual pending-list completion, forced-upload flag update, persistence-before-event and close cleanup. Full version-file IO, manager reload and transport remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original data version increment and synchronization completion') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original data version increment and synchronization completion','checksPassed':383,'outgameChecksPassed':116,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
note='\n\n## 数据版本状态（383项）\n新增OutgameDataVersionState，保留首次版本-1递增到0、整数溢出、空键拒绝、双待处理列表门控、强制上传标志更新和先持久化后完成事件。关闭同步只清指定标志/队列，保留两份版本字典且不发完成事件。3项验证通过，集成383项（原267+关外116），Unity退出0；源方法1004。原版版本文件IO、传输与账号入口仍待补齐。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameDataVersionState','--result','pass','--evidence','383 integrated checks; data version and completion ordering verified; full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded383; full goal remains active.')
