from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-skin-item-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==348
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='original-skin-icon-atlas-binding';s['validation'].update(integratedChecksPassed=348,skinItemActionChecksPassed=14)
s['nextActions']=['Capture and visually verify assembled original shop with real skin posters.','Bind source shop lifecycle/events and activity/video/scene providers, then account startup.','Complete remaining outgame systems and playable build/end-to-end validation.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['skin-original-posters']={'implementationReady':True,'scope':'96 configured original SkinConfig/SceneSkinConfig posters with atlas-qualified resource binding','rules':['Resolve each soldier iconName only from skinandtoolicon.spriteatlas and each scene iconName only from sceneskin.spriteatlas. Exactly one matching source Sprite required.','Carry original source id, atlas, bundle path, PNG hash/pivot/PPU/border through import manifest. Runtime resolves by skinId and source id, not first matching name; unrelated guide tubiao01..04 cannot shadow scene icons.'],'source':['ui-import.json','../tables/SkinConfig.json','../tables/SceneSkinConfig.json','disassembly/Type4364-33366.txt'],'implementation':['outgame_ui_prepare.py','OutgameSkinSprites.cs'],'validation':'All configured card img_poster references equal their atlas-qualified loaded Sprite, including scene and soldier families. Full visual composition capture pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='SkinItem original atlas icon lookup') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'All original configured skin posters with atlas-qualified identities','checksPassed':348,'outgameChecksPassed':81,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Shop acquisition/payment/UI, complete account startup or playable lobby'};write(p,s)
note='\n\n## 原皮肤图标资源（348项）\n96个SkinConfig/SceneSkinConfig图标已全部由原skinandtoolicon/sceneskin图集精确定位并导入，资源清单从134到230个Sprite。场景tubiao01..04与引导图集存在同名冲突，改用skinId到原Sprite ID映射，记录图集/包路径/像素文件哈希与导入参数，运行时缺失明确失败。全皮肤卡片img_poster绑定验证通过，Unity退出0，348集成检查（原267+关外81）。尚需组装商店视觉检查、生产生命周期/事件和平台提供者、账户启动及新构建；完整目标继续active。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
for name in ['unityCompile','outgameCommanderCore','outgameInventoryCore','outgameToolDispatchCore','outgameProfileStore','outgameMenuNavigation','outgameCommanderActions','outgameUiImport','outgameMenuView','outgameCommanderView','outgameLevelProgression','outgameOriginalLocalData','outgameOriginalCommanders','outgameSkinRecords','outgameSkinActions','outgameSkinItemActions','outgameSkinItemView','outgameSceneSkinActions','outgameSceneSkinView','outgameSkinOrder','outgameShopSkinLists','outgameShopTabs','outgameToggleBindings','outgameShopInitialSelection','outgameSkinPosters']:
 subprocess.run(b+['set-check']+a+['--name',name,'--result','pass','--evidence','348 integrated checks passed including skin item callbacks and isolated restart; full outgame incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded 348 checks; full goal remains incomplete.')
