from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==466
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='wx-video-adapter-composition';s['validation'].update(integratedChecksPassed=466,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['wx-video-adapter-composition']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type9186-64358.txt','disassembly/Type9186-64360.txt','disassembly/Type9186-64361.txt','disassembly/Type9186-64362.txt','disassembly/Type7488-54721.txt'],'implementation':['OutgameWxVideoAdapter.cs'],'scope':'One adapter identity composes loading, presentation, notifications, timeouts and price cache; implements controller cache and preload candidates. Injected native handle exercises actual serial listener reward chain. Live runtime and original controller initialization remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original Wx video adapter composition and controller callback lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original Wx video adapter composition and controller callback lifecycle','checksPassed':466,'outgameChecksPassed':199,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Concrete Wx video adapter composes recovered loading/presentation/notification/timeouts/price cache using one source identity. Notification cancellation routes to owned timers. Actual serial listener receives native load, show and close callbacks; controlled handle proves reward completion, load timeout recovery and delayed autoload reuse.466 integrated checks pass; live SDK and production initialization remain pending.','source':['disassembly/Type9186-64358.txt','disassembly/Type9186-64360.txt','disassembly/Type9186-64361.txt','disassembly/Type9186-64362.txt'],'implementation':'OutgameWxVideoAdapter.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'WX_VIDEO_ADAPTER_AUDIT.json';audit=read(p);audit['composition']={'implemented':True,'productionConnected':False,'path':'OutgameWxVideoAdapter.cs','validation':'466 integrated checks pass; controlled native handle, actual serial listener and owned timer wiring','pending':['Live platform runtime','Original controller initialization selection','Prediction response processing']};write(p,audit)
note='\n\n## 微信视频适配器组合与控制器链（466项）\n新增OutgameWxVideoAdapter，以同一对象连接加载、展示、通知、超时和价格缓存，并同时参与预加载队列与控制器缓存。通知取消直接作用于适配器自身的协程句柄。受控原生句柄通过真实Serial监听器完成加载→展示→奖励→关闭，另验证加载超时清理/重试和自动加载延迟复用。466项（战斗267+关外199）通过，Unity退出0。真实微信Runtime、原始控制器配置选择与预测响应仍待完成，未声称SDK/生产入口或完整关外完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameWxVideoAdapterComposition','--result','pass','--evidence','466 integrated checks; composed adapter and serial listener native reward chain, load timeout retry and delayed autoload verified; actual platform runtime pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded466; full goal remains active.')
