from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==522
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-runtime-composition';s['validation'].update(integratedChecksPassed=522,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-runtime-composition']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4058-31210.txt','disassembly/Type4058-31214.txt','disassembly/Type4058-31216.txt','disassembly/FlyNativeMath-1108.txt','disassembly/FlyNativeMath-1114.txt'],'implementation':['OutgameFlyRuntime.cs','OutgameFlyScatter.cs'],'scope':'MonoBehaviour composition of source economic entry, coroutine, tween, ids, cleanup with mandatory audio/pool dependencies. Shop/account production binding and full animation verification pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Fly runtime composition and source scatter') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Fly runtime composition and source scatter','checksPassed':522,'outgameChecksPassed':255,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Scatter consumes shared inclusive angle0..360 then radius10..20, radius/10f and angle*.017f, y sin evaluated before x cos. Runtime composes real economic/coroutine/tween/id/cleanup classes; source wrappers play voice before target-null grant suppression.','source':['disassembly/Type4058-31210.txt','disassembly/Type4058-31214.txt','disassembly/Type4058-31216.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'FLY_RUNTIME_AUDIT.json';write(p,{'status':'composition_compiles_boundaries_verified_pool_page_pending','checks':522,'source':['disassembly/Type4058-31210.txt','disassembly/Type4058-31214.txt','disassembly/Type4058-31216.txt','disassembly/FlyNativeMath-1108.txt','disassembly/FlyNativeMath-1114.txt'],'verified':['Source scatter draw order, inclusive ranges, .017f angle and radius/10f arithmetic','Runtime connects existing economic entry, coroutine, actual tween runner, shared id registry and cleanup classes','Gold voice1/2019 and provider-resolved diamond voice run before missing-target suppression','No simulated pool/audio success: explicit dependencies required'],'limits':['Only missing-target runtime branch tested this turn, not successful real-time end-to-end animation','Mathf sin/cos adapters are not bitwise compared to original native sinf/cosf across entire input range','Original NormalPool resource loading/reuse/release semantics and live callbacks pending','Page lifecycle/disposal/rebinding and real TopInfo/account providers pending']})
note='\n\n## 飞行动效宿主组合与散点（522项）\n新增OutgameFlyRuntime将真实入账入口、协程、原生Tween、共享编号和清理组合为MonoBehaviour；对象池与音频要求显式提供，未模拟成功。恢复散点原共享随机顺序：角0～360、半径10～20，再按angle*0.017f和radius/10f算y sin/x cos。原生math包装已提取，Mathf适配的全输入位级一致性仍未验证。522项（战斗267+关外255）通过，Unity退出0；验证散点调用顺序及宿主目标为空时先音效、不入账/不动画。尚未验证宿主成功路径的真实时间动画；NormalPool加载/回收、页面生命周期和账号连接待继续。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyRuntime','--result','pass','--evidence','522 integrated checks; runtime missing-target boundaries and scatter sequencing verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded522; full goal remains active.')
