from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==509
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-product-prices';s['validation'].update(integratedChecksPassed=509,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-product-prices']={'implementationReady':True,'productionConnected':False,'source':['product-price-generics.json','product-price-control-flow.json','PRODUCT_PRICE_AUDIT.json','disassembly/Type4547-34610.txt'],'implementation':['OutgameProductPrices.cs'],'scope':'Original six array/scalar modes, count lookup, compact indexing, integer arithmetic, error continuation, allocation and scalar gates; reset composition validated. Random/power providers remain explicit dependencies pending source sequence and precision equivalence.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original product array and scalar price formulas') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original product array and scalar price formulas','checksPassed':509,'outgameChecksPassed':242,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Price control-flow confirms each array exception logs and continues, scalar exception logs and retains prior value. RandomHelper integer overload uses Random.Next(min,unchecked(max+1)). Implemented six array/scalar formulas with separate per-item/product counts, compact indexing, only-null allocation, Int32 wrap/float cast, detached missing lookups; reset composition passes.509 checks pass; random/power provider equivalence pending.','source':['product-price-control-flow.json','product-price-generics.json','disassembly/Type3391-26192.txt'],'implementation':['OutgameProductPrices.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='lifecycle_scheduling_resets_price_formulas_implemented_providers_pending';audit['priceImplementation']={'files':['OutgameProductPrices.cs'],'checks':509,'source':['product-price-control-flow.json','product-price-generics.json'],'detail':'Six array/scalar modes, separate purchase counts, compact indexes, allocation, original arithmetic and exception scopes. Resets call real formula implementation. Random and power delegates remain required source platform dependencies.'};audit['pending']=['Resolve source random list primitive and verify random/power production providers','Implement reward side effects and statistics bus production host','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 商品价格公式实现（509项）\n新增OutgameProductPrices恢复数组与单一价格六模式、不同计数来源、压缩索引、仅null分配、缺失计数不入列表、Int32溢出及原浮点转整型门。原控制流证明数组单项异常记录后继续，单一价格异常保持旧值。与实际ProductResets组合验证，重置后价格在UI消息前更新。随机整数调用证实Next(min,unchecked(max+1))，随机列表/原生power精度与真实平台序列仍待对齐，当前作为显式依赖。509项（战斗267+关外242）通过，Unity退出0；首次新增用例循环价格预期算错，已按3%(3-1)+1=2修正fixture后重验通过。全目标仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameProductPrices','--result','pass','--evidence','509 integrated checks; source array/scalar price modes, error continuation, numeric rules and actual reset composition verified; random/power and production providers pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded509; full goal remains active.')
