from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==518
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-tool-cleanup';s['validation'].update(integratedChecksPassed=518,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-tool-cleanup']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4058-31221.txt','disassembly/Type4058-31223.txt','disassembly/Type4058-31219.txt','disassembly/Type4058-31209.txt','fly-tween-cleanup-generics.json'],'implementation':['OutgameFlyToolCleanup.cs'],'scope':'Source deferred cleanup, strict time thresholds, complete=true child tween kill and removal order; production animation host pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Source fly-tool cleanup and timing') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Source fly-tool cleanup and timing','checksPassed':518,'outgameChecksPassed':251,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'EffectControl.StopEffect enqueues existing coroutine ids without deduplication. Updata drains pending before timeout scan. Timeout uses Time.time>nextCheck and age>4; nextCheck += Time.time+1. Removal kills child tween ids with complete=true, stops coroutine, removes both dictionaries then subids.','source':['disassembly/Type4058-31221.txt','disassembly/Type4058-31223.txt','disassembly/Type4058-31219.txt','disassembly/Type4058-31209.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'FLY_TOOL_CLEANUP_AUDIT.json';write(p,{'status':'cleanup_controller_verified_host_pending','checks':518,'source':['disassembly/Type4058-31221.txt','disassembly/Type4058-31223.txt','disassembly/Type4058-31219.txt','disassembly/Type4058-31209.txt','fly-tween-cleanup-generics.json'],'verified':['StopEffect queues only tracked id and does not deduplicate','Update drains pending before timeout checks','Child ids fly_{id}_{sub} are killed with complete=true, then stop coroutine, remove coroutine/time entries and subids','Strict time>nextCheck and age>4; nextCheck=old+(Time.time+1), preserving repeated clock reads','Exceptions preserve source partial state, including duplicate stop queue failure'],'tweenResolution':{'4017576':'OnComplete','4017676':'SetUpdate(bool independentUpdate)','4017592':'SetAutoKill','4017620':'SetId','4017552':'Pause','4017616':'SetEase'},'pending':['Actual native pool, tween and scheduler host','Verify tween easing enum and implementation against original before constructing animation','Runtime concurrent effects and complete callback reentrancy']})
note='\n\n## 飞行动效清理控制器（518项）\n新增OutgameFlyToolCleanup，恢复StopEffect仅排队、下一次Update先清理再扫超时的顺序；严格Time.time>检查阈值且年龄>4秒才排队，阈值保留原累计式old+(Time.time+1)。清理按子ID逐项Kill(complete=true)，再停协程、移除协程/时间字典及子ID。保留重复排队与异常中间态，不擅自去重。解析原泛型调用确认OnComplete/SetUpdate/SetAutoKill/SetId/Pause/SetEase。518项（战斗267+关外251）通过，Unity退出0。生产动画池、Tween及调度宿主仍待连接；无新Player构建。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyToolCleanup','--result','pass','--evidence','518 integrated checks; source deferred cleanup, strict timeout and failure state verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded518; full goal remains active.')
