from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
v=read(w/'analysis/outgame-menu-validation.json');r=read(w/'analysis/unity-integrated-validation.json');assert v['passed'] and r['passed'] and len(r['checks'])==297
now=datetime.now(timezone.utc).isoformat()
contract={'implementationReady':True,'scope':'Runtime route identities, supported 2/3/4 navigation state and commander overlay; no complete page view or animation claim. MenuTabConfig alone does not establish runtime reachability.','rules':[{'id':'runtime-pages','value':{'2':'ShopUI','3':'Proj_xqzdStartUI','4':'CommanderUI'},'source':['disassembly/Type4296-32705.txt','disassembly/Type4296-32729.txt','disassembly/Type4296-32714.txt','disassembly/Type4296-32708.txt','disassembly/Type4296-32698.txt'],'offsets':['00477334..00477365','00280811..0028083e'],'correction':'Legacy MenuTabConfig id4 inactive HerosDetailUI must not suppress actual CommanderUI runtime route. IDs1/5 runtime calls exist but have no mapped page transform in this method; investigate visibility before including as valid navigation.'},{'id':'switch-lock','value':'No current page => immediate display and CanCheckTab=true. Otherwise reject same page and while CanCheckTab=false. Transition sets false; callback reparents incoming and sets true, hides outgoing.','source':['disassembly/Type4379-33486.txt','disassembly/Type4296-32705.txt','disassembly/Type4295-32744.txt']},{'id':'slide','value':'target<current: incomingX=-width,outgoingTargetX=+width; otherwise opposite; duration0.3 seconds. Easing not established here.','source':'disassembly/Type4296-32705.txt','offsets':['00477435..0047747b','004774b0..004774f0']},{'id':'main','value':'Return helper uses CheckUI(3), then MoveCamera on accepted return.','source':'disassembly/Type4379-33464.txt'},{'id':'commander-lock-overlay','value':'Level data < CommanderConfig[1].unlockLevel shows lock overlay; observed configuration value6. This is an overlay gate, not an extra check inside CheckUI.','source':'disassembly/Type4379-33472.txt','offsets':['005557bc..00555800']}]}
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['runtime-menu-navigation']=contract;write(p,s)
write(o/'runtime-entry-map.json',{'target':'wxcf1394487200e48f/43','status':'partial','runtimePages':contract['rules'][0],'pending':['Map remaining overlay/popup buttons and runtime hiding of tab1/5.','Resolve OpenAllMenuItemUI generic coroutine type arguments.','Bind actual page views and transitions, source HUD assets and battle return.'],'methodInventoryCount':323})
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in v['checks']};s['cases']=[c for c in s['cases'] if c['id'] not in ids]+[dict(c,sourceContract='OUTGAME_RESTORE_SPEC.json#subsystemGates.runtime-menu-navigation') for c in v['checks']];write(p,s)
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=now;s['currentStage']='runtime-menu-view-and-consumers';s['validation'].update(integratedChecksPassed=297,menuNavigationChecksPassed=4);s['nextActions']=['Bind actual three runtime page views to profile and navigation; source HUD assets and original reachable callbacks.','Trace commander UI upgrade/select actions, stats and save ordering; bind durable profile.','Trace runtime popup/store/skin entity flows and finish IOutgameToolEffects consumers.'];s['milestones'].append({'id':'runtime-menu-navigation','atUtc':now,'checks':4,'status':'partial-subsystem'})
for x in s['subsystems']:
 if x['id']=='entry-navigation':x.update(evidenceStatus='Runtime2/3/4 routes confirmed; legacy MenuTabConfig is not authoritative for CommanderUI reachability.',implementation='source switch state and commander overlay predicate implemented; page views pending',validation='4 navigation checks pass; full playable lobby pending')
write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Runtime menu routing and transition state','checksPassed':297,'outgameChecksPassed':30,'freshPlayerBuild':False,'freshPlayerSmoke':False,'commands':['BattleBuild.ValidateMechanicsOnly'],'notClaimed':'Playable lobby views, animation presentation or complete account/consumers'};write(p,s)
note='''\n\n## 运行时菜单证据修正与切换状态（297项）
重要修正：MenuTabConfig id4 isActive=false仅描述旧HerosDetailUI记录，不能据此判定指挥官不可达。新提取UIControl共52方法（总323），OpenMenuItemUI/GetMainUITrans直接路由2→field28 ShopUI、3→field32 Proj_xqzdStartUI、4→field36 CommanderUI，三个getter确证。MenuTabUI点击4调用CheckUI(4)再CommanderControl.ShowCommanderGuild；使用配置禁用4会错误丢失真实入口。旧表保持原样，生产OutgameMenuNavigation按真实运行时映射。
已实现首次即时显示、当前页重复点击拒绝、过渡期间锁定、目标方向与源码0.3秒时长、完成回调解锁、返回主页面3，以及CommanderConfig[1].unlockLevel驱动的锁定覆盖层判据（5锁/6开）。实际动画/easing、RectTransform重挂和页面呈现尚未接入，不得宣称大厅可玩。1/5仍需追踪按钮隐藏与弹窗，不能因为表isActive=true就列为可滑动页面。
4项新检查通过，集成297，Unity批处理退出0。新增runtime-entry-map.json及spec gate。下一步把三页实际视图接到存档，追踪CommanderUI选择/升级操作与统计/保存，再补皮肤/商店实体消费者。无新玩家构建，完整关外目标保持active/incomplete。
'''
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
for name in ['unityCompile','outgameCommanderCore','outgameInventoryCore','outgameToolDispatchCore','outgameProfileStore','outgameMenuNavigation']:
 subprocess.run(b+['set-check']+a+['--name',name,'--result','pass','--evidence','297 integrated checks pass including4 runtime-menu state checks; no new player build or complete lobby.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded297 checks; runtime route correction saved; full goal incomplete.')
