from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/prefab-loader-native-validation.json');assert r['passed'] and len(r['checks'])==718;assert n['passed'] and len(n['checks'])==8 and n['requests']==5
v={'atUtc':now,'scope':'Source Path/ResLoadHelper/LoadPrefabControl loading branches and GameControl integration through native bundle runtime','checksPassed':718,'nativePlayModeChecks':8,'nativeRequests':5,'freshPlayModeRun':True,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'LoadPrefabControl entity-pool/preload business paths, remaining30 controller lifecycles, actual remote URLs/services, full Main/account/Player','commands':['OutgamePrefabLoaderBundles.Build','BattleBuild.ValidateMechanicsOnly','OutgamePrefabLoaderPlayModeValidation.Run']}
a={'atUtc':now,'status':'partial-subsystem','sourceEvidence':'PREFAB_LOADER_SOURCE_EVIDENCE.json','productionFiles':['OutgameLoadPrefabControl.cs','OutgameResourcePaths.cs','OutgameCoreControllerBindings.cs','OutgameGameControl.cs'],'findings':['Controller4117 OnInit and Updata have proven empty source bodies; OnDispose clears registry only. Existing OutgamePrefabCache handles InitData/ClearModelEntityCache with shared dictionaries.','All13 Path.GetPath cases recovered including uppercase .Json, duplicated Materials/materials prefix, case11 without extension, and unknown enum passthrough. ToFileName uses last forward slash then first dot.','ResLoadHelper legacy route reads modern flag and logs/returns on modern. LoadPrefab prefixes Prefabs/ and checks route again in LoadPrefabOri; scheduler supplies .prefab and lowercase .unity3d.','LoadAsset11001 uses original EntityModelConfig AssetName GameScene/HD4_CJ_1 and PathEnum8. Cold load caches native template before instantiation and names instance from config; warm route names from cached template.','Concurrent same-path requests share scheduler loader but each callback retains its original argument array; second completion replaces template cache rather than duplicate Add.','LoadPrefab path route instantiates native asset and retains Clone suffix; LoadTexture uses ConfigMgr.dic_res mapping and has no prefab cache write. Missing configuration logs without successful callback.','GameControl resource interface now forwards source argument arrays, including empty arrays and effect key/parent context. Concrete OutgameGameSceneResources resolves LoadPrefabControl at request time.','Original imported HD4_CJ_1 prefab, scene_skin_idle1, scene_skin_game1 and eff_idle_GuBao are packed as four native bundles. Native manifest/package/scheduler/download runtime loads them from local file patch URLs, with five requests including manifest.','Validation initially checked prefab Sprite presence too early because original prefab already contains a Sprite. Corrected harness waits for GameSprites cache completion; preserved early failure report. Production callback order unchanged.'],'verification':v,'remaining':['Recover PrepareStart/PreLoad/PrepareEntity/GetEntity/GetEntityNow/GetEntityRoot and entity-pool helpers.','Bind original remote resource/SDK services and complete Main/account/module graph.','Restore remaining30 lifecycles, UI business callbacks and all pending outgame systems; complete persistence/restart/failed-callback/Player acceptance.']}
folder=W/'analysis/prefab-loader-native-bundles';a['bundles']=[{'name':name,'bytes':(folder/name).stat().st_size,'sha256':hashlib.sha256((folder/name).read_bytes()).hexdigest()} for name in ['prefab-loader-native-bundles','scene-prefab','home-texture','game-texture','effect-prefab']];write(O/'PREFAB_LOADER_NATIVE_AUDIT.json',a)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d['atUtc']=now
if 4117 not in d['implementedControllerTypes']:d['implementedControllerTypes'].append(4117)
d['remainingControllerCount']=30;d['implementations']['4117']='OutgameLoadPrefabControl.cs';d['prefabLoaderAudit']='PREFAB_LOADER_NATIVE_AUDIT.json';d['verification']=v;d['remaining'][0]='Restore remaining30 lifecycle controllers, finish LoadPrefabControl entity/preload methods and connect complete UI/game/level/player service graph.';write(p,d)
p=O/'GAME_CONTROLLER_NATIVE_AUDIT.json';d=read(p);d['resourceBinding']='OutgameGameSceneResources -> OutgameLoadPrefabControl -> OutgameResLoadHelper -> legacy scheduler/package/runtime; verified by PREFAB_LOADER_NATIVE_AUDIT.json';d['remaining'][0]='Complete entity/preload service paths and original remote service bindings. Asset11001 and scene textures now pass native local bundle integration.';write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='prefab-loader-native-resource-binding',prefabLoaderNativeAudit='generated/outgame/PREFAB_LOADER_NATIVE_AUDIT.json',nextPriority='Finish LoadPrefabControl4117 PrepareStart/PreLoad/PrepareEntity/GetEntity/GetEntityNow/GetEntityRoot using source shared cache/static state; then LevelControl4107 and PlayerControl4462. Remaining30 lifecycles. Assemble full Main/account/menu and complete all outgame/persistence/Player acceptance.')
d['validation']['integratedChecksPassed']=718;d['validation']['prefabLoader']=v;d['validation']['prefabLoaderNative']=n;d['milestones'].append({'id':'prefab-loader-native-resource-binding','atUtc':now,'status':'partial-subsystem','integratedChecks':718,'nativeChecks':8,'remainingControllers':30});write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=718,latestValidation=v);d['validationHistory'].append(v)
for path in ['analysis/prefab-loader-native-validation.json','analysis/prefab-loader-native-early-readiness-failure.json']:
 if path not in d['reports']:d['reports'].append(path)
files=[p for p in (W/'UnityProject/Assets/AreaBattle').rglob('*') if p.is_file() and (p.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas') or '/FirstPack/' in p.as_posix())];d['sourceFingerprints']=[{'path':p.relative_to(W).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files)];write(p,d)
text='\n\n## 2026-09-30 LoadPrefabControl 原生资源接线增量\n- Path13种地址、ToFileName、ResLoadHelper旧资源gate/前缀、LoadPrefabControl三类加载/模板缓存/回调参数已实现。生命周期8/38，剩30；LoadPrefabControl实体池与预加载业务仍未完成。\n- GameControl经真实4117控制器→legacy scheduler/package/download runtime→原生AssetBundle完成资源11001与主页/战斗纹理、原始特效加载。Game接口补传原始args数组。\n- 718集成与8原生检查通过，原生链路5次本地file请求（manifest+4bundle），缓存命中不发新下载。原始远程URL和完整Main/Player不在此验证范围。\n- 原生harness首次因预制体自带Sprite而过早检查缓存失败；已改为等GameSprites写入，保留 prefab-loader-native-early-readiness-failure.json，生产时序未改。\n- 审计 O/PREFAB_LOADER_SOURCE_EVIDENCE.json、PREFAB_LOADER_NATIVE_AUDIT.json。method-map4560。日志 analysis/prefab-loader-integrated.log / prefab-loader-native.log。\n- 下一步恢复4117的PrepareStart/PreLoad/PrepareEntity/GetEntity/GetEntityNow/GetEntityRoot及helper，再Level4107/Player4462，保持完整关外目标。\n'
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('711 项 checks','718 项 checks').replace('caseCount=711；latestValidation 为 GameControl + native scene','caseCount=718；latestValidation 为 LoadPrefabControl + native resource graph').replace('最新method-map4497；7控制器生命周期/共享绑定已实现并验证，剩31','最新method-map4560；8控制器生命周期/共享绑定已实现并验证，剩30')
s=s.replace('最新集成日志 analysis/game-control-integrated.log；Game原生日志 analysis/game-controller-native.log。711集成+7Game原生通过；历史UI原生6项及五控制器原生10项通过。无本任务待续进程。','最新集成日志 analysis/prefab-loader-integrated.log；资源链原生日志 analysis/prefab-loader-native.log。718集成+8资源链原生通过；历史Game/UI/基础控制器原生分别7/6/10项通过。无本任务待续进程。');s+=text;p.write_text(s,encoding='utf8')
print(json.dumps({'checks':718,'native':8,'requests':5,'fingerprints':len(files),'remainingControllers':30}))
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 r=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert r.returncode==0,r.stderr
r=subprocess.run(base+['set-check']+common+['--name','outgamePrefabLoaderNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/PREFAB_LOADER_NATIVE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert r.returncode==0,r.stderr
print('Orchestration evidence recorded')
