"""Audit original1016 assets and reviewed loader/page resource ownership."""
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parent.parent;target=root/'analysis/targets/wxcf1394487200e48f/43';out=target/'generated/outgame';snap=target/'generated/resource-snapshots/task-box-effect-20261003'
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
index={r['metadata']:r for r in read(out/'method-map.json')};selected=(26177,26188,26189,26234,26235,26237,26249,26250)
acq=read(snap/'acquisition-manifest.json');assert len(acq['items'])==10 and all(x['status']=='verified'for x in acq['items'])
for r in acq['items']:
 data=(target/r['path']).read_bytes();assert len(data)==r['catalog']['size']and hashlib.md5(data).hexdigest()==r['catalog']['md5']and hashlib.sha256(data).hexdigest()==r['sha256']
native=read(snap/'prepared/native-import.json');assert len(native['prefabs'])==1 and native['prefabs'][0]['sourceComponentCounts']==dict(GameObject=4,RectTransform=1,ParticleSystem=4,ParticleSystemRenderer=4,Transform=3)
roundtrip=read(snap/'particle-roundtrip-validation.json');assert roundtrip['passed']and roundtrip['particleSystems']==4 and roundtrip['numericScalars']==7362
deps=('EFFECT_MODULE_SOURCE_EVIDENCE.json','TASK_LIVENESS_SOURCE_EVIDENCE.json','TASK_PAGE_SOURCE_EVIDENCE.json','ACCOUNT_REWARDS_SOURCE_EVIDENCE.json','AUDIO_MANAGER_SOURCE_EVIDENCE.json','ui-root-import.json')
report=dict(status='original-task-effect-assets-and-source-loader-binding',methods=[dict(index[i],sha256=sha(out/index[i]['path']))for i in selected],dependencies=[dict(path=p,sha256=sha(out/p))for p in deps],
 acquisition=dict(path=str((snap/'acquisition-manifest.json').relative_to(target)),sha256=sha(snap/'acquisition-manifest.json'),bundles=10,newBundles=sum(r['acquisition']=='new-snapshot'for r in acq['items']),newBytes=sum(r['size']for r in acq['items']if r['acquisition']=='new-snapshot')),
 prefab=native['prefabs'][0],resources=[dict(id=r['id'],type=r['type'],name=r['name'],builtin=r.get('builtin',False))for r in native['resources']],particleReadback=dict(path=str((snap/'particle-roundtrip-validation.json').relative_to(target)),sha256=sha(snap/'particle-roundtrip-validation.json'),passed=True,particleSystems=4,numericScalars=7362),findings=[
 'Original EffectConfig1016 references Effect/UI/hdzd_eff_bxGlow with type0 and duration5. Original catalog prefab and recursive dependency closure contain10 verified bundles,7 newly acquired totaling82086 bytes. Every source size/MD5/SHA256 rechecked; immutable baseline asset evidence remains unchanged. Snapshot exporter preserves baseline references and repairs tuple-map reference scanning locally.',
 'Original prefab has4 GameObjects,1 root RectTransform,3 child Transforms and4 ParticleSystem/ParticleSystemRenderer pairs. Root scale100 retained, no synthetic particle replacement. Dependency descriptors contain4 original materials,4 source textures and2 builtin shaders (fileIDs200/203). Native importer remaps references and retains component fields. All7362 numeric particle scalars/curve fields roundtrip without differences; PPtr identities separately checked by importer. Current engine generates requested texture mipmaps from decoded base-level PNG, with original compressed bytes retained in source bundles.',
 'RecoveredSkillEffectImporter now accepts a scoped snapshot/destination/readback directory via ImportManifest optional parameters. Existing skill import entry retains its original destinations/defaults; new ImportTaskBoxEffect imports only original1016 into Recovered/TaskBoxEffect. Original source ShaderIDs remain builtin; no translated custom shader or generated bitmap is needed for this prefab.',
 'NewResLoadHelper26177/26188 checks modern mode, emits original misuse error and returns null on failure; otherwise awaits module LoadPrefabAsync with the unchanged caller path. New wrapper has explicit provider acquisition, preserving original case/path and async errors. No fabricated asset success, prefix/lowercase rewrite or fallback.',
 'AssetbundleModule26237/26249 ignores the legacy-check boolean after diagnostic, derives missing name from substring after final slash, appends .prefab then lowercases path and appends .unity3d. Cache key concatenates lower bundle path and original-case asset name. Cached live UnityObject is cast toGameObject; missing/destroyed cache loads then writes/adds before Object.Instantiate. Each call returns a distinct clone without modern handle, rename or forced activation; instance disposal does not clear prefab cache.',
 'OutgameEffectConfigReader specializes already-recovered ConfigRead26612 Unity JSON behavior: native TextAsset EffectConfig, substring from first brace, Datas list, original missing-file diagnostic/null. Other parser modes and config acquisition remain explicit. Tests build a real native AssetBundle from the original imported prefab plus original EffectConfig.bytes, not a fixture visual prefab.',
 'OutgameEffectBinding.BindTask is installed before TaskPanelUI.Awake copies liveness services. Show/Close resolve current actual module on each call. Source liveness reward order remains Show1016, animation, frame wait, currency presentation, disable Button, actual award and red refresh. Account ItemManager/LocalDataManager/data-pool are shared with original daily task activity. No extra reward gate, rollback or cosmetic cancellation is introduced.',
 'Tab changes close only the latest page effect handle. Natural effect completion removes module entry but retains the source page integer until later tab close. Overlapping box claims leave older effects owned by module timers; tests assert both provider references and subsequent selective close. Early-close late-load races from previous EffectModule milestone remain source behavior.',
 'Native fixture uses recovered original UIRoot initialization and UITip Canvas, with a settled host Canvas before attaching through source worldPositionStays parenting. A simplified bare parent previously hid the true sorting context; initial diagnostic retained. Native provider loads the original prefab using AssetBundle.LoadAssetAsync and real recovered OutgameAssetProvider/OutgameAssetHandle. Acquisition host remains a local-bundle fixture, separate from full production catalog/network startup.',
 'Full production Main/account/platform/resource catalog, complete EffectControl4058/NormalPool/sequence/currency-fly assembly, all remaining18 controllers and business, final Player and original-frame audiovisual equivalence remain incomplete. Actual original particle resource and task claim/tab/timer/account binding are the bounded restored scope.'
])
(out/'TASK_BOX_EFFECT_SOURCE_EVIDENCE.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(methods=len(selected),dependencies=len(deps),bundles=10,particles=4,scalars=7362,indexedMethods=len(index))))
