from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==449
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-error-click-notifications';s['validation'].update(integratedChecksPassed=449,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-error-click-notifications']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7488-54687.txt','disassembly/Type7488-54689.txt','ad-notify-listener-slots.json'],'implementation':['OutgameAdNotifications.cs'],'scope':'Source show-error state5 gate, special close routes, listener retry result, banner reporting switch and click-repeat reports restored. Concrete listener/controller retry and native bridge remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original adapter error routing and repeated click reports') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original adapter error routing and repeated click reports','checksPassed':449,'outgameChecksPassed':182,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'notifyShowAdError suppresses state5 then sets5/stops show timeout. INTERSTITAL specific interval error or platform458/459 uses reports then closed; VIDEO requires nonnull message and specific busy/orientation error or platform458 for same route. General enabled reporting invokes bool onShowFail and reportsShowFail only when listener exists and returnsfalse; disabled banner still invokes listener but no reports. Click sets clicked before first reports; repeats still NewReportAdClick(true).449 checks pass.','source':['disassembly/Type7488-54687.txt','disassembly/Type7488-54689.txt'],'implementation':'OutgameAdNotifications.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 展示错误分流与重复点击（449项）\n补齐NotifyShowAdError和NotifyClickAd。展示错误先state5/停展示超时，按原文本、广告类型、平台458/459走关闭或bool展示失败监听器；保留VIDEO空消息绕过特殊分支、banner上报开关、无监听器不补reportShowFail。重复点击仍报new-click(true)，主点击与插屏等级事件仅首次。449项（战斗267+关外182）通过，Unity退出0。下一步仍需实际控制器监听器和原生回调组合，完整目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdErrorClickNotifications','--result','pass','--evidence','449 integrated checks; source show-error close/retry paths, banner switch and repeated click reports verified; native/controller wiring incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded449; full goal remains active.')
