from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==532 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type2954-'+str(i)+'.txt' for i in [23019,23029,23031,23034,23035]]+['disassembly/ProviderGeneric-23030.txt','provider-completion-generics.json','provider-create-handle-generic.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='asset-provider-completion';s['validation'].update(integratedChecksPassed=532,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['asset-provider-completion']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameAssetProvider.cs','OutgameAssetHandle.cs'],'scope':'Provider asset-handle creation/refcount/release, completion snapshots and Task restored; native fly fixture runs provider-driven callbacks. Original loader startup flags, bundle ownership and production loading remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Object<T> shared source wrapper') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original pooled object count/lifecycle wrapper','checksPassed':532,'outgameChecksPassed':265,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'provider_completion_chain_verified_loader_pending','source':sources,'verified':['Asset handle creation increments reference count then adds handle','Release warns when count<=0; failed List.Remove throws before decrement','IsDone requires suppression flag false and (status&~1)==4','Completion sets Progress1 then copies handle list, skips handles whose providers are released/destroyed','Callback failure interrupts later callbacks and Task completion','Task lazily allocated; terminal status on first access completes it; dispatch uses TrySetResult after callbacks','Play Mode now follows provider->handle event->NormalPool->fly animation'],'remaining':['Actual resource loader completion scheduling and startup flags','Provider bundle ownership, dependency release and destruction','Other handle types and failed loading state transitions','Production account/pages and full build/E2E'],'checks':532,'playmodeChecks':8,'dynamicScope':'Recovered-resource adapter uses explicit normal-provider mode and sets status4; no original platform loader claim'}
write(o/'ASSET_PROVIDER_COMPLETION_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Provider completion/refcounts restored from23019/23029/23031/23034/23035 and generic23030; actual fly Play Mode uses provider-driven handle events. Original loader and bundle lifetime integration pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## Provider完成通知与引用（532项 + 独立8项动态检查）\n提取provider2954的37个方法及CreateHandle泛型方法，原常规索引2114。恢复OutgameAssetProvider引用计数、List.Remove失败路径、终态判断、完成句柄快照、释放后跳过通知、Task延迟创建和回调后完成顺序。验证回调释放下一个句柄、异常阻止Task完成、全局抑制分支及引用错误。飞币Play Mode由显式兼容模式夹具改为正常provider创建句柄并派发完成事件，形成provider→句柄→NormalPool→动画链路，532项集成、8项动态通过。资源底层仍为恢复资源适配，原调度/启动开关、bundle依赖和完整关外生产流程未完成。\n' 
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAssetProviderCompletion','--result','pass','--evidence','532 integrated checks and8 independent actual Play Mode checks; complete pool and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded532; full goal active.')
