from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==473
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='adapter-source-initialization';s['validation'].update(integratedChecksPassed=473,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['adapter-source-initialization']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7488-54668.txt','disassembly/Type7488-54724.txt','disassembly/Type7488-54725.txt','disassembly/Type7488-54712.txt','disassembly/Type7488-54679.txt'],'implementation':['OutgameAdConfiguration.cs','OutgameWxVideoAdapter.cs'],'scope':'Retains source IdsInfo/Adz consumed fields, source init report-option gates, parse ordering, canRequest=true, ctor defaults and configured platform identity. Reads current config for price, priority, native id and show timeout. Original complete remote config and platform factory remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original DAU adapter initialization and retained configuration semantics') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original DAU adapter initialization and retained configuration semantics','checksPassed':473,'outgameChecksPassed':206,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'DAU adapter init stores config references before prefix/JSON work. Parse gate is day-clear key OR banner key with exact BANNER zone; parse both optional flags, TryParse failure writes0, empty field preserves prior value. Wx canRequest inherited constant true. Ctor interval20/bannerError1; configured platform from IdsInfo differs from native883.473 checks pass.','source':['disassembly/Type7488-54668.txt','disassembly/Type7488-54724.txt','disassembly/Type7488-54725.txt','disassembly/Type7488-54712.txt'],'implementation':['OutgameAdConfiguration.cs','OutgameWxVideoAdapter.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'VIDEO_CONTROLLER_INITIALIZATION_AUDIT.json';audit=read(p);audit['adapterInitializationUpdate']={'implemented':'Wx source init/canRequest, config references and consumed DTO fields','checks':473,'productionConnected':False,'remaining':'Original complete config factory, SDK and controller setAdz binding'};write(p,audit)
note='\n\n## 平台适配器源初始化与配置引用（473项）\n补齐Wx继承DAU的init/canRequest：先保存IdsInfo/Adz引用和追加平台日志，再按day-clear字段或BANNER专属字段决定JSON解析；保留空字段旧值与TryParse失败写0。构造默认interval20/bannerError1；区分IdsInfo.platformId与原生883。价格键、优先级、请求id和展示超时读取当前配置，展示时重新解析customParam。473项（战斗267+关外206）通过，Unity退出0。DTO当前覆盖已恢复生命周期消费字段，完整远端配置与平台工厂、生产入口尚待接通，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdapterSourceInitialization','--result','pass','--evidence','473 integrated checks; source init gates, defaults, retained config and parse failure ordering verified; complete remote config and factory pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded473; full goal remains active.')
