from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==493
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-item-indexes';s['validation'].update(integratedChecksPassed=493,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-item-indexes']={'implementationReady':True,'productionConnected':False,'source':['global-item-init-generics.json','global-item-fields.json','disassembly/Type4542-34586.txt','disassembly/Type4542-34587.txt','disassembly/Type4542-34583.txt','disassembly/Type4542-34596.txt','disassembly/Type4547-34608.txt','disassembly/Type4547-34611.txt'],'implementation':['OutgameGlobalItemIndexes.cs','OutgameItemRecords.cs'],'scope':'Source config filtering, clear-and-rebuild live indexes, shallow snapshots, duplicate Add exceptions, lazy hash UID and selective snapshot update fields. Global init/save/time/reward consumers and production provider still pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original global item/product indexes and snapshots') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original global item/product indexes and snapshots','checksPassed':493,'outgameChecksPassed':226,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Resolved generic calls prove Dictionary.Clear/Add, config ContainsKey, and list iteration. Global initialization retains configured records only, uses Add (duplicate failure), replaces snapshots and shallow clones. Product UID caches GetHashCode if0. Existing snapshot updates only selected fields; original haveBuyTimes self-write targets live record, not snapshot.493 checks pass; complete runtime remains pending.','source':['global-item-init-generics.json','disassembly/Type4542-34586.txt','disassembly/Type4542-34587.txt','disassembly/Type4542-34583.txt','disassembly/Type4542-34596.txt'],'implementation':['OutgameGlobalItemIndexes.cs','OutgameItemRecords.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='records_and_indexes_implemented_lifecycle_pending';audit['indexImplementation']={'files':['OutgameGlobalItemIndexes.cs','OutgameItemRecords.cs'],'checks':493,'source':['global-item-init-generics.json'],'cloneEvidence':'ItemUserData.Clone/ProductUserData.Clone share wasmcode1 function1361 with Object.MemberwiseClone metadata3953; native wrapper table109131','detail':'Config-qualified dictionary Add; duplicate failure retains earlier entries; source field40/44 snapshots are memberwise clones; nested references stay shared; haveBuyTimes self-write not corrected.'};audit['pending']=['Implement full GlobalItemManager save list reconstruction','Implement update/time/statistics/reward side effects','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 全局物品/商品索引与快照（493项）\n新增global-item-init-generics.json证实Clear/Add/ContainsKey/列表迭代。OutgameGlobalItemIndexes恢复配置过滤、保留原记录引用、字典Clear后重建和重复键异常、快照字典替换及浅复制。Product UID零时缓存GetHashCode；更新快照仅更新原字段，保留haveBuyTimes写回live自身的原逻辑及未更新price/time。MemberwiseClone由与Object.MemberwiseClone同函数1361的原Clone确认。493项（战斗267+关外226）通过，Unity退出0。源初始化总流程、保存列表重建、时间/统计/奖励以及实际4500Provider尚待完成，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameGlobalItemIndexes','--result','pass','--evidence','493 integrated checks; source item/product index filtering, duplicate failure, UID and shallow snapshot behavior verified; full lifecycle pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded493; full goal remains active.')
