from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==549 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type3843-'+str(i)+'.txt' for i in range(29987,29991)]+['disassembly/VideoConfigGeneric-26612.txt','disassembly/VideoConfigGeneric-26619.txt','video-manager-generics.json','video-config-generic.json','video-config-rgctx.json','VIDEO_CONFIG_ASSET_EVIDENCE.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='video-config-manager';s['validation'].update(integratedChecksPassed=549,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['video-config-manager']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameVideoButtonManager.cs','OutgameShopVideoBindings.cs','Recovered/OutgameConfig/VideoBtnConfig.bytes'],'scope':'Original VideoBtnManager cache/duplicate/reset/resource-unavailable semantics restored. Original65row JSON asset copied byte-identically and parsed through source JsonUtility branch; actual ShopUI integration test uses it. Global mode selection, binary loader and real SDK/account composition pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='VideoBtnManager cache and ConfigRead JSON branch source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original video configuration asset, lazy cache semantics and ShopUI integration','checksPassed':549,'outgameChecksPassed':282,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'freshPlayModeRun':False,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'video_config_json_and_cache_verified_actual_sdk_pending','source':sources,'verified':['Original65row VideoBtnConfig asset copied byte-for-byte with SHA256 evidence','ConfigRead shared generic and RGCTX resolve JSON Datas branch to JsonUtility.FromJson','JSON source names preserved without invented videoParam1/2 to Video_param1/2 aliases','Lazy cache initialized once; duplicate ID logs and keeps first; missing ID logs and returns null','Reset only clears initialized flag; missing bundle leaves previous dictionary readable','Available reload replaces dictionary before parsing; null list marks initialized; invalid row failure leaves flag false for retry','Original ShopUI pointer/reward integration now loads original table rather than hand-written configuration'],'remaining':['Startup config mode selection and binary/alternate parser paths','Actual SDK/report host and production account/menu owner','Fresh PlayMode evidence for native Button lifecycle','Full persistence/build/E2E'],'checks':549,'priorPlaymodeChecks':8,'dynamicScope':'Real prefab/native Button with original JSON config; platform results remain explicit fixture; prior fly PlayMode not rerun'}
write(o/'VIDEO_CONFIG_MANAGER_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Original65row video configuration asset and manager cache semantics restored; shop integration now uses original JSON data. Global config mode selection, SDK/report/account host remain pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## 视频配置原数据与缓存管理器（549项）\n解析ConfigRead共享泛型及RGCTXData，确认Datas对象JSON分支使用Unity JsonUtility.FromJson。原始VideoBtnConfig65条数据按字节复制到Resources，SHA256证据已保存；保留字段名，不臆造videoParam1/2到Video_param1/2的别名。新增OutgameVideoButtonManager，恢复惰性缓存、重复键首条优先、缺失日志、Reset仅清初始化标记、资源未就绪继续读旧缓存、失败重试以及null表初始化规则。原ShopUI点击到奖励验证改用原始表。549项集成通过，Unity退出0；此前8项飞币PlayMode未重跑。全局配置模式选择、二进制分支、真实SDK/上报与账号菜单入口及完整构建仍待完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameVideoConfigManager','--result','pass','--evidence','549 integrated checks; prior8 PlayMode checks not rerun. Global config selection/SDK/account composition and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded549; full goal active.')
