from pathlib import Path
import json,hashlib,datetime,subprocess,struct
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/update-manager-native-validation.json');assert r['passed'] and len(r['checks'])==959;assert n['passed'] and len(n['checks'])==23
assert 'AREABATTLE_INTEGRATED_PASS cases=959' in (W/'analysis/update-manager-integrated.log').read_text(encoding='utf8')
helper=W/'analysis/recover_outgame_manager_registry.py';ns={'__file__':str(helper)};exec(helper.read_text().split('rows=[]')[0],ns);u,md,ms,mem,ts,b,pairs=[ns[k] for k in ('u','md','ms','mem','ts','b','pairs')]
fields=[]
for ti in (2920,2921):
 t=ts[ti]
 for j in range(t[18]):
  x=struct.unpack_from('<3i',b,pairs[11][0]+12*(t[8]+j));fields.append(dict(typeIndex=ti,offset=u(u(3823136+4*ti)+4*j),name=ms(x[0]),typeReference=x[1]))
write(O/'UPDATE_MANAGER_METADATA.json',dict(fields=fields,fieldMeaning={'2920:0':'static instance','2920:12':'Dictionary<int,UpdateHandle> IndexDict','2920:16':'isPause','2920:20':'next id','2920:24':'normal handles','2920:28':'force handles','2920:32':'fixed handles','2920:36':'alternate unused list','2920:40':'pending removal ids','2920:44':'pending removal delegates','2920:48':'Dictionary<int,UpdateData>','2920:52':'TimePreFrame default16','2920:56':'alternate rotation list','2921:8':'string actionName','2921:12':'string handle'},genericMethods={'3956760':'Dictionary.Add','3956768':'Dictionary.ContainsValue','3980168':'List.IndexOf','3980176':'List.RemoveRange','4000884':'GameObject.AddComponent<UpdateManager>','4001148':'GameObject.GetComponent<UpdateManager>'}))
mm=read(O/'method-map.json');graph=read(O/'UPDATE_MANAGER_CALL_GRAPH.json')
source=dict(atUtc=now,metadataEvidence='UPDATE_MANAGER_METADATA.json',callGraph='UPDATE_MANAGER_CALL_GRAPH.json',tracedMethodCount=len(graph['reachable']),alternateMethodCount=len(graph['alternateMetadata']),criticalEvidence=[
 'get_Instance22794 Unity fake-null checks cached static, GameObject.Find("UpdateManager"), creates/names if absent, GetComponent before AddComponent, writes static then DontDestroyOnLoad(root). No synthetic Awake/OnDestroy cleanup is added. Native Update/FixedUpdate are named source messages.',
 'Constructor22759 allocates pending ids/delegates and debug data dictionary; timePerFrame52=16. Other lists/IndexDict lazily allocate through getters. ID22795 starts at field20 and unchecked increments until IndexDict lacks key, stores0 if returnedid>2147483645 otherwise returnedid. Adds insert live list before IndexDict.Add.',
 'Public AddHandle22777 ->22788 normal, AddFixed22748->22768 fixed, AddForce22793->22782 force. RemoveHandle22791->22763 and RemoveById22798->22786 only queue with IndexOf<=-1 deduplication. AddUpdateData22796->22797 creates name/handle strings record; duplicate logs CLog.Error "重复添加："+id and preserves old record.',
 'Update22802 returns when isPause; calls ProcessRemovals22770 first, then force and normal lists. Each pass captures Count once and re-fetches live property/list element every iteration; direct delegate invocation has no null guard/catch. Adds during force can reach later normal pass same frame, adds to current pass defer. Pause changed during callback is only read next Update.',
 'FixedUpdate22785 returns when paused, captures count once and accesses live fixed list each iteration, skips null delegates. Does not process pending removals. Force update is still pause-gated.',
 'ProcessRemovals22770 iterates live indexed pending IDs, then replaces ID list with new empty List if nonempty; processes pending delegates similarly and replaces list. Does not Clear old queue object. ID removals precede delegate removals regardless of call chronology.',
 'RemoveNowById22783: absent IndexDict id returns before debug-data cleanup; otherwise delegates to22806 with IndexDict[id], then removes debug data for originally requested id. Delegate removal22806 removes first normal occurrence OR first force if not normal; independently removes first fixed occurrence. If IndexDict.ContainsValue(callback), enumerates dictionary with delegate equality until first matching key, then removes only if key>=0. Duplicate delegates can make requested-id removal delete an earlier equal entry; negative ids retain dictionary entry. Delegate-only removal does not remove debug data.',
 '22806 loop branch0018bb0d br_if0 repeats loop at0018ba09 when delegate inequality; it is not an unconditional first-key removal. Source slice helper annotates loop end rather than backward branch target; raw WASM loop semantics used.',
 '35 alternate obfuscated methods remain extracted and mapped. Some genuinely differ (removal thresholds/index starts/rotation RemoveRange/infinite-loop variants). They are not substituted for public/Unity paths; future callers must select exact referenced method. No claim all alternates are callable production APIs.'
],limits=['Complete traced public API and native message paths restored, not unverified alternate entrypoints.','TimeModule still editor-pumped in native integration; UpdateManager itself is an actual Unity MonoBehaviour. Audio resource/config/node manager owner and full Main graph still pending.'])
write(O/'UPDATE_MANAGER_SOURCE_EVIDENCE.json',source)
v=dict(atUtc=now,scope='Source UpdateManager traced public APIs and real MonoBehaviour Update/FixedUpdate bound to source audio actions',checksPassed=959,newIntegratedChecks=21,nativePlayModeChecks=23,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameUpdateManagerPlayModeValidation.Run'],notClaimed='Alternate obfuscated entrypoints, AudioManager/resource/config ownership, full Main/account/menu or complete outgame Player')
remaining=['Restore AudioManager3421 configuration/root/listener/node ownership and3424 audio resource helpers; bind production services to actual shared UpdateManager and TimeModule.','Continue remaining27 controller lifecycles and complete Main/account/module/menu graph, business flows, persistence/restart/failure/return and runnable Player acceptance.']
a=dict(atUtc=now,status='source-update-owner-restored-composition-pending',sourceEvidence='UPDATE_MANAGER_SOURCE_EVIDENCE.json',verification=v,findings=['OutgameUpdateManager is a real MonoBehaviour singleton with source-named GameObject, lazy reuse/create and DontDestroyOnLoad. BindAudio uses source global owner lookup for add/remove, no fixture update fallback.','959 integrated checks passed,21 new. 23 native checks passed: actual MonoBehaviour automatically updates recovered1001/2001 audio, fixed callback runs, Dispose queues then Update removes callback, singleton destruction/recreation yields empty new ownership.','Source deferred removal, duplicate delegate equality/index quirks, pause gates and failure prefix state preserved.35 obfuscated alternatives recorded separately; no fake semantic merging.','Business lifecycle coverage remains11/38,27 remaining; method map5058. No complete outgame Player build/acceptance claim.'],remaining=remaining,artifacts=dict(integratedLog='analysis/update-manager-integrated.log',nativeLog='analysis/update-manager-native.log',nativeReport='analysis/update-manager-native-validation.json'),disassembledMethodMapCount=len(mm))
write(O/'UPDATE_MANAGER_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='update-manager-native-audio',updateManagerAudit='generated/outgame/UPDATE_MANAGER_AUDIT.json',nextPriority=' '.join(remaining));d['validation']['integratedChecksPassed']=959;d['validation']['updateManagerNativeAudio']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='update-manager-native-audio'];d['milestones'].append(dict(id='update-manager-native-audio',atUtc=now,status='source-update-owner-restored-composition-pending',integratedChecks=959,nativeChecks=23,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,updateManagerAudit='UPDATE_MANAGER_AUDIT.json');d['remaining'][0]=' '.join(remaining);d['findings'].append('Actual MonoBehaviour UpdateManager now drives source native audio:959 integrated,23 native. AudioManager/config/resource/full app ownership remains; count11/38 unchanged.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=959,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=(W/'analysis/unity-integrated-validation.json').stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 原生UpdateManager增量\n- OutgameUpdateManager.cs实现Type2920实际公开API/Unity消息调用链28方法，MonoBehaviour singleton按Unity fake-null→Find("UpdateManager")→建GO/name→GetComponent/AddComponent→DontDestroyOnLoad。无虚构Awake/OnDestroy清理；销毁后getter重建。BindAudio连接静态AddHandle/RemoveHandleById，每次操作访问真实owner。\n- ctor pending id/handle lists和debugData dict、TimePreFrame16；正常/force/fixed lists和IndexDict lazy。共享ID unchecked递增跳过已占key，返回id>2147483645时将storedNext清0。Add立即liveList.Add→IndexDict.Add。\n- Update pause gate→移除→force→normal。每pass捕获count，但每次getter/live index；force新增normal同帧可跑，同pass新项下次。FixedUpdate独立pause gate/count，nullskip，无移除处理。普通/force无nullguard/catch。\n- 移除按id/委托都先IndexOf去重入队，Update先ID再delegate，nonempty处理后替换list而非Clear。RemoveNow委托只移normal第一项或force第一项，另移fixed第一项；IndexDict按委托相等找第一key仅>=0才删。重复delegate按较晚ID移除可能删除较早key，但debugData按原请求ID删；delegate移除留debugData，缺失ID不删debugData，负key留Index。异常保留prefix。\n- O/UPDATE_MANAGER_CALL_GRAPH.json、METADATA、SOURCE_EVIDENCE、AUDIT。65新提取（63manager+2UpdateHandle delegate），methodmap5058。35混淆alternate有不同阈值/边界/循环，不能同名归并；未接productionalternate，未来实际调用需追确切metadata。\n- 22806删除foreach的0018bb0d br_if0是循环回0018ba09，helper显示end位置不是实际backedge；逻辑为不相等continue，找到后取key退出。\n- 959集成通过（新增21），23原生通过，analysis/update-manager-integrated.log / update-manager-native.log / update-manager-native-validation.json。Native源audioAction由真正MonoBehaviour自动Update驱动，Fixed也真实；TimeModule仍editor pump。原始1001/2001音频fade/play/end/Dispose与源码延迟update移除结合，singleton销毁重建通过。resource/config/AudioManager host仍fixture或待接。\n- 验证Unity44220/59144已正常退出，无待续进程。状态update-manager-native-audio；959/5058/11/27，无完整关外Player build。next实际AudioManager3421（26345..26369、多个alternate）和3424异步加载helpers，再其余27控制器/完整主入口与流程验收。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('938 项 checks','959 项 checks').replace('caseCount=938；latestValidation 为 full source TimeModule/native audio','caseCount=959；latestValidation 为 native UpdateManager/audio').replace('in_progress / time-module-native-audio','in_progress / update-manager-native-audio').replace('最新集成日志 analysis/time-module-integrated-final.log。938集成、19原生完整TimeModule/音频链通过（loader/shared audio update为fixture，timer为完整源码实现）；','最新集成日志 analysis/update-manager-integrated.log。959集成、23原生UpdateManager/TimeModule/音频链通过（loader为fixture，shared update为实际MonoBehaviour，timer为完整源码实现）；').replace('最新method-map4993；','最新method-map5058；');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameUpdateManagerNativeAudio','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/UPDATE_MANAGER_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=959,nativeChecks=23,fingerprints=len(files),tracedMethods=28,methodMap=len(mm))))
