from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==530 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type2929-'+str(i)+'.txt' for i in [22893,22901,22902,22905,22906]]+['disassembly/Type2930-22916.txt','disassembly/Type2930-22917.txt','disassembly/Type2945-22982.txt']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='asset-handle-lifetime';s['validation'].update(integratedChecksPassed=530,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['asset-handle-lifetime']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameAssetHandle.cs'],'scope':'Asset handle validity, release, main-object access and parameterless prefab instantiation restored. Uses explicit runtime mode/provider dependencies. Recovered-resource Play Mode adapter uses explicit compatibility branch; original provider loader and completion events pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Object<T> shared source wrapper') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original pooled object count/lifecycle wrapper','checksPassed':530,'outgameChecksPassed':263,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'asset_handle_core_verified_loading_events_pending','source':sources,'verified':['Normal release validates provider, releases it and only then clears provider reference','Failed release preserves provider; repeated release warns without provider call','Destroyed provider suppresses main-object and instance access','Compatibility branch directly reads mainObject and skips release','Default instantiate activates clone and assigns original prefab name','Actual fly Play Mode uses restored handle in explicitly selected compatibility fixture'],'remaining':['Determine actual loader mode initialization from original startup','Provider creation, reference counts and load completion subscriptions','Native pool manager/resource lifetime composition','Legacy backend validation and full outgame build/E2E'],'knownDifferences':['Non-default instantiate overloads not implemented','Original instantiate diagnostic log not emitted','No claim full AssetOperationHandle API restored'],'checks':530,'playmodeChecks':8}
write(o/'ASSET_HANDLE_LIFETIME_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Asset handle core restored from22893/22902/22905/22906 and base22916/22917; default native prefab activation/name behavior from22982. Provider loading and completion subscriptions remain pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## 资源句柄生命周期（530项 + 独立8项动态检查）\n提取AssetOperationHandle、OperationHandleBase、InstantiateOperation共31个方法，原方法索引2077。新增OutgameAssetHandle：正常模式有效性检查、provider释放后断开、失败保留连接、重复释放告警；兼容模式直读mainObject且不释放。参数默认Instantiate实际激活克隆并恢复原名，已接入飞币Play Mode的显式兼容模式资源适配。530项集成及8项动态检查通过，Unity退出0。兼容模式是验证夹具明确设置，尚不证明原启动模式；原加载事件、provider引用计数/平台加载和完整生产页面构建未完成。\n' 
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAssetHandleLifetime','--result','pass','--evidence','530 integrated checks and8 independent actual Play Mode checks; complete pool and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded530; full goal active.')
