from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==497
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-item-timestamp';s['validation'].update(integratedChecksPassed=497,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-item-timestamp']={'implementationReady':True,'productionConnected':False,'source':['item-timestamp-evidence.json','disassembly/Type3531-27247.txt','disassembly/Type3531-27248.txt','disassembly/Type3534-27293.txt'],'implementation':['OutgameGlobalItemPersistence.cs'],'scope':'Original fixed 1970-01-01 08:00:00 unspecified epoch; direct DateTime subtraction, millisecond Int64 truncation and reverse conversion. Default item persistence now uses this converter.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original item timestamp epoch and conversion') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original item timestamp epoch and conversion','checksPassed':497,'outgameChecksPassed':230,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'TimeHelper uses TimeModule static offset32 initialized to DateTime(1970,1,1,8,0,0). Source subtracts ticks without timezone normalization, converts TotalMilliseconds to Int64 toward zero; reverse uses AddMilliseconds. Default item persistence wired.497 checks pass.','source':['item-timestamp-evidence.json','disassembly/Type3531-27247.txt','disassembly/Type3531-27248.txt','disassembly/Type3534-27293.txt'],'implementation':['OutgameGlobalItemPersistence.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='records_indexes_save_timestamp_implemented_lifecycle_pending';audit['timestampImplementation']={'files':['OutgameGlobalItemPersistence.cs'],'checks':497,'source':['item-timestamp-evidence.json'],'detail':'1970-01-01 08:00:00 unspecified epoch, direct DateTime subtraction and Int64 milliseconds; default persistence converter connected.'};audit['pending']=['Implement full GlobalItemManager init, timer registration and release','Implement update/statistics/reward side effects','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 原始物品时间戳（497项）\nTimeHelper与TimeModule静态构造确认原起始时间为1970-01-01 08:00:00、Unspecified。直接DateTime相减后TotalMilliseconds截断Int64，不转UTC；反向AddMilliseconds。OutgameGlobalItemPersistence默认接入原转换，验证时区Kind、正负亚毫秒截断、64位往返与真实保存路径。497项（战斗267+关外230）通过，Unity退出0。全局初始化、更新/统计/奖励及实际4500Provider仍待完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameGlobalItemTimestamp','--result','pass','--evidence','497 integrated checks; original eight-hour epoch, milliseconds, truncation and default persistence converter verified; full lifecycle pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded497; full goal remains active.')
