from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==482
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-request-completion-reload';s['validation'].update(integratedChecksPassed=482,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-request-completion-reload']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7511-54864.txt','disassembly/Type7511-54855.txt','disassembly/Type7511-54856.txt','disassembly/Type7510-54883.txt'],'implementation':['OutgameAdRequestCompletion.cs','OutgameSerialAdPreload.cs'],'scope':'Source full/partial/empty cache request completion reports and realtime reload, minimum15 delay, banner-specific refresh value, retained coroutine handles and serial check integration. Controlled native failure reaches scheduled serial retry; live runtime composition pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original request completion and realtime reload lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original request completion and realtime reload lifecycle','checksPassed':482,'outgameChecksPassed':215,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Base checkRequest captures cache count and showing, counts showing as one toward capacity. Full capacity reports success unless BANNER and returns; below capacity reports success for nonzero cache, otherwise failure and VIDEO false event, then reload. Reload truncates float, min15, BANNER banRefreshTime otherwise reqInterTime; realtime coroutine calls virtual load and retains completed handle.482 checks pass including actual serial/native failure to scheduled retry and cache success.','source':['disassembly/Type7511-54864.txt','disassembly/Type7511-54855.txt','disassembly/Type7511-54856.txt','disassembly/Type7510-54883.txt'],'implementation':['OutgameAdRequestCompletion.cs','OutgameSerialAdPreload.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 广告请求完成检查与自动重载（482项）\n新增OutgameAdRequestCompletion还原base checkRequest及reload：展示中计入1个容量；满容量除BANNER外报告成功并返回；不足时按非零/零缓存报告成功或失败，VIDEO零缓存事件false，之后重载。重载采用BANNER banRefreshTime或reqInterTime，WASM浮点截断后最少15秒，WaitForSecondsRealtime，保留完成协程句柄；替换前停止旧句柄。串行checkRequest可直接调用该组件，验证原生失败→检查→定时重试→serialLoad→成功入缓存。482项（战斗267+关外215）通过，Unity退出0。真实生产服务组合与完整关外仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdRequestCompletionReload','--result','pass','--evidence','482 integrated checks; request completion, realtime min15 reload and native failure to serial retry verified; production composition pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded482; full goal remains active.')
