from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/level-start-native-validation.json');assert r['passed'] and len(r['checks'])==756;assert n['passed'] and len(n['checks'])==10
v={'atUtc':now,'scope':'Level4107 lifecycle, live active tower tick, CampInfo aggregation, source tower/obstacle initialization and prepared-start sequence','checksPassed':756,'newIntegratedChecks':15,'nativePlayModeChecks':10,'freshPlayModeRun':True,'freshPlayerBuild':False,'freshPlayerSmoke':False,'commands':['BattleBuild.ValidateMechanicsOnly','OutgameLevelStartPlayModeValidation.Run'],'notClaimed':'Complete Tower/Soldier/WayLine/AI implementations in controller graph, full Level InitGameData/state hosts, Player4462/Main/account/full outgame Player'}
a={'atUtc':now,'status':'partial-subsystem','sourceEvidence':'LEVEL_CONTROL_SOURCE_EVIDENCE.json','verification':v,'findings':[
 'Resolved Global type4272 static offset8=PlayCampID: LevelControl OnInit writes heldPlayerCamp then count-1 maximum; OnDispose clears registry4107 then shared playstate0 without releasing native objects/config. Real BindLevel factory added.',
 'OutgameLevelRuntimeState shares original field8 between dispatcher and lifecycle. Existing dispatcher callers retain equivalent independent default state when no owner is supplied. Independent battle kernel is unchanged.',
 'Updata runs only state6, foreach active towers invokes source tower callback with delta*live ConfigMgr GameTimeScale and unchanged unscaled delta. List mutation/exception stops before timer work. NeedsCampRefresh timer uses raw delta, runs at<=0 once then adds1 only after successful refresh.',
 'CampInfo Clear zeros counts/score, sets index/camp=-1, active=false, retains color. Pool returns first inactive object or appends a fresh default object. Lookup skips inactive entries.',
 'RefreshCampInfo retains active empty camp records; resets their count/score, computes next index from active nonneutral camps, assigns playerindex0/neutralGlobalCampCount/enemynext. Active tower counts and per-tower truncated scores accumulate; neutral scores excluded from total. WASM conversion returns intMin for NaN/infinity/out-of-range and integer accumulation wraps.',
 'Source ConfigMgr GetCampColor uses dictionaryfield272 and falls back Color(0,1,0,1). CampChange is Event4271 staticfield16; it is sent after refreshflagfalse but before live state/PVP/outcome checks. Missing player record does not trigger defeat; retained empty record does. Boss victory truncates score and does not check Boss.Active.',
 'Tower initialization uses current SO/array on each iteration, initial count stored in live field36, one-based IDs, factory by ShipID, last boss reference assigned before Init and HasBoss set only after successful Init. Factories remain explicit required boundaries pending full native Tower/Soldier restoration.',
 'Obstacle initialization sets flagfalse, null/empty returns true with no log, otherwise gets actual pooled entities synchronously, applies world position/world Euler/localScale from IntVector3 /100, appends retained object list, then sets flagtrue and logs. Tested with original native Entity81 mesh; its recovered visual prefab has no Collider, so the first test collider assumption was corrected to original MeshFilter evidence. Physics/collider graph is not claimed complete.',
 'Prepared callback31535 now sequences tower/obstacle initialization, concrete GameControl.PrepareGameScene, two UI module reads and existing-page second getter/Refresh or Show, camp refresh, optional state4true, GameControl resolve, source unused current-level read, actual camera resize then coroutine start.',
 'Coroutine type4106: Clear immediately, scaled WaitForSeconds0.2, independently resolve InitPrePrefabLoad and InitStarLine, another scaledWait0.2, AI InitInfo. Golden test verifies lazy iterator, empty Dispose, Reset NotSupported, terminal state on callback failure and retained Current. Native timing observed0.200046 and0.400073 scaled seconds; both waits halt at timeScale0.',
 '15 new integrated cases plus10 native cases pass. Native factory/lifecycle and original obstacle geometry are concrete; line/AI effects in native timing harness are explicitly recorded fixture services. No full native battle initialization or platform/account claim.'
 ],'remaining':['Finish LevelControl InitGameData, remaining collections/source Tower/Soldier factories and actual WayLine/AI services; supply complete state/continuation/prepared UI hosts into real Main graph.','Implement Player4462 lifecycle and remaining29 roster lifecycles. Nine lifecycle implementations are a method-level count, not nine fully restored gameplay controllers.','Complete all objective subsystems, production entry, actual preload entity asset set, persistence/restart/failure/return-flow and Player build acceptance.'],'artifacts':{'integratedLog':'analysis/level-control-integrated-final.log','nativeLog':'analysis/level-start-native.log','nativeReport':'analysis/level-start-native-validation.json'},'disassembledMethodMapCount':4681}
write(O/'LEVEL_CONTROL_AUDIT.json',a)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,levelControllerAudit='LEVEL_CONTROL_AUDIT.json',verification=v,remainingControllerCount=29);d['implementedControllerTypes']=list(dict.fromkeys(d['implementedControllerTypes']+[4107]));d['implementations']['4107']='OutgameLevelControl.cs';d['sourceMethods']=list(dict.fromkeys(d['sourceMethods']+[31503,31504,31526]));d['remaining'][0]=a['remaining'][0]+' '+a['remaining'][1];d['findings'].append('Level4107 lifecycle implemented with source camp aggregation and native obstacle/coroutine verification; full source tower/soldier/state/Main composition remains pending. Lifecycle count is not complete-controller coverage.');write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='level-lifecycle-camps-prepared-start',levelControllerAudit='generated/outgame/LEVEL_CONTROL_AUDIT.json',nextPriority='Finish Level4107 InitGameData and remaining collection/factory APIs, real Tower/Soldier/WayLine/AI and prepared/state/UI hosts. Then Player4462 lifecycle and remaining29 lifecycle controllers. Compose actual Main/account/entry and complete every outgame subsystem plus persistence/restart/failure/Player acceptance; no fake platforms.');d['validation']['integratedChecksPassed']=756;d['validation']['levelController']=v;d['validation']['levelStartNative']=n;d['milestones']=[m for m in d['milestones'] if m['id']!='level-lifecycle-camps-prepared-start'];d['milestones'].append({'id':'level-lifecycle-camps-prepared-start','atUtc':now,'status':'partial-subsystem','integratedChecks':756,'nativeChecks':10,'remainingLifecycleControllers':29});write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=756,latestValidation=v);d['validationHistory'].append(v)
if 'analysis/level-start-native-validation.json' not in d['reports']:d['reports'].append('analysis/level-start-native-validation.json')
files=[p for p in (W/'UnityProject/Assets/AreaBattle').rglob('*') if p.is_file() and (p.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in p.as_posix() or '/Recovered/Loading/' in p.as_posix())];d['sourceFingerprints']=[{'path':p.relative_to(W).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 Level生命周期、阵营统计与准备完成流程增量\n- OutgameLevelControl 实现 OnInit/Updata/OnDispose，玩家阵营源为Global.PlayCampID；OutgameLevelRuntimeState与既有PlayStateDispatcher共享field8。BindLevel已验证。生命周期方法层面9/38、剩29，不能理解为9个业务控制器全部复原。\n- CampInfo池/索引/颜色/逐塔计数与分数截断/neutral排除/CampChange后胜负判断按源实现；Update逐塔读取live时间倍率、foreach异常和一次timer刷新保留。\n- InitTowers顺序、live总数和最后Boss；InitObstacles实际nativeEntity81变换、append与flag；Prepare后场景/PlayUI/state4/相机/协程顺序已实现。完整Tower/Soldier factory、InitGameData、WayLine/AI和Main接线仍待补。\n- 两次WaitForSeconds(.2)协程源已恢复；756集成（新增15）+10原生检查通过。原生验证暂停scaled等待、原始障碍物mesh、真实BindLevel与销毁保留。WayLine/AI是明确记录fixture效果，无完整原生战斗或新Player声明。\n- 首次障碍物测试错误要求Collider；原始恢复visual prefab只有mesh，改为验证MeshFilter，未添加虚构碰撞器。失败日志保留。\n- O/LEVEL_CONTROL_AUDIT.json / LEVEL_CONTROL_SOURCE_EVIDENCE.json（35方法及原字段布局）；method-map4681。日志analysis/level-control-integrated-final.log、level-start-native.log。无本任务待续进程。\n- 下一步Level InitGameData/剩余集合与factory、完整Tower/Soldier/WayLine/AI与prepared/state UI/Main，Player4462和其他29生命周期，再全关外验收。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('741 项 checks','756 项 checks').replace('caseCount=741；latestValidation 为 level config/player skins/loading page','caseCount=756；latestValidation 为 Level lifecycle/camps/prepared-start').replace('最新method-map4612；8控制器生命周期/共享绑定已实现并验证，剩30。','最新method-map4681；9控制器生命周期/共享绑定已实现并验证，剩29（仅生命周期方法计数，并非完整业务图）。').replace('in_progress / level-config-player-skins-loading-page','in_progress / level-lifecycle-camps-prepared-start').replace('最新集成日志 analysis/level-resource-integrated-fixed.log；加载页原生日志 analysis/loading-page-native-fixed.log。741集成+23加载页原生通过；历史实体池/资源链/Game/UI/基础控制器原生分别13/8/7/6/10项通过。无本任务待续进程。','最新集成日志 analysis/level-control-integrated-final.log；Level准备原生日志 analysis/level-start-native.log。756集成+10 Level准备原生通过；历史加载页/实体池/资源链/Game/UI/基础控制器原生分别23/13/8/7/6/10项通过。无本任务待续进程。');s+=text;p.write_text(s,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameLevelLifecyclePreparedNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/LEVEL_CONTROL_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps({'checks':756,'native':10,'fingerprints':len(files),'lifecycleImplementations':9,'remaining':29}))
