from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-baked-animation-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==357
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='original-model-roots';s['validation'].update(integratedChecksPassed=357,bakedAnimationChecksPassed=3);s['nextActions']=['Resolve source tag/color rules, attack display prefabId+1000 and auxiliary9033/9034 assets.','Connect original model roots, camera, loaders, color/animation and shop state for visual validation.','Restore remaining account lifecycle and outgame systems; full playable build/end-to-end verification.'];write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['sourceMethodsIndexed']=888;write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['original-model-roots']={'implementationReady':True,'productionConnected':False,'source':['model-roots.json','player-scene-singletons.json','player-scene-components.json','disassembly/Type4462-34192.txt','disassembly/Type4462-34201.txt'],'implementation':['OutgameModelRoots.cs','OutgameModelRootsImporter.cs'],'scope':'Ten original group/camera ancestor nodes, HomeCamera scalar projection/mask, group references, constructor scale1/localPosition0 model factory. Full GameSceneMono and InitScene adaptation not included.'};write(p,s)
p=o/'PLAYER_DISPLAY_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'GameControl singleton and GameSceneMono generic types resolved. Source fields NormalGroup44/DefenseGroup41/AttackGroup42 map categories1/2/3; initial positions (-4,.2,0)/(4,.2,0)/(0,-1,0), scales .85/.85/1, layer31. Source constructor curSelectNo3, model scale1/localPosition0. Original HomeCamera47 and ancestor transforms imported.','source':['model-roots.json','player-scene-singletons.json','player-scene-components.json','disassembly/Type4462-34192.txt','disassembly/Type4462-34201.txt']});s['confirmed'].append({'fact':'Soldier.SetSoldierColor(GameObject,int) skips all work if camp tag already matches; otherwise changes tag, colors first child MeshRenderer and sets root Renderer Default/-5. Renderer overload indexes ColorHelper.GetSoldierColor(max(camp,1)-1). Tag mapping static constants and source current LevelControl camp value remain to resolve.','source':['player-scene-components.json'],'functions':[5663,10316,7123]});s['pending']=['Concrete camp tag/color adapter, attack display variant and auxiliary asset imports','Scene aspect adaptation and camera lifecycle','Swipe/rotation and shop production wiring'];write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original GameSceneMono group/camera references') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original model group ancestors and HomeCamera','checksPassed':357,'outgameChecksPassed':90,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
note='\n\n## 原始模型展示节点与摄像机（357项）\n直接从 BuildPlayer-GamePlay/GameSceneMono 原始引用提取10个展示组/摄像机祖先节点，导入 OriginalModelRoots.prefab，保留局部变换、层级、active/layer和HomeCamera投影参数。OutgameModelRoots 按原构造 scale1/localPosition0 创建模型控制器。验证通过，357项（原267+关外90），Unity退出0。源方法888。已确认着色具有camp标签相同则完全跳过的规则，标签常量/当前camp、攻击展示变体、9033/9034资源与完整生产接线下一步继续；关外整体未完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameOriginalModelRoots','--result','pass','--evidence','357 integrated checks; original model group references and camera verified; full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded357; full goal remains active.')
