from pathlib import Path
import json,hashlib,datetime,subprocess,struct
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');assert r['passed'] and len(r['checks'])==860
mm=read(O/'method-map.json');methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['cls'] in ['AudioCompositeBase','AudioParallel','AudioSequence','AudioSingle','AudioActionBase'] or m['metadata'] in [26284,26285,26400,26401]]
h=W/'analysis/recover_outgame_manager_registry.py';env={'__file__':str(h)};exec(h.read_text(encoding='utf8').split('rows=[]')[0],env);u,ms,md,ts,mem=[env[k] for k in ['u','ms','md','ts','mem']];generic=[]
for addr in [3955208,3955220,3974436,3955224,3982872,3982868,3982880]:
 v=u(addr);idx=(v&0x1ffffffe)>>1;assert v>>29==6;metadata=struct.unpack_from('<3i',mem,483008+12*idx)[0];generic.append(dict(address=addr,methodSpec=idx,metadata=metadata,type=ms(ts[md[metadata][1]][0]),method=ms(md[metadata][0])))
extra=[dict(path=f'disassembly/{name}',sha256=hashlib.sha256((O/'disassembly'/name).read_bytes()).hexdigest()) for name in ['AudioNode-Utils-NewGameObject-f4685.txt','AudioNode-Utils-SetParent-f9635.txt','AudioAction-VirtualOnPlay-f1449.txt']]
write(O/'AUDIO_NODE_ACTION_SOURCE_EVIDENCE.json',dict(atUtc=now,methods=methods,genericMethods=generic,extra=extra,criticalEvidence=['AudioParallel.Stop26390 snapshots dictionary keys under Monitor/lock, gets actions by captured GUID, filters voice, Stop then Dictionary.Remove(loopIndex) @008cb3f7 using generic address3955208. This apparent original bug is preserved.','AudioSequence26412 coerces only actionType2->1, starts while queue empty BEFORE Enqueue. OnEnd26403 dequeues unless stopping, sends AudioPlayEnd, then rechecks stopping and Peeks/Plays. Stop26413 dequeues all, skips source-null entries, invokes Destroy afterward.','AudioSingle26414 creates using first ID or0, stores pending before stopping current; End26415 clears current before message and starts pending before clearing pending. Destroy26419 clears current only; pending remains.','AudioActionBase.Play26271/MoveNext26284 captures native root before config lookup, stores data before root/data gate, nonpositive volume=>1 (NaN preserved), voice, await OnPlay virtualslot6, assigns source and invokes start only for native-nonnull source. No disposal generation/cancellation guard.','AudioAction constructor26261 computes this.GetHashCode GUID then init26262 virtualAwake, AddUpdate, remove/add volume listener; Dispose26274 removes handle/reset0 then listener then virtual OnDispose then resource-unload/data-null. Failures preserve source partial writes.'],limits=['AudioCompositeBase.NewAudio override/factory selection and full AudioManager ownership remain pending. Current nodes require explicit action factory; no fallback simulates audible playback.','Action base is abstract. Once/Loop/Fade/LoopFade concrete OnPlay/OnStop/OnUpdate and resource/update services remain to implement. Test derived actions and scripted task completion are explicitly probes.']))
v=dict(atUtc=now,scope='Source Parallel/Sequence/Single node state, AudioActionBase async/lifecycle/volume, native Unity object boundaries in integrated checks',checksPassed=860,newIntegratedChecks=33,nativePlayModeChecks=0,freshPlayModeRun=False,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly'],notClaimed='Concrete Once/Loop/Fade/LoopFade playback, original resource/update/AudioManager host, fresh PlayMode/audio output or complete outgame Player')
a=dict(atUtc=now,status='partial-subsystem',sourceEvidence='AUDIO_NODE_ACTION_SOURCE_EVIDENCE.json',verification=v,findings=[
 'OutgameAudioNodes implements source native node roots with parent transform reset/layer inheritance, Parallel/Sequence/Single scheduling, pause/stop/destroy, and AudioPlayStart/End message order. IOutgameAudioAction/newAudio are required concrete playback dependencies, not synthetic success defaults.',
 'Parallel registers only at action start, so pending asynchronous loads cannot be stopped through its active map. Constructor-time callback observes null captured action but still publishes. Stop uses key snapshot under lock and source loop-index removal; StopByGUID only delegates Stop. Pause enumerates live dictionary, skips unloaded/destroyed native sources. Destroy clears collection/root without cancelling untracked actions, late events remain possible.',
 'Sequence starts first action before enqueue (synchronous completion source stale queue behavior retained); type2 coerced to1. End dequeues before message then starts next. Stop sets flag, dequeues source-loaded actions only, ignores voice, then destroys root/nulls queue/resets flag; callback failure leaves partial dequeue and flag. Pause visits all loaded queue entries, including not started entries.',
 'Single consumes first ID only (null/empty=>0), returns null handles, overwrites pending before stopping current. End clears current before event and promotes/plays pending before pending clear. Stop can start pending via completion before destroying root. Destroy retains pending, so late completion can promote it.',
 'OutgameAudioAction abstract production base restores hash GUID, source fields, virtual Awake/update registration/remove-add volume subscription, source async-void Play/config guards and assignment order, typed volume message, native pause/unpause, and partial-failure disposal. Source late awaited success after Dispose still assigns source and calls Start without resubscribing or restoring released config. No invented cancellation or once-only cleanup.',
 '860 integrated checks pass,33 new (20 node +13 action). Native GameObject/AudioSource fields are used in editor tests; action implementation, loading, scheduling and async errors use explicit probes/manual SynchronizationContext. No fresh PlayMode or audible playback claim. Method map4969; business lifecycle remains11/38,27 remaining.'
 ],remaining=['Implement concrete Once/Loop/Fade/LoopFade actions including source SDK branch, async resource operations and countdown behavior. Restore AudioManager/config/native root/listener/node ownership and AudioCompositeBase.NewAudio override/factory; wire shared UI/controller to complete native playback and verify it.','Continue remaining27 controllers and full Main/module/config/account/menu entry; finish all objective subsystems, preserved combat/data, persistence/restart/failure/return flows and runnable Player acceptance.'],artifacts=dict(integratedLog='analysis/audio-action-integrated.log',earlierNodeLog='analysis/audio-node-integrated.log'),disassembledMethodMapCount=len(mm))
write(O/'AUDIO_NODE_ACTION_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='audio-nodes-action-base',audioNodeActionAudit='generated/outgame/AUDIO_NODE_ACTION_AUDIT.json',nextPriority=' '.join(a['remaining']));d['validation']['integratedChecksPassed']=860;d['validation']['audioNodesActionBase']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='audio-nodes-action-base'];d['milestones'].append(dict(id='audio-nodes-action-base',atUtc=now,status='partial-subsystem',integratedChecks=860,nativeChecks=0,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,audioNodeActionAudit='AUDIO_NODE_ACTION_AUDIT.json');d['remaining'][0]=' '.join(a['remaining']);d['findings'].append('Shared source audio nodes and abstract action base now restored and860 integrated pass; required concrete action/resource/update/AudioManager factory remains open. Controller lifecycle count unchanged11/38.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=860,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 音频节点与动作基类增量\n- OutgameAudioNodes：真实native根对象/parent/local变换/layer；Parallel、Sequence、Single源调度、暂停、Stop/Destroy、开始结束消息。要求显式newAudio动作factory，尚不提供假成功或替换音频后端。\n- Parallel开始回调才入字典，未开始的异步load不在Stop覆盖内；Stop源码lock+keys快照+Remove(i)循环索引bug保留（不是Remove(keys[i])）；Pause live字典；销毁后迟到callback仍发消息。\n- Sequence type2只转1、首动作Play先于Enqueue、同步结束可留下已结束队首；End先Dequeue/消息/再Peek.Play。Stop置flag并Dequeue，只有已有native AudioSource才Stop，忽略voice，尾部Destroy清queue/resetflag；失败保留部分状态。Single firstID/null=>0，Pending先写再停Current；End清Current->消息->Pending.Play->清Pending；Destroy保留Pending，迟到End仍可能启动。\n- OutgameAudioAction抽象生产基类：this.GetHashCode GUID、OnAwake/update注册/remove-add音量监听、async void Play先捕获Root再取Data、<=0音量=1/NaN保留、await OnPlay后写source/开始回调，无cancel/dispose版本gate。Dispose removeHandle后归零、监听、虚拟清理、Unload后Data=null，失败顺序和反复Dispose保留。\n- 860集成通过（20 node+13 base新增），日志analysis/audio-action-integrated.log，O/AUDIO_NODE_ACTION_SOURCE_EVIDENCE.json与AUDIO_NODE_ACTION_AUDIT.json。native GameObject/AudioSource属性用于编辑器测试，加载/update/具体动作/async context为明确probe；本批没有新PlayMode/发声/Player验证。本任务无待续进程。\n- 仍11/38控制器生命周期方法，余27；method-map4969。下一步具体Once/Loop/Fade/LoopFade、原始资源/SDK/倒计时，以及AudioManager root/listener/config/node与Composite.NewAudio override/factory，接通UI/controller原生音频。完整关外goal继续active。\n- 下轮源码索引：基类3405/26260..26283，Play状态机3404/26284（1420bytes）；Once3415/26327..26334，Loop3410/26301..26307，Fade3408/26286..26295，LoopFade3413/26310..26321；嵌套OnPlay状态机已经在method-map，但按declaring type取，不要猜嵌套type顺序。AudioManager3421/26345..26369，UI3431/26421..26435，AudioData3420 offsets8 id/12Voice/16Atype/20Ptype/24Start/28End/32Vol/36ResPath。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('827 项 checks','860 项 checks').replace('caseCount=827；latestValidation 为 audio controller/settings/UI routing','caseCount=860；latestValidation 为 audio nodes/action base').replace('in_progress / audio-controller-settings-ui-routing','in_progress / audio-nodes-action-base').replace('最新集成日志 analysis/audio-control-integrated.log。827集成通过，本批未跑原生音频；','最新集成日志 analysis/audio-action-integrated.log。860集成通过，本批未跑原生音频；');p.write_text(s+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameAudioNodesActionBase','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/AUDIO_NODE_ACTION_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=860,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
