from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==476
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='platform-adapter-factory';s['validation'].update(integratedChecksPassed=476,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['platform-adapter-factory']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type9202-64479.txt','disassembly/Type9240-64778.txt','disassembly/Type9254-64922.txt'],'implementation':['OutgameAdAdapterFactory.cs','OutgameAdModuleEntry.cs'],'scope':'Source platform normalization, first-day suppression and all adapter-kind mappings. Cached module factory entry bypasses function-active gate. Actual WxVideo constructor integrated with lazy list/init/preload in validation. Other adapter constructors and production runtime remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original ADModule platform factory mapping and source WxVideo construction chain') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original ADModule platform factory mapping and source WxVideo construction chain','checksPassed':476,'outgameChecksPassed':209,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'ADModule.createAdAdapter firstDayNoAd suppresses before key access. Platform >=10001 normalizes by100; maps banners424/484/883, interstitials424/425/883, video883 and native variants883. WX manager factory caches module and bypasses CheckFunctionActive.476 checks pass including extended88301 config through source list, init, serial preload and native loaded callback.','source':['disassembly/Type9202-64479.txt','disassembly/Type9240-64778.txt','disassembly/Type9254-64922.txt'],'implementation':['OutgameAdAdapterFactory.cs','OutgameAdModuleEntry.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'PLATFORM_ADAPTER_FACTORY_AUDIT.json';write(p,{'target':'wxcf1394487200e48f/43','source':['disassembly/Type9202-64479.txt','disassembly/Type9240-64778.txt','disassembly/Type9254-64922.txt'],'firstDayField':{'declaringType':9202,'staticOffset':4,'name':'firstDayNoAd'},'normalization':'platformId<10001 ? platformId : platformId/100','sourceAddresses':{'firstDayGate':'006338b8','normalization':'006338c8','video':'006339d8','managerModuleCache':'0045fe5d'},'mapping':{'BANNER':{'424':'WxCpsBanner','484':'WxGridBanner','883':'WxBanner'},'contains INTERSTITAL':{'424':'CpsInters','425':'ApiInters','883':'WxInters'},'VIDEO':{'883':'WxVideo'},'NATIVE/NATIVE_BIG/NATIVE_START/NATIVE_OVER/NATIVE_SPLASH':{'883':'WxNative'}},'checks':476,'productionConnected':False,'remaining':['Nonvideo adapter constructor implementations','Production SDK runtime','Full configuration acquisition and startup binding']})
note='\n\n## 平台适配器工厂与源列表连接（476项）\n还原ADModule.createAdAdapter首日免广告门控、>=10001平台编号除100归一、横幅/插屏/视频/原生适配器类型映射；WXFunctionManger工厂入口使用缓存模块且不经过Active检查。验证88301配置保留原始平台编号，并通过工厂创建WxVideo、源init、惰性平台列表、Serial预加载到原生loaded回调进入缓存。476项（战斗267+关外209）通过，Unity退出0。非视频类型目前只确认工厂映射，构造实现未完成；真实SDK及完整生产启动连接仍待完成，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgamePlatformAdapterFactory','--result','pass','--evidence','476 integrated checks; source platform factory mappings, first-day gate, module cache and WxVideo construction/preload chain verified; production runtime pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded476; full goal remains active.')
