from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-ads-playmode-validation.json')
assert r['passed'] and len(r['checks'])==554 and v['passed'] and play['passed'] and len(play['checks'])==7
sources=['disassembly/Type3135-'+str(i)+'.txt' for i in [23907,23908,23910,23912]]+['sdk-button-registry-generics.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='sdk-button-registry';s['validation'].update(integratedChecksPassed=554,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['sdk-button-registry']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameSdkButtonRegistry.cs','OutgameVideoButton.cs'],'scope':'Original SDK button registration, destroyed-button cleanup and readiness fan-out restored; native PlayMode startup now uses recovered registry. Function state owner and concrete platform transport remain explicit dependencies.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='DBTSDKManager button registration and readiness source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'SDK button registration/readiness with refreshed native PlayMode timing','checksPassed':554,'outgameChecksPassed':287,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-ads-playmode-validation.json','playModeChecksPassed':7,'freshPlayModeRun':True,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'sdk_button_registry_verified_concrete_platform_pending','source':sources,'verified':['Function registration retains duplicate Button entries and duplicate native onClick listeners','Registration appends before SetActive(IsOpen) and optional platform callback, then cleans destroyed entries','Cleanup traverses list backwards using Unity null equality','CheckVideoIsReady queries feature5 then readiness; ChangeVideoBtnState queries feature5 again','Change sets feature15 before cleanup and enumerating registered feature5 buttons implementing original video-state interface','Only video-state-capable buttons receive ready2/not-ready1 state','Actual native ShopUI Start now registers through recovered registry and uses real source readiness refresh path'],'remaining':['Complete SDK function state owner and refresh APIs','Concrete platform implementation selected during SDK startup','Production account/menu/report owner and full persistence/build/E2E'],'checks':554,'freshAdsPlaymodeChecks':7,'priorFlyPlaymodeChecks':8,'dynamicScope':'Fresh actual Unity PlayMode with restored registry; readiness source and SDK/report transport remain fixtures; historical fly PlayMode not rerun'}
write(o/'SDK_BUTTON_REGISTRY_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'DBTSDKManager button registration/readiness subset restored and exercised through actual native Start in fresh7check PlayMode. Complete SDK state owner and concrete platform/account integration remain pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-ads-playmode-validation.json']});write(p,s)
note='\n\n## SDK按钮注册与就绪刷新（554项+独立7项）\n提取DBTSDKManager/ISDK，索引2755，并解析List<Button>/字典操作。新增OutgameSdkButtonRegistry，保留重复注册/原生监听、注册→显示状态→平台通知顺序及Unity销毁对象倒序清理；CheckVideoIsReady和ChangeVideoBtnState分别检查功能5，先设置功能15，再刷新原视频状态接口为2或1。原生OutgameVideoButton实现状态接口，PlayMode宿主不再直接改按钮状态，改经恢复后的注册表。554项集成和重新运行的7项真实PlayMode通过，Unity退出0；原8项飞币PlayMode未重跑。就绪来源、完整SDK功能状态和具体平台播放仍待恢复，生产账号菜单及完整构建尚未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSdkButtonRegistry','--result','pass','--evidence','554 integrated checks and7 fresh actual Ads PlayMode checks; prior8 fly PlayMode not rerun. SDK function owner/concrete platform/account composition pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded554; full goal active.')
