from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();report=W/'analysis/unity-integrated-validation.json';r=read(report);assert r['passed'] and len(r['checks'])==1050
assert 'AREABATTLE_INTEGRATED_PASS cases=1050' in (W/'analysis/global-item-rewards-integrated-verified.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');ids={34573,34592,34594,34597,34598,34589,34581,34596,34583,34588,34564,34565,34566,34567,34568,34310,34311,34312,34317,34321};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
findings=[
'GlobalItemManager AddRewards34573/AddRewardsModel34592 snapshot override delegate before default work. Override receives original List<RewardData>, int0 (Action2 metadata plus raw wasm f3198 confirms). Default live indexed loop calls Change(id,longcount); regular path then current IItemManager.AddRewards(original list), model path has no host callback. ExpendReward34594 unchecked negates long count then calls host.ExpendReward(original list), no balance guard.',
'Change helper34589 existing entry: unchecked Int64 add then statistics(eventId,currentCount,id). New entry: construct row and statistics before holdTime0/Items.Add. Reentrant insertion can cause Add duplicate exception. Then helper34596/wasm12037 updates ITEM snapshot, ItemUI_RefreshUserItem(id), Report(id,delta,0), dirty=true. Preliminary product-snapshot identification was incorrect, fixed before final validated artifact. GLOBAL_ITEM_REWARD_FIELD_AUDIT.json verifies36/44 Dictionary<int,ItemUserData4548>, versus32/40 ProductUserData4547; no product snapshot mutation here.',
'Report34581 first Item_ItemChange(id,longdelta), then current ReportDel override(id,longdelta,reason). Otherwise current config.Items[id] indexer: absent key throws, existing null emits source Debug.LogError and returns. Resolve report factory before populating id/item_game/type1/type2. gain when delta>=1, otherwise cost including0. Magnitude conversion out of signed32 range becomes0; abs int.MinValue remains int.MinValue via unchecked bit arithmetic. Current balance after report creation becomes0 outside signed32 range. Resolve report service again to send. Typed report fields represent only source-owned fields; real ReportManager/platform delivery is explicit host boundary.',
'GetItem34597 null config returns null; nonnull GetCommonItem delegate result takes precedence, null result falls through current host.GetItem(config). AddRewardsByItemSelf34598 override replaces whole path, otherwise each current config/current GetItem invokes virtual AddItemOnlyModel for nonnull entities, then one current host.AddRewards(original list).',
'ItemBase4541 constructor current shared config.Items[id] direct lookup. ItemToReward34567 new list; nonnullconfig adds RewardData(config.id,longcount,order0), null returns empty. AddItem34565 and AddItemOnlyModel34566 capture current GlobalItemManager before virtual ItemToReward, then call respective reward engines. Use34568 emits Item_Use(id,longcount), builds use report id/game/type1/type2 and sends; does not decrement stock itself.',
'VirtualItemBase4492 delegates AddItem and Use to ItemBase, inherits AddItemOnlyModel/ItemToReward. Gold4496 and Diamond4494 only chain constructors, no additional effects. Concrete constructor service now creates those two actual entities; remaining seven source entity types require explicit AdditionalConstructors, no base-item fallback.',
'Global lifecycle Init34588 stores actual IItemManager host first before record decode; InitializeWithHost captures that host and local clock method, accepts null host/local clock fallback. ItemManager.UpdateDataCallBack now uses this actual host path. Added separate method name to preserve older clock-only helper tests that pass null.'
]
limits=['Seven concrete source item types remain unimplemented: Strength4499, Commander4493, HeroPiece4498, HeadBox4497, GamePoints4495, PackageOpenAuto4490 and PackageOpenManual4491.','Report creation/send is explicit host API with verified source field assignment/order; no live ReportManager/SDK delivery claimed.','Tests use isolated memory storage and explicit reporting/lifecycle hosts. Real production Gold/Diamond/engine/manager/tool/local/shared state compose, but no fresh native PlayMode or full outgame Player.','Controller lifecycle remains14/38; full Main/account/business graph incomplete.']
write(O/'GLOBAL_ITEM_REWARDS_SOURCE_EVIDENCE.json',dict(atUtc=now,methods=methods,fieldAudit='GLOBAL_ITEM_REWARD_FIELD_AUDIT.json',criticalEvidence=findings,limits=limits))
v=dict(atUtc=now,scope='Global reward engine, overrides/report conversion, ItemBase and concrete Gold/Diamond; real module->factory->entity->global->manager->tool->storage chain',checksPassed=1050,newIntegratedChecks=16,nativePlayModeChecks=0,freshPlayModeRun=False,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly'],notClaimed='Seven other concrete entities, live report platform delivery, full Main and outgame Player')
remaining='Restore remaining virtual entities Strength4499/Commander4493/HeroPiece4498/HeadBox4497/GamePoints4495 and PackageOpenAuto4490/Manual4491, bind AdditionalConstructors to actual effects and source randomness. Integrate report host into recovered reporting owner. Complete24 remaining controller lifecycles/full source-default legacy Main/account/menu/business flows and runnable outgame Player acceptance.'
a=dict(atUtc=now,status='global-rewards-and-gold-diamond-real-chain-seven-entities-pending',sourceEvidence='GLOBAL_ITEM_REWARDS_SOURCE_EVIDENCE.json',verification=v,implementedLifecycleControllers=14,remainingLifecycleControllers=24,findings=findings,remaining=[remaining]+limits,disassembledMethodMapCount=len(mm),artifacts=dict(integratedLog='analysis/global-item-rewards-integrated-verified.log'));write(O/'GLOBAL_ITEM_REWARDS_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='global-item-rewards-gold-diamond',globalItemRewardsAudit='generated/outgame/GLOBAL_ITEM_REWARDS_AUDIT.json',nextPriority=remaining);d['validation']['integratedChecksPassed']=1050;d['validation']['globalItemRewards']=v;d['milestones'].append(dict(id='global-item-rewards-gold-diamond',atUtc=now,status=a['status'],integratedChecks=1050,remainingLifecycleControllers=24));write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=1050,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=report.stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 Global奖励引擎与金币/钻石实体增量\n- 1050集成全通过（新增16），最终日志analysis/global-item-rewards-integrated-verified.log；Unity43036已退出。首次70128编译因Initialize(null)重载歧义失败，改为InitializeWithHost后64040跑1049通过；复核snapshot函数发现本轮初稿/初始说明把34596误认商品快照，已按字段36/44修成道具快照并加nullhost检查，最终43036跑1050通过。只有最终结果用于manifest。无新native/Player，14/38 lifecycle不变；method-map5152。\n- 新OutgameGlobalItemRewards.cs：AddRewards/AddRewardsModel委托Action<List<RewardData>,int>覆盖整个默认路径、第二参0；默认live indexed rows逐条Change，regular末尾currentIItemManager.AddRewards(original)，model无host。Expend unchecked负long再Change，无不足检查，末尾host.ExpendReward原正数list。AddRewardsByItemSelf逐条current config→GetItem→非null AddItemOnlyModel，再host.AddRewards一次。GetItem nullconfig直接null、common非null优先、common返回null回退host。\n- Change helper34589既有row先unchecked longadd后统计；newrow先构造/统计再holdTime0/Items.Add，重入插入会让原Add抛异常。随后正确SnapshotItem34596/f12037（不是SnapshotProduct34583）→ItemUI_RefreshUserItem→Report→dirty=true；O/GLOBAL_ITEM_REWARD_FIELD_AUDIT.json与analysis/audit_global_item_reward_fields.py以metadata泛型和offset证明live36/snapshot44 ItemUserData4548，而product32/40 ProductUserData4547。旧说明和本轮初版商品快照推断作废。\n- Report helper34581先Item_ItemChange(id,longdelta)→ReportDel(id,longdelta,reason)如有则替代默认。默认currentconfig.Items[id]（missing抛、presentnull日志返回）；报告factory先执行，填id/item_game/type1/type2；delta>=1用get，否则cost（0也cost），delta出signed32范围转0，intMin abs按WASM位算仍intMin；balance factory后读取，出范围0；再次resolve报告服务发送。IOutgameItemReports明确只承载源拥有字段和创建/发送顺序，尚未实际SDK发送。\n- 新OutgameItemBase.cs：ItemBase ctorcurrentconfig.Items[id]，ItemToReward新list，config非null单row(id,longcount,order0)否则empty；Add/OnlyModel先capture currentengine再virtualToReward→AddRewards/Model。Use只Item_Use(id,longcount)→create/填use report→send，不扣数量。VirtualBase转发；真实Gold4496/Diamond4494纯构造继承。OutgameItemEntityServices.Construct这两类真创建，剩七类继续required AdditionalConstructors，不fallback。IOutgameItemEntity新增AddItemOnlyModel，旧recordingfixture仅兼容接口。\n- GlobalLifecycle新增RewardHost和InitializeWithHost(text,host)，先发布host再既有record初始化，hostnull允许localclockfallback；ManagerCallback改用此入口，actualManager实现IOutgameGlobalItemRewardHost，解决此前只传clock丢失奖励host问题。\n- 15新GlobalRewardschecks+1Module真实链：统计新/旧prefix、重入Add冲突、正确ItemSnapshot先于UI、四委托替代、live奖励list、report覆盖、zero/long溢出/intMin金额、negative库存/longMin负号、配置missing/null、create回调改余额、report失败、commonfallback、BySelf模型路径、Base空配置/Use不扣、virtualToReward前捕获engine、nullhost。实际module→manager→factory→Gold→global→manager→Tool/local→pool/storage保存，再实例化读取，金币+7/-3两套库存均4；无实体recording替身但报告/生命周期为显式hostfixture。\n- O/GLOBAL_ITEM_REWARDS_SOURCE_EVIDENCE.json/AUDIT.json、状态/manifest/交接已同步；完整目标继续active。下一步具体实体Strength4499、Commander4493、HeroPiece4498、HeadBox4497、GamePoints4495、PackageOpenAuto4490/Manual4491，源body均已抽取（Type449x-343xx）。注意共享WASM函数label会显示ActivityVirtualItemBase/TaskLivenessPoint，要按metadata继承解释。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('1034 项 checks','1050 项 checks').replace('caseCount=1034；latestValidation 为 ItemModule/ItemManager/factory routing','caseCount=1050；latestValidation 为 global rewards and Gold/Diamond entities').replace('最新集成日志 analysis/item-module-integrated.log。1034集成通过','最新集成日志 analysis/global-item-rewards-integrated-verified.log。1050集成通过').replace('in_progress / item-module-manager-factory-routing','in_progress / global-item-rewards-gold-diamond');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameGlobalItemRewardsGoldDiamond','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/GLOBAL_ITEM_REWARDS_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
assert all(hashlib.sha256((W/f['path']).read_bytes()).hexdigest()==f['sha256'] for f in d['sourceFingerprints'])
print(json.dumps(dict(checks=1050,controllers=14,remaining=24,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
