from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==528 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type3667-'+str(i)+'.txt' for i in [28681,28683,28684,28685]]+['disassembly/Type3666-'+str(i)+'.txt' for i in range(28687,28691)]
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='normal-pool-load-callbacks';s['validation'].update(integratedChecksPassed=528,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['normal-pool-load-callbacks']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameNormalPool.cs'],'scope':'NormalPool spawn, new/legacy loading route dispatch, cache callback ordering, instance registration and returned-object hits. New-resource branch connected to recovered-prefab Play Mode adapter. Original resource provider internals, manager lifecycle and DestroyObjectPool pending; legacy branches statically restored but not dynamically covered.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Object<T> shared source wrapper') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original pooled object count/lifecycle wrapper','checksPassed':528,'outgameChecksPassed':261,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'spawn_cache_callbacks_verified_native_provider_pending','source':sources,'verified':['Pool hit returns target without resource load','Concurrent misses issue separate loads; first completed non-null handle cached; every callback instantiates its delivered handle','Cached handle creates additional instances while original pooled instances are in use','Null cached-mode completion performs no callback','Instances registered as spawned before caller completion','Actual fly coroutine now uses NormalPool adapter and recovered native prefab resources'],'staticOnly':['Legacy ResourcesInfo name resolution and synchronous Assetbundle callback branch','Invalid mainObject warns and notifies null then continues instead of returning'],'remaining':['NormalPool DestroyObjectPool: remove from manager, destroy root, unload resource/asset caches in source order','Original NewResLoadHelper and ReleaseUIForm provider internals','Production account and page resource composition','Full Player build and end-to-end acceptance'],'knownDifferences':['Host interfaces expose original provider operations; recovered native resources currently supplied in isolated fixture','Pool exception/logging differences retained'],'checks':528,'playmodeChecks':8}
write(o/'NORMAL_POOL_LOAD_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'NormalPool loading callbacks and first-completion cache restored from28681/28684/28685/28687..28690; actual fly Play Mode now uses adapter. Original provider internals and pool destruction pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## NormalPool加载缓存与回调（528项 + 独立8项动态检查）\n新增OutgameNormalPool，恢复池命中、缓存资源与非缓存路径、新旧加载器分流、加载完成注册以及回收转发。源28687/28688确认空异步结果不回调，并发缺失不合并，先完成句柄留在缓存，每个回调仍使用自己的结果创建实例；28681/28684异常资源告警回调后继续的行为也保留。新增逆序完成与复用检查，实际飞币通过此适配层访问已恢复原资源，528项集成及8项动态检查通过，Unity退出0。底层资源加载当前为显式恢复资源夹具；旧加载分支尚仅静态恢复，DestroyObjectPool资源卸载顺序、原提供者、生产账号页面和完整构建验收待完成。\n' 
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameNormalPoolLoadCallbacks','--result','pass','--evidence','528 integrated checks and8 independent actual Play Mode checks; complete pool and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded528; full goal active.')
