from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==445
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='wx-video-loading';s['validation'].update(integratedChecksPassed=445,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['wx-video-loading']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type9186-64360.txt','disassembly/Type9186-64364.txt','disassembly/Type9186-64365.txt','disassembly/Type9185-64371.txt','wx-video-config-resolution.json','wx-build-setting-fields.json'],'implementation':['OutgameWxVideoLoading.cs'],'scope':'WxVideoAdapter request/load/cache-clear lifecycle restored with native handle interface. State5 autoload reuse and scaled0.1 delay; one-id multiton rule, request error, destroy ordering. Concrete native bridge and base notify listeners pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original WxVideoAdapter loading and reuse lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original WxVideoAdapter loading and reuse lifecycle','checksPassed':445,'outgameChecksPassed':178,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Usage3984736 is SingleScriptObject<WXBuildSetting>.I; field76 is MiniGameCommonPlugin. WxVideoAdapter loading restores multiton=false only for one configured id, adunit- prefix, load/error listeners, state5 automatic load flag, reuse via scaled WaitForSeconds0.1 before notify success, destroy before clearing native reference. Native handle implementation and DAU base notification chain still pending.445 checks pass.','source':['WX_VIDEO_ADAPTER_AUDIT.json','wx-video-config-resolution.json','wx-build-setting-fields.json'],'implementation':'OutgameWxVideoLoading.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'WX_VIDEO_ADAPTER_AUDIT.json';a=read(p);a['loadingImplementation']='OutgameWxVideoLoading.cs';a['resolvedConfig']='WXBuildSetting.MiniGameCommonPlugin (offset76)';a['validation']={'runtimeChecks':445,'liveSdkVerified':False};a['pending']=['Restore DAUAdsAdapter notify/listener state transitions.','Implement video show/close native callbacks and analytics with confirmed MiniGameCommonPlugin flag.','Connect concrete native handle bridge and verify controller variant/runtime config.'];write(p,a)
note='\n\n## 微信视频加载与自动加载复用（445项）\n新增OutgameWxVideoLoading，恢复单广告位关闭multiton、adunit-键、加载/错误监听、state5自动加载标志及0.1秒缩放延迟复用。清理遵守先Destroy后清引用，异常保留引用。解析3984736为SingleScriptObject<WXBuildSetting>.I，字段76确认为MiniGameCommonPlugin。445项（战斗267+关外178）通过，Unity退出0；源码索引1653。实际原生handle桥、DAU基类notify监听链和展示关闭分析上报仍待接入，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameWxVideoLoading','--result','pass','--evidence','445 integrated checks; Wx native loading policy and automatic reuse verified with controlled handle; native bridge and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded445; full goal remains active.')
