from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==542 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type10741-'+str(i)+'.txt' for i in [74413,74414,74415,74417,74423]]+['disassembly/Type10740-74434.txt','video-button-generics.json','video-button-virtual-slots.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='shop-video-click';s['validation'].update(integratedChecksPassed=542,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['shop-video-click']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameVideoClick.cs','OutgameVideoButtonCompletion.cs'],'scope':'UIVideoBtn click ordering and shared five-second/per-button one-second cooldown recovered. Completion uses integer delay with scaled WaitForSeconds. Native Button adapter, button configuration/readiness/reports and actual ad host remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='UIVideoBtn click and delay-report source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Video click cooldown, event ordering, mutation/error boundaries and scaled report coroutine','checksPassed':542,'outgameChecksPassed':275,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'freshPlayModeRun':False,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'click_core_and_delay_verified_native_adapter_pending','source':sources,'verified':['Missing data skips audio and all other effects','PlayAudio executes before cooldown gates; global play gate precedes click gate','Update uses strict greater-than unscaled clock deadlines; click never expires timers itself','Click locks one second before click report, UnityEvent and base Button.OnPointerClick','Button state re-read after callbacks; only state2 sets shared five-second lock, reports play, then shows ad','Exceptions preserve prior state changes and stop later calls','Completion does not reset shared cooldown','DelayReport argument is Int32, not bool; WaitForSeconds uses scaled time; create report before SDK flag15(false) gate and ready report'],'remaining':['Native Button subclass adapter and original serialized properties','Button configuration, readiness/state and reporting implementation','Actual AdsManager/platform callback host','Production account/menu composition, persistence/build/E2E'],'checks':542,'priorPlaymodeChecks':8,'dynamicScope':'Integrated editor checks with explicit ad result fixture; no real SDK or fresh PlayMode claim'}
write(o/'SHOP_VIDEO_CLICK_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'UIVideoBtn source click and cooldown core restored with callback mutation/error boundaries. Corrected DelayReport argument to source Int32 and implemented scaled report coroutine. Native Button adapter and actual ad/platform/account composition pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## 视频按钮点击与延迟上报（542项）\n恢复UIVideoBtn点击核心：无配置直接返回；音效先于冷却拦截；单按钮1秒、全局播放5秒，Update以unscaledTime严格超过截止时间才解锁；点击报告、UnityEvent和原Button回调后重新判断state2，再设置播放锁、上报和请求广告。异常保留此前副作用。确认DelayReport参数为Int32并修正之前Action<bool>接口，恢复scaled WaitForSeconds及创建报告→SDK开关→就绪报告顺序。542项集成通过，Unity退出0；原8项PlayMode未重跑。测试中的广告结果为显式fixture，不代表真实SDK。原Button适配、配置/状态/上报、广告平台、生产账号菜单及完整构建仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameShopVideoClick','--result','pass','--evidence','542 integrated checks; prior8 PlayMode checks not rerun. Native Button adapter, ad platform and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded542; full goal active.')
