from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==490
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-item-records';s['validation'].update(integratedChecksPassed=490,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-item-records']={'implementationReady':True,'productionConnected':False,'source':['global-item-fields.json','disassembly/Type4542-34588.txt','disassembly/Type4544-34604.txt','disassembly/Type4547-34613.txt'],'implementation':['OutgameItemRecords.cs'],'scope':'Original ItemManagerData/ItemUserData/ProductUserData wire and constructor/missing-record defaults; preserves Int64 item quantities, prices and timestamps, keyed-list duplicates/order. Global item dictionaries, timer/statistics registration and production ItemManager provider pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original global item and product record wire format') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original global item and product record wire format','checksPassed':490,'outgameChecksPassed':223,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'ItemManager4500 is original registered provider and delegates callback/init/save/release to GlobalItemManager. Global records differ from LocalData inventory: itemCount/price arrays/prices/time are Int64. Source missing decode creates lists and sets saveTimestamp,lastExitDayOfYear=-1, whereas held {} stayszero.490 checks pass for wire/defaults; global initialization consumers and registration provider not implemented.','source':['global-item-fields.json','disassembly/Type4542-34588.txt','disassembly/Type4500-34335.txt','data-manager-registration-roster.json'],'implementation':'OutgameItemRecords.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';write(p,{'target':'wxcf1394487200e48f/43','status':'records_implemented_lifecycle_pending','sourceMethodsIndexed':len(read(o/'method-map.json')),'registeredTypeIndex':4500,'source':['global-item-fields.json','disassembly/Type4542-34588.txt','disassembly/Type4542-34576.txt','disassembly/Type4542-34579.txt','disassembly/Type4542-34580.txt'],'confirmed':['Init stores IItemDataFunction host then decodes record; null creates lists and timestamps-1','Init gets current time, converts to timestamp, SynServerTime, invokes item/product initialization methods, sets dirty and registers statistics callback','GetNowDateTime with nonnull host invokes interface slot4 twice and returns second result; null host uses DateTime.Now','SynServerTime writes data.saveTimestamp and installs update handle only if absent','OnSave rebuilds source lists from runtime state then updates timestamp and serializes record'],'implementation':'OutgameItemRecords.cs','checks':490,'productionConnected':False,'pending':['Resolve generic collections and item/product initialization methods34586/34587','Implement full GlobalItemManager save list reconstruction','Implement update/time/statistics/reward side effects','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately; absence of auto attribute is not proof of total unreachability']})
note='\n\n## 已注册ItemManager与全局物品存档（490项）\n确认ItemManager4500为当前游戏注册项，回调/init/save/release转GlobalItemManager，提取其完整方法并新增global-item-fields.json，方法索引1774。新增OutgameItemRecords恢复ItemManagerData/ItemUserData/ProductUserData/购买方式次数的原字段、列表与构造默认值；物品数量、价格/价格数组、时间戳为Int64，独立于LocalData Int32库存。空解码sentinel=-1与已有{}零默认不同，重复购买方式记录顺序保留。490项（战斗267+关外223）通过，Unity退出0。尚未接全局字典、时间/统计、奖励消费者与真实4500Provider；原注册池已接管理器仍3个。StoreDataManager手动可达性继续待查，未推断完全无用。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameGlobalItemRecords','--result','pass','--evidence','490 integrated checks; original global item/product wire, Int64 fidelity and missing-record defaults verified; registered ItemManager runtime lifecycle pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded490; full goal remains active.')
