from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==443
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='video-controller';s['validation'].update(integratedChecksPassed=443,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['video-controller']={'implementationReady':True,'productionConnected':False,'source':['video-controller-callback-audit.json','disassembly/Type7533-55035.txt','disassembly/Type7533-55036.txt','disassembly/Type7532-55039.txt','disassembly/Type7532-55040.txt'],'implementation':['OutgameVideoController.cs'],'scope':'Shared serial/echelon show/close wrappers now implement router controller interface and call restored show flow. Source completion flag, clock, readiness and finish/reset/close ordering connected. Native adapter events, controller initialization variant and SDK configuration still incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original video controller callback lifecycle and composed reward route') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original video controller callback lifecycle and composed reward route','checksPassed':443,'outgameChecksPassed':176,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'OutgameVideoController implements source shared Serial/Echelon show/close wrappers and IOutgameAdController. Reads realtime before clearing completion flag; stores shown callback and closures, reward closure unconditionally sets completed=true while close closure ignores argument and reads current flag. Close scans state4 candidates, finishes then clears shared flag then calls current close wrapper, retaining callback for subsequent entries. Reward entry now tested through module/router/restored controller/show flow with test adapter. 443 checks pass; native SDK events and variant initialization incomplete.','source':['video-controller-callback-audit.json','disassembly/Type7533-55035.txt','disassembly/Type7533-55036.txt'],'implementation':'OutgameVideoController.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'video-controller-callback-audit.json';a=read(p);a['pending']=['Verify serial versus echelon initialization from original active ad configuration.','Restore native adapter initialization and listener events before production SDK connection.'];a['implementation']=['OutgameVideoController.cs','OutgameAdShowFlow.cs'];a['validation']='443 integrated checks; restored entry/controller/display flow tested with controlled adapter, not live SDK';write(p,a)
note='\n\n## 视频控制器与奖励入口接线（443项）\n新增OutgameVideoController实现路由控制器接口，连接已恢复showAd流程，保持Serial/Echelon共有show/close语义。show先读取时钟再清完成标志，完成回调忽略bool并置true，关闭回调忽略传入bool读取当前完成标志；close仅处理state4，依次finish、共享showing=false、当前close回调，多候选不擅自去重。奖励入口→模块→路由→恢复控制器→展示流程已用受控适配器验证完整调用链和提前关闭、重复关闭、清理异常。443项（战斗267+关外176）通过，Unity退出0。仍缺实际SDK事件、初始化变体与配置连接，完整目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameVideoController','--result','pass','--evidence','443 integrated checks; restored video controller, completion flag, close ordering and reward route verified with controlled adapter; live SDK and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded443; full goal remains active.')
