from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==516
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-tool-collection';s['validation'].update(integratedChecksPassed=516,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-tool-collection']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4057-31241.txt','disassembly/Type4058-31212.txt','disassembly/Type4056-31238.txt','disassembly/Type4053-31227.txt'],'implementation':['OutgameFlyToolCollection.cs','OutgameFlyToolStart.cs'],'scope':'Original fly-icon count, label baseline, per-arrival text and completion ordering; corrected callback type. Actual pool/tween/coroutine host pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Source fly-tool collection display and completion') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Source fly-tool collection display and completion','checksPassed':516,'outgameChecksPassed':249,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Fly collection only changes display, never grants again. Source request.callback is Action, not integer mode; addMoneyShow gates text only. Last arrival corrects remainder then invokes callback. Baseline subtracts amount only for gold/diamonds when displayed text equals current inventory.','source':['disassembly/Type4057-31241.txt','disassembly/Type4056-31238.txt','disassembly/Type4053-31227.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'FLY_TOOL_COLLECTION_AUDIT.json';write(p,{'status':'collection_logic_verified_visual_host_pending','checks':516,'source':['disassembly/Type4057-31241.txt','disassembly/Type4058-31212.txt','disassembly/Type4056-31238.txt','disassembly/Type4053-31227.txt'],'correction':'Previous request.Mode int was provisional and incorrect. Metadata names callback/addMoneyShow and arrival invocation prove Action Completion and bool UpdateDisplayedValue; ShopUI passes null completion.','verified':['Create count5 through100; above100 min(10,6+(amount-100)/50), with unchecked subtraction','Int32.Parse target label; gold/diamond label equal to current inventory subtracts amount for animation baseline','Asset paths golditem1001,diamonditem1002,strengthitem1004; other ids null','Each arrival returns object to pool, increments count, plays target tween, optionally updates label, then completion only at exact total','Final arrival snaps to end value to correct truncated division remainder; no second inventory grant','Pool exception occurs before count mutation; invalid label throws'],'remaining':['Recover actual gold/diamond/strength prefab assets','Instantiate original pool and Tween animation with observed .025s spawn cadence,1.1s cleanup wait,.4s scatter,.5s return and target pulse','Confirm tween generic settings and clean-up scheduler before production connection']})
p=o/'SHOP_FEEDBACK_AUDIT.json';audit=read(p);audit['correction']='Effect callback argument is Action Completion=null in ShopUI, not integer Mode. Last boolean is addMoneyShow. Native feedback and fly-start signatures corrected at516.';write(p,audit)
note='\n\n## 飞行图标收集与完成回调（516项）\n新增OutgameFlyToolCollection，按源码恢复图标数量、显示初值、整数分摊、尾数补齐及到达顺序（回收图标→计数→目标动画→可选数字更新→完成回调）。收集不重复发奖。修正上一阶段临时Mode整数参数：原元数据字段为callback，实际为Action；商店传null，末尾布尔控制addMoneyShow。金币/钻石显示等于库存时才减去本次奖励作为动画初值，保留原Int32.Parse异常。516项（战斗267+关外249）通过，Unity退出0。动画池、实际Tween/清理协程和资源连接仍待恢复，没有新Player构建。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyToolCollection','--result','pass','--evidence','516 integrated checks; source fly collection counts, label baseline, remainder and completion verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded516; full goal remains active.')
