from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==551 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type3157-'+str(i)+'.txt' for i in [24562,24567,24568,24569,24589,24619]]+['disassembly/Type3155-24626.txt','ads-callback-generics.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ads-video-flow';s['validation'].update(integratedChecksPassed=551,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ads-video-flow']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameAdsVideoFlow.cs','OutgameShopVideoBindings.cs'],'scope':'AdsManager video request/async wait/result-dispatch core restored and joined to original ShopUI test. Callback replacement occurs before four-second gate; platform result broadcasts precede callback. Actual SDK adapter, raw callback parser and Unity await runner remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='AdsManager video async and result-dispatch source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'AdsManager request gate, callback replacement, result ordering and original ShopUI chain','checksPassed':551,'outgameChecksPassed':284,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'freshPlayModeRun':False,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'ads_flow_core_verified_platform_adapter_pending','source':sources,'verified':['Current completion delegate cleared/replaced before request gate; gated request can replace prior callback','Manager unscaled four-second gate accepts equality, then awaits shared WaitForSecondsRealtime0.2','GF_ShowAdsVideo broadcasts with null payload before static platform call','Result dictionary<string,object> fields use ToString; only exact0 means success; present null throws','Successful optional video report precedes GF_AdsPlayCallBack with bool array, then current completion delegate','Failed result sets manager interval to current unscaled time; success retains existing deadline','afterVideo clears SDK playing flag before parsing; afterVideoFailed only logs','Original ShopUI plus original configuration now uses recovered ad flow between pointer and inventory reward'],'remaining':['Util.DataParse raw callback parser','Concrete DBTSDKManager platform adapter and readiness','Unity IEnumeratorAwait runtime runner and real PlayMode timing','Production account/menu/report owner and full persistence/build/E2E'],'checks':551,'priorPlaymodeChecks':8,'dynamicScope':'Original prefab/config and recovered ad flow with explicit wait/platform fixtures; previous fly PlayMode not rerun'}
write(o/'ADS_VIDEO_FLOW_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'AdsManager request/result core restored including delegate replacement before throttling and message-before-reward order. Shop integration uses recovered core; concrete SDK, raw parser, await runner and production account remain pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## 广告视频请求与结果分发（551项）\n提取AdsManager及嵌套类89方法，索引2278。恢复ShowVide替换当前回调→4秒unscaled请求门槛→共享0.2秒WaitForSecondsRealtime→GF_ShowAdsVideo→平台请求顺序。被门槛拒绝的请求仍替换回调。原结果字典仅ToString()==0成功；成功可选上报，失败将间隔设为当前时间，再广播GF_AdsPlayCallBack后调用当前委托；不清除回调、不去重。afterVideo先清SDK播放标记再解析，afterVideoFailed仅日志。原ShopUI加原配置的发奖验证已通过恢复后的广告核心。551项集成通过，Unity退出0；此前8项飞币PlayMode未重跑。原始字符串解析、Unity等待运行器、具体SDK/就绪逻辑和生产账号菜单仍待完成；平台和等待在本次测试中仍为显式fixture。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdsVideoFlow','--result','pass','--evidence','551 integrated checks; prior8 PlayMode checks not rerun. Concrete SDK/parser/await runner/account composition and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded551; full goal active.')
