from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==521
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-native-tween-runner';s['validation'].update(integratedChecksPassed=521,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-native-tween-runner']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type9962-68833.txt','disassembly/Type9962-68831.txt','disassembly/Type9962-68826.txt','disassembly/Type9962-68824.txt','disassembly/Type9871-68377.txt','disassembly/Type9974-68862.txt'],'implementation':['OutgameFlyTweenRunner.cs','OutgameFlyEasing.cs'],'scope':'Native forward one-loop move/scale subset for fly currency, independent advance, target pulse retained completion and id kill. Full DOTween equivalence and production host not claimed.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Native fly forward tween execution subset') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Native fly forward tween execution subset','checksPassed':521,'outgameChecksPassed':254,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'TweenManager.PlayForward completed tween sets isPlaying/isBackwards false and does not restart. Original DOTween .cctor defaultEaseType76=6 OutQuad. Native scoped runner verifies paused target pulse .2s to(1.2,1.2,0), return .2s to(1,1,0), independent movement and kill-complete callback once.','source':['disassembly/Type9962-68833.txt','disassembly/Type9871-68377.txt','disassembly/Type4057-31241.txt','disassembly/Type4055-31234.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'FLY_NATIVE_TWEEN_AUDIT.json';write(p,{'status':'native_forward_tween_subset_verified_composition_pending','checks':521,'source':['disassembly/Type9962-68833.txt','disassembly/Type9962-68831.txt','disassembly/Type9962-68826.txt','disassembly/Type9962-68824.txt','disassembly/Type9871-68377.txt','disassembly/Type9974-68862.txt'],'verified':['Real Transform OutCirc position at half/full duration using unscaled delta while scaled delta0','Target tween starts paused, completes without auto-kill and does not restart on subsequent PlayForward','Completion starts return-scale tween; global Target_Tween id kills retained pulse','Kill complete sets endpoint and invokes callback once','Original .cctor default ease6 restored as -t*(t-2)'],'limits':['Runner only exposes forward single-loop fly movement/scale, not complete DOTween API','Project-level DOTween settings overrides, global time scales, callback error/safe-mode logs and destroyed-target behavior not comprehensively matched','Pool scheduling, source random scatter and integrated concurrent effects pending','No player animation capture or matched visual verification']})
note='\n\n## 飞行动效原生逐帧执行子集（521项）\n新增OutgameFlyTweenRunner，真实Transform逐帧执行单次向前位置/缩放Tween，支持独立更新时间、暂停目标跳动和按ID停止/强制完成。源码确认已完成PlayForward不重启，目标放大保留不自动销毁，完成后另建缩小Tween；默认OutQuad来自原DOTween静态初始化。521项（战斗267+关外254）通过，Unity退出0，验证真实位置缓动、暂停时独立前进、目标完成不重启和强制完成仅一次回调。本实现仅覆盖所需向前单循环子集，不宣称完整DOTween等价；配置覆盖、安全模式细节、动画池/散点及完整页面组合与动态验收待继续。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyNativeTween','--result','pass','--evidence','521 integrated checks; native Transform movement, pulse and complete-kill verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded521; full goal remains active.')
