from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==399
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='commander-storage-lifecycle';s['validation'].update(integratedChecksPassed=399,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['commander-storage-lifecycle']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4028-31008.txt','disassembly/Type4028-31009.txt','disassembly/Type4028-31010.txt','disassembly/Type4028-31012.txt','disassembly/Type3465-26715.txt','disassembly/Type3465-26712.txt','disassembly/Type3465-26713.txt','disassembly/Type3465-26714.txt','disassembly/Type3466-26721.txt','disassembly/Type3606-27869.txt','disassembly/Type3467-26738.txt','disassembly/Type3467-26744.txt','disassembly/Type3467-26730.txt','disassembly/Type3467-26751.txt','data-manager-registration-roster.json','data-manager-registration-resolution.json','disassembly/Type3795-29619.txt','data-version-manager-resolution.json','data-manager-base-fields.json','disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json','original-sdk-storage.js','sdk-storage-source.json','storage-sdk-slot-candidates.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs','OutgameSdkStringStorage.cs','OutgameDataVersionStorage.cs','OutgameFileStorageBackend.cs','OutgameDataManagerPool.cs','OutgameManagerRegistrationCatalog.cs','OutgameDataManagerStorage.cs','OutgameCommanderManager.cs','OutgameOriginalCommanders.cs'],'scope':'Concrete commander manager uses source original record names and registered flags, requests real server callback when enabled, loads local otherwise, initializes missing configs and rebuilds save list from valid live manager records. Six original configs and isolated actual file restart verified through pool and SDK queue. Full manager roster, real login and production startup still incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Concrete commander manager original storage and restart lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Concrete commander manager original storage and restart lifecycle','checksPassed':399,'outgameChecksPassed':132,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Concrete OutgameCommanderManager implements source init/update callback/save lifecycle. Initial update requests server data only when allowServer, server mode and autoSyn; otherwise reads original local key. Empty callback creates default UsedCommanderId1 and fills configs with level0/skill1. Current original commander JSON codec preserves isNew/Id/curLevel/skillsData and UsedCommanderId, preserves held valid state and serializes live valid dictionary values at save. Original metadata registration flags and all6 source commander configs exercised through pool; actual isolated desktop file written and reloaded through a fresh manager. Server callback provider and full startup still incomplete.','source':['disassembly/Type4028-31008.txt','disassembly/Type4028-31009.txt','disassembly/Type4028-31010.txt','disassembly/Type4028-31012.txt','disassembly/Type3465-26715.txt'],'implementation':['OutgameCommanderManager.cs','OutgameOriginalCommanders.cs'],'validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Connect skin and local data managers to original serialization/storage without dropping source fields.','Complete remaining registered managers and required account providers.','Implement UserLogin reload/upload/download and complete startup to menu.'];write(p,audit)
note='\n\n## 统帅管理器原格式存档与实际文件重载（399项）\n新增OutgameCommanderManager实现注册接口，按原初始化分流到服务器请求或本地读取；空记录才恢复UsedCommanderId1等默认值并补配置，保存将有效字典值重建原commanderDatas列表。扩展OutgameOriginalCommanders当前格式读写，保留等级/技能/isNew/出战ID；无效配置记录在保存时不再输出。测试覆盖旧记录更新重载、服务器等待回调、非同步本地初始化；另用原6条统帅配置与ModelRegister标记，经Pool→SDK队列写入隔离实际文件，以全新管理器重载验证。399项（原267+关外132）通过，Unity退出0。未接完其他管理器或完整账号主界面闭环，目标仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameCommanderStorageLifecycle','--result','pass','--evidence','399 integrated checks; concrete commander lifecycle and actual isolated file restart verified; remaining managers and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded399; full goal remains active.')
