from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==459
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='serial-show-listener';s['validation'].update(integratedChecksPassed=459,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['serial-show-listener']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7527-54990.txt','disassembly/Type7527-54991.txt'],'implementation':['OutgameSerialControllerLifecycle.cs','OutgameAdShowFlow.cs'],'scope':'Serial OnShowAd/OnRealShowAd and concrete listener delegate binding restored; adapter state notifications now reach cache, business shown callback, banner/timer/shared state and preload host. Native adapter and production host still pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original serial shown event and notification listener binding') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original serial shown event and notification listener binding','checksPassed':459,'outgameChecksPassed':192,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Adapter slot11 resolves waitCloseReportShow metadata54721. Serial OnShowAd invokes business shown(true) first, rereads type, hides banner/timer1 except BANNER/NATIVE_SPLASH, BANNER timer2, interstitial reports only if !waitCloseReportShow, shared showing for INTERSTITAL or VIDEO, video preload last. OnRealShowAd reports delayed platform result for nonnull interstitial candidate with waitCloseReportShow. CreateListener now binds actual notifying adapter callbacks to serial lifecycle.459 checks pass; production host/native adapter incomplete.','source':['disassembly/Type7527-54990.txt','disassembly/Type7527-54991.txt'],'implementation':'OutgameSerialControllerLifecycle.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 展示成功监听器组合（459项）\n恢复Serial OnShowAd/OnRealShowAd，slot11确认为waitCloseReportShow。CreateListener将适配器通知连接到缓存、展示/关闭/奖励/失败处理。保持shown业务回调优先、类型重读、banner/timer、插屏上报、共享showing及视频预加载次序。459项（战斗267+关外192）通过，Unity退出0，已用真正的通知基类与监听器链验证；实际微信适配器、SDK与生产Host仍未接通，完整目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSerialShowListener','--result','pass','--evidence','459 integrated checks; notification-to-serial-listener chain, shown ordering and delayed platform reporting verified; production native wiring incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded459; full goal remains active.')
