from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');assert r['passed'] and len(r['checks'])==827
mm=read(O/'method-map.json');methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['cls'] in ['AudioControl','UIAudioManager'] or m['metadata'] in [26850,26864,26867,26870,26354]]
write(O/'AUDIO_CONTROL_SOURCE_EVIDENCE.json',dict(atUtc=now,sourceTypes=[3904,3431],methods=methods,sourceSwitch={'2':'Play(Parallel,[1001])','3':'StopAll','5':'Play(Parallel,[1002])','6':'existing parallel Pause(false)','7':'existing parallel Pause(true)','8,9':'StopParallelNode(Music=1)','10':'StopParallelNode(0)','other':'no operation'},limits=['Full AudioManager/native node/action construction is not implemented by this milestone. Extracted source classes provide next-step evidence; no placeholder playback implementation is bound.','UIAudioManager source static instance is represented by one host-owned OutgameUiAudioManagerSlot. Full application must share the slot. Source Destroy clears it without stopping retained nodes.','CLog stop diagnostic is routed through required host logger; source CLog filtering remains pending.']))
v=dict(atUtc=now,scope='AudioControl3904 lifecycle/state switch, source volume preferences/messages, UIAudioManager routing and isolated disk restart',checksPassed=827,newIntegratedChecks=16,nativePlayModeChecks=0,freshPlayModeRun=False,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly'],notClaimed='Native AudioManager/node/action/clip playback, audible audio, actual Main/account/platform composition or complete outgame Player build')
a=dict(atUtc=now,status='partial-subsystem',sourceEvidence='AUDIO_CONTROL_SOURCE_EVIDENCE.json',verification=v,findings=[
 'Actual AudioControl3904 factory now binds registry lifecycle and complete nine-method public surface. OnInit/Updata are verified empty; OnDispose clears current registry slot unconditionally. State switch follows exact source states2/3/5/6/7/8/9/10; other states are no-op. Existing BattleAudio is preserved and not substituted as the source audio manager.',
 'OutgameAudioSettings reads/writes original SoundGameVolume and MusicGameVolume through live OutgameUserPreferences with default1 and strict>.99 enable threshold. Sound boolean setter only writes. Music boolean setter writes via source AudioManager.SetMusicGameVolume contract and dispatches GlobalVolumeChange typed VoiceType/float after write. Invalid voice still sends event; raw floats remain unclamped. Callback failures retain committed preference.',
 'OutgameUiAudioManager initializes routes lazily, caches independent Parallel/Sequence/Single nodes, passes original ID array and returns node handles unchanged. Required factory can fail or return null following source behavior, and retry does not erase already assigned node. StopAll clears each slot only after successful Stop(0), later slots read live. Parallel Pause/StopByGUID do not create missing nodes. StopParallel logs before optional stop. Destroy only resets host-owned singleton slot, including from an old instance.',
 '827 integrated checks pass (16 new), including real isolated UserData.txt disk save/reopen with both audio settings and unrelated key retained. Node commands use explicit validator probes. No fresh native audio/PlayMode/build claimed. Lifecycle matrix now11/38 method-level implementations, remaining27, not eleven fully integrated business controllers.',
 'Disassembled UIAudioManager/AudioManager/GlobalData and node/action classes for next production dependency: AudioCompositeBase, AudioParallel, AudioSequence, AudioSingle, AudioActionBase, Once/Loop/Fade/LoopFade. Method map4969. Full AudioManager resource/update/action backend remains next; method extraction is not implementation.'
 ],remaining=['Restore AudioManager native root/listener/resource/config/node ownership, AudioCompositeBase/Parallel/Sequence/Single and source Once/Loop/Fade/LoopFade actions; connect required UI audio node factory and native playback validation.','Restore remaining27 controllers and complete real Main/module/config/account/menu entry, Level/Tower/Soldier/WayLine/AI/effects and remaining native assets. Complete every objective outgame subsystem, persistence/restart/failure/return and runnable Player acceptance.'],artifacts=dict(integratedLog='analysis/audio-control-integrated.log',isolatedPreferenceRoundtrip='analysis/audio-settings-restart/UserData.txt'),disassembledMethodMapCount=len(mm))
write(O/'AUDIO_CONTROL_AUDIT.json',a)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,audioControllerAudit='AUDIO_CONTROL_AUDIT.json',verification=v,remainingControllerCount=27);d['implementedControllerTypes']=list(dict.fromkeys(d['implementedControllerTypes']+[3904]));d['implementations']['3904']='OutgameAudioControl.cs';d['sourceMethods']=list(dict.fromkeys(d['sourceMethods']+list(range(30380,30389))));d['remaining'][0]=' '.join(a['remaining']);d['findings'].append('Audio3904 real lifecycle/settings/source state routing now bound; UIAudio routing restored with required native factory pending.827 integrated, no fresh audio native check;11/38 methods-level lifecycle implementations,27 remaining.');write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='audio-controller-settings-ui-routing',audioControllerAudit='generated/outgame/AUDIO_CONTROL_AUDIT.json',nextPriority=' '.join(a['remaining']));d['validation']['integratedChecksPassed']=827;d['validation']['audioController']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='audio-controller-settings-ui-routing'];d['milestones'].append(dict(id='audio-controller-settings-ui-routing',atUtc=now,status='partial-subsystem',integratedChecks=827,nativeChecks=0,remainingLifecycleControllers=27));write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=827,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 音频控制器、设置与UI路由增量\n- OutgameAudioControl3904实际registry绑定；9方法表面/生命周期复原，Init/Updata源码为空、Dispose清当前slot。状态2播parallel1001、3StopAll、5播1002、6/7仅已有parallel暂停false/true、8/9停Music1、10停0、其他无操作。未改已有BattleAudio。\n- OutgameAudioSettings直接复用live UserDataPrefs，原始SoundGameVolume/MusicGameVolume键、默认1、严格>.99；Sound开关只存，Music开关存后GlobalVolumeChange(typed VoiceType,float)。非法voice仍通知/不写、值不clamp、回调失败保留已写数据。\n- OutgameUiAudioManager路由lazy初始化，3种node独立lazy缓存；Play保留ID数组/返回GUID数组引用。StopAll按parallel/sequence/single顺序stop成功才清引用；日志失败先于Stop；Pause/GUID不建node；Destroy只清共享owner，旧实例仍可清新slot。\n- 827集成通过（新增16），含analysis/audio-settings-restart/UserData.txt真实隔离磁盘保存/重读，保留无关key。节点是验证probe，本批无原生音频/发声/PlayMode/Player构建主张。\n- 生命周期11/38方法级，余27；method-map4969。O/AUDIO_CONTROL_SOURCE_EVIDENCE.json、AUDIO_CONTROL_AUDIT.json；日志analysis/audio-control-integrated.log；本任务无待续进程。\n- 下一步AudioManager/native根节点/listener/资源/config、AudioCompositeBase与Parallel/Sequence/Single、AudioActionBase与Once/Loop/Fade/LoopFade后端，接上当前required node factory并验证原生音频。相关源码已抽取，尚未实现。之后剩余27控制器与真实Main/account/menu/全部关外范围、重启失败返回和可运行构建验收。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('811 项 checks','827 项 checks').replace('caseCount=811；latestValidation 为 shared InputManager/native route','caseCount=827；latestValidation 为 audio controller/settings/UI routing').replace('in_progress / shared-input-manager-native','in_progress / audio-controller-settings-ui-routing').replace('最新method-map4821；10控制器生命周期/共享绑定已实现并验证，剩28','最新method-map4969；11控制器生命周期/共享绑定已实现并验证，剩27').replace('最新集成日志 analysis/input-manager-integrated-final.log；输入原生日志 analysis/input-manager-native-final.log。811集成+10 InputManager原生通过；','最新集成日志 analysis/audio-control-integrated.log。827集成通过，本批未跑原生音频；历史输入原生日志 analysis/input-manager-native-final.log，10 InputManager原生通过；');p.write_text(s+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameAudioControllerRouting','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/AUDIO_CONTROL_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=827,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm),controllerLifecycles=11,remaining=27)))
