from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==426
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-request-controller-routing';s['validation'].update(integratedChecksPassed=426,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-request-controller-routing']={'implementationReady': True, 'productionConnected': False, 'source': ['disassembly/Type7544-55102.txt', 'disassembly/Type7544-55103.txt', 'disassembly/Type7544-55075.txt', 'ad-controller-slots.json'], 'implementation': ['OutgameAdRequestRouter.cs'], 'scope': 'NewAdsManager controller request routing and platform close-repair restored. Remaining interstitial blocks via closed(false); absent controller fails via shown(false); option stored before controller show, no extra readiness guard. Concrete controllers, module activation and business reward linkage remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original NewAdsManager request/controller routing') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original NewAdsManager request/controller routing','checksPassed':426,'outgameChecksPassed':159,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact': 'NewAdsManager showVideo calls fixNoClose before platform checks. Xiaomi/weixin repair when InterVideoShowing closes video then interstitial controllers; alipay/zijie only closes interstitial in later branch. State is reread after callbacks. Remaining InterVideoShowing calls closed(false), missing video calls shown(false), valid video receives source bool at offset20 then virtual slot8 show. BaseController slot6 resolves close. isVideoReady returns false for missing controller otherwise delegates readiness. Concrete controller and native advertising integration still pending. WXFunctionManger CheckFunctionActive warns then rereads module flag8; this entry gate extracted but not yet implemented.', 'source': ['disassembly/Type7544-55102.txt', 'disassembly/Type7544-55103.txt', 'disassembly/Type7544-55075.txt', 'ad-controller-slots.json'], 'implementation': 'OutgameAdRequestRouter.cs', 'validation': 'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 底层广告控制器请求分流（426项）\n新增OutgameAdRequestRouter恢复NewAdsManager：微信/小米遇遗留插屏状态先关闭视频再关闭插屏，支付宝/字节分支仅关闭插屏；关闭回调后重读状态。插屏仍显示调用closed(false)，控制器缺失调用shown(false)，有效控制器先写原offset20选项再Show，不添加准备状态门控。验证平台分支、关闭顺序与回调改变状态、缺控制器/阻塞分流及显式Ready调用；426项（原267+关外159）通过，Unity退出0；源方法1504。实际控制器/模块启用与完整领奖仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdRequestControllerRouting','--result','pass','--evidence','426 integrated checks; source NewAdsManager platform repair and controller callback routing verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded426; full goal remains active.')
