from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==463
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='wx-video-presentation';s['validation'].update(integratedChecksPassed=463,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['wx-video-presentation']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type9186-64361.txt','disassembly/Type9186-64362.txt','disassembly/Type9186-64366.txt','disassembly/Type9186-64367.txt','wx-build-setting-fields.json'],'implementation':['OutgameWxVideoPresentation.cs'],'scope':'Native display/close callback flow connects loading handle and state notifications, preserves null/partial/completed outcomes, count/reward/report order and late shown behavior. Prediction response implementation and actual SDK handle pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original Wx video native show and close callback lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original Wx video native show and close callback lifecycle','checksPassed':463,'outgameChecksPassed':196,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Wx native display/close flow now connected to loading handle and notifying adapter. Close sets isClosed, unregisters current native close listener, clears autoload, then rewards/counts/prediction request before notifyClose. Null close increments total only; partial plugin close reports show; ended reward notification precedes success count. Late show avoids notifyShow but still AMS event. Empty failure text logs only.463 checks pass; live handle/prediction response/reporting host pending.','source':['disassembly/Type9186-64361.txt','disassembly/Type9186-64362.txt','disassembly/Type9186-64366.txt','disassembly/Type9186-64367.txt'],'implementation':'OutgameWxVideoPresentation.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 微信视频展示/关闭原生回调（463项）\n新增OutgameWxVideoPresentation，将加载原生句柄与状态通知连接。关闭先isClosed/OffClose/清autoload，再按结果奖励、计数、请求预测，最后通知close；空结果只计总次数，提前关闭按MiniGameCommonPlugin分支报告。保留迟到shown仍报AMS、空ShowFail消息只日志、非空错误转通知。463项（战斗267+关外196）通过，Unity退出0。预测响应处理、真实SDK句柄和生产Host仍待完成，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameWxVideoPresentation','--result','pass','--evidence','463 integrated checks; Wx show/close callback ordering, null/partial outcomes and late callbacks verified; actual SDK/prediction host pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded463; full goal remains active.')
