from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==525 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['normal-pool-generic-bodies.json']+['disassembly/PoolGeneric-'+str(i)+'.txt' for i in range(28724,28732)]
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='pooled-object-use-count';s['validation'].update(integratedChecksPassed=525,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['pooled-object-use-count']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgamePoolEntry.cs'],'scope':'Source Object<T> wrapper, including negative counts and timestamp/lifecycle ordering. Integrated into actual fly Play Mode fixture. Pool-level reuse, expiry and original loading provider pending. Exception class differs from GameFrameworkException.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Object<T> shared source wrapper') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original pooled object count/lifecycle wrapper','checksPassed':525,'outgameChecksPassed':258,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'wrapper_verified_pool_methods_extracted','source':sources,'extraction':{'script':'analysis/extract_normal_pool_generics.py','methodCount':23,'genericPointersAddress':2623360,'pointerCount':6294,'methodTableAddress':382304,'specTableAddress':483008,'validation':'All generic pointer entries resolve to an original wasm table entry or zero'},'verified':['Constructor stores initial count0/1 and calls OnSpawn only when spawned, without updating time','Spawn increments unchecked Int32, updates DateTime.Now, then calls OnSpawn','Unspawn calls OnUnspawn, updates DateTime.Now, then decrements unchecked Int32','IsInUse is count>0; duplicate return may make count negative','Release forwards without counter reset'],'remaining':['Decode concrete list/generic context for pool collection and first-match selection','Implement pool capacity, expiration filter, update and shutdown','Connect NormalPool original loading and resource release providers','Integrate production page/account flows'],'knownDifferences':['InvalidOperationException used instead of original GameFrameworkException'],'checks':525,'playmodeChecks':8}
write(o/'NORMAL_POOL_ENTRY_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Resolved23 original generic object/pool methods via metadata method specs and code registration. Restored Object<T> count/timestamp/lifecycle wrapper, used by actual fly Play Mode fixture. Full NormalPool still incomplete.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## 原底层池泛型方法与占用计数（525项 + 独立8项动态检查）\n新增extract_normal_pool_generics.py，从静态registration解析23个Object<T>/ObjectPool<T>共享方法，验证6294个函数指针。OutgamePoolEntry恢复初始0/1占用计数、取用先增计数再更新时间并调用OnSpawn、回收先OnUnspawn再更新时间并减计数、IsInUse=count>0以及原版重复回收负数行为。实际飞币Play Mode夹具接入此对象包装；525项集成检查和8项动态检查通过，两次Unity退出0。异常类型差异保留记录。下步解析池容器与泛型上下文，落实取用选择、容量/到期和真实资源加载；账号/页面生产流程、完整构建验收仍未完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgamePooledObjectUseCount','--result','pass','--evidence','525 integrated checks and8 independent actual Play Mode checks; complete pool and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded525; full goal active.')
