from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==435
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-price-policy';s['validation'].update(integratedChecksPassed=435,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-price-policy']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7511-54852.txt','disassembly/Type7488-54701.txt','ad-price-fields-and-request-slot.json'],'implementation':['OutgameAdCacheSelection.cs','OutgameAdPriceCache.cs'],'scope':'Default cache selector now uses original zero-only price validity and logging order. Adapter price cache restores original key/date/zero retry semantics. Concrete Utils_PlayerPrefs storage and native adapter wiring remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original price validity and adapter price cache') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original price validity and adapter price cache','checksPassed':435,'outgameChecksPassed':168,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'allPlatHasPrice appends platformId and getRealPrice to log text, reads getRealPrice again and rejects only zero. Logs prefix through failing item, or all entries on success; empty accepts. getRealPrice caches nonzero values; zero reads Utils_PlayerPrefs.GetInt(realPrice+adz.zkey+platformId+[local yyyy-MM-dd when flag==1],0), preserving repeat reads and no spontaneous nonzero invalidation at midnight. Slot9 resolves isHighPriority for upcoming request queue restoration. 435 integrated checks pass.','source':['disassembly/Type7511-54852.txt','disassembly/Type7488-54701.txt','ad-price-fields-and-request-slot.json'],'implementation':['OutgameAdCacheSelection.cs','OutgameAdPriceCache.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 广告价格校验与本地价格缓存（435项）\n默认缓存选择现已使用原始allPlatHasPrice规则：日志拼接后再次读价格，只拒绝0，负数有效，失败只记录已遍历项。新增OutgameAdPriceCache，按realPrice+zkey+platformId拼键，开关恰为1时追加本地日期；0反复读取，非0跨日期仍留在内存，显式清零后才重读。435项（战斗267+关外168）通过，Unity退出0。明确Utils_PlayerPrefs不是账户UserData，实际存储桥与原生适配器仍待接线。已解析虚槽9为isHighPriority，下一步恢复双遍请求队列。完整关外目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdPricePolicy','--result','pass','--evidence','435 integrated checks; source zero-only price check, repeated reads, key format and cached date behavior verified; complete controller and goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded435; full goal remains active.')
