from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/time-countdown-native-validation.json');assert r['passed'] and len(r['checks'])==913;assert n['passed'] and len(n['checks'])==15
mm=read(O/'method-map.json');ids=set(range(27270,27285))|{27253,27255,27256,27257,27258,27293,27310,27311};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
s=dict(atUtc=now,methods=methods,metadataEvidence='TIME_MODULE_METADATA.json',criticalEvidence=[
 'Static3534 fields now/startTime/isInit/timeDifference/defaultTime/IsFocus; cctor27293 defaultTime DateTime(1970,1,1,8,0,0), difference0, focus true. Initialize27253 sets startTime=defaultTime. GetTime27270/GetNowTime27271 compute local DateTime subtraction TotalMilliseconds plus difference. GetNowTimeInt27272/Long27273 use seconds and ignore difference; exported overflow conversions return signed minimum.',
 'Source Initialize replaces complete/second/minute/millisecond/deadline dictionaries; resets lastTime16,lastMinute32,timeId40 but not lastMillisecond24 or unityRealTime48. ClearTimer27258 clears these same maps then resets selected fields; full method also clears loop/Unity maps outside this countdown component.',
 'AddCoundDown227275: null complete returns-1 before any mutation; unchecked ++id, completeHandles.Add, GetNowTime()+duration, completeTimes.Add, optional everyMillisecond.Add(id,new Every(callback,interval1)). Wrapper27283 delegates exactly. Remove27276 removes in order complete/deadline/second/minute/millisecond, then observes count of complete/second/minute. RemoveTime27284 delegates.',
 'Check27277 captures GetTime date once then runs complete -> second -> millisecond -> minute. CheckTime27282 writes float realtime as double before checking. Source Update27255 supplies DateTime.Now and Unity realtime, then also invokes loop and Unity timer branches not yet implemented here.',
 'CheckComplete27278 snapshots parallel key/callback lists from dictionary enumeration, creates shared instance removeList88. Iterates captured callbacks but consults live deadlines; at deadline<=now invokes first, then adds id to current instance removeList. Cleanup only after entire callback loop; thrown callback skips remaining calls and cleanup, so previously completed callbacks may replay. Callback removes later deadline => skip; replacement of callback does not replace snapshot. Added entries absent from current complete snapshot.',
 'CheckSecond27279 threshold now-last>=1000, Millisecond27280 now>last; both update last after successful pass even if their maps empty. Minute27281 requires now-last>=60000 AND nonempty map before writing last. Every passes snapshot objects even if removed from live map; missing deadline yields remaining0. Last timestamp is reread per callback; earlier callback/reentry can change elapsed for later entries.',
 'Remaining is WASM int conversion of deadline-now BEFORE /1000 or /60000 integer division; oversized/NaN values map int.MinValue. Elapsed double delta demoted float before unit division. Every3537.Call27310 adds float elapsed, once if interval<=accum invokes callback then resets0; no catch-up loop or remainder retention. Throw leaves accumulator and outer last timestamp unchanged.',
 'Countdown methods have no focus/pause gate. GameFocus27257 only writes static focus; GamePause27256 touches loop timer dictionary76 when event bool true. Complete module event subscription and loop-specific pause behavior are not implemented by this countdown component.'
 ],limits=['OutgameTimeCountdowns is the source countdown projection, not a replacement for the full TimeModule startup module. LoopTimers, Unity timers, event subscriptions and complete module lifecycle still pending.','Native validation uses real source DateTime countdown and actual AudioSource; fixture remains for full resource and shared update ownership. No device recording, full Main entry or Player build claim.'])
write(O/'TIME_COUNTDOWN_SOURCE_EVIDENCE.json',s)
v=dict(atUtc=now,scope='Source TimeModule clock/countdown component bound to production audio fade; real local DateTime in native PlayMode',checksPassed=913,newIntegratedChecks=20,nativePlayModeChecks=15,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameTimeCountdownPlayModeValidation.Run'],notClaimed='Complete TimeModule loop/Unity timers or event lifecycle; full UpdateManager/resource/AudioManager host and full outgame Player')
a=dict(atUtc=now,status='partial-subsystem',sourceEvidence='TIME_COUNTDOWN_SOURCE_EVIDENCE.json',verification=v,findings=[
 'OutgameTimeClock restores shared localDateTime/default08:00epoch/difference and milliseconds vs seconds conversion; OutgameTimeEvery source accumulator; OutgameTimeCountdowns implements initialization/registration/removal/complete and second/millisecond/minute passes/clear of countdown portion and audio delegate binding.',
 'Source deferred cleanup, snapshot callbacks and live deadlines, same-frame addition reaching later every pass, cancellation semantics, float accumulation, exact equality, time rewind and overflow behavior retained. No substitute deltaTime or automatic pause/catch-up behavior.',
 '913 integrated checks pass,20 new. Initial test incorrectly assumed ID order after Dictionary free-slot reuse; fixed test isolation with fresh source initialization, left production dictionary enumeration unchanged. Final log time-countdown-integrated-final.log is authoritative; initial log records that single test failure.',
 '15 native PlayMode checks pass: actual source countdown registration/removal delegates replace earlier synthetic countdown driver, DateTime.Now drives recovered1001 loop-fade and2001 one-shot fade through AudioControl/UI/Parallel/type factory. Native cursor/pause/resume/fractional volume/fade completion/end/release/destruction verified; focus=false does not gate countdown.',
 'TimeModule is still incomplete: loop/Unity timers and lifecycle/events remain. Countdown component is not substituted as a fake full startup module. Remaining audio resource/update/AudioManager host is explicit. Controller lifecycle count11/38,27 remaining. Method map4993 after extracting helper types3535/3536/3537.'
 ],remaining=['Continue source TimeModule3534 loop/Unity timers and helpers3535/3536, lifecycle/start/pause/focus/shutdown, preserving full source ordering; then shared UpdateManager and AudioManager/config/root/listener/node/resources composition.','Continue remaining27 business controller lifecycles and full Main/account/module/menu graph; all original scope, restart/failure/return and runnable Player acceptance remain required.'],artifacts=dict(integratedLog='analysis/time-countdown-integrated-final.log',initialTestFailureLog='analysis/time-countdown-integrated.log',nativeLog='analysis/time-countdown-native.log',nativeReport='analysis/time-countdown-native-validation.json'),disassembledMethodMapCount=len(mm))
write(O/'TIME_COUNTDOWN_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='time-countdowns-native-audio',timeCountdownAudit='generated/outgame/TIME_COUNTDOWN_AUDIT.json',nextPriority=' '.join(a['remaining']));d['validation']['integratedChecksPassed']=913;d['validation']['timeCountdownNativeAudio']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='time-countdowns-native-audio'];d['milestones'].append(dict(id='time-countdowns-native-audio',atUtc=now,status='partial-subsystem',integratedChecks=913,nativeChecks=15,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,timeCountdownAudit='TIME_COUNTDOWN_AUDIT.json');d['remaining'][0]=' '.join(a['remaining']);d['findings'].append('Source DateTime/countdown component now drives actual native audio:913 integrated and15 native pass. Full TimeModule loop/Unity/lifecycle and shared update/resource/audio ownership pending; count11/38 unchanged.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=913,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 源码倒计时驱动音频增量\n- OutgameTimeCountdowns.cs含OutgameTimeClock（shared本地DateTime、1970-01-01 08:00 epoch、毫秒加TimeDifference/整数秒不加）、OutgameTimeEvery（float累积>=interval最多调用一次，成功后归零）、OutgameTimeCountdowns（TimeModule倒计时部分）。未冒充完整startup TimeModule，loop/Unity计时与事件lifecycle仍待实现。\n- Add要求complete非null否则-1，unchecked++ID/complete.Add先于clock/deadline.Add，每毫秒句柄interval1。Complete快照keys+callbacks，live查deadline<=now；先callback后写当前实例RemoveList，所有callback完毕才统一Remove。回调抛出导致前面已完成timer仍在下次重播；替换callback不替换快照，删除deadline会跳过待完成callback。\n- Check顺序complete/second/ms/minute；later every pass可看到complete回调新注册timer。Every快照对象即便被其他callback从live字典删除也继续调用（缺deadline剩余0）；每次call重新读取Last字段，保留重入影响。remaining先double→int(WASM溢出int.MinValue)再整数除单位，elapsed先float再除单位。\n- second>=1000、ms严格>，空字典仍推进Last；minute>=60000且字典非空才推进Last。Initialize/Clear重置LastTime/LastMinute/TimeId，保留LastMillisecond/UnityRealTime。没有focus/pause gate；源码GamePause只触及loopTimers，完整事件所有权待接。\n- BindAudio连接实际源倒计时到四种音频服务。913集成通过（新增20），初次1个测试因误判Dictionary复用空槽遍历顺序失败，修测试隔离后通过；最终analysis/time-countdown-integrated-final.log。15新原生通过，time-countdown-native-validation.json / time-countdown-native.log：真实DateTime.Now与源码countdown驱动1001/2001原生音频链，替换前次计时driver；loader/shared update仍fixture，无设备录音/完整Main/Player新build。\n- O/TIME_COUNTDOWN_SOURCE_EVIDENCE.json、TIME_COUNTDOWN_AUDIT.json、TIME_MODULE_METADATA.json（3534/3535/3536/3537字段和泛型method解析）。状态time-countdowns-native-audio；913/4993/11/27，无本任务待续进程。\n- 下一步完整TimeModule3534：27252priority60、27253init、27254Start监听GF_NewGamePause/GF_GameFocus、27255Update(本地DateTime.CheckTime→CheckLoopTimer→CheckUnityTimer)、27256GamePause、27257Focus、27258Clear、27259..27269 loop、27285..27290 Unity、27291Shutdown移监听/Clear/flagfalse。新抽helper3535/27298..27306、3536/27307..27309、3537/27310..27311，methodmap4993。GamePausetrue枚举loopTimers.Values调用helper.GamePause，false不操作；其他原始细节继续核对，不能以通用Unitytimer代替。\n- Countdown component初始化/清理是完整Initialize/Clear的字段投影，未来整合要保留源所有字段重建/清理顺序与callback时机。TimeClock.IsInit static与模块Initialized flag是两个不同字段，不要混同。analysis/audio_disassembly_slice.py已修复忽略混淆类名NEL拆行，支持Time源码br target。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('893 项 checks','913 项 checks').replace('caseCount=893；latestValidation 为 audio fade/factory native','caseCount=913；latestValidation 为 source time countdown/native audio').replace('in_progress / audio-fade-actions-factory-native','in_progress / time-countdowns-native-audio').replace('最新集成日志 analysis/audio-fade-integrated.log。893集成、13原生音频链通过（timer/loader/update为fixture）；','最新集成日志 analysis/time-countdown-integrated-final.log。913集成、15原生源码计时/音频链通过（loader/update为fixture，timer为实际源码实现）；').replace('最新method-map4979；','最新method-map4993；');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameTimeCountdownNativeAudio','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/TIME_COUNTDOWN_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=913,nativeChecks=15,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
