from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==419
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='wx-preferences-platform-branch';s['validation'].update(integratedChecksPassed=419,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['wx-preferences-platform-branch']={'implementationReady': True, 'productionConnected': False, 'source': ['platform-prefs-hierarchy.json', 'sdk-day-initialization-slots.json', 'disassembly/Type3146-24165.txt', 'disassembly/Type7581-55502.txt', 'disassembly/Type7703-56242.txt'], 'implementation': ['OutgameWxPreferenceSession.cs'], 'scope': 'Exact XYXCommon_DBT_ISDK + Bridge_WX_XYXFunction preference composition: inherited GetDaysByFirstLaunch=0 and CanReadLocalData=true. Original managed preferences, recovered file/SDK queue and day event integrated. Full application selected-platform initialization, account login and remaining daily systems not completed.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original concrete WX preference ownership and inherited day behavior') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original concrete WX preference ownership and inherited day behavior','checksPassed':419,'outgameChecksPassed':152,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact': 'Metadata inheritance XYXCommon_DBT_ISDK type7703 -> ISDK3146 shows no override for slot203; ISDK.GetDaysByFirstLaunch f972 returns0. Bridge_WX_XYXFunction9254 -> IXYXFunction7581 shows no override for slot54; IXYXFunction.CanReadLocalData f1048 returns true. Thus this exact WX branch uses managed UserDataPrefs initialization and constant zero SDK day, not DateTime calendar progression. OutgameWxPreferenceSession composes recovered prefs/file/SDK/new-day behavior without inventing clock semantics. Test loads legacy Day12, emits(0,12) once without saving, persists explicitly and fresh session emits nothing. Scope is these recovered platform classes; complete app activation/login/daily consumers remain incomplete.', 'source': ['platform-prefs-hierarchy.json', 'disassembly/Type3146-24165.txt', 'disassembly/Type7581-55502.txt'], 'implementation': 'OutgameWxPreferenceSession.cs', 'validation': 'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 微信平台偏好初始化与天数继承分支（419项）\n完整继承链证实XYXCommon_DBT_ISDK直接继承ISDK的GetDaysByFirstLaunch=0，Bridge_WX_XYXFunction继承IXYXFunction.CanReadLocalData=true。新增OutgameWxPreferenceSession将此实际分支接入原偏好存档/文件键/SDK队列/跨日事件，不擅自引入自然日计时。验证旧Day12更新为0并发(0,12)，重复检查不重发，显式保存后新实例不重发；419项（原267+关外152）通过，Unity退出0，源方法1302。完整应用平台激活与登录、其他每日系统仍待接通。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameWxPreferencesPlatformBranch','--result','pass','--evidence','419 integrated checks; source concrete WX managed initialization and inherited zero-day behavior verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded419; full goal remains active.')
