from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==479
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='serial-controller-configuration';s['validation'].update(integratedChecksPassed=479,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['serial-controller-configuration']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7511-54833.txt','disassembly/Type7527-54985.txt','disassembly/Type7511-54865.txt'],'implementation':['OutgameSerialAdConfiguration.cs','OutgameAdPlatformList.cs','OutgameAdShowFlow.cs','OutgameAdConfiguration.cs'],'scope':'Source setAdz binding, retained configuration, shared platform list, cache clamp and tag order; repeated empty-list reads and reentrant list replacement preserved. Concrete production service composition and full configuration acquisition pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original serial controller configuration and shared platform-list binding') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original serial controller configuration and shared platform-list binding','checksPassed':479,'outgameChecksPassed':212,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Serial configuration binding now performs base TAG/config/getPlatList/cache clamp first, then serial TAG replacement. Shared mutable list used by source getPlatList and show flow; callback replacement is reread before append. Empty creation retries on each getter; zero count does not clamp; rebinding nonempty list preserves adapters and their original config.479 integrated checks pass.','source':['disassembly/Type7511-54833.txt','disassembly/Type7527-54985.txt','disassembly/Type7511-54865.txt'],'implementation':['OutgameSerialAdConfiguration.cs','OutgameAdPlatformList.cs','OutgameAdShowFlow.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'VIDEO_CONTROLLER_INITIALIZATION_AUDIT.json';audit=read(p);audit['setAdzUpdate']={'implemented':True,'implementation':'OutgameSerialAdConfiguration.cs','checks':479,'productionConnected':False,'scope':'Source binding, clamp, prefix and shared list identity. Runtime acquisition and service composition pending.'};write(p,audit)
note='\n\n## 串行控制器配置绑定与共享平台列表（479项）\n新增OutgameSerialAdConfiguration执行原始base setAdz后serial setAdz顺序：base标签、保留配置、初始化平台列表、仅非零数量时下调缓存上限，最后替换serial标签。show流程和惰性创建器共用同一可替换列表；工厂重入替换列表时追加到当前字段。保留空列表重复创建、非空列表重绑定不重建、配置失败后的中间状态，并让广告类型读取当前配置引用。479项（战斗267+关外212）通过，Unity退出0。真实生产服务组合、完整配置获取与全关外入口仍待完成，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSerialControllerConfiguration','--result','pass','--evidence','479 integrated checks; source setAdz ordering, cache clamp, retained config and shared/reentrant platform list verified; production composition pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded479; full goal remains active.')
