from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/entity-pool-native-validation.json');assert r['passed'] and len(r['checks'])==729;assert n['passed'] and len(n['checks'])==13 and n['requests']==5
v={'atUtc':now,'scope':'LoadPrefabControl entity acquisition/template preparation/shared preload queues, native bundle pool reuse/deferred destruction','checksPassed':729,'nativePlayModeChecks':13,'nativeRequests':5,'freshPlayModeRun':True,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Concrete LevelControl/PlayerControl/loading-page preload host, remaining30 controller lifecycles, Main/account/full outgame Player or original remote services','commands':['BattleBuild.ValidateMechanicsOnly','OutgameEntityPoolPlayModeValidation.Run']}
a={'atUtc':now,'status':'source-branches-implemented-host-composition-pending','sourceEvidence':'PREFAB_LOADER_SOURCE_EVIDENCE.json','productionFiles':['OutgameLoadPrefabControl.cs','OutgameCoreControllerBindings.cs','OutgamePrefabCache.cs'],'verification':v,'findings':[
 'EntityRoot corrected from Transform to original GameObject field type16505 -> Type6826. Per-id roots are parented with worldPositionStays=true and then positioned at world zero; existing null roots are not replaced.',
 'GetEntity/GetEntityNow reuse by activeSelf; newly instantiated entities enter cache before root lookup/parent/name and activation. Name is config AssetName + underscore + child count, verified by ExtesionMethod cctor/signEnumToStr/IntToString.',
 'Destroyed-entry removal still increments index, so shifted idle object is skipped for that request. GetEntityNow misses return null after scheduling only template loading.',
 'PrepareEntity warms native templates without creating instances. Entity template loader Adds only absent keys, unlike LoadAsset replacement; successful reload of present null cache calls back but leaves cache null.',
 'Source31577 success resets only a local variable. Failure writes the unchanged count then requeues when count<=3; default count0 can retry indefinitely. No invented retry cap/increment added. Bounded test verifies repeated pending work then seeds count4 to exercise terminal log/no callback.',
 'PrepareStart cancels next background preload, resets shared cursor, rebuilds shared list and prepares serially. Each success increments cursor, resets loading UI float44 and continues; UI failure preserves advanced cursor. PreLoad sets gate true, leaves cursor unchanged, advances callback-local index, and checks gate before next item.',
 'Preload list is fixed1,10,11,12,13,14,15,101,9033,9034 then positive unique player skin/random skin per star, boss821, obstacle EnityID. Repeated source LevelControl getter reads retained. Generic instantiation table72592 independently verified against Level/Player/UI parent contexts.',
 'Native PlayMode proves cold template preparation, native pool naming/parent/activeSelf reuse and deferred9033 root/child destruction; original entity11001 and main EntityRoot survive selective clear. Uses rebuilt original native assets with local file patch URLs.',
 'New native harness initial launch occurred before its file was saved due generator assertion; preserved entity-pool-native-missing-harness.log. Fixed harness generator and ran successfully; no production change required.'
 ],'remaining':['Supply IOutgamePrefabPreloadHost from actual LevelControl4107, PlayerControl4462 and loading page in production composition. Current optional dependency is not a noop fallback; calling preload without it fails.','Finish remaining30 controller lifecycles and all pending Main/account/UI/service graph; complete full outgame persistence/restart/failure/Player acceptance.'],'sourceMethods':52,'resolvedGenericUsages':19,'disassembledMethodMapCount':4565}
write(O/'ENTITY_PRELOAD_AUDIT.json',a)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d['atUtc']=now;d['entityPreloadAudit']='ENTITY_PRELOAD_AUDIT.json';d['verification']=v;d['remaining'][0]='Bind concrete Level/Player/loading-page preload dependencies and restore remaining30 lifecycle controllers; complete Main/UI/game service graph.';write(p,d)
p=O/'PREFAB_LOADER_NATIVE_AUDIT.json';d=read(p);d['entityPreloadFollowup']='ENTITY_PRELOAD_AUDIT.json';d['remaining'][0]='Entity/preload source branches now implemented and verified by ENTITY_PRELOAD_AUDIT.json; concrete Level/Player/loading-page host composition remains pending.';write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='entity-preload-source-and-native-pool',entityPreloadAudit='generated/outgame/ENTITY_PRELOAD_AUDIT.json',nextPriority='Recover LevelControl4107 and PlayerControl4462 using existing source-backed business helpers; bind IOutgamePrefabPreloadHost and original loading page. Remaining30 lifecycles. Complete Main/account/menu graph and full outgame/persistence/Player acceptance.')
d['validation']['integratedChecksPassed']=729;d['validation']['entityPreload']=v;d['validation']['entityPoolNative']=n;d['milestones']=[m for m in d['milestones'] if m['id']!='entity-preload-source-and-native-pool'];d['milestones'].append({'id':'entity-preload-source-and-native-pool','atUtc':now,'status':'partial-subsystem','integratedChecks':729,'nativeChecks':13,'remainingControllers':30});write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=729,latestValidation=v);d['validationHistory'].append(v)
if 'analysis/entity-pool-native-validation.json' not in d['reports']:d['reports'].append('analysis/entity-pool-native-validation.json')
files=[p for p in (W/'UnityProject/Assets/AreaBattle').rglob('*') if p.is_file() and (p.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas') or '/FirstPack/' in p.as_posix())];d['sourceFingerprints']=[{'path':p.relative_to(W).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 实体池与预加载增量\n- LoadPrefabControl4117实体获取/同步获取/模板准备/根节点/PrepareStart/PreLoad及嵌套回调已按源实现。EntityRoot纠正为GameObject，实体命名、activeSelf复用、移除销毁项后跳项、模板空缓存不替换、同步miss返回null均有测试。\n- 保留原作异常：失败计数不递增、成功只清局部；默认0可持续重试。有限轮黄金用例验证，无虚构重试上限或成功回调。\n- 预加载固定10id→士兵皮肤/随机皮肤→Boss821→障碍物EnityID；PrepareStart共享计数与加载页reset、PreLoad局部索引与CanLoadNext。具体LevelControl/PlayerControl/加载页host仍需接线。\n- 729集成+13原生PlayMode通过；原生仍5个本地file请求，验证真实AssetBundle预缓存/复用/帧末销毁。Native test原始生成脚本assert导致缺失harness的一次启动日志已保留。\n- O/ENTITY_PRELOAD_AUDIT.json / PREFAB_LOADER_SOURCE_EVIDENCE.json（52方法/19usage）；method-map4565。日志analysis/entity-preload-integrated.log、entity-pool-native.log。生命周期仍8/38，剩30，不新增完整Player声明。\n- 下一步Level4107/Player4462与加载页，绑定IOutgamePrefabPreloadHost，再完整Main/account/menu/全部关外验收。无待续进程。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('718 项 checks','729 项 checks').replace('caseCount=718；latestValidation 为 LoadPrefabControl + native resource graph','caseCount=729；latestValidation 为 LoadPrefabControl entity/preload + native pool').replace('最新method-map4560','最新method-map4565').replace('in_progress / controller-lifecycle-production-binding','in_progress / entity-preload-source-and-native-pool').replace('最新集成日志 analysis/prefab-loader-integrated.log；资源链原生日志 analysis/prefab-loader-native.log。718集成+8资源链原生通过；历史Game/UI/基础控制器原生分别7/6/10项通过。无本任务待续进程。','最新集成日志 analysis/entity-preload-integrated.log；实体池原生日志 analysis/entity-pool-native.log。729集成+13实体池原生通过；历史资源链/Game/UI/基础控制器原生分别8/7/6/10项通过。无本任务待续进程。');s+=text;p.write_text(s,encoding='utf8')
print(json.dumps({'checks':729,'native':13,'requests':5,'fingerprints':len(files),'remainingControllers':30}))
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 r=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert r.returncode==0,r.stderr
r=subprocess.run(base+['set-check']+common+['--name','outgameEntityPreloadNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/ENTITY_PRELOAD_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert r.returncode==0,r.stderr
print('Orchestration evidence recorded')
