from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==389
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='manager-version-reconciliation';s['validation'].update(integratedChecksPassed=389,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Resolve and implement GameDataVersionMgr reload/upload/download branches and inherited login failure handling.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['manager-version-reconciliation']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type3795-29619.txt','data-version-manager-resolution.json','data-manager-base-fields.json','disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json','original-sdk-storage.js','sdk-storage-source.json','storage-sdk-slot-candidates.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs','OutgameSdkStringStorage.cs','OutgameDataVersionStorage.cs','OutgameFileStorageBackend.cs'],'scope':'Source f12180 enumerates participating manager keys, adds missing version -1, preserves existing rows, prunes stale or disabled keys through a snapshot of Local.Keys and saves once even unchanged. LoadManagers connects this to source version loading. Concrete registry and live SDK remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Source manager version reconciliation after local record loading') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Source manager version reconciliation after local record loading','checksPassed':389,'outgameChecksPassed':122,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'GameDataVersionMgr f12180 adds missing synchronized manager keys with version -1, retains existing records, snapshots Local.Keys and removes keys without a participating manager, then saves exactly once even if unchanged. DataManagerBase offset9 is the participation flag and slot4 is get_DataKey. Added LoadManagers integration; concrete production manager registry remains pending.','source':['disassembly/Type3795-29619.txt','data-version-manager-resolution.json','data-manager-base-fields.json'],'implementation':['OutgameDataVersionState.cs','OutgameDataVersionStorage.cs'],'validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Resolve production DataManagerPool registration, save restrictions and concrete manager metadata.','Implement UserLogin reload/upload/download with the verified version initialization.','Trace first LevelID assignment and connect complete startup to menu.'];write(p,audit)
note='\n\n## 管理器版本初始化与清理（389项）\n还原GameDataVersionMgr f12180：只纳入offset9为真的管理器，缺失键版本-1；已有版本不递增，按Local.Keys快照删除失效或停用键；无变化也统一保存一次。LoadManagers将其接入原格式读档；新增保留/重复/停用/空注册表及加载后保存验证。Unity集成389项（原267+关外122）通过，退出0。新增DataManagerBase/Pool共34个源码索引；具体注册表、初始化保存限制与完整启动生产连接继续推进，整体未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameManagerVersionReconciliation','--result','pass','--evidence','389 integrated checks; manager versions reconcile and persist after loading; full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded389; full goal remains active.')
