from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==431
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-readiness-adapter-policy';s['validation'].update(integratedChecksPassed=431,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-readiness-adapter-policy']={'implementationReady': True, 'productionConnected': False, 'source': ['disassembly/Type7511-54847.txt', 'disassembly/Type7488-54711.txt', 'disassembly/Type7488-54715.txt', 'disassembly/Type7488-54719.txt', 'disassembly/Type7488-54720.txt', 'ad-adapter-slots.json', 'ad-readiness-vcall-helper.txt'], 'implementation': ['OutgameAdReadiness.cs'], 'scope': 'Original adapter readiness alternative, guarantee interval policy, cache defaults and finish ordering restored. Complete showAd selection/retry, concrete adapter and live ad/reward wiring incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original readiness virtual dispatch and adapter timing policy') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original readiness virtual dispatch and adapter timing policy','checksPassed':431,'outgameChecksPassed':164,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact': 'BaseController.isReady accepts (adapter.state==2 && adapter.canShow()) OR adapter.isCacheRequest(). Table1746 resolves wasmcode function1545, a virtual dispatch helper using supplied slot8. Metadata slot8 is DAUAdsAdapter.isCacheRequest, base returns true. canShow bypasses interval unless guarantee/non-BANNER, then negates interval>realtime-sharedLastShowTime. finish calls virtual onFinishClearCache before state0. Implemented OutgameAdReadiness/OutgameAdAdapterState,431 checks pass.', 'source': ['disassembly/Type7511-54847.txt', 'disassembly/Type7488-54711.txt', 'disassembly/Type7488-54715.txt', 'disassembly/Type7488-54719.txt', 'disassembly/Type7488-54720.txt', 'ad-adapter-slots.json', 'ad-readiness-vcall-helper.txt'], 'implementation': 'OutgameAdReadiness.cs', 'validation': 'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 广告就绪虚调用与适配器时间策略（431项）\n解析table1746→wasm1545为虚槽分派，传入slot8对应isCacheRequest。新增OutgameAdReadiness保持(state2&&canShow)||isCacheRequest，不能只按加载状态判定。新增OutgameAdAdapterState保持默认cache=true/guarantee=false，仅保底非BANNER执行间隔判断，原否定大于表达式保留等号/NaN与日志后重读共享时间；finish先虚清理再state0，异常不重置。431项（原267+关外164）通过，Unity退出0；源码1635方法。BaseController.showAd完整选择/重试与实际适配器仍待恢复，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdReadinessAdapterPolicy','--result','pass','--evidence','431 integrated checks; source readiness cache alternative, guarantee timing and finish ordering verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded431; full goal remains active.')
