from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-ads-playmode-validation.json')
assert r['passed'] and len(r['checks'])==555 and v['passed'] and play['passed'] and len(play['checks'])==7
sources=['disassembly/Type3135-23913.txt','disassembly/Type3135-23914.txt','disassembly/Type3394-26224.txt']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='sdk-function-state';s['validation'].update(integratedChecksPassed=555,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['sdk-function-state']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameSdkFunctionStates.cs','OutgameSdkButtonRegistry.cs','OutgameVideoButton.cs'],'scope':'SDK function-state cache and refresh semantics restored and connected to native PlayMode registry. IsOpen second argument corrected to refresh, not fallback. Platform capability resolver and complete state refresh APIs remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='DBTSDKManager function state cache and SDKExtension source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'SDK state caching, forced refresh and native registry integration','checksPassed':555,'outgameChecksPassed':288,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-ads-playmode-validation.json','playModeChecksPassed':7,'freshPlayModeRun':True,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'sdk_state_cache_verified_platform_capabilities_pending','source':sources,'verified':['SDKExtension.IsOpen forwards bool as IsRefresh to GetSDKOpenFunctionState','Cache miss queries source then stores; cached values queried again only when refresh=true','SetSDKFunctionState distinguishes Add from overwrite and logs before mutation','Readiness callback sets cached feature15 before changing button states','Native PlayMode registry reads/writes recovered state cache'],'correction':'Earlier SDK15 defaulttrue/defaultfalse wording was incorrect; arguments are forced refresh true/false. Native-video audit and generation script corrected. No invented fallback implemented.','remaining':['GetState full source capability switch and concrete platform implementations','Full SDK state refresh APIs and platform initialization','Production account/menu/report owner and full persistence/build/E2E'],'checks':555,'freshAdsPlaymodeChecks':7,'priorFlyPlaymodeChecks':8,'dynamicScope':'Fresh actual Unity PlayMode using restored cache and registry; platform capability resolver and SDK/report transport remain fixtures'}
write(o/'SDK_FUNCTION_STATE_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'SDK function state cache restored and IsOpen second parameter corrected to force-refresh semantics. Fresh7check native PlayMode uses shared state cache; platform capability queries and account integration remain pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-ads-playmode-validation.json']});write(p,s)
note='\n\n## SDK功能状态缓存与刷新语义（555项+独立7项）\n确认SDKExtension.IsOpen的bool参数为IsRefresh，不是默认值；修正之前关于SDK15 defaulttrue/defaultfalse的审计描述和生成脚本。新增OutgameSdkFunctionStates，缓存未命中或强制刷新时调用GetState来源，Set状态先按新增/覆盖上报日志再写入。PlayMode宿主通过恢复后的缓存和按钮注册表读取/更新功能15，替代直接恒定IsOpen返回。555项集成和重新运行的7项实际PlayMode通过，Unity退出0。源索引2757。完整GetState平台能力分发、其他刷新API、具体平台初始化与生产账号菜单、完整构建尚未完成；当前能力来源仍明确为fixture。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSdkFunctionState','--result','pass','--evidence','555 integrated checks and7 fresh actual Ads PlayMode checks; prior8 fly PlayMode not rerun. SDK capability resolver/concrete platform/account composition pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded555; full goal active.')
