"""Append this original-reference cycle without replacing prior reverse evidence."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
W=Path(__file__).resolve().parent.parent;R=W/'analysis/targets/wxcf1394487200e48f/43';G=R/'generated'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
stamp=datetime.now(timezone.utc).isoformat()
rules=[
 {'id':'background-scene-parent','status':'confirmed','value':{'position':[0,0,2.265000104904175],'baseScale':[.25,0,.4],'aspect':'below .5625 multiply .5625/aspect; above multiply 2*cameraSize*aspect/2.5875000953674316'},'evidence':['original871-disassembly/wasmcode-19607.txt','original871-disassembly/wasmcode-7819.txt','assets/gameplay.unity_6a7134d1d26bb7354ce61871131a7a4c/Transform__28.json']},
 {'id':'tower-label-initial-versus-grade-refresh','status':'confirmed','value':{'baseWorldOffset':[0,.3,0],'initial':'battle.WorldToScreenPoint(base) -> UI.ScreenToWorldPoint -> UI-world up*(.1+grade*.15)','subsequentGradeChange':'battle-world up*(.1+(maxLines-1)*.05) before projection'},'evidence':['original871-disassembly/wasmcode-5595.txt','original871-disassembly/wasmcode-15515.txt','original871-disassembly/wasmcode-10061.txt','original871-disassembly/wasmcode-9712.txt','original871-disassembly/wasmcode-10060.txt']},
 {'id':'native-font-fallback-metrics','status':'confirmed','value':'Retain original defaultNullFont (one empty glyph), original font names and HYZhuZiMuTouRenW fallback; replacing primary with fallback changes best-fit metrics.','evidence':['unity-assets/Font/defaultNullFont__CAB-a14f3eb3adf948afc8e578331928efaf__6544835752251692798.json','presentation-prepared/hud-import.json']},
 {'id':'commander-in-level-presentation','status':'confirmed','value':{'entities':[8031,8032,8033,8034,8035,8036],'parent':'SkillUI/main/commandRoot','localPosition':[0,0,3],'localScale':[70,70,0],'rotation':'retain source prefab','animations':'idle loop -> skill nonloop on use -> idle loop on completion, scaled clock','sortingLayer':'UIPopup original ID2446685369'},'evidence':['tables/CommanderConfig.json','tables/EntityModelConfig.json','original871-disassembly/wasmcode-15922.txt','original871-disassembly/wasmcode-15918.txt','original871-disassembly/wasmcode-15919.txt','resource-snapshots/commanders-20260928/prepared/native-import.json','gesture-visuals/original-TagManager.json']},
 {'id':'entry-highlight-without-input','status':'confirmed','value':'LevelControl.OnGamePlayState calls ShowMyCampEffect on entry when guide does not take over; effect107 at player towers, Default sorting order -20.','evidence':['original871-disassembly/wasmcode-7630.txt','original871-disassembly/wasmcode-4973.txt']},
 {'id':'generic-tool-footer','status':'confirmed','value':'Unlocked + no specific stock + generic points >0 shows original go_toolValue footer; label formats LanguageConfig SkillUI.itemPointNum.','evidence':['original871-disassembly/wasmcode-10347.txt','original871-disassembly/wasmcode-15930.txt','original871-disassembly/wasmcode-15920.txt','original871-disassembly/wasmcode-5670.txt','tables/LanguageConfig.json']}
]
out={'target':{'appId':'wxcf1394487200e48f','version':'43'},'atUtc':stamp,'userConfirmation':'刚进入关卡，尚未操作','rules':rules,'comparison':'original871-visual-comparison.json','classification':'source-backed corrections and single original entry frame compared; full battlefield fidelity remains incomplete'}
write(G/'original871-presentation-evidence.json',out)
p=R/'evidence/original-reference/manifest.json';m=read(p);m['gameViewportEstimate']={'x':0,'y':55,'width':723,'height':1282,'visibleHeight':1263,'status':'inferred from window dimensions and source-aligned anchors; bottom19px occluded'};m['comparison']='generated/original871-visual-comparison.json';write(p,m)
p=G/'presentation-prepared/tower-score-projection.json';m=read(p);m['correction20260928']=rules[1];write(p,m)
p=G/'RESTORE_SPEC.json';m=read(p);m['originalEntryReferenceCorrection']={'status':'confirmed-with-explicit-timing-limits','evidence':'generated/original871-presentation-evidence.json','reference':'evidence/original-reference/manifest.json','comparison':'generated/original871-visual-comparison.json'};write(p,m)
p=R/'BATTLEFIELD_RESTORE_STATE.json';m=read(p);m['sourceArtifacts']['originalReferences']=['evidence/original-reference/manifest.json'];m['target']['representativeLevel']='layout5 mechanics replay and original normal871/layout120 entry frame';m['milestones'].append({'id':'original871-entry-comparison','atUtc':stamp,'status':'single-frame-compared','evidence':['generated/original871-presentation-evidence.json','generated/original871-visual-comparison.json'],'limits':'No original recording, exact time or RNG state; full replay not passed.'});write(p,m)
p=W/'analysis/GOAL_COMPLETION_AUDIT.json';m=read(p);m['atUtc']=stamp;m['latestBuildSha256']=hashlib.sha256((W/'Build/Windows/AreaBattle.exe').read_bytes()).hexdigest()
for row in m['requirements']:
 if row['requirement']=='Complete in-level mechanics':row['scope']=row['scope'].replace('232','239')
 if row['requirement']=='Representative matched visual comparison':row.update(status='single-frame-compared',evidence=['analysis/targets/wxcf1394487200e48f/43/generated/original871-visual-comparison.json'],missing=['Original action/skill/result recordings and synchronized timing'])
m['blockerAudit']={'priorCaptureBlocker':'Superseded for entry frame by user-supplied screenshot; native helper still unavailable.','independentProgressCompleted':'Source corrections, six commanders,239 checks, build and fresh600-frame smoke pass.','remainingEvidence':'Original action/skill/result frames, timing and RNG alignment; one entry screenshot does not establish full fidelity.'};write(p,m)
with (R/'REVERSE_PROGRESS.md').open('a',encoding='utf-8') as f:f.write('\n\n## Original level871 entry reference cycle\n\n'+stamp+' User confirms entry with no input. Recovered source parent scaling, distinct label init/grade projection, original empty-font fallback metrics, six commander Spines, entry highlight and generic tool footer.239 integration checks and fresh600-frame binary smoke pass. The local1.5s no-input fixture also reaches the screenshot connection topology. Single-frame metrics in generated/original871-visual-comparison.json; full synchronized replay remains open.\n')
note='\n\n## 第871关原图对照\n\n用户确认截图为刚进入关卡、尚未操作。已修正背景父节点缩放、塔顶标记初始投影、原字体后备链、六名指挥官骨骼动画、开场蓝圈及道具点栏。239项集成检查和600帧独立程序测试通过；构建0错误、0警告。723×1282视口按原图窗口推定；1.5秒无操作测试可得到同样兵线拓扑。原始随机状态、精确帧时间、完整技能及其他模式的动态对照仍未通过。详见 `analysis/targets/wxcf1394487200e48f/43/generated/original871-visual-comparison.json`。\n'
for p in [W/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md']:
 with p.open('a',encoding='utf-8') as f:f.write(note)
print('Recorded original871 evidence and current validation scope.')
