from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==387
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='version-storage-connected';s['validation'].update(integratedChecksPassed=387,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Resolve and implement GameDataVersionMgr reload/upload/download branches and inherited login failure handling.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['version-storage-connected']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json','original-sdk-storage.js','sdk-storage-source.json','storage-sdk-slot-candidates.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs','OutgameSdkStringStorage.cs','OutgameDataVersionStorage.cs','OutgameFileStorageBackend.cs'],'scope':'Original version array records, integer/default fidelity, duplicate-key Add behavior and SDK queue connected to isolated desktop persistence; real file restart verified. Live SDK and full LitJson malformed-input parity remain unverified.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original version records and isolated persistence restart') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original version records and isolated persistence restart','checksPassed':387,'outgameChecksPassed':120,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
note='\n\n## 版本JSON与隔离持久化接通（387项）\n新增OutgameDataVersionStorage，按原数组格式读写版本、先清字典再Add、保存前标记field29；int32精度与缺失版本-1保持。新增显式目录OutgameFileStorageBackend，通过现有SDK队列实际写入隔离测试目录，并用全新实例重载验证；未访问实际用户存档。2项JSON/重复键/重启测试通过，集成387项（原267+关外120），Unity退出0。DataContract JSON用于已验证记录格式，完整LitJson异常兼容和真实平台仍待验证；整体未完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameVersionStorageConnected','--result','pass','--evidence','387 integrated checks; version JSON and actual persistence restart verified; full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded387; full goal remains active.')
