from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();report=W/'analysis/unity-integrated-validation.json';r=read(report);assert r['passed'] and len(r['checks'])==1063
assert 'AREABATTLE_INTEGRATED_PASS cases=1063' in (W/'analysis/virtual-items-integrated.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');ids=set(range(34313,34333))|{31013,31015,31102,31135,31144,32198,32228,32229,32607};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
findings=[
'VirtualItem_Commander4493 AddItem34315/AddItemOnlyModel34313 invoke virtual Use slot7 unchanged long count. Use34314 ignores quantity, current CommanderControl.Manager.UnlockCommander(config.paramInt), then current UIControl.CommanderUI.RefreshCommanderItem(config.paramInt), reads config param again after resolving UI. No base item stock mutation/report.',
'CommanderManager31013 GetCommanderData uses TryGetValue and returns null on miss.31015 UnlockCommander unconditionally writes CommanderData4030.curLevel(offset16)=1; existing higher level is reset, missing row throws. Added these real methods to existing manager; no invented unlock price or protection.',
'VirtualItem_HeadBox4497 Add34323/OnlyModel34325 likewise virtual Use34324 ignoring quantity, current UserInfoControl.UnlockHeadBox(config.paramInt).32198 checks HaveHeadBox then AddHeadBox. Manager32228 reads actual UserInfoData.field52 List<int>.Contains;32229 List.Add then UserInfo_HeadBoxUnlock(id). Control guard skips duplicates; direct manager Add permits duplicates. OutgameHeadBoxInventory restores these methods against explicit current owner-list provider; full UserInfoManager/control lifecycle not claimed.',
'VirtualItem_HeroPiece4498 Add34327/OnlyModel34326/Use34329 call original virtual/base behavior; no extra crafting, consume or unlock. Shared WASM labels ActivityVirtualItemBase are aliases; type metadata establishes actual parent VirtualItemBase4492.',
'VirtualItem_Strength4499 Add34330 invokes base Add then sends Event.SP_CHANGE with null args; Use34331 invokes base Use then same event. Inherited AddItemOnlyModel does not send SP. Source Event4271 field56 and cctor32607 SP_CHANGE confirmed. Failure before notification skips it without reverting prior base effects.',
'VirtualItem_GamePoints4495 Add34318 and OnlyModel34319 execute respective base first then current DiceGameControl.AddPoint(low32 count). DiceGameControl31102 discards caller quantity and invokes DiceGameDataManager.ChangePoint with zeros.31135 ChangePoint ignores receiver/delta, gets31144 GetPoint = low32 current GlobalItemManager.GetItemCount(11001), clamps returned/message value to max(value,0), sends Mxtz_DataChange(1,result), returns result. It never adds count or repairs global stock. Restored narrow OutgameDicePoints service, not full4038 lifecycle.',
'Factory service now constructs all seven supported virtual source types. Only PackageOpenAuto4490 and PackageOpenManual4491 remain explicit AdditionalConstructors. Original unsupported type2=6/7/9 remain null rather than invented entities.13 new checks load actual79-row shared item table and exercise concrete constructor/real reward engine and real CommanderManager, while UI refresh/reporting and profile ownership remain explicit service boundaries.'
]
limits=['Package entities and random reward selection not restored yet.','Head-box owner list and CommanderUI refresh must be supplied by full production UserInfo/UI owners; restoring narrow methods does not complete those controllers.','Dice points service only restores31102/31135/31144, not full DiceGameControl4038. Lifecycle count remains14/38.','No new native PlayMode or outgame Player; real reports/SDK/accounts/full Main not claimed.']
write(O/'VIRTUAL_ITEMS_SOURCE_EVIDENCE.json',dict(atUtc=now,methods=methods,criticalEvidence=findings,limits=limits))
v=dict(atUtc=now,scope='All seven virtual item entities, real CommanderManager unlock, source head-box unlock/list events and Dice point notification methods',checksPassed=1063,newIntegratedChecks=13,nativePlayModeChecks=0,freshPlayModeRun=False,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly'],notClaimed='Package entities/randomness, full UserInfo/Dice/UI owners, live SDK/report delivery, full outgame Player')
remaining='Restore PackageItemBase4489 and PackageOpenAuto4490/Manual4491 including original weighted selection, long quantities, temporary rewards and use/report/debit ordering. Then complete production owner composition for UserInfo/CommanderUI/Dice/reporting plus24 remaining controller lifecycles/full Main/account/menu/business flows and runnable outgame Player.'
a=dict(atUtc=now,status='seven-virtual-entities-implemented-packages-and-full-owners-pending',sourceEvidence='VIRTUAL_ITEMS_SOURCE_EVIDENCE.json',verification=v,implementedLifecycleControllers=14,remainingLifecycleControllers=24,findings=findings,remaining=[remaining]+limits,disassembledMethodMapCount=len(mm),artifacts=dict(integratedLog='analysis/virtual-items-integrated.log'));write(O/'VIRTUAL_ITEMS_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='virtual-item-entities',virtualItemsAudit='generated/outgame/VIRTUAL_ITEMS_AUDIT.json',nextPriority=remaining);d['validation']['integratedChecksPassed']=1063;d['validation']['virtualItems']=v;d['milestones'].append(dict(id='virtual-item-entities',atUtc=now,status=a['status'],integratedChecks=1063,remainingLifecycleControllers=24));write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=1063,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=report.stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 五类虚拟道具实体增量\n- 1063集成全通过（新增13），日志analysis/virtual-items-integrated.log；Unity51948已退出，无新native/Player。method-map5170（新抽DiceGameDataManager22函数其中18新增）；控制器14/38、24余未变。状态virtual-item-entities。\n- 新OutgameVirtualItems.cs恢复Commander4493、HeadBox4497、HeroPiece4498、Strength4499、GamePoints4495，OutgameItemEntityServices.Construct现在七种virtual实体真实创建，只PackageAuto4490/Manual4491走AdditionalConstructors。原始共享表不支持的type2=6/7/9仍null，不填充。\n- Commander Add/OnlyModel虚调用Use(count)，Use忽略quantity，currentCommanderManager.UnlockCommander(paramInt)→currentUI.RefreshCommanderItem再次读paramInt。新增真正manager.GetCommanderData31013 TryGetValue missnull；Unlock31015无条件curLevel=1（CommanderData4030.offset16确认），高等级也重置，未知id nullfault，界面失败保留先前解锁，不加价格、库存或report。UI接口IOutgameCommanderItemRefresh仍须fullUI owner提供。\n- HeadBox Add/OnlyModel同样virtualUse；Use currentHeadBoxInventory.Unlock(paramInt)。窄服务复原UserInfoControl32198 guard→UserInfoManager32228 List.Contains→32229 List.Add→UserInfo_HeadBoxUnlock(id)。controller去重、manager直接Add允许重复；List由真实UserInfoData owner provider供给，当前测试独立List，未声称完整UserInfoManager生命周期/存档接线。\n- HeroPiece三操作严格base，Use不扣库。Strength Add→baseAdd后SP_CHANGE(nullargs)，Use→baseUse后SP_CHANGE；OnlyModel继承无SP。Event4271静态56/cctor32607证据已核对。\n- GamePoints Add/OnlyModel respectivebase后currentDicePoints.AddPoint(low32count)。源DiceGameControl31102实际丢弃参数调ChangePoint(zeros)，DiceData31135又忽略delta，GetPoint31144=(int)currentGlobal.GetItemCount(11001)，return/message max(point,0)→Mxtz_DataChange(1,result)，不再次加/修复原long库存。这三个窄方法由OutgameDicePoints生产服务实现，尚非全DiceController。\n- 13checks真实原始79行表、7类型工厂、unsupportednull、Commander高level重置/negative/zero/未知id/UI失败/currentparam/虚Use数量传递、头像去重/live记录/消息失败prefix、Strengthnormal/model/use差异与当前dispatcher切换、HeroPiece真实base、积分不双加/低32截断/clamp仅消息及失败prefix。复用GlobalRewardsValidation的internalfixture，实际奖励引擎/manager/原表，有明确报告/界面sink，不冒充全平台。\n- 新O/VIRTUAL_ITEMS_SOURCE_EVIDENCE.json/AUDIT.json、state/manifest/交接同步。下一步PackageItemBase4489.ItemToReward34300(1599bytes)、Use34302(179bytes)、AddItem34304/OnlyModel34303(basecalls)；OpenAuto4490.ItemToReward34305(2078bytes)、Add34306/OnlyModel34307(39bytes虚Use?须核对slot)，Manual4491仅ctor。已抽源body可继续读，不要凭常规礼包机制假设概率/循环。全目标保持active。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('1050 项 checks','1063 项 checks').replace('caseCount=1050；latestValidation 为 global rewards and Gold/Diamond entities','caseCount=1063；latestValidation 为 seven virtual item entities').replace('最新集成日志 analysis/global-item-rewards-integrated-verified.log。1050集成通过','最新集成日志 analysis/virtual-items-integrated.log。1063集成通过').replace('in_progress / global-item-rewards-gold-diamond','in_progress / virtual-item-entities').replace('最新method-map5152；14控制器','最新method-map5170；14控制器');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameVirtualItemEntities','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/VIRTUAL_ITEMS_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
assert all(hashlib.sha256((W/f['path']).read_bytes()).hexdigest()==f['sha256'] for f in d['sourceFingerprints'])
print(json.dumps(dict(checks=1063,controllers=14,remaining=24,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
