from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();report=W/'analysis/unity-integrated-validation.json';r=read(report);assert r['passed'] and len(r['checks'])==1034
assert 'AREABATTLE_INTEGRATED_PASS cases=1034' in (W/'analysis/item-module-integrated.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');classes=['ItemModuleControl','ItemManager','FactoryBase','VirtualItem_Factory','PackageItem_Factory','ItemBase'];methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['cls'] in classes]
findings=[
'ItemModuleControl3875 ctor30187 creates Props/Skills/Heroes only. Init30185->30181 stores current config.Items then30180 rereads current config.Items.Values. type1=4/5 Add id,row;6 indexer overwrite. Reinitialization does not clear; duplicate failure retains source prefix.30184 update empty;30188 Dispose clears controller singleton only.',
'ItemModule get_ItemMgr30182 and separate ItemManager.get_Instance34333 each lazily cache DataManagerPool.GetModel<ItemManager4500>, generic3995108->26750; null lookup retries. Manager OnInit/OnRelease do not set/reset these caches.',
'ChangeItemNum30179 sign-extends delta, wraps Int64 addition with GetItemNum, negative warns exact source string and returns false. Otherwise current manager.GetItem(current config).AddItem(delta), then Item_Change(id), then current pool.SaveData, return original next>=0. Vtable offsets220/224 resolve to ItemBase virtual slot4 AddItem, not Use/AddItemOnlyModel. No balance recheck, zero shortcut, clamp or rollback.',
'ItemManager34334 OnInit invokes inherited UpdateData(true);34335 callback current GlobalItemManager.Init(text,this);34336 release delegates current global.Release;34337 save current global.OnSave then inherited SaveLocalData. Existing actual storage/global lifecycle/persistence composed.34338 Update and34341 ExpendReward are empty.34343 DateTime.Now used as supplied local-now host, not server clock.',
'ItemManager.AddRewards34340 live indexed List<RewardData4549> loop: ItemHelper.GetGoodsType(itemId)==6 skips row. Otherwise current ToolControl.ToolChange(row.id,low32(row.longCount),false,emptyString,false), ignore bool. Uses actual restored ToolControl/dispatcher and explicit source goods-type delegate. No batch transaction. DataKey ItemManager uses existing DataManagerBase storage semantics.',
'GetPackageOpenReward34344 creates List<RewardData>, AddRange3976588 then LinkedList.Clear3971048; copies row references and retains same linked list. Source field20 initialized new linked list in34345.',
'FactoryBase34293 performs ContainsKey on current shared config table then rereads current singleton table indexer; missing emits exact error and leaves null config.34292 Produce supports type1=1 via VirtualItemFactory or9 via PackageItemFactory, else null. Each subclass constructor reruns source base lookup. ItemManager34342 supplies only passed config.id and calls Produce.',
'VirtualItemFactory34298 type2 mapping:1 Gold4496,2 Diamond4494,4 Strength4499,5 Commander4493,8 HeroPiece4498,10 HeadBox4497,11 GamePoints4495; others null. PackageFactory34296:1 OpenAuto4490,2 OpenManual4491,others null. Resolved allocation usage IDs against original type metadata, not ambiguous shared constructor labels.',
'Concrete entity construction remains required explicit dependency by sourceType and id. No generic inventory mutation fallback added. Tests use named recording entity fixture to validate dispatch/order only, not claim actual entity effects. Next work ItemBase4541/global reward engine and all nine entities.'
]
limits=['Concrete item entities, global reward engine and package randomness not restored in this milestone; factory construction is an explicit boundary.','14/38 counts lifecycle wiring only, not full controller business behavior or full Main owner composition.','No fresh native PlayMode or Player build; isolated memory backend used for real serialization/storage pipeline tests; fixture login progress10 is test-only, never fabricated production login.']
write(O/'ITEM_MODULE_SOURCE_EVIDENCE.json',dict(atUtc=now,methods=methods,criticalEvidence=findings,limits=limits))
v=dict(atUtc=now,scope='ItemModule3875 lifecycle and change ordering; ItemManager4500 real global/storage bridge; original factory routing with explicit entity constructor boundary',checksPassed=1034,newIntegratedChecks=14,nativePlayModeChecks=0,freshPlayModeRun=False,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly'],notClaimed='Concrete entity effects/global reward engine/full Main/outgame Player')
remaining='Restore ItemBase4541 and GlobalItemManager AddRewards/AddRewardsModel/ExpendReward engine, then nine concrete VirtualItem/PackageItem entities and package randomness using source evidence; bind concrete constructor provider to current factory routing. Complete remaining24 controller lifecycles and source-default legacy Main/account/menu/business graph, failure/return flows, runnable outgame Player acceptance.'
a=dict(atUtc=now,status='item-module-manager-and-factory-routing-bound-entity-effects-incomplete',sourceEvidence='ITEM_MODULE_SOURCE_EVIDENCE.json',verification=v,implementedLifecycleControllers=14,remainingLifecycleControllers=24,findings=findings,remaining=[remaining]+limits,disassembledMethodMapCount=len(mm),artifacts=dict(integratedLog='analysis/item-module-integrated.log'));write(O/'ITEM_MODULE_AUDIT.json',a)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,itemModuleAudit='ITEM_MODULE_AUDIT.json',verification=v);d['implementedControllerTypes']=list(dict.fromkeys(d['implementedControllerTypes']+[3875]));d['remainingControllerCount']=24;d['implementations']['3875']='OutgameItemModuleControl.cs';d['sourceMethods']=list(dict.fromkeys(d['sourceMethods']+[m['metadata'] for m in methods if m['cls']=='ItemModuleControl']));d['remaining'][0]=remaining;d['findings'].append('ItemModule3875 lifecycle and query/change façade bound;14/38 lifecycle controllers,24 remain. Entity construction still explicit dependency; actual item effects not claimed.');write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='item-module-manager-factory-routing',itemModuleAudit='generated/outgame/ITEM_MODULE_AUDIT.json',nextPriority=remaining);d['validation']['integratedChecksPassed']=1034;d['validation']['itemModule']=v;d['milestones'].append(dict(id='item-module-manager-factory-routing',atUtc=now,status=a['status'],integratedChecks=1034,remainingLifecycleControllers=24));write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=1034,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=report.stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 ItemModule/ItemManager/工厂分派增量\n- 1034集成全通过（新增14），日志analysis/item-module-integrated.log；Unity65828已退出，无新native/Player。method-map5152；controller生命周期14/38，剩24；不是业务图完成。状态item-module-manager-factory-routing。\n- 新OutgameItemModuleControl.cs，CoreBindings.BindItems注册3875。Init二次读取current config（第一次保存Items，第二次遍历Values），4/5类别Add、6覆盖，无clear；Dispose仅清registry3875，保留map/cachedmanager。getItemMgr懒取pool.GetModel4500、null重试。Change先long当前数+signedint unchecked、negative警告退出；否则Manager.GetItem(currentconfig).AddItem(delta)→current message Item_Change(id)→current pool.SaveData→返回先前next>=0。不加clamp/recheck/零值跳过。源虚表220/224是slot4 AddItem（不是此前summary粗略的slot3）。\n- 新OutgameItemManager.cs：IOutgameDataManager接已有Storage和GlobalItemLifecycle，OnInit UpdateData(true)，Callback global.Initialize(text,GetNowDateTime)，OnSave global.Save→storage.SaveLocalData，OnRelease global.Release；Update/ExpendReward源nop。GetNowDateTime为local DateTime.Now provider，不走server。独立OutgameItemManagerSlot懒取pool4500，OnInit/Release不清slot。AddRewards live indexed list跳过GoodsType6，其余取current ToolControl后low32 reward count→ToolChange(...false,empty,false)忽略bool。GetPackageOpenReward新List.AddRange原LinkedList后原表Clear，共享行引用。RewardData4549字段int id,long count,int order。\n- 新OutgameItemFactory.cs恢复FactoryBase ctor双次currentConfiglookup、缺失log保留null，Produce只支持type1=1虚拟/9礼包。子工厂再次源ctor查表；type2映射1 Gold4496、2 Diamond4494、4 Strength4499、5 Commander4493、8 HeroPiece4498、10 HeadBox4497、11 GamePoints4495；Package1 OpenAuto4490、2 OpenManual4491，其他null。实体构造依赖Func<sourceType,id,IOutgameItemEntity>明确尚需实现，不做通用库存fallback。\n- 新OutgameItemModuleValidation14checks：真实Global/Storage内存backend重启和Int64持久化、真实login门槛（测试显式progress10、生产无假登录）、serverdownload、manager/currentGlobal及lazy缓存、release顺序、Tool真实奖励live list/type6skip/long截断/保存失败、package行引用、9实体类型分派、缺失和工厂二次查表、module分类/reinit异常prefix、dispose保留状态、余额不足/Int64overflow、zero/消息/保存顺序以及entity/message失败。实体只recording fixture验证调用，不声称各实体效果已恢复。\n- O/ITEM_MODULE_SOURCE_EVIDENCE.json/AUDIT.json记录证据和界限，matrix/audit14/38同步。完整生产Main/平台/关外Player仍未完成。下一步实现ItemBase4541→GlobalItemManager奖励引擎→九个具体实体，接入construct provider。\n- 本轮新抽取ItemBase4541五方法（34564ctor、34565AddItem、34566AddItemOnlyModel、34567ItemToReward、34568Use）。Ctor直接currentConfig.Items[id]；ItemToReward非nullConfig返回一个RewardData(id,longcount,order0)，nullConfig返回empty。AddItem先resolve global，再virtual ItemToReward(count)→global.AddRewards；OnlyModel同理AddRewardsModel。Use先Item_Use(id,longcount)消息，再构造NewReport_item_use report设置id/item_game/type1/type2 nullable fields并上报；尚未生产实现。VirtualItemBase.AddItem等小方法反汇编的共享函数label可能是ActivityVirtualItemBase/TaskLivenessPoint，不能按label误判实际继承，metadata确认父为ItemBase4541。Global.AddRewards f12045、AddRewardsModel f12046，方法map检索字段非name（用已有结构字段）。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('1020 项 checks','1034 项 checks').replace('caseCount=1020；latestValidation 为 shared item config','caseCount=1034；latestValidation 为 ItemModule/ItemManager/factory routing').replace('最新集成日志 analysis/shared-item-config-integrated.log。1020集成通过','最新集成日志 analysis/item-module-integrated.log。1034集成通过').replace('in_progress / shared-item-config','in_progress / item-module-manager-factory-routing').replace('最新method-map5147；13控制器生命周期/共享绑定已实现并验证，剩25','最新method-map5152；14控制器生命周期/共享绑定已实现并验证，剩24');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameItemModuleManagerFactoryRouting','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/ITEM_MODULE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
assert all(hashlib.sha256((W/f['path']).read_bytes()).hexdigest()==f['sha256'] for f in d['sourceFingerprints'])
print(json.dumps(dict(checks=1034,controllers=14,remaining=24,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
