from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==523
play=read(w/'analysis/outgame-fly-playmode-validation.json');assert play['passed'] and len(play['checks'])==8
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='pooled-prefab-lifecycle';s['validation'].update(integratedChecksPassed=523,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['pooled-prefab-lifecycle']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type3665-28675.txt','disassembly/Type3665-28676.txt','disassembly/Type3665-28677.txt','disassembly/Type3665-28678.txt'],'implementation':['OutgamePooledPrefab.cs'],'validation':'analysis/outgame-fly-playmode-validation.json','scope':'Original NormalPool object lifecycle; restored parent/active state used in actual Play Mode fixture. Base object-pool selection, capacity and resource load/release providers pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original pooled prefab lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original pooled prefab lifecycle','checksPassed':523,'outgameChecksPassed':256,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Original NormalPool object3665 unspawn remembers parent, hides, reparents to poolRoot with worldPositionStays=false; spawn restores remembered live parent then activates without local-transform reset. Release forwards Target to resource helper. Used restored lifecycle in successful8-check actual fly Play Mode rerun.','source':['disassembly/Type3665-28675.txt','disassembly/Type3665-28677.txt','disassembly/Type3665-28678.txt'],'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,audit)
p=o/'NORMAL_POOL_OBJECT_AUDIT.json';write(p,{'status':'object_lifecycle_verified_base_pool_pending','integratedChecks':523,'playmodeChecks':8,'source':['disassembly/Type3665-28675.txt','disassembly/Type3665-28676.txt','disassembly/Type3665-28677.txt','disassembly/Type3665-28678.txt'],'verified':['Unspawn: capture parent, SetActive(false), SetParent(poolRoot,false)','Spawn: restore remembered parent if Unity-alive, SetActive(true); no invented local transform reset','Destroyed previous parent skips restoration while target still activates','Release forwards original target to explicit resource release dependency','Actual simultaneous gold/diamond animation continues to pass with recovered lifecycle callbacks'],'remaining':['Underlying generic object pool selection/reuse, counts and expiration','NormalPool synchronous/asynchronous source asset loaders and release helper','Use original pool in production page/runtime and validate reentry/disposal']})
p=w/'analysis/VALIDATION_MANIFEST.json';manifest=read(p);manifest['latestValidation']['playModeReport']='analysis/outgame-fly-playmode-validation.json';manifest['latestValidation']['playModeChecksPassed']=8;write(p,manifest)
note='\n\n## NormalPool对象生命周期（523项 + 独立8项动态检查）\n新增OutgamePooledPrefab，恢复原3665对象构造/生成/回收/释放：回收先记父节点、隐藏、SetParent(poolRoot,false)，取用时恢复尚存父节点再显示，不重置局部位置/缩放，释放转发原对象。验证父节点销毁分支与原局部变换；Play Mode池夹具的单纯隐藏回调已替换为此恢复生命周期。523项（战斗267+关外256）机械检查通过，8项真实Play Mode检查重跑通过，两个Unity进程均退出0。底层池复用选择/容量/到期、实际资源加载和释放提供者仍未恢复完整，未宣称完整池或关外已完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgamePooledPrefabLifecycle','--result','pass','--evidence','523 integrated checks; 523 integrated checks plus8 actual Play Mode checks; original pooled object parent/active lifecycle verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded523; full goal remains active.')
