from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-skin-item-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==344
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='native-shop-skin-lists';s['validation'].update(integratedChecksPassed=344,skinItemActionChecksPassed=10)
s['nextActions']=['Connect ShopUI toggle/selection listeners and source coroutine pacing, actual icon resources.','Bind activity/video/scene providers and full account startup effects.','Complete remaining outgame systems and playable build/end-to-end validation.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['native-shop-skin-lists']={'implementationReady':True,'scope':'Skin card collection construction/grouping/refresh; not full ShopUI lifecycle or creation pacing','rules':['ShopUI coroutine partitions ordered soldier records by current selected soldier type, builds selected category first, and uses skinType to obtain content parent. Generic resolution confirms List<SkinData>.Add and Dictionary<int,GameObject>.get_Item.','Build creates original SkinItem clones in normal/defense/attack/scene content roots with required provider binding; scene cards use explicit scene controller. Ordered manager indices supply card order.','Collection refresh updates all cards; reconstruction rebuild releases previous card instances.'],'source':['disassembly/Type4407-33808.txt','disassembly/Type4408-33770.txt','shop-list-generic-resolution.json'],'implementation':['OutgameShopSkinLists.cs'],'validation':'All original configured soldier/scene cards instantiate and bind; category parent, current category first, scene shared template, equipment refresh and duplicate-free rebuild verified.','limitations':['Source coroutine yield/pacing not yet implemented','Icon and platform/activity providers remain injected; full page/account wiring pending']};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='ShopUI source skin list construction') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Native original shop skin list construction and refresh','checksPassed':344,'outgameChecksPassed':77,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Shop acquisition/payment/UI, complete account startup or playable lobby'};write(p,s)
note='\n\n## 原商店皮肤列表生成（344项）\n新增OutgameShopSkinLists，按原有序皮肤记录创建全部兵种/场景卡片，当前兵种类别优先创建，映射normal/defense/attack/scene内容容器，场景共享SkinItem模板并绑定独立控制器。每卡片要求显式提供依赖绑定，不以无动作默认值冒充生产行为。原ShopUI预制体验证全部配置数量、分组、当前类别优先、装备刷新和重建无重复；Unity退出0，344集成检查（原267+关外77）。源协程逐帧创建时序、图标与toggle/选择监听、真实提供者、账户启动与完整构建仍未完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
for name in ['unityCompile','outgameCommanderCore','outgameInventoryCore','outgameToolDispatchCore','outgameProfileStore','outgameMenuNavigation','outgameCommanderActions','outgameUiImport','outgameMenuView','outgameCommanderView','outgameLevelProgression','outgameOriginalLocalData','outgameOriginalCommanders','outgameSkinRecords','outgameSkinActions','outgameSkinItemActions','outgameSkinItemView','outgameSceneSkinActions','outgameSceneSkinView','outgameSkinOrder','outgameShopSkinLists']:
 subprocess.run(b+['set-check']+a+['--name',name,'--result','pass','--evidence','344 integrated checks passed including skin item callbacks and isolated restart; full outgame incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded 344 checks; full goal remains incomplete.')
