from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/audio-resource-native-validation.json');assert r['passed'] and len(r['checks'])==994;assert n['passed'] and len(n['checks'])==18
assert 'AREABATTLE_INTEGRATED_PASS cases=994' in (W/'analysis/audio-resource-integrated.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');ids={26373,26374,26375,26376,26378,26169,26181,23827,23789,23790,23791,23792,22357,22389};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
generics=read(O/'audio-resource-generics.json');
for m in generics['methods']:m['sha256']=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()
source=dict(atUtc=now,methods=methods,sharedGenerics=generics,usageResolution={'3938048':'ResourcesModule static pack dictionary at0','3958596':'Dictionary<string,AssetBundle>.ContainsKey','3958600':'Dictionary<string,AssetBundle>.get_Item','3989920':'AssetBundle.LoadAsset<AudioClip>75781','4000588':'GameFrameEntry.GetModule<AssetbundleModule>26446','3989996':'AssetbundleModule._LoadAsset<AudioClip>26239','4008644':'NewResLoadHelper.LoadAssetAsync<AudioClip>26176','4000600':'GameFrameEntry.GetModule<KeWanResLoadModule3511>','4000640':'GameFrameEntry.GetModule<YOResourcesModule3527>'},criticalEvidence=[
'Audio26376 computes original basename via last forward slash and first dot before culture-sensitive path.ToLower. New flag36 branch awaits typed handle, casts MainObject and retains handle; does not call legacy logs/packs.',
'Legacy branch logs lower path and original-case basename, bundle=lower+.unity3d, reads live pack dictionary twice (ContainsKey then get_Item after CLog). Present entry loads AudioClip synchronously; null/missing asset does not fallback. Else GetModule<AssetbundleModule>._LoadAsset<AudioClip>(bundle,basename,null).',
'New-only26378 evaluates unused basename then ToLower and awaits modern helper without its own mode guard. Unload26375 lowercases/appends before checking current mode; modern does not call legacy unload.',
'New helper26176/26186 guard26181 false logs then null, true resolves new module and awaits typed module operation. GetNewResModule26169 selects AppSetting field40 true KeWanResLoadModule3511, false YOResourcesModule3527. Actual module acquisition remains explicit boundary.',
'AssetbundleModule._LoadAsset26253 calls CheckUseRightResLoad and ignores its bool; requests native operation, null operation returns default without log; awaits IEnumerator, GetAsset<T>, native-null logs exact failure text and returns asset.',
'AssetBundleManager23827 checks legacy then RemapVariantName, LoadAssetBundle(mapped,false,original), constructs AssetBundleLoadAssetOperationFull and adds shared operation list. Operation23791 returns false as soon as native request exists, rather than waiting for request completion. IsDone23792 returns request.isDone or logs any nonnull error (including0) and returns true; failed operation can remain in manager list.',
'IEnumeratorAwait22357 -> callback22389 -> shared constructor22371/Run22374/MoveNext22377. MoveNext catches IEnumerator.MoveNext exceptions and completes awaiter; native asset operation is sealed, Current=null and no compiler-generated $this parents, so dedicated source specialization needs no nested coroutine/object-trace synthesis. Existing generic single-yield helper would lose this exception and was not used for the final asset wait.'
],limits=['Modern module/provider acquisition not implemented by this milestone; typed helper boundary is explicit.','Native first-pack audio mapping is a branch fixture; original firstpack contains configs/UI but this does not assert original audio firstpack membership. Native config loading uses actual rebuilt source firstpack.','Native test bundle uses recovered original2001 audio and file transport; no claim of source platform/network remote availability or full Main/Player acceptance.','Coroutine await implementation specializes sealed legacy asset operation. Full generic IEnumerator wrapper nested traversal and trace augmentation are not newly claimed.'])
write(O/'AUDIO_RESOURCE_SOURCE_EVIDENCE.json',source)
v=dict(atUtc=now,scope='Audio helper path branches and legacy native asset operation/transport/config/audio/reference/unload/reentry; sealed IEnumerator error specialization',checksPassed=994,newIntegratedChecks=16,nativePlayModeChecks=18,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameAudioResourcePlayModeValidation.Run'],notClaimed='Modern module acquisition, full generic coroutine wrapper, actual remote server, complete Main/account/menu or full outgame Player')
remaining=['Restore modern new-resource module selection/acquisition: AppSetting field40 selects KeWanResLoadModule3511 or YOResourcesModule3527; NewResLoadHelper26176 guard and typed forwarding exist, provider loading remains explicit boundary. Finish production resource/config composition in full Main owner.','Continue remaining27 business controller lifecycles, original menu/account/module workflows, persistence/restart/failure/return, and runnable full outgame Player acceptance.']
a=dict(atUtc=now,status='source-audio-resource-helper-and-native-legacy-verified-modern-module-pending',sourceEvidence='AUDIO_RESOURCE_SOURCE_EVIDENCE.json',verification=v,findings=['OutgameAudioResources implements both async wrappers, firstpack branch and unload, and binds AudioActionServices. OutgameNewResourceAsyncHelper preserves source guard and generic type.', 'OutgameLegacyAssetOperation, OutgameAssetbundleAsyncLoader and shared BundleRuntime.LoadAssetAsync use existing manifest/remap/acquisition/unload. Source failure/retention and native task propagation retained.','994 integrated pass (16 new),18 native pass. Native actual bundle file download/request -> original2001 manager playback -> reference count2/1/0 -> native Unload(true) -> fresh download verified. Config read from original rebuilt native firstpack.','Full goal remains in progress; lifecycle count11/38 unchanged,27 remain.'],remaining=remaining,artifacts=dict(integratedLog='analysis/audio-resource-integrated.log',nativeLog='analysis/audio-resource-native.log',nativeReport='analysis/audio-resource-native-validation.json'),disassembledMethodMapCount=len(mm));write(O/'AUDIO_RESOURCE_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='audio-resource-native-legacy',audioResourceAudit='generated/outgame/AUDIO_RESOURCE_AUDIT.json',nextPriority=' '.join(remaining));d['validation']['integratedChecksPassed']=994;d['validation']['audioResourceNativeLegacy']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='audio-resource-native-legacy'];d['milestones'].append(dict(id='audio-resource-native-legacy',atUtc=now,status=a['status'],integratedChecks=994,nativeChecks=18,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,audioResourceAudit='AUDIO_RESOURCE_AUDIT.json');d['remaining'][0]=' '.join(remaining);d['findings'].append('Audio resource helpers and actual legacy native bundle/clip/config load/release/reentry verified:994 integrated,18 native; modern module/full app remain;11/38 unchanged.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=994,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=(W/'analysis/unity-integrated-validation.json').stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 音频资源helper与原生旧资源加载增量\n- 当前994集成（新增16）+18原生通过，source method-map5081；controller仍11/38，27剩余。日志audio-resource-integrated.log/audio-resource-native.log，原生报告audio-resource-native-validation.json；状态audio-resource-native-legacy，完整关外Player仍未构建。\n- OutgameAudioResources实现26373/26376、26374/26378和Unload26375，Bind到AudioActionServices。basename保持原大小写、仅forwardSlash和firstdot；path.ToLower当前culture；modern handle MainObject转AudioClip无release；legacy先loglower和basename，packDict ContainsKey→log→再次getdict/getItem→nativeLoadAudioClip，存在但空/缺资源不fallback；否则AssetbundleModule._LoadAsset<AudioClip>(lower+.unity3d,basename,null)。new-onlyhelper无自身modeguard；Unload归一化先于mode检查。\n- OutgameNewResourceAsyncHelper恢复26176/26186的guard26181（false日志+null）、generic类型和await；具体modern module仍delegate边界。GetNewResModule26169按AppSetting static40 true选KeWanResLoadModule3511(generic4000600)，false选YOResourcesModule3527(4000640)，下一步追查各module typed async load和主程序实际配置。\n- 新OutgameLegacyAssetOperation对应23789/91/92、generic23788：bundle lookup→native AssetBundle.LoadAssetAsync；request一旦存在Update立即false，manager移除但await继续看IsDone。error!=null包括"0"日志+done；未获request的failed op仍会留manager list。GetAsset只在request!=null&&done后as T。OutgameLegacyBundleRuntime.LoadAssetAsync恢复23827 check→remap→Acquisition.Load→register。OutgameAssetbundleAsyncLoader恢复26239/26253 ignored falseguard→nulloperation silentnull→await→GetAsset→native-null日志返回。\n- IEnumerator await源22357→22389→generic22371/22374/22377已经提取（analysis/extract_audio_resource_generics.py共9sharedbodies；O/audio-resource-generics.json）。OutgameUnityAwait新增仅对sealed OutgameLegacyAssetOperation的overload：手动MoveNext catch并完成awaiter，以保留原异常传播/同步完成；此类型Current始终null、无$this coroutine parents，不宣称恢复通用nested-wrapper。原generic single-yield会丢异常，本轮asset default不再使用。\n- 原生测试BuildPipeline将已恢复原始2001音频重建Windows AB。首包audio分支映射为显式测试fixture，不冒称原始firstpack包含音频；真实Config读取已有rebuilt91asset firstpack内AudioConfig/OnceAudioConfig（55+53）。actualfile UWR+manifest+native AssetBundleRequest+AudioManager+UpdateManager+OnceAction，ref2→1→0、自然结束卸载、missing asset null诊断、nativeUnLoad销毁clip、再次真实下载、同步MoveNext异常传播均验证。Modern typed module acquisition未完成，不用fake成功。\n- O/AUDIO_RESOURCE_SOURCE_EVIDENCE.json/AUDIT.json保存source hashes/usage IDs/边界。本轮自建Unity37040/55736/66928/48228全部正常退出；无需要续等的进程。最新fingerprints由脚本重算。\n- 下一步modern模块loading以及full Main资源/配置owner；随后继续27controller/可操作业务/存档与完整Player验收。保持整体goal active，无阻塞。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('978 项 checks','994 项 checks').replace('caseCount=978；latestValidation 为 native AudioManager ownership','caseCount=994；latestValidation 为 audio native legacy resources').replace('in_progress / audio-manager-native-ownership','in_progress / audio-resource-native-legacy');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameAudioResourceNativeLegacy','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/AUDIO_RESOURCE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=994,nativeChecks=18,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
