from pathlib import Path
import json,hashlib,datetime,subprocess,struct
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/input-manager-native-validation.json');assert r['passed'] and len(r['checks'])==811;assert n['passed'] and len(n['checks'])==10
h=W/'analysis/recover_outgame_manager_registry.py';ns={'__file__':str(h)};exec(h.read_text(encoding='utf8').split('rows=[]')[0],ns)
u,b,pairs,ts,ms=[ns[k] for k in ['u','b','pairs','ts','ms']];t=ts[3603];fields=[]
for j in range(t[18]):
 f=struct.unpack_from('<3i',b,pairs[11][0]+12*(t[8]+j));fields.append(dict(name=ms(f[0]),typeIndex=f[1],offset=u(u(3823136+4*3603)+4*j)))
mm=read(O/'method-map.json');methods=[]
for m in mm:
 if m['cls']=='InputManager':methods.append(dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()))
write(O/'INPUT_MANAGER_SOURCE_EVIDENCE.json',dict(atUtc=now,sourceType=3603,image='GFRunning.dll',methods=methods,fields=fields,coverage='Complete disassembly inventory, not a claim that all obfuscated aliases are implemented. Production paths: singleton27760, CheckTouch27714, mouse27761, touch27752, keys27750/27742, Update27771, OnGUI27698, Shutdown27712, named Add/Remove wrappers and source delegate offsets52..104. TouchBegin add helper27697 logs before combining; opaque extra singleton alias27682 is not selected.',sourceNotes=['MultiTouchData type3604 id is original touch-array index, not fingerId. Active list excludes Ended/Canceled. MulTouchBegin and TouchDebug have source listener APIs but are not dispatched by restored Update/OnGUI paths.','KeyDown duplicate branches out of inner key block and still reaches KeyHold: wasm br_if1 inside if, at0057cd7c. KeyHold receives live HeldKeys list.','Single-touch End/Canceled invokes End before strict<MoveStep click; mouse does reverse. Multi zero-count End is also emitted following single-touch frames.','TouchBegin CLog payload is preserved with injectable RegistrationLog; default sink is Unity Debug.Log. Full source CLog filtering/config is not restored here.']))
v=dict(atUtc=now,scope='Shared source InputManager native singleton/Update/OnGUI, mouse/touch/multi/key event boundaries and default PlayerInput subscription',checksPassed=811,newIntegratedChecks=19,nativePlayModeChecks=10,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameInputManagerPlayModeValidation.Run'],notClaimed='OS/device input injection, original CLog policy, full actual Main/account/platform/UI composition or complete outgame Player build')
a=dict(atUtc=now,status='partial-subsystem',sourceEvidence='INPUT_MANAGER_SOURCE_EVIDENCE.json',verification=v,findings=[
 'Native OutgameInputManager MonoBehaviour singleton follows Find named InputManager -> GetComponent -> AddComponent -> DontDestroyOnLoad, using Unity destroyed-null semantics. Update calls CheckTouch; OnGUI calls key handler. Android/iPhone/WebGL choose touch through original short-circuit platform reads; other platforms use mouse.',
 'Mouse source reads independent XY/press positions; Down > Up > Held. Movement uses exact coordinate inequality. Mouse Click precedes End; touch End/Canceled precedes Click, strict distance<MoveStep50, live callback state and exceptions preserved. No invented UI blocking, debounce, cancel suppression or WebGL mouse fallback.',
 'Multi-touch rebuilds active list each frame, original array indices, excludes ended/canceled, dispatches Hold when none moved (including all Began), Move when any moved. Scale is current-first-two distance minus previous-first-two distance divided by50, after callback, with live mutable list. Active<2 returns; zero count dispatches MultiEnd only if retained count>=1. No synthesized MultiBegin.',
 'Keys initialize list even for absent event; only GUI key events update. Repeated KeyDown avoids duplicate Down but still Hold; KeyUp invokes before removal using live HeldKey. Hold receives live list; zero KeyCode preserves current key. Shutdown clears14 delegates and preserves history/owner; registration supports duplicates and one-at-a-time removal. Begin registration logs before combination, preserving failure ordering.',
 'OutgamePlayerInput default constructor now registers directly with actual InputManager; explicit adapters retained for probes. Native run verifies Unity Update -> default input -> Player.OnTouchBegin -> source native ray gate; disposal unsubscribes, other listeners remain, Shutdown clears old subscriptions while frames continue, persistent-scene placement and destroyed-owner recreation verified.',
 '811 integrated checks (19 new) and10 native pass. Native device reads are explicitly scripted, not OS input or original matched replay. Original CLog policy remains a supplied host boundary (default Unity debug sink). InputManager is framework type3603, so controller roster remains10/38 method-level implementations,28 remaining.'
 ],remaining=['Restore remaining28 actual controller lifecycles and business methods, and full Main/module/config/account/menu composition. Shared CLog policy and actual device validation remain open.','Finish remaining Level/Tower/Soldier/WayLine/AI/effect services and native resource set; complete all objective outgame subsystems, persistence/restart/failure/return flows and runnable Player acceptance.'],artifacts=dict(integratedLog='analysis/input-manager-integrated-final.log',nativeLog='analysis/input-manager-native-final.log',nativeReport='analysis/input-manager-native-validation.json'),disassembledMethodMapCount=len(mm))
write(O/'INPUT_MANAGER_NATIVE_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='shared-input-manager-native',inputManagerAudit='generated/outgame/INPUT_MANAGER_NATIVE_AUDIT.json',nextPriority='Restore remaining28 actual controller lifecycles and business methods, supply real Main/module/config/account/menu entry composition; finish Level/Tower/Soldier/WayLine/AI/effects and native resources. Complete full objective flows, persistence/restart/failure/return and runnable Player acceptance without invented platform success.');d['validation']['integratedChecksPassed']=811;d['validation']['inputManager']=v;d['validation']['inputManagerNative']=n;d['milestones']=[m for m in d['milestones'] if m['id']!='shared-input-manager-native'];d['milestones'].append(dict(id='shared-input-manager-native',atUtc=now,status='partial-subsystem',integratedChecks=811,nativeChecks=10,remainingLifecycleControllers=28));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,inputManagerAudit='INPUT_MANAGER_NATIVE_AUDIT.json');d['remaining'][0]=a['remaining'][0]+' '+a['remaining'][1];d['findings'].append('Shared framework InputManager now restored with default PlayerInput native route:811 integrated +10 new native. Framework manager does not change10/38 controller lifecycle count. Full entry/platform/device replay still open.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=811,latestValidation=v);d['validationHistory'].append(v)
if 'analysis/input-manager-native-validation.json' not in d['reports']:d['reports'].append('analysis/input-manager-native-validation.json')
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 共享InputManager原生输入增量\n- 新增OutgameInputManager(type3603)：原生MonoBehaviour Update/OnGUI、命名单例Find/GetComponent/AddComponent/DontDestroyOnLoad，原生UnityInput默认数据源；PlayerInput默认构造已直接接入共享输入监听。\n- Android/iPhone/WebGL走touch，其余mouse；鼠标Down>Up>Held、独立位置读数、精确坐标移动、Click先于End；touch End/Canceled先于Click、严格<50、不补UI屏蔽/WebGL鼠标回退。多指重建有效列表、id=数组index、Began也走Hold、位移后缩放delta/50、zero count触发MultiEnd。\n- KeyDown重复仍派发Hold（WASM内层block核对），KeyUp先回调后移除live HeldKey，Hold传live list。Shutdown只清14个委托，保留历史/单例。注册Begin先日志后Combine，重复监听按次移除；CLog原始过滤策略待完整host恢复，当前可注入日志适配器默认Debug.Log。\n- 811集成（新增19）+10 InputManager原生PlayMode通过。原生Update->默认PlayerInput->真实Player.OnTouchBegin射线gate，Dispose注销/Shutdown持续更新/持久场景/销毁重建验证。设备读取为明确脚本fixture，不宣称OS触摸或SDK/完整入口接通。\n- O/INPUT_MANAGER_SOURCE_EVIDENCE.json、INPUT_MANAGER_NATIVE_AUDIT.json；日志analysis/input-manager-integrated-final.log、input-manager-native-final.log；无本任务待续进程。method-map4821。\n- InputManager是框架类，不增加业务控制器计数：仍10/38方法级实现，剩28；完整关外goal active，无新Player构建。下一步剩余控制器与真实Main/module/account/menu生产组合、Level/AI等余项及完整目标验收。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('792 项 checks','811 项 checks').replace('caseCount=792；latestValidation 为 Player controller/native input/models','caseCount=811；latestValidation 为 shared InputManager/native route').replace('in_progress / player-controller-native-input-models','in_progress / shared-input-manager-native').replace('最新method-map4681；','最新method-map4821；').replace('最新集成日志 analysis/player-control-integrated-final.log；Player原生日志 analysis/player-control-native.log。792集成+10 Player原生通过；','最新集成日志 analysis/input-manager-integrated-final.log；输入原生日志 analysis/input-manager-native-final.log。811集成+10 InputManager原生通过；历史Player10项通过；');p.write_text(s+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameInputManagerNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/INPUT_MANAGER_NATIVE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=811,native=10,fingerprints=len(files),sourceMethods=len(methods),fields=len(fields),methodMap=len(mm))))
