from pathlib import Path
import json,hashlib,struct,datetime
W=Path.cwd();T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame';h=W/'analysis/recover_outgame_manager_registry.py';n={'__file__':str(h)};exec(h.read_text().split('rows=[]')[0],n);u,b,pairs,ts,ms=n['u'],n['b'],n['pairs'],n['ts'],n['ms'];mm=json.loads((O/'method-map.json').read_text(encoding='utf8'));methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if any(m['path'].startswith('disassembly/Type'+str(i)+'-') for i in range(4458,4463))];fields=[]
for i in [4462]:
 t=ts[i]
 for j in range(t[18]):
  f=struct.unpack_from('<3i',b,pairs[11][0]+12*(t[8]+j));fields.append({'class':ms(t[0]),'field':ms(f[0]),'type':f[1],'offset':u(u(3823136+4*i)+4*j)})
extras=[]
for path in ['generated/gesture-visuals/original-TagManager.json','generated/controls-disassembly/Layers-.cctor-100665864.txt','generated/controls-disassembly/Layers-GetLayerID-100665863.txt']:
 extras.append({'path':path,'sha256':hashlib.sha256((T/path).read_bytes()).hexdigest()})
r={'atUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'source-backed-controller-lifecycle-input-and-model-composition','methods':methods,'fields':fields,'additionalSources':extras,'resolvedUsages':{'3956396':'Dictionary<int,Transform>.Add (InitLoadModel roots, not set_Item)','3956196':'Dictionary<int,SpineAnimator>.Clear (only model animator cache cleared by OnDispose)','3954536':'Dictionary<int,Dictionary<int,GameObject>>.get_Item (periodic RefreshAnimation)','3931644':'System.Exception (periodic refresh catches and logs)','3944712':'Event4271; staticfield0 is LoadGameScreen','Layer112':'Layers.cctor staticfield112=Scenes11; original TagManager index31; GetLayerID returns 1<<NameToLayer(name)'},'rules':[
 'Constructor source SelectedType3, DragLimit200f, ModelScale1, zero vectors; roots and animator dictionaries initialized, model dictionaryfield8 remains null until InitLoadModel.',
 'OnInit registers LoadGameScreen then RotateSoldier then InputManager touch-begin. OnDispose clears registry4462, animator dictionary, then both message listeners and touch listener. No initialization guard, model or root cleanup, or native destruction.',
 'LoadGameScreen handler calls actual GameControl.InitScene then InitLoadModel. InitLoadModel independently resolves game.SceneRoot roots48/52/56, creates new model dictionary, Add keys1/2/3 to retained root dictionary, captures left normal/middle attack/right defense position then scales, requests currently equipped type1/2/3 separately.',
 'Home state2 adds scaled delta to all three timers before threshold checks; strict>11.7/13.7/14.7 zero each before refresh, once per update. Refresh catches Exception and logs object[]{Chinese type prefix,category,ex.ToString()}; warning failure propagates. UI page2 dragging is independent of home-state condition.',
 'Drag requires selected root activeInHierarchy. MouseDown y>integerScreenHeight/2 sets finger=true,amount0,beginX. Fetch current/next/previous roots. While held and finger, clamp signed delta to +/-200 then source Vector3.Lerp of 3 positions first then3 scales; set direction after transforms. MouseUp and finger: amount>.3 snaps and wraps, sends ChooseSoldier then clears finger; otherwise snaps back. Page leave/hidden root does not clear finger. Event rotation uses same state and sequential live root lookup positions before scales; no ChooseSoldier notification.',
 'TouchBegin gates levelstate2 then UI page3. Uses game.HomeCamera and Scenes11 layer. Raycast writes sourcepoint172 x/y only retaining z; ScreenPointToRay, floatMax ray length, 1<<NameToLayer, shared hit128. If hit transform Animator exists, resolve component again and SetTrigger(Trigger).',
 'InitFirstAdsItem0 clears three fields116/120/124; selectors1/2/3 clear one; others no-op. SetSoldierActive foreach retained roots values sets active, no list snapshot/null filtering.',
 'Model load callback34213 uses live modelposition field188 (separate from raypoint172) and live scale184. Existing model/animation services now share retained controller ownership, model-map replacement and live SkinManager; disposed native animator compares Unity null rather than CLR interface null. Completion34219 reads current equipped animator cache then captured fallback.'
],'remaining':['Full production Main entry and shared source InputManager host graph; model asset set for all skins, matched UI and platform behavior, remaining28 lifecycle controllers and full outgame acceptance.']}
(O/'PLAYER_CONTROL_SOURCE_EVIDENCE.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print({'methods':len(methods),'fields':len(fields)})
