from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-skin-item-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==345
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='shop-tab-title-and-red-dots';s['validation'].update(integratedChecksPassed=345,skinItemActionChecksPassed=11)
s['nextActions']=['Restore original toggle group content visibility/graphics/event wiring and source startup selection.','Bind original sprites/activity/video/scene providers and full account startup effects.','Complete remaining outgame systems and playable build/end-to-end validation.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['shop-tab-source-callbacks']={'implementationReady':True,'scope':'ShopUI toggle callback title/rotation/red-dot effects; separate content/group wiring pending','rules':['False toggle callback is inert. True plays2001, normal/defense/attack update retained soldier type1/2/3; scene/shop retain prior soldier type. Refresh red dots with active category hidden, dispatch RotateSoldier using retained type, localize title.','Red dots use indexed soldier isNew matching category or any scene isNew, without ownership test. Shop dot always false. Hiding active dot does not clear skin flags.','Import native Toggle selectable scalar state and targetGraphic; source persistent event/group/graphic references still pending.'],'source':['disassembly/Type4408-33785.txt','disassembly/Type4408-33774.txt','disassembly/Type4150-31751.txt','disassembly/Type4150-31752.txt','ui-import.json'],'implementation':['OutgameShopTabs.cs','RecoveredHudImporter.cs'],'validation':'Original Toggle events invoke source effect order, retained soldier rotation, localized scene title, non-consuming current red dot suppression and false no-op.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='ShopUI toggle/title/red-dot callback') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original ShopUI native toggle callbacks and red-dot behavior','checksPassed':345,'outgameChecksPassed':78,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Shop acquisition/payment/UI, complete account startup or playable lobby'};write(p,s)
note='\n\n## 商店页签回调（345项）\n新增OutgameShopTabs：true切换播放2001，兵种类别更新保留的旋转类别，场景/商店保留前一个兵种类别；更新红点、发送旋转通知并本地化标题。选中页签隐藏红点但不清除皮肤isNew，false回调无动作。初次验证发现原Toggle未导入，已补原组件基础状态/targetGraphic导入并重新导入页面，复验Unity退出0，345集成检查（原267+关外78）。Toggle图形/group/持久事件和内容切换、启动选中、原图标与实际提供者仍需补齐，完整关外未完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
for name in ['unityCompile','outgameCommanderCore','outgameInventoryCore','outgameToolDispatchCore','outgameProfileStore','outgameMenuNavigation','outgameCommanderActions','outgameUiImport','outgameMenuView','outgameCommanderView','outgameLevelProgression','outgameOriginalLocalData','outgameOriginalCommanders','outgameSkinRecords','outgameSkinActions','outgameSkinItemActions','outgameSkinItemView','outgameSceneSkinActions','outgameSceneSkinView','outgameSkinOrder','outgameShopSkinLists','outgameShopTabs']:
 subprocess.run(b+['set-check']+a+['--name',name,'--result','pass','--evidence','345 integrated checks passed including skin item callbacks and isolated restart; full outgame incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded 345 checks; full goal remains incomplete.')
