from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-skin-item-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==339
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='native-soldier-skin-card-view';s['validation'].update(integratedChecksPassed=339,skinItemActionChecksPassed=6)
s['nextActions']=['Recover separate SceneSkinItem controller; source skin ordering and full ShopUI card creation/listeners.','Bind production sprite/activity/video providers and account startup concrete effects.','Complete remaining outgame systems and fresh playable build/end-to-end validation.']
for sub in s['subsystems']:
 if sub['id']=='skins-cosmetics':sub.update(implementation='Skin manager/item actions plus native soldier SkinItem view; full ShopUI/scene controller and providers pending',validation='7 manager and6 item/native-card checks pass; subsystem incomplete')
write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['native-soldier-skin-card']={'implementationReady':True,'scope':'Original soldier SkinItem template; excludes SceneSkinItem and full ShopUI assembly/providers','rules':['Owned card state1 if equipped else0. Locked special0/1 ->3 purchase; special2 ->4 activity when actNo1301 seven-day is active or other activity status !=5, otherwise3; special3 ->5 special acquisition; other special retains prior state.','Refresh clears activity/using/ad/buy/special UI then state1 using,3 buy,4 activity,5 special with localized ShopUI.ActivityGetWay; state0 none, default ad. btn_choose visibility preserved.','Native buttons call source action layer and refresh. Ad request uses skinType+1001 and explicit provider callback. Red dot follows isNew. Gold/diamond group visibility follows castType, labels source price; tag only nonempty.'],'source':['disassembly/Type4364-33355.txt','disassembly/Type4364-33358.txt','disassembly/Type4364-33359.txt','disassembly/Type4364-33361.txt','disassembly/Type4364-33366.txt','disassembly/Type4364-33370.txt','disassembly/Type4364-33371.txt'],'implementation':['OutgameSkinItemView.cs'],'validation':'Original ShopUI soldier template instantiated; native buy event updates real skin/inventory and used badge; activity transitions and unknown-special retention verified. Sprite/activity/video providers injected; full production binding pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='SkinItem native button/state flow') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Native soldier SkinItem buttons and activity visibility transitions','checksPassed':339,'outgameChecksPassed':72,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Shop acquisition/payment/UI, complete account startup or playable lobby'};write(p,s)
note='\n\n## 原兵种皮肤卡片（339项）\n新增 OutgameSkinItemView，绑定原 ShopUI 的 SkinItem 模板：价格/货币图标、标签、购买/选择/广告回调、使用中与新标记、活动入口。保留 special0/1购买、special2按活动状态切换、special3特殊入口、未知special保留既有状态；活动1301读取七日活动，其他读取status!=5。广告请求编号skinType+1001。恢复原预制体直接调用按钮事件，验证真实解锁/装备与活动状态转换。2新检查通过，Unity退出0，339集成检查（原267+关外72）。完整ShopUI生成/排序/监听、独立SceneSkinItem、真实图标与活动/广告提供者、账户启动和构建仍待完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
for name in ['unityCompile','outgameCommanderCore','outgameInventoryCore','outgameToolDispatchCore','outgameProfileStore','outgameMenuNavigation','outgameCommanderActions','outgameUiImport','outgameMenuView','outgameCommanderView','outgameLevelProgression','outgameOriginalLocalData','outgameOriginalCommanders','outgameSkinRecords','outgameSkinActions','outgameSkinItemActions','outgameSkinItemView']:
 subprocess.run(b+['set-check']+a+['--name',name,'--result','pass','--evidence','339 integrated checks passed including skin item callbacks and isolated restart; full outgame incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded 339 checks; full goal remains incomplete.')
