from pathlib import Path
import json,hashlib,datetime,subprocess,re
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/audio-playback-native-validation.json');assert r['passed'] and len(r['checks'])==875;assert n['passed'] and len(n['checks'])==13
mm=read(O/'method-map.json');ids=set(range(26301,26310))|set(range(26327,26337))|{26371,26372};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
source=dict(atUtc=now,methods=methods,assetEvidence='MAIN_AUDIO_ASSET_EVIDENCE.json',criticalEvidence=[
 'Loop MoveNext26308: initial data-null branch00431fec->004328d4 calls Stop. Loaded clip-null branch00432629(false path) returns null without Stop or log. Captures path/start/type/normalized volume/setting/name before await; root read after await. New-resource result stored at offset48 and MainObject as AudioClip; legacy branch returns AudioClip directly.',
 'Loop source.playOnAwake=false; spatialBlend Atype1=>0 otherwise1; dopplerLevel=0 only Atype2; clip/volume(start volume*setting)/time(start int asfloat)/loop=true/Play, then base assigns source and invokes start. Empty update and pause hooks.',
 'Loop Stop26305: source.Stop if native-nonnull -> end callback -> handle.Release if CLR-nonnull -> Dispose. Handle field is not cleared. Both Once/Loop Dispose26334/26306 DestroyAudioSource then clear source. Helper26372 destroys source.gameObject, helper26371 checks root, creates Utils child then AddComponent<AudioSource>. No postawait cancellation/root guard.',
 'Once26335 reachable initial branch00481672->0048196e and scheduled states2/3 use new/legacy loaders. States0/1 have resume-only bodies without a scheduling predecessor in this exported WASM. SDK switch stateoffset48 is set false at00481627, with no later write; SDK path string initialized empty at00481620. No Android or SDK playback activation is inferred from dead code.',
 'Once captures path/start/end/type/volume/setting/name; stores EndTime52 then StartTime48 before await. Null clip logs object[]{nonAndroidPathMessage}; unconditionally progresses to no-source deadline realtime+field64 (default0). No natural start callback for null source. Native configuration matches loop with loop=false.',
 'Once OnUpdate26333: with source EndTime<=0 only stops when !isPlaying&&!paused; EndTime>0 branch tests source.time>=EndTime without paused gate (NaN comparison follows source). Without source requires deadline>0, realtime-deadline>0 and !paused. Stop resets deadline=-1/SDKhandle0 before callback then release and Dispose. SDK stop call is inside native source gate but handle remains0 in reachable exported path.',
 'Stop during loading does not cancel. A later successful await can start a native source after update/data/listener disposal; destroyed live root instead returns null from helper and faults at unguarded source property assignment.'
 ],limits=['Concrete source actions require resource tasks and shared update/config/settings bindings. Full original resource helper26373/26374/26375 and AudioManager ownership not yet wired.','Native13 checks validate Unity cursor/isPlaying/fields/destruction using original clips; update scheduling and resource providers are explicit fixtures. No acoustic/device recording or Player smoke claim.'])
write(O/'AUDIO_PLAYBACK_SOURCE_EVIDENCE.json',source)
v=dict(atUtc=now,scope='Source Once/Loop concrete playback actions and native source helper; original main-music1002 asset import',checksPassed=875,newIntegratedChecks=15,nativePlayModeChecks=13,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameAudioPlaybackPlayModeValidation.Run'],notClaimed='Full original audio resource/update/AudioManager composition, Fade/LoopFade, SDK playback, device recording or full outgame Player')
a=dict(atUtc=now,status='partial-subsystem',sourceEvidence='AUDIO_PLAYBACK_SOURCE_EVIDENCE.json',verification=v,findings=[
 'OutgameAudioLoopAction and OutgameAudioOnceAction are concrete production actions that create and play real native AudioSource objects. Shared action services now require explicit new/legacy audio load tasks, original OutgameAssetHandle operation, logging/SDK-stop boundary, and production realtime/native destruction defaults.',
 'Source asynchronous capture, late load after stop, null/destroyed-root faults, volume timing, both resource branches and end/release/dispose failure ordering retained. Native helper children inherit root layer and reset local transforms; destruction targets GameObject.',
 'Once recovers strict real-time null-clip completion and native isPlaying/EndTime branches. Paused positive-EndTime playback still stops at boundary; exact-zero null-clip deadline remains pending. Exported WASM has no reachable Android scheduling or true SDK switch write, so no synthetic platform behavior added.',
 'Original main-music1002 recovered AAC was already present in asset evidence but excluded from earlier combat-only preparation. prepare_outgame_main_audio.py decodes to PCM float32 without resampling and copies1002.wav to production Resources; source and decoded hashes preserved separately. Existing combat audio code and manifest remain unchanged.',
 '875 integrated checks pass (15 new).13 native PlayMode checks pass using original1002 and2001: native cursor advancement/start seek, pause freeze/resume, volume messages, explicit stop/release/delayed destruction, positive EndTime during pause, natural one-shot completion. Resource/update ownership in this validation is an explicit fixture.',
 'Lifecycle stays11/38 with27 remaining; indexed method-map4979. Full outgame objective still incomplete; no fresh Player build.'
 ],remaining=['Restore Fade/LoopFade including source countdowns. Restore AudioManager config/root/listener/node registry and Composite.NewAudio hook/factory. Recover actual helper load/unload operations and shared UpdateManager before full UI/controller production audio acceptance.','Continue remaining27 controller lifecycles and full Main/account/module/menu composition; validate all original objective subsystems including restart/failure/return flows and runnable Player.'],artifacts=dict(integratedLog='analysis/audio-playback-integrated.log',nativeLog='analysis/audio-playback-native.log',nativeReport='analysis/audio-playback-native-validation.json',asset='MAIN_AUDIO_ASSET_EVIDENCE.json'),disassembledMethodMapCount=len(mm))
write(O/'AUDIO_PLAYBACK_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='audio-once-loop-native',audioPlaybackAudit='generated/outgame/AUDIO_PLAYBACK_AUDIT.json',nextPriority=' '.join(a['remaining']));d['validation']['integratedChecksPassed']=875;d['validation']['audioOnceLoopNative']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='audio-once-loop-native'];d['milestones'].append(dict(id='audio-once-loop-native',atUtc=now,status='partial-subsystem',integratedChecks=875,nativeChecks=13,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,audioPlaybackAudit='AUDIO_PLAYBACK_AUDIT.json');d['remaining'][0]=' '.join(a['remaining']);d['findings'].append('Concrete Once/Loop production actions and native13 verified; original1002 imported.875 integrated pass; Fade/LoopFade/resource/update/AudioManager still open. Controller count11/38 unchanged.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=875,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 单次/循环原生音频增量\n- OutgameAudioPlaybackActions.cs：实际Once/Loop动作，真实native AudioSource.Play/Pause/UnPause/Stop，helper子GO/local/layer和DestroyGO；基类services新增显式new/legacy资源task、OutgameAssetHandle、log/SDK-stop、默认Time.realtimeSinceStartup/原生Destroy。资源与共享update host尚未完整接线。\n- Loop加载前捕获config/setting/name，await后使用live Root；clip null直接return，data null才Stop；OnUpdate/OnPause为空。Stop原生停播→end→handle.Release→Dispose；不清handle引用。停止期间load不取消，晚到可以重新开始但无update/data/listener；Root销毁后helper null、设置属性原样报错。\n- Once保留EndTime/StartTime在await前写入，空clip报错后deadline=实时+0；deadline必须>0且elapsed>0才结束；0时刻空clip永久pending。已有source End<=0以!isPlaying&&!paused完成；End>0分支到时即停，无paused gate。Stop重置deadline/SDKhandle再end/release/dispose。\n- 该微信WASM OnPlay只调度state2/3资源等待，Android state0/1无调度来源；SDK state48只初始化false且无后续写入，不人为打开SDK播放。SdkDuration和SdkHandle在可达路径保持0。\n- 主界面1002原始AAC已存在asset-evidence但旧prepare_audio.py仅战斗跳过它。analysis/prepare_outgame_main_audio.py独立解码PCM float32无重采样，Resources/Recovered/Audio/1002.wav，O/MAIN_AUDIO_ASSET_EVIDENCE.json存source/decoded hashes。旧战斗代码/audio-runtime manifest未改。\n- 875集成通过（新增15），analysis/audio-playback-integrated.log。13原生PlayMode通过，analysis/audio-playback-native-validation.json / audio-playback-native.log：原始1002/2001实际游标/起始seek/暂停恢复/音量/Stop/释放/帧后销毁/正EndTime暂停门限/自然结束。无设备录音或Player新build；loader/update在验证中显式fixture，不能冒充完整host。无本任务待续进程。\n- O/AUDIO_PLAYBACK_SOURCE_EVIDENCE.json、AUDIO_PLAYBACK_AUDIT.json。状态audio-once-loop-native；875/4979/11/27。下步Fade/LoopFade+countdown、完整AudioManager root/listener/config/node ownership、Composite.NewAudio hook/factory、源资源与UpdateManager接通，之后其他完整关外范围。\n- 已新抽取helper类型3424（26370..26379）和嵌套3422/26376、3423/26378。26371 CreateAudioSource/26372 Destroy已实现；LoadAudioClip26373/LoadAudioClipForNewRes26374需继续读嵌套；UnLoadAudioClip26375把path.ToLower()+.unity3d后只有!NewRes时AssetBundleManager.UnloadAssetBundle。analysis/audio_disassembly_slice.py PATH STARTHEX ENDHEX可打印紧凑源码及br目标，便于确认复杂状态机。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('860 项 checks','875 项 checks').replace('caseCount=860；latestValidation 为 audio nodes/action base','caseCount=875；latestValidation 为 audio once/loop native').replace('in_progress / audio-nodes-action-base','in_progress / audio-once-loop-native').replace('最新集成日志 analysis/audio-action-integrated.log。860集成通过，本批未跑原生音频；','最新集成日志 analysis/audio-playback-integrated.log。875集成、13原生音频通过（loader/update为fixture）；').replace('最新method-map4969；','最新method-map4979；');p.write_text(s+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameAudioOnceLoopNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/AUDIO_PLAYBACK_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=875,nativeChecks=13,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
