from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==514
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='shop-native-products';s['validation'].update(integratedChecksPassed=514,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['shop-native-products']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4407-33808.txt','disassembly/Type4408-33770.txt','disassembly/Type4362-33338.txt'],'implementation':['OutgameShopProductList.cs','OutgameProjectShopItemView.cs'],'scope':'ShopUI goods section filters storeType11 only, clones original ShopItem under original Content_Shop, binds native price/quantity/button to real inventory purchase. Full page lifecycle and account/asset/audio/report providers pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Native ShopUI product cards and actual inventory purchase') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Native ShopUI product cards and actual inventory purchase','checksPassed':514,'outgameChecksPassed':247,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'ShopUI coroutine33808 selects only storeType11; original16-row table yields10001..10004. Native prefab buttons tested with actual inventory. Legacy StorePurchaseUI coroutine33860 only hides templates and yields once; it does not populate the product catalog.','source':['disassembly/Type4407-33808.txt','disassembly/Type4411-33860.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'PROJECT_SHOP_ITEM_AUDIT.json';write(p,{'status':'native_cards_verified_full_page_pending','sourceType':4362,'configType':3943,'checks':514,'implementation':['OutgameProjectShopItem.cs','OutgameProjectShopItemView.cs','OutgameShopProductList.cs'],'source':['disassembly/Type4407-33808.txt','disassembly/Type4408-33770.txt','disassembly/Type4362-33338.txt'],'verified':'Actual ShopUI storeType11 rows10001..10004; original prefab paths; native button clicks debit1440 diamonds/grant36 ToolValue; insufficient funds no reward; rebuild no duplicate callbacks; no invented isActive filter.','legacyPurchaseCoroutine':'Type4411-33860 only hides5 templates and yields one WaitForEndOfFrame; no catalog population.','pending':['Connect full ShopUI lifecycle and actual account dependencies','Connect original icon/audio/report providers','Complete other page callbacks and source coroutine initialization cadence']})
note='\n\n## ShopUI原生商品卡片（514项）\n追踪ShopUI协程33808确认仅storeType11进入商品列表，原表对应10001～10004；旧StorePurchaseUI协程33860只隐藏模板并等待一帧，没有构建商品列表。新增OutgameShopProductList和OutgameProjectShopItemView，按原Prefab的bottom/ShopItem与Content_Shop路径绑定价格、数量、图标请求和按钮。真实按钮验证依次扣1440钻石、加36张道具卡，余额不足不发奖，重建不重复绑定，不增设isActive过滤。514项（战斗267+关外247）通过，Unity退出0。完整ShopUI初始化、账号与图标/音频/上报提供者尚待生产连接，本次没有新Player构建。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameShopNativeProducts','--result','pass','--evidence','514 integrated checks; native ShopUI four product cards/buttons and actual currency/reward verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded514; full goal remains active.')
