from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==393
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='manager-pool-registration';s['validation'].update(integratedChecksPassed=393,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['manager-pool-registration']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type3467-26738.txt','disassembly/Type3467-26744.txt','disassembly/Type3467-26730.txt','disassembly/Type3467-26751.txt','data-manager-registration-roster.json','data-manager-registration-resolution.json','disassembly/Type3795-29619.txt','data-version-manager-resolution.json','data-manager-base-fields.json','disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json','original-sdk-storage.js','sdk-storage-source.json','storage-sdk-slot-candidates.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs','OutgameSdkStringStorage.cs','OutgameDataVersionStorage.cs','OutgameFileStorageBackend.cs','OutgameDataManagerPool.cs','OutgameManagerRegistrationCatalog.cs'],'scope':'Metadata v31 source roster of 25 derived manager classes: 16 Proj_hdzd, 5 CommonGameModule and 4 unmarked. Registration filters exact namespace, applies sync/compress flags, initializes before dictionary assignment. SaveData respects disable flag, skips null and logs individual failures before continuing. Concrete manager factories and live SDK remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original metadata manager roster and registration/save lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original metadata manager roster and registration/save lifecycle','checksPassed':393,'outgameChecksPassed':126,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Complete Assembly-CSharp DataManagerBase hierarchy inventory: 25 derived classes, 21 direct ModelRegister attributes with constructor args decoded from metadata v31. Namespace Proj_hdzd has16, CommonGameModule has5, four classes unmarked. All marked managers autoSyn=true and compressData=false. Registration f12652 initializes before dictionary set_Item; pool init resets save-disable and dictionary then upload queue. SaveData tests disable/dictionary rather than the separate ready flag, skips null and Debug.LogError logs individual failures while continuing. Runtime registry resource imported; concrete recovered manager factories remain pending.','source':['data-manager-registration-roster.json','data-manager-registration-resolution.json','disassembly/Type3467-26738.txt','disassembly/Type3467-26744.txt','disassembly/Type3467-26751.txt','disassembly/Type3464-26704.txt'],'implementation':['OutgameDataManagerPool.cs','OutgameManagerRegistrationCatalog.cs','Resources/Data/OutgameManagerRegistration.json'],'validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Implement concrete registered manager initialization/save/read and connect required factories; preserve original data keys.','Resolve CommonGameModule registration entry and active MineGameName initialization.','Implement UserLogin reload/upload/download and complete startup to menu.'];write(p,audit)
note='\n\n## 原始管理器注册表及保存生命周期（393项）\n按元数据v31解码ModelRegister属性并完整枚举Assembly-CSharp继承树：25类，16个Proj_hdzd、5个CommonGameModule、4个无标记，全部标记项同步=true、压缩=false。注册表加入Resources/Data/OutgameManagerRegistration.json。新增OutgameDataManagerPool：先赋标志并OnInit后登记，按原gameName筛选；初始化重置禁用及字典；保存跳过null，单项异常Debug.LogError后继续，并保持IsEnableSaveData查询与SaveData实际检查的区别。新增4项注册/异常/守卫/原元数据选择检查；393项（原267+关外126）通过，Unity退出0。实际管理器工厂及完整生产启动尚未接通，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameManagerPoolRegistration','--result','pass','--evidence','393 integrated checks; original metadata roster and manager pool lifecycle verified; concrete manager providers and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded393; full goal remains active.')
