from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==424
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='reward-video-lifecycle';s['validation'].update(integratedChecksPassed=424,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['reward-video-lifecycle']={'implementationReady': True, 'productionConnected': False, 'source': ['disassembly/Type9202-64456.txt', 'disassembly/Type9202-64478.txt', 'disassembly/Type9202-64480.txt', 'disassembly/Type9202-64481.txt', 'disassembly/Type9202-64482.txt', 'disassembly/Type9202-64484.txt', 'disassembly/Type9202-64487.txt', 'disassembly/Type9202-64491.txt', 'disassembly/Type9202-64492.txt'], 'implementation': ['OutgameRewardVideo.cs'], 'scope': 'ADModule ShowVideo filters, constructor Ready=true/LastClick=-1, callback replacement, first-day/no-ready failure, scaled10-second timeout, native show/close and string result callbacks restored. Host provides native delivery, coroutine scheduling and reports; complete adapter initialization/module activation and actual business reward integration pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original ADModule rewarded-video lifecycle and callbacks') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original ADModule rewarded-video lifecycle and callbacks','checksPassed':424,'outgameChecksPassed':157,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact': 'ADModule source ShowVideo replaces callback before filtering. Empty or1 ad_click_lock_enable selects showing lock; other values select strict realtime delta<1. Constructor sets Ready=true and LastClick=-1. Accepted request records showing/time before firstDayNoAd or not-ready failure. Native not-ready schedules scaled WaitForSeconds10 after canceling prior timer, then still calls showVideo and sends VideoAdShow. Shown(false) cancels timer/resets showing but retains callback; Closed resets showing then invokes current callback, clears it and emits close event. String1/0 invokes and clears only callback; -1 reports unknow and warns, unknown leaves callback; null callback logs empty. No callback-finally/once guard added; throwing recipients preserve source partial state. Actual native adapter/reward consumers remain pending.', 'source': ['disassembly/Type9202-64456.txt', 'disassembly/Type9202-64478.txt', 'disassembly/Type9202-64480.txt', 'disassembly/Type9202-64481.txt', 'disassembly/Type9202-64482.txt', 'disassembly/Type9202-64484.txt', 'disassembly/Type9202-64487.txt', 'disassembly/Type9202-64491.txt', 'disassembly/Type9202-64492.txt'], 'implementation': 'OutgameRewardVideo.cs', 'validation': 'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 激励广告请求与回调生命周期（424项）\n新增OutgameRewardVideo恢复ADModule：构造就绪true/点击时间-1，先替换回调再按在线参数选择播放锁或严格1秒防重；接受后先写状态/时间，首日禁广告或未就绪返回false。底层未准备好时取消旧计时并等待缩放时间10秒，仍发起原生请求；展示失败保留回调，关闭先复位再回调/清理/发事件。字符串1/0回调后清空，-1报告unknow保留等待，未知结果不发奖；异常部分更新保持。424项（原267+关外157）通过，Unity退出0；源方法1499。平台适配器初始化、实际原生广告与业务领奖链路尚待接通。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameRewardVideoLifecycle','--result','pass','--evidence','424 integrated checks; source rewarded-video request/callback ordering and failures verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded424; full goal remains active.')
