from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-skin-item-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==349
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='shop-equipment-listener';s['validation'].update(integratedChecksPassed=349,skinItemActionChecksPassed=15);s['nextActions']=['Finish PlayerControl cached model loading/show callback and source display roots.','Connect concrete shop effects with equipment listener and original lifecycle.','Complete account startup and remaining outgame systems; fresh playable build/end-to-end validation.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['shop-equipment-listener']={'implementationReady':True,'scope':'ShopUI ChooseSkin source event listener and category-card refresh; PlayerControl model consumer pending','rules':['Try soldier SkinConfig lookup; missing IDs return including scene IDs. Equip by config.skinType, reset first ad for that category, refresh same-category cards, then PlayerControl.ChangeSkinUse(type,id). No extra save, ownership gate or report.'],'source':['disassembly/Type4408-33772.txt'],'implementation':['OutgameShopEquipment.cs','OutgameShopSkinLists.cs'],'validation':'Real native card collection verifies previously-used and newly-used states before model callback and exact reset/refresh/model order.'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['sourceMethodsIndexed']=799;write(p,s)
write(o/'PLAYER_DISPLAY_AUDIT.json',{'status':'partial','confirmed':[{'fact':'ChangeSkinUse creates per-category cache dictionary if missing, then helper checks skinId key; absent loads model and always invokes display helper immediately; callback invokes it again after load.','source':['disassembly/Type4462-34205.txt','disassembly/Type4462-34197.txt']},{'fact':'LoadModel uses SkinConfig prefabId; category3 adds1000 and selects9034, other categories9033. Callback/placement semantics still require extraction.','source':['disassembly/Type4462-34194.txt']},{'fact':'InitFirstAdsItem(0) clears all3 fields; types1/2/3 clear corresponding single field; others no-op.','source':['disassembly/Type4462-34195.txt']}],'pending':['Display callback parent/transform/animation and pooled lifecycle','Source model roots/camera and actual prefab import coverage','Swipe/rotation continuous input behavior']})
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='ShopUI ChooseSkin listener') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Shop equipment source event listener and same-category refresh','checksPassed':349,'outgameChecksPassed':82,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Shop acquisition/payment/UI, complete account startup or playable lobby'};write(p,s)
note='\n\n## 商店装备事件联动（349项）\n新增OutgameShopEquipment：按原SkinConfig查找，写装备、重置该类别广告候选、刷新同类别所有卡片、请求展示模型，缺失/场景ID无动作；不加保存或所有权判断。真实卡片列表验证旧/新使用中状态在模型回调前一致更新。Unity退出0，349项检查（原267+关外82）。PlayerControl新增28个源方法索引，总799，缓存/加载/首广告重置证据写PLAYER_DISPLAY_AUDIT.json；模型加载完成回调、实际父节点/摄像机/动画与完整生产接线仍待完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
for name in ['unityCompile','outgameCommanderCore','outgameInventoryCore','outgameToolDispatchCore','outgameProfileStore','outgameMenuNavigation','outgameCommanderActions','outgameUiImport','outgameMenuView','outgameCommanderView','outgameLevelProgression','outgameOriginalLocalData','outgameOriginalCommanders','outgameSkinRecords','outgameSkinActions','outgameSkinItemActions','outgameSkinItemView','outgameSceneSkinActions','outgameSceneSkinView','outgameSkinOrder','outgameShopSkinLists','outgameShopTabs','outgameToggleBindings','outgameShopInitialSelection','outgameSkinPosters','outgameShopEquipment']:
 subprocess.run(b+['set-check']+a+['--name',name,'--result','pass','--evidence','349 integrated checks passed including skin item callbacks and isolated restart; full outgame incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded 349 checks; full goal remains incomplete.')
