from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==402
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='skin-storage-lifecycle';s['validation'].update(integratedChecksPassed=402,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['skin-storage-lifecycle']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4150-31728.txt','disassembly/Type4150-31729.txt','disassembly/Type4150-31732.txt','skin-serialization-fields.json','disassembly/Type4028-31008.txt','disassembly/Type4028-31009.txt','disassembly/Type4028-31010.txt','disassembly/Type4028-31012.txt','disassembly/Type3465-26715.txt','disassembly/Type3465-26712.txt','disassembly/Type3465-26713.txt','disassembly/Type3465-26714.txt','disassembly/Type3466-26721.txt','disassembly/Type3606-27869.txt','disassembly/Type3467-26738.txt','disassembly/Type3467-26744.txt','disassembly/Type3467-26730.txt','disassembly/Type3467-26751.txt','data-manager-registration-roster.json','data-manager-registration-resolution.json','disassembly/Type3795-29619.txt','data-version-manager-resolution.json','data-manager-base-fields.json','disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json','original-sdk-storage.js','sdk-storage-source.json','storage-sdk-slot-candidates.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs','OutgameSdkStringStorage.cs','OutgameDataVersionStorage.cs','OutgameFileStorageBackend.cs','OutgameDataManagerPool.cs','OutgameManagerRegistrationCatalog.cs','OutgameDataManagerStorage.cs','OutgameCommanderManager.cs','OutgameOriginalCommanders.cs','OutgameSkinManager.cs','OutgameSkinCatalog.cs'],'scope':'Concrete skin manager assigns instance before update, requests server callback or loads local, preserves source defaults/legacy behavior and saves through SDK. Metadata proves private s/u SerializeField and all other skin fields NonSerialized; source wire serializer emits only those fields, newSkins and equipment. Original configs/registry and isolated actual file restart verified. Full manager roster and production startup incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Concrete skin manager original wire fields and restart lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Concrete skin manager original wire fields and restart lifecycle','checksPassed':402,'outgameChecksPassed':135,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['confirmed'].append({'fact':'Concrete skin manager publishes instance before initial data update, requests server callback when required or loads local original key. Metadata field flags and custom attributes prove SkinData private s/u have SerializeField and skinType/sortNo/special/isNew/castType have NonSerialized. Dedicated source serializer excludes those transient fields while projecting newSkins and usedSkin through original PrepareSave. Held unknown skin records remain in serialized list. Legacy ownership migration neither saves nor changes equipment/new flags. Actual isolated file restart with source configs and ModelRegister selection verifies ownership/new/equipment. Required live account/provider connection remains pending.','source':['disassembly/Type4150-31728.txt','disassembly/Type4150-31729.txt','disassembly/Type4150-31732.txt','skin-serialization-fields.json'],'implementation':['OutgameSkinManager.cs','OutgameSkinCatalog.cs'],'validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Recover full original LocalData field serialization and lifecycle without dropping fields.','Connect local data and remaining registered manager providers.','Implement UserLogin reload/upload/download and complete startup to menu.'];write(p,audit)
note='\n\n## 皮肤管理器原格式存档与实际文件重载（402项）\n新增OutgameSkinManager接入注册接口、实例发布、服务器等待/本地读取、原迁移与统一保存。元数据证实SkinData私有s/u为SerializeField，另外5字段NonSerialized；OutgameSkinCatalog新增独立原格式序列化，避免将恢复侧运行时字段写入原存档，newSkins/usedSkin按原PrepareSave构造且保留未知持有记录。原配置/注册标记经Pool→SDK队列写入隔离实际文件，全新管理器恢复拥有/新标记/装备；迁移不自动保存或改装备得到验证。402项（原267+关外135）通过，Unity退出0。LocalData及其余管理器与完整生产启动仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSkinStorageLifecycle','--result','pass','--evidence','402 integrated checks; concrete skin lifecycle, source wire field fidelity and actual isolated restart verified; remaining managers and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded402; full goal remains active.')
