from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==451
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='serial-controller-lifecycle';s['validation'].update(integratedChecksPassed=451,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['serial-controller-lifecycle']={'implementationReady':True,'productionConnected':False,'source':['controller-request-slots.json','disassembly/Type7527-54996.txt','disassembly/Type7527-54997.txt','disassembly/Type7527-54998.txt'],'implementation':['OutgameSerialControllerLifecycle.cs'],'scope':'Serial close/reward/show-fail lifecycle restored using existing video controller and show flow. Host boundaries preserve timer report, interstitial chaining, preload load and banner restoration. Actual request/preload implementations and native wiring pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original serial controller close, reward and retry lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original serial controller close, reward and retry lifecycle','checksPassed':451,'outgameChecksPassed':184,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Controller slot5 resolves load and slot9 checkRequest. Shared function3370 in Serial close is stopVideoShowLoad metadata54994. OutgameSerialControllerLifecycle restores close callback before subsequent state/flag reads, timer reset, interstitial chain, video preload cancellation/cacheAmount update, load before banner restoration. ShowFail rechecks type/readiness after failure callback then retries showAd(false,true) or closes.451 checks pass; concrete hosts/native wiring pending.','source':['controller-request-slots.json','disassembly/Type7527-54996.txt','disassembly/Type7527-54998.txt'],'implementation':'OutgameSerialControllerLifecycle.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 串行控制器关闭、奖励与重试（451项）\n解析控制器slot5=load、slot9=checkRequest；Serial关闭中的共享3370为stopVideoShowLoad。新增OutgameSerialControllerLifecycle，连接现有视频控制器和show流程，保留业务回调先行、回调后重读isFromClose、插屏链、预加载停止及cacheAmount更新、load后恢复banner。showFail先回调true，再重读类型/就绪，重试showAd(false,true)。451项（战斗267+关外184）通过，Unity退出0，源码索引1710。Host边界下的实际预加载、报表和原生SDK仍待接入，整体目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSerialControllerLifecycle','--result','pass','--evidence','451 integrated checks; serial controller close/reward/retry callback ordering and failure boundaries verified; native/preload hosts incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded451; full goal remains active.')
