"""Record original TopInfo particle dependency closure and BigNumExtension formatting evidence."""
from pathlib import Path
import hashlib,json,struct
helper=Path(__file__).parent/'recover_outgame_manager_registry.py';c={'__file__':str(helper.resolve())};exec(helper.read_text().split('rows=[]')[0],c)
out=c['p']/'generated/outgame';index=json.loads((out/'method-map.json').read_text());selected={27611,27612,27613,33917,33922,33933}
methods=[dict(r,sha256=hashlib.sha256((out/r['path']).read_bytes()).hexdigest())for r in index if r['metadata']in selected];assert len(methods)==6
usages=[]
for a in [4103656,4039964,4040520,4034536]:
 v=c['u'](a);ix=(v&0x1ffffffe)>>1;assert v>>29==5;n,o=struct.unpack_from('<II',c['b'],c['pairs'][0][0]+8*ix);usages.append(dict(address=a,literal=c['b'][c['pairs'][1][0]+o:c['pairs'][1][0]+o+n].decode()))
snap=c['p']/'generated/resource-snapshots/top-info-effects-20261003';acq=json.loads((snap/'acquisition-manifest.json').read_text());prep=json.loads((snap/'prepared/native-import.json').read_text());roundtrip=json.loads((snap/'particle-roundtrip-validation.json').read_text());assert len(acq['items'])==11 and all(r['status']=='verified'for r in acq['items']) and roundtrip['passed'] and roundtrip['numericScalars']==9085
report=dict(status='original-top-info-effect-assets-and-number-format-restored-full-page-pending',metadataSha256=hashlib.sha256(c['b']).hexdigest(),memorySha256=hashlib.sha256(c['mem']).hexdigest(),methods=methods,usages=usages,snapshot=str(snap.relative_to(c['p'])),assetEvidence=dict(bundles=11,newAcquisitions=0,prefabs=prep['prefabs'],resources=prep['validation']['resources'],particleSystems=5,numericScalars=9085,roundtrip='particle-roundtrip-validation.json'),findings=[
 'BigNumExtension.SetBigNumSymbol27611 preserves dictionary enumeration order through copied Values list and First key. BigToString27612 warns with original literal before zero if list is null; returns empty after warning. Callback exception propagates. Formatting uses BigInteger.ToString current culture, source hundredths scale100 and literal decimal dot.',
 'Short branch uses raw.Length<=FirstMagnitude+2, PadLeft(2,0), decimal insertion two digits from right, then source first-four-character truncation or PadLeft(4,0). For raw length<=5 the loop overwrites a flag for each fractional character; only the last digit decides whether the entire fraction is dropped. Thus120 and150 both display1, while123 displays1.23. This source behavior is preserved, not rounded or corrected.',
 'Large branch divides BigInteger by100 then derives group from quotient digit count and FirstMagnitude, decrementing at exact boundaries. Only symbol index saturates at last list entry, while decimal placement uses the original group. Negative sign participates in raw length/string operations. Empty symbol list or zero magnitude preserve original exceptions; no fallback introduced.',
 'TopInfoUI33917/async33933 waits BaseUI.Await then shows1007 under imgIcon and1019 under imgDiamondIcon, retaining distinct IDs. Original33922 closes these IDs after removing two message listeners. These methods are source evidence for asset scope; full TopInfo lifecycle/account/auth disposal is not yet implemented by this milestone.',
 'OriginalEffectConfig1007 and1019 are type0 duration0; exact resources hdzd_effect_jinbiglow and hdzd_eff_Diamond02. Modern paths preserve case; legacy appends .prefab.unity3d to lowercase path while retaining original prefab name for bundle lookup. Native fixtures use existing real EffectModule/new helper/legacy cache/provider without changing module behavior.',
 'Both prefabs and their11 source bundle closure were already locally available and pass original directory size/MD5 and SHA256 verification. Seven original nodes, five particle systems, four materials/four textures and one builtin shader imported as editable assets. All9085 particle numeric scalar values/curves pass native Editor JSON readback tolerance; original native-reference identities checked by importer.',
 'Diamond root has a source-disabled ParticleSystemRenderer with null material; its three child renderers provide visuals. Gold child scale200 and diamond children scale150 remain intact; both roots have unit scale. Initial validation incorrectly required every renderer to have a material; corrected test to check enabled renderers and separately assert the original disabled-null root. No production asset modified for this test failure.',
 'Native validation first sampled before source particles emitted, then diagnosed the verification canvas placing UIRoot behind its camera because the canvas had not refreshed before original SetParent(worldPositionStays=true). The fixture now refreshes its camera canvas before calling the unchanged source root initialization and waits for actual particle emission. Initial reports and render diagnostics retained; no source particle timing/position/culling override introduced.',
 'Gold first live particle may still have zero visible alpha under the original curve. Native verification observes real successive frames until each currency effect independently contributes nonzero pixels, retaining its visible/hidden image pair at that frame. Gold/diamond pixel counts need not be from one simultaneous frame; timing/alpha/particle simulation are not overridden.',
 'Current-engine generated mipmaps derive from source decoded base texture; original compressed bytes remain preserved. Tests demonstrate native visible pixels and ownership/lifetime; they do not establish original screenshot/audio equivalence or full production resource acquisition.',
 'TopInfo full account/profile refresh, avatar authorization, page open/close ownership and UIControl production assembly remain pending, as do RankControl and MatchControl dependencies, Main/platform/all remaining business and final Player acceptance. Lifecycle controller matrix remains21/38.'
])
(out/'TOP_INFO_ASSETS_SOURCE_EVIDENCE.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(methods=len(methods),literals=len(usages),particleSystems=5,numericScalars=9085)))
