from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==418
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='preferences-webgl-storage';s['validation'].update(integratedChecksPassed=418,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['preferences-webgl-storage']={'implementationReady': True, 'productionConnected': False, 'source': ['disassembly/Type3622-28205.txt', 'disassembly/Type3622-28219.txt', 'disassembly/Type7703-56243.txt', 'disassembly/Type7703-56244.txt', 'disassembly/Type9254-64935.txt', 'disassembly/Type9254-64936.txt', 'storage-sdk-slot-candidates.json', 'sdk-storage-source.json'], 'implementation': ['OutgameWebGlFileStorage.cs', 'OutgameUserPreferences.cs', 'OutgameSdkStringStorage.cs', 'OutgameFileStorageBackend.cs'], 'scope': 'Original FileManager fixed-key read/write routes preferences into recovered SDK string cache/queue and actual isolated desktop backend. Read logging after retrieval and write logging before storage retained. Async failure leaves cache/digest/report state; changed records continue. Full application startup/platform ownership and real WeChat backend still incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original preferences through WebGL file routing and SDK queue') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original preferences through WebGL file routing and SDK queue','checksPassed':418,'outgameChecksPassed':151,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact': 'FileManager ReadWebGLFile/SaveWebGLFile call ISDK slots304/303 using unchanged keys; XYXCommon_DBT_ISDK forwards Bridge slots56/55; Bridge_WX_XYXFunction invokes WXBase string storage. UserData.txt is not game-name/UID-prefixed here. Connected original preferences through this routing and SDK queue into actual isolated desktop files. ReportSaveUserData happens after enqueue returns, before completion; failed backend write keeps SDK cache and preference MD5, so unchanged retry remains suppressed; changed record writes proceed. ISDK GetDaysByFirstLaunch default returns0, CanReadLocalData defaulttrue, XYXCommon ownership reads Bridge slot54; concrete complete hierarchy/selected platform day behavior still pending.', 'source': ['disassembly/Type3622-28205.txt', 'disassembly/Type3622-28219.txt', 'disassembly/Type7703-56243.txt', 'disassembly/Type7703-56244.txt', 'disassembly/Type9254-64935.txt', 'disassembly/Type9254-64936.txt', 'storage-sdk-slot-candidates.json', 'sdk-storage-source.json', 'sdk-day-initialization-slots.json'], 'implementation': 'OutgameWebGlFileStorage.cs', 'validation': 'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 偏好存档接通原WebGL文件与SDK队列（418项）\n新增OutgameWebGlFileStorage按FileManager→ISDK303/304→微信Bridge→WXBase字符串存储传递原键，确认UserData.txt不拼接游戏名或账号目录。通过CreatePreferences接通现有原格式偏好数据；读取日志发生在取值后、写入日志在入队前。实际隔离文件验证缓存即时可见/落盘前新实例不可见/完成后全新实例恢复；异步失败保留缓存与MD5，报告不等待落盘，未变内容不重试而新值可继续保存。418项（原267+关外151）通过，Unity退出0；源方法1301。平台初始化归属、具体SDK天数/完整应用入口仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgamePreferencesWebGlStorage','--result','pass','--evidence','418 integrated checks; source WebGL key routing and SDK queued actual isolated persistence verified; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded418; full goal remains active.')
