from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==412
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='prefab-cache-initialization';s['validation'].update(integratedChecksPassed=412,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['prefab-cache-initialization']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4117-31554.txt','disassembly/Type4117-31563.txt','disassembly/Type4117-31557.txt','startup-prefab-resolution.json','prefab-cache-resolution.json','prefab-cache-fields.json'],'implementation':['OutgamePrefabCache.cs','OutgameLevelEditorConfig.cs'],'scope':'Original dictionary cache initialization and selective actual Unity object destruction implemented. Source destroys roots 1000..6999 and 9033..9034, clears/removes corresponding pool lists, then removes root keys. InitData subsequently clears all three dictionaries and loads LevelEditor before disabling IsEditor. Required original resource loader and shared production cache wiring remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original prefab cache initialization and selective model root cleanup') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original prefab cache initialization and selective model root cleanup','checksPassed':412,'outgameChecksPassed':145,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'LoadPrefabControl InitData f11495 calls ClearModelEntityCache f4379, clears prefab/pool/root dictionaries in order, Resources.Load<LevelEditorCfg>(LevelEditor).IsEditor=false. ClearModelEntityCache selects IDs 1000..6999 or 9033/9034, destroys root GameObject before clearing/removing matching List<GameObject>, accumulates keys and removes them from root dictionary after enumeration. Other roots remain alive; InitData drops their cache references without destroying them. No null guards or transactional rollback added. Actual Unity objects validated using immediate destroy injection in editor; runtime defaults to original Object.Destroy. Production cache/resource routing still incomplete.','source':['startup-prefab-resolution.json','prefab-cache-resolution.json','prefab-cache-fields.json','disassembly/Type4117-31554.txt','disassembly/Type4117-31563.txt'],'implementation':'OutgamePrefabCache.cs','validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Restore ProcedureStarGame.OnEnter video mapping/events/daily checks and connect shared prefab caches/resource loader.','Connect production menu/reward/loading/resource/activity providers to OutgameStartupEntry.','Complete remaining data managers/login synchronization and verify actual player end-to-end.'];write(p,audit)
note='\n\n## 原始模型缓存初始化与实际对象清理（412项）\n新增OutgamePrefabCache还原LoadPrefabControl：ClearModelEntityCache仅销毁1000..6999及9033/9034编号模型根，先Destroy后清空并移除对应对象列表，最后集中移除根索引；保留其他编号实际对象。InitData随后清空三份字典，加载LevelEditor并仅关闭IsEditor。Unity实际对象验证覆盖边界、子对象销毁、外部列表引用、重复调用、缺资源及null列表的部分更新顺序。412项（原267+关外145）通过，Unity退出0；源方法索引1232。共享缓存/原资源生产接线、OnEnter前置与完整关外仍未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgamePrefabCacheInitialization','--result','pass','--evidence','412 integrated checks; source prefab cache lifecycle verified with actual Unity objects and required resource loader; production startup and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded412; full goal remains active.')
