from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==504
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-product-updates';s['validation'].update(integratedChecksPassed=504,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-product-updates']={'implementationReady':True,'productionConnected':False,'source':['global-item-update-generics.json','product-config-fields.json','disassembly/Type4542-34584.txt','disassembly/Type4542-34582.txt','disassembly/Type4542-34585.txt','disassembly/Type4542-34569.txt'],'implementation':['OutgameProductUpdates.cs','OutgameGlobalItemLifecycle.cs'],'scope':'Source per-frame host Update, strict >1 second product pass, DayOfYear comparison, interval/hour/weekday schedule math with original overflow/invalid calendar behavior. Concrete reset-price-notification engine remains an injected required dependency.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original global product scheduling') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original global product scheduling','checksPassed':504,'outgameChecksPassed':237,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'GlobalItemManager.Update accumulates deltaTime, only when >1 subtracts1 once and compares DayOfYear. Iterates live product Values; buyLimit1 resets on different day,3 interval,4 hours,5 weekdays. Always calls IItemManager.Update slot0 after successful pass/every sub-threshold frame. Hour rollover uses invalid-at-month-end day+1 constructor; weekdays use AddDays.504 checks pass.','source':['global-item-update-generics.json','product-config-fields.json','disassembly/Type4542-34584.txt','disassembly/Type4542-34582.txt','disassembly/Type4542-34585.txt','disassembly/Type4542-34569.txt'],'implementation':['OutgameProductUpdates.cs','OutgameGlobalItemLifecycle.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='lifecycle_and_product_scheduling_implemented_reset_rewards_provider_pending';audit['productUpdateImplementation']={'files':['OutgameProductUpdates.cs','OutgameGlobalItemLifecycle.cs'],'checks':504,'source':['global-item-update-generics.json','product-config-fields.json'],'detail':'Original update schedule, interval catchup without multiple grants, hours/weekdays, strict boundary, overflow and month-end exception preserved. Lifecycle overload registers actual scheduler. Reset engine and IItemManager.Update implementation still dependencies.'};audit['pending']=['Implement UpdateProductBuyLimit including purchase counters, UpdateConsumeItemPrice and UI notifications','Implement reward side effects and statistics bus production host','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 商品定时更新（504项）\n新增OutgameProductUpdates并由生命周期构造入口注册。原Update累计deltaTime严格大于1才处理，每帧仅减1；仅比较DayOfYear。buyLimit1跨日刷新，3间隔、4指定小时、5星期调度，完成后及未过阈值帧调用IItemManager.Update。保留间隔Int32乘1000溢出、严格时间边界、仅一次补刷新、空参数先访问异常、小时模式day+1月底异常以及星期AddDays跨月。504项（战斗267+关外237）通过，Unity退出0。购买计数重置/价格重算/UI消息仍是待补齐的必需回调，生产Provider未连接。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameProductUpdates','--result','pass','--evidence','504 integrated checks; source frame/day/interval/hour/weekday scheduling and original boundary failures verified; reset-price engine and production provider pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded504; full goal remains active.')
