"""Record TopInfoUI4425 lifecycle/account/auth order and BaseUI ready predicate from original bodies."""
from pathlib import Path
import json,hashlib,struct
helper=Path(__file__).parent/'recover_outgame_manager_registry.py';c={'__file__':str(helper.resolve())};exec(helper.read_text().split('rows=[]')[0],c)
out=c['p']/'generated/outgame';index=json.loads((out/'method-map.json').read_text());selected=set(range(33916,33935))|{27335,27340,27361,27362,27612}
methods=[dict(r,sha256=hashlib.sha256((out/r['path']).read_bytes()).hexdigest())for r in index if r['metadata']in selected];assert len(methods)==24
fields=[]
for owner in [4425,4424,4127]:
 for k in range(c['ts'][owner][18]):
  name,typ,tok=struct.unpack_from('<3i',c['b'],c['pairs'][11][0]+12*(c['ts'][owner][8]+k));ptr=c['u'](200288+4*typ);fields.append(dict(owner=owner,name=c['ms'](name),typeIndex=typ,typeKind=(c['u'](ptr+4)>>16)&255,typeData=c['u'](ptr),offset=c['u'](c['u'](3823136+4*owner)+4*k)))
assert len([r for r in fields if r['owner']==4127])==11
usages=[]
for address in [3995120,3953584,3953520,3953472,4061088,4045372,4079552,4054884]:
 v=c['u'](address);kind=v>>29;ix=(v&0x1ffffffe)>>1;r=dict(address=address,kind=kind,index=ix)
 if kind==6:
  spec=struct.unpack_from('<3i',c['mem'],483008+12*ix);m=c['md'][spec[0]];r.update(spec=list(spec),sourceClass=c['ms'](c['ts'][m[1]][0]),method=c['ms'](m[0]))
 elif kind==5:
  n,o=struct.unpack_from('<II',c['b'],c['pairs'][0][0]+8*ix);r['literal']=c['b'][c['pairs'][1][0]+o:c['pairs'][1][0]+o+n].decode()
 usages.append(r)
report=dict(status='original-top-info-owned-page-account-auth-flow-restored-required-platform-rank-match-ports-pending',metadataSha256=hashlib.sha256(c['b']).hexdigest(),memorySha256=hashlib.sha256(c['mem']).hexdigest(),methods=methods,fields=fields,usages=usages,externalCalls=[dict(table=64394,name='WXAvatar.get_Instance'),dict(table=64396,name='WXAvatar.GetMyAvatarURl'),dict(table=64398,name='WXAvatar.GetAvatar'),dict(table=25239,name='UserDataPrefs.OnSave'),dict(table=24598,name='DataManagerPool.SaveData')],findings=[
 'TopInfoUI ctor33929 initializes gold/diamond effect IDs to-1 and source layer2/open0/close0. All25 original UIOutlet bindings are attached using preserved source object/sibling mappings. Existing root-only constructor remains for earlier scoped presentation fixtures; owned constructor adds actual BaseUI modern/legacy load and asynchronous close hosts.',
 'Awake33924 registers LoadStartingUI then Avatar_Refresh_OnAuth, captures LocalDataManager4119 once from data pool, replaces two GameObject profile pointer delegates, hides stamina, finds profile imgRed, enables normal user/hides Match user, RefreshInfo then async icons then RefreshProfile. Virtual Refresh33930 is empty. OpenLater33920 only constructs currency/stamina dictionaries and adds Canvas/GraphicRaycaster with source layer, without invoking base OpenLater.',
 'RefreshInfo33921 has Unity-null GoldText and managed-null LocalData guard; captures Text before reading current local record. Diamond text has no independent null guard. LocalDataManager reference stays captured while its current account inventory projection can be replaced by the existing server callback. Actual account Tools.RefreshTopInfo callback reaches the owned page; source refreshTop flag must be true. Initial test accidentally supplied false and was corrected; dispatcher behavior unchanged.',
 'RefreshProfile33927 captures name Text, resolves current UserInfo, then separately captures red and current name before language You lookup. Score Text is captured before reading RankControl.CurPlayerScore BigInteger value, passed to recovered BigNumExtension. Headport config uses icon/atlas offsets12/16; HeadBox uses12/20. Both sprite calls use mode0; null config skips only its own call. Rank score and general sprite acquisition remain required services, not invented domain rules.',
 'BaseUI.Await27335/27361 yields new WaitUntil(predicate27340). Predicate emits GF_LoadUIOver with page identity whenever Transform is Unity-nonnull, even if disposed, then returns true even if callback destroys it. Otherwise rereads Transform or IsDisposed. This does not wait for OpenLater/animation and adds no cancellation gate. Native coroutine wait is default, controlled wait is test-only.',
 'Icons33917/33933 await original readiness then resolve effect module separately for Show1007 under GoldIcon and Show1019 under DiamondIcon, writing each result after return. First success/second failure retains first new ID and old diamond ID. Repeated direct calls do not close old effects. Pending continuation after direct Dispose can still create effects as original.',
 'Auth33918 returns only for null/zero-length argument array, evaluates args0.ToString then args1.ToString before checking emptiness; length1/null elements retain failures. Arguments are gates, not account values. Current MatchPlayerData4127.isGetWechatInfo offset48 is set first; nickname target captured before WXAvatar.GetMyNickName then assigned field12. New current player target captured before GetMyAvatarURl then assigned field16. Subsequent URL checks, avatar provider acquisition and current URL lookup retain original order.',
 'Avatar download callback33926 assigns held WeChat Image sprite directly, with no disposed guard. After download request, MatchName Text is captured before current player name lookup, then UserDataPrefs.OnSave precedes entire DataManagerPool.SaveData. Exceptions retain previous writes and suppress later operations. IOutgameMatchPlayerInfo is an explicit live projection contract, not a replacement persisted Match record; actual MatchManager/WXAvatar/UserDataPrefs implementations remain pending.',
 'Both profile GameObject pointer handlers33923 request UserInfoUI with empty args and no button audio/global button message. Full UserInfoUI destination is a required endpoint pending its restoration. TopInfo Dispose33922 removes both listeners then separately resolves effect module and closes gold then diamond. It does not call base.Dispose, reset IDs, clear object dictionary/arguments/native references, or remove button delegates. Standard close still marks disposed/destroys root/releases main and dynamic resources in original order.',
 'Integrated tests share actual account LocalData/Items/Tool, UserInfoManager/controller, config, data pool/storage, source effect module and real UIControl lazy currency cache. Native fixture drives real open/await/OpenLater/close, original sprites/particles, native pointer event, explicit supplied authorization callback, then independent file-backed account/UserInfo restart. Test Match projection, Rank score, platform/avatar callbacks/UserDataPrefs and UserInfoUI destination are explicitly fixture endpoints; no platform success or Match persistence is inferred.',
 'Full production resource catalog/Main/SDK/login/Match/Rank/UserInfoUI and remaining17 controller/all business/final Player/original audiovisual acceptance remain pending. Lifecycle matrix stays21/38. Current source project version remains6000.0.68f1; verification uses isolated6000.3.7f1.'
])
(out/'TOP_INFO_PAGE_SOURCE_EVIDENCE.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps(dict(methods=len(methods),fields=len(fields),usages=len(usages),indexed=len(index))))
