from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==470
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='video-controller-initialization';s['validation'].update(integratedChecksPassed=470,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['video-controller-initialization']={'implementationReady':True,'productionConnected':False,'source':['VIDEO_CONTROLLER_INITIALIZATION_AUDIT.json','disassembly/Type7544-55066.txt','disassembly/Type7511-54876.txt','disassembly/Type7511-54865.txt'],'implementation':['OutgameAdPlatformList.cs','OutgameVideoController.cs','OutgameAdShowFlow.cs'],'scope':'Source VIDEO branch is confirmed serial/cache1. Runtime implements post-publication bind/bidding/delay-load order, source constructor defaults and lazy adapter list creation. Original production config, factory, adapter init/canRequest and setAdz binding pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original video initialization and lazy platform adapter construction') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original video initialization and lazy platform adapter construction','checksPassed':470,'outgameChecksPassed':203,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Original NewAdsManager VIDEO branch selects SerialVideoController, sets cache1 before setAdz, then bidding and conditionally immediate load using global NewAdsRequestDelayEnable. Runtime implements this post-publication order and lazy platform list behavior. Source constructor defaults corrected: cache1/videoShowTime-1/DAU- prefix.470 integrated checks pass; effective remote config and full production init remain pending.','source':['VIDEO_CONTROLLER_INITIALIZATION_AUDIT.json','disassembly/Type7544-55066.txt','disassembly/Type7511-54865.txt'],'implementation':['OutgameVideoController.cs','OutgameAdPlatformList.cs','OutgameAdShowFlow.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 视频控制器初始化与惰性平台列表（470项）\n原包NewAdsManager VIDEO分支确认直接选择SerialVideoController并覆盖cacheAmount=1，先setAdz后bidding，NewAdsRequestDelayEnable为false时立即load。补充InitializeSerial初始化顺序与OutgameAdPlatformList：空列表每次重建，非空列表保留，INTERSTITAL变体归一，factory非空后init再canRequest。修正源构造默认cache1/videoShowTime-1/DAU-日志前缀；4个旧用例只调整已确认的日志前缀断言。470项（战斗267+关外203）通过，Unity退出0。完整配置解析、工厂、adapter init/canRequest和生产setAdz仍待完成，远端实际配置未知，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameVideoControllerInitialization','--result','pass','--evidence','470 integrated checks; source constructor defaults, VIDEO serial init ordering and lazy adapter list verified; production configuration and platform factory pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded470; full goal remains active.')
