from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==405
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='local-storage-lifecycle';s['validation'].update(integratedChecksPassed=405,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['local-storage-lifecycle']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4119-31618.txt','disassembly/Type4119-31628.txt','disassembly/Type4119-31630.txt','disassembly/Type4119-31632.txt','disassembly/Type3534-27293.txt','local-data-serialization-schema.json','local-limited-bag-resolution.json','disassembly/Type4150-31728.txt','disassembly/Type4150-31729.txt','disassembly/Type4150-31732.txt','skin-serialization-fields.json','disassembly/Type4028-31008.txt','disassembly/Type4028-31009.txt','disassembly/Type4028-31010.txt','disassembly/Type4028-31012.txt','disassembly/Type3465-26715.txt','disassembly/Type3465-26712.txt','disassembly/Type3465-26713.txt','disassembly/Type3465-26714.txt','disassembly/Type3466-26721.txt','disassembly/Type3606-27869.txt','disassembly/Type3467-26738.txt','disassembly/Type3467-26744.txt','disassembly/Type3467-26730.txt','disassembly/Type3467-26751.txt','data-manager-registration-roster.json','data-manager-registration-resolution.json','disassembly/Type3795-29619.txt','data-version-manager-resolution.json','data-manager-base-fields.json','disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json','original-sdk-storage.js','sdk-storage-source.json','storage-sdk-slot-candidates.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs','OutgameSdkStringStorage.cs','OutgameDataVersionStorage.cs','OutgameFileStorageBackend.cs','OutgameDataManagerPool.cs','OutgameManagerRegistrationCatalog.cs','OutgameDataManagerStorage.cs','OutgameCommanderManager.cs','OutgameOriginalCommanders.cs','OutgameSkinManager.cs','OutgameSkinCatalog.cs','OutgameLocalRecord.cs','OutgameLocalDataManager.cs'],'scope':'Concrete local data manager preserves all18 serialized LocalData fields plus nested records, source season_pass1, bag initialization before tools/legacy/save registration and original OnSave projection. Limited bags require active GameProductConfig row and strictly future expiry using original 1970-01-01 08:00 millisecond epoch. Actual isolated file restart and int64 precision verified. DataManagerSave host, full roster and startup remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Concrete LocalData serialized schema and limited bag restart lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Concrete LocalData serialized schema and limited bag restart lifecycle','checksPassed':405,'outgameChecksPassed':138,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Full source LocalData metadata has19 fields,18 serialized; dailyChallengeData is NonSerialized. Source ctor initializes nested/list fields and season_pass1 without setting LevelID1. Local manager initializes limited bags before tools/legacy/register-save callback, and prepares limited bag list before source JSON storage. Bag filtering uses GameProductConfig[id=ItemBagId].isActive==1, converts long milliseconds from fixed TimeModule epoch 1970-01-01 08:00 unspecified, skips zero or expiry<=DateTime.Now, and Dictionary.Add retains duplicate failure. Held bag isActive flag does not filter. Local record retains byte flags, first-charge int64, jump/purchased/season/group/daily fields across actual isolated file restart. Required DataManagerSave registration provider remains pending.','source':['local-data-serialization-schema.json','local-limited-bag-resolution.json','disassembly/Type4119-31618.txt','disassembly/Type4119-31628.txt','disassembly/Type4119-31630.txt','disassembly/Type4119-31632.txt','disassembly/Type3534-27293.txt'],'implementation':['OutgameLocalRecord.cs','OutgameLocalDataManager.cs'],'validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Recover DataManagerSave.RegisterSaveData and connect registration provider.','Connect source commander/skin/local managers together with remaining roster and login providers.','Implement UserLogin reload/upload/download and complete startup to menu.'];write(p,audit)
note='\n\n## 本地数据完整序列化与限时礼包（405项）\n新增OutgameLocalRecord，覆盖原LocalData全部18个序列化字段及首充/跳关/礼包嵌套结构；第19个dailyChallengeData原标记NonSerialized不写入。新增LocalDataManager对接原读取、限时礼包→道具→旧迁移→RegisterSaveData顺序与统一保存。限时礼包原规则：GameProductConfig存在且isActive==1，非零时间以1970-01-01 08:00固定起点加毫秒且严格晚于DateTime.Now；保存从有效字典重建列表，保留Add重复键异常。原商品配置已导入。测试覆盖完整字段/int64精度、时限等号/零值/无效商品/重复键，以及实际隔离文件重载进度/货币/首充/购买/礼包。405项（原267+关外138）通过，Unity退出0。DataManagerSave注册provider、其余管理器和完整启动仍待接通，整体未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameLocalStorageLifecycle','--result','pass','--evidence','405 integrated checks; full local serialized schema, limited bag rules and actual isolated restart verified; remaining providers and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded405; full goal remains active.')
