from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==534 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type4408-33786.txt','disassembly/Type4408-33773.txt','shop-dispose-generics.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='shop-page-lifecycle';s['validation'].update(integratedChecksPassed=534,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['shop-page-lifecycle']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameShopLifecycle.cs'],'scope':'ShopUI OpenLater/Dispose event integration, actual native ToolChange label refresh, video callback registration, initialization coroutine stop and SelectCardControl access restored. Full account/menu invocation and original message/video hosts pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Object<T> shared source wrapper') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original pooled object count/lifecycle wrapper','checksPassed':534,'outgameChecksPassed':267,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'freshPlayModeRun':False,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'shop_lifecycle_binding_verified_production_entry_pending','source':sources,'verified':['OpenLater registers ChooseSkin, ChooseSoldier, ValnetineStatueChanged and ToolChange in source order','Gold then diamond video completion delegates point at recovered feedback handlers','Dispose removes same four listener delegates in source order; no video delegate removal','Non-null saved initialization coroutine stopped without clearing field; SelectCardControl singleton then accessed','Original ShopUI prefab ToolChange updates tool-value label through lifecycle registration'],'remaining':['Original MsgDispatcher and UIVideoBtn concrete host bindings','Shop initialization coroutine and page visibility sequencing','Connect real login/account/menu ownership without fixture defaults','Full product/skin purchase and persistence E2E'],'checks':534,'priorPlaymodeChecks':8,'dynamicScope':'Native page exercised by integrated editor checks; prior8 fly Play Mode checks not rerun this turn'}
write(o/'SHOP_PAGE_LIFECYCLE_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'ShopUI OpenLater/Dispose event binding restored and original prefab feedback label verified. Source lifecycle owner/message/video host integration still pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## ShopUI页面生命周期连接（534项）\n核对运行脚本发现商品/奖励部件尚缺页面事件连接，新增OutgameShopLifecycle恢复OpenLater33786注册顺序：ChooseSkin、ChooseSoldier、ValnetineStatueChanged、ToolChange、金币视频、钻石视频。Dispose33773按序退订四消息，停止非空初始化协程但不清字段，最后访问SelectCardControl（泛型解析确认）。实际原ShopUI预制体已验证事件驱动ToolValue文本更新及回调身份。534项集成通过，Unity退出0；此前8项飞币动态报告保留不作为本轮页面端到端证明。原MsgDispatcher/UIVideoBtn宿主、初始化可见生命周期与真实账号菜单入口仍未连接完整，目标继续。\n' 
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameShopPageLifecycle','--result','pass','--evidence','534 integrated checks and8 independent actual Play Mode checks; complete pool and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded534; full goal active.')
