from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
r=read(W/'analysis/unity-integrated-validation.json');assert r['passed'] and len(r['checks'])==711
native=read(W/'analysis/game-controller-native-validation.json');assert native['passed'] and len(native['checks'])==7
assert (W/'analysis/game-controller-native-validation.json').stat().st_mtime>(W/'UnityProject/Assets/AreaBattle/Scripts/OutgameGameControl.cs').stat().st_mtime
v={'atUtc':now,'scope':'GameControl concrete lifecycle/shared scene state, original GameSceneMono references, native texture/effect reuse and deferred unlock-model destruction','checksPassed':711,'nativePlayModeChecks':7,'freshPlayModeRun':True,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Original resource transport, battle asset11001 acquisition, remaining31 controller lifecycles, full Main/account/menu composition or complete playable outgame','commands':['prepare_outgame_model_roots.py','OutgameModelRootsImporter.ImportBatch','BattleBuild.ValidateMechanicsOnly','OutgameGamePlayModeValidation.Run']}
a={'atUtc':now,'status':'partial-subsystem','sourceEvidence':'GAME_CONTROLLER_FIELD_EVIDENCE.json','controllerType':4064,'productionFiles':['OutgameGameControl.cs','OutgameGameSceneMono.cs','OutgameCoreControllerBindings.cs'],'sceneImport':{'manifest':'model-roots.json','selectedNodes':21,'cameras':4,'sourceComponent':'generated/unity-assets/MonoBehaviour/unnamed__BuildPlayer-GamePlay__59.json','scope':'All17 GameSceneMono serialized references; selected ancestor transforms in original sibling order. Unreferenced scene children not claimed.'},'findings':['Metadata resolves arr_homeGroud as Texture2D[], correcting earlier handoff GameObject[] statement. Original OnInit clears UseAnimationIns first, then allocates by dicSceneSkin.Count.','GameControl now owns shared current scene id, home texture array, game sprite dictionary(capacity10), lazy effect dictionary, native root and camera references. OnDispose only clears registry slot4064.','InitScene finds first Tag10 object named objSceneRoot, copies four camera references, activates game root, applies source screen/aspect adjustment and selects current skin. Missing/repeated initialization retains source partial state semantics.','Original soldierRoot child1 is model backdrop; source sibling order restored during import. Preview component remains separately available to prior callers.','Home texture callback stores captured array index but applies effect for current selection. LoadGameScene sets same current id used by home path; same-id home selection is skipped.','Battle background LoadAsset11001 callback parents/normalizes object and GetComponentInChildren<SpriteRenderer>. Sprite.Create uses full texture rect, pivot0.5, default100PPU. Completion caches under current id, preserving duplicate Dictionary.Add failures.','Effect cache keys are current id plus0 or100. Cached effects reactivate without reparenting; callback sets parent/active, initializes Spine animation and then Dictionary.Add.','Home and game camera/root activation sequences, source MoveCamera comparison against home world position, and SetCameraSize baseline vector(0.25,0,0.4) retained.','ClearRenderModel destroys unlock-root children in reverse order using deferred native Destroy. Native validation confirms next-frame removal and retained scene on disposal.'],'verification':v,'remaining':['Connect IOutgameGameSceneResources to recovered LoadPrefabControl loading/cache service and actual battle asset11001. Current native test uses synchronous recovered texture/effect adapters.','Wire GameControl into full Main and LevelControl/PlayerControl state transitions.','Complete all remaining31 controller lifecycles and full outgame objective; no final acceptance or Player build.']}
write(O/'GAME_CONTROLLER_NATIVE_AUDIT.json',a)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d['atUtc']=now
if 4064 not in d['implementedControllerTypes']:d['implementedControllerTypes'].append(4064)
d['remainingControllerCount']=31;d['implementations']['4064']='OutgameGameControl.cs';d['gameControllerAudit']='GAME_CONTROLLER_NATIVE_AUDIT.json';d['verification']=v;d['sourceMethods']=list(dict.fromkeys(d['sourceMethods']+list(range(31254,31278))));d['remaining'][0]='Restore and bind remaining31 controllers including Level/Player/LoadPrefab/PVP/Arena/Rank/Dice, and connect concrete UI/game resource dependencies.';write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='game-controller-native-scene-binding',gameControllerNativeAudit='generated/outgame/GAME_CONTROLLER_NATIVE_AUDIT.json',nextPriority='Restore LevelControl4107 initialization/update/state and PlayerControl4462, plus LoadPrefabControl resource service for UI/game owners. Remaining31 lifecycle controllers. Connect full Main/account/menu production entry and run complete persistence/return/failure/Player acceptance; preserve all other outgame scope.')
d['validation']['integratedChecksPassed']=711;d['validation']['gameController']=v;d['validation']['gameControllerNative']=native;d['milestones'].append({'id':'game-controller-native-scene-binding','atUtc':now,'status':'partial-subsystem','integratedChecks':711,'nativeChecks':7,'remainingControllers':31});write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=711,latestValidation=v);d['validationHistory'].append(v)
if 'analysis/game-controller-native-validation.json' not in d['reports']:d['reports'].append('analysis/game-controller-native-validation.json')
files=[p for p in (W/'UnityProject/Assets/AreaBattle').rglob('*') if p.is_file() and (p.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas') or '/FirstPack/' in p.as_posix())]
d['sourceFingerprints']=[{'path':p.relative_to(W).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files)];write(p,d)
text='\n\n## 2026-09-30 GameControl 原生场景共享状态增量\n- GameControl4064 生命周期、InitScene/皮肤与背景加载完成/相机与特效切换/模型清理已实现；与注册器绑定。生命周期7/38，剩31；这不代表完整关外已完成。\n- 纠正旧交接：arr_homeGroud 元素类型是 Texture2D，不是 GameObject。当前场景id由主页/战斗共享，纹理回调保留源码捕获索引与当前id的不同读取时机。\n- 从原GameSceneMono59序列化引用补齐4相机、17字段和21个选中节点，恢复兄弟顺序，使soldierRoot.GetChild(1)对应原模型背景。\n- 集成711项通过；Game原生PlayMode7项通过（原场景引用、原皮肤7/8/9特效复用、回主页、下一帧销毁）。当前资源验证使用本地同步适配器，LoadPrefabControl/11001真实加载仍待接。\n- 审计 O/GAME_CONTROLLER_NATIVE_AUDIT.json 与 GAME_CONTROLLER_FIELD_EVIDENCE.json；日志 analysis/game-control-integrated.log、analysis/game-controller-native.log。\n- 下一步 LevelControl4107/PlayerControl4462与资源控制器；仍需完整Main/account/menu接线、所有关外系统闭环和新Player构建验收。\n'
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('705 项 checks','711 项 checks').replace('caseCount=705；latestValidation 为 UIControl + native TopInfo/MenuTab','caseCount=711；latestValidation 为 GameControl + native scene').replace('6控制器生命周期/共享绑定已实现并验证，剩32','7控制器生命周期/共享绑定已实现并验证，剩31')
s=s.replace('最新集成日志 analysis/ui-controller-integrated.log；UI原生日志 analysis/ui-native-rendered-playmode.log。705集成+6UI原生通过；历史五控制器原生10项通过。无本任务待续进程。','最新集成日志 analysis/game-control-integrated.log；Game原生日志 analysis/game-controller-native.log。711集成+7Game原生通过；历史UI原生6项及五控制器原生10项通过。无本任务待续进程。');s+=text;p.write_text(s,encoding='utf8')
print(json.dumps({'checks':711,'native':7,'fingerprints':len(files),'remainingControllers':31}))
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 r=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert r.returncode==0,r.stderr
r=subprocess.run(base+['set-check']+common+['--name','outgameGameControllerNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/GAME_CONTROLLER_NATIVE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert r.returncode==0,r.stderr
print('Orchestration evidence recorded')
