from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');play=read(w/'analysis/outgame-fly-playmode-validation.json')
assert r['passed'] and len(r['checks'])==547 and v['passed'] and play['passed'] and len(play['checks'])==8
sources=['disassembly/Type10741-'+str(i)+'.txt' for i in range(74403,74432)]+['disassembly/Type10740-74434.txt','video-button-generics.json','video-button-virtual-slots.json','ui-import.json','video-manager-generics.json']
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='shop-prefab-video';s['validation'].update(integratedChecksPassed=547,loginSyncChecksPassed=len(v['checks']));write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['shop-prefab-video']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameShopVideoBindings.cs','OutgameVideoButton.cs','RecoveredHudImporter.cs','Recovered/Outgame/ShopUI.prefab'],'scope':'All five original ShopUI UIVideoBtn components imported with original IDs/graphic/selection fields. Shop binding joins source pointer event to video host, completion, inventory and saving through recovered lifecycle. Actual SDK/config/account composition remains pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original ShopUI serialized video components and UIVideoBtn source') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original ShopUI video component import and pointer-to-reward integration with SDK fixture','checksPassed':547,'outgameChecksPassed':280,'freshPlayerBuild':False,'freshPlayerSmoke':False,'playModeReport':'analysis/outgame-fly-playmode-validation.json','playModeChecksPassed':8,'freshPlayModeRun':False,'notClaimed':'Complete pooling, production account or full lobby'};write(p,s)
audit={'status':'shop_prefab_video_chain_verified_actual_sdk_pending','source':sources,'verified':['All five original ShopUI UIVideoBtn components imported as native restored Button subclass','Original videoIDs1001/1006/1001/1002/1002, auto-show, colors, navigation, animation triggers and targetGraphic retained','Importer explicitly rejects unsupported persistent video button callbacks; all five source events are empty','OutgameShopVideoBindings binds before activation and registers lifecycle gold/diamond completion callbacks','Original prefab pointer event passes videoID1001 to explicit SDK fixture, grants nothing before completion or on failure, grants50gold with notify/report/save on success','VideoBtnManager four methods extracted; ConfigRead<VideoBtnData> and dictionary generic bindings resolved'],'remaining':['Concrete VideoBtnManager configuration loader and original JSON binding','Actual SDK/report host and production account/menu owner','Fresh PlayMode evidence for new Button lifecycle','Full persistence/build/E2E'],'checks':547,'priorPlaymodeChecks':8,'dynamicScope':'Real prefab/native Button in integrated editor test with explicit SDK fixture; prior fly PlayMode not rerun'}
write(o/'SHOP_PREFAB_VIDEO_AUDIT.json',audit)
p=o/'ACCOUNT_STARTUP_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Original ShopUI now imports five native video buttons. Inactive-page binding connects actual prefab pointer events through video host/lifecycle to inventory and saving. SDK fixture remains explicit; production account/config/platform host pending.','source':sources,'validation':['analysis/outgame-login-sync-validation.json','analysis/outgame-fly-playmode-validation.json']});write(p,s)
note='\n\n## 商店原预制体视频按钮接入（547项）\n更新共用导入器识别UIVideoBtn，ShopUI五个原视频组件保留ID、自动上报标记、Selectable颜色/导航、动画trigger及targetGraphic；原persistent onClick均为空，不支持的非空事件会显式拒绝。重导入关外四页面成功。新增OutgameShopVideoBindings在激活前绑定SDK宿主，并将原金币/钻石回调接入商店生命周期。实际ShopUI指针点击传出videoID1001，失败/未完成不发奖，成功50金币并通知/上报/存档。547项集成通过，Unity退出0。提取VideoBtnManager四方法，索引2189，解析ConfigRead<VideoBtnData>及字典调用；真实配置解析、SDK/账号入口仍待完成。此前8项飞币PlayMode未重跑，本轮SDK结果明确为fixture。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameShopPrefabVideo','--result','pass','--evidence','547 integrated checks; prior8 PlayMode checks not rerun. Actual config/SDK/account composition and production flows pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded547; full goal active.')
