from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==506
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-product-resets';s['validation'].update(integratedChecksPassed=506,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-product-resets']={'implementationReady':True,'productionConnected':False,'source':['product-reset-generics.json','product-buy-count-evidence.json','disassembly/Type4542-34595.txt','disassembly/Type4542-34574.txt'],'implementation':['OutgameProductResets.cs','OutgameItemRecords.cs'],'scope':'Original reset mode branches, price callback order, dirty and snapshot behavior, UI messages; corrected nested ProductBuyCount wire shape. Concrete price formulas and production host pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original product resets and nested purchase records') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original product resets and nested purchase records','checksPassed':506,'outgameChecksPassed':239,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'HaveBuyCounts generic is List<ProductBuyCount>, with key:Int32 and buyCount:List<ItemGetTypeBuyCount>; corrected prior flat key/value model and revised golden wire fixture. Reset modes0/1/3/4/5 clear histories and recalculate price; daily assigns buyCount before price,3-5 after.2 returns without messages, unknown modes send messages only. Snapshot uses config id rather than UID.506 checks pass.','source':['product-reset-generics.json','product-buy-count-evidence.json','disassembly/Type4542-34595.txt','disassembly/Type4542-34574.txt'],'implementation':['OutgameProductResets.cs','OutgameItemRecords.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='lifecycle_scheduling_resets_implemented_price_rewards_provider_pending';audit['productResetImplementation']={'files':['OutgameProductResets.cs','OutgameItemRecords.cs'],'checks':506,'source':['product-reset-generics.json','product-buy-count-evidence.json'],'detail':'Original reset mode branches, price callback order, dirty update, config-id snapshot and ordered UI messages; scheduler integration tested. Prior flat HaveBuyCounts model superseded by original nested ProductBuyCount wire.'};audit['pending']=['Implement ProductUserData.UpdateConsumeItemPrice full scalar and array pricing formulas','Implement reward side effects and statistics bus production host','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 商品购买计数重置与原记录修正（506项）\n泛型证据纠正HaveBuyCounts为List<ProductBuyCount>，每项key+buyCount(List<ItemGetTypeBuyCount>)，内层才是key/value；旧扁平模型与黄金fixture已替换。新增OutgameProductResets，保留每日先buyCount后价格、3/4/5先价格后buyCount、模式2直接返回、未知模式仅通知；快照键按源config.id而非UID，通知依次RefreshStore/ProductReset。已验证定时更新串接真实计数重置、消息顺序及价格回调失败中间态。506项（战斗267+关外239）通过，Unity退出0。价格公式本体、奖励、平台及真实账号Provider仍待完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameProductResets','--result','pass','--evidence','506 integrated checks; corrected nested purchase wire, source reset branches, scheduler integration and UI order verified; price formulas and production provider pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded506; full goal remains active.')
