from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==453
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='serial-ad-preload';s['validation'].update(integratedChecksPassed=453,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['serial-ad-preload']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7527-54987.txt','disassembly/Type7527-54992.txt','disassembly/Type7527-54994.txt','disassembly/Type7527-54999.txt','disassembly/Type7526-55004.txt'],'implementation':['OutgameSerialAdPreload.cs'],'scope':'Serial request scan binds absent listeners and removes state0/3/5 candidate before Handle. Video preload counts twice, caps cache at count-1, waits2 scaled seconds then load; stop ordering and completed handle retention preserved. Full load setup/native candidate connection pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original serial preload timing and request scan') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original serial preload timing and request scan','checksPassed':453,'outgameChecksPassed':186,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Serial preload requests first state0/3/5 candidate, binds missing listener on every visited entry, removes before Handle. videoShowLoad checks count>=2 then rereads count to cacheAmount=count-1, stops old handle, starts WaitForSeconds2 then virtual load. Stop clears handle only after stop callback; completed handle retained. CheckRequest prints state, calls base when request-end or cache full, otherwise serial loads next.453 checks pass.','source':['disassembly/Type7527-54987.txt','disassembly/Type7527-54992.txt','disassembly/Type7526-55004.txt'],'implementation':'OutgameSerialAdPreload.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 串行预加载扫描与协程（453项）\n新增OutgameSerialAdPreload，恢复requestPlatList扫描、缺失监听器绑定、state0/3/5首候选先移除后Handle。播放预加载候选数至少2才执行，重读数量设cacheAmount=count-1，停旧协程后等WaitForSeconds(2)调用load，完成句柄保留至显式停止；停止抛异常保留句柄。453项（战斗267+关外186）通过，Unity退出0。仍需完整load配置、实际适配器候选与控制器Host连接，整体目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSerialAdPreload','--result','pass','--evidence','453 integrated checks; serial preload delay, count reread, listener binding and removal-before-request verified; production wiring incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded453; full goal remains active.')
