from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==455
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='serial-load-entry';s['validation'].update(integratedChecksPassed=455,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['serial-load-entry']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7511-54843.txt','disassembly/Type7511-54854.txt','disassembly/Type7511-54859.txt','disassembly/Type7511-54860.txt','disassembly/Type7527-54986.txt'],'implementation':['OutgameSerialAdPreload.cs'],'scope':'Load/requestAdapters now binds non-cache listeners, rebuilds retryable cache request list, applies only source cacheAmount1 non-banner break, reports then serial loads. Null/end and state2 count restored. Full controller/native lifecycle connection pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original serial loading entry and request-list construction') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original serial loading entry and request-list construction','checksPassed':455,'outgameChecksPassed':188,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Serial loading entry binds absent non-cache listeners then fetches platform list again for request-list rebuild. Cache candidates state0/3/5 included; only cacheAmount==1 and non-BANNER breaks after first, no general count cap. Nonempty non-banner reports rota then serial loads. isRequestEnd null/empty true; getNowCacheNum counts state2 in platform list.455 checks pass; full native/controller wiring incomplete.','source':['disassembly/Type7527-54986.txt','disassembly/Type7511-54860.txt'],'implementation':'OutgameSerialAdPreload.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 串行load入口与候选重建（455项）\nOutgameSerialAdPreload补齐Load/RequestAdapters/InitRequestList/IsRequestEnd/GetNowCacheNum。先给非缓存候选绑定缺失监听器，再重取列表选缓存state0/3/5；仅cacheAmount=1且非BANNER才首项截断，并非按任意容量截断。非空非banner先报告再serialLoad。455项（战斗267+关外188）通过，Unity退出0。完整控制器事件、原生适配器及实际配置连接仍待完成，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSerialLoadEntry','--result','pass','--evidence','455 integrated checks; serial load entry, request reconstruction, state filters and source one-item special case verified; production wiring incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded455; full goal remains active.')
