from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==485
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='serial-video-session';s['validation'].update(integratedChecksPassed=485,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['serial-video-session']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7544-55066.txt','disassembly/Type7527-54985.txt','disassembly/Type7527-54996.txt','disassembly/Type7527-54999.txt','disassembly/Type7511-54864.txt'],'implementation':['OutgameSerialVideoSession.cs'],'scope':'Composes source factory/config/controller/listener/preload/completion. Owns internal load/check/show-preload/cancellation/actual platform count. Controlled native handles verify reward-to-reload, failure-to-retry and multi-adapter display/refill without manual continuation. Live SDK/reporting and game startup binding remain external.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original serial video session composed lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original serial video session composed lifecycle','checksPassed':485,'outgameChecksPassed':218,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'OutgameSerialVideoSession composes source factory, config binding, controller, serial listener, preload and completion. Internal lifecycle load/check/stop/preload/count route to owned modules, not reporting-host stubs.485 checks pass including complete and partial watches followed by automatic reload, native failure retry, and second adapter preloading while first displays then capacity restoration/refill.','source':['disassembly/Type7544-55066.txt','disassembly/Type7527-54996.txt','disassembly/Type7527-54999.txt','disassembly/Type7511-54864.txt'],'implementation':'OutgameSerialVideoSession.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 串行视频运行组合（485项）\n新增OutgameSerialVideoSession组合工厂、源配置、控制器、监听器、预加载与请求完成/重试。Load、CheckRequest、show预加载、取消及平台数量由组合对象内部连接，不再交给报告Host空桩。受控原生句柄验证完整/提前关闭后自动重载、原生失败后定时重试，以及双适配器展示中预加载、关闭恢复容量并补满缓存。485项（战斗267+关外218）通过，Unity退出0。仍需真实SDK/报告服务与游戏启动配置接线；未声称完整平台或完整关外完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameSerialVideoSession','--result','pass','--evidence','485 integrated checks; composed serial video session automatically reloads/retries/preloads from native callbacks; live SDK and game startup binding pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded485; full goal remains active.')
