from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/time-module-native-validation.json');assert r['passed'] and len(r['checks'])==938;assert n['passed'] and len(n['checks'])==19
assert 'AREABATTLE_INTEGRATED_PASS cases=938' in (W/'analysis/time-module-integrated-final.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');ids=set(range(27252,27312));methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
source=dict(atUtc=now,methods=methods,metadataEvidence='TIME_MODULE_METADATA.json',previousCountdownEvidence='TIME_COUNTDOWN_SOURCE_EVIDENCE.json',criticalEvidence=[
 'TimeModule27252 priority60; Initialize27253 replaces countdown, loop and Unity dictionaries in source order, resets lastMinute/lastTime/timeId, sets instance initialized flag then calls callback. Constructor lists survive reinitialization. Static IsInit is distinct from the instance flag.',
 'Start27254 registers GF_NewGamePause then GF_GameFocus with no deduplication. Pause27256 typed bool args[0], true iterates live loop values and calls GamePause; false does nothing. Focus27257 assigns shared static focus. Update27255 updates local DateTime, checks countdowns with Unity realtime, then loop timers with scaled/unscaled delta, then Unity timers. No instance initialized/focus blanket gate.',
 'ClearTimer27258 clears countdown maps then loop removal ids/loop map then Unity maps and resets selected timestamps/id. Does not destroy loop callbacks or clear pending additions/Unity removal lists, lastMillisecond or realtime. Shutdown27291 removes each source listener once, ClearTimer then initialized=false. Exceptions preserve prefix mutations.',
 'Loop Add27259/27260 increments shared id, constructs helper3535, queues it, autoPlay true writes paused=false but false leaves same defaultfalse; log count observes live map after queue. Wrapper27262/27263 order verified against parameter metadata. Check27261 removes queued ids then activates queued helpers with Dictionary.Add, then two live Values passes AddTimes and Check. Pending work created during callbacks waits until next call. Source generic usage3956496 resolves Dictionary.Add10512.',
 'Loop helper27298..27306: AddTimes returns on paused/unfocused; unscaled>1 is ignored, scaled spikes accepted. Both elapsed/total accumulate. Check does not consult pause/focus; >=step resets elapsed before one callback passing configured step, discards overshoot. GamePause if enabled invokes with actual elapsed (integer truncates) then resets elapsed after callback, no paused flag change. Destroy nulls callbacks only. Pause callback sees elapsed; GetLoopTimerValue returns truncated total; Reset optionally clears total. Remove queues id before callback and never removes immediately.',
 'Unity Add27285 queues main one-shot plus optional separate looping1second helper sharing id; AddUnityEverySecond27286 queues only1second helper. Helper3536 AddTimer reads Unity scaled/unscaled delta, returns if complete/unfocused or unscaled>1, adds elapsed then invokes every callback before testing live elapsed>=duration. Complete invokes callback first, then live loop flag selects subtract duration versus setcomplete. One callback per step; overshoot retained for loop.',
 'CheckUnity27288 merges cached removal ids into complete list with Contains dedupe, clears cache, removes all three maps by id, clears complete list, activates queued lists in main/second/minute order, each Dictionary.Add (usage3956548 resolves10512). Tick order everysecond/main/everyminute, separate live Values enumerators. Only main loop enqueues IsComplete ids; removal occurs next check. Adds during callbacks stay pending; callbacks requesting removal do not prevent later same-frame passes. Source conditional queue Clear only occurs for nonempty pending/cache lists.',
 'All conversions preserve WASM signed-int overflow behavior. Callback exceptions propagate; no fabricated cancellation, retry cleanup, pause behavior, catchup or queue normalization.'
],limits=['This is the complete recovered TimeModule method family as an IOutgameStartupModule implementation; actual full application startup/update owner composition remains pending.','Native validation drives module.Update from editor pump with actual Unity deltas and DateTime.Now. Resource and shared audio update services remain fixtures; no full Player or platform service claim.'])
write(O/'TIME_MODULE_SOURCE_EVIDENCE.json',source)
v=dict(atUtc=now,scope='Source TimeModule full lifecycle/loop/Unity timers composed with existing countdown and native audio',checksPassed=938,newIntegratedChecks=25,nativePlayModeChecks=19,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameTimeModulePlayModeValidation.Run'],notClaimed='Full Main/account/menu composition, shared UpdateManager/AudioManager/resource ownership, full outgame Player')
remaining=['Restore shared UpdateManager and AudioManager3421/config/root/listener/node/resource helper composition, then bind real ownership into full Main module graph.','Continue remaining27 business controller lifecycles and full Main/account/module/menu graph; all original scope, restart/failure/return and runnable Player acceptance remain required.']
a=dict(atUtc=now,status='source-module-restored-composition-pending',sourceEvidence='TIME_MODULE_SOURCE_EVIDENCE.json',verification=v,findings=[
 'Production OutgameTimeModule extends countdown implementation while sharing TimeId and preserving map creation/clear ordering. Full source lifecycle, looping helpers, Unity helpers, pending queues and messages restored. Existing countdown API and tests retained.',
 '938 integrated checks passed,25 new source golden checks. 19 native checks passed with full module Update including original1001/2001 audio, actual Unity delta accumulation and DateTime fade, focus listener and shutdown disposal. Remaining resource/shared audio update owner is explicitly fixture.',
 'Initial integrated invocation directly called report-returning ValidateIntegrated and did not auto-exit; after it produced938 passes, only own PID62448 was terminated. Initial native launch71540 hit existing-project lock and produced no result. Final successful native62124 and integrated51160 exited normally. Final logs below are authoritative.',
 'Controller lifecycle count remains11/38,27 remaining. Method map unchanged4993. No full outgame Player build or acceptance claim.'
],remaining=remaining,artifacts=dict(integratedLog='analysis/time-module-integrated-final.log',nativeLog='analysis/time-module-native-final.log',nativeReport='analysis/time-module-native-validation.json'),disassembledMethodMapCount=len(mm))
write(O/'TIME_MODULE_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='time-module-native-audio',timeModuleAudit='generated/outgame/TIME_MODULE_AUDIT.json',nextPriority=' '.join(remaining));d['validation']['integratedChecksPassed']=938;d['validation']['timeModuleNativeAudio']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='time-module-native-audio'];d['milestones'].append(dict(id='time-module-native-audio',atUtc=now,status='source-module-restored-composition-pending',integratedChecks=938,nativeChecks=19,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,timeModuleAudit='TIME_MODULE_AUDIT.json');d['remaining'][0]=' '.join(remaining);d['findings'].append('Source complete TimeModule lifecycle/loop/Unity timers now verified:938 integrated and19 native audio checks. Shared UpdateManager/resource/AudioManager and application ownership pending; controller count11/38 unchanged.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=938,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset')
assert all(f.stat().st_mtime<=(W/'analysis/unity-integrated-validation.json').stat().st_mtime for f in files)
d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 完整TimeModule增量\n- OutgameTimeModule.cs实现3534生命周期与3535循环/3536Unity计时器；继承已有OutgameTimeCountdowns共享ID，base拆出protected InitializeCountdownMaps/ClearCountdownMaps/ResetTimeFields，保留完整初始化与清理字段顺序。IOutgameStartupModule ready，完整应用所有权待装配。\n- Start注册GF_NewGamePause/GF_GameFocus，允许重复注册；Shutdown每种只移除一次→ClearTimer→IsInitialized=false。GamePause bool true仅flush loop elapsed，false无操作；Focus写static。Update实际DateTime.Now/Unity realtime→countdown→loop(delta/unscaled)→Unity。\n- loop先移除队列，再Dictionary.Add待加入，再全体AddTimes，再全体Check。autoPlay=false仍默认未暂停；仅unscaled>1丢弃。AddTimes由pause/focus gating，Check无gate。一次callback后丢弃超额elapsed；GamePause先callback后reset，与Check先reset后callback不同。GetValue返回total，remove先排队再callback。\n- Unity先合并cached移除并去重→移除3个map→清complete→按main/second/minute加入→按second/main/minute tick。主timer完成仅排入下帧移除，其sameID秒timer同步移除。helper先Every再live判断完成；Complete先callback再按liveLoop减Duration或置完成；循环保留超额但每步一次。\n- ClearTimer/Initialize均保留pendingAdds/Unity移除队列，并重置TimeId，源可能重启ID冲突如实保留。Clear不Destroy loop回调，不reset lastMilli/realtime。所有异常保留已提交的部分状态。\n- 938集成通过（新增25），19全新native通过；最终log analysis/time-module-integrated-final.log / time-module-native-final.log，report time-module-native-validation.json。Native使用完整module.Update、实际Unity delta和DateTime驱动原音频；Focus冻结loop/Unity但countdown继续，Shutdown移监听验证。loader/shared audio update仍fixture。无完整Main/Player build声明。\n- 初次integrated直接调用ValidateIntegrated返回report但不退出；验证完成后仅终止本任务62448。首次native71540因项目锁退出，无有效结果；最终native62124/integrated51160已正常退出，无待续进程。下次集成请用ValidateMechanicsOnly自动退出。\n- O/TIME_MODULE_SOURCE_EVIDENCE.json、TIME_MODULE_AUDIT.json；状态time-module-native-audio；938/4993/11/27。next：shared UpdateManager + AudioManager3421（config/root/listener/node owner，3424异步clip资源helpers），随后其余27控制器和完整应用生产装配。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('913 项 checks','938 项 checks').replace('caseCount=913；latestValidation 为 source time countdown/native audio','caseCount=938；latestValidation 为 full source TimeModule/native audio').replace('in_progress / time-countdowns-native-audio','in_progress / time-module-native-audio').replace('最新集成日志 analysis/time-countdown-integrated-final.log。913集成、15原生源码计时/音频链通过（loader/update为fixture，timer为实际源码实现）；','最新集成日志 analysis/time-module-integrated-final.log。938集成、19原生完整TimeModule/音频链通过（loader/shared audio update为fixture，timer为完整源码实现）；');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameTimeModuleNativeAudio','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/TIME_MODULE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=938,nativeChecks=19,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
