"""Audit source-grounded account item/activity reward composition; no new WASM claims."""
from pathlib import Path
import json,hashlib
root=Path(__file__).resolve().parent.parent;out=root/'analysis/targets/wxcf1394487200e48f/43/generated/outgame'
read=lambda p:json.loads(p.read_text());digest=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
index={r['metadata']:r for r in read(out/'method-map.json')}
selected={32533,34335,34337,34340,34598,34589,34581,35226,31618,31621,31632,26744,35406,35407,35408,35467,35500,35621,35646}
assert selected<=index.keys()
roster=read(out/'data-manager-registration-roster.json');registrations=[r for r in roster['managers'] if r['typeIndex'] in (4119,4500)]
assert len(registrations)==2 and all(r['registration']['gameName']=='Proj_hdzd'and r['registration']['autoSyn']and not r['registration']['compressData']for r in registrations)
deps=['TASK_ACTIVITY_SOURCE_EVIDENCE.json','TASK_MANAGER_SOURCE_EVIDENCE.json','ACHIEVEMENT_RUNTIME_SOURCE_EVIDENCE.json','ITEM_MODULE_SOURCE_EVIDENCE.json','BUFF_TOOL_CONTROLLER_SOURCE_EVIDENCE.json','data-manager-registration-roster.json']
report=dict(status='source-grounded-account-reward-composition',methods=[dict(index[i],sha256=digest(out/index[i]['path']))for i in sorted(selected)],dependencies=[dict(path=p,sha256=digest(out/p))for p in deps],registrations=registrations,
 findings=[
  'OutgameAccountItemRuntime composes original LocalDataManager4119, ItemRuntime/ItemManager4500 and ToolControl4256 in the existing account data pool, using caller-supplied real login/storage/version services. Original registration attributes remain Proj_hdzd/autoSyn=true/compressData=false. No successful account login, platform response or upload is supplied by production defaults.',
  'ToolChange32533 calls actual DataManagerPool.SaveData on every normal return. New concrete account Tool effects preserve that owner rather than allowing an inert Save endpoint. Type6 resolves current ItemConfigMgr.GetGameItemConfig, actual ItemManager.GetItem, AddItem; missing entity endpoint remains required. Other presentation/skin/report callbacks remain explicit required hosts. LocalDataManager server callbacks replace Profile.inventory, so inventory and dispatcher projections rebind to current record on subsequent Tool calls.',
  'OutgameActivityRewardBinding is installed BEFORE ActivityRuntime.Init. Source ActivityControl35226 remove/add GetCommonItem therefore attaches the actual account reward engine; Task/Achievement/optional limited-task factories share actual entity/config providers. Late replacement would omit the virtual liveness factory callback. Fixture construction now supports a before-init composition hook, leaving previous fixture defaults unchanged.',
  'Original GameItemConfig is loaded via a real AssetBundle through the legacy config reader:79 items.1003 is daily liveness type2/3 param130001;1004 is original type1/4, not the synthetic achievement-point override used by isolated model tests. Both shared-global item statistics and activity events use the same account message owner.',
  'Daily TaskComplete marks state1 BEFORE rewards. Global AddRewardsByItemSelf34598 calls each entity AddItemOnlyModel; the virtual liveness reward mutates actual task ext. Only then ItemManager.AddRewards34340 calls ToolChange for each non-type6 reward. Thus its pool save includes daily claim/liveness plus ItemManager and LocalDataManager currency. Source dirty task update still executes afterwards; no transaction or reordered award is introduced.',
  'Achievement reward differs: source GetAchievementReward uses entity.AddItem before marking state/time. The Tool-triggered pool save captures currency but the achievement compact ids list still lacks that claim. Subsequent original account pool save persists claim/time. Tests prove the source distinction and independent restart after the proper account save.',
  'Liveness reward endpoint awards through actual account before setting source claim bit; dirty update persists bit. Original package20000 uses real package/random/entity services through Tool type6, and nested gold/diamonds reach both manager records. Tests force low/high random inputs to cover all four original package branches: gold, diamonds, nested package8000 (drawing actual hero pieces8401 on high input) and dice points11001. Points use the recovered OutgameDicePoints owner and shared stock/message path; all sampled records are compared after independent restart.',
  'Unsatisfied login progress and data-pool SaveDisabled retain their source save restrictions. Report failure during daily award leaves state1 and already-mutated shared inventory, but prevents later local economic delivery and storage. No invented rollback or success callback.',
  'ItemRuntime now accepts an explicit UpdateManager registration/removal owner, retaining original static UpdateManager defaults. Account composition passes shared scheduler. Initial edit-mode validation invoking DontDestroyOnLoad was corrected by using the already-instantiated real scoped UpdateManager; native validation uses actual Unity Update.',
  'Fresh native page pointers grant original achievement200 then daily50; both actual ItemManager and LocalDataManager records restore250 after independent storage/activity/page restart together with both claims and daily liveness. Full production Main/account/platform/presentation/skins/effects/reports and final Player/original audiovisual acceptance remain incomplete.'
 ],remaining=['Production Main/account login lifecycle and whole data-pool/controller startup composition.','Actual external/platform/presentation/skin/audio/effect/report hosts, remaining18 controllers/all business and final Player/original audiovisual acceptance.'])
(out/'ACCOUNT_REWARDS_SOURCE_EVIDENCE.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(methods=len(selected),dependencies=len(deps),registrations=len(registrations),indexedMethods=len(index))))
