from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/level-reuse-native-validation.json');assert r['passed'] and len(r['checks'])==778;assert n['passed'] and len(n['checks'])==10
v={'atUtc':now,'scope':'Level reset/pools/EffectCellection/native immediate reentry and deferred destruction; shared query buffers/range/random/entity lookup/speed/special scene routing','checksPassed':778,'newIntegratedChecks':22,'nativePlayModeChecks':10,'freshPlayModeRun':True,'freshPlayerBuild':False,'freshPlayerSmoke':False,'commands':['BattleBuild.ValidateMechanicsOnly','OutgameLevelReusePlayModeValidation.Run'],'notClaimed':'Complete source Tower/Soldier/WayLine/AI/EffectModule, full Level/UI/Main composition, Player4462 lifecycle, account/platform/native full outgame build'}
a={'atUtc':now,'status':'partial-subsystem','sourceEvidence':'LEVEL_REUSE_QUERY_SOURCE_EVIDENCE.json','verification':v,'findings':[
 'InitGameData preserves exact ordered partial mutations: currentBoss=null, native obstacle hide then list clear, check flags98/96/97=false, active CampInfo.Clear, active Tower.Clear, all Soldier.Clear(true) and Effects.Destory, then WayLine field168=0. Source pools/tuple/playstate/scores/timers/HasBoss/obstacle flag retained.',
 'GetEmptySoldier requires inactive AND original field112=true; GetEmptyBoss filters inactive Boss; GetEmptyTower type4 uses Arrow, other values ordinary nonArrow, all exclude Boss. Required factories still need full source classes; no implicit activation/readiness invented.',
 'Complete EffectCellection nine-method surface implemented with source one-child duplicate-name behavior, dictionary Add/Display/Spawn/Remove, live module resolution, exception/foreach mutation behavior, native root guard and reverse native child deletion. Real EffectModule service remains a required host boundary.',
 'Native original Entity81 survives reset, immediate reentry reuses same instance; EffectCellection root/children persist until Unity frame boundary then only that subtree is destroyed. All soldiers cleared even inactive. Native root recreated correctly after cleanup. Explicit recording effect-module/soldier callbacks do not establish full effect or soldier production behavior.',
 'Four camp queries preserve shared list aliases: same-camp variants use field76 and exclude only Arrow in nonArrow route; other/enemy share80, differing on neutral inclusion. Missing tower fails with partial shared results. Object lookup uses Unity equality and active source order, including destroyed native reference equaling null.',
 'Range query allocates fresh list and compares squared cached xyz distance against outer range squared and sqrt(minimum), including equality boundaries and NaN greater-than semantics. Random pick uses original shared System.Random.Next(count) for nonempty lists, including singleton consumption.',
 'SetScoreSumChangeOn leaves timer untouched. SetLevelSpeed writes sourcefield104 then Unity Time.timeScale. GetBossObj reuses actual loader object, only normalizes localScale, and preserves exact null diagnostic.',
 'InitSpecialScene captures SpecialState before GameControl getter; exactly1 uses existing source FestRewardSelection awardtype5, all other values source SkinCatalog type4. Actual GameControl.LoadGameScene dispatched. LoadCurrentLevel wrapper loads configuration before scene selection.'
 ],'remaining':[
 'Level remaining methods and full native Tower/Soldier/WayLine/AI/effect services; compose prepared/state/continuation UI hosts into actual Main. Existing independent combat kernel is unchanged.',
 'Player4462 and remaining29 controller lifecycles, then actual Main/account/menu entry and every objective subsystem. Nine lifecycle implementations remain a method-level count, not complete gameplay controllers.',
 'Full objective persistence/restart/failure/return-to-home flows and runnable Player build acceptance remain open.'
 ],'artifacts':{'integratedLog':'analysis/level-query-integrated.log','resetIntegratedLog':'analysis/level-reuse-integrated.log','nativeLog':'analysis/level-reuse-native.log','nativeReport':'analysis/level-reuse-native-validation.json'},'disassembledMethodMapCount':4681}
write(O/'LEVEL_REUSE_QUERY_AUDIT.json',a)
p=O/'LEVEL_CONTROL_AUDIT.json';d=read(p);d.update(lastUpdatedAtUtc=now,latestIncrement='LEVEL_REUSE_QUERY_AUDIT.json');d['remaining']=a['remaining'];write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,levelReuseQueryAudit='LEVEL_REUSE_QUERY_AUDIT.json',verification=v);d['remaining'][0]=a['remaining'][0]+' '+a['remaining'][1];write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='level-reset-pools-effects-queries',levelReuseQueryAudit='generated/outgame/LEVEL_REUSE_QUERY_AUDIT.json',nextPriority='Finish remaining Level source methods and full Tower/Soldier/WayLine/AI/effect providers, then Player4462 and remaining29 lifecycle controllers. Compose actual Main/account/menu/entry, all objective outgame subsystems and persistence/restart/failure/return-flow plus runnable Player acceptance; no fake platform callbacks.');d['validation']['integratedChecksPassed']=778;d['validation']['levelReuseQuery']=v;d['validation']['levelReuseNative']=n;d['milestones']=[m for m in d['milestones'] if m['id']!='level-reset-pools-effects-queries'];d['milestones'].append({'id':'level-reset-pools-effects-queries','atUtc':now,'status':'partial-subsystem','integratedChecks':778,'nativeChecks':10,'remainingLifecycleControllers':29});write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=778,latestValidation=v);d['validationHistory'].append(v)
if 'analysis/level-reuse-native-validation.json' not in d['reports']:d['reports'].append('analysis/level-reuse-native-validation.json')
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix())];d['sourceFingerprints']=[{'path':f.relative_to(W).as_posix(),'sha256':hashlib.sha256(f.read_bytes()).hexdigest()} for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 Level重置、复用、特效集合与查询增量\n- InitGameData按源顺序清理：Boss引用→隐藏障碍物并清列表→check flags→active Camp/Tower.Clear→全部Soldier.Clear(true)/Effects.Destory→WayLine.field168=0。保留池/关卡配置/状态/其它flags与计时，不补造重置。\n- 对象池按inactive/士兵field112/Arrow type4/Boss过滤；完整具体Tower/Soldier仍待恢复。EffectCellection九方法已实现，原生帧末销毁、根丢失时保留句柄、单child重复命名和异常顺序均保留；真实EffectModule仍待接入。\n- 778集成（本批新增22）通过；10原生检查通过：原始Entity81重置后立即复用同实例、特效子树帧末销毁、实体与SO保留。原生EffectModule/Soldier回调是明确fixture，不声称完整业务对象完成。\n- 查询共享field76/80结果、neutral差异、仅排除Arrow、Unity destroyed==null、range平方距离对外半径平方/内参数开方及NaN比较、Random.Next(count)均按源。补SetLevelSpeed、refreshflag、GetBossObj和现有皮肤/节日选择到真实GameControl的场景路由。\n- O/LEVEL_REUSE_QUERY_AUDIT.json与LEVEL_REUSE_QUERY_SOURCE_EVIDENCE.json（26方法/71字段+2泛型随机函数）；method-map4681，生命周期仍9/38剩29。日志analysis/level-query-integrated.log、level-reuse-native.log；无本任务待续进程。\n- 下一步剩余Level API与完整Tower/Soldier/WayLine/AI/effect、Player4462及剩29生命周期，实际Main/account/menu接线与全目标验收。没有新Player构建，完整关外目标保持active。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('756 项 checks','778 项 checks').replace('caseCount=756；latestValidation 为 Level lifecycle/camps/prepared-start','caseCount=778；latestValidation 为 Level reset/pools/effects/queries').replace('in_progress / level-lifecycle-camps-prepared-start','in_progress / level-reset-pools-effects-queries').replace('最新集成日志 analysis/level-control-integrated-final.log；Level准备原生日志 analysis/level-start-native.log。756集成+10 Level准备原生通过；','最新集成日志 analysis/level-query-integrated.log；Level重置原生日志 analysis/level-reuse-native.log。778集成+10 Level重置原生通过；历史Level准备10项通过；');s+=text;p.write_text(s,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameLevelReuseQueriesNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/LEVEL_REUSE_QUERY_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps({'checks':778,'native':10,'fingerprints':len(files),'lifecycleImplementations':9,'remaining':29}))
