from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==433
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-cache-selection';s['validation'].update(integratedChecksPassed=433,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-cache-selection']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7511-54851.txt','disassembly/Type7507-54877.txt','disassembly/Type7508-54879.txt','ad-selection-list-resolution.json','ad-selection-comparer-types.json'],'implementation':['OutgameAdCacheSelection.cs'],'scope':'Source cache branch and comparers restored, including in-place sort, priority rotation, guarantee exclusion, bidding gates and platform fallback. Full request queue, allPlatHasPrice policy, native adapter and controller wiring remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original cache selection comparers, bidding gates and priority rotation') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original cache selection comparers, bidding gates and priority rotation','checksPassed':433,'outgameChecksPassed':166,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'BaseController.showAd cache selection sorts in place. Bidding only when flag==1, cache count==cacheAmount and source allPlatHasPrice accepts; PriceComparer ascending signed price, last item selected, no priority update. Otherwise ascending priority rotates strictly above last priority, excluding guarantee entries, then wraps only to first item if non-guarantee. Both comparers return0 for either null argument. Source allPlatHasPrice is an explicit policy boundary, not invented. 433 integrated checks pass.','source':['disassembly/Type7511-54851.txt','disassembly/Type7507-54877.txt','disassembly/Type7508-54879.txt'],'implementation':'OutgameAdCacheSelection.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 广告缓存排序与选择（433项）\n新增OutgameAdCacheSelection，保持原地排序、最高价格选择、优先级轮转、保底排除、平台回退和短路条件。比较器保留null比较为0与有符号整型比较，避免相减溢出。新增竞价门槛、极值价格、轮转回绕、保底回退和平台优先覆盖；433项（战斗267+关外166）通过，Unity退出0。allPlatHasPrice暂为显式策略输入，完整请求队列、原生适配器和生产接线未完成，目标继续有效。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdCacheSelection','--result','pass','--evidence','433 integrated checks; cache bidding gates, source comparers, priority rotation and fallback verified; complete controller and goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded433; full goal remains active.')
