from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==500
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-item-lifecycle';s['validation'].update(integratedChecksPassed=500,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-item-lifecycle']={'implementationReady':True,'productionConnected':False,'source':['global-item-lifecycle-generics.json','disassembly/Type4542-34588.txt','disassembly/Type4542-34580.txt','disassembly/Type4542-34577.txt','disassembly/Type4542-34593.txt','disassembly/Type4542-34570.txt','disassembly/Type4542-34591.txt'],'implementation':['OutgameGlobalItemLifecycle.cs'],'scope':'Compose original decode, time sync, update handle, products/items and statistics registration order; repeated init and release exception semantics. Source Update body/reward engine and production host remain required dependencies.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original global item initialization and release lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original global item initialization and release lifecycle','checksPassed':500,'outgameChecksPassed':233,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Global item init installs clock host before decode, syncs time/registers Nullable<Int32> update handle before product/item indexes, then sets dirty and registers statistics10020. Query consumes boxed Int32 first argument and returns live Int64 count. Release removes handle then disposes config then clears singleton.500 checks pass.','source':['global-item-lifecycle-generics.json','disassembly/Type4542-34588.txt','disassembly/Type4542-34580.txt','disassembly/Type4542-34577.txt','disassembly/Type4542-34593.txt','disassembly/Type4542-34570.txt'],'implementation':['OutgameGlobalItemLifecycle.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='init_save_release_implemented_update_rewards_provider_pending';audit['lifecycleImplementation']={'files':['OutgameGlobalItemLifecycle.cs'],'checks':500,'source':['global-item-lifecycle-generics.json'],'detail':'Init decode/time/handle/indexes/dirty/statistics order; handle0 valid; repeat init retains handle; failed add/remove and duplicate index preserve original partial state; statistics callback Int32 unbox to Int64 count.'};audit['pending']=['Implement GlobalItemManager.Update body and product reset/expiry rules','Implement reward side effects and statistics bus production host','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 全局物品初始化与释放（500项）\n新增OutgameGlobalItemLifecycle组合原记录、时间戳、更新句柄、商品/物品索引与统计注册。统计事件10020查询接受首个boxed Int32参数，返回live Int64数量；null/空参数返回0。Nullable<Int32>句柄允许0，重复初始化不重复注册；保存Add失败、重复键异常、Remove失败的原中间状态。释放依次移除句柄、释放配置、清实例。500项（战斗267+关外233）通过，Unity退出0。Update/奖励具体实现、统计总线生产Host、实际4500Provider尚待完成，生产门未开启。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameGlobalItemLifecycle','--result','pass','--evidence','500 integrated checks; original item init/time/update-handle/statistics/release ordering and failure states verified; Update body and production provider pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded500; full goal remains active.')
