from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==440
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-show-flow';s['validation'].update(integratedChecksPassed=440,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-show-flow']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7511-54851.txt','disassembly/Type7511-54849.txt','disassembly/Type7511-54863.txt'],'implementation':['OutgameAdShowFlow.cs','OutgameAdRequestQueue.cs','OutgameAdCacheSelection.cs'],'scope':'Composed source showAd control flow: initial report, busy gates, requests, weixin guarantee fallback, continuation failure reporting, cache selection, source state check, video clock and post-display removal. Native adapter lifecycle/events and video controller wiring remain incomplete.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original composed advertisement show control flow') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original composed advertisement show control flow','checksPassed':440,'outgameChecksPassed':173,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'OutgameAdShowFlow composes original BaseController.showAd, isShowing state4 scan, and removeCacheList Contains/Remove. Initial INTERSTITAL report precedes busy gates; busy closes VIDEO only. Requests run before fallback/cache. weixin fallback selects first guarantee/state2/canShow adapter in direct platList. Empty continuation with no fallback reports failure (INTERSTITAL4 close(true) first) but still continues to cache selection. Final selected must be state2; VIDEO clock resets -1 before ShowAd, cache removed only afterward and reread after callback. 440 integrated checks pass. Native SDK adapter/event initialization not yet connected.','source':['disassembly/Type7511-54851.txt','disassembly/Type7511-54849.txt','disassembly/Type7511-54863.txt'],'implementation':'OutgameAdShowFlow.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 广告showAd组合流程（440项）\n新增OutgameAdShowFlow，将原始忙碌检查、请求队列、微信保底回退、续请求失败报告、缓存选择、状态检查和展示后移除串通。保持INTERSTITAL首报告早于忙碌检查，VIDEO忙碌才回调false；INTERSTITAL4无回退续请求close(true)后报告失败，仍继续尝试缓存。展示前视频时间=-1，展示抛异常不移除缓存。440项（战斗267+关外173）通过，Unity退出0。实际原生广告生命周期、监听事件和视频控制器接线仍未完成，整体关外目标继续有效。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdShowFlow','--result','pass','--evidence','440 integrated checks; composed source show flow, busy gates, request/cache ordering and platform fallback verified; native lifecycle and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded440; full goal remains active.')
