from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==396
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='manager-storage-pipeline';s['validation'].update(integratedChecksPassed=396,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['manager-storage-pipeline']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type3465-26712.txt','disassembly/Type3465-26713.txt','disassembly/Type3465-26714.txt','disassembly/Type3466-26721.txt','disassembly/Type3606-27869.txt','disassembly/Type3467-26738.txt','disassembly/Type3467-26744.txt','disassembly/Type3467-26730.txt','disassembly/Type3467-26751.txt','data-manager-registration-roster.json','data-manager-registration-resolution.json','disassembly/Type3795-29619.txt','data-version-manager-resolution.json','data-manager-base-fields.json','disassembly/Type4612-34985.txt','disassembly/Type4612-34990.txt','disassembly/Type4612-34993.txt','disassembly/Type4612-34994.txt','login-sync-generic-resolution.json','login-sync-fields.json','disassembly/Type4610-34974.txt','login-failure-fields.json','login-failure-generic-resolution.json','login-success-generic-resolution.json','disassembly/Type4611-34978.txt','disassembly/Type4611-34983.txt','disassembly/Type3795-29617.txt','disassembly/Type3795-29613.txt','disassembly/Type3795-29614.txt','disassembly/Type3795-29615.txt','disassembly/Type3795-29616.txt','data-version-fields.json','data-version-generic-resolution.json','original-sdk-storage.js','sdk-storage-source.json','storage-sdk-slot-candidates.json'],'implementation':['OutgameLoginSync.cs','OutgameLoginFailure.cs','OutgameLoginSuccess.cs','OutgameLoginDataPlan.cs','OutgameDataVersionState.cs','OutgameSdkStringStorage.cs','OutgameDataVersionStorage.cs','OutgameFileStorageBackend.cs','OutgameDataManagerPool.cs','OutgameManagerRegistrationCatalog.cs','OutgameDataManagerStorage.cs'],'scope':'Original DataManagerBase save/read path: key validation warning does not abort, UTF8 lowercase MD5 dedup unless login procedure field8, compression before write/queue, local SDK writes gated at login progress10, version updates and upload conditions preserved independently. Required account/compression/upload host, real string SDK and version state connected; concrete manager factories and live SDK remain pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original DataManagerBase local storage, digest and sync pipeline') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original DataManagerBase local storage, digest and sync pipeline','checksPassed':396,'outgameChecksPassed':129,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'DataManagerBase f20028 validates keys before save and warns/toasts without aborting invalid keys. Identifier accepts optional @, Unicode letters/underscore first, then letters/digits/underscore, max511 UTF16 chars. UTF8 MD5 dedup precedes compression/local enable check and is bypassed by current LoginProcedure byte8. Local f8029 writes only when ILoginProcedure static int0>=10; version increment remains inside local-enabled branch even below10. Upload remains outside local-enabled branch; both version and upload require autoSyn plus server use or procedure-byte8 AND login-static-byte4. Digest is updated before local write and not rolled back on async failure. Read uses source MineGameName+DataKey and optional required decompression. Added storage component connects SDK cache/queue and version state; concrete manager lifecycle remains pending.','source':['disassembly/Type3465-26712.txt','disassembly/Type3465-26713.txt','disassembly/Type3465-26714.txt','disassembly/Type3466-26721.txt','disassembly/Type3606-27869.txt'],'implementation':'OutgameDataManagerStorage.cs','validation':'analysis/outgame-login-sync-validation.json'});audit['next']=['Connect concrete registered manager initialization/save callbacks and faithful serialization to OutgameDataManagerStorage.','Resolve active MineGameName/login progress providers and CommonGameModule registration entry.','Implement UserLogin reload/upload/download and complete startup to menu.'];write(p,audit)
note='\n\n## 原始管理器存档流水（396项）\n新增OutgameDataManagerStorage连接SDK字符串缓存/队列及版本状态：按原标识符规则校验（无效仍警告后写入），UTF8小写MD5去重，特定登录标志绕过去重；压缩发生在保存前，本地写入要求登录进度>=10，版本与上传条件分别保持。测试覆盖进度9/10、去重跨登录进度、版本后上传顺序、禁用本地但仍上传、非同步本地写入、压缩读写、键校验与重复警告。396项（原267+关外129）通过，Unity退出0。账号/压缩/上传仍由必需host提供，具体管理器序列化及完整生产启动未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameManagerStoragePipeline','--result','pass','--evidence','396 integrated checks; source manager storage, digest and sync ordering verified; concrete providers and full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded396; full goal remains active.')
