from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==461
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='ad-request-timeouts';s['validation'].update(integratedChecksPassed=461,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['ad-request-timeouts']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type7488-54673.txt','disassembly/Type7488-54674.txt','disassembly/Type7488-54678.txt','disassembly/Type7488-54679.txt','disassembly/Type7486-54729.txt','disassembly/Type7487-54735.txt','ad-timeout-config-resolution.json','ad-timeout-types.json'],'implementation':['OutgameAdTimeouts.cs'],'scope':'Adapter Handle/show timer sequencing, realtime load/show expiration, audio interrupt VIDEO recovery, timeout defaults/parse rules restored. Native bridge, reporting and concrete host composition pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original adapter request and timeout lifecycle') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original adapter request and timeout lifecycle','checksPassed':461,'outgameChecksPassed':194,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'DAU adapter Handle unconditionally sets state1, starts load timer for cache or show timer for noncache, reports then starts native request. Show stops previous show timer before starting anew. Both timeouts use WaitForSecondsRealtime. Load timeout only state1 clears then notifiesfail. Show timeout has audio-interrupted VIDEO recovery to notifyShowAd(true,true), else clears, state5, close listener then timeout report. CustomParam.video_ad_timeout resolved; defaults5, nonempty invalid parse0, rota<5 uses banner5/other60.461 checks pass.','source':['ad-timeout-types.json','ad-timeout-config-resolution.json','disassembly/Type7487-54735.txt'],'implementation':'OutgameAdTimeouts.cs','validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
note='\n\n## 广告请求与超时生命周期（461项）\n新增OutgameAdTimeouts恢复Handle/show启动计时、停止句柄、WaitForSecondsRealtime超时与清理通知次序。加载超时仅state1处理；展示超时保留音频中断VIDEO转notifyShowAd(true,true)，普通路径清理→state5→关闭监听→超时上报。解析CustomParam.video_ad_timeout，保留空值5、解析失败0、负数和WASM浮点转整型边界。461项（战斗267+关外194）通过，Unity退出0。尚需实际微信桥/报表及控制器Host组合，整体目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameAdRequestTimeouts','--result','pass','--evidence','461 integrated checks; request/show timer order, realtime expiration, audio recovery and config conversion verified; native production wiring incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded461; full goal remains active.')
