from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/audio-manager-native-validation.json');assert r['passed'] and len(r['checks'])==978;assert n['passed'] and len(n['checks'])==18
assert 'AREABATTLE_INTEGRATED_PASS cases=978' in (W/'analysis/audio-manager-integrated.log').read_text(encoding='utf8')
mm=read(O/'method-map.json');ids={26345,26346,26347,26348,26349,26350,26351,26352,26353,26354,26356,26358,26359,26363,26364,26365,26366,26367,26368,26370,26625};methods=[dict(m,sha256=hashlib.sha256((O/m['path']).read_bytes()).hexdigest()) for m in mm if m['metadata'] in ids]
assets=[]
for name,field in [('AudioConfig','Datas'),('OnceAudioConfig','AudioInfos')]:
 p=W/('UnityProject/Assets/AreaBattle/Resources/Recovered/FirstPack/Config/'+name+'.bytes');assets.append(dict(path=p.relative_to(W).as_posix(),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),rows=len(read(p)[field]),provenance='Previously imported byte-exact original firstpack configuration; no new data invented or transformed.'))
source=dict(atUtc=now,methods=methods,metadataEvidence='AUDIO_MANAGER_METADATA.json',configurationAssets=assets,utilityRandomEvidence=dict(path='analysis/audio-random-id-disassembly.txt',sha256=hashlib.sha256((W/'analysis/audio-random-id-disassembly.txt').read_bytes()).hexdigest(),function=6831,rangeCall=dict(function=1883,metadata=50652,owner='UnityEngine.Random',method='Range')),criticalEvidence=[
 'AudioManager3421 ctor creates nodes dictionary and Android-id dictionary, field36 empty string; config/once maps null, flagsfalse. get_Instance26364 caches normal CLR instance. Destroy26353 does not clear manager singleton; UIAudioManager.Destroy clears only its own slot.',
 'InitAudioManager26368 delegates26365. Initialized flag33 guard first; when ConfigRead resource null and AppSetting new-resource flag36false, log error and return without changing maps. Otherwise log then replace audio dictionary, readConfig<AudioData>("AudioConfig") via generic metadata26612. Null list still proceeds. Live indexed rows: duplicate id logs and keeps first, then all rows including duplicates scan ResPath.ToLower().Contains("audio/once") and can set sticky flag32.',
 'After audio rows, replace Once dictionary. If sticky UseOnceAudio log and ConfigRead26625 readOnceAudioConfig into dictionary. Flag33=true is written only after data work succeeds but before root/listener setup. ClearNode does not reset UseOnceAudio or Once/Android caches; reinit after Clear retains sticky once requirement.',
 'ConfigRead26625 warns when no legacy resource and no new route, still loads OnceAudioConfig. Actual JsonUtility generic4004888 resolves AudioList2893 with AudioInfos; each item Name/string Length -> float.Parse(current culture) -> Dictionary.Add. Missing asset logs exact message. Duplicate or invalid values propagate and preserve earlier additions. AudioConfig adapter explicitly implements already-proven UnityJson readConfig branch; modern loader/MemoryPack route not claimed.',
 'Root creation26346 creates new AudioRoot via Utils.NewGameObject with null parent, then DontDestroyOnLoad. Listener26347 creates new AudioListener GameObject + component, no separate persistence call. Ensure26367 invokes root then MoveAudioListen(1). Move26363 gets UIModule3558 camera field24 before ensuring listener; type1 and non-null camera parent it with worldPositionStays defaulttrue; other types leave hierarchy untouched.',
 'CreateNode26366 ensures root/listener only if root Unity-null; snapshots node dictionary Keys only if nonempty; RandomId(1,10000,keys), default null/destroyed parent to root; creates parallel_/sequence_/single_+id with source constructors for modes1/2/3, invalid returnsnull after preceding work. Registration26359 nullguards node/dictionary then set_Item, not Add.',
 'Random wrapper26370 delegates Utils wasm6831. Unity Random.Range returns chosen id; for each matching excluded id recursively calls RandomId but discards result. Original chosen id still returned, allowing dictionary overwrite while old native node remains. No uniqueness repair is invented.',
 'ClearNode26348 enumerates live node dictionary and virtual slot6 Stop(voice0), NOT slot8 Destroy; after all stops clears nodes, clears audio map, sets initializedfalse. Failure/mutation aborts subsequent cleanup. Destroy then destroys root through GlobalUnityEngineAPI (always sets rootnull after success or already fake-null), destroys listener GameObject and clears listener only inside live-object branch, then gets UI singleton and clears its slot.',
 'GetAudioData26345 null map or absent key returnsnull. GetAndroid26352 absent returns empty string. Once query26356 disabled logs error returns0 before accessing dictionary; enabled dictionary lookup case-sensitive, missing warning0. Settings26354 already restored delegates source prefs/message behavior.'
],limits=['AudioManager ownership and source configs now production code; config TextAsset transport and clip loaders in native test remain explicit adapters.','Audio helper3424 async LoadAudioClip26373/MoveNext26376 and LoadAudioClipForNewRes26374/MoveNext26378 still pending production implementations. Modern helper traced to NewResLoadHelper.LoadAssetAsync<AudioClip> metadata26176, lowercased full original path after unused basename splitting. Legacy helper and actual package routing remain to follow.','Other obfuscated AudioManager variants are retained as source evidence, not substituted for public entrypoints. Full Main module/config/account/menu app ownership and complete outgame Player acceptance remain open.'])
write(O/'AUDIO_MANAGER_SOURCE_EVIDENCE.json',source)
v=dict(atUtc=now,scope='Source AudioManager original55+53configuration/root/listener/node/UI/action ownership with native UpdateManager and source TimeModule',checksPassed=978,newIntegratedChecks=19,nativePlayModeChecks=18,freshPlayModeRun=True,freshPlayerBuild=False,freshPlayerSmoke=False,commands=['BattleBuild.ValidateMechanicsOnly','OutgameAudioManagerPlayModeValidation.Run'],notClaimed='Actual clip/config resource transport, alternate parser/entrypoint branches, complete Main/account/menu or full outgame Player')
remaining=['Restore audio resource helper3424 legacy/new clip async load and unload, source FirstPack/package routing, modern NewResLoadHelper26176 path; bind real config/resource ownership into AudioManager and full Main graph.','Continue remaining27 business controller lifecycles and full Main/account/module/menu graph, all original flows, persistence/restart/failure/return and runnable Player acceptance.']
a=dict(atUtc=now,status='source-audio-manager-restored-resource-composition-pending',sourceEvidence='AUDIO_MANAGER_SOURCE_EVIDENCE.json',verification=v,findings=['OutgameAudioManagerServices/Manager/Slot and AudioConfigReader now use actual55 AudioConfig rows and53 OnceAudio rows, manage root/listener/nodes and bind action config lookups/UI node factory. Source singleton cache lifetime and partial-failure ordering preserved.','978 integrated checks pass,19 new. 18 native checks pass using real original1001 loop-fade,1002 loop and2001 Ptype1 one-shot through AudioManager/UI/controller/factory/TimeModule/native UpdateManager. Source roots/listener/persistence/parenting, clear/destruction/reentry verified.','Earlier native fixture used synthetic2001 Ptype3 for fade testing; new manager native test uses actual original2001 Ptype1. Historical fade fixture tests remain scoped to action behavior, not changed source table.','Configuration and clips acquired through explicit local adapters in native test; actual clip/config resource transport and full Main app not claimed. Controller coverage11/38,27 remaining; method map5058.'],remaining=remaining,artifacts=dict(integratedLog='analysis/audio-manager-integrated.log',nativeLog='analysis/audio-manager-native.log',nativeReport='analysis/audio-manager-native-validation.json'),disassembledMethodMapCount=len(mm))
write(O/'AUDIO_MANAGER_AUDIT.json',a)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='audio-manager-native-ownership',audioManagerAudit='generated/outgame/AUDIO_MANAGER_AUDIT.json',nextPriority=' '.join(remaining));d['validation']['integratedChecksPassed']=978;d['validation']['audioManagerNativeOwnership']=v;d['milestones']=[m for m in d['milestones'] if m['id']!='audio-manager-native-ownership'];d['milestones'].append(dict(id='audio-manager-native-ownership',atUtc=now,status='source-audio-manager-restored-resource-composition-pending',integratedChecks=978,nativeChecks=18,remainingLifecycleControllers=27));write(p,d)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,audioManagerAudit='AUDIO_MANAGER_AUDIT.json');d['remaining'][0]=' '.join(remaining);d['findings'].append('Actual AudioManager original55+53 configs and native root/listener/node ownership verified:978 integrated,18 native. Clip/config resource transport and full app remain; count11/38 unchanged.');write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=978,latestValidation=v);d['validationHistory'].append(v)
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix() or '/Recovered/Audio/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');assert all(f.stat().st_mtime<=(W/'analysis/unity-integrated-validation.json').stat().st_mtime for f in files);d['sourceFingerprints']=[dict(path=f.relative_to(W).as_posix(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 AudioManager真实配置与节点所有权增量\n- OutgameAudioManager.cs含Services/Manager/Slot和AudioConfigReader（UnityJson AudioConfig + OnceAudioConfig专用解析）。原始firstpack已有55音频行+53Once时长，本轮读真实数据，未新增伪配置。AudioManager构造连接Actions.GetData和UIaudioSlot.CreateNode，工厂/节点/动作都真实。\n- Init26365先flag33 guard；缺ConfigResource且!NewRes才errorreturn，不改旧map。log后replaceAudioMap→live rows，duplicate保留first但仍scanpath.ToLower.Contains audio/once→stickyUseOnce32。replaceOnceMap→若sticky加载（float.Parse当前culture+Dict.Add，duplicate/error保留prefix）→flag33true→EnsureRoot/MoveListener1。root/listener失败flag已提交，repeat不自动repair。Clear不resetsticky/Once/Android缓存。\n- AudioRoot new+DontDestroy；AudioListener独立new，没有独立DontDestroy，Move先getUIModule3558.Camera(offset24)再EnsureListener，type1&&camera parent默认worldPositionStays=true；其它type不detach。CreateNode若Root fake-null才Ensure；defaultparentRoot；id viaRandomId(1,10000,keys)，mode1/2/3命名parallel_/sequence_/single_；Nodes[id]=node。\n- Utils.RandomId wasm6831直接调用Unity.Random.Range@1883 metadata50652；碰到excluded递归，但丢弃递归返回值，最后返回首次id，允许overwrite追踪并遗留oldnode。证据analysis/audio-random-id-disassembly.txt。原样实现/测试，不修成唯一ID。\n- ClearNode liveNodes foreach虚槽6=Stop(0)，不是Destroy；所有Stop成功后clearNodes/AudioData→flagfalse。Destroy随后root destroy/null→listener.gameObject destroy/null（只有listener live时）→UiSlot.Instance.Destroy。AudioManager singleton本身不清，UIaudio singleton清。\n- 978集成通过（新增19），18原生通过；analysis/audio-manager-integrated.log / audio-manager-native.log / audio-manager-native-validation.json。原生按真实1001Ptype4、1002Ptype2、2001Ptype1跑controller/UI/manager/action/sharedUpdate/timer，root/listener/真实销毁后重入验证；此前2001Ptype3仅fade测试fixture，不能误作原表。\n- O/AUDIO_MANAGER_METADATA.json、SOURCE_EVIDENCE、AUDIT。状态audio-manager-native-ownership；978/5058/11/27，fingerprints2054。Unity72600/32848已正常退出，无待续进程；仍无完整关外Player build。\n- 下一步clip资源helpers3424：26373wrapper→3422/26376MoveNext(3764bytes)旧资源；26374→3423/26378(1349bytes)新资源。新分支已核对path.Substring(lastSlash+1).Split('.')[0]结果unused，再path.ToLower→NewResLoadHelper.LoadAssetAsync<AudioClip> metadata26176(genericusage4008644) await并返回handle；无额外release。旧分支还需完整阅读，包括firstpack/newroute/fallback。Unload26375先path.ToLower()+'.unity3d'再if!NewRes AssetBundleManager.UnloadAssetBundle。必须接真实源资源owner，当前native传输与TextAsset加载还是显式fixture adapter。\n- 配置通用generic3993488=ConfigRead26612<AudioData3420>，4004888=JsonUtility.FromJson<AudioList2893>（AudioInfos，Name/Length string），4000632=GetModule<UIModule3558>。AudioConfigReader只实现已证据化且Main选择的UnityJson路径，modern/binary路由不冒充完成。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';q=p.read_text(encoding='utf8').replace('959 项 checks','978 项 checks').replace('caseCount=959；latestValidation 为 native UpdateManager/audio','caseCount=978；latestValidation 为 native AudioManager ownership').replace('in_progress / update-manager-native-audio','in_progress / audio-manager-native-ownership').replace('最新集成日志 analysis/update-manager-integrated.log。959集成、23原生UpdateManager/TimeModule/音频链通过（loader为fixture，shared update为实际MonoBehaviour，timer为完整源码实现）；','最新集成日志 analysis/audio-manager-integrated.log。978集成、18原生AudioManager/原表/UpdateManager/TimeModule/音频链通过（clip/config传输为fixture adapter，manager/node/update/timer为真实实现）；');p.write_text(q+text,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgameAudioManagerNativeOwnership','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/AUDIO_MANAGER_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps(dict(checks=978,nativeChecks=18,fingerprints=len(files),sourceMethods=len(methods),methodMap=len(mm))))
