from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==519
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='fly-tool-animation-coroutine';s['validation'].update(integratedChecksPassed=519,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['fly-tool-animation-coroutine']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4057-31241.txt','disassembly/Type4055-31235.txt','disassembly/Type4056-31237.txt','disassembly/Type4058-31218.txt','fly-tween-cleanup-generics.json'],'implementation':['OutgameFlyToolAnimation.cs'],'scope':'Source IEnumerator with shared WaitForSecondsRealtime, real prefab spawn callback wiring, two movement stages and cleanup commands; actual tween/pool host remains pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Source fly-tool animation coroutine') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Source fly-tool animation coroutine','checksPassed':519,'outgameChecksPassed':252,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Fly source wait usage3941924 resolves to WaitForSecondsRealtime6855. Each icon yields shared .025s object; final wait uses shared1.1s object. Source movement is .4s OutCirc21 then .5s InCirc20, both independent update. Return completion wires collection; final coroutine queues StopEffect then kills global Target_Tween with complete=false.','source':['disassembly/Type4057-31241.txt','disassembly/Type4055-31235.txt','disassembly/Type4056-31237.txt','disassembly/Type4058-31218.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'FLY_TOOL_ANIMATION_AUDIT.json';write(p,{'status':'coroutine_and_native_callback_wiring_verified_tween_host_pending','checks':519,'source':['disassembly/Type4057-31241.txt','disassembly/Type4055-31235.txt','disassembly/Type4056-31237.txt','disassembly/Type4058-31218.txt','fly-tween-cleanup-generics.json'],'verified':['Original WaitForSecondsRealtime type6855 from usage3941924; shared .025s and1.1s objects, unscaled','Native recovered icons parented with source world position and unit scale','Scatter .4s ease21 OutCirc; arrival .5s ease20 InCirc; independent tween update','Spawn completions feed next stage and collection; actual native Text reaches final amount once','After final wait queue StopEffect then global Target_Tween kill complete=false'],'testScope':'IEnumerator advanced directly and tween completions invoked by test host; proves callback sequencing/native assets, not measured animation timing or visual fidelity','pending':['Concrete tween executor, target pulse and pool host','Original random scatter algorithm and global sub-id registry','Audio wrappers/real top-info targets and ShopUI production composition','Dynamic runtime visual verification']})
note='\n\n## 飞行动效协程流程（519项）\n新增OutgameFlyToolAnimation，按原协程串起图标生成、散开0.4s/OutCirc21、归位0.5s/InCirc20、收集和结束清理。确认等待类型为WaitForSecondsRealtime：逐个生成共享0.025s等待对象，末尾共享1.1s等待对象；Tween独立更新。真实恢复Prefab/Text参与测试，尾部先StopEffect排队再Kill全局Target_Tween(complete=false)。519项（战斗267+关外252）通过，Unity退出0。测试直接推进IEnumerator并由测试宿主触发Tween完成，尚未验证实际动画计时/动态画面；具体Tween/池宿主、随机散点、音频及页面组合待继续。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameFlyToolAnimation','--result','pass','--evidence','519 integrated checks; source coroutine realtime waits, native asset callback wiring and cleanup ordering verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded519; full goal remains active.')
