from pathlib import Path
import json,hashlib,datetime,subprocess
W=Path(__file__).resolve().parent.parent;T=W/'analysis/targets/wxcf1394487200e48f/43';O=T/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();r=read(W/'analysis/unity-integrated-validation.json');n=read(W/'analysis/player-control-native-validation.json');assert r['passed'] and len(r['checks'])==792;assert n['passed'] and len(n['checks'])==10
v={'atUtc':now,'scope':'Player4462 lifecycle/model owners/home animation timers/native source category drag/touch scene raycast, shared registry/LogicModule','checksPassed':792,'newIntegratedChecks':14,'nativePlayModeChecks':10,'freshPlayModeRun':True,'freshPlayerBuild':False,'freshPlayerSmoke':False,'commands':['BattleBuild.ValidateMechanicsOnly','OutgamePlayerControlPlayModeValidation.Run'],'notClaimed':'Shared source InputManager production host, all skin resource imports, full actual Main/account/platform/UI integration or complete outgame Player build'}
a={'atUtc':now,'status':'partial-subsystem','sourceEvidence':'PLAYER_CONTROL_SOURCE_EVIDENCE.json','verification':v,'findings':[
 'OutgamePlayerControl4462 now implements OnInit/Updata/OnDispose, native models/animations, rotation events, selection, visibility, first-ad counter reset, equipped/random skin delegation and native scene touch. Actual BindPlayer factory resolves shared controller. Ten lifecycle implementations are method-level coverage, not ten complete gameplay controllers.',
 'OnInit installs LoadGameScreen, RotateSoldier then touch; repeated initialization adds duplicate subscriptions. OnDispose clears registry then only animation cache before one-at-a-time listener removal. Roots/models/selection/timers and native objects remain. InitLoadModel reads GameScene roots independently, resets model dictionary then Dictionary.Add retained roots1/2/3, captures positions then scales then three equipped skin loads. Reentry source duplicate-root exception preserved with partial reset.',
 'Home state2 increments all scaled timers first, strict>11.7/13.7/14.7, zeros before once-only refresh; no remainder/catch-up. Periodic refresh catches System.Exception into source warning array. Page2 drag is checked independently from home state. Button down must be above integer half-height, horizontal range200, six ordered transform writes, release strict>.3, wrapped selection and ChooseSoldier before finger clear. Page change/hidden root retains drag state.',
 'OutgameModelRotation now shares mutable controller fields for both event selection and drag. Event selection changed from paired position/scale writes to exact all-positions-before-scales source order, retaining first position on a later missing-root failure.',
 'Original TagManager layer names restored at existing source indices8..31; only previously blank slots filled and nonblank conflicts asserted absent. Scenes11 is31. Touch gate Levelstate2/UIpage3 then HomeCamera ray to floatMax with 1<<NameToLayer, cached hit and xy write preserving z. Native hit Animator is resolved twice before Trigger, matching source.',
 'Original source model callback reads placement188 and scale184 live, separate from raypoint172; controller now provides those getters. Animation uses live SkinCatalog and source native Unity-null check for destroyed cached components. Existing model dictionary replacement and completion fallback behavior retained.',
 'Native PlayMode drives actual Player via LogicModule and LoadGameScreen over original imported roots, three original baked models and source prefab loader. Native drag/ChooseSoldier, ray hit/Animator trigger, relax-to-idle completion, timed refresh, shutdown and late captured fallback all pass. Input events and collider/AnimatorController are explicit test probes, not original SDK or matched scene-interaction content.',
 '792 integrated (14 new) and10 new native checks pass. Corrected stale lifecycle matrix generator: Level4107 was implemented earlier but matrix still said8; matrix and audit now agree on10/38, remaining28. No source inference from empty lifecycle bodies.'
 ],'remaining':[
 'Restore actual shared InputManager host and remaining28 controllers; supply full UI/Main/module/account entry. Complete skin/native resource set and matched UI interactions.',
 'Finish remaining Level/Tower/Soldier/WayLine/AI/effect services and actual state/prepared/UI production composition without replacing existing independent combat kernel.',
 'Every full objective subsystem and persistence/restart/failure/return-flow plus runnable Player build acceptance remain open.'
 ],'artifacts':{'integratedLog':'analysis/player-control-integrated-final.log','nativeLog':'analysis/player-control-native.log','nativeReport':'analysis/player-control-native-validation.json'},'disassembledMethodMapCount':4681}
write(O/'PLAYER_CONTROL_NATIVE_AUDIT.json',a)
p=O/'CONTROLLER_LIFECYCLE_AUDIT.json';d=read(p);d.update(atUtc=now,playerControllerAudit='PLAYER_CONTROL_NATIVE_AUDIT.json',verification=v,remainingControllerCount=28);d['implementedControllerTypes']=list(dict.fromkeys(d['implementedControllerTypes']+[4462]));d['implementations']['4462']='OutgamePlayerControl.cs';d['sourceMethods']=list(dict.fromkeys(d['sourceMethods']+[34199,34196,34206]));d['remaining'][0]=a['remaining'][0]+' '+a['remaining'][1];d['findings'].append('Player4462 actual registry binding/lifecycle and native model/input slice passed. Matrix generator synchronized with earlier Level4107 plus Player4462:10/38 lifecycle implementations, remaining28; full source InputManager/Main/account/assets still pending.');write(p,d)
p=T/'OUTGAME_RESTORE_STATE.json';d=read(p);d.update(lastUpdatedAtUtc=now,currentStage='player-controller-native-input-models',playerControllerAudit='generated/outgame/PLAYER_CONTROL_NATIVE_AUDIT.json',nextPriority='Restore shared source InputManager and remaining28 real controller lifecycles, supply actual Main/module/config/account/menu/entry composition. Finish remaining Level/Tower/Soldier/WayLine/AI/effect services and native resource set. Complete every objective outgame subsystem, persistence/restart/failure/return-flow and runnable Player acceptance; no fake platforms.');d['validation']['integratedChecksPassed']=792;d['validation']['playerController']=v;d['validation']['playerControllerNative']=n;d['milestones']=[m for m in d['milestones'] if m['id']!='player-controller-native-input-models'];d['milestones'].append({'id':'player-controller-native-input-models','atUtc':now,'status':'partial-subsystem','integratedChecks':792,'nativeChecks':10,'remainingLifecycleControllers':28});write(p,d)
p=W/'analysis/VALIDATION_MANIFEST.json';d=read(p);d.update(atUtc=now,caseCount=792,latestValidation=v);d['validationHistory'].append(v)
if 'analysis/player-control-native-validation.json' not in d['reports']:d['reports'].append('analysis/player-control-native-validation.json')
files=[f for f in (W/'UnityProject/Assets/AreaBattle').rglob('*') if f.is_file() and (f.suffix.lower() in ('.cs','.shader','.json','.prefab','.mat','.unity','.txt','.bytes','.ttf','.otf','.spriteatlas','.anim','.controller') or '/FirstPack/' in f.as_posix() or '/Recovered/Loading/' in f.as_posix())];files.append(W/'UnityProject/ProjectSettings/TagManager.asset');d['sourceFingerprints']=[{'path':f.relative_to(W).as_posix(),'sha256':hashlib.sha256(f.read_bytes()).hexdigest()} for f in sorted(files)];write(p,d)
text='''\n\n## 2026-09-30 Player控制器、模型交互与原生生命周期增量\n- OutgamePlayerControl4462已绑定共享registry，连接真实GameControl/Level/UI/皮肤/模型与加载器；OnInit/Updata/OnDispose按源顺序。LoadGameScreen先Game.InitScene再InitLoadModel；重复InitLoadModel先换模型字典、后Roots.Add重复失败；不虚构去重/清对象。\n- 主页3动画计时先全部累加，再严格>11.7/13.7/14.7清零刷新；周期刷新捕获Exception并保留源warning。Page2拖动独立gate、200像素、严格>.3切换、3position后3scale、ChooseSoldier先于finger清除。事件旋转与拖动共享状态。\n- TouchBegin gate state2/page3，HomeCamera原生射线、Scenes11=31、floatMax距离、xy更新/z保留与Animator.Trigger；原包TagManager图层8..31补回空槽，未覆盖已有冲突图层。\n- Models回调位置188与scale184 live读取，raypoint172分离；animation实时SkinCatalog，native destroyed animator按Unity null处理。OnDispose只清animation缓存与监听，保留root/model，迟到动画完成仍走源fallback。\n- 792集成（新增14）+10 Player原生PlayMode通过。原生真实LogicModule/场景/原始模型/烘焙动画；鼠标touch和点击Collider/AnimatorController为明确probe，不声称设备输入、原始动态场景或账号接通。\n- O/PLAYER_CONTROL_NATIVE_AUDIT.json、PLAYER_CONTROL_SOURCE_EVIDENCE.json（28方法/26字段+原始图层证据）；日志analysis/player-control-integrated-final.log、player-control-native.log。无本任务待续进程。\n- 修复生命周期matrix生成器遗漏此前Level4107的问题；当前10/38方法级实现，剩28，不代表10完整业务控制器；method-map4681。\n- 下一步共享InputManager、剩28实际控制器、Main/module/account/menu；保留Level/Tower/Soldier/WayLine/AI/effect剩余范围、全部关外子系统与持久化/重启/失败/返回/Player验收。完整goal保持active，无新Player构建。\n'''
for p in (T/'REVERSE_PROGRESS.md',T/'RESTORE_PROGRESS.md',W/'analysis/VALIDATION_REPORT.md'):
 with p.open('a',encoding='utf8') as f:f.write(text)
p=W/'AREA_BATTLE_HANDOFF.md';s=p.read_text(encoding='utf8').replace('778 项 checks','792 项 checks').replace('caseCount=778；latestValidation 为 Level reset/pools/effects/queries','caseCount=792；latestValidation 为 Player controller/native input/models').replace('in_progress / level-reset-pools-effects-queries','in_progress / player-controller-native-input-models').replace('最新method-map4681；9控制器生命周期/共享绑定已实现并验证，剩29（仅生命周期方法计数，并非完整业务图）。','最新method-map4681；10控制器生命周期/共享绑定已实现并验证，剩28（仅生命周期方法计数，并非完整业务图）。').replace('最新集成日志 analysis/level-query-integrated.log；Level重置原生日志 analysis/level-reuse-native.log。778集成+10 Level重置原生通过；','最新集成日志 analysis/player-control-integrated-final.log；Player原生日志 analysis/player-control-native.log。792集成+10 Player原生通过；历史Level重置10项通过；');s+=text;p.write_text(s,encoding='utf8')
script='C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py';base=['python','-X','utf8',script];common=['--project-root',str(W),'--target','wxcf1394487200e48f/43']
for kind,path in [('validationManifest','analysis/VALIDATION_MANIFEST.json'),('validationReport','analysis/VALIDATION_REPORT.md')]:
 result=subprocess.run(base+['record-artifact']+common+['--kind',kind,'--path',path],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
result=subprocess.run(base+['set-check']+common+['--name','outgamePlayerControllerNative','--result','pass','--evidence','analysis/targets/wxcf1394487200e48f/43/generated/outgame/PLAYER_CONTROL_NATIVE_AUDIT.json','--depends-on','unityProject','--depends-on','validationManifest'],capture_output=True,text=True,encoding='utf8');assert result.returncode==0,result.stderr
print(json.dumps({'checks':792,'native':10,'fingerprints':len(files),'lifecycleImplementations':10,'remaining':28}))
