from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-baked-animation-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==356
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='baked-model-animation';s['validation'].update(integratedChecksPassed=356,bakedAnimationChecksPassed=2);s['nextActions']=['Recover source display roots, scale, position and attack display prefab variant; expand skin model assets.','Connect model provider, baked animator, coloring, shop effects and account lifecycle.','Complete remaining outgame systems and fresh full playable build/end-to-end validation.'];write(p,s)
sources=['disassembly/Type4523-'+str(i)+'.txt' for i in [34490,34492,34493,34498,34502,34503,34504,34506,34507,34509]]+['disassembly/NativePauseRemainder-1272.txt','baked-model-clips.json']
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['baked-model-animation']={'implementationReady':True,'productionConnected':False,'source':sources,'implementation':['OutgameBakedAnimator.cs','OutgameBakedModelImporter.cs'],'assetCoverage':['soldier_100','soldier_102','soldier_200','soldier_300'],'rules':['Source clip mesh choice and property block timing, preserved color; explicit shader clock matches selected source clock.','Nonloop strict f32 end comparison, reset before callback, clear callback after invocation, default autoplay only if callback leaves no current clip.','Pause uses fmod phase; paused Play queues only name; Resume restarts queued name looping. Reset retains completion callback.'],'pending':'Remaining models including attack display prefabId+1000, scene roots, original coloring and production wiring.'};write(p,s)
p=o/'PLAYER_DISPLAY_AUDIT.json';s=read(p);s['confirmed'].append({'fact':'Baked renderer implemented against actual four imported source clip lists. wasmcode1 Pause table109163 resolves wasmcode f1272, float remainder implementation. Source f32 addition at completion needs explicit rounding under Unity Mono; strict boundary regression caught and fixed. No source clip in imported four needs alternate mesh.','source':sources});s['pending']=['Soldier.SetSoldierColor adapter and full skin/attack display asset coverage','Original display roots/camera and model source transform constants','Swipe/rotation and production lifecycle'];write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original SpineAnimator baked renderer') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Baked mesh animator and four original model prefabs','checksPassed':356,'outgameChecksPassed':89,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'All skin models, original shop scene or playable lobby'};write(p,s)
note='\n\n## 关外烘焙模型动画（356项）\n新增 OutgameBakedAnimator 与独立模型导入器，以原 animationData 和现有原始网格/材质生成关外 soldier_100/102/200/300 四个预制体；不改战斗预制体。实现渲染属性、默认播放、缺动画回退、暂停/恢复、完成回调顺序。严格完成边界测试发现并修复 Mono 中间精度与 WASM f32 加法的差异。Unity导入和验证退出0，356项通过（原267+关外89）。这是四个模型及动画控制验证，其他皮肤/攻击展示变体、原始场景节点、生产接线和完整关外仍待完成。\n'
for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameBakedModelAnimation','--result','pass','--evidence','356 integrated checks; four original models and baked animation state verified; full goal incomplete.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded356; full goal remains active.')
