from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==515
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='shop-feedback-fly-grant';s['validation'].update(integratedChecksPassed=515,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['shop-feedback-fly-grant']={'implementationReady':True,'productionConnected':False,'source':['disassembly/Type4408-33778.txt','disassembly/Type4408-33788.txt','disassembly/Type4408-33779.txt','disassembly/Type4408-33801.txt','disassembly/Type4058-31217.txt','disassembly/Type4053-31227.txt','disassembly/Type4256-32536.txt'],'implementation':['OutgameShopFeedback.cs','OutgameFlyToolStart.cs'],'scope':'Native tool-value label, video success-to-effect callbacks, source NewFlyTool inventory/scheduling entry; actual video event registration, audio wrappers and animation coroutine host still pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Native ShopUI feedback and source fly-tool grant entry') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Native ShopUI feedback and source fly-tool grant entry','checksPassed':515,'outgameChecksPassed':248,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'ShopUI video success callbacks request50 gold/20 diamonds at source button position. NewFlyTool with missing target returns-1 without grant; otherwise allocates id, resolves root, applies inventory before starting/tracking coroutine and timestamp. ToolChange overload sets notify/report true and refreshTop false. Native label uses localized ShopUI.toolvalue1 plus ToolValue.','source':['disassembly/Type4408-33801.txt','disassembly/Type4408-33779.txt','disassembly/Type4058-31217.txt','disassembly/Type4256-32536.txt'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'SHOP_FEEDBACK_AUDIT.json';write(p,{'status':'native_feedback_and_fly_entry_verified_animation_host_pending','checks':515,'sourceMethodsIndexed':1940,'source':['disassembly/Type4408-33778.txt','disassembly/Type4408-33788.txt','disassembly/Type4408-33779.txt','disassembly/Type4408-33801.txt','disassembly/Type4058-31217.txt','disassembly/Type4053-31227.txt','disassembly/Type4256-32536.txt'],'verified':['Original native tool-value text refresh ignores event payload','Failed video callback has no effect request','Successful gold/diamond callback forwards50/20, effectRoot, source button world position and flags true/0/true','Missing currency target suppresses NewFlyTool grant and scheduling','Real inventory grant/report/save occurs before animation; no immediate top refresh','Animation failure preserves prior grant and prevents subsequent tracking'],'pending':['Source effect animation coroutine and cleanup','FlyMoney/FlyDiamonds audio and real currency-target wrappers','Bind live video completion handlers during ShopUI.OpenLater and remove listeners on Dispose','Full page lifecycle and account providers']})
note='\n\n## ShopUI数量刷新与广告飞行动效入账边界（515项）\n新增OutgameShopFeedback绑定原txt_toolValue，按ShopUI.toolvalue1+ToolValue刷新；ToolChange忽略事件参数。两个广告完成回调成功才请求50金币/20钻石，保留原effectRoot、按钮世界坐标和true/0/true参数。追踪EffectControl.NewFlyTool确认目标为空不发奖，否则先分配ID/补默认root，再真实ToolDispatcher入账、通知/上报/保存，最后启动并登记动画/时间；不刷新顶部数值。新增OutgameFlyToolStart恢复此入口，验证动画启动异常不会回滚已到账奖励。515项（战斗267+关外248）通过，Unity退出0。实际动画协程、音频包装、平台视频注册及完整页面/账号连接仍待恢复；未生成新Player构建。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameShopFeedbackFlyGrant','--result','pass','--evidence','515 integrated checks; native ShopUI feedback, video result arguments and source fly-tool immediate grant verified; full store page and account integration pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded515; full goal remains active.')
