from pathlib import Path
import json,subprocess
from datetime import datetime,timezone
w=Path(__file__).resolve().parent.parent;t=w/'analysis/targets/wxcf1394487200e48f/43';o=t/'generated/outgame'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
r=read(w/'analysis/unity-integrated-validation.json');v=read(w/'analysis/outgame-login-sync-validation.json');assert r['passed'] and v['passed'] and len(r['checks'])==496
p=t/'OUTGAME_RESTORE_STATE.json';s=read(p);s['lastUpdatedAtUtc']=datetime.now(timezone.utc).isoformat();s['currentStage']='global-item-persistence';s['validation'].update(integratedChecksPassed=496,loginSyncChecksPassed=len(v['checks']));s['nextActions']=['Implement source registered manager providers and original data key/save semantics, then connect UserLogin data reload/upload/download.','Trace first LevelID assignment and connect account initialization to menu.','Complete remaining outgame systems and runnable end-to-end build.'];write(p,s)
p=o/'OUTGAME_RESTORE_SPEC.json';s=read(p);s['subsystemGates']['global-item-persistence']={'implementationReady':True,'productionConnected':False,'source':['global-item-save-generics.json','disassembly/Type4542-34576.txt','disassembly/Type4542-34579.txt'],'implementation':['OutgameGlobalItemPersistence.cs'],'scope':'Rebuild live product list then item list; timestamp after lists; original double host time call and reentrant data assignment. Full init/update/reward lifecycle and provider pending.'};write(p,s)
p=o/'golden-cases.json';s=read(p);ids={c['id'] for c in s['cases']};s['cases'] += [dict(c,sourceContract='Original global item save and clock semantics') for c in v['checks'] if c['id'] not in ids];write(p,s)
p=w/'analysis/VALIDATION_MANIFEST.json';old=read(p);subprocess.run(['python',str(w/'analysis/record_validation_manifest.py')],check=True);s=read(p)
for k,val in old.items():
 if k not in s:s[k]=val
s.setdefault('validationHistory',[]).append(old.get('latestValidation',{}));s['latestValidation']={'scope':'Original global item save and clock semantics','checksPassed':496,'outgameChecksPassed':229,'freshPlayerBuild':False,'freshPlayerSmoke':False,'notClaimed':'Full scene, aspect adaptation, all skin assets or playable lobby'};write(p,s)
p=o/'ACCOUNT_STARTUP_AUDIT.json';audit=read(p);audit['sourceMethodsIndexed']=len(read(o/'method-map.json'));audit['confirmed'].append({'fact':'Global save clears and rebuilds product then item lists from live dictionaries, captures timestamp target before clock callbacks and rereads data for JSON serialization. Host clock called twice, local clock once when absent.496 checks pass.','source':['global-item-save-generics.json','disassembly/Type4542-34576.txt','disassembly/Type4542-34579.txt'],'implementation':['OutgameGlobalItemPersistence.cs'],'validation':'analysis/outgame-login-sync-validation.json'});write(p,audit)
p=o/'GLOBAL_ITEM_MANAGER_AUDIT.json';audit=read(p);audit['status']='records_indexes_save_implemented_lifecycle_pending';audit['saveImplementation']={'files':['OutgameGlobalItemPersistence.cs'],'checks':496,'source':['global-item-save-generics.json'],'detail':'Product then item live lists rebuilt in place before timestamp; no snapshot or dirty mutation; original double clock callback and reentrant Data target behavior preserved.'};audit['pending']=['Implement full GlobalItemManager init and timestamp conversion','Implement update/time/statistics/reward side effects','Connect real ItemManager4500 registration provider; keep LocalData Int32 inventory distinct','Trace StoreDataManager manual activation separately'];write(p,audit)
note='\n\n## 全局物品保存与时钟（496项）\n新增global-item-save-generics.json，恢复先商品后物品的live字典列表重建、完成列表后更新时间戳和JSON序列化。原时钟有host时调用两次，否则使用本地时间；保留回调替换Data时旧对象接收时间戳而新对象序列化的行为。496项（战斗267+关外229）通过，Unity退出0。初始化总流程、时间转换/统计/奖励及实际4500Provider尚待完成，目标未完成。\n'

for p in [w/'AREA_BATTLE_HANDOFF.md',w/'RESTORE_PROGRESS.md',w/'analysis/VALIDATION_REPORT.md',t/'REVERSE_PROGRESS.md']:p.write_text(p.read_text(encoding='utf8')+note,encoding='utf8')
b=['python','C:/Users/jiachengwei/.codex/skills/wechat-minigame-reconstruction-orchestrator/scripts/orchestrate.py'];a=['--project-root',str(w),'--target','wxcf1394487200e48f/43']
for kind,p in [('unityProject',w/'UnityProject'),('validationManifest',w/'analysis/VALIDATION_MANIFEST.json'),('validationReport',w/'analysis/VALIDATION_REPORT.md')]:subprocess.run(b+['record-artifact']+a+['--kind',kind,'--path',str(p)],check=True,capture_output=True)
subprocess.run(b+['set-check']+a+['--name','outgameGlobalItemPersistence','--result','pass','--evidence','496 integrated checks; source live list save order, timestamp, callback reentrancy and clock fallback verified; full lifecycle pending.','--depends-on','unityProject','--depends-on','validationManifest'],check=True,capture_output=True)
print('Recorded496; full goal remains active.')
