"""Persist bounded special-mode reachability evidence without changing shared spec."""
import hashlib,json,subprocess,sys
from pathlib import Path
R=Path(__file__).parent/'targets/wxcf1394487200e48f/43';G=R/'generated'
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def w(a,b,module='wasmcode'):return f'generated/wasm/{module}.wasm:0x{a}-0x{b}'
def rule(id,value,*refs,status='confirmed-static'):return dict(id=id,status=status,value=value,evidence=list(refs))
rules=[
rule('level-type-is-tutorial-sequence',{'fieldType':'int[]','consumer':'ConfigMgr.IsGuideLv(level): require direct dicLevel contains level, index=SmallLevelIndex capped to array.Count-1, return LevelType[index]==1. No GetLevelRealID/wrap in this query.','notBattleMode':'Observed LevelType consumer selects guide status; it does not create Boss or select soldier behavior.'},w('3a948e','3a9580')),
rule('special-current-level',{'normal':'SpecialLevel==0: CurLevel reads LocalData gameplay.currentLevel; setter writes it and saves.','special':'SpecialLevel!=0: CurLevel reads LevelControl field16. Normal CurLevel setter does nothing.','loader':'Both load functions bypass LevelConfig.SceneId remapping when SpecialLevel!=0 and use the supplied direct layout ID.'},w('67c06','67c21'),w('1ffedb','1fff34'),w('56a3a3','56a3db'),w('56a595','56a5c7')),
rule('festival-boss-entry',{'SpecialLevel':1,'entry':'FestActUI callback sets SpecialLevel1 and field16 from festival manager indexed selection, then Enter.','layoutSelector':'dicSummerReward[2].giftWay[index]','cachedLayouts':[99998,99999],'bossActions':[998,999],'sceneSkin':'InitSpecialScene uses activity award ID for scene skin when SpecialLevel1; does not alter tower config.'},w('a69db0','a69e22','wasmcode1'),w('51ab91','51ac2b','wasmcode1'),'tables/SummerRewardConfig.json:id2.giftWay',w('56ad19','56ad96')),
rule('daily-challenge-entry',{'SpecialLevel':2,'entry':'DailyChaallengeItem callback stores GetChallengeLevel result in LevelControl field16, then Enter3.','layoutSelector':'DailyChallengeActivity.GetChallengeLevel resolves current/selected challenge index, calls DailyChallengeData.GetLevel; reads saved dictionary field32 entry[index].field12.','mechanics':'This entry uses the same serialized tower loader. No boss-flag patch observed along this path.','remaining':'Persisted pool last-entry consumption and selector recovered in pvp-evidence; pool initialization/refill remains unknown.'},w('140cdbd','140ce0f','wasmcode1'),w('b07dac','b07dd3','wasmcode1'),w('4c52a6','4c52bf','wasmcode1')),
rule('loader-boss-source',{'normalAndSpecial':'OnLevelCfgLoad deserializes layout then InitGameByLevelConfig; callback15186 invokes tower factory11599 before obstacles. Factory reads StarInfoCfg.isBoss offset56 directly and chooses Boss factory only when true, else ordinary/Arrow factory based on ShipID52.','bossAction':'AICampController.InitInfo consumes StarInfoCfg.bossSkillId60 only on a Star marked isBoss; CampInfoCfg.BossActionId alone does not activate a Boss.','patchScan':'Instruction-aware scan of all mapped Assembly-CSharp bodies found9 offset56 byte-store method entries. Three LevelEditorManager methods construct StarInfoCfg and copy editor-component isBoss20/bossSkillId24 into fields56/60. Other stores belong to PVP/controller/line/SkillItem objects. No runtime loading path writing StarInfoCfg.isBoss was identified.','scopeLimit':'This is a bounded mapped-body direct byte-store scan and traced loader path, not a proof against arbitrary reflection, bulk memory copies, editor-only path activation or downloaded code.'},w('81faa2','81fb74'),w('37a6d6','37a729'),w('708548','708559'),w('56ac48','56acd9'),w('1236ad7','1236af9','wasmcode1'),w('1237844','1237866','wasmcode1'),w('1235d57','1235d79','wasmcode1'),'analysis/special_field_stores_result.json','combat-evidence.json:boss-schedule-creation'),
rule('boss-victory-exact',{'priority':['If player camp has zero active towers: Defeat.','If player tower count >= initial tower count: Victory.','Otherwise if curBoss reference exists and trunc_toward_zero(curBoss.Score)<=0: Victory.'],'importantBoundary':'Boss score0.5 satisfies victory; score1 does not. No Active check on curBoss in this branch. Last Boss assigned in the serialized tower loop is retained as curBoss.'},w('163a92','163abc'),w('163b10','163b68'),w('379ee5','379ef1'),w('56ac8d','56aca0')),
rule('normal-victory-progress',{'victoryState8':'clears SmallLevelIndex to0 and opens win UI','winUIOpenLater':'normal progression increments CurLevel exactly once on Proj_xqzdOverUI.OpenLater; setter ignores special modes','close':'OverUI.CloseSelf sends Exit11, which leaves battle; do not increment again on result-close/next wrapper','skipJump12':'separate explicit branch clears data, increments CurLevel, enters Enter3','sublevelAdvance14':'clears data, increments SmallLevelIndex, enters Enter3; main loader still only consumes typed SceneId, not legacy SceneId2..10.'},w('37a47d','37a483'),w('7a3768','7a3783'),w('7a3bcd','7a3bd3'),w('37a574','37a5a4'),w('37a5db','37a5fb')),
rule('level-speed-no-configuration-mutation',{'SetLevelSpeed':'stores current LevelConfig reference284; gameTimeScale=baseScale*1; another static value28=base24*1. Does not read LevelType or mutate StarInfoCfg.','channel':'InitChanelData reads online hcrzd_ABtest and stores parsed int268; this body does not swap dicLevel/dicLevelB. Exact remote channel effects remain unobserved.'},w('5df8fc','5df9cf'),w('5e013e','5e01c4')),
rule('comm04-state-vs-multiplier',{'Mode6':'Adds effect420 to generated soldiers. Does not itself multiply attack/regen/spawn/speed.','actualSkill11':'Commander4 skills[1].inSkill and matching camp gate GetSpawnRate*=args1 and GetSoldierSpeed*=args0; setting Tower.Mode6 alone is insufficient to activate those modifiers.','attack':'Skill13 applies attack+99 and occupy multiplier to newly initialized own soldiers; Skill16 sets attack and reinforce0 for new enemy soldiers. These are separate initialization consumers.'},'combat-evidence.json:commander4-speed','combat-evidence.json:spawn-batches','combat-skill-coverage.json:skills11/13/16'),
rule('buff-and-rain-consumers',{'buffs':'Tower spawnRate and regen riseRate use products; batchX2/X3 chances use maxima and testX3 is tested first. Tower.InitBuff and BuffControl.Updata are nop; injection provenance remains unknown.','rain':'Mode3 changes spawn-rate base to GameSceneControl.rainSpawnMultiplier; BossConfig action for camp6 initializes that base and rainDamage. It is not an independent timed enemy-wave system.','plain':'Ordinary AI creates directions; no additional wave-spawn timer in recovered LevelControl.Update.'},'combat-evidence.json:spawn-multiplier','combat-evidence.json:regeneration','combat-evidence.json:buff-lifecycle-stubs','combat-evidence.json:boss-skill-parameters','flow-evidence.json:ordinary-wave-scope'),
rule('pvp-independent-battle-branch',{'gate':'PVPController flag8 true enables OnGamePlayState and Updata; same controller active flag causes ordinary LevelControl.RefreshCampInfo to skip normal outcome evaluation.','setup':'PVP Enter gets ArenaControl combat map and enemy record, chooses AI/Commander, determines enemy camp in2..4, creates Commander through CommanderSkillFactor and initializes3 AgentSkillUse entries.','update':'WhileRunning, updates active AgentSkillUse with dt*gameTimeScale; separately calls enemy Commander virtual update with original dt.','scope':'Confirmed extra in-level mechanics, not covered by ordinary AICampController + player Commander alone. Agent clocks, targeting and score outcome now recovered in pvp-evidence; matchmaking/model tactical line actions remain unknown.'},w('7e1556','7e15c6'),w('5401cf','5402bc'),w('7e099d','7e09b6'),w('7e0ad0','7e0af9'),w('7e0b94','7e0bc1'),w('163a82','163a90'))
]
levels=[]
for p in sorted((G/'all-levels').glob('*.json')):
 d=load(p)
 if 'StarInfoCfgs' in d:levels.append((int(p.stem.split('_')[-1]),d))
bosses=load(G/'tables/BossConfig.json')['Datas'];coverage=[]
for row in bosses:
 id=row['id'];star=[];camp=[]
 for level,d in levels:
  for i,s in enumerate(d['StarInfoCfgs']):
   if s.get('isBoss') and s.get('bossSkillId')==id:star.append({'layout':level,'towerId':i+1,'camp':s['CampID']})
  for c in d.get('CampInfoCfgs',[]):
   if c.get('BossActionId')==id:camp.append({'layout':level,'camp':c['CampID']})
 coverage.append({'bossConfigId':id,'status':'serialized-active-branch' if star else 'not-activated-by-scanned-layout-loader','activeStars':star,'campConfigReferences':camp,'qualification':'No live observation; CampInfo.BossActionId alone is not the active loader binding.'})
normal=load(G/'tables/LevelConfig.json')['Datas'];other=load(G/'tables/LevelBConfig.json')['Datas']
dataCoverage={'levelCount':len(levels),'mainGuideRows':[{'level':r['id'],'sceneId':r['SceneId'],'LevelType':r['LevelType']} for r in normal if 1 in r['LevelType']],'BGuideRows':[{'level':r['id'],'sceneId':r['SceneId'],'LevelType':r['LevelType']} for r in other if 1 in r['LevelType']],'bosses':coverage,'modes':[{'id':'normal','mechanics':'ordinary+arrow+player commander+guide','binding':'LevelControl.SpecialLevel0; main LevelConfig.SceneId','staticCoverage':'confirmed'},{'id':'festival','mechanics':'Boss998/999 onlayouts99998/99999','binding':'SpecialLevel1, SummerRewardConfig[2].giftWay','staticCoverage':'confirmed'},{'id':'daily','mechanics':'ordinary layout selected from challenge mapping','binding':'SpecialLevel2','staticCoverage':'loader and saved-pool last-entry consumption confirmed; pool initialization/refill unresolved'},{'id':'arena-pvp','mechanics':'enemy Commander and AgentSkillUse plus independent result handling','binding':'PVPController active flag','staticCoverage':'entry/update/agent targeting/result confirmed in pvp-evidence; Arena/model line policy unresolved'}]}
selected=[(8085,'wasmcode'),(1254,'wasmcode'),(5934,'wasmcode'),(5935,'wasmcode'),(11600,'wasmcode'),(11599,'wasmcode'),(7631,'wasmcode'),(15186,'wasmcode'),(18901,'wasmcode'),(4384,'wasmcode'),(7629,'wasmcode'),(7630,'wasmcode'),(18080,'wasmcode'),(18083,'wasmcode'),(12783,'wasmcode'),(12787,'wasmcode'),(28375,'wasmcode1'),(15032,'wasmcode1'),(66176,'wasmcode1'),(30228,'wasmcode1'),(14264,'wasmcode1'),(18347,'wasmcode'),(18343,'wasmcode'),(11175,'wasmcode'),(42844,'wasmcode1'),(58388,'wasmcode1'),(58389,'wasmcode1'),(58387,'wasmcode1')]
dis=[]
for f,m in selected:
 p=subprocess.run([sys.executable,str(Path(__file__).parent/'flow_disassemble.py'),'@'+str(f),m],capture_output=True,encoding='utf-8',check=True)
 assert 'offset=' in p.stdout
 dis.append({'module':m,'function':f,'text':p.stdout})
out={'target':{'appId':'wxcf1394487200e48f','version':'43'},'mode':'static-only, bounded mapped-method/serialized-layout analysis','rules':rules,'coverage':dataCoverage,'functions':dis,'scanSources':['analysis/special_callers.py','analysis/special_field_stores.py'],'unknowns':['PVP Arena matchmaking/model tactical line policy remain unresolved; see pvp-evidence for confirmed agent and outcome rules.','Daily pool initialization/refill not recovered; saved-pool last-entry consumption confirmed.','LevelB remote-channel reachability not established.','All nine typed guide rows now covered by guide-evidence; visual/runtime equivalence still requires separate validation.','Boss direct-store scan cannot prove absence of reflection or bulk-copy mutations outside traced loading path.'],'fullGoalComplete':False,'sourceHashes':{m:hashlib.sha256((G/'wasm'/m).read_bytes()).hexdigest() for m in ['wasmcode.wasm','wasmcode1.wasm']}}
(G/'special-mode-evidence.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
(G/'special-mode-coverage.json').write_text(json.dumps(dataCoverage,ensure_ascii=False,indent=2),encoding='utf-8')
print('special modes:',len(rules),'rules',len(dis),'functions',len(coverage),'BossConfigs;',sum(bool(x['activeStars']) for x in coverage),'serialized active')
